### ISSUE TITLE
Rename all the occurrences of Cause to DAC

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#100]
We decided to use the term DAC for the Causes so lets stick with it.

**Comment by satyavh** [comment]
Where do you still find occurrences of `cause`? I did a code search and we only talk about causes in help text, to explain what a dac is, or what a dac does. Example:

`These campaigns are working hard to solve the cause of this DAC`

**Comment by vsimetka** [comment]
For example here.

<img width="1043" alt="screen shot 2017-10-22 at 21 00 20" src="https://user-images.githubusercontent.com/7974813/31865248-0ad861ae-b76c-11e7-9f99-f000d213d7ad.png">

**Comment by satyavh** [comment]
I don't see the term `Cause` being used. 

I also don't see the term DAC being used because nobody in the world has any idea what that means except us :-)

**Comment by vsimetka** [comment]
You are correct and I am very sorry for that :). I meant Communities.

Well we can for sure use community everywhere, but for many other reasons we have decided to use DAC instead. If the team agrees to go back to Communities lets use only `Communities`. If they want `DACs` then there should be no Communities button or link only DAC. During my testing there were people asking me what is the difference between DAC and Community.

**Comment by satyavh** [comment]
I made a trade-off between the abbreviation DAC, and `Decentralized Altruistic Community` which says it all but hardly fits anywhere in the UI. People that land on the homepage don't know about DACs yet, but they do know what a community is. If that triggers them to go to the next step, then they figure out what kind of community they are creating or donating to: a Decentralized Altruistic Community (wow, whatever it means, sounds amazing ;-)

Once they know the phrase Decentralized Altruistic Community, we teach them the abbreviation DAC. So in the dashboard we refer to it as DAC.

So as you can see, our UI has a build-in customer journey to teach people what a DAC is :-)

**Comment by vsimetka** [comment]
Nonetheless it somehow failed even after I asked them to read our website 😄 . Maybe @krrisis could help here?

**Comment by krrisis** [comment]
I'd agree to keep using 'Communities' everywhere in the menus & buttons. In longform descriptions we can indeed say 'Decentralized Altruistic Communities (DAC)' and that copy still needs to be adapted in some places. At the moment they create a community we also mention the cause around which they unite (=already the case). Confusion during the testing is that the form says 'create a DAC', if you change that to community we're good.
