### ISSUE TITLE
"donating 3% to a DAC" display is weird

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1000]
It's esthetically confusing that theres a sentence in between "Delegating 3% to:" and the DAC i've chosen... the subject should always go directly after the colon. maybe just move the explainer "This milestone is contributing to this DAC on every donation." to below "Giveth DAC"  - or take it away? Not sure the explainer does that much here... it could be a hover over pop up too
![Screen Shot 2019-09-24 at 5 32 49 PM](https://user-images.githubusercontent.com/38163206/65527563-23c45780-def3-11e9-88e4-ef2f17a66eb7.png)

**Comment by GriffGreen** [comment]
OMG! The 1000'th issue!!! 
COOL!

**Comment by aminlatifi** [comment]
@lorelei1 Explain texts are regularly below title for all item on milestone details. If I move the explain text, it would not be consistent with its other siblings. However I changed the explain text to have consistent grammar with other items. I hope it is more user friendly now.

![image](https://user-images.githubusercontent.com/5684607/66823045-4544bc00-ef52-11e9-8394-c4fb05374e6d.png)

**Comment by arbreton** [comment]
I think the best way to solve this is issue is to see if we can work on a hover feature just like mentioned, i'm thinking on a little "i" symbol with a circle right beside each element , if someone wants to read more info, that will be the way to go, what do you think about something like that @aminlatifi ?

**Comment by aminlatifi** [comment]
> I think the best way to solve this is issue is to see if we can work on a hover feature just like mentioned, i'm thinking on a little "i" symbol with a circle right beside each element , if someone wants to read more info, that will be the way to go, what do you think about something like that @aminlatifi ?

@arbreton Sounds good 👍 
In this case we should change it for all items keep consistency in design. 
I changed all detail label like this 
<img width="619" alt="Screen Shot 2019-10-16 at 23 36 56" src="https://user-images.githubusercontent.com/5684607/66955342-ffc9e100-f06e-11e9-862a-9288f4638841.png">
