### ISSUE TITLE
milestone rewrites mid-creation

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1001]
while i'm in the middle of creating a milestone for May, it rewrites all of a sudden with all the data of my milestone for October that i made recently. all data that i was working on is lost, and no it isn't saved with the save milestone function. wtf! this has happened to me at least 3 or 4 times now.

**Comment by arbreton** [comment]
That is way too strange, not good!, will look into this one @lorelei1 , to replicate is it needed to stay the data for a long time?

**Comment by arbreton** [comment]
WIP at #1057
