### ISSUE TITLE
expense milestone won't propose

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1003]
Issue type: **Error**
Something went wrong with the Milestone creation. Is your wallet unlocked?

**TransactionLink:**
undefinedtx/undefined => {
  "name": "Forbidden",
  "message": "Total amount in ether is incorrect",
  "code": 403,
  "className": "forbidden",
  "errors": {}
}

The error message says "Total amount in ether is incorrect" - but the milestone isn't accepting ether its accepting dai. 
<img width="1098" alt="Screen Shot 2019-09-25 at 12 14 48 PM" src="https://user-images.githubusercontent.com/38163206/65632330-43f52480-df8e-11e9-826e-3df989ce0ba0.png">

**Comment by GriffGreen** [comment]
"ether" in this error message should be replaced with a variable that changes based on the currency that was chosen

**Comment by arbreton** [comment]
seems that the token selected wasn't correctly loaded into the proof items, will look into it
