### ISSUE TITLE
Donations not showing under profiles

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1004]
Seen this forever, finally logging it.
Under a profile, you see what amounts have been sent to that person, but amount in 'donations' and 'donated' columns in this list remains zero. 
So, for example [here](https://beta.giveth.io/profile/0x0f278383E746344d613b1980008C2ACfB8070A70) and see screenshot below

![image](https://user-images.githubusercontent.com/6533925/65648344-3a0d0900-e002-11e9-8d30-f769b35d9fe2.png)

**Comment by arbreton** [comment]
Identified the problem, seems to happen only on profile section, data should show up, will look into it
