### ISSUE TITLE
Donated column says 0 after paid out

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1008]
https://beta.giveth.io/profile/0x9073B943c749b85E83390c18cd45Df85dCd2E9Cc

<img width="905" alt="Screen Shot 2019-09-30 at 12 33 01 AM" src="https://user-images.githubusercontent.com/14945613/65858047-f247f380-e319-11e9-85c8-760e9c94345c.png">
Should say the amount that was paid... probably referencing the wrong data

**Comment by arbreton** [comment]
Problem identified! will look into it, seems already noted by @krrisis https://github.com/Giveth/giveth-dapp/issues/1004
