### ISSUE TITLE
Bowen's 150 is stuck

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1013]
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5d3640d51038ff0d20b0b5c3

**Comment by arbreton** [comment]
@bowensanders can you please try again? thank you!

**Comment by bowensanders** [comment]
Thank you for the fix!!

**Comment by arbreton** [comment]
150 need to be re delegated since it got reverted due to the bug, i think @lorelei1 should be able to redelegate the funs from the Unicorn DAC

**Comment by arbreton** [comment]
Bumping, bowen's milestone still needs a reprocessing of the delegation

**Comment by arbreton** [comment]
@bowensanders you have 150 to collect on this milestone !
