### ISSUE TITLE
Any blockchain transaction should ask for confirmation to pay gas

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#102]
Currently user does not know when executing transactions on blockchain. Some users could be surprised where is their ether disappearing.

Related to #101

**Comment by ojones** [comment]
@perissology any ideas on this. I know we want to move to MetaMascara but that's not live quite yet. My feeling is we should hold off on this until we nail down our wallet solution but if there's an easy solution I'm game.

**Comment by vojtechsimetka** [comment]
Not an issue anymore. The donate TXs will prompt metamask, any other TXs are on sidechain.
