### ISSUE TITLE
Critical error! Direct donations don't work for milestones that donate 3% to a DAC

### ISSUE THREAD

**Issue by plur9** [Giveth/giveth-dapp#1027]
we can't get donations for our Fairdrive campaign. This is what we got forwarded from our donors.

*********

Issue type: **Error**
Something went wrong with your donation.

**TransactionLink:**
https://etherscan.io/tx/undefined => {
  "code": -32000,
  "message": "gas required exceeds allowance (9967525) or always failing transaction"
}

**Comment by GriffGreen** [comment]
https://www.youtube.com/watch?v=6b2TNJp2zxs

It approves and sends dai to only the giveth dac... the desired behavior would be 

1 approve for enough to cover both donations. 
1 tx to fund the milestone
1 tx to fund the DAC

**Comment by arbreton** [comment]
Seems to be milestone specific, is not happening on other milestones

**Comment by GriffGreen** [comment]
#1229

**Comment by aminlatifi** [comment]
https://github.com/Giveth/giveth-dapp/pull/1236 should be fixed.
