### ISSUE TITLE
Atomic transactions for feathers for preventing duplicates and pending items

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#1029]

**Comment by aminlatifi** [comment]
It needs transaction capability of mongodb. Mongoose (the library is used to connect to mongodb) needs to be upgraded. It related to #839 . Upgrading mongoose breaks some functionalities and it seems we need to upgrade feathersjs libraries too.

**Comment by papermache** [comment]
@aminlatifi Updates?

**Comment by aminlatifi** [comment]
After long time working on feathers, I believe we don't need atomic transaction capability with current design. Because nodejs is single threaded, and don't have any service worker
