### ISSUE TITLE
Mail notifications no longer arriving 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1037]
We just noticed mail notifications for the DApp no longer work... :/
@griffgreen filled a number of Milestones but neither @Jeff-Emmett or I received any notification of this.

**Comment by arbreton** [comment]
Seems that the mailer service was down / stuck / crashed, restarted the service it should be working now!

**Comment by GriffGreen** [comment]
@geleeroyale  is working on this? We should follow up with him

**Comment by geleeroyale** [comment]
Mongo database needs to be updated & upgraded to point to an atlas mongo db account. The service got switched over to use a different provider for sending the mails. The newest change in config points to mailjet. **Still trying to find out who from our DApp team is managing the mailjet service.** Worst case we register a new account with mailjet or similar provider and set the config on the dappmailer accordingly.

**Comment by GriffGreen** [comment]
@arbreton whats the status on this one?
