### ISSUE TITLE
Error delegating in DECENTRAL Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1052]
Issue type: **Error**
There was a problem with the delegation transaction.

**TransactionLink:**
https://rinkeby.etherscan.io/tx/undefined

Delegating the full amount of what remains from Natalia's donation to David's Milestone and it's stuck, throws error then when I go back into her donation it says it's 'delegating' -- 

![image](https://user-images.githubusercontent.com/39466970/68691885-1feba380-053a-11ea-8c99-c300e7c37935.png)

I have successfully delegated other donations to this Milestone.

**Comment by arbreton** [comment]
Good morning @Danibelle, I think i may know what the problem could be

What would be the donation that you are trying to delegate and from what donor is it so i can look it up? thank you

**Comment by Danibelle** [comment]
Whoops just getting back and realizing I don't have much time left to work with you @arbreton !

Here is the user id of the donation, the one we're working with is to [DECENTRAL](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33): https://beta.giveth.io/profile/0x5f2d0eC2483FfAF6496393115A26099F44d38681
