### ISSUE TITLE
Draft functionality redesign

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1057]
Current implementation of Draft functionality is not clear and not working properly, at least for Milestone view. 
It saves temporary values in  browser memory to load latter, but `Save Draft` button is not working as expected.
I imagine a `Draft` functionality which is integrated with feather/mongo, and works cross browser.

**Comment by papermache** [comment]
@aminlatifi check server side loading speed.

**Comment by aminlatifi** [comment]
> @aminlatifi check server side loading speed.

@papermache It seems OK now... what was the problem?
