### ISSUE TITLE
Giveth 2.0 Unicef Grant Overview 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1058]
WOOOO HOOOOO! 

We made it to the next step! We have 1 week to fill out a grant application to get 100k to fund Alibre to build Giveth 2.0 and include a last mile solution in Mexico :-D

The pilot project would be with Castro Limon. https://fundacioncastrolimon.org/ 

http://alibre.giveth.io/ links to our blog post from March talking about this 

We have this tight youtube video that got us past the first round: 
https://www.youtube.com/watch?v=JCLF5_Ib69U&feature=youtu.be

We will be putting some issues up here but this is going to be a big priority for the week!

**Comment by mroberts10** [comment]
Congrats!! and wow great video!  So professional.  Can we share this video?  I see that its on youtube.

**Comment by GriffGreen** [comment]
@mroberts10 absolutely!

**Comment by GriffGreen** [comment]
Ask Sergio for master files 
Add revenue streams to video
