### ISSUE TITLE
Can't edit milestone

### ISSUE THREAD

**Issue by gentlemandonadams** [Giveth/giveth-dapp#1060]
I tried to update a milestone I'd created (https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d89082aad3696263686d08d) to reflect the amount of hours I'd worked during the time period covered by that milestone, but when I clicked the edit button, I received the following error message:

"Oh no!
You are not whitelisted"

**Comment by arbreton** [comment]
@gentlemandonadams sorry for the inconvinience, can you try again now? seems to be a bug related to project owners

**Comment by gentlemandonadams** [comment]
Noting now that you (arbreton) DID fix this the same day I reported it.  Unfortunately, I'm having the exact same problem now

**Comment by gentlemandonadams** [comment]
I did just notice that I was able to edit a milestone that I'd submitted but which had not yet been accepted (adding this detail in case it helps the troubleshooting process...)
