### ISSUE TITLE
Sort dated items from newest to oldest (re: donation lists, etc)

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#1061]
It should be somewhat trivial to fix this by adding a date sort to the feathers queries, but the way that donations are displayed (and perhaps other items) there does not appear to be any order to them that makes sense.

Sorting them from newest to oldest (or the reverse) would make the donations lists easier to go through..

**Comment by arbreton** [comment]
TBD feature request conflicting with current leaderboard implementation
