### ISSUE TITLE
Urgent feature request! Notify users that only SAI works, no longer DAI

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1067]
We discovered today that the Giveth DApp no longer accepts Dai donations! Of course, because Dai is no longer Dai. If it can slip by us, then it certainly can confuse our donors. Let's put a temporary banner or something saying that if you're having problems with your donation, it's likely because only Sai can be donated, and maybe a link to how to change your Dai into Sai.

**Comment by GriffGreen** [comment]
WOW! Quick work! still an issue tho: 
<img width="409" alt="Screen Shot 2019-11-29 at 1 50 17 AM" src="https://user-images.githubusercontent.com/14945613/69827625-bf9f7600-124a-11ea-8bf7-a167ccfbbf8f.png">
<img width="240" alt="Screen Shot 2019-11-29 at 1 50 03 AM" src="https://user-images.githubusercontent.com/14945613/69827626-bf9f7600-124a-11ea-8c70-906b40f4b67e.png">

No SAI option in the conversion... only DAI... not sure what is going on here...

**Comment by arbreton** [comment]
Right now the renaming to SAI is reflected 👍 , now investigating naming on past records and New DAI support

**Comment by lorelei1** [comment]
this helps for milestone creators, but for someone donating it doesn't help their confusion. I still think we need a banner message saying generally "DAI not working? It's because Giveth still runs on Single Collateral Dai (now SAI) and your DAI may be a different token!" or something to that effect

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956 funny one

**Comment by aminlatifi** [comment]
> https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956 funny one

It's related to 30K missing!

**Comment by GriffGreen** [comment]
yeah and the 30k missing is still labeled DAI where as the real donation is DAI!

**Comment by arbreton** [comment]
We are working on big migrations script required for functionality to properly work also we might need to do some smart contract function calling

We are still collecting insight
