### ISSUE TITLE
New users don't discover Campaigns

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#107]
Campaigns are really hidden for new users. We should try and make it more clear that the DApp has both DACs and Campaigns by putting them in the same list or by adding a clear switch.

**Comment by satyavh** [comment]
First this is an assumption, because we don't have users yet. We should measure whether they can find campaigns or not.

For now, there are 2 clear menu items, not sure if a switch is a good UI pattern. 

Moving this to icebox for now

**Comment by vsimetka** [comment]
Not an assumption. This has been reported by @adriamb, @youngyeezy, @maomao who were testing the app. I can provide the video recordings if needed. But I do agree it is a very tricky to solve from UI perspective.

**Comment by vojtechsimetka** [comment]
Duplicate of #476
