### ISSUE TITLE
Eth denomination in notification email is confusing

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1072]
The e-9 at the end of the number looks super weird, why is it there?
<img width="472" alt="Screen Shot 2019-12-03 at 4 01 47 PM" src="https://user-images.githubusercontent.com/38163206/70036054-941fe100-15e6-11ea-8f64-678153de7c49.png">

**Comment by GriffGreen** [comment]
because i sent a very small donation to you... sorry for not mentioning
