### ISSUE TITLE
text error in milestone update

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1073]
Lose the "and" 
<img width="349" alt="Screen Shot 2019-12-03 at 6 13 19 PM" src="https://user-images.githubusercontent.com/38163206/70046436-a3a82580-15f8-11ea-8703-2a1c9f4022b3.png">

**Comment by arbreton** [comment]
worth checking @aminlatifi

**Comment by aminlatifi** [comment]
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5d8bbdddad3696263686d13f
It had been fixed.
![image](https://user-images.githubusercontent.com/5684607/82219435-865edd80-9932-11ea-93fc-4f758547410c.png)
