### ISSUE TITLE
Hack this morning didnt work? 8300 SAI in limbo?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1075]
You gave me access to that locked Sai... but then weirdness occurred... we should try again

No collect button for jeff? maybe the donations didnt work?
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5dad62efd25d7f4a295e3eef

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5daef7bb0fbace4ce8d30ef7

and 

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5db1bb900fbace4ce8d30fd5

too

**Comment by arbreton** [comment]
The bug got corrected
