### ISSUE TITLE
Can't Donate if the Allowance is non-zero, need to fix the 3 transaction scheme

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1078]
<img width="1041" alt="Screen Shot 2019-12-07 at 12 46 30 AM" src="https://user-images.githubusercontent.com/14945613/70343965-2516e680-188b-11ea-9e92-9d0227b10e85.png">
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e
Trying to donate SAI but can only select DAI and it errors out
<img width="1251" alt="Screen Shot 2019-12-07 at 12 48 24 AM" src="https://user-images.githubusercontent.com/14945613/70344032-4f68a400-188b-11ea-842b-e3e1cc4af185.png">

**Comment by arbreton** [comment]
Seems to be working now, just tested it

**Comment by arbreton** [comment]
If it still not working, browser cache or metamask reset might be needed

**Comment by GriffGreen** [comment]
Cool for sure we need to fix the text too tho!

**Comment by GriffGreen** [comment]
WOW!! SO FUCKING WEIRD! 

Just my 0x83939 "Santa" address doesn't work for DAI... i can use other addresses without issue :-P 

It doesn't work for me... reset metamask, cleared browser cache... even tried a private window 
<img width="1298" alt="Screen Shot 2019-12-12 at 9 21 37 PM" src="https://user-images.githubusercontent.com/14945613/70721840-e10f6000-1d28-11ea-8cae-c2f19f551831.png">

Here is the error message:


Issue type: **Error**
Something went wrong with your donation.

**TransactionLink:**
https://etherscan.io/tx/undefined => {
  "code": -32000,
  "message": "gas required exceeds allowance (9899720) or always failing transaction"
}

not sure how just my address could be having the issue... its really weird

**Comment by GriffGreen** [comment]
ok i figured it out... there is something wrong with the 3 transaction game.. I have an allowance of 900 which isnt enough to make the donation....

<img width="607" alt="Screen Shot 2019-12-16 at 10 40 29 PM" src="https://user-images.githubusercontent.com/14945613/70945313-34e5b600-2055-11ea-9c88-4eb033e945ef.png">

The expected behavior was that it would make me do 3 txs, the first would send my allowance to 0, then the normal approve and donate calls...

so i am setting my allowance to 0 manually using etherscan
<img width="1085" alt="Screen Shot 2019-12-16 at 10 39 33 PM" src="https://user-images.githubusercontent.com/14945613/70945565-c48b6480-2055-11ea-8536-c4c04471fd88.png">

And now it works!

**Comment by GriffGreen** [comment]
there is something wrong in the formation of this transaction

**Comment by GriffGreen** [comment]
The plot thickens!!! Are the behaviors just switched? 

This is the behavior i see

If Allowance = 0, then do 2 transactions
If Allowance > amount donating, then do 3 transactions
If Allowance = amount donating, then do 1 transaction
If Allowance < amount donating, then break 

WHAT IT SHOULD BE:

If Allowance = 0, then do 2 transactions
If Allowance > amount donating, then do 1 transaction
If Allowance = amount donating, then do 1 transaction
If Allowance < amount donating, then do 3 transactions




SO now if i have too much allowance (like i have an allowance of 1600 SAI and only want to donate 95) it wants to move my allowance down to 0 and then raise it :-( 

This sucks... cause I actually want to skip a few transactions for multiple donations... so i am going to go to etherscan to do it :-(
