### ISSUE TITLE
Page refreshes when filling in forms

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#108]
From time to to time, the page refreshes while filling in a form which erases the content. I did not figure out what can be the trigger.

**Comment by satyavh** [comment]
I haven't experienced this problem. Can you create a reproduction scenario?

**Comment by vsimetka** [comment]
Yes but not always. I believe someone needs to change the system while you are in form or you need to have a pending transaction which refreshes the page for you as the state changed. Anyways the forms should remain filled until you click on save so that you don't lose data even if you go back in history.

**Comment by satyavh** [comment]
Sounds like our real-time feathers implementation is causing issues. This is going to be hard to solve.

**Comment by satyavh** [comment]
I hate to say it, but Redux might fix this :-|

**Comment by vsimetka** [comment]
I would be down for Redux TBH. Also I don't know the full impact, it probably is not an issue now, but if there are several transactions/minute, successfully filling in a form could be a nice challenge :).

**Comment by satyavh** [comment]
I have fixed this
