### ISSUE TITLE
Compatibility with Metamask Q1 2020 Changes

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1082]
Metamask inpage provider will change Q1 2020 and Dapp should be ready for.
These changes are reported [here](https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a).

**Comment by aminlatifi** [comment]
> Metamask inpage provider will change Q1 2020 and Dapp should be ready for.
> These changes are reported [here](https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a).

To make the code compatible with changes, we should use [new API](https://github.com/MetaMask/metamask-docs/blob/new-provider/03_API_Reference/01_Ethereum_Provider.md#new-api) which will be available On December 16, 2019. The function specifically we depends on is `send` which will be replace by update.
@bowensanders I tried to make code compatible but it seems we should wait till new api is released.

**Comment by aminlatifi** [comment]
@bowensanders @GriffGreen Is there any other wallet to support except metamask? I am afraid updates regarding this issue stops other wallet from working with dapp.

**Comment by GriffGreen** [comment]
nope

**Comment by aminlatifi** [comment]
Tested again... API not added yet!

**Comment by GriffGreen** [comment]
still not ready yet

**Comment by aminlatifi** [comment]
https://github.com/MetaMask/metamask-extension/issues/8077 is the issue related to new API, it's still open!

**Comment by horus2021** [comment]
@aminlatifi I have played wtih Metamask on develop. It works. Great Job!

**Comment by GriffGreen** [comment]
#1397
