### ISSUE TITLE
Delegate funds doesn't work 

### ISSUE THREAD

**Issue by mmohorko** [Giveth/giveth-dapp#1083]
I am trying to delegate funds from the FDS DAC to the Swarm Ops campaign -> milestone 1 but I can't do this. I tried 2 options: 

1. At the campaign page, I selected "Delegate funds here" and choose DAI. The pop-up window refreshes but it doesn't work. See the screenshot. I can't do anything. 
![Screenshot 2019-12-12 at 14 36 23](https://user-images.githubusercontent.com/45455085/70717549-ddf77e00-1cee-11ea-8ee9-2b98fd760c60.png)

2. I went to the "My delegations page" and tried to delegate funds from there. At first (i thought it worked, but now I am getting the "proposed delegation" status. I don't know what that means. 
![Screenshot 2019-12-12 at 14 41 12](https://user-images.githubusercontent.com/45455085/70717807-6544f180-1cef-11ea-8761-b34dfdcb32cc.png)

So I tried to do it one more time, only this time it didn't work either because when I select the campaign (Swarm Ops) it says that there is no milestone to delegate to. See the screenshot. 
![Screenshot 2019-12-12 at 14 42 53](https://user-images.githubusercontent.com/45455085/70717734-4181ab80-1cef-11ea-9e0b-79e74447b38d.png)

What do you suggest I should do?

**Comment by aminlatifi** [comment]
Regarding 1 approach are you sure at the time of trying FDS DAC had non zero balance of DAI? If its balance of DAI is zero, the window you were seeing was what should be

Approach 2 is normal, because donator (here santa) should confirm you delegation. So its status `proposed delegation` is correct and it waits for santa to confirm.

At the last try you aimed to delegate from an `ETH` delegation. In this case you can just delegate to a milestone which its token is `ETH`.

@mmohorko If you have any question please let me know.

**Comment by mmohorko** [comment]
1. No the balance was not zero. 
<img width="517" alt="Screenshot 2019-12-18 at 10 55 15" src="https://user-images.githubusercontent.com/45455085/71076101-6fe70700-2185-11ea-856a-317c4778abfd.png">

2. I am not sure that I understand why "Santa" needs to confirm that delegation? Isn't that the money he donated to the DAC? Did Santa get a notification that he needs to confirm something? 

3. Ok I see. I didn't think of that. Thank you.

**Comment by aminlatifi** [comment]
> 1. No the balance was not zero.
> 
> <img alt="Screenshot 2019-12-18 at 10 55 15" width="517" src="https://user-images.githubusercontent.com/45455085/71076101-6fe70700-2185-11ea-856a-317c4778abfd.png">
> 
> 1. I am not sure that I understand why "Santa" needs to confirm that delegation? Isn't that the money he donated to the DAC? Did Santa get a notification that he needs to confirm something?
> 2. Ok I see. I didn't think of that. Thank you.

1.  Yes it has positive balance of DAI now. I meant at the time of trying it may had zero balance.
2. When user donated to dac, he should confirm when it's delegated. Donating to dac has different procedure than donating to campaign or milestone.
