### ISSUE TITLE
Error on Collect from Partially Funded Milestone (no reviewer)

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1084]
Testing some standard functionalities and found an error on 'Collect' from this [Milestone](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5dabb2f9d25d7f4a295e3dd5):

![image](https://user-images.githubusercontent.com/39466970/70724413-91994780-1cc8-11ea-81a6-1827775c0158.png)

Press Collect:
![image](https://user-images.githubusercontent.com/39466970/70724476-ab3a8f00-1cc8-11ea-9d2b-dd602eb3a072.png)

Click "yes, withdraw":
![image](https://user-images.githubusercontent.com/39466970/70724513-bf7e8c00-1cc8-11ea-89b3-973f9e9bb2c3.png)

Same outcome when selecting 'Collect' from My Milestones:
![image](https://user-images.githubusercontent.com/39466970/70724614-e50b9580-1cc8-11ea-8294-41761f17b296.png)

**Comment by arbreton** [comment]
Hello @Danibelle , i will need to take a look at your browser console, seems to be an specific case

Here are the steps
<img width="756" alt="Screen Shot 2019-12-12 at 10 36 55 AM" src="https://user-images.githubusercontent.com/12836187/70739370-8267c900-1ccb-11ea-8e23-44782371d788.png">

Keep me posted!

**Comment by gentlemandonadams** [comment]
I'm experiencing the same issue with this milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d7fd9dfad3696263686cc1b

**Comment by GriffGreen** [comment]
Lorelei might be as well

**Comment by Danibelle** [comment]
Hi @arbreton - here is a screenshot of the console with error:

![image](https://user-images.githubusercontent.com/39466970/71592221-6ce10480-2afd-11ea-94f2-33d799462905.png)

**Comment by Danibelle** [comment]
![image](https://user-images.githubusercontent.com/39466970/71606452-e51bea00-2b3e-11ea-95ee-2215dfd967ce.png)

**Comment by Danibelle** [comment]
Still errors, sorry!   Here's how it looks now:
![image](https://user-images.githubusercontent.com/39466970/71647718-e5e08780-2cc8-11ea-9dd2-0bc7ccbb02ef.png)

**Comment by Danibelle** [comment]
Sadly still no.
![image](https://user-images.githubusercontent.com/39466970/71859669-bca36b00-30bd-11ea-8248-de59164e23bc.png)

**Comment by gentlemandonadams** [comment]
Just got the error message on this milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956

**Comment by aminlatifi** [comment]
> Just got the error message on this milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956

This milestone should have been collected. The frontend problem will be fixed, however it is cleaned now.

**Comment by gentlemandonadams** [comment]
Just tried it and it worked, thanks!

**Comment by aminlatifi** [comment]
> Just tried it and it worked, thanks!
You collected again?

**Comment by gentlemandonadams** [comment]
@

> > Just got the error message on this milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956
> 
> This milestone should have been collected. The frontend problem will be fixed, however it is cleaned now.

You mean I already collected it?  Or I should be able to collect it now?  I just tried again and wasn't able (pretty sure I never successfully collected this milestone)

**Comment by aminlatifi** [comment]
> @
> 
> > > Just got the error message on this milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956
> > 
> > 
> > This milestone should have been collected. The frontend problem will be fixed, however it is cleaned now.
> 
> You mean I already collected it? Or I should be able to collect it now? I just tried again and wasn't able (pretty sure I never successfully collected this milestone)

Showing error on frontend does not necessary mean that collect action is not done on blockchain side! 
The original cause of seeing error message is that data is not synced with blockchain and we are working on that.
