### ISSUE TITLE
Normalizing token entity 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1089]
In current implementation token entity is saved entirely every place across the objects (donation, milestone, ....)
This implementation makes hard to rename a token symbol when needed, specially for the case of DAI/SAI migration.

In new implementation just token address should be saved every where needed and token specification should be stored only once in separate db collection. To design collection should consider symbol name for both presentation and conversion rate service. Because cryptocompare uses DAI name for SAI and probably MCD for new DAI.

@bowensanders I appreciate if you add anything you think is missed.

**Comment by papermache** [comment]
@aminlatifi

**Comment by aminlatifi** [comment]
It's big refactoring.... it would be nice to do it however but time consuming

**Comment by GriffGreen** [comment]
Technical debt bankruptcy?

**Comment by aminlatifi** [comment]
> Technical debt bankruptcy

It's not complicated and easy to implement... but scattered all over the application and needs extensive testing to be sure everything is OK after.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 

We should create token coolection that should've some records like these:

```
 {
      "name": "ETH",
      "address": "0x0",
      "foreignAddress": "0xe3ee055346a9EfaF4AA2900847dEb04de0195398",
      "symbol": "ETH",
      "decimals": 6
    },
    {
      "name": "DAI",
      "address": "0x6b175474e89094c44da98b954eedeac495271d0f",
      "foreignAddress": "0x05A075B296995AdCaEC7c1dE0E52271a4Cf6DEb8",
      "symbol": "DAI",
      "decimals": 3
    },
    {
      "name": "PAN",
      "address": "0xd56dac73a4d6766464b38ec6d91eb45ce7457c44",
      "foreignAddress": "0x0aaf4acccddb40cdb6a1df3cfbc7944aa5effcc6",
      "symbol": "PAN",
      "coingeckoId": "panvala-pan",
      "decimals": 2
    },
    {
      "name": "WBTC",
      "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
      "foreignAddress": "0x6d03800013c591611a6ee597191d9f608b833510",
      "symbol": "WBTC",
      "decimals": "8",
      "rateEqSymbol": "BTC"
    },
    {
      "name": "USDC",
      "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
      "foreignAddress": "0xf14eCE303f190A70A2CF7C7011F75bDa658aD6EF",
      "symbol": "USDC",
      "decimals": "3"
    },
    {
      "name": "ANT",
      "address": "0x960b236a07cf122663c4303350609a66a7b288c0",
      "foreignAddress": "0x7283b97f7546ba8eff68167cab2da526e7d7f88a",
      "symbol": "ANT",
      "decimals": "3"
    }
```
Am I right?

**Comment by aminlatifi** [comment]
> @aminlatifi
> 
> We should create token coolection that should've some records like these:
> 
> ```
>  {
>       "name": "ETH",
>       "address": "0x0",
>       "foreignAddress": "0xe3ee055346a9EfaF4AA2900847dEb04de0195398",
>       "symbol": "ETH",
>       "decimals": 6
>     },
>     {
>       "name": "DAI",
>       "address": "0x6b175474e89094c44da98b954eedeac495271d0f",
>       "foreignAddress": "0x05A075B296995AdCaEC7c1dE0E52271a4Cf6DEb8",
>       "symbol": "DAI",
>       "decimals": 3
>     },
>     {
>       "name": "PAN",
>       "address": "0xd56dac73a4d6766464b38ec6d91eb45ce7457c44",
>       "foreignAddress": "0x0aaf4acccddb40cdb6a1df3cfbc7944aa5effcc6",
>       "symbol": "PAN",
>       "coingeckoId": "panvala-pan",
>       "decimals": 2
>     },
>     {
>       "name": "WBTC",
>       "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
>       "foreignAddress": "0x6d03800013c591611a6ee597191d9f608b833510",
>       "symbol": "WBTC",
>       "decimals": "8",
>       "rateEqSymbol": "BTC"
>     },
>     {
>       "name": "USDC",
>       "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
>       "foreignAddress": "0xf14eCE303f190A70A2CF7C7011F75bDa658aD6EF",
>       "symbol": "USDC",
>       "decimals": "3"
>     },
>     {
>       "name": "ANT",
>       "address": "0x960b236a07cf122663c4303350609a66a7b288c0",
>       "foreignAddress": "0x7283b97f7546ba8eff68167cab2da526e7d7f88a",
>       "symbol": "ANT",
>       "decimals": "3"
>     }
> ```
> 
> And after that obviously the values should read from there, am I right?

We have the token whitelist already, so let's use it so far
