### ISSUE TITLE
Home page visual and content issues

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#109]
Most of this amazing feedback is from @krrisis who agreed to help with the content. Many other testers had similar remarks though.

Top bar
- [x] The grey header block is not very inspiring, even depressing. 
- [ ] Slogan is a bit naive/generic here - let's replace it at least for now by 'Building the Future of Giving'
- [ ] I am confused about 'Create a community' and 'Start a Campaign' incl the links under 'dashboard', I don't know what they mean, I'm missing a help button or at least a link to the wiki
- [ ] Join Giveth slack should not be on top here, unrelated
- [ ] First button should be to Donate - to a campaign or a community, current top buttons are secondary, focus should be on the Giver (!)

<img width="1170" alt="screen shot 2017-10-19 at 00 21 48" src="https://user-images.githubusercontent.com/7974813/31745553-87696026-b463-11e7-902f-ca716401e9b4.png">

GIVER (donate button and adapted look&feel) should be front & center 
- proposal: first have two buttons:
    1) Are you Giver?
    2) Are you a Maker?
- post click action
    1) a sentence that says sth like 'Read up on any of these DACs or Campaigns and donate directly' -- show both mixed with filter to select (Givers should see both) Donate directly to one of the campaigns or communities 
    2) Show current two buttons (without 'join giveth :) )

COMMUNITIES
- I'd write DAC & Campaign everywhere with a capital now to create consistency (//wiki & medium post) ---> all pages
- Every community has a name at the top, unclear to me who this is,even after I click on that name. It should not be the focus

<img width="1134" alt="screen shot 2017-10-19 at 00 28 29" src="https://user-images.githubusercontent.com/7974813/31745773-84204a78-b464-11e7-9936-d3764396616b.png">

**Comment by satyavh** [comment]
This is great feedback and it will result in hours of discussion in Cancun :-)

**Comment by krrisis** [comment]
I think you can close this one as most is covered, only really important thing - to me - to still add for Toronto is more focus on our GIVER, who should be front & center and is now not even there. 

I can create a new issue but maybe we can do this together & finetune maybe in barcelona @vojtechsimetka @satyavh @GriffGreen ? I think a 'simple' frontend solution could be possible?
Proposal:

- delete 'join giveth' (should be in the top nav, see our other pages such as donate, join, fame etc)
- replace by 'Give'
-- when you click this a small dropdown/textblock appears that describes how you can donate and navigate around (can write this)
--- I'd put the 'Give' button literally above the Create Campaign & Create Community button - First Givers, then Makers ;-)

**Comment by horus2021** [comment]
This is GUI. It is not priority at this stage,
