### ISSUE TITLE
Can't collect an old milestone with new delegations

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1091]
For both https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5bb2758fae4f6e3373e4faee
and
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5bb26f5cae4f6e3373e4fae5
 Can't mark it complete?

**Comment by aminlatifi** [comment]
@GriffGreen Their status are changed to completed manually.

**Comment by aminlatifi** [comment]
I tested both with changing recipientAddress with mine temporarily. For both `Mark Complete` button appeared. 
@GriffGreen Do you use account which is set as recipient? Because you should be recipient or milestone owner to see the button.

**Comment by GriffGreen** [comment]
thats weird... yeah it works now... maybe i was just tired before... wish i had a screen shot here to prove i wasnt crazy :-D
