### ISSUE TITLE
my-campaign view should show "pending" campaign

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#11]
when a user creates a campaign, there is a wait until the tx is mined. We should show these "pending" campaigns in the my-campaigns view.

a cause is "pending" if cause.projectId === 0

**Comment by satyavh** [comment]
You mean?
`pendingCampaigns: resp.data.filter(campaign => !(campaign.projectId))`

**Comment by perissology** [comment]
Yep. I filtered it already, but didn't really show them. Only the number of pending dacs.

```
                  {pendingCauses.length > 0 &&
                  <p>{pendingCauses.length} pending dacs</p>
                  }
```
