### ISSUE TITLE
It said it was unable to update the amount in feathers after delegating 5 eth to a milestone

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1102]
I was delegating 5 eth to a milestone and it said it couldnt update the amounts correctly... this was for the ETH on Commons Stack Iteration 0

Issue type: **Error**
Unable to update the donation in feathers

**Name:**
Timeout of 30000ms exceeded calling donations::create

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

Error: Timeout of 30000ms exceeded calling donations::create
    at https://d33wubrfki0l68.cloudfront.net/js/e981d3d277c9a4dc3f1a28a3b6f44e9eb770e020/static/js/main.d1981354.js:1:2195393
</details>

**Comment by aminlatifi** [comment]
@griff Does the milestone get the donation? 
Can you share milestone link here? I found one with 5 eth capacity, but I am not sure it is the one you delegated to.

**Comment by aminlatifi** [comment]
> @griff Did the milestone get the donation?
> Can you share milestone link here? I found one with 5 eth capacity, but I am not sure it is the one you delegated to.

That was the one :)
Hopefully it seems everything is OK on blockchain and bridge.
