### ISSUE TITLE
Giveth-dapp seems to assume that transactions are guaranteed to be executed

### ISSUE THREAD

**Issue by Troublor** [Giveth/giveth-dapp#1103]
Transactions on Ethereum are not guaranteed to be executed and included in block from my perspective. However, when investigating source code of giveth-dapp, I find some evidence that it seems to assume transactions are guaranteed to be executed. One example is [here](https://github.com/Giveth/giveth-dapp/blob/37f3316b84606b020b507d60de25ab893ca090da/src/services/DonationService.jsx#L591) when trying to refund donations. 

```js
return network.liquidPledging
          .withdraw(donation.canceledPledgeId || donation.pledgeId, _amountRemainingInWei, {
            from: address,
            $extraGas: extraGas(),
          })
          .once('transactionHash', hash => {
            txHash = hash;
            updateExistingDonation(donation, _amountRemainingInWei);

            const newDonation = {
              ...
            };

            feathersClient
              .service('/donations')
              .create(newDonation)
              .then(() => onCreated(`${etherScanUrl}tx/${txHash}`))
              .catch(err => {
                ErrorPopup('Something went wrong while revoking your donation.', err);
                onError(err);
              });
          });
```

`updateExistingDonation` is called immediately after it gets transactionHash, but at this time transaction hasn't been executed. This kind of situation should be handled to improve robustness.

**Comment by aminlatifi** [comment]
Yes, it's just depend on transaction hash which is not a guarantee of a confirmed transaction. We are working on a db/blockchain conflict resolve resolution.

**Comment by Troublor** [comment]
@aminlatifi I would like to also mention that even after the transaction is mined, it can still be "cancelled or reverted" due to re-org. I checked the source code in feathers-giveth, it seems like feathers-giveth only handles removed events on Ethereum by removing it from db. But it does not consider to undo the possible actions taken after the corresponding transactions on dapp side. This also might be a problem I think.

**Comment by aminlatifi** [comment]
> @aminlatifi I would like to also mention that even after the transaction is mined, it can still be "cancelled or reverted" due to re-org. I checked the source code in feathers-giveth, it seems like feathers-giveth only handles removed events on Ethereum by removing it from db. But it does not consider to undo the possible actions taken after the corresponding transactions on dapp side. This also might be a problem I think.

Thank you. 
Having two backend and syncing them is a hard task. Feather process transfer events too and keeps event pending till required confirmation blocks are mined.
Syncing two backend (db and blockchain) is declicate and complex job, and we hope is solved soon.

**Comment by GriffGreen** [comment]
@Troublor Thx so much for diving into this!

We now have a simulation script that is a major fix for this issue... In the end, if you are trying to fork our code, I would recommend building from scratch, as we built this in 2017 and there are much better tools availible for solving the problems we ran into

If you are looking into this, we would love to team up!! We want to rebuild from scratch! Please reach out!!!

Much love,
Griff

**Comment by Troublor** [comment]
@GriffGreen Thanks for your invitation. I am a PhD student focusing on blockchain-oriented software engineering. This issue is one of the findings of my recent research work. I am very interested in the Giveth Project but currently I'm afraid I don't have enough time and effort to take part in the development of Giveth, sorry. Nevertheless, I will keep following up with Giveth project and post issues here if I have more interesting findings.
