### ISSUE TITLE
Odd things going on in my milestones

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#1111]
Hey guys,

Just thought I'd report some oddball things in my milestones view.

![image](https://user-images.githubusercontent.com/46964190/72185384-adbfff80-33c0-11ea-9f9b-b8d78d1554d1.png)

I believe the first milestone "Fall Asia Milestones" has been paid out already, not sure why it's still there: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d856399ad3696263686cd7c

Third milestone has been sitting in "paying" status for weeks now, I am just the verifier: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5db1bb900fbace4ce8d30fd5

Fourth milestone has been donated to, but for some reason I can't collect:  https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5dad62efd25d7f4a295e3eef

Thanks for the help, team!

Jeff

**Comment by aminlatifi** [comment]
All the milestones data are synced with blockchain. Thanks for reporting. We are working on an automated syncing procedure.
About the fourth milestone, it has already collected.
