### ISSUE TITLE
Fairdrive campaign - not working

### ISSUE THREAD

**Issue by mmohorko** [Giveth/giveth-dapp#1114]
If you click the Fairdive campaign (https://beta.giveth.io/campaigns/5d9466be0be6c23fee64fbda) it doesn't open the campaign landing page but gets redirected back to the Giveth homepage. 

This does not happen if I am logged in with MetaMasc. Then it works normally. 

Can you please check what is going on?  Thanks!

**Comment by lorelei1** [comment]
I made a video showing this and posted it in riot

**Comment by aminlatifi** [comment]
The problem is related to CreateDonationAddressButton component added for fund forwarder capability. I commented out that part of code since fund forwarder is not 100% working feather yet.
@ascariandrea Please don't forget to fix this bug before releasing fund forwarder.

**Comment by mmohorko** [comment]
Thanks. It works now.
