### ISSUE TITLE
Input forms URL not valid without protocol (https://, http://)

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#112]
<img width="813" alt="screen shot 2017-10-19 at 00 37 58" src="https://user-images.githubusercontent.com/7974813/31746062-c9d87cb0-b465-11e7-92ec-f3fe4a2eb5c1.png">

**Comment by satyavh** [comment]
That's right, your example input is not a valid url. I don't think we should guess the url

**Comment by vsimetka** [comment]
Last time I checked scheme was not a mandatory part of URL and defaults to http if not provided https://url.spec.whatwg.org/#urls . If we require scheme to be part of inputed URL it should be explicitly written in the help below.
