### ISSUE TITLE
Update donation counter to be accurate

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1121]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d5a5795420f06212039fdb5

i didnt donate 500k to this milestone i promise

**Comment by aminlatifi** [comment]
> https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d5a5795420f06212039fdb5
> 
> i didnt donate 500k to this milestone i promise

This [user](https://beta.giveth.io/profile/0x567355f84d44a982629d8675ab4aadbb92dbfd54) (which is registered with your name) has delegated your donation to  `Commons Stack - Iteration 0` to this milestone.
This is the transaction [link](https://rinkeby.etherscan.io/tx/0xd8753fe1a6217e1b7040c571f26a5becbfb7ba41fadb337c4eb241e0c61dd8c4)

**Comment by GriffGreen** [comment]
Donation counter is not correct
Everytime a donation occurs it updates the donation counter
Because the donation wasn't correct, we need to re calculate these amounts
How much exists inside

**Comment by aminlatifi** [comment]
They should be all accurate now.
