### ISSUE TITLE
Able to cancel a Milestone that is already paid

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1124]
I cancelled [this Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5df00afa71e84069aad0a228) that I could not edit and that was filled (see issue #1034 ) 
As I still saw that Milestone in active later on I cancelled this one too, unfortunately this was NOT an active Milestone, this was an already PAID Milestone, that for some reason showed up under active. 
So this is [this Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e1c64d66664fc2495909771). It now shows up under cancelled, which is incorrect, as it should be under paid, and should not be under cancelled. On top of it, it says that 6200 DAI was donated to it, where only 3100 was donated to it.

**Comment by arbreton** [comment]
#1136 fixes cancel and edit when not allowed (when milestone has received a donation)

**Comment by krrisis** [comment]
Great news! Will you also be able to fix the above in the frontend so our accounting is correct again? thanks!

**Comment by aminlatifi** [comment]
> #1136 fixes cancel and edit when not allowed (when milestone has received a donation)

This change is reverted.
@krrisis I updated [this milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e1c64d66664fc2495909771) status to `Paid` on DB (front-end shows that). Whie the `CancelProject` event is emitted, it wouldn't affect anything because money is collected before.
