### ISSUE TITLE
How much money is in the Commons Stack Campaign?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1125]
This is a real issue for me.. :-( I don't understand how much money we have in our campaign, so its hard to do the budget... can you guys help!! :-D

**Comment by aminlatifi** [comment]
I can write an script to calculate by projectId. 
But updating database is useless because after each donating it will be recalculated by values of donation entities in mongo which are not synced!

**Comment by aminlatifi** [comment]
However, I wrote [this script](https://github.com/Giveth/feathers-giveth/blob/develop/scripts/utils/getDonationCounter.js) which gather information from blockchain and tells you how much money is in the project. For example the project id for common stack is 1402. 
```
➜  utils git:(f_1125_donation_counter_script) ✗ node ./getDonationCounter.js 1402
Number of pledges 6550
Number of pledge admins 2034
0xb5afaed1ae9b0485a859023e1372c100b11e98ab(SAI): 21151.359082293092970121
0xe3ee055346a9efaf4aa2900847deb04de0195398(ETH): 0.05
0x05a075b296995adcaec7c1de0e52271a4cf6deb8(DAI): 1.010000000000000009
```
Notice set the correct value for node url in config/default.json
