### ISSUE TITLE
Deploy Giveth on Private Blockchain 

### ISSUE THREAD

**Issue by Troublor** [Giveth/giveth-dapp#1130]
Is it possible to run and deploy Giveth dapp on private blockchain? Are there any guidelines showing how to do this?

**Comment by aminlatifi** [comment]
Yes, you should run feathers server too.
Giveth has a test environment using two private test networks. Do this steps

1. Start ipfs server
2. Start test networks by `npm run start:network` command in feathers server
3. Start feathers server by `npm start`
4. Start dapp by command `npm start`
5. You should have metamask on your browser. Add localhost:8546 network to it, it's foreign network. Home network is localhost:8545
6. Use 5 addresses provided in keystore folder under giveth-dapp project, they are privileged accounts in test environment.

You can connect to your private network, just modify network addresses in feathers config.
