### ISSUE TITLE
Adam can't collect on this milestone

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1134]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956

What is the story with it?

**Comment by aminlatifi** [comment]
> https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956
> 
> What is the story with it?

The money is moved to Paid pledge and as far as I know he should has collected.

**Comment by GriffGreen** [comment]
@aminlatifi he says:

same response as before, I get the “Oh no!
Something went wrong with the transaction” message before it even asks me to sign a transaction

(I hadn’t been able to withdraw it since then, just tried it right now and it’s still not working)

**Comment by gentlemandonadams** [comment]
Griff points out that I withdrew this a long time ago and that's why it wasn't working... I guess I let the "collect" button play with my memory, sorry for wasting some people's time here!  https://etherscan.io/tx/0xdf7f1de317d77bb51af9d7e163d1c14ad9d2fa81d7ca921c3376e8843d8b11a5
