### ISSUE TITLE
Cannot create campaign

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1135]
Trying to create campaign in localhost setup this error is generated and campaign is not created
```
info: error: campaigns - Method: create - campaign validation failed: fundsForwarder: Path `fundsForwarder` is required.
error: campaign validation failed: fundsForwarder: Path `fundsForwarder` is required. {"type":"FeathersError","name":"BadRequest","code":400,"className":"bad-request","errors":{"fundsForwarder":{"message":"Path `fundsForwarder` is required.","name":"ValidatorError","properties":{"message":"Path `{PATH}` is required.","type":"required","path":"fundsForwarder"},"kind":"required","path":"fundsForwarder","$isValidatorError":true}}}
```

**Comment by aminlatifi** [comment]
@arbreton I still cannot create campaign on localhost.
I guess it's related to fundsForwarder and coownerAddress fields which are required in model but they are not filled whey user creates a new campaign!

**Comment by aminlatifi** [comment]
@arbreton Still bug exists... Maybe fundsForwader should not be required in Campaign model...

**Comment by arbreton** [comment]
Tested on the latest commits seems to be working!, also needs new commits from feathers
