### ISSUE TITLE
milestones taking over an hour to load?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1139]
as a campaign owner i created milestones but they arent showing up in the campaign, after an hour!
<img width="1030" alt="Screen Shot 2020-02-21 at 9 51 15 PM" src="https://user-images.githubusercontent.com/14945613/75087396-72067280-54f4-11ea-9cf8-3ed0b9574833.png">

**Comment by aminlatifi** [comment]
Rinkeby gateway is done!! 
``wss://rinkeby.giveth.io/ws``
The events are not received by feathers

**Comment by Danibelle** [comment]
Is this related?  I am delegating donations to Milestones and they are hanging for an hour.. earlier this week these delegations were complete within minutes:

examples
https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d813493ad3696263686cc28
![image](https://user-images.githubusercontent.com/39466970/75095353-6d27da00-5559-11ea-8809-fd8c3ff9f706.png)

https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d699a7670de3a04788a762f
![image](https://user-images.githubusercontent.com/39466970/75095375-a4968680-5559-11ea-98f9-7c681688a13e.png)

**Comment by aminlatifi** [comment]
> Is this related? I am delegating donations to Milestones and they are hanging for an hour.. earlier this week these delegations were complete within minutes:
> 
> examples
> https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d813493ad3696263686cc28
> ![image](https://user-images.githubusercontent.com/39466970/75095353-6d27da00-5559-11ea-8809-fd8c3ff9f706.png)
> 
> https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d699a7670de3a04788a762f
> ![image](https://user-images.githubusercontent.com/39466970/75095375-a4968680-5559-11ea-98f9-7c681688a13e.png)

Yes they are related to that. Because rinkeby gateway was down, those delegations assumed failed! They and other similar donations are fixed now.
