### ISSUE TITLE
DECENTRAL Campaign Donation Weirdness

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1141]
Documenting what I see here - 

A new donation appeared in the past 24 hours. Yesterday the Campaign showed 411 SAI remaining, I happened to have taken a screenshot as I was tracking my work.. then today the Campaign says 1397 SAI remaining - see this [Google Doc.](https://docs.google.com/document/d/1H4l4u68fJUe-9yK1ZVBakgJi_TUvDWw5iK305zKhDMI/edit?usp=sharing)
 
I noticed because I was delegating donations to open Milestones and checked the amount remaining after doing a few, and it was higher than when I started.. but isn't going down with each delegation .. two examples included in the doc as well.

**Comment by Danibelle** [comment]
Note: Tracked the increase to an $800 donation from Anonymous user linked to Kingsley's account.  When I check his profile it doesn't show a donation to DECENTRAL, only to Shiftpod and Bike campaigns.

![image](https://user-images.githubusercontent.com/39466970/75096221-12937b80-5563-11ea-96bc-2ba233a1ed51.png)

![image](https://user-images.githubusercontent.com/39466970/75096226-20e19780-5563-11ea-8810-42fa133de235.png)

**Comment by aminlatifi** [comment]
@Danibelle I hope the problem with donation counters (current balance) are fixed now. If no please mention here.
The user profile page doesn't show some donations because they are recovered by simulation script and they don't have homeTxHash (corresponding transaction hash on home network) value. Donations with homeTxHash value only are shown in profile page.

Working on that...

**Comment by aminlatifi** [comment]
> @Danibelle I hope the problem with donation counters (current balance) are fixed now. If no please mention here.
> The user profile page doesn't show some donations because they are recovered by simulation script and they don't have homeTxHash (corresponding transaction hash on home network) value. Donations with homeTxHash value only are shown in profile page.
> 
> Working on that...

It's fixed.
