### ISSUE TITLE
Milestone stuck 'In Progress' after 'Collect' initiated

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1142]
https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5e4ac2d611b6b12e5cfbad51

Delegation successful, Collect button appeared and was clicked, confirmation received.. but it never hit the bridge and hasn't paid out even though the Donation Status at bottom says Paid.
![image](https://user-images.githubusercontent.com/39466970/75096041-e37c0a80-5560-11ea-996e-9d4f31a682be.png)

**Comment by aminlatifi** [comment]
@Danibelle There milestone and many other similar ones are fixed now
