### ISSUE TITLE
Payouts have been blocked for 2 weeks?!?!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1144]
<img width="1369" alt="Screen Shot 2020-02-22 at 8 05 25 AM" src="https://user-images.githubusercontent.com/14945613/75174757-0126ac80-56e6-11ea-8f9f-efd6d798867b.png">

I don't know what is the problem

**Comment by GriffGreen** [comment]
could be related to #1145

**Comment by GriffGreen** [comment]
I tried to pay out these miestones:
<img width="1275" alt="Screen Shot 2020-02-24 at 2 47 09 PM" src="https://user-images.githubusercontent.com/14945613/75198091-a22c5c00-5714-11ea-9bdb-7dab4c6061f8.png">
The bottom 2 were for less... they have weird donation amounts: https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d699a2d70de3a04788a762d

When i tried to collect those 2, it just fails, with this error 

```inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (10000000) or always failing transaction 
{code: -32000, message: "gas required exceeds allowance (10000000) or always failing transaction"}
code: -32000
message: "gas required exceeds allowance (10000000) or always failing transaction"
__proto__: Object" 
```

The 105 sai milestone sort of worked... It gave me a couple error messages acting like the tx wasnt going to work... but then the metamask window popped up and I was able to send the rinkeby tx which went thru, this is a screen shot of the last error message

<img width="1284" alt="Screen Shot 2020-02-24 at 2 43 29 PM" src="https://user-images.githubusercontent.com/14945613/75198846-6c887280-5716-11ea-8f39-a3e81bcdc508.png">

So now there is a new tx in the red :-( on the bridge

<img width="1272" alt="Screen Shot 2020-02-24 at 3 02 55 PM" src="https://user-images.githubusercontent.com/14945613/75199060-f6384000-5716-11ea-8001-56881b5d44c2.png">

**Comment by aminlatifi** [comment]
> https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d699a2d70de3a04788a762d

The problem with this milestone donations is fixed, can you collect again?

**Comment by GriffGreen** [comment]
hey, sorry for the delay... Just getting over the flu :(
7h
It looks like it was using infura endpoints and they now require a projectID.
7h
Do you have a mainnet & rinkeby node I can point the bridge to?
7h

**Comment by GriffGreen** [comment]
Ok so i made some infura endpoints
:-D  Hopefully that will fix it!
