### ISSUE TITLE
syncing script uses the date that the tx was resync'd instead of the date it was originally created

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1147]
The date shown on the dapp should be of the original donation, not the day that the syncing script added it to feathers.

See the last 6 donations in this screen shot: they were all old donations that just popped up in my delegation screen

<img width="1284" alt="Screen Shot 2020-02-24 at 3 05 35 PM" src="https://user-images.githubusercontent.com/14945613/75199238-6e9f0100-5717-11ea-8081-938b5c549409.png">

**Comment by aminlatifi** [comment]
We should find a way to deduce the date from somewhere, maybe transaction block number. Working on that...

**Comment by aminlatifi** [comment]
The date of donations are updated by corresponding rinkeby block timestamp.
