### ISSUE TITLE
Milestones that are fully funded are not showing as funded

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1149]
I funded a bunch of Milestones today and have a variety of issues with them that are probably the same issue that present a little differently.

On most of them, the header initially changes to "This Milestone has reached it's funding goal" then, reverts back to the amount requested.
Example [one ](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d6954c95df4387a353637cb) and [two](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d694d0a5df4387a353637bd) 
These show the amount requested and donated correctly:
![image](https://user-images.githubusercontent.com/39466970/75297687-20146400-57f6-11ea-9502-6f9c588e4b4d.png)

Others, the delegation appears at bottom with Committed status, however teh amount donated is still zero, per example [three ](url
![image](https://user-images.githubusercontent.com/39466970/75297840-826d6480-57f6-11ea-894e-181643275b93.png)
), [four ](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d813493ad3696263686cc28) and [five](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d699a7670de3a04788a762f)
![image](https://user-images.githubusercontent.com/39466970/75297874-95803480-57f6-11ea-919e-e5ad4e716d23.png)

In example [six](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d699b3570de3a04788a7631), the amount received is double the donation shown at bottom.  This might be user error, maybe I accidentally did it twice? But it only appears once below:
![image](https://user-images.githubusercontent.com/39466970/75298099-30790e80-57f7-11ea-8862-3576a94d0fe0.png)

**Comment by aminlatifi** [comment]
Maybe these donations are created by simulation script! Currently the script does not update projects fields, it is in our plan and will be fixed soon.

**Comment by aminlatifi** [comment]
Some of milestones were funded a little less than their goal! That tiny differences are not shown on front-end. 
By latest update we neglect tiny difference (less than 10000000000 wei).
Finally, all are fixed now.
