### ISSUE TITLE
Empty delegations appearing in DECENTRAL Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1150]
I've been delegating funds from the Campaign to Milestones, and see multiple new donations for 0.000 SAI dropping into the campaign?

![image](https://user-images.githubusercontent.com/39466970/75298337-d3318d00-57f7-11ea-9676-1c828cd6b8ed.png)

**Comment by aminlatifi** [comment]
They are not absolutely zero, they are tiny!

0x1083A91f0010bB30D9AFccc88a7C38B020165B91 has donated very small values several times (1705, 2274, 284, 2842 ... WEI). 

I agree that we should prevent users from choosing small amounts.
