### ISSUE TITLE
Every time i click the collect button i get an error... but everything else works?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1153]
Here is the play by play on https://beta.giveth.io/my-milestones when i click the Collect button

<img width="1289" alt="Screen Shot 2020-02-26 at 3 13 19 PM" src="https://user-images.githubusercontent.com/14945613/75397064-d6398580-58aa-11ea-94cf-7d2542d5fe64.png">
<img width="1302" alt="Screen Shot 2020-02-26 at 3 13 29 PM" src="https://user-images.githubusercontent.com/14945613/75397070-d9cd0c80-58aa-11ea-977c-f15b009ad8c5.png">
<img width="1280" alt="Screen Shot 2020-02-26 at 3 13 37 PM" src="https://user-images.githubusercontent.com/14945613/75397073-dafe3980-58aa-11ea-8d69-1f79d11449b8.png">
<img width="1287" alt="Screen Shot 2020-02-26 at 3 13 45 PM" src="https://user-images.githubusercontent.com/14945613/75397074-db96d000-58aa-11ea-92bd-c4587b501eed.png">

**Comment by aminlatifi** [comment]
Applied some patch, still testing...

**Comment by aminlatifi** [comment]
For testing, I have created tiny amount milestones. Waiting for acceptance and delegating money to one of them to test all cases, should be done by @arbreton

**Comment by arbreton** [comment]
@aminlatifi delegated everything correctly

**Comment by aminlatifi** [comment]
Tested... Fixed.

**Comment by GriffGreen** [comment]
Still happening: https://youtu.be/zzkYMJsAqyg

**Comment by aminlatifi** [comment]
> Still happening: https://youtu.be/zzkYMJsAqyg

It's weird, I did it myself today for my milestone! Investigating...

**Comment by aminlatifi** [comment]
Feathers log messages helped to find the problem. It's repetition of the bug reported in #1164.  
The error is thrown because feathers tries to once move money to a `Paying` donation, and next moving from that to a `Paid` donation. Unfortunately the second movement is intended to processed first sometimes and appropriate donation is not created yet.

**Comment by aminlatifi** [comment]
@GriffGreen If the error happens after this please report here. I hope the update on feathers solve this problem too.
