### ISSUE TITLE
Gas Error on Bridge Payout Transaction

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1160]
I have a purple 'Pay' button and pressed it.. signed transaction then it failed.

On second look, scrolling the MetaMask transaction window reveals a red Alert:
![image](https://user-images.githubusercontent.com/39466970/76167887-1107ad00-6138-11ea-8d41-6f244f4d6223.png)

Here's the view with Dev window displayed, says it ran out of gas - when I hit the button again it says.. $31.19 / .144045 ETH ??
![image](https://user-images.githubusercontent.com/39466970/76167962-b458c200-6138-11ea-8620-06ce42e35885.png)

**Comment by aminlatifi** [comment]
You should wait till security check is done. Someone do that manualy.
