### ISSUE TITLE
Milestone in the past shows that Kay and I both accepted the Review? - Simulation Script for Status updates?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1161]
https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5c1abeeb6c76245cd3f97c68

Its weird cause it says that both Kay and I reviewed it? but really he reviewed it an maybe i dispersed it?

Either way this is a larger issue... the status updates on the lower right side are fucked up in a lot of milestones.... if it tracks them at all... i feel like this is a perfect thing to be tracked with the simulation script and updated as they happen... might also make sense to include in the CSV

**Comment by aminlatifi** [comment]
Actually simulation script does nothing to conversation till now. And the wrong conversation item has been created more than one year ago.
I guess it was created wrongly and unintentionally by a script like the migration ones before. I investigated the saved migration scripts however and couldn't find a clue.
I deleted the mistakenly created conversation item.

**Comment by aminlatifi** [comment]
This milestone https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5c1abeeb6c76245cd3f97c68 status should be `Completed` based on implemented logic. If a milestone is uncapped or is not fully funded, it is not marked as `Paid`. 
However I implemented an script which will fix status of all milestones and I will apply it soon after sufficient testing.

**Comment by aminlatifi** [comment]
There are lot's of incorrect conversations which are duplicate of a correct one but with a wrong user!
It's a chronic bug, this is a case which happened in 2018
https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b3a22d12cbb135dfa59aaf5

**Comment by GriffGreen** [comment]
Previous ones are ok....
