### ISSUE TITLE
Change Ownership feature only works on feathers, isn't connected to smart contracts

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1169]
To change the owner of campaign on blockchain you need to follow this instruction:
https://docs.google.com/document/d/1cPOR7kjyT_syywlQhG0-fYF_lGJikPZ7hmnEjq4pNMs/edit?usp=sharing

Issue type: **Error**
There was a problem with catching the transaction hash, but your transaction probably went through.

**TransactionLink:**
https://rinkeby.etherscan.io/tx/undefined

Attempting from 'My Delegations' .. I notice the icons have gone back to that purple circle white dot on many of the user profiles listed too.. 
![image](https://user-images.githubusercontent.com/39466970/77175661-5bbee880-6a99-11ea-849b-63220557d8f3.png)

![image](https://user-images.githubusercontent.com/39466970/77175704-6da08b80-6a99-11ea-8f8f-597bf979b1b2.png)

**Comment by Danibelle** [comment]
Milestone: https://beta.giveth.io/campaigns/5d1cfe6bbd45530e23ad87d0/milestones/5e6a57759a20e61b022849b6

![image](https://user-images.githubusercontent.com/39466970/77175920-b5bfae00-6a99-11ea-983a-b371624e0a87.png)

![image](https://user-images.githubusercontent.com/39466970/77175979-ccfe9b80-6a99-11ea-9c44-c019d8bf5ffb.png)

**Comment by aminlatifi** [comment]
Are you sure the transaction has happened? Would you please check your metamask history and share the transaction hash value here?
Regarding images, I agree. Something is wrong with giveth ipfs gateway.

**Comment by Danibelle** [comment]
![image](https://user-images.githubusercontent.com/39466970/77337721-a772cb80-6cff-11ea-950d-15f01552bbe5.png)

**Comment by Danibelle** [comment]
Changed Ownership to Griff primary and Dani co-owner:
![image](https://user-images.githubusercontent.com/39466970/77338068-2cf67b80-6d00-11ea-90dc-5ad14ca64dcf.png)

**Comment by Danibelle** [comment]
Works for Griff.. likely an issue with Dani being both owner and reviewer.

**Comment by GriffGreen** [comment]
not sure what the error was... 

Does the Ownership change feature work?

Does it only fail when the owner is also the reviewer?

Either way something is buggy... but its not urgent

**Comment by GriffGreen** [comment]
To test with the DApp Campaign?

**Comment by aminlatifi** [comment]
Testing on localhost is easier

**Comment by GriffGreen** [comment]
Check for a check in the smart contract

**Comment by aminlatifi** [comment]
Haven't tested yet! But Andre mentioned (and it's true) that `Change Ownership` button just updates db!!
To change the owner of campaign on blockchain you need to follow this instruction:
https://docs.google.com/document/d/1cPOR7kjyT_syywlQhG0-fYF_lGJikPZ7hmnEjq4pNMs/edit

**Comment by GriffGreen** [comment]
#916
