### ISSUE TITLE
Donation stuck in pending

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1172]
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5dabb2f9d25d7f4a295e3dd5

**Comment by Danibelle** [comment]
![image](https://user-images.githubusercontent.com/39466970/77339433-25d06d00-6d02-11ea-9fcb-5cc467bbfab0.png)

**Comment by aminlatifi** [comment]
The donation has done long time ago and it should not need user accept.

**Comment by Danibelle** [comment]
I see this issue has been closed, but I still see a pending transaction in my donations that is not yet completed:

![image](https://user-images.githubusercontent.com/39466970/77858747-9f64d100-71c2-11ea-9136-e124d2289a8a.png)

**Comment by aminlatifi** [comment]
The issue is closed automatically because a commit messages says has fixed it 🚶 
Actually, we fixed the bug which causes problem like this!
The `Committed` donation is recovered by syncing script. 
@Danibelle  Can you collect this donation again to withdraw that 150 SAI?

**Comment by Danibelle** [comment]
done thank you!
