### ISSUE TITLE
Something wrong with delegating the funds in the Doge Art Car Campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1175]
Issue type: **Error**
There was a problem with catching the transaction hash, but your transaction probably went through.

**TransactionLink:**
https://rinkeby.etherscan.io/tx/undefined

<img width="1136" alt="Screen Shot 2020-03-25 at 8 24 06 PM" src="https://user-images.githubusercontent.com/14945613/77577302-cf685780-6ed6-11ea-9099-7a78db247a46.png">

Can't delegate :-(

**Comment by GriffGreen** [comment]
cant delegate single donations from the "My Delegations" page either

**Comment by GriffGreen** [comment]
@aminlatifi maybe you and I can hack on this some time? I'm going to work on the CSV tomorrow, could also work on this if you have the time

**Comment by GriffGreen** [comment]
<img width="990" alt="Screen Shot 2020-04-06 at 6 48 42 PM" src="https://user-images.githubusercontent.com/14945613/78583589-51417480-7837-11ea-939d-b5a8c18ee00c.png">

**Comment by aminlatifi** [comment]
#973 releates

**Comment by aminlatifi** [comment]
Other main issues:
Modal disappears
Value typing problem
Delegate max amount

**Comment by GriffGreen** [comment]
The Delegation worked... but the bug isnt fixed... there needs to be some sort of limit (like there is with collecting) for delegating pledges. 

This happens when a campaign collects a lot of small donations and delegates a lot of them to a large milestone... its a rare event... but it happened for both the Bike campaign and the art car campaign for decentral

**Comment by aminlatifi** [comment]
The feature of limiting number of donations to delegate is deployed on beta.

**Comment by aminlatifi** [comment]
@GriffGreen Does the problem exist yet?

**Comment by GriffGreen** [comment]
Not ure, needs to be tested :-( we need to get something with a lot of small donations

**Comment by horus2021** [comment]
I should test this issue and finalise it.

**Comment by horus2021** [comment]
Hey @aminlatifi , I was going to check number and values of donations and delegation of "Doge Art Car Campaign". How can I search for this in beta? Do we have this feature , I mean **search for projects**. If not. I think it is a good search. Imagine the following scenario. You told a friend that he can donate to a project in Giveth site, but he lost the link. He googled Giveth and find it, how he wants to find that project in Giveth in the next step.

**Comment by aminlatifi** [comment]
We had limited number of pledges are dealt with on every delegation
