### ISSUE TITLE
i got the error message before that didnt say anything but the tx worked

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1177]
<img width="1662" alt="Screen Shot 2020-03-25 at 9 53 38 PM" src="https://user-images.githubusercontent.com/14945613/77584485-2b38dd80-6ee3-11ea-93c9-1af8ff4bce70.png">

https://beta.giveth.io/campaigns/5d1cfe6bbd45530e23ad87d0/milestones/5e6a57759a20e61b022849b6

https://rinkeby.etherscan.io/tx/0x41ee4b02b4d96a2b5533bbfbfd6ba160cec3db1277b7ab685b8442ca691278ef

^^^ I got an "Oh No" message (with no further description of the error) but it worked anyway

**Comment by aminlatifi** [comment]
Maybe donations need to be synced again...

**Comment by aminlatifi** [comment]
@GriffGreen I haven't change anything except the way error is handled for a special case that I reckon caused such error message.
If that happens again we would have more information to solve it.

**Comment by horus2021** [comment]
@aminlatifi tell "It's ancient error, reported frequently and don't know yet the root cause"
