### ISSUE TITLE
We can increase the number of pledges

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1178]
Rinkeby upped the block gas limit to 10 million

https://rinkeby.etherscan.io/tx/0x41ee4b02b4d96a2b5533bbfbfd6ba160cec3db1277b7ab685b8442ca691278ef

we should up the limit to 11 pledges and see what happens... we might even be able to get to 14 or 15 pledges

**Comment by aminlatifi** [comment]
> Rinkeby upped the block gas limit to 10 million
> 
> https://rinkeby.etherscan.io/tx/0x41ee4b02b4d96a2b5533bbfbfd6ba160cec3db1277b7ab685b8442ca691278ef
> 
> we should up the limit to 11 pledges and see what happens... we might even be able to get to 14 or 15 pledges

Greate, applying on beta.giveth.io?

**Comment by aminlatifi** [comment]
@GriffGreen The value is changed to 12
