### ISSUE TITLE
Funded Milestone to be cancelled, SAI returned

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1184]
This Milestone by Kris for Jake on Dani's Campaign needs to be cancelled: https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5e4c2a3911b6b12e5cfbad78

It's fully funded with SAI. So we need to make sure this goes through, the funds get returned, and then I have to redelegate those funds so we can get the SAI out of the system.

**Comment by aminlatifi** [comment]
Have you tried to cancel it? do you have permission?

**Comment by aminlatifi** [comment]
There is no Cancel button for a fully funded milestone!

**Comment by aminlatifi** [comment]
This should be fixed by #1198 revert.
@krrisis @Danibelle please update here with new status.

**Comment by krrisis** [comment]
Yes!!! Cancel button is back in overview & in the Milestone. Cancellation worked. Money should be back in the Decentral Campaign now. @Danibelle do you see this?
