### ISSUE TITLE
Emptying SAI from the BIKE campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1185]
We need to get all the SAI out and into this milestone: https://beta.giveth.io/campaigns/5d1cfe6bbd45530e23ad87d0/milestones/5e6ab2b39a20e61b022849c0

I was really excited when i saw this:
<img width="593" alt="Screen Shot 2020-04-03 at 5 53 45 PM" src="https://user-images.githubusercontent.com/14945613/78381109-2bb53080-75d5-11ea-9325-7ef23d924a7f.png">

but to no avail... maybe its cause the bridge is down?
<img width="1508" alt="Screen Shot 2020-04-03 at 5 54 52 PM" src="https://user-images.githubusercontent.com/14945613/78381099-2821a980-75d5-11ea-999f-f16919f0292a.png">

**Comment by aminlatifi** [comment]
@GriffGreen rinkeby gas limit doesn't allow 15 collection at same time. Changing it to 10 to see what happens

**Comment by aminlatifi** [comment]
@Danibelle Please check it again.

**Comment by GriffGreen** [comment]
DONE!
