### ISSUE TITLE
SAI Accounting

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1189]
This issue is to report projects (DACs/Campaigns/Milestones) which have SAI inside and how much in each one.

**Comment by aminlatifi** [comment]
[report1.txt](https://github.com/Giveth/giveth-dapp/files/4431191/report1.txt)
@Danibelle @GriffGreen it's the report just for SAI. Generating for multiple token is easily possible if you want.

**Comment by GriffGreen** [comment]
I would love the report with all the funds! Its a good spring cleaning exercise.

**Comment by aminlatifi** [comment]
@Danibelle 
[report_all_tokens.txt](https://github.com/Giveth/giveth-dapp/files/4442046/report_all_tokens.txt) has all tokens include.

**Comment by aminlatifi** [comment]
@GriffGreen Any reason to move it to "In Progress"?

**Comment by GriffGreen** [comment]
we still have to get everyone off... there is 12000 SAI sitting there waiting to be collected

**Comment by aminlatifi** [comment]
[report_all_tokens_2.txt](https://github.com/Giveth/giveth-dapp/files/4566056/report_all_tokens_2.txt) has all tokens included.

**Comment by aminlatifi** [comment]
[report_sai_3.txt](https://github.com/Giveth/giveth-dapp/files/4635782/report_sai_3.txt) to see just SAI balance.

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1iY2V535ucoWklF02MIDeDG8b69N6z4aLhqiODULpunM/edit?usp=sharing

**Comment by GriffGreen** [comment]
Great way to see if they did it https://bridge.beta.giveth.io/

**Comment by GriffGreen** [comment]
Great work so far!

**Comment by GriffGreen** [comment]
Abram needs to Review https://beta.giveth.io/campaigns/5b94a71490b3c1478f06b42b/milestones/5c8f8a14c7ed727e1add1b9f

**Comment by GriffGreen** [comment]
4,615.903410070839661228 SAI left to go!

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b94a71490b3c1478f06b42b/milestones/5c8f8a14c7ed727e1add1b9f
Both the reviewer and the milestone creator lost their keys for this one

**Comment by horus2021** [comment]
[SAI Accounting Google Sheet](https://docs.google.com/spreadsheets/d/1Ewj2W0BmiZ7NVeH3ENZdkgtCW25eiiVtfzTjtZtp5J4/edit#gid=563656601&fvid=1364139678)!

**Comment by horus2021** [comment]
Conflict!
According to [Etherscan](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359?a=0x30f938fed5de6e06a9a7cd2ac3517131c317b1e7) Balance is 4615 SAI.

According to my [Accounting] (https://docs.google.com/spreadsheets/d/1Ewj2W0BmiZ7NVeH3ENZdkgtCW25eiiVtfzTjtZtp5J4/edit#gid=563656601) our Balance is 4038 SAI. I neglect some cents and did not take them into account, but 550 SAI difference is too big. Something strange happens.

**Comment by GriffGreen** [comment]
Figure out where the SAI is? 

150 is in control of by lorelei...

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5d1ba874bd45530e23ad86ed 
https://beta.giveth.io/campaigns/5c0e84ea06392d786b64d484

**Comment by aminlatifi** [comment]
@horus2021 https://github.com/Giveth/giveth-dapp/issues/1323#issuecomment-653884670 reports stuck money inside canceled projects. Some has SAI inside.

**Comment by horus2021** [comment]
Conflict warning

According to Etherscan SAI balance of Giveth Bridge is **771 SAI**
According to my Accounting our Balance in projects with state (Active and Needs Review) is **194 SAI**. I neglect some cents and did not take them into account, but **557 SAI** difference is too big. Something strange happens.

The total SAI in cancelled project is **110 SAI**

First)
Campaign Title: Cryptoxmas.xyz - Venezuelans need your help
Status: Canceled
Link: localhost:3010/campaigns/5c0e84ea06392d786b64d484
Owner: localhost:3010/profile/0x224CF0B963c59B95623b3Dd6ce07b4cE40F7b134
Reviewer: localhost:3010/profile/0x5D28FE1e9F895464aab52287d85Ebff32B351674
SAI: 50

Two)
Milestone Title: Buying the Disco Fish to turn it into our Shiba
Status: Canceled
Link: localhost:3010/campaigns/5cfe3366228b71296a491fa7/milestones/5d1ba874bd45530e23ad86ed
Owner: localhost:3010/profile/0x567355f84d44a982629D8675AB4aadBB92dbfD54
Recipient: localhost:3010/profile/0x839395e20bbB182fa440d08F850E6c7A8f6F0780
SAI: 50

Three)
Milestone Title: Vocdoni - Minimum Viable Product
Status: Canceled
Link: localhost:3010/campaigns/5c42162454c4dd181cdb28b7/milestones/5c44562e54c4dd181cdb2a01
Owner: localhost:3010/profile/0x47fCD86C2a8A02af00CADF8660Ca1896AA4FE238
Reviewer: localhost:3010/profile/0x5D28FE1e9F895464aab52287d85Ebff32B351674
Recipient: localhost:3010/profile/0x47fCD86C2a8A02af00CADF8660Ca1896AA4FE238
SAI: 10

**Comment by horus2021** [comment]
We have two amount of SAI balance in the below projects. The owners are not in control of these amounts anymore. So we cannot get out them from our platform. We give up! :(
Maybe we can remove them from UI.

DAC Title: Unicorn DAC
Status: Active
Link: localhost:3010/dacs/5c086caed663227e436371c5
Owner: localhost:3010/profile/0xB3e43abf014cb2d8cF8dc3D8C2e62157E6093343 (@lorelei1 )
SAI: 150.000000000000015242

Milestone Title: Apple Membership and additional features
Status: NeedsReview
Link: localhost:3010/campaigns/5b94a71490b3c1478f06b42b/milestones/5c8f8a14c7ed727e1add1b9f
Owner: localhost:3010/profile/0xeDB4Bd2aA6170a4dE85Da2B3733fD8AB0a6e4658
Reviewer: localhost:3010/profile/0x29684371d4dFb108B66B24922679442d3218F560
Recipient: localhost:3010/profile/0xeDB4Bd2aA6170a4dE85Da2B3733fD8AB0a6e4658
SAI: 44.069297029702970318

**Comment by GriffGreen** [comment]
#1323 and #1368 are opened to close this out Lorelei was warned to get the last funds she has out or else!
