### ISSUE TITLE
Starting DAC with locked wallet does not prompt wallet unlock

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#119]
When starting a DAC with locked wallet, there is never a prompt for unlocking the wallet. If user clicks on the `Save DAC` button, it just remains on s`Saving`.
<img width="345" alt="screen shot 2017-10-22 at 22 11 26" src="https://user-images.githubusercontent.com/7974813/31865859-32194cc4-b776-11e7-916c-7382e63eb48a.png">

**Comment by satyavh** [comment]
This is caused by #58 
You will not be able to access this route at all if your wallet is locked. So this bug will be auto-solved when #58 is solved.
