### ISSUE TITLE
FDS Swarm Alpha Milestone 20,000 DAI Transaction Monitoring

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1190]
This Milestone requesting 50,000 DAI has a 20,000 DAI donation currently in process.

https://beta.giveth.io/campaigns/5d5e73f9ee8dd87908fcd27d/milestones/5e68ff279a20e61b0228496b

Miha is requesting any expedition or management to prevent delays.

**Comment by GriffGreen** [comment]
https://etherscan.io/tx/0x8093b6ee4d4bba5bd7410048f577888a7c27553d94bb30bf703929e38d8a5eee

It looks good :-D
