### ISSUE TITLE
Our IPFS pictures are falling off? Where are we hosting them?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1196]
Pictures are not all available... 

<img width="1008" alt="Screen Shot 2020-04-06 at 6 37 12 PM" src="https://user-images.githubusercontent.com/14945613/78582505-a7151d00-7835-11ea-9a59-9c899c93723b.png">

**Comment by aminlatifi** [comment]
Changed some configuration to keep service alive all the time and increase performance. Hope that fixes the problem.
Keep issue open so far to become sure.

**Comment by horus2021** [comment]
We pin files on both our ipfs server and pinata cloud ipfs service
