### ISSUE TITLE
show "pending transaction" donations

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#12]
when viewing the donations (my-donations, a dac/campaign) we should show "incoming/pending" donations.

a donation is pending if "donation.noteId === 0"

**Comment by satyavh** [comment]
Just to clarify, I'm now sorting / displaying them like this:

```
              donations: _.sortBy(resp.data, (d) => {
                if(d.status === 'pending') return 1
                if(d.status === 'to_approve') return 2
                if(d.status === 'waiting') return 3
                if(d.status === 'committed') return 4
                if(d.status === 'cancelled') return 5
                return 4
              }),
```

So how are the other statuses defined?

**Comment by satyavh** [comment]
I think the easiest is just to at a `donation.status = transaction_pending`
Then we can also add `transaction_cancelled`, `transaction_failed` etc.

**Comment by satyavh** [comment]
I've implemented it like that for now
