### ISSUE TITLE
when going straight to a Milestone page, the user is not prompted to switch to Rinkeby

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1203]
I have been making milestones to pay out the Commons Simulator team and when i send them a link to the milestone and ask them to collect... there is no clear guidance on how to collect...

This has happened a couple times... the key piece missing is that they need to set their metamask account to Rinkeby:
![photo_2020-04-09_20-34-46](https://user-images.githubusercontent.com/14945613/78928927-cadc9b00-7aa1-11ea-9c60-78215c558531.jpg)

I think this is a Common problem that extends beyond this one button, but to all buttons that are greyed out

Potential Solution:
Instead of greying out the button... allow it to be clickable but then if they click it, and are on mainnet tell them that they need to switch their network to rinkeby... and maybe even have a gif that shows them how to do it for metamask.

**Comment by BenSchZA** [comment]
Another point is that although the button was greyed out, it was still clickable. This added a bit more uncertainty.
