### ISSUE TITLE
Download CSV goes to a browser window instead of downloading as a file

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1207]
I was the Campaign Manager and it downloaded fine the first time... 

Does this problem only happen the second time its downloaded? or only when you are not the campaign manager? not sure...

<img width="1147" alt="Screen Shot 2020-04-15 at 6 22 07 PM" src="https://user-images.githubusercontent.com/14945613/79361771-0c5bc300-7f46-11ea-8afe-5cbd542000c7.png">

**Comment by aminlatifi** [comment]
It happened to me.
Not sure...
