### ISSUE TITLE
Wow! Love this idea! thx for adding this little button :-D

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1219]
<img width="806" alt="Screen Shot 2020-04-21 at 2 13 14 PM" src="https://user-images.githubusercontent.com/14945613/79864771-4dd2ef00-83da-11ea-99da-4ffc8d132fd9.png">

**Comment by GriffGreen** [comment]
that is all you can close this issue... :-D

**Comment by aminlatifi** [comment]
@GriffGreen: I think it's better to remove 'please' word...

**Comment by GriffGreen** [comment]
If we want to rephrase, I would say:

To take this action, connect to the **Rinkeby** Network

**Comment by GriffGreen** [comment]
And the button could have a different background color... :-D

**Comment by aminlatifi** [comment]
> If we want to rephrase, I would say:
> 
> To take this action, connect to the **Rinkeby** Network

Some actions doesn't need network interactions and can be done without being connected to `Foreign Network`. Like deleting proposed milestone, and in future archiving maybe.
