### ISSUE TITLE
I want "Sort By" in a campaign's milestones!!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1224]
Really hard to keep budgets up to date when a milestone that gets accepted 4 months after proposal then gets buried back into the other milestones proposed at the same time it was. 
Right now I wish that they were just automatically sorted by most recently accepted rather than date proposed but I think in the long run it would be more important to be able to choose between those 2 options, and maybe some others like biggest $ amount milestones etc.

**Comment by aminlatifi** [comment]
@lorelei1 We don't keep acceptance date in DB... but we have udpateAd field which shows the last time the document (milestone/dac/campaign) is modified. For instance whenever a milestone state is changed, donated to or disbursed this value is updated to action time. Is it helpful for short term solution?
Also, do you have any specific view to add this feature to? or all the views who list items?

**Comment by aminlatifi** [comment]
Just change the default sort to updatedAt

**Comment by GriffGreen** [comment]
so this is 2 issues... the quick fix and big fix :-D
