### ISSUE TITLE
A couple milestones are in some sort of limbo... Need to fix!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1225]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e3831dd11b6b12e5cfbabbb

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e65775a9a20e61b02284914

They say pending... Not sure what happened... i clicked "Approve" and then they left the "my Milestone" page, but never made it to the milestone page... there is a bit of a rush since this is a SAI payment.

Whats weird is that i approved 3 milestones all at about same time and only had a problem with 2 of them, the third one i approved was: 
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e5e88419a20e61b022847fa

And that worked fine.

**Comment by aminlatifi** [comment]
Those two milestones were not treated normally because `SAI` token is forbidden in creating milestone!
Currently frontend doesn't allow you to create new milestones using `SAI`. They may have proposed before changing whitelist.

**Comment by aminlatifi** [comment]
I believe activeTokenWhitelist should just limit frontend behavior, and we should stick to original whitelist at backend.

**Comment by aminlatifi** [comment]
This milestone seems OK right now: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e3831dd11b6b12e5cfbabbb

**Comment by aminlatifi** [comment]
I cannot find transaction corresponding to this one: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e65775a9a20e61b02284914
It's in `Proposed` state. @GriffGreen Are you sure you have accepted this one?

**Comment by GriffGreen** [comment]
Thx amin!!

**Comment by GriffGreen** [comment]
Feel free to close this if you have no further actions ;-D
