### ISSUE TITLE
Can't remove fundraising cap when editing a milestone

### ISSUE THREAD

**Issue by loietaylor** [Giveth/giveth-dapp#1227]
<img width="930" alt="Screen Shot 2020-04-23 at 10 00 52 PM" src="https://user-images.githubusercontent.com/38163206/80144783-68aa8c80-85af-11ea-9ba5-44d2d150e756.png">

Originally this milestone had a fundraising cap. But I went to edit it while it was still just 'proposed' not accepted.. and the UI let me change it to no fundraising cap accepting donations in all tokens but then when I clicked save it looked like this ^... still raising 1500 ANYTOKEN and below it said raising 1500 SAI

**Comment by aminlatifi** [comment]
@lorelei1 you have canceled that milestone... right?
We should fix dapp to such error does not happen any more

**Comment by GriffGreen** [comment]
it might have been just because of SAI
