### ISSUE TITLE
Stuck SAI Milestone

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1228]
<img width="1248" alt="Screen Shot 2020-04-24 at 1 18 48 AM" src="https://user-images.githubusercontent.com/14945613/80158770-9f8d9c00-85c9-11ea-9d08-2897e48bac9f.png">
https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5ea16cb81db39e3252bd1607

**Comment by aminlatifi** [comment]
@GriffGreen it's like #1177

**Comment by GriffGreen** [comment]
oh great! :-D
