### ISSUE TITLE
Dai Donations don't work right when 3% to a DAC is activated

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1229]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5ea22bcb1db39e3252bd1743

When you donate ETH to the milestone... the way everything works is fine, it takes 2 transactions but thats ok we can deal.

When you try to donate dai to this milestone, 3% goes to the DAC (it takes 2 transactions) and then nothing goes to the milestone... I suppose there is supposed to be 2 more transactions here... but honestly this is not acceptable... 4 transactions for a donation isnt worth the 3%!

Until we can get it working in an acceptable way, can we just let dai donations go 100% to the milestone?

Thx!

**Comment by aminlatifi** [comment]
We disabled donating to DAC for that milestone. 
Donating to DAC in milestone will be refactored in first opportunity.

**Comment by GriffGreen** [comment]
![there goes my hero](https://user-images.githubusercontent.com/14945613/80205906-bd8be880-862b-11ea-8271-f4127f3e4eea.gif)
https://www.youtube.com/watch?v=EqWRaAF6_WY

**Comment by GriffGreen** [comment]
see #1027

**Comment by GriffGreen** [comment]
Would like to see this #735 worked along with it

**Comment by aminlatifi** [comment]
https://github.com/Giveth/giveth-dapp/pull/1236 should fix this. Also we do one transaction to grant allowance.
