### ISSUE TITLE
Allow a more flexible Conversation within milestones

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1234]
As a Milestone proposer or a recipient, i would like to make updates on my milestones

**Comment by GriffGreen** [comment]
Needs a little design work :-D

**Comment by GriffGreen** [comment]
Allow them to update this column: 
<img width="492" alt="Screen Shot 2020-07-01 at 5 14 33 PM" src="https://user-images.githubusercontent.com/14945613/86261094-69b6f600-bbbe-11ea-8b43-f22ffdfc2d1f.png">

**Comment by GriffGreen** [comment]
The Campaign Manager, Recipient, Reviewer and Milestone Manager should be able to make status updates to milestones at any time :-D

**Comment by GriffGreen** [comment]
Love the Write Comment button?

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/92715614-f62a2580-f372-11ea-9775-23ef28d46198.png)
@GriffGreen Do you have any feedback on phrases? Personally guess  `<User> wrote` title can be changed.

**Comment by GriffGreen** [comment]
@mahdine OMG YES! Great WORK!!
