### ISSUE TITLE
Taking a long time for the review to happen?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1235]
https://rinkeby.etherscan.io/tx/0x9936fb396712d81735f158da00fadee36f59e0dfd63e6c63a63557b23154604f

Currently its been 25 minutes

https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5c994b98150a830a701e167a

I can't see the collect button?

<img width="1271" alt="Screen Shot 2020-04-29 at 10 07 57 PM" src="https://user-images.githubusercontent.com/14945613/80641968-f5e55980-8a65-11ea-8b54-e56740279caf.png">

Or the Disburse button!

<img width="1280" alt="Screen Shot 2020-04-29 at 10 08 15 PM" src="https://user-images.githubusercontent.com/14945613/80642003-04cc0c00-8a66-11ea-8cdf-03f54a7ac205.png">

**Comment by aminlatifi** [comment]
There was problem on connecting to aragon rinkeby node. I changed that with infura one and it is solved right now.
