### ISSUE TITLE
Milestones stuck in 'Paying' and 'Needs Review' status

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1240]
Three Milestones in 'My Milestones' appear to be stuck:
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5cf1791f8182665680873f7d
https://beta.giveth.io/campaigns/5c4794dd8a6a785b61462b0f/milestones/5c5785e78b07881f803428fa
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5de1037f92236b547e29d9d9

![image](https://user-images.githubusercontent.com/39466970/80967789-2dd8fd80-8dd4-11ea-9ab3-2f55be1f377d.png)

**Comment by Danibelle** [comment]
![image](https://user-images.githubusercontent.com/39466970/80968106-a475fb00-8dd4-11ea-8b08-d9358087de16.png)

**Comment by Danibelle** [comment]
The two that needed approval are cleared and I have approved them:
![image](https://user-images.githubusercontent.com/39466970/80993720-cbdebf00-8df8-11ea-848c-28a205eee7df.png)

**Comment by aminlatifi** [comment]
All should be fixed now, @Danibelle does any of those reported milestones still have any kind of problem?

**Comment by horus2021** [comment]
Hey @Danibelle , I want to close this issue. Please check it out and give comment ASAP. Do you still see the problem in those milestone?

**Comment by Danibelle** [comment]
These are all completed and paid now!
