### ISSUE TITLE
Weird rounding error for delegation from my delegations screen

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1245]
I just delegated some of this delegation to the milestone... now the amount that feathers estimates is a little off...
<img width="903" alt="Screen Shot 2020-05-07 at 11 36 44 PM" src="https://user-images.githubusercontent.com/14945613/81347173-e6948a80-90bb-11ea-93bb-e2f0d8266318.png">

When i try to do it i get this error:
<img width="1059" alt="Screen Shot 2020-05-07 at 11 39 38 PM" src="https://user-images.githubusercontent.com/14945613/81347252-0e83ee00-90bc-11ea-9559-045fb13e501e.png">

I assume it failed because it added that random 3695 at the end. When i delete that 3695... it works great:

<img width="822" alt="Screen Shot 2020-05-07 at 11 41 00 PM" src="https://user-images.githubusercontent.com/14945613/81347401-53a82000-90bc-11ea-97d7-d437e649e26f.png">

<img width="1198" alt="Screen Shot 2020-05-07 at 11 41 14 PM" src="https://user-images.githubusercontent.com/14945613/81347399-5276f300-90bc-11ea-9262-d57f5ef0a928.png">

<img width="1035" alt="Screen Shot 2020-05-07 at 11 41 24 PM" src="https://user-images.githubusercontent.com/14945613/81347390-4f7c0280-90bc-11ea-9b3a-6638f31a3953.png">

**Comment by GriffGreen** [comment]
low priority bug

**Comment by aminlatifi** [comment]
It's weird, original value was 91909999999999996589 wei
