### ISSUE TITLE
buttons show up before i can click them for committing donations

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1249]
<img width="154" alt="Screen Shot 2020-05-08 at 10 33 33 PM" src="https://user-images.githubusercontent.com/14945613/81447920-c75e3180-917d-11ea-817e-8f2e9e9983ba.png">
<img width="387" alt="Screen Shot 2020-05-08 at 10 33 22 PM" src="https://user-images.githubusercontent.com/14945613/81447921-c88f5e80-917d-11ea-8d3d-8501504ed2cb.png">

**Comment by aminlatifi** [comment]
The buttons should not be appear before enough confirmation
