### ISSUE TITLE
Donations not working on the dapp again?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1250]
made 2 donations...

This one 
https://etherscan.io/tx/0x310445afd5cd316db574c273aa8add27d93d04b5a5fdc76728d25177418b954d
to a campaign:
https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7

<img width="1031" alt="Screen Shot 2020-05-09 at 1 38 17 AM" src="https://user-images.githubusercontent.com/14945613/81457304-cf29d000-9195-11ea-9d3d-7cdf11eb1e7e.png">

Another one to a milestone:

https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5ea31673f00d813b5f62b2ac

But oh no! It doesnt show up on the bridge monitor??!?!
https://bridge.beta.giveth.io/
<img width="1437" alt="Screen Shot 2020-05-09 at 2 02 15 AM" src="https://user-images.githubusercontent.com/14945613/81458123-27ae9c80-9199-11ea-8c4a-ec04dd7f2ac8.png">

:-( Whomp Whomp :-D

**Comment by aminlatifi** [comment]
https://github.com/Giveth/feathers-giveth/blob/704b1bab8adc88be383616b4e5e1cc1369e65b77/src/blockchain/failedTxMonitor.js#L221-L233

Feathers cannot find `Home Transaction` `Recipient`!
@GriffGreen Do you have any idea?

**Comment by aminlatifi** [comment]
There was a problem on bridge ... fixed.
