### ISSUE TITLE
edit text

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1253]
<img width="961" alt="Screen Shot 2020-05-11 at 6 50 35 PM" src="https://user-images.githubusercontent.com/14945613/81588122-58205180-93b8-11ea-918b-075f01ac07e5.png">

**Comment by GriffGreen** [comment]
<img width="730" alt="Screen Shot 2020-05-11 at 6 53 50 PM" src="https://user-images.githubusercontent.com/14945613/81589649-e0ebbd00-93b9-11ea-91d5-d7925ab186bc.png">
make `!` a `?`

**Comment by aminlatifi** [comment]
Any suggestions are welcomed regarding above messages. Messages are for confirming `Infinite allowance` and `taking away allowance` of an ERC20 token.

**Comment by aminlatifi** [comment]
See the updates on develop.giveth.io
