### ISSUE TITLE
CSV update

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1255]
Get the feedback and make the new CSV doc

**Comment by lorelei1** [comment]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d8df8b0ad3696263686d1f6 
something wrong with the way the sequencing of actions is portrayed in the CSV. Says the money was "returned" on Oct 1st, 4 days before it was "delegated - canceled later" on Oct 5th
.... I assume maybe oct 5th is just when it got the new status title/action title of "delegated - canceled later" but really it should still say the date that it was actually delegated

**Comment by lorelei1** [comment]
<img width="963" alt="Screen Shot 2020-06-16 at 3 57 02 PM" src="https://user-images.githubusercontent.com/38163206/84784064-2bc8a800-afea-11ea-8854-1578a6325330.png">

**Comment by GriffGreen** [comment]
Making new template in tab "Revised Goal"

**Comment by GriffGreen** [comment]
Making new template in tab "Revised Goal" https://docs.google.com/spreadsheets/d/1QECQfXulcLXg-fGQzl2UjtrHNHOK36V1m-w0guzgMy8/edit#gid=1602448578

**Comment by lorelei1** [comment]
Status report function should be by milestone rather than by event

**Comment by GriffGreen** [comment]
CSV still needs to have a little more work done

**Comment by GriffGreen** [comment]
Updated!!!

**Comment by GriffGreen** [comment]
https://docs.google.com/spreadsheets/d/1QECQfXulcLXg-fGQzl2UjtrHNHOK36V1m-w0guzgMy8/edit#gid=1272119542

**Comment by GriffGreen** [comment]
New doc: https://docs.google.com/spreadsheets/d/1OXiq_TQgMaS5KLFvpAo1Y2homEXjS10dHybioTQE6OE/edit?usp=sharing

**Comment by aminlatifi** [comment]
@GriffGreen Any progress?

**Comment by GriffGreen** [comment]
Nope :-(

**Comment by aminlatifi** [comment]
@Danibelle can you dedicate time to this?

**Comment by Danibelle** [comment]
Meeting scheduled for 8am CR/9am Eastern to comb for issues with Griff!

**Comment by GriffGreen** [comment]
Time to implement!!! :-D @aminlatifi go for it!

**Comment by aminlatifi** [comment]
@Danibelle @GriffGreen new CSV is deployed, you can test it
