### ISSUE TITLE
Pending Transaction ?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1256]
https://etherscan.io/tx/0x25dc311a1a8c65c0e685499bd3cf02d54ad65bc12afd8b1fdec0154c2a64dde9

https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5ea31c21f00d813b5f62b2ae

**Comment by aminlatifi** [comment]
@GriffGreen Donation doesn't have rinkeby transaction hash! 
I found the rinkeby txHash, https://rinkeby.etherscan.io/tx/0x8b082678200249418a8fac3f789c7e10b3667706c180d74156be05eebe5db3dd
However there is no events are recorded for this transaction!

**Comment by aminlatifi** [comment]
I added the events by some scripts, but that was weird!
