### ISSUE TITLE
Fair Data Society Delegation Stuck

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1262]
Delegated from [FDS DAC](https://beta.giveth.io/dacs/5c34b2e746d9c67925654070) to the [Fairdrop Campaign.](https://beta.giveth.io/campaigns/5c81316527ae4211c836be4e). see Donated Amount in DAC screenshot:

![image](https://user-images.githubusercontent.com/39466970/81989523-a02eb680-95fa-11ea-82e1-d5c3ac93279f.png)

**Comment by aminlatifi** [comment]
Are you sure that delegations has happened? There is no corresponding events in network!

**Comment by mmohorko** [comment]
Yes. I delegated around 770 SAI and 1.3 ETH from the FDS DAC to the Fairdrop campaign. The balance in the DAC is now 0 SAI. 

The money was there before (see the Tg discussion screenshots).

<img width="464" alt="Screenshot 2020-05-15 at 17 29 42" src="https://user-images.githubusercontent.com/45455085/82068028-c4a99200-96d1-11ea-8e72-30f8432bf139.png">

**Comment by aminlatifi** [comment]
> Yes. I delegated around 770 SAI and 1.3 ETH from the FDS DAC to the Fairdrop campaign. The balance in the DAC is now 0 SAI.
> 
> The money was there before (see the Tg discussion screenshots).
> 
> <img alt="Screenshot 2020-05-15 at 17 29 42" width="464" src="https://user-images.githubusercontent.com/45455085/82068028-c4a99200-96d1-11ea-8e72-30f8432bf139.png">

Money is there :D
Donations followed regular procedure and after 3 days moved to campaign. During these 3 days giver could veto (reject) or approve (money goes through immediately).
