### ISSUE TITLE
The Value of Donation is Incorrect in Notification Email

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1269]
I donated 0.002 xDAI but I see  2000000000000 XDAI in notification email.
![Screenshot from 2020-05-23 18-13-28](https://user-images.githubusercontent.com/65175075/82732224-2b0d6080-9d21-11ea-9efd-6cd83a5740f5.png)
![Screenshot from 2020-05-23 18-14-38](https://user-images.githubusercontent.com/65175075/82732250-4d9f7980-9d21-11ea-9ac4-deea3d89ced4.png)

**Comment by GriffGreen** [comment]
For Develop so not a big deal....? might be worth checking this to learn this repo

**Comment by aminlatifi** [comment]
@horus2021 It should be fixed on develop, please check it again.

**Comment by horus2021** [comment]
@aminlatifi  Great Job! It works.
![email bug solved](https://user-images.githubusercontent.com/65175075/83281445-5b577200-a1ed-11ea-96bf-e86fb73a4f2e.png)
