### ISSUE TITLE
Commons Stack Milestone Pics aren't showing up

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1273]
Related to #1196  but i thought i would make it specific 

<img width="950" alt="Screen Shot 2020-05-24 at 1 57 18 PM" src="https://user-images.githubusercontent.com/14945613/82753526-95c4a780-9dc6-11ea-8a6c-700d521281cf.png">

**Comment by GriffGreen** [comment]
Issue is that new pics might not be pinned?
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

**Comment by aminlatifi** [comment]
The not showing images cannot be found by ifps, they aren't in pinned file list! They may have been lost after updating ipfs

**Comment by horus2021** [comment]
![common stack milestone picture](https://user-images.githubusercontent.com/65175075/83164337-59c07800-a121-11ea-9567-58c59f5d9d2f.png)
pictures are showing.
Tnx @aminlatifi.

**Comment by horus2021** [comment]
![milestone without pics](https://user-images.githubusercontent.com/65175075/83176240-584b7b80-a132-11ea-88d6-969db5843049.png)
some of pics aren't still showing up
