### ISSUE TITLE
Canceling a Campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1285]
I want to cancel the Tennagraph campaign... will it work?

**Comment by horus2021** [comment]
Hey @GriffGreen , It is not crystal clear for me what you mean by cancel. If you mean to cash out that 1 ETH in the balance, a **workaround** would be propose (create) a milestone and set yourself as recipient! 
Andreas got rid of his last SAI in GRACEaid with this trick.  I hope it works for you. If you mean something else tell me. ;)

**Comment by horus2021** [comment]
@GriffGreen  is going to cancel the campaign after @aminlatifi comes back vacation. It is a good opportunity for debug.

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c97f58c150a830a701e161a

**Comment by GriffGreen** [comment]
Ok so the owner can't cancel? Only the reviewer can i guess?
https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5

Also... what will happen when it cancels? Will it be wiped off the platform? or will it be visible still... The desired behavior is that it will stay there.

Ideally, when canceled, the campaign will remain visible, but then not be able to receive donations

**Comment by GriffGreen** [comment]
And where will the money go when a campaign gets canceled? If it came from a DAC, what happens, if it came from a direct donation what happens?
Who can cancel a Campaign? It seems like only Reviewers?

**Comment by GriffGreen** [comment]
Reviewers and Campaign owners can cancel... but only from 
https://beta.giveth.io/my-campaigns

**Comment by aminlatifi** [comment]
> Ok so the owner can't cancel? Only the reviewer can i guess?
> https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5
> 
> Also... what will happen when it cancels? Will it be wiped off the platform? or will it be visible still... The desired behavior is that it will stay there.
> 
> Ideally, when canceled, the campaign will remain visible, but then not be able to receive donations

Home page just shows campaigns which are active (not pending neither canceled)

**Comment by GriffGreen** [comment]
So make tests around cancelling a campaign

**Comment by GriffGreen** [comment]
We have changed how we deal with canceled projects...

**Comment by aminlatifi** [comment]
Tested, campaign is canceled and its donations (those has remaining value) are reverted. 
This is returned donation corresponding pledge: 
```
{
  '0': '103230000000000000000',
  '1': '360',
  '2': '0',
  '3': '0',
  '4': '0',
  '5': '0',
  '6': '0xe1DA0672bDBdBc469E82cCACCe9e4c7C79dAF6cf',
  '7': '0',
  amount: '103230000000000000000',
  owner: '360',
  nDelegates: '0',
  intendedProject: '0',
  commitTime: '0',
  oldPledge: '0',
  token: '0xe1DA0672bDBdBc469E82cCACCe9e4c7C79dAF6cf',
  pledgeState: '0' }

```
There is a point to notice, those donations are returned to source, giver in this case. In giver **My Delegations** page the returned donation is listed, but it doesn't have delegate button!
![image](https://user-images.githubusercontent.com/5684607/95655885-56012100-0b17-11eb-8062-30185796f346.png)

@GriffGreen I guess we should put delegate button for it to allow user pay it to other project. What do you think?

**Comment by GriffGreen** [comment]
Yeah the delegate button would solve the issue!

**Comment by GriffGreen** [comment]
#1371
