### ISSUE TITLE
We lost some images it seems from IPFS, we need a default image for them

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1288]
Following #1273 if images dont show up then we need to make them show the default Giveth Image

This should happen in the database, not the front end.

BUT FIRST!!!

Let's find all the images we can and pin them ourselves!

**Comment by krrisis** [comment]
Came here to log that issue. 
Images missing that I see below on DACs:

- So, Commons Stack DAC & Campaign are two you can do Griff
- Children in Baja is @lorelei1 
- Giveth security is you as well @GriffGreen 

![image](https://user-images.githubusercontent.com/6533925/83557027-375b9f80-a511-11ea-807c-7053a5bfb59e.png)

Campaigns: 

Well... I don't really need to look, most of them are yours griff :)

![image](https://user-images.githubusercontent.com/6533925/83557344-c49ef400-a511-11ea-9316-873227fc2072.png)

**Comment by GriffGreen** [comment]
https://pinata.cloud/pricing  for redundancy... so it doesnt happen again but it seems like these pictures are lost :-(

**Comment by GriffGreen** [comment]
Stefaan Ponnet, [01.06.20 12:56]
there are different things you can do to improve IPFS reachability yeah

Stefaan Ponnet, [01.06.20 12:56]
you can indeed set up some pinning consortium ,

Stefaan Ponnet, [01.06.20 12:56]
you can use an external service like pinata

Stefaan Ponnet, [01.06.20 12:57]
and you can also link a few IPFS servers together by configuring their enode id's together in the config file

Stefaan Ponnet, [01.06.20 12:58]
when we add new hashes in our AVADO store - we also have a script that 'warms up' some well known IPFS servers

Stefaan Ponnet, [01.06.20 12:58]
by requesting the data through those gateways, thereby improving the availablility

Stefaan Ponnet, [01.06.20 13:00]
https://github.com/ipfs/public-gateway-checker/blob/master/gateways.json
