### ISSUE TITLE
Update reviewer list

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1292]
I think @Danibelle worked on this at some point but can't seem to find that issue, so proposing the following names to be deleted/added to the reviewer list : 

Add: 
- Jeff Emmett - 0x778549Eb292AC98A96a05E122967f22eFA003707

Delete: 
- Emex
- Quazia
- Parker Williams
- Anonymous user
- Satya

**Comment by GriffGreen** [comment]
<img width="346" alt="Screen Shot 2020-06-03 at 5 08 10 PM" src="https://user-images.githubusercontent.com/14945613/83654108-eb663480-a5bc-11ea-977b-ea339b43c536.png">

**Comment by GriffGreen** [comment]
Remove
CaraB
Maria
Cleo
Adria
Quazia
Griff's Boss
Magenta
Oz
Abram

**Comment by krrisis** [comment]
main reason for me to create this issue was to add jeff, the deleting of the others is great but was secondary :) Could this still be done? (see original issue above)

**Comment by aminlatifi** [comment]
@krrisis I added jeff to reviewer list.
