### ISSUE TITLE
Tried to donate but the thing freaked out

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1294]
I did an infinite approve... and then the metamask popped up and then i changed the gas price and then clicked accept and then it freaked out and the tx was failed

It was to this milestone
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e8d29c8cb08e33938daff2c

Issue type: **Error**
Something went wrong with your donation.

**TransactionLink:**
https://etherscan.io/tx/undefined => {
  "code": -32603,
  "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":720237913511,\"jsonrpc\":\"2.0\",\"params\":[\"0xf8e9608502540be40082c0aa9430f938fed5de6e06a9a7cd2ac3517131c317b1e780b8844c4316c700000000000000000000000000000000000000000000000000000000000007ee00000000000000000000000000000000000000000000000000000000000008230000000000000000000000006b175474e89094c44da98b954eedeac495271d0f0000000000000000000000000000000000000000000000050aa25f43cf54000026a066bddc031d0722ee82ece9b0efe9458aa0165845d2d69d5b80f5fce18426797ea0385430a3b04f9a2fc74cde17e5891f617bb41577676bb6c477dc641e2cce14df\"],\"method\":\"eth_sendRawTransaction\"} [object Object]",
  "stack": "Error: Error: [ethjs-rpc] rpc error with payload {\"id\":720237913511,\"jsonrpc\":\"2.0\",\"params\":[\"0xf8e9608502540be40082c0aa9430f938fed5de6e06a9a7cd2ac3517131c317b1e780b8844c4316c700000000000000000000000000000000000000000000000000000000000007ee00000000000000000000000000000000000000000000000000000000000008230000000000000000000000006b175474e89094c44da98b954eedeac495271d0f0000000000000000000000000000000000000000000000050aa25f43cf54000026a066bddc031d0722ee82ece9b0efe9458aa0165845d2d69d5b80f5fce18426797ea0385430a3b04f9a2fc74cde17e5891f617bb41577676bb6c477dc641e2cce14df\"],\"method\":\"eth_sendRawTransaction\"} [object Object]"
}

**Comment by GriffGreen** [comment]
transaction that worked
https://etherscan.io/tx/0xa59f1f587fe7399ac4a97f467d121123a94a60c4bf24877aefd8f492fc714bd3

Data:
0x4c4316c700000000000000000000000000000000000000000000000000000000000007ee00000000000000000000000000000000000000000000000000000000000008230000000000000000000000006b175474e89094c44da98b954eedeac495271d0f0000000000000000000000000000000000000000000000050aa25f43cf540000

**Comment by aminlatifi** [comment]
Probably it's the metamask problem happens on low gas values!

https://ethereum.stackexchange.com/questions/59454/catching-errors-with-gas-issues

https://ethereum.stackexchange.com/questions/52274/error-error-ethjs-rpc-rpc-error-with-payload-id6223335088050-jsonrpc

> [ethjs-rpc] rpc error with payload in Solidity 0.5.0 happens if the passed parameters to the contract is empty, hence from DApp console log all parameters and see if any values are being passed as empty or null. Once you address the empty values to some concrete values rpc error will go way and transaction will be success.
