### ISSUE TITLE
Canceled donations need to be handled

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1295]
When a donation is canceled... it stays pending forever... sort of related to #1133

**Comment by horus2021** [comment]
@aminlatifi  suggest a solution (using a timer for donation) for this issues. 
We need to discuss with @aminlatifi  on his solution and estimation on time to develop it.

**Comment by GriffGreen** [comment]
if the nonce on the user's accounts increments then it should be taken off the list completely
