### ISSUE TITLE
Andre's DApp Milestones

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1304]
I would suggest canceling all 4 of Andre's Milestones and ask that they be remade in either ETH or DAI... He remade them in SAI which give him a 30% profit over DAI. 

While i appreciate Andre's willingness to delay payment, waiting for ETH to rise out of the slump... I still would like to just give him the USD value agreed upon... and I didnt think SAI Milestones were allowed on the DApp any more.

**Comment by arbreton** [comment]
Took care of redoing them 👍 !

**Comment by GriffGreen** [comment]
Now i just need to fund them

**Comment by aminlatifi** [comment]
@arbreton has collected his milestones...close it

**Comment by arbreton** [comment]
Confirming!, also feel free to assign me side tasks if needed here or on giveth 2.0, have an excellent week guys!, crypto boom 2020 is coming
