### ISSUE TITLE
Cron job for simulation script that logs errors

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1307]
nice to run periodically and use to find issues we missed

**Comment by GriffGreen** [comment]
Connected to #1308

**Comment by GriffGreen** [comment]
If the simulation script finds a conflict... it creates an automatic github issue.. this will take a bot

**Comment by aminlatifi** [comment]
Created a cron job to run simulation script daily, it will produce logs saved in a specific directory so far.

**Comment by aminlatifi** [comment]
If cron job script works properly for a period of days, next step would be creating automatic github issues whenever scripts produces some logs and put logs in issue.

**Comment by horus2021** [comment]
@aminlatifi tells that the script has worked since June.
Next step #1436
