### ISSUE TITLE
Make a new Giveth NPM package namespace

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1311]
Needed for #893

**Comment by GriffGreen** [comment]
and #812

**Comment by aminlatifi** [comment]
Giveth org is created already in npm!
![image](https://user-images.githubusercontent.com/5684607/85522081-6cdc4000-b61a-11ea-946a-7927029bb4a4.png)

**Comment by aminlatifi** [comment]
@GriffGreen Can you add me to group with enough permission whenever you get access
