### ISSUE TITLE
Sent donation... but still says pending after 3 hours

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1313]
Sent this direct donation
https://etherscan.io/tx/0x57a6ba0a319eac98c64141d86ef1c2e3e208c938ed133c0a9cc4795fcca8e1e8

to Hadi's Milestone: https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ee12822ed35f954feb45462

Milestone shows "pending"
<img width="1025" alt="Screen Shot 2020-06-17 at 9 11 11 PM" src="https://user-images.githubusercontent.com/14945613/84939945-68c29680-b0df-11ea-94a2-ed53d0113a3f.png">

https://bridge.beta.giveth.io/ shows it didnt make it across....

**Comment by GriffGreen** [comment]
<img width="1281" alt="Screen Shot 2020-06-18 at 4 56 13 PM" src="https://user-images.githubusercontent.com/14945613/85036826-e5f41700-b184-11ea-890d-d568cdcb4d39.png">
WOW! Weird! 

The bridge is working for DAI but not ETH maybe? or it was just a weird 1 off bug?
we will want to test this.

**Comment by aminlatifi** [comment]
> <img alt="Screen Shot 2020-06-18 at 4 56 13 PM" width="1281" src="https://user-images.githubusercontent.com/14945613/85036826-e5f41700-b184-11ea-890d-d568cdcb4d39.png">
> 
> WOW! Weird!
> The bridge is working for DAI but not ETH maybe? or it was just a weird 1 off bug?
> we will want to test this.

The transaction has failed maybe!
Notice the status of corresponding record in bridge database
![image](https://user-images.githubusercontent.com/5684607/85199922-80309800-b308-11ea-92ab-e04d693363ea.png)

**Comment by GriffGreen** [comment]
Weird I wonder why

**Comment by aminlatifi** [comment]
@GriffGreen can you see whether the donation is returned to giver account or not?

**Comment by aminlatifi** [comment]
According to bridge produced log it seems bridge used wrong nonce value to do the transaction `nonce too low`.

**Comment by aminlatifi** [comment]
I guess the transaction has done! 
https://rinkeby.etherscan.io/tx/0xe18bd2ed77c9d171ec43914773c5195151874d7fc77aabefa9d8873d7944b805

**Comment by aminlatifi** [comment]
> I guess the transaction has been sent!
> https://rinkeby.etherscan.io/tx/0xe18bd2ed77c9d171ec43914773c5195151874d7fc77aabefa9d8873d7944b805

The transaction is new though!

**Comment by aminlatifi** [comment]
I manually changed the state of record in db to `to-send`, maybe that was helpful.
