### ISSUE TITLE
I have an account with no DAI and the dapp freaks out?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1314]
I'm using my Moloch addy... and i go to donate just as a test... and i see this:

<img width="1034" alt="Screen Shot 2020-06-19 at 2 15 31 AM" src="https://user-images.githubusercontent.com/14945613/85083705-d26f9d00-b1d2-11ea-846a-ee7acb9ba179.png">

Maybe because i have no DAI?

Any way if thats the case it needs to be fixed... maybe we can make an affiliate link to 1inch.exchange or something and have someone go trade DAI?

**Comment by GriffGreen** [comment]
the slider was hidden and the screen just looked weird... maybe there should be a different pop up for it?

**Comment by GriffGreen** [comment]
griff needs to make a referral link
There might be other scenarios where this might be used

**Comment by GriffGreen** [comment]
Referral link: https://1inch.exchange/#/r/0x8f951903C9360345B4e1b536c7F5ae8f88A64e79

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/86357833-ae589500-bc83-11ea-9394-e3e0592be8a2.png)

![image](https://user-images.githubusercontent.com/5684607/86358027-02fc1000-bc84-11ea-9682-91016cbaea98.png)


@GriffGreen I added `But/Change Crytpo` button to donate modal... probably you have better design in your mind

**Comment by GriffGreen** [comment]
Exchange Crypto
