### ISSUE TITLE
DApp is down?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1318]
<img width="1584" alt="Screen Shot 2020-06-22 at 9 10 31 PM" src="https://user-images.githubusercontent.com/14945613/85326029-d77f6580-b4cc-11ea-8288-10ec0a928464.png">
Issue type: **Error**
Something went wrong with getting user profile. Please try again after refresh.

**Name:**
Timeout of 30000ms exceeded calling users::find

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

Error: Timeout of 30000ms exceeded calling users::find
    at https://d33wubrfki0l68.cloudfront.net/js/91d54b13455a5fe525c3334a5b8db7338e20bba3/static/js/main.8dc3c142.js:1:2204273
</details>

**Comment by aminlatifi** [comment]
There was a problem on atlas mongodb

> There were some scheduled maintenance on your cluster which was going through.
My apologies for any inconvenience this may have caused you.
Minor MongoDB Atlas upgrades, and maintenance initiated by our system can cause a new primary to be elected.
Atlas migrates one node at a time in a rolling fashion, starting with the secondary nodes first and then the primary. Time between elections is typically a few seconds.
To ensure the application(s) can handle elections gracefully, please include all three nodes specified in your URI connection string. 
To test the failure of a primary replica set member in your Atlas cluster and observe how your application responds to a replica set failover, you can use the test failover (please note that the test failover is not available with the free tier (M0), M2 and M5 Instances).
Again, I apologize for any inconvenience the upgrade may have caused. Please feel free to reach out if you have any further questions.

**Comment by aminlatifi** [comment]
Updated mongo connection string to include replica all three nodes in order to prevent such problem in future.
