### ISSUE TITLE
Can't edit the DAC from DAC screen

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1327]
I expected to see an edit button here:
<img width="1256" alt="Screen Shot 2020-06-27 at 3 22 11 PM" src="https://user-images.githubusercontent.com/14945613/85923260-0cebd080-b88a-11ea-85cf-dac0629d0398.png">

**Comment by aminlatifi** [comment]
Edit feature is not implemented for DACs unlike other types of projects.

**Comment by GriffGreen** [comment]
https://github.com/Giveth/lpp-dac/blob/437f56e8763a7d5d066d1d2f599e00236bf95723/contracts/LPPDac.sol#L161

**Comment by GriffGreen** [comment]
<img width="858" alt="Screen Shot 2020-07-01 at 5 00 48 PM" src="https://user-images.githubusercontent.com/14945613/86259558-733f5e80-bbbc-11ea-8d1b-8878712227e7.png">
https://beta.giveth.io/my-dacs
