### ISSUE TITLE
Add PAN to the DApp and consider adding other tokens

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1334]
This will take some multisig work... :-D
We wait to drain all the SAI and then we make a strategy for the left over SAI and adding PAN... it will involve a bunch of Giveth Multisig Transactions

**Comment by aminlatifi** [comment]
We should wait till all sai is exited

**Comment by krrisis** [comment]
I would not add more tokens and just stick with dai & eth. Keep it simple for people, we don't know if Pan will stay in the long run. Simplicity will support our mission.

**Comment by GriffGreen** [comment]
We will need to add PAN... cause Giveth 2 has a lot of Pan and they will want to use the dapp to distribute funds at the end of the month

**Comment by krrisis** [comment]
Well you could exchange it for DAI when you need it - this is to me a typical example of scope creep. This quarter it's PAN, next quarter some other project will pop up. But hey, can only give the advice, your call :)

**Comment by GriffGreen** [comment]
It costs money to exchange and needless friction.

I think we should add PAN, ANT, USDC and WBTC

PAN for Panvala to use the DApp for next round as opposed to Gitcoin :-D

ANT to align with this community around TE Commons, Conviction Voting and ABCs

USDC because it is the most stable token used for donations currently on Gitcoin and the easiest stable coin to obtain with fiat for normal people (via coinbase) 

WBTC because its use is growing dramatically and people do like using BTC as a unit of account in crypto

**Comment by GriffGreen** [comment]
Pan is not on crypto compare :-(

https://www.coingecko.com/en/coins/panvala-pan/usd#panel
^^^ This is the Pan we want!

This is the pan con crypto compare: https://www.cryptocompare.com/coins/pan/overview

**Comment by arbreton** [comment]
updating progress https://github.com/Giveth/feathers-giveth/pull/234

**Comment by aminlatifi** [comment]
No

**Comment by arbreton** [comment]
https://github.com/Giveth/feathers-giveth/pull/239

**Comment by aminlatifi** [comment]
> [Giveth/feathers-giveth#239](https://github.com/Giveth/feathers-giveth/pull/239)
It has conflict and few points to fix

**Comment by GriffGreen** [comment]
moved to beta and needs to be tested.

**Comment by GriffGreen** [comment]
Benjamin and Amin will confirm it works

**Comment by aminlatifi** [comment]
@arbreton We tested donating using PAN. We donated 4 PAN and the usdValue was set 0.16$, while the coingecko price was 0.09$ per token at the time of donating. Can you check it? getting rate maybe has problem, or maybe not.

**Comment by aminlatifi** [comment]
https://feathers.beta.giveth.io/donations/5f761b8342d4cd1c03dce06c

**Comment by aminlatifi** [comment]
@arbreton it's the donation https://feathers.beta.giveth.io/donations/5f761b8342d4cd1c03dce06c

**Comment by GriffGreen** [comment]
@arbreton to tackle this this week

**Comment by GriffGreen** [comment]
Add ANT, Wbtc and USDC to the front end!

**Comment by GriffGreen** [comment]
#1467

**Comment by aminlatifi** [comment]
> Add ANT, Wbtc and USDC to the front end!

Added, as these tokens are supported by cryptocompare they should work like other tokens.
