### ISSUE TITLE
Aggregate the leader board so that it sorts by the top donors not the top donations  

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1339]
<img width="1012" alt="Screen Shot 2020-07-06 at 2 27 51 PM" src="https://user-images.githubusercontent.com/14945613/86593137-fda90900-bf94-11ea-93c4-1a9e7a9ec1d8.png">
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

One donation of 25k is on top but there are several donors that have donated more than that... Santa and Anonymous Donors (or Gitcoin)

**Comment by GriffGreen** [comment]
Make this a leader board and not a list of the Donations!

List the USD Value, using the date that the ETH hits the milestone or campaign

**Comment by aminlatifi** [comment]
Need to redesign the donation table... we should aggregate based usdValue of donations

**Comment by krrisis** [comment]
okay so this was supposed to be a leaderboard. :) See my issue #1406. I would order them by date. Or you can have the two options with just an arrow next to date & amount so people can pick. But in any case not randomized.

**Comment by GriffGreen** [comment]
Yeah, @krrisis with the CSV feature in place, we can make this a true leaderboard

**Comment by GriffGreen** [comment]
Leaderboard should just have:


Rank | Person | Total Donated | Address
#1 | Santa | $40,000 | 0x839395e20bbB182fa440d08F850E6c7A8f6F0780

Then there should be a plus button that shows the history of their donations and shows:

Date | Amount | Currency | USD Equiv | (Delegated or Direct) | (IF DELEGATED) Delegator

**Comment by markoprljic** [comment]
WIP 
<img width="1218" alt="Image 2020-09-08 at 4 24 59 pm" src="https://user-images.githubusercontent.com/5704285/92489258-e1715480-f1ef-11ea-867e-581459e1309b.png">

**Comment by markoprljic** [comment]
Attached new version, cleaner. 
<img width="1195" alt="Image 2020-09-09 at 7 42 37 am" src="https://user-images.githubusercontent.com/5704285/92559065-2341df80-f270-11ea-9f3e-49f4affc6c6e.png">

**Comment by aminlatifi** [comment]
Donation aggregate service is up now on beta 😃
@mahdine Test it by such requests: https://feathers.beta.giveth.io/aggregateDonations/?id=5b39d45e14cec916d00dab20&$limit=2&$skip=1
Notice result has donations  and user object too, and supports pagination.

**Comment by aminlatifi** [comment]
total field is added to the result of API

**Comment by aminlatifi** [comment]
https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2453%3A23
