### ISSUE TITLE
Tried to update profile picture but the picture screen didnt come up

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1340]
https://beta.giveth.io/profile

Looks like we lost a lot of profile pics in the IPFS issue... so we might want to make this fix soon.

<img width="957" alt="Screen Shot 2020-07-06 at 2 33 18 PM" src="https://user-images.githubusercontent.com/14945613/86593547-bb33fc00-bf95-11ea-90be-fc24f2628000.png">
I selected the file... but then nothing popped up to crop it

It popped up after i did the transaction tho...?

<img width="978" alt="Screen Shot 2020-07-06 at 2 36 10 PM" src="https://user-images.githubusercontent.com/14945613/86593734-0ea64a00-bf96-11ea-9941-2b0a6377b64c.png">

**Comment by horus2021** [comment]
Hey @GriffGreen I cannot reproduce this issue. I smoothly update my profile in beta.giveth.io by just one signing in Rinkeby.

**Comment by aminlatifi** [comment]
I couldn't reproduce this bug, event by bringing down ipfs server! 🤔

**Comment by aminlatifi** [comment]
I probably happens for users with empty value in their avatar field (their ipfs pics have been lost)
