### ISSUE TITLE
Milestone duplicated on UI?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1341]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

<img width="980" alt="Screen Shot 2020-07-06 at 3 35 04 PM" src="https://user-images.githubusercontent.com/14945613/86599045-5fba3c00-bf9e-11ea-875f-da7606d79cc0.png">

**Comment by horus2021** [comment]
Yes. I also see this issue!

**Comment by horus2021** [comment]
![Screenshot from 2020-07-08 17-03-13](https://user-images.githubusercontent.com/65175075/86919132-00def900-c13d-11ea-9279-24d282183dc0.png)

**Comment by GriffGreen** [comment]
#877

**Comment by GriffGreen** [comment]
#876 #639

**Comment by aminlatifi** [comment]
Two identical projects has been created by smart contract!

**Comment by lorelei1** [comment]
Hm... I honestly don't remember, sorry! I think I created some milestone recently where it didn't take and i had to recreate it... that rings a bell in my head but I really couldn't say if it's this milestone.

**Comment by lorelei1** [comment]
Is there a way to verify on etherscan if I did 2 txs creating this milestone?

**Comment by papermache** [comment]
@aminlatifi has this been fixed?

**Comment by aminlatifi** [comment]
Sorry for late update... Those two milestones were created by different TXs
