### ISSUE TITLE
Wallet is unlocked... not sure why it wont let me propose this milestone

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1348]
I started making a milestone, then went to sleep and woke up to finish the milestone... but it wouldn't let me submit it.... I have had this problem before... it seems like if you take too long to propose a milestone, it gets lost....

Ok wow... after making this issue, and trying to propose the milestone a third time to get a good screen shot, it worked!!!! ¯\_(ツ)_/¯

Issue type: **Error**
Something went wrong with the Milestone creation. Is your wallet unlocked?

**TransactionLink:**
"undefinedtx/undefined => {}"

**Comment by horus2021** [comment]
hey @GriffGreen and @aminlatifi, 
I want to regenerate  this bug by proposing a  dummy milestone in beta.givet. Which campaign is a safe place. The main point it that I do not want to make clutter.

**Comment by GriffGreen** [comment]
Improve error handling on this so that we can know where the connection is failed... websockets? feathers?

We should have a more resilient front end so that if the connection to feathers is broken it tries to reconnect on a request

**Comment by aminlatifi** [comment]
@peymannaderi3 Do we have fixed this? It's the same issue about error thrown by web3 (MetaMask)
