### ISSUE TITLE
Ask Anon Donors to fill out a profile  

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1349]
If it is an anon donor... after the donation is complete we should ask them to make a profile if they want to track their donations and not be anon, I think this can replace the "Thank you for donating, want to donate to giveth" pop up

And then we add the "Thank you for donating, want to donate to giveth" pop up after people make their profile ? 

The challenge there is that we require people to switch their metamask on both moves... but honestly I think its worth it.

**Comment by horus2021** [comment]
Hey @aminlatifi,   Do you think that I (@horus2021 ) can fix this issue?

**Comment by GriffGreen** [comment]
The new pop up should say:

"Thank you for donating, fill out your Giveth Profile if you want recognition for your contribution"

(then have 2 buttons)

No Thanks      -       Ok

**Comment by horus2021** [comment]
I have fixed 

After successful donation 

1) anon donor
sees a popup suggest fill out profile
2)known donor 
sees a popup suggest donating to Giveth (as before )

**Comment by GriffGreen** [comment]
#1413
