### ISSUE TITLE
Allow donors to leave messages when they donate...

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1350]
This has a lot of uses... some times its nice for accounting.. most times its great for people to send words of encouragement, either way it would be a powerful feature to make donating more engaging ;-D

Can be added to the leader board in #1339

**Comment by GriffGreen** [comment]
<img width="931" alt="Screen Shot 2020-07-10 at 1 21 33 AM" src="https://user-images.githubusercontent.com/14945613/87100091-c44df300-c24b-11ea-851d-42f0c917408c.png">
Also when Delegating? Might need to make it obvious if the message came from someone delegating or donating

**Comment by GriffGreen** [comment]
Take care in the simulation script!!

**Comment by aminlatifi** [comment]
Refs #1339

**Comment by GriffGreen** [comment]
We can decide later if we should let the delegators leave a comment.... for now lets only enable donors to comment

**Comment by GriffGreen** [comment]
https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2453%3A23

**Comment by mdehghani** [comment]
It is closed by #1519

**Comment by aminlatifi** [comment]
Yes, it should be tested

**Comment by horus2021** [comment]
This works in develop.giveth.io for milestone.I can see my comment in Donation list see below. 
![image](https://user-images.githubusercontent.com/65175075/100522994-26d76980-31c2-11eb-9bcb-72c0486cc12b.png)


However for campaign it does not work. I can not see my donation in leaderboard and my comment. I am not sure the exact requirement. @aminlatifi please make requirement clear for me.

**Comment by aminlatifi** [comment]
> This works in develop.giveth.io for milestone.I can see my comment in Donation list see below.
> ![image](https://user-images.githubusercontent.com/65175075/100522994-26d76980-31c2-11eb-9bcb-72c0486cc12b.png)
> 
> However for campaign it does not work. I can not see my donation in leaderboard and my comment. I am not sure the exact requirement. @aminlatifi please make requirement clear for me.

On campaign we use leaderboard component and it only shows donation with usdValue greater than zero. Since on develop.giveth.io all the tokens are testing ones, no rate exists for them and their usd values can be zero

**Comment by aminlatifi** [comment]
@horus2021 It should be fixed now, you can test it
![image](https://user-images.githubusercontent.com/5684607/100541495-90568700-3259-11eb-82d4-0a37499c9379.png)

**Comment by horus2021** [comment]
It works. Good Job!!!
![image](https://user-images.githubusercontent.com/65175075/100552186-c10ae080-329a-11eb-8033-03f4ced4c57b.png)
