### ISSUE TITLE
Accepted 4 milestones all at once... but one didnt show up

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1351]
Why didn't Markos show up? 
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f06e3b3fdc3662810267c4a

I imagine the simulator will catch this and it will pop up tomorrow :-D

<img width="1164" alt="Screen Shot 2020-07-10 at 1 31 39 AM" src="https://user-images.githubusercontent.com/14945613/87100619-2d823600-c24d-11ea-8865-a3adf0ac82e4.png">

**Comment by aminlatifi** [comment]
It has created
