### ISSUE TITLE
Default pipeline is "in progress" for new issues?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1352]
<img width="417" alt="Screen Shot 2020-07-10 at 1 33 10 AM" src="https://user-images.githubusercontent.com/14945613/87100707-6b7f5a00-c24d-11ea-865e-43a40a70fc41.png">
How did that happen?

**Comment by horus2021** [comment]
I found a quick fix for this issue. I moved New Issues pipeline to the beginning of board.
I checked out ZenHub for I a better solution, but I cannot find.
