### ISSUE TITLE
feature request! DAI value of total donations should be listed on campaigns and milestones

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1353]
Remember how you loved this in the metamask phone app @GriffGreen ?
I think we would love it just as much in Giveth :)

**Comment by lorelei1** [comment]
of course eventually it would be great to have a "native currency" choice - where on your profile in the DApp you can select which currency you would like to see things denominated in. Then your milestones and campaigns could show a total in DAI, USD, EURO, ETH value or whatever you prefer

**Comment by GriffGreen** [comment]
We can easily use the price from the day before, but it would be much better to use a price from today...

So it would be "Approximate value in Campaign"

**Comment by aminlatifi** [comment]
@mdehghani Let's start 😃

**Comment by aminlatifi** [comment]
@mdehghani Good job for campaigns, just the label can be better. I suggest `Current Balance Value`. @GriffGreen @lorelei1 probably have better options.
For milestone we have a detail column
<img width="496" alt="Screen Shot 2020-10-31 at 15 56 10" src="https://user-images.githubusercontent.com/5684607/97779199-d1437900-1b91-11eb-83c3-7508236999fa.png">

**Comment by aminlatifi** [comment]
@lorelei1 @GriffGreen I told @mdehghani  to just compute value for current balance, because current value of total donations (which some part is spent) is immaterial in my view

**Comment by GriffGreen** [comment]
merged to develop, need to add the new whitelist for the currencies
