### ISSUE TITLE
Numbered & lettered list switches to just numbered list 

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1355]
In edit mode/when writing this milestone my list appears as I want it: with numbers and letters as subcategories:
<img width="851" alt="Screen Shot 2020-07-10 at 11 41 32 AM" src="https://user-images.githubusercontent.com/38163206/87187789-0760a280-c2ee-11ea-88e0-9cf279f5dc16.png">

But when the milestone is published, it appears only with a bunch of numbers:
<img width="954" alt="Screen Shot 2020-07-10 at 11 41 52 AM" src="https://user-images.githubusercontent.com/38163206/87187852-1f382680-c2ee-11ea-9848-671b850da3e4.png">

**Comment by GriffGreen** [comment]
We should probably try to fix this ... if its hard then we replace the component

**Comment by GriffGreen** [comment]
oooo! Excited to hear how this goes @mmnematollahi :-D

**Comment by GriffGreen** [comment]
<img width="898" alt="Screen Shot 2020-09-06 at 8 37 14 PM" src="https://user-images.githubusercontent.com/14945613/92332833-d64be680-f080-11ea-8509-6c7fcaba0426.png">

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f4fc629fb3dbe37aee4e04d

**Comment by GriffGreen** [comment]
Bullet points went away
