### ISSUE TITLE
Milestone Collected did not hit Bridge

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1356]
[Dani's Commons Simulator Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5e75396286c75d08d918cf2e) - hit collect on July 10 and donations show paid:

![image](https://user-images.githubusercontent.com/39466970/87231878-f3618300-c377-11ea-93df-916b53ca4a50.png)

But there's no transaction on the Bridge:
![image](https://user-images.githubusercontent.com/39466970/87231913-29066c00-c378-11ea-8626-2c2fee8a4f43.png)

**Comment by Danibelle** [comment]
Rinkeby Transaction Hash: https://rinkeby.etherscan.io/tx/0x9009f044ff93f9c7fc44adb94d8d9bd79830edd48ae4d6ed5e4beaa8558b21c7

**Comment by GriffGreen** [comment]
I see what happened... the bridge ran out of money... just sent some... might need to restart the bridge to get them to go thru....

Watch the Rinkeby-Mainnet Tab to see if the RED turns Green :-D

**Comment by aminlatifi** [comment]
Bridge was restarted and the red transactions went through

**Comment by Danibelle** [comment]
Nice! Thank you!
