### ISSUE TITLE
I want a "View on Etherscan" button!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1359]
It would be cool if one of these links was a "View it on etherscan" - it's odd that I can't click to see the tx on a block explorer directly from the Milestone!
<img width="906" alt="Screen Shot 2020-07-15 at 12 10 42 PM" src="https://user-images.githubusercontent.com/38163206/87585752-d0b8cc80-c6df-11ea-9d02-c2de493a01a0.png">
I think specifically for donations it's something users would desire. We don't need a button to view every contract interaction for every move on the DApp, but at least when it's a milestone that has a donation that says "Paid" I want to see that on etherscan

**Comment by lorelei1** [comment]
Especially when I see something like this:
<img width="381" alt="Screen Shot 2020-07-15 at 12 14 26 PM" src="https://user-images.githubusercontent.com/38163206/87586035-37d68100-c6e0-11ea-9987-f75a0c153db0.png">

Recipient pending? That makes me think that this isn't actually paid out to me, even tho it says it is below... an etherscan link would be a quick way to check that

**Comment by lorelei1** [comment]
This is the milestone https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c7e9b044db42c0731c603cb

**Comment by krrisis** [comment]
The 'paid' or 'pending' text could just be hyperlinked which avoids extra UX changes. Now you can get to etherscan by clicking the address under the profile name, where you see all the transactions. Unfortunately on rinkeby, so that should still be changed, see issue #1412

**Comment by aminlatifi** [comment]
Every status is a link now which refers to tx on either home or foreign network related to type of donation
![image](https://user-images.githubusercontent.com/5684607/90240775-226b8880-de3f-11ea-8b36-adc0660ed4aa.png)
