### ISSUE TITLE
Pending donations stuck in CS Campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1381]
<img width="826" alt="Screen Shot 2020-08-01 at 8 54 08 PM" src="https://user-images.githubusercontent.com/14945613/89108484-37a4e800-d439-11ea-87c1-da4a393c94db.png">
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

**Comment by aminlatifi** [comment]
There was a problem in backend which was fixed... it was weird, some of the web3 tools are not working as before, though they have been working for years! I did some modification to get the result.
