### ISSUE TITLE
Incorrect Date of Milestone in Milestone Page (one day earlier)

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1396]
The milestone page displays Date of Milestone one day before real date of milestone creation. For example check out **Buy Mojito**. 

The milestone page displays Date of Milestone **Buy Mojito**   *5th Aug*, but milestone has been created in *6th Aug* (Iran Time). 

Note: When I check the Date of Milestone, it is pending. I am not sure maybe this causes the problem!

https://develop.giveth.io/campaigns/5ed2848c0486523330330eae/milestones/5f2b7096676d623f0adbaa22

![Screenshot from 2020-08-06 07-48-48](https://user-images.githubusercontent.com/65175075/89486906-56004000-d7b9-11ea-8a67-5817d62cdeb2.png)

In list of my milestones the Date of Milestone is correct. 

https://develop.giveth.io/my-milestones

![Screenshot from 2020-08-06 07-51-42](https://user-images.githubusercontent.com/65175075/89487075-dc1c8680-d7b9-11ea-80af-f9d8be976dd3.png)

**Comment by GriffGreen** [comment]
This date is actually for the exchange rate... CryptoCompare's average daily price only has rates for the past days...

We should rethink the UX around this... its a nice feature... but maybe we remove it... it should be thought about with #1214

**Comment by horus2021** [comment]
@mohammadranjbarz I know this is too late and the show is over, but I checked it. It works. Thanks.
