### ISSUE TITLE
Something went wrong with getting user profile. 

### ISSUE THREAD

**Issue by JulietEA** [Giveth/giveth-dapp#1400]
Issue type: **Error**
Something went wrong with getting user profile. Please try again after refresh.

**Name:**
Timeout of 30000ms exceeded calling users::find

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"Error: Timeout of 30000ms exceeded calling users::find\n    at https://d33wubrfki0l68.cloudfront.net/js/0ad5dcd1312e1005de417cdec68db4305a40cfe4/static/js/main.d8b5e222.js:1:2194253"
</details>

**Comment by aminlatifi** [comment]
It's happen for connectivity issues....
