### ISSUE TITLE
Add a second Donate button at the end of the description of a Campaign

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1405]
Many people might start reading what they're donating to, at the bottom, before Milestones appear there should be a second button saying: 'Donate'

![image](https://user-images.githubusercontent.com/6533925/89920156-5b67eb00-dbfc-11ea-9520-63c4b71de444.png)

**Comment by GriffGreen** [comment]
great idea!

**Comment by GriffGreen** [comment]
#1376 make the donate button big!

**Comment by aminlatifi** [comment]
@mahdine Please add the button for other projects (DAC and Milestone)
