### ISSUE TITLE
Optimize donating interface 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1408]
1) Remove SAI from donating interface 

![image](https://user-images.githubusercontent.com/6533925/89921956-b13d9280-dbfe-11ea-915c-ce8dc5d90b9b.png)

2) Remove the option to donate from another address - if people want to donate from another address they will do so by selecting another metamask account, this is clutter and causes donors to be distracted / not donate. 

![image](https://user-images.githubusercontent.com/6533925/89922628-97e91600-dbff-11ea-9069-c793ff2a067f.png)

3) Remove the infinite unlock option, this is clutter and causes donors to be distracted / not donate. 

![image](https://user-images.githubusercontent.com/6533925/89922663-a5060500-dbff-11ea-8ab0-5616c3b7e1bc.png)

4) Write Campaign instead of 'campaign' -> consistency

![image](https://user-images.githubusercontent.com/6533925/89922761-ccf56880-dbff-11ea-92da-3f794c507c0b.png)

**Comment by aminlatifi** [comment]
About removing SAI we had removed it from active tokens list. @GriffGreen Can we remove it again from active tokens list to just allow delegating that token and not direct donate?

**Comment by aminlatifi** [comment]
It's done.

**Comment by krrisis** [comment]
Great that SAI is removed but this issue was about more than just SAI - have changed title to reflect that.

**Comment by GriffGreen** [comment]
> Remove the option to donate from another address - if people want to donate from another address they will do so by selecting another metamask account, this is clutter and causes donors to be distracted / not donate.

I use this feature many times a month... We need to keep it!

**Comment by GriffGreen** [comment]
> Remove the infinite unlock option, this is clutter and causes donors to be distracted / not donate.

The Infinite unlock option allows for easy 1 click donations for regular users... it is an important UX feature and follows the best pattern of DApps today... giving the unlock this amount, so next time you will have to do 2 tx again... or unlock infinite amount so you will only have to do 1 tx next time (and spend less gas)

**Comment by GriffGreen** [comment]
4 was implemented
