### ISSUE TITLE
Milestone optimization 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1409]
1) Remove the template option - this will be replaced by #1214 and is not used anyways 

2) replace this by a simple pre-checked checkmark 'Donate 3% to Giveth' with a hyperlink to the Giveth DAC or Campaign. Remove all the options here, this is distracting and giving too many choices. 

![image](https://user-images.githubusercontent.com/6533925/89924141-e26b9200-dc01-11ea-926c-588877ab461a.png)

3) Remove the disable Milestone Reviewer option. Depending on the chosen template (see #1214) the reviewer selection field is there or not. I would say: do a reviewer for Milestone only but see #1214 for Griff's thoughts on this.

![image](https://user-images.githubusercontent.com/6533925/89924493-6160ca80-dc02-11ea-9893-b244a272bddc.png)

4) Remove this option. 

Milestone raises funds for a Campaign by default. Payments/Expenses should go to the address with which you are logged in.  (see point 5 below)

![image](https://user-images.githubusercontent.com/6533925/89924645-9bca6780-dc02-11ea-87d4-ba7eed9eefe9.png)

5) Fill in the user's address by default and delete the 'use my address' button + the text above.
In case of a Milestone (so not payment or expense) the address field should not be there at all, just the name of the Campaign.

![image](https://user-images.githubusercontent.com/6533925/89924741-bc92bd00-dc02-11ea-9652-ccba0213979c.png)

6) I'd remove the 'add multiple expenses, invoices etc' option, this makes the system more complicated than needed. people can add this in the text field and upload images there as well.

![image](https://user-images.githubusercontent.com/6533925/89925105-3dea4f80-dc03-11ea-8411-3b1b6ad0011b.png)

**Comment by GriffGreen** [comment]
This should be reviewed with #1214
