### ISSUE TITLE
Hide menu options for default users 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#1410]
Your average user should only see two things in the 'Manage' menu: 'My donations' and 'My Milestones'.
Hide all the other options and only show them to whitelisted people who are authorized to create Campaigns & Communities (and thus able to do delegations)

![image](https://user-images.githubusercontent.com/6533925/89925419-ab967b80-dc03-11ea-931f-61871ac24f13.png)

**Comment by GriffGreen** [comment]
Great point!

**Comment by aminlatifi** [comment]
The point is where user was whitelisted some day, had created some project and he is not whitelisted any more.

**Comment by aminlatifi** [comment]
My Campaigns menu entry is shown when user is in campaign manager or reviewer white list
My Communities menu entry is shown when user is in delegate or reviewer white list
