### ISSUE TITLE
Special Donation Thank You pop up for Commons Stack Campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1413]
What do you think about making a custom Thank You pop up for the Commons Stack... let me think about the exact copy for this..

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/donate

**Comment by krrisis** [comment]
Proposal text: 

Thank you for your donation to the Commons Stack! If you would like to receive [CSTK tokens](https://medium.com/commonsstack/cstk-the-token-of-the-commons-stack-trusted-seed-931978625c61) in return for your contribution, please <a href="mailto:info@commonsstack.org?subject=I%20just%20donated%20to%20the%20Commons%20Stack!">contact us</a> and we'll send you all the details!

**Comment by lorelei1** [comment]
@lorelei1 help on the wording of "in return for contribution"

**Comment by lorelei1** [comment]
"If you would like to receive CSTK tokens in return for contribution, please contact us and we'll send you all the details!"

**Comment by krrisis** [comment]
@aminlatifi after check with @lorelei1 the above is the one you can implement, so this should be a customized pop-up, only valid for this campaign. 

There are two hyperlinks, please do verify if the code for the mailto is correct, but seems to be on my side.

**Comment by GriffGreen** [comment]
making progress!

**Comment by aminlatifi** [comment]
@horus2021 @GriffGreen We should revise the flow! Currently after user donate:
1.If he has donated to a project other than default DAC, he will see `Would you like to support Giveth as well?`. @horus2021  has changed this message with custom thanks message!
2.If he has donated to default DAC the user profile is checked and ask him to fill if he has not yet!

I think scenario is incomplete and doesn't cover all cases!

**Comment by GriffGreen** [comment]
just one pop up :-D

**Comment by aminlatifi** [comment]
If the project has special thanks message, no support giveth any more. So we should forget other scenarios if project has some special thanks message
