### ISSUE TITLE
3% of Donation is below minimum (acceptable) donation

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1414]
In milestone where 3% of donation goes to another DAC, when 3% donation is too small (0.000000) then we got an error. In the case you donate 0.0000001 ETH in the following milestone you can see this issue. A simple solution can be avoiding 3% to DAC when the value is too small. 

**https://develop.giveth.io/campaigns/5d2eb691e31bd24ef8bd3fa8/milestones/5eaf26784c93f3161c3b73bc**

**Comment by GriffGreen** [comment]
#953 #1000 #1397 #1229

**Comment by GriffGreen** [comment]
If the value is small the 3% is ignored

**Comment by GriffGreen** [comment]
When the user clicks donate we should have a check that skips the donation to the DAC if it's too small... cut off donation should be around $1... each token has it's own precision so that should be considered

**Comment by GriffGreen** [comment]
To be handled in the front end

**Comment by GriffGreen** [comment]
$40 should be the limit here... this will give us a $1.20 donation

**Comment by GriffGreen** [comment]
We need to put a limit on the lower end.... this should be fast

**Comment by mohammadranjbarz** [comment]
@MoeNick  for testing this you should create a trace and mark the `Donate 3% to Giveth`
then for donations with amount 10$ or less than 10$ your all donations will go to trace, 
but for greater amount the 3% percent of donations should go to community

PS 1 : the amount in production is 50$ ( it doesn't matter what token you donate, we compare the usdValue)
PS 2: this 3 percent works for donation not delegation

**Comment by MoeNick** [comment]
It worked for me. but for second scenario (less that 10) there is a UX problem, the donation modal still be there for minutes before the submitting trx showed up. 
Let me test it more it may lead to another UI problem over there.
