### ISSUE TITLE
Make a second line of buttons for secondary actions

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1416]
Move propose milestone to this second line as well as CSV, Edit milestone, and View donation address and all the other buttons Besides donate and join

**Comment by aminlatifi** [comment]
@markoprljic

**Comment by GriffGreen** [comment]
Any updates on this one @markoprljic :-D?

**Comment by markoprljic** [comment]
@GriffGreen This issue is directly related (and resolved) with this one https://github.com/Giveth/giveth-dapp/issues/1376
Please correct me if I'm wrong.
