### ISSUE TITLE
Hiring a Junior Developer! 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1417]

**Comment by GriffGreen** [comment]
#1355 was assgined to Mahdi

**Comment by horus2021** [comment]
@aminlatifi hired Mahdi.

**Comment by GriffGreen** [comment]
Yay! Can he accept DAI and track his hours?

**Comment by aminlatifi** [comment]
> Yay! Can he accept DAI and track his hours?

Yes hopefully 😃
