### ISSUE TITLE
Dapp is not loaded on firefox without installing MetaMask

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1425]
Dapp page doesn't show up on Firefox till MetaMask is not installed.

**Details**
Dapp server was deployed on local machine and configuration.js file was modified in order to dapp connects to beta backend.

**Comment by krrisis** [comment]
Same issue in Brave Browser... :/ Came here to log this

**Comment by krrisis** [comment]
And - I guess logically - the same with Chrome browser! So this needs to be fixed asap if possible because we're about to push a page live to donate to the Commons Stack that links to the donate page
