### ISSUE TITLE
Fork the bridge server so that it connects to xDAI

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1431]
for the Commons Stack

**Comment by aminlatifi** [comment]
https://github.com/poanetwork/blockscout/issues/3248

**Comment by GriffGreen** [comment]
need to put this on a server !

**Comment by aminlatifi** [comment]
It's done. It has been setup to call method on xDAI network on every donation to develop.giveth.io
The result will be events shown here: https://blockscout.com/poa/xdai/address/0x5b293019C338D9D902f20A924E49Dd41819D7D63/transactions

**Comment by horus2021** [comment]
It works on develop. We need to push it in beta.
