### ISSUE TITLE
Remove rarely used buttons from quill editor

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1433]
Quill editor is used in writing project description on edit views. Quill has versatile editing options in its menu and few of them are not used mostly. 
![image.png](https://images.zenhubusercontent.com/5d111377d6bc17028a43c827/6195ca09-b640-4798-acf6-508a3c8f42e5)

We can make the editor simple by just keeping essential buttons. @GriffGreen may help on choosing the ones to keep.

**Comment by GriffGreen** [comment]
I have never used
Strike thru
Indents
Clear text format We can get rid of them

**Comment by GriffGreen** [comment]
I wish the Video Button, the Picture button and Link button were bigger and more obvious...

**Comment by aminlatifi** [comment]
Thanks @peymannaderi3 for implementing progress bar, and removing the rarely used buttons once.

**Comment by aminlatifi** [comment]
When I upload big image and while it's resizing/uploading I deleted the image. 
These are what happened:
1. Sometimes images appears again after a few moment
2. Sometimes nothing will appear, but new added image is not shown any more.
