### ISSUE TITLE
Send Email For Simulation Script Fixing Reports

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1436]
This is the next step for #1307.

**Comment by mohammadranjbarz** [comment]
![image.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/43b2bb6f-5471-4e69-b58f-57643cf5d204)

@aminlatifi Now email send after the running simulation and it sends report or error if simulation crash

**Comment by aminlatifi** [comment]
@mohammadranjbarz Nice job

**Comment by horus2021** [comment]
@mohammadranjbarz  Thanks. Who gets this email?
