### ISSUE TITLE
Make MetaMask network change work on test environment

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1438]
New MetaMask api provides api to listen on network change. This feature is used in Dapp and is working on well known networks (Mainnet, Rinkeby, Ropsten, etc.). 
On local environment we use two local network as Home Network (Localhost:8545) and Foreign Network (Localhost:8546). Switching to these networks is not recognized by Dapp and user should manually reload the page.

**Comment by mahdine** [comment]
In the local environment, the event 'chainChanged' does not call. this event is responsible for handling network changes. 
so for this case, we should use pollNetwork.
