### ISSUE TITLE
Milestone form should not have completion date

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#144]
The milestone form has a field "Until what date is the milestone achievable?"...

This sounds like the milestone can only be funded/completed until this date.

This is not how the contracts work. We only have a max amount. Not a max completion date.

@vsimetka @satyavh I think we should remove this field. While I think a max completion date is useful in certain circumstances, I think that should be added later on when we have different types of milestones. I think keeping the first version simple is best.

**Comment by vsimetka** [comment]
I would agree, it makes it much simpler.

**Comment by GriffGreen** [comment]
I am pretty sure we are deleting the date (I think we should for now), but if we doleave the date, it should be autofilled when editing the Milestone, currently it pops up blank.

**Comment by GriffGreen** [comment]
Also, the month should be written out as December instead of 12. Otherwise there is confusion between US and Europe.

12/4/2018 is December 4th for Perissology and me but April 12th for Satya, Jordi and Vojtech...

**Comment by vsimetka** [comment]
Date removed in 1b1b2fb364722b0f0e87429c06974558b674ff4c
