### ISSUE TITLE
Still an issue withdrawing money from milestone "Jeff's June 20 Work"

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#1441]
I had no trouble withdrawing funds from Jeff's July '20 work, but this milestone is still giving me the same error: "No funds are available to be withdrawn."

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5ed075da6e542114b5a58897

**Comment by GriffGreen** [comment]
@Jeff-Emmett This was paid out, you made issue #1430 

But i changed the title because the real bug is that you are given the option to collect the money... when it has already been collected
