### ISSUE TITLE
Add PAN, ANT, WBTC, USDC to the dapp and the simulation script

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1442]
PAN doesnt work on cryptocompare... it doesnt work for PAN... and it doesnt have to be coin gecko... but it needs to be some service that has PAN

**Comment by GriffGreen** [comment]
Code to be reviewed by Amin :-D

**Comment by GriffGreen** [comment]
https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=panvala-pan
Coingecko API

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/92380190-f1206880-f11d-11ea-80d1-57d759f2998d.png)

**Comment by aminlatifi** [comment]
@arbreton Currently we need the price of token on specific day and hour.
A donation USDValue is set based on token price at the hour the donation is created (block timestamp in ethereum network).

**Comment by arbreton** [comment]
Sounds perfect, I'm checking on this, making some room on the schedule

**Comment by arbreton** [comment]
After reviewing the API and current implementation /coins/{id}/history is what we need, since we need to input the timestamp into the API, this will retrieve past USD prices for PAN 😁

**Comment by arbreton** [comment]
Currently testing variations on this implementation

**Comment by aminlatifi** [comment]
> After reviewing the API and current implementation /coins/{id}/history is what we need, since we need to input the timestamp into the API, this will retrieve past USD prices for PAN 😁

@arbreton does it support hourly rates?

**Comment by arbreton** [comment]
> > After reviewing the API and current implementation /coins/{id}/history is what we need, since we need to input the timestamp into the API, this will retrieve past USD prices for PAN 😁
> 
> @arbreton does it support hourly rates?

Sadly It doesn’t support hourly rates which could be important for volatility?

I can lookup some other APIs with timestamps in milliseconds like cryptocompare

**Comment by tmlee** [comment]
For hourly rates, do check out the `/coins/{id}/market_chart` endpoint in the coingecko.com/api docs

`Minutely data will be used for duration within 1 day, Hourly data will be used for duration between 1 day and 90 days, Daily data will be used for duration above 90 days.`

Let me know if that helps!

**Comment by arbreton** [comment]
Th

> For hourly rates, do check out the `/coins/{id}/market_chart` endpoint in the https://www.coingecko.com/api docs
> 
> `Minutely data will be used for duration within 1 day, Hourly data will be used for duration between 1 day and 90 days, Daily data will be used for duration above 90 days.`
> 
> Let me know if that helps!

That’s definitely it!, i think is just what we need, i think the api was just a little confusing on the routing

It could be maybe something like /history/{symbol}?={milliseconds}

Not an expert on api design ofc but i really had hard time deducing what was the purpose of each route i checked lol

I will test with that route!✨

**Comment by GriffGreen** [comment]
@tmlee You are a hero! Thank you so much for coming into the issue and helping us out!!

**Comment by aminlatifi** [comment]
> For hourly rates, do check out the `/coins/{id}/market_chart` endpoint in the https://www.coingecko.com/api docs
> 
> `Minutely data will be used for duration within 1 day, Hourly data will be used for duration between 1 day and 90 days, Daily data will be used for duration above 90 days.`
> 
> Let me know if that helps!

@tmlee Thanks for your guide. I also imagined using `/coins/{id}/market_chart/range` cause it would be better fit for our requirement. We need hourly rates and I reckon calling api using ranges 10 minutes before and 10 minutes after the requested hour. Do you think it will work out?

**Comment by aminlatifi** [comment]
@arbreton Let's go with `/coins/{id}/market_chart/range` and for each timestamp call api using a range around timestamp. It would give us drastically less records that the one we seeking for is among them.

**Comment by GriffGreen** [comment]
- [ ] Update our Oracle Service to use coingecko instead of Cryptocompare
- [ ] add all the tokens to the front end!

**Comment by aminlatifi** [comment]
> * [ ]  Update our Oracle Service to use coingecko instead of Cryptocompare
> * [ ]  add all the tokens to the front end!

@GriffGreen you mean use coingecko for all tokens, including old ones cryptocompare supports (just eth token now)?

**Comment by vcealicu** [comment]
more than happy to provide support and quick integration on the tokens you could not find through our API. Both for historical prices and for current ones.

**Comment by GriffGreen** [comment]
needs to be added to the simulation script

**Comment by GriffGreen** [comment]
Tested PAN on Giveth 2 but the USD value wasn't right #1334

**Comment by arbreton** [comment]
After some deep research, there was hidden pieces of code that resets usdValue, i rewrote that piece of code, now the usdValue of all tokens should be reflected correctly on donations
https://github.com/Giveth/feathers-giveth/pull/245
https://github.com/Giveth/giveth-dapp/issues/1442
This gh tasks could be closed now
Waiting for @aminlatifi review

**Comment by aminlatifi** [comment]
> After some deep research, there was hidden pieces of code that resets usdValue, i rewrote that piece of code, now the usdValue of all tokens should be reflected correctly on donations
> [Giveth/feathers-giveth#245](https://github.com/Giveth/feathers-giveth/pull/245)
> #1442
> This gh tasks could be closed now
> Waiting for @aminlatifi review

Hey,
Thanks...the pull request didn't pass circleci check. Please fix it.
