### ISSUE TITLE
Resize images before uploading to db/ipfs

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1447]
In case images are too large, they should be resized before uploading to ipfs or db. Extra large images make upload failure and slow page loading. Like this milestone:
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f4fc629fb3dbe37aee4e04d

**Comment by GriffGreen** [comment]
Figure out a limit for the size.... 720p is prob more than enough

2400 pixel width is the ideal

**Comment by aminlatifi** [comment]
The failed upload was for picture of size 1000 * 562 and size of 1 MB

**Comment by GriffGreen** [comment]
We need a library for compression... we are uploading a raw image... which is not normal... we should compress it! 

@arbreton is looking into libraries

**Comment by arbreton** [comment]
After testing and researching a few libraries https://www.npmjs.com/package/browser-image-compression seems to be our best option, finishing the last tests on this one

**Comment by aminlatifi** [comment]
Refs #1621
