### ISSUE TITLE
Gaia Protection requesting permission to campaign 

### ISSUE THREAD

**Issue by gaiaprotection** [Giveth/giveth-dapp#1455]
Requesting permission to create campaign and DACs on Giveth 1 on behalf of Gaia Protection. 

My wallet address is: 0x04d9525b92Fd50b8ca4a0D7d3c45ca337F5b7c00

**Comment by Danibelle** [comment]
note: please let me know any special instructions for people requesting to be Whitelisted for either/both Campaign and DAC creation, I'm onboarding new project owners :) thank you!

**Comment by GriffGreen** [comment]
Tell dani when its done

**Comment by arbreton** [comment]
this is done @Danibelle!, sending message on element asswell
