### ISSUE TITLE
Payment not working?! Kris' milestone says paid but it didnt hit the bridge

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1457]
Here is the milestone

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f510a4b0573fc732be1c67f

No tx was ever sent to the rinkeby bridge it looks like

<img width="574" alt="Screen Shot 2020-09-14 at 3 49 41 PM" src="https://user-images.githubusercontent.com/14945613/93094276-ffccc980-f6a1-11ea-8b6e-73de0fd2c588.png">

**Comment by aminlatifi** [comment]
The third item in the list is Kris' milestone
Unfortunately I didn't check and modified bridge db to send the transaction... and a duplicate one is created!
![image](https://user-images.githubusercontent.com/5684607/93098274-ed5f8980-f6bb-11ea-86b4-0d810623292a.png)

**Comment by GriffGreen** [comment]
SHIT! my bad @aminlatifi I missed it too :(

Ok let's look to see how we cancel txs in the bridge
