### ISSUE TITLE
When jess asked for review it posted in status update twice

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1458]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f5959bb317d720b71df995c

Probably related to #1450 and #1234 

<img width="460" alt="Screen Shot 2020-09-14 at 5 06 02 PM" src="https://user-images.githubusercontent.com/14945613/93103442-ec732b80-f6ac-11ea-9e97-768bb6e1e566.png">

**Comment by aminlatifi** [comment]
We had removed some uniq index on db to allow comments, made it manually.
