### ISSUE TITLE
Gus' milestone was reviewed but didnt make it to the bridge

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1460]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f4fc629fb3dbe37aee4e04d

Did a tx get stuck?

**Comment by aminlatifi** [comment]
The milestone status is ok, has Gus tried to collect?

**Comment by GriffGreen** [comment]
pinged gus
