### ISSUE TITLE
Is feathers down? 20 minutes after accepting a proposal, it still hasnt let me delegate to it...

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1462]
https://rinkeby.etherscan.io/tx/0x82d11c124147f06e2d4e4ad930a018173bc5671f8c02cee2b26e6110955e284a

https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f66af75b505b6607064ab05

**Comment by aminlatifi** [comment]
Related to https://github.com/Giveth/feathers-giveth/issues/241
That issue is fixed.
