### ISSUE TITLE
The Bridge monitor isnt updating since we canceled the tx

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1463]
https://bridge.beta.giveth.io/

I assume that it is because we cancelled the duplicate tx with the multisig and it broke the bridge somewhere.
<img width="386" alt="Screen Shot 2020-09-29 at 3 12 38 AM" src="https://user-images.githubusercontent.com/14945613/94501234-aa47ff00-0201-11eb-9090-33e75c1f1dd6.png">

**Comment by aminlatifi** [comment]
@bowensanders It wasn't DAI, right? I couldn't track it in Bridged Multi-Collateral DAI 
https://rinkeby.etherscan.io/token/0x05a075b296995adcaec7c1de0e52271a4cf6deb8
I couldn't find that value '1062' in bridge db too
Can you send me link to tx?

**Comment by bowensanders** [comment]
It's 3565 DAI (MCD). There were two with the same value, that tx (1057) is the second one that was initially delayed then cancelled by multisig vote.

This is the TX from the bridge monitor:
<img width="1570" alt="Screen Shot 2020-09-29 at 9 35 40 AM" src="https://user-images.githubusercontent.com/27023908/94587279-33c5f400-0237-11eb-857f-7e4c97932e4e.png">

The milestone was: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f510a4b0573fc732be1c67f

This is what the bridge reports for TX 1057:
<img width="1222" alt="Screen Shot 2020-09-29 at 9 38 26 AM" src="https://user-images.githubusercontent.com/27023908/94587484-87d0d880-0237-11eb-9a11-a787a6731c96.png">

This is the events from the multisig that emitted the payment cancel:
0x8f951903C9360345B4e1b536c7F5ae8f88A64e79

and the bridge:
https://etherscan.io/address/0x30f938fED5dE6e06a9A7Cd2Ac3517131C317B1E7#events


Maybe the info you need is there?

**Comment by aminlatifi** [comment]
@bowensanders Thanks for details... my bad I thought 1061 is amount!!! 🤦‍♂️

**Comment by aminlatifi** [comment]
Fixed, there was problem on connecting to Aragon gateways using websocket. 
Refs https://github.com/Giveth/feathers-giveth/issues/241
