### ISSUE TITLE
Sort by activity and Hide inactive Campaigns and DACs from the front page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1464]
Currently, we are featuring campaigns and DACs that haven't had any activity in years, the sorting on the front page should be by activity, and projects that haven't had activity for 6+mo should be hidden off the front page...
<img width="1269" alt="Screen Shot 2020-09-30 at 4 32 09 PM" src="https://user-images.githubusercontent.com/14945613/94699344-83d9af00-033a-11eb-823a-029a9ec84a2c.png">

**Comment by arbreton** [comment]
After some research on the code got the logic for sorting on the main page, now just querying the database for 6 months newer project should do the job, diving into MongoDB docs for date ranges
