### ISSUE TITLE
CORS issue from Michelle from Fair Data Society

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1465]
She said:

I think there's a CORS issue on https://beta.giveth.io/

Access to XMLHttpRequest at 'https://rinkeby2.giveth.io/' from origin 'https://beta.giveth.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://beta.giveth.io, *', but only one is allowed.

you cannot have * and a string, it's only * or a list of strings

I'm not sure what any of this means.. but i figured i should pass it along

**Comment by aminlatifi** [comment]
Fixed by changing nginx ocnfig.

**Comment by wendydv1989** [comment]
> Fixed by changing nginx ocnfig.

It's not live yet?

**Comment by GriffGreen** [comment]
@aminlatifi ping michelle and make sure her needs are met
