### ISSUE TITLE
List of new token addresses

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1467]
WBTC = 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599 (Mainnet)
GivWBTC = 0x6d03800013c591611a6ee597191d9f608b833510 (Rinkeby)

USDC = 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
GivUSDC = 0xf14eCE303f190A70A2CF7C7011F75bDa658aD6EF

ANT = 0x960b236a07cf122663c4303350609a66a7b288c0
GivANT = 0x7283b97f7546ba8eff68167cab2da526e7d7f88a

PAN = 0xd56dac73a4d6766464b38ec6d91eb45ce7457c44
GivPAN = 0x0aaf4acccddb40cdb6a1df3cfbc7944aa5effcc6

I got these from the logs of the rinkeby multisig txs that created the tokens... and i verified the token addresses on etherscan... but we should still make small test donations on beta with these tokens thru the front end to make sure it all works.

-----------------
Address
0xff9cd5140e79377feb23f6dfaf1f8b558c0fe621
Name
TokenAdded (index_topic_1 address mainToken, address sideToken)View Source

Topics
0 0xdffbd9ded1c09446f09377de547142dcce7dc541c8b0b028142b1eba7026b9e7
1  0xd56dac73a4d6766464b38ec6d91eb45ce7457c44
Data
sideToken :
0x0aaf4acccddb40cdb6a1df3cfbc7944aa5effcc6

------------------

Address
0xff9cd5140e79377feb23f6dfaf1f8b558c0fe621
Name
TokenAdded (index_topic_1 address mainToken, address sideToken)View Source

Topics
0 0xdffbd9ded1c09446f09377de547142dcce7dc541c8b0b028142b1eba7026b9e7
1  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
Data
sideToken :
0xf14ece303f190a70a2cf7c7011f75bda658ad6ef

----------
TokenAdded (index_topic_1 address mainToken, address sideToken)View Source

Topics
0 0xdffbd9ded1c09446f09377de547142dcce7dc541c8b0b028142b1eba7026b9e7
1  0x2260fac5e5542a773aa44fbcfedf7c193bc2c599
Data
sideToken :
0x6d03800013c591611a6ee597191d9f608b833510

**Comment by aminlatifi** [comment]
Thanks griff.

**Comment by arbreton** [comment]
Seem to be all tokens added by now
