### ISSUE TITLE
[Propose milestone] - Error after typing the description (I think on client save)

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapp#1468]
When proposing a milestone I got an error while not doing anything special - I was merely creating the description!

Here is a screenshot:
![image](https://user-images.githubusercontent.com/317685/95022250-4ba5d980-0676-11eb-8c04-50416717aa86.png)

[EDIT]
I was finally able to complete the process. Since the error message suggested that it did not like the empty adress, I tried filling this in first (before the description) and then it worked to complete the milestone and propose it.

**Comment by GriffGreen** [comment]
Common problem when there is a bad internet connection... we should add some protections against this... Also tell the user with an informative error message telling them that their internet sucks and they need to have better wifi before clicking this button
