### ISSUE TITLE
Write Comment is limited to 150 characters, making contribution status update difficult

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-dapp#1469]
https://beta.giveth.io/campaigns/5f504e7bfb3dbe37aee4e050/milestones/5f7a147242d4cd1c03dce18c 

![image](https://user-images.githubusercontent.com/2126012/95025324-daa2f980-0656-11eb-982b-abae29f9b249.png)

Recommend increasing character limit.

**Comment by aminlatifi** [comment]
@papermache @GriffGreen It's good time to decide between simple text or rich text!

**Comment by GriffGreen** [comment]
Work around right now is multiple comments... but we should make it one comment...

**Comment by GriffGreen** [comment]
Add Quill powers to the Write update...

<img width="1275" alt="Screen Shot 2020-10-08 at 6 30 15 PM" src="https://user-images.githubusercontent.com/14945613/95487237-5d4bf180-0994-11eb-8962-8f9324634e62.png">

**Comment by mahdine** [comment]
How about length limitation?
