### ISSUE TITLE
Off-chain propose milestones

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#147]
Anyone can propose milestones, but they only go on-chain when the campaign manager approves them

**Comment by satyavh** [comment]
Do we want to show proposed milestone on the view campaign page? It might be very confusing

**Comment by satyavh** [comment]
OK I got this hooked up, but here are some questions:

When a milestone is proposed, it shows under 'My Milestones' of the campaign owner.
When the campaign owner accepts the milestone it gets mined

But the owner of the milestone is still the person that proposed the milestone. 

Is that OK?

@perissology 
I also noticed that each time we patch it actually creates a new json object in the database...

**Comment by perissology** [comment]
regarding the new db object, it's not really the case. It will merge the entries in the *.db file periodically. Not exactly sure how often it does this.

I'm not sure of the best way to show milestone proposals the campaign owner needs to accept/reject, but I'd say that my-milestones is not the right location.

~Also, the way it is written now, the contract will be deployed with whoever "accepts" the milestone as the owner.~

Actually, this is quite a bit easier then I thought, and the current implementation should work fine. The contract only has 3 roles, and no `owner`.

1. recipient - assigned during proposal
2. milestoneReviewer - auto-assigned
3. campaignReviewer - reviewer of the campaign the milestone part of (I have this done locally and will push once a few more contract issues are done)
