### ISSUE TITLE
Milestone has a Rinkeby tx but didn't hit Mainnet

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1474]
we have a tx that happened properly on rink but not on main - see bridge.beta.giveth.io
this milestone https://beta.giveth.io/campaigns/5df21b3c71e84069aad0a23c/milestones/5f5776e0317d720b71df993e
has a rinkeby side tx: https://rinkeby.etherscan.io/tx/0x8204fbf185a6d68be28a0ce813a6190505af7e47d9085ff08ace593b23727bd7
Ethereum (ETH) Blockchain Explorer
Rinkeby Transaction Hash (Txhash) Details | Etherscan
Rinkeby (ETH) detailed transaction info for txhash 0x8204fbf185a6d68be28a0ce813a6190505af7e47d9085ff08ace593b23727bd7. The transaction status, block confirmation, gas fee, Ether (ETH), and token transfer are shown.
but no matching one on mainnet
you can see this on the bridge server

**Comment by aminlatifi** [comment]
The payment is on bridge in pending state, the mainnet tx is https://etherscan.io/tx/0x713efff8ec23cfd8bf8531b0e1ad4e48f749c43d830b52d3a3e78cedd474f214

**Comment by Danibelle** [comment]
@aminlatifi There are two similar transactions!
This one (September) is on the bridge: 
https://beta.giveth.io/campaigns/5df21b3c71e84069aad0a23c/milestones/5f7b2a1f42d4cd1c03dce1a2

This is the one (August) in question: 
https://beta.giveth.io/campaigns/5df21b3c71e84069aad0a23c/milestones/5f5776e0317d720b71df993e

**Comment by aminlatifi** [comment]
Fixed
![image](https://user-images.githubusercontent.com/5684607/95612133-bdfc2c80-0a6f-11eb-94b3-dc95f902bfc4.png)
