### ISSUE TITLE
Make it just PAN, not Pan Token

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1480]
<img width="209" alt="Screen Shot 2020-10-15 at 5 47 00 PM" src="https://user-images.githubusercontent.com/14945613/96153862-76adea00-0f0e-11eb-8f0c-ecf7db971bf8.png">

**Comment by arbreton** [comment]
Included in https://github.com/Giveth/feathers-giveth/pull/245
