### ISSUE TITLE
Add new tokens to the options of currencies for making the milestone

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1481]
<img width="239" alt="Screen Shot 2020-10-15 at 5 47 35 PM" src="https://user-images.githubusercontent.com/14945613/96154012-a5c45b80-0f0e-11eb-834f-31aa00fb7585.png">

We need PAN, ANT, USDC and BTC there, and remove SAI... Also, it should be sorted probably with Native tokens at the top and Fiat Tokens at the bottom... My ideal sorting:

ETH
DAI
PAN
ANT
BTC
USDC
...
USD
fiat
fiat
fiat
fiat

**Comment by arbreton** [comment]
Included in https://github.com/Giveth/feathers-giveth/pull/245

**Comment by aminlatifi** [comment]
@mdehghani Create separate list for native currencies and use that on user profile... as Griff mentioned they need to be just fiat currencies
