### ISSUE TITLE
Leaderboard on DAC doesn't have load more

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1483]
Refs #1477 #1339

**Comment by GriffGreen** [comment]
https://share.getcloudapp.com/7Ku8Qlzl

**Comment by mahdine** [comment]
![image](https://user-images.githubusercontent.com/2072995/96930524-b35a8200-14c8-11eb-8243-9ea9a382e70c.png)
@markoprljic Is it OK?

**Comment by mahdine** [comment]
The milestone does not have leaderboard and has donation list instead. The `donationsPerBatch` setting was set to 5 for campaign and 50 for DAC.  I changed it to 5 for DAC.

**Comment by markoprljic** [comment]
> ![image](https://user-images.githubusercontent.com/2072995/96930524-b35a8200-14c8-11eb-8243-9ea9a382e70c.png)
> @markoprljic Is it OK?

Perfect!
