### ISSUE TITLE
Need Donation Badge

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-dapp#1486]
@aminlatifi has description.

**Comment by markoprljic** [comment]
@aminlatifi Can you please describe this issue so that I know what needs to be done? Thanks!

**Comment by aminlatifi** [comment]
@markoprljic Sorry for late response
It happens when donations are changed, user currently needs to refresh the page to see new donations (it should be fixed in future to the list of donations be updated too).
![image](https://user-images.githubusercontent.com/5684607/97077924-8e632d80-15f4-11eb-9155-ff7a786f7312.png)

**Comment by aminlatifi** [comment]
> @markoprljic Sorry for late response
> It happens when donations are changed, user currently needs to refresh the page to see new donations (it should be fixed in future to the list of donations be updated too).
> ![image](https://user-images.githubusercontent.com/5684607/97077924-8e632d80-15f4-11eb-9155-ff7a786f7312.png)

I generated it by collectiong/dusbursing

**Comment by markoprljic** [comment]
@aminlatifi So ... you mean that when I'm on the page and a new donation just happened it will be automatically updated? 
In such case we should show a "New" badge + highlight the incoming donation(s) in the list below? Is that correct?
Those new donations would then be considered as "seen" when the user refreshes the page?

**Comment by aminlatifi** [comment]
> @aminlatifi So ... you mean that when I'm on the page and a new donation just happened it will be automatically updated? 
> In such case we should show a "New" badge + highlight the incoming donation(s) in the list below? Is that correct?
> Those new donations would then be considered as "seen" when the user refreshes the page?

Currently, when new donations are added the badge shows the number only and list is not updated.
Your story is great and results better user experience. If you design it we would implement

**Comment by markoprljic** [comment]
@aminlatifi I created a mockup for this new donations notifications inside the new Leaderboard table (because I have it in Figma). You can apply it to the old table we currently have on the site, it's the same thing. 

Here's a preview 
<img width="1255" alt="Image 2020-12-09 at 8 54 06 am" src="https://user-images.githubusercontent.com/5704285/101600930-49585680-39fc-11eb-9e9c-a386bd8fc056.png">

**Comment by aminlatifi** [comment]
@peymannaderi3 See whether leaderboard api supports feathers watching (monitor updates)

**Comment by aminlatifi** [comment]
@RamRamez Please fix this for DACs, Campaigns and Milestones

**Comment by aminlatifi** [comment]
https://github.com/Giveth/feathers-giveth/issues/454

**Comment by MoeNick** [comment]
In milestone: 
wo refreshing right after submitting
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/a8101744-ded8-4b16-a5fc-7557c4453b0c)
Right after submitting, be refreshing the page:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/a06b3b3e-a328-43d0-9e1b-9a28c48425d7)
After 3 min:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/3b12e6b2-c3e5-4fde-8727-14d6769599ae)

In Campaign, after 5 min refreshing:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c5604808-2384-4041-9c27-a910ea74da6c)

In  DAC after 3 min refreshing:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/9a82a1e3-7da6-4db1-89c7-74ed69ca2e7e)

**Comment by MoeNick** [comment]
I also tested delegation method. All scenarios needs to be refreshed the page to update the leaderboard.

**Comment by MoeNick** [comment]
@mohammadranjbarz Refreshing is needed on this issue, I made a mistake in our daily call.
Should we consider auto-updating without refreshing in leader-board?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
We think maybe it's related to some reactive library, and the updating packages maybe solve this, So we have no specified task for this issue

**Comment by MoeNick** [comment]
@mohammadranjbarz shall I keep it here, until the library get updated and I see the result?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
What do you think about this?

**Comment by aminlatifi** [comment]
> @aminlatifi
> What do you think about this?

@mohammadranjbarz Upgrading just feathers-reactive may solve. Can you try it? and see whether subscription to donations work after?

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi
> > What do you think about this?
> 
> @mohammadranjbarz Upgrading just feathers-reactive may solve. Can you try it? and see whether subscription to donations work after?

I'm working on it, 
upgrading ` feathers-reactive` didn't solve this, I'm investigating

**Comment by MoeNick** [comment]
@RamRamez update state after user push pending donations to backend.

**Comment by MoeNick** [comment]
Discussed in grooming, mohammad suggests a solution, they will test it on tomorrow 15 July. got paired witch cherick.
