### ISSUE TITLE
Should we ignore metamask errors? when creating user profile

### ISSUE THREAD

**Issue by Anna-Oz** [Giveth/giveth-dapp#1487]
![chrome_2020-10-23_12-59-15](https://user-images.githubusercontent.com/69071691/96990324-a15ffa00-152f-11eb-95b0-aa7f4a9b88cb.jpg)

Issue type: **Error**
There has been a problem creating your user profile. Please refresh the page and try again.

**TransactionLink:**
"https://rinkeby.etherscan.io/tx/undefined => {}"

**Comment by GriffGreen** [comment]
Oh no issue!

**Comment by GriffGreen** [comment]
Maybe we should ignore erros from metamask
