### ISSUE TITLE
The Comment section of the leader board gets cut off depending on window size? 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1493]
OMG THE LEADER BOARD IS THERE!!! FUCK YEAH!!!

This is just a little bit of QA but oh man this is so great! 

Here it shows the comment header cut in 1/2... that shouldnt happen... I'm also curious to see what it looks like when someone makes a comment.

<img width="911" alt="Screen Shot 2020-10-27 at 1 38 44 AM" src="https://user-images.githubusercontent.com/14945613/97242855-38a9a380-17f5-11eb-9f0e-5ea19c04158c.png">

**Comment by aminlatifi** [comment]
On mobile view, the table scrolls horizontally. But the comment section has no cell.
![image](https://user-images.githubusercontent.com/5684607/97280660-d0d57600-1851-11eb-873c-81613b95115e.png)

**Comment by aminlatifi** [comment]
@mahdine It also be great, if clicking on header row (entire row, except links) expand the donations section, and not just the plus sign. Can you implement it under this issue?
