### ISSUE TITLE
Milestone for Approval Has No Buttons

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1494]
[James' Milestone](https://beta.giveth.io/campaigns/5f504e7bfb3dbe37aee4e050/milestones/5f987a22ebdc6e41fe6aeb0d) shows up in my list but doesn't have any buttons for me to click.. 
Mahdi's above it shows correctly:

![image](https://user-images.githubusercontent.com/39466970/97375876-8ec42880-1881-11eb-8848-26c6637d8457.png)

The buttons are not there in the Milestone itself either:
![image](https://user-images.githubusercontent.com/39466970/97376013-e4003a00-1881-11eb-8c32-1dbf56616722.png)

**Comment by aminlatifi** [comment]
It's in inProgress state! you didn't accept it?

**Comment by aminlatifi** [comment]
@Danibelle I had experienced the same I guess, a milestone is added without campaign manager accept

**Comment by aminlatifi** [comment]
@Danibelle Has you accepted this milestone ? https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5f987ab9ebdc6e41fe6aeb0f

I am afraid of data is hacked to misguide us!

**Comment by aminlatifi** [comment]
@Danibelle Willy has accepted the James milestone

**Comment by Danibelle** [comment]
Yes I saw it was accepted by Willy instead!

I don't have anything more to add and the problem is resolved!
