### ISSUE TITLE
Error on editMilestone

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1495]
@jamespfarrell and @mahdine had this problem on editMilestone view (creating milestone)

![unknown](https://user-images.githubusercontent.com/5684607/97417130-8f5dcd00-191c-11eb-9c07-8c1e13266636.png)

**Comment by aminlatifi** [comment]
Did some modification to address this problem, hope fixed

**Comment by papermache** [comment]
User provider caused some problem at the beginning.
