### ISSUE TITLE
Trying to go directly to a link doesn't work very well

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1508]
Try it
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/propose

**Comment by aminlatifi** [comment]
EditMilestone view redirects user to homepage in case the user account is undefined. 
When user opens add/propose milestone page directly (not by clicking create button on campaign view), the user account (currentuser) is not loaded at first, so the above situation happens. 
Edit milestone page should be redesigned to show some modal to say user you should login first. It's the best scenario I have in mind. @GriffGreen You may have better idea.

**Comment by GriffGreen** [comment]
the cause is know by amin... the user provider has not loaded the user info

It sends you to the home page cause it assumes you have not logged in
