### ISSUE TITLE
New Campaign Manager Request fo Whitelist

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#1516]
Hi my name is Ashley. Im working with Dani on user testing and I would like to be able to create DACs and communities and have reviewer permissions for the following addresses:

0xed8DB37778804A913670d9367aAf4F043AAd938b
0x7554f10Da3Ed7128300577e55abCd8F8835BCee4

Thank you <3

**Comment by aminlatifi** [comment]
Hi,
If you want test we have develop.giveth.io, has whitelisting disabled. On beta I can add your addresses, but don't test there because there is real users there.
I added your token to beta whitelists.
