### ISSUE TITLE
Make milestone navbar mobile friendly

### ISSUE THREAD

**Issue by mahdine** [Giveth/giveth-dapp#1520]
![image](https://user-images.githubusercontent.com/2072995/98951903-12cc1080-2510-11eb-845b-69ba3b54f14a.png)

**Comment by aminlatifi** [comment]
@geleeroyale Need your help here too :)

**Comment by geleeroyale** [comment]
Thanks for assigning this to me. Won't get to it before finishing frontend work for giveth-v2, but I can promise to fix this sometime next week.

**Comment by aminlatifi** [comment]
@geleeroyale We have new front-end dev 😃🎉

**Comment by aminlatifi** [comment]
The issue title is misleading... views of campaign and dac needs to be changed too.

**Comment by peymannaderi3** [comment]
> The issue title is misleading... views of campaign and dac needs to be changed too.

How should it be?
