### ISSUE TITLE
Unique Milestone Name Requirement

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1521]
It'd be great if Milestone Names had to be unique, like a User Name - when Milestones have the same name, especially in the same Campaign, selecting which to delegate funds to is very difficult to discern.

**Comment by GriffGreen** [comment]
create a check to ensure that the names are unique... at least per campaign!

**Comment by GriffGreen** [comment]
adding a slide functionality eventually...

**Comment by horus2021** [comment]
A fix for this issue can be adding "Project ID" beside "Title Milestone". we can ask givers to donate to this milestone "Title milestone" with this "Project ID". The Project ID is unique (Like Bank account No.) and the possibility of error will be reduced.

**Comment by aminlatifi** [comment]
We should make it uniq in each campaign, not globally

**Comment by aminlatifi** [comment]
@mdehghani what is needed to implement:
- [ ] In the backend, creating/patching a milestone with title equal title of another milestone in the same campaign is forbidden
- [ ] The create milestone page form validator checks uniqueness of title

**Comment by GriffGreen** [comment]
:-D
