### ISSUE TITLE
When payouts happen on mainnet grab that info and add it the milestone front end

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1522]
That tx is in the bridge... we should be making it accessible to the users... it is what they want to see...

And in the spot where we put the address... we should alert them that their payout is still pending

**Comment by aminlatifi** [comment]
This should be by creating appropriate doc in events collection.

**Comment by GriffGreen** [comment]
@aminlatifi to add smaller issues

**Comment by GriffGreen** [comment]
Goal is to create an end point in the current bridge monitor so the dapp can be aware of mainnet payments

**Comment by aminlatifi** [comment]
It has implemented.

**Comment by mohammadranjbarz** [comment]
> How can I test buddies?
> @aminlatifi @mohammadranjbarz
> 
> One of its issue is still in product backlog! why is it here?

Anything related to payout money to main net can not be tested in  `develop` server and in a routine way, so testing these scenarios needs me or @aminlatifi , to change something manually in db , or running our local instance with using beta db dump , ....

**Comment by mohammadranjbarz** [comment]
> How can I test buddies?
> @aminlatifi @mohammadranjbarz
> 
> One of its issue is still in product backlog! why is it here?

Anything related to payout money to main net can not be tested in  `develop` server and in a routine way, so testing these scenarios needs me or @aminlatifi , to change something manually in db , or running our local instance with using beta db dump , ....
