### ISSUE TITLE
dashboard community & campaign pages are not reactive

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#153]
If a pending dac/campaign is mined while viewing the corresponding dashboard pages, the `Status` is not updated & still show `pending`.

This may be the same on the other dashboard pages.

**Comment by vsimetka** [comment]
Noticed it as well. I can work on it but after friday.

**Comment by satyavh** [comment]
I fixed campaigns, but cannot test due to https://github.com/Giveth/feathers-giveth/issues/60

**Comment by satyavh** [comment]
DACs implements DACservice, which needs to be rewritten, see https://github.com/Giveth/giveth-dapp/issues/157
