### ISSUE TITLE
Option to donate Milestone funds to a Campaign on Collection

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1531]
I see my only options on collection are to Collect, or to Change Recipient.
I can't go back and edit my choices at Milestone creation to give a percent back to Giveth, or to donate my donations fully, partially etc. to a Campaign (or DAC or Milestone for that matter).
I would like that option!
Not sure where it makes most sense and could be nice to present it at both places, on Collection, you could either withdraw funds to a wallet OR delegate them to a DAC, Campaign, Milestone..
![image](https://user-images.githubusercontent.com/39466970/99010757-3b540a80-2510-11eb-8ea4-81183248416a.png)
And/Or the option to change recipient to a Campaign and keep the funds in the DApp..
![image](https://user-images.githubusercontent.com/39466970/99010713-25464a00-2510-11eb-94c6-e04bad276ebd.png)

**Comment by papermache** [comment]
Needs research.

**Comment by GriffGreen** [comment]
This feature makes the dapp too complicated :-(

**Comment by Danibelle** [comment]
This can be accomplished if necessary, by creating a donation address for the new recipient Campaign then changing the Recipient.
