### ISSUE TITLE
UI Text Revision: Create A Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1532]
Text instructions on this page are not clear and lead to very long DAC names.  In part, because, as soon as you click away from the Title text box the line of text instructions below it disappears!
![image](https://user-images.githubusercontent.com/39466970/99337033-28f70b00-2847-11eb-9ad9-1508c742455d.png)
![image](https://user-images.githubusercontent.com/39466970/99338249-74aab400-2849-11eb-9ca2-2944a68ecf10.png)

**Current Header Text:** A DAC aims to solve a cause by building a community, raising funds, and delegating those funds to Campaigns that solve its cause. Should you create a Campaign or Community? Read more here.
**Recommended Text Revision:** A DAC unites Givers and Makers in building a community around their common vision to raise then delegate funds to Campaigns that deliver a positive impact to shared goals.

**Current DAC Title Box Text:** Community cause *

**Recommended Text Revision:** Name your Community *
Describe your altruistic community (DAC) in 1 sentence
^^make it so the instruction text remains even if the box gets highlighted RED as it does^^

**Current DAC Description Box Text:** Explain your cause *
Make it as extensive as necessary. Your goal is to build trust so that people join your Community and/or donate Ether.
**Recommended Text Revision:** Explain the cause of your community *
Describe the shared vision and goals of your Community and the cause that you are collaborating to solve. Share links, insert media to convey your message and build trust so that people will join your Community and/or donate to the cause.

**Comment by horus2021** [comment]
@aminlatifi please checkout my [PR](https://github.com/Giveth/giveth-dapp/pull/1587)
@Danibelle  You are great copywriter! Thanks.

**Comment by aminlatifi** [comment]
@horus2021 Did you test on develop? beta is not merged yet!

**Comment by Danibelle** [comment]
Tested, changes confirmed - thank you!
