### ISSUE TITLE
Instructions for Donors on Infinite Unlock needed

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1533]
Donor wishes to give multiple currencies, DAI, PAN, ETH.

Infinite Unlock when donating DAI, is that only for DAI? Will the Donor have to do the Infinite Unlock for each currency?

When is it beneficial to use Infinite Unlock, and why might one choose not to?

![image](https://user-images.githubusercontent.com/39466970/99836621-ff323280-2b2b-11eb-9f88-799546f62c0a.png)

**Comment by GriffGreen** [comment]
add a tool tip that says:

"Infinite unlock will allow the Giveth Bridge smart contract to interact freely with the DAI in your wallet, this can be revoked later by using https://revoke.cash/" 

DAI needs to switch to the token that is being chosen

**Comment by GriffGreen** [comment]
"Infinite unlock will allow the Giveth Bridge smart contract to interact freely with the DAI in your wallet, this can be changed later by clicking Donate and choosing to "Revoke" unlike your bank irl.. hehehehe"

hahaha ummm Ashley can you confirm this is ok

**Comment by WhyldWanderer** [comment]
@GriffGreen I like it.. but maybe we take out the abbreviation and like 2 he's.. sooo like this.

"Infinite unlock will allow the Giveth Bridge smart contract to interact freely with the DAI in your wallet, this can be changed later by clicking Donate and choosing to "Revoke" unlike your bank.. hehe"

**Comment by GriffGreen** [comment]
Great!

**Comment by GriffGreen** [comment]
@peymannaderi3 it's all yours ;-)
