### ISSUE TITLE
Delegate Funds from a DAC Option on viewing a Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1536]
Arriving at a Campaign, I have the option to Delegate funds from a DAC. 
When I click on it, it says there are no options - in which case the button should not appear as the user does not have a DAC from which to Delegate to the Campaign. Maybe because this account is whitelisted to be able to make DACs? 
The Window does not have a cancel button, so I felt like I got stuck there..  which I was, you can't click away from the popup box to make it go away. Escape key did let me escape :)

![image](https://user-images.githubusercontent.com/39466970/99888506-fd8f6a00-2c12-11eb-9d49-3be8c64c6c94.png)

**Comment by GriffGreen** [comment]
Make the delegate button only show up based on if they are
1. On the Delegator white list
2. On the DAC 
3. The owner of the campaign

**Comment by aminlatifi** [comment]
Close button is added, also delegate button is shown only to users who are owner of at least one DAC or campaign owner in milestone case.
