### ISSUE TITLE
Can not create new milestone

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#154]
With the lates dev backend / fronted, creating new milestone throws error.

<img width="1132" alt="screen shot 2017-11-23 at 13 26 30" src="https://user-images.githubusercontent.com/7974813/33185651-24a390c8-d052-11e7-86fc-3543afd8d3d0.png">

**Comment by satyavh** [comment]
Has been fixed by @perissology

**Comment by perissology** [comment]
fixed in 3eb4fcf5dbc4e21d0b4b1145f881a9ae95e6c503
