### ISSUE TITLE
Community, Campaign, Milestone Image

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#1540]
The chosen images shown on the Community, Campaign, and Milestone pages are very dark and difficult to make out.
Can we adjust the brightness or transparency a bit to show more of the image?
![Screenshot 2020-11-24 at 2 23 27 PM](https://user-images.githubusercontent.com/74267818/100147300-cc0bde00-2e60-11eb-8724-82d527c48ca4.png)

**Comment by aminlatifi** [comment]
We make them darker to allow white text visible on any image,
