### ISSUE TITLE
Text Wrap on Milestone page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#1543]
When a campaign or community has a longer title the text overlaps the navigation options.
Maybe we could add a text wrap feature so this doesn´t happen?
![Screenshot 2020-11-24 at 2 33 59 PM](https://user-images.githubusercontent.com/74267818/100148692-b5668680-2e62-11eb-896f-abd2e3278bc2.png)

**Comment by aminlatifi** [comment]
@geleeroyale Hey, Griff said you like to help :D

**Comment by geleeroyale** [comment]
Yes - keep collecting visual bugs. Like the other issue - will likely get to this sometime next week.

**Comment by aminlatifi** [comment]
Fixed by #1614
