### ISSUE TITLE
Donation view missing "donated to" field after any successful action

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#155]
If user does any action on donation (reject, commit or refund), the `Donated to` field turns blank. Changing page/refreshing fills the `Donated to` field correctly.

<img width="1632" alt="screen shot 2017-11-23 at 13 49 49" src="https://user-images.githubusercontent.com/7974813/33186267-37bc4534-d056-11e7-830c-fd3d2644139f.png">

**Comment by perissology** [comment]
fixed
