### ISSUE TITLE
Pick a Hosting Service to apply for nonprofit credits

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1550]

**Comment by GriffGreen** [comment]
AWS is not an option till January

Comes from Text Soup.

We are using Digital Ocean... but we might want to switch...

**Comment by GriffGreen** [comment]
blocked by Giveth not having the right paper work

Some systems show our nonprofit status is revoked.

**Comment by aminlatifi** [comment]
@willyogo had contacted dreamhost, they offer free service to non-profit
https://help.dreamhost.com/hc/en-us/articles/215560437-What-types-of-hosting-plans-are-available-
https://help.dreamhost.com/hc/en-us/articles/215769478-Non-profit-discount

**Comment by willyogo** [comment]
@aminlatifi just created an account and followed their instructions submitted a ticket. I'll let you know as soon as we hear back on whether we're approved 🤞

**Comment by GriffGreen** [comment]
@willyogo ! Wow thx for taking this on! @aminlatifi is excited about Microsoft Azure... is that what is happening...

If you get stuck on it Willy, please just let it fall ;-) 

Amin said he doesnt have the space to execute it right now... we are looking for a new front end person (i think we found them in @MohammadPCh :-D, but we won't let this be a blocker if it doesn't happen)

**Comment by willyogo** [comment]
Update: We got the free Dreamhost shared hosting, but after trying it out it ended up not being a great fit for our needs. Yesterday I created an azure account and applied for the free credit for non-profits. Our application is in review and we should hear back in the next 6 days 🤞 

https://github.com/Giveth/giveth-planning/issues/95

**Comment by willyogo** [comment]
Approved for $3,500/year credits for Microsoft Azure! @aminlatifi has been invited as an admin to Giveth's new Azure account.

Email from Microsoft:

Your organization is now eligible for donations and discounts from Microsoft

Organization: SDG Impact Fund
Microsoft account username: willygiv@givethio.onmicrosoft.com
Domain: givethio.onmicrosoft.com

Dear willygiv,

We have verified that SDG Impact Fund is eligible to receive nonprofit offers from Microsoft. You can now access nonprofit offers in the Nonprofit Portal. We are committed to helping you choose secure, trusted technologies to protect your sensitive data from accidental or malicious threats. Here are just some of the ways your organization can benefit from Microsoft technologies:

Securely run and grow your nonprofit with Microsoft 365 Premium. Security and device management capabilities are embedded into the Office 365 best-in-class productivity solution, helping to further safeguard your organization's data for $5 USD user/month.

Accelerate nonprofit innovation with Microsoft Azure. You can take advantage of up to $3,500 USD per year in donated Azure services credits.

Add nonprofit-specific relationship management capabilities with Dynamics 365 to help improve relationships with donors, volunteers, and beneficiaries, and optimize your operations.

If you need help deciding which offers are right for you, please contact us by submitting an inquiry. Here are some helpful resources to learn more:

Crash Course in Microsoft 365 Business Premium
Crash Course in Microsoft Teams
Microsoft Teams Adoption Guide
Learn Azure in a Month of Lunches
Activating Your Organization's Azure Credits
Note: If you are currently using an Microsoft 365 or Office 365 trial subscription, it will expire at the end of the trial subscription period.

Please contact us if you have any questions.

Thank you,
Microsoft Philanthropies
Tech for Social Impact
