### ISSUE TITLE
conversionRates service doesn't resolve correct result for PAN

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1555]
conversionRates service should resolve requested token value (yesterday zero hour value) in all fiats
![image](https://user-images.githubusercontent.com/5684607/100660774-bc602e00-3367-11eb-8612-db1571b5a92b.png)

But it's not working for PAN!
![image](https://user-images.githubusercontent.com/5684607/100660583-7b681980-3367-11eb-9ee6-02f11b7b0b83.png)

**Comment by mdehghani** [comment]
the PAN conversion is calculating using Coingecko api and all other tokens are calculating using Cryptocompare api.
I couldn't find the reason of this, so I decided to get all conversion rates through Cryptocompare api.

**Comment by mdehghani** [comment]
To solve the issue, we need to add an item for PAN "tokenWhitelist" value in config file that contains a field named "coingeckoId" with value "panvala-pan". For better understand, you can take a look at beta.json file. It has the correct value, but it is not correct in develop.json.
At the other hand, if you want to use the coingecko api for another token, you should the field "coingeckoId" for the token too. to achieve the list of all ids, you can use the following api:
https://api.coingecko.com/api/v3/coins/list

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/104940438-f7c1c500-59c6-11eb-913e-35c351172cbc.png)
