### ISSUE TITLE
Oh No! Message still popping up but delegation completed... also happens with Collecting

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1557]
Got this.. then got confirmation of success in bottom right..

![image](https://user-images.githubusercontent.com/39466970/100663269-a6c51700-331b-11eb-9267-17ab50c4e996.png)

![image](https://user-images.githubusercontent.com/39466970/100663442-e4c23b00-331b-11eb-81df-b2ee0c0d9ac8.png)

**Comment by Danibelle** [comment]
Might be something else going on, Feathers?

![Uploading image.png…]()

**Comment by aminlatifi** [comment]
> be something else going on, Feathers?

Maybe you are right.. good point
