### ISSUE TITLE
allow whitelist to be disabled

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#156]
in feathers, we have a boolean that can be used to disable the whitelist. This allows for allowing anyone to use the testing environments, but restricting use on mainnet.

we need to add this to the dapp.

**Comment by satyavh** [comment]
Is there any way we can detect being on mainnet (I guess not)?
Or do we need to set this setting when starting the dapp?

**Comment by perissology** [comment]
yes. it's trivial to detect which network we're on. look at `getNetwork.js`

However this is already set in feathers. We just need to add to the whitelist service and then detect in the dapp

**Comment by satyavh** [comment]
So...why don't we just conditionally return an empty whitelist from feathers?

**Comment by perissology** [comment]
this issue depends on https://github.com/Giveth/feathers-giveth/issues/63.

so this issue just needs to make sure the dapp will ignore the whitelist if the whitelist is empty

**Comment by satyavh** [comment]
Currently we only check for reviewer, so the other whitelists are not implemented. Should we?

**Comment by perissology** [comment]
yes, we want to limit who can create dacs/campaigns when we're on mainnet for the time being

**Comment by satyavh** [comment]
So delegateWhitelist is for creating DACS?
And projectOwnerWhitelist for creating Campaigns?

**Comment by perissology** [comment]
projectOwnerWhitelist is for creating campaigns & milestones. 

maybe we should have separate campaign/milestone whitelists?

or maybe we don't need a milestone whitelist as the campaign owner has to approve any milestones for their campaign.

**Comment by satyavh** [comment]
I don't think we need it for milestone. I'll implement the other once right away

**Comment by vojtechsimetka** [comment]
Fixed in 1b1b2fb364722b0f0e87429c06974558b674ff4c
