### ISSUE TITLE
Rewrite DACservice to support reactie feathers subscribe pattern

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#157]
The DACservice needs to be rewritten to support the feathers subscribe pattern, because MyDACS is using the DACservice, and that page needs to reactively update.

The current pattern uses Promises, but the feathers subscribe pattern uses callbacks (so it can constantly update the data). Also, a conditional unsubscribe needs to be implemented upon `componentWillUnmount`

For examples, check MyCampaigns to see how this pattern is implemented

**Comment by vsimetka** [comment]
Fixed 559fa210764f1f1239c2b54614cfede1494f8f49
