### ISSUE TITLE
Metamask iOS Browser - beta.giveth.io - Creating Milestone / crash

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-dapp#1570]
While using the browser imbedded in the Metamask iOS app on the iPad,and accessing beta.giveth.io, I was attempting to Create a Milestone.  During the process of writing the body description of my milestone proposal, the pop up continues to disappear.  I lose all my progress and am unable to save drafts along the way.

**Comment by GriffGreen** [comment]
#1559
