### ISSUE TITLE
Still getting those false errors on clicking "Collect", even tho everything works

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1574]
<img width="1069" alt="Screen Shot 2020-12-05 at 8 39 29 AM" src="https://user-images.githubusercontent.com/14945613/101244601-c38c9080-3707-11eb-9866-a5a59fd6ec12.png">

Not sure if the Console logs say much:

<img width="554" alt="Screen Shot 2020-12-05 at 8 40 40 AM" src="https://user-images.githubusercontent.com/14945613/101244666-0ea6a380-3708-11eb-9acd-acc5441aa9f7.png">

**Comment by aminlatifi** [comment]
It's happens due to errors thrown by `milestoneContract.mWithdraw` or `milestoneContract.mTransfer`. 

We don't show error popup, if error is undefined we show nothing otherwise some warning toast is sufficient.
