### ISSUE TITLE
Server... feathers or something is unreliable

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1576]
Giveth keeps going down... third time in the last few days? Does a server need to be upgraded or something?

tx still pending:
<img width="1270" alt="Screen Shot 2020-12-05 at 5 59 03 PM" src="https://user-images.githubusercontent.com/14945613/101267148-06755500-3756-11eb-85da-1cdcca64231a.png">

Bridge says its all good
<img width="694" alt="Screen Shot 2020-12-05 at 5 54 57 PM" src="https://user-images.githubusercontent.com/14945613/101267149-07a68200-3756-11eb-9d17-f19db06f6e51.png">

**Comment by aminlatifi** [comment]
There is a chance db connection be the problem.
@mohammadranjbarz Maybe upgrading node version needs mongo driver and mongoose be updated too.

**Comment by aminlatifi** [comment]
@mohammadranjbarz For short solution, make the feathers work with node 8 again. Don't forget to change the circleci config too.
We will upgrade node to 10 again after upgrading database related stuff.

**Comment by aminlatifi** [comment]
@GriffGreen Server has enough resources hopefully

**Comment by geleeroyale** [comment]
> @GriffGreen Server has enough resources hopefully

Please ping me if you discover that the server has to be stronger - I can upgrade it.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz For short-term solution, make the feathers work with node 8 again. Don't forget to change the circleci config too.
> We will upgrade node to 10 again after upgrading database related stuff.

done.
https://github.com/Giveth/feathers-giveth/pull/290

**Comment by papermache** [comment]
this will be further fixed once we have nonprofit discounts and can migrate to azure or AWS.

**Comment by GriffGreen** [comment]
switched back to node 8
