### ISSUE TITLE
Donation sliding scale needs % buttons

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-dapp#1579]
it's much more intuitive to work with percentages instead of sliding amounts or manually entering numbers. % buttons are becoming an industry standard.

![image](https://user-images.githubusercontent.com/2126012/101301944-4eed4b00-3808-11eb-863c-70ef4c5e2e23.png)

**Comment by GriffGreen** [comment]
add the 25/50/100% buttons

**Comment by GriffGreen** [comment]
use a well known slider for crypto

**Comment by MoeNick** [comment]
@RamRamez 
1- Sign In before press donation is missed. 
2- If Im not signed-in, it shows my last sign-in account balance, not mine right now. 
3- If I need to unlock and donate, after I press "unlock & donate" , only unlock works and pop up still remains there. no thank you pop-up will be shown.

**Comment by RamRamez** [comment]
> @RamRamez
> 1- Sign In before press donation is missed.
> 2- If Im not signed-in, it shows my last sign-in account balance, not mine right now.
> 3- If I need to unlock and donate, after I press "unlock & donate" , only unlock works and pop up still remains there. no thank you pop-up will be shown.

They are not related to this issue.
By the way, I mentioned number 1 and 2 in Issue #2093 and PR #2094

**Comment by MoeNick** [comment]
Thanks @RamRamez , what about the delegate buttons, are they fixed?

**Comment by RamRamez** [comment]
> Thanks @RamRamez , what about the delegate buttons, are they fixed?

@MoeNick Yes, sign in check is added for both delegate buttons (in milestone and campaign page and in the my-delegations page) and the donate button.

**Comment by MoeNick** [comment]
Tested, tnx
