### ISSUE TITLE
Have Marko briefly go through V1 and make it slightly easier to use

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-dapp#1582]
See below for specifics.

**Comment by markoprljic** [comment]
@papermache Please describe what specifically should be improved. Thank you.

**Comment by papermache** [comment]
There should be a "Create" button on the My Milestones, My Communities, and My Campaigns pages:
 
![image](https://user-images.githubusercontent.com/2126012/101362840-a6be9d00-386e-11eb-8da4-3b63576fcdff.png)

**Comment by papermache** [comment]
For the new front end developer.

**Comment by markoprljic** [comment]
Can we close this issue?
