### ISSUE TITLE
Attachment Field when Marking Complete not Working

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1583]
When I mark a milestone as complete, I can write complete, but I cannot attach anything. I see attachment field, but it is disabled. I do not know exact specification. Should I attach anything or not? 

- If "No" please remove attachment field from UI. 
- if "Yes" please fix it.
![image](https://user-images.githubusercontent.com/65175075/101368709-b664d280-38bc-11eb-99b6-b59226eeca90.png)

**Comment by GriffGreen** [comment]
Remove the feature!

**Comment by divine-comedian** [comment]
feature has been removed from UI 

![image](https://user-images.githubusercontent.com/67759413/121204123-a8c8df00-c844-11eb-820e-596efd3b86cf.png)
