### ISSUE TITLE
While commenting cannot insert picture.

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1584]
I can add text comment to milestone, but I cannot inset picture in comment box. Maybe this is due to slow mongodb in develop.giveth.io. This is my guess @aminlatifi what do you think?

**Comment by GriffGreen** [comment]
need a progress bar for uploading pictures #1524

**Comment by GriffGreen** [comment]
Look ing for a front end dev to add to Amin's Team :-D

**Comment by aminlatifi** [comment]
@horus2021 It should be fixed by new update.
