### ISSUE TITLE
Donation to Diamante Bridge DAC is STUCK

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1589]
Tien donated .5 ETH to this DAC last night.. we need to move it through to a Milestone for payout but it isn't showing up for Delegation.

Here's how it looks in his "My Donations" still:
![image](https://user-images.githubusercontent.com/39466970/101554863-11f69500-397d-11eb-9a40-b739f591013e.png)

**Comment by GriffGreen** [comment]
https://beta.giveth.io/dacs/5fbbc85f188f980d941470e2 it needed a kick... there is a server issue for sure lately.... we have had trouble diagnosing the problem ;-/
