### ISSUE TITLE
Canceled this milestone... did it work as expected?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1594]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5fd0219a5a4b31622895ab90

**Comment by aminlatifi** [comment]
Money is reverted to campaign,
![image](https://user-images.githubusercontent.com/5684607/102801629-b4296a80-43ca-11eb-9fde-b016fba1edb5.png)
