### ISSUE TITLE
Email Notification Overhaul Requirement Specification 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1597]
Emails are not being passed around well... can we make an email audit?

Status updates should have emails? What else? Can we make more issues and tests on this.

**Comment by GriffGreen** [comment]
This needs to be documented somewhere... where should our docs go? @geleeroyale

**Comment by GriffGreen** [comment]
We need to list out the actual requirements... When are emails made? List it all out! 

Sadly its impossible to maintain a good email service with out clear expectations on the product.

**Comment by GriffGreen** [comment]
docs repo! 

We can do it however we want, we need a giveth 1 section in both.

**Comment by GriffGreen** [comment]
@geleeroyale is making an email notification section. @Danibelle, maybe this is a good first task for one of your crew?

**Comment by Danibelle** [comment]
Yess... taking it to Discordia..

**Comment by laurenluz** [comment]
Not sure I understand the task... Need to just determine when email push notifications are and are not being sent?

**Comment by geleeroyale** [comment]
I think this issue needs more thought. It really is unclear what should happen. To reiterate my opinion from the call - we need to document **full system flows** better and those should include the hooks and services we use for email. 

However - this is not a task for someone new to the system (as all dev documentation), but should be written by @aminlatifi , @arbreton and the like. A contributor could however take the responsibility of reminding others to document :)

In any case - beta now has their own docs page - will differentiate it more visually later.

Deployed at: https://docs.beta.giveth.io
Repo: https://github.com/Giveth/giveth-beta-docs

**Comment by GriffGreen** [comment]
Ashley to take this on!

**Comment by horus2021** [comment]
This is a draft of what @horus2021 and Ashly thinks. It is not finalized yet..
[Giveth 1 Email Overhaul Requirement](https://docs.google.com/spreadsheets/d/1tDqhN41NR_4jvHGFgQOAXHD15PeeHXHICH3Osx64iI0/edit#gid=0)

**Comment by Danibelle** [comment]
Ok Reviewed and Edited!
I was pretty critical and changed a LOT of Yes to No.
There's a transaction confirmation for most of these, so the person making the change does not need to receive an email.

**Comment by aminlatifi** [comment]
Sometime the recipient doesn't have email address, we should ignore that email right?
@Danibelle @GriffGreen

**Comment by horus2021** [comment]
Thanks @Danibelle  for her useful and greate comment. I appreciate all you comments. Please pay attention to my reply on cell [I11](https://docs.google.com/spreadsheets/d/1tDqhN41NR_4jvHGFgQOAXHD15PeeHXHICH3Osx64iI0/edit?disco=AAAALSQUaJQ)
It seems to me that we can forward Email Overhaul one step forward and finalized text for notification emal.

**Comment by horus2021** [comment]
#1522 @GriffGreen  thinks Notification on real transfer money in Mainnet is more important than accounting action in testnet.

**Comment by GriffGreen** [comment]
@laurenluz and @horus2021 are hacking on the emails a lot... its not as simple as before.

Lauren is making inspiring and validating text for each email!

**Comment by laurenluz** [comment]
Actually it's @WhyldWanderer (Ashley) :) not me
