### ISSUE TITLE
Check native currency balance correctness on develop

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1599]

**Comment by horus2021** [comment]
@aminlatifi I do not have any idea what is this issue is about please help.

**Comment by GriffGreen** [comment]
is the native currency working when it is set to Euro, or other currencies

Check that it is working everywhere!

**Comment by horus2021** [comment]
User can change native currency in his profile and we expect DApp updates native currency everywhere DAC, Campaign, Milestoen.

**Comment by horus2021** [comment]
In **Balance Current Value** native currency works. In leader board it does not works, however I am not sure about requirement. It needs clarification. @aminlatifi @GriffGreen please put comments.

Fire Horus (0x17bd53F3295C6E6790aA5fc2D9f0dAd1aad8a139) profile with BRL native currency 
see the following view from[ DAC Hurrican Help](https://develop.giveth.io/dacs/5d6ffe5ee5806c0411f0ae53)
![image](https://user-images.githubusercontent.com/65175075/104914764-d94ad200-59a4-11eb-85f3-65149af4d77a.png)

see the following view from [Campaign My Test Camp](https://develop.giveth.io/campaigns/5fef135eec471b4967fc3b0c)

![image](https://user-images.githubusercontent.com/65175075/104914963-28910280-59a5-11eb-8e36-20c98bc76aa7.png)
