### ISSUE TITLE
Unable to get conversion rates for donations

### ISSUE THREAD

**Issue by papermache** [Giveth/giveth-dapp#1604]
Issue type: **Error**
Sadly we were unable to get the exchange rate. Please try again after refresh.

**Name:**
Timeout of 30000ms exceeded calling conversionRates::find

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"Error: Timeout of 30000ms exceeded calling conversionRates::find\n    at https://d33wubrfki0l68.cloudfront.net/js/307bd597f85cd5be1e0a052e6e68d1c2e6189f1f/static/js/main.8d425d3f.js:1:2234512"
</details>

![image](https://user-images.githubusercontent.com/2126012/103035866-37b39a80-4536-11eb-9366-c88ab9bca8d6.png)

**Comment by aminlatifi** [comment]
Refs #1609

**Comment by aminlatifi** [comment]
We have two type of rates
1. Daily: average rate during a specific date
2. Hourly: Token rate for a requested timestamp, the precision is hourly (minutes, seconds and mili-seconds are considered zero)

@dehghani-giveth The implemented daily rate api resolve requested token rate against all of fiats/tokens listed in configuration. This cause timed-out error on user request or partially filled response (not all rates are resolved)
We need to change daily rate api and how it's used in front-end to just respond daily rate against one token/fiat client requested.

**Comment by aminlatifi** [comment]
@mdehghani Thanks for the pull request and changed you made. The giveth-dapp project should be updated too to become compatible with this changes
giveth-dapp assumes on every call to this api every rates which are resolvable will be fetched. By new change to db only rates has been resolved will be returned which includes the rate dapp has asked in `to` field.

![image](https://user-images.githubusercontent.com/5684607/105025315-6bfd7680-5a62-11eb-87ce-dfc247872606.png)

**Comment by aminlatifi** [comment]
@mdehghani Please test your two PRs together and include these scenarios in your tests
- [ ] Propose Milestone
- [ ] Create Milestone
- [ ] Used different rates and test rateEqSymbol feature
- [ ] Edit proposed milestone

**Note:** 
* Use the latest https://github.com/Giveth/feathers-giveth/pull/362 
* Make the tests cases pass after your change, some of them should be changed.
