### ISSUE TITLE
Unable to get the exchange rate!

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1609]
I am on [promote Plato philosophy..](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201) when I see this error. 

Issue type: **Error**
Sadly we were unable to get the exchange rate! Please try again after refresh.

**Name:**
Timeout of 30000ms exceeded calling conversionRates::find

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"Error: Timeout of 30000ms exceeded calling conversionRates::find\n    at https://d33wubrfki0l68.cloudfront.net/js/7a39e2050105675c476c50f15ddfb58fd1e83289/static/js/main.84f489ac.js:1:2243467"
</details>

**Comment by dehghani-giveth** [comment]
It seems there is a problem in backend on the staging server, so the 'getConversionRate' request times out sometimes. We dont want to show an error popup in this situation. So I added an argument to the service to indicate that if we want to show the popup and pass false value to it in this page.

**Comment by horus2021** [comment]
This issue happens sometime. I have no idea how to regenerate this issue again! If @dehghani-giveth sure about fix, we can close this issues.

> It seems there is a problem in backend on the staging server, so the 'getConversionRate' request times out sometimes. We dont want to show an error popup in this situation. So I added an argument to the service to indicate that if we want to show the popup and pass false value to it in this page.

**Comment by mdehghani** [comment]
now we show a toast to the user if conversionRate service fails.
