### ISSUE TITLE
When sorting the My Milestones page it is missing the partially paid out milestones... I guess because they are still in active

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1612]
To recreate:

Go here: https://beta.giveth.io/my-milestones

<img width="474" alt="Screen Shot 2020-12-27 at 9 57 08 PM" src="https://user-images.githubusercontent.com/14945613/103186427-cd498400-48c0-11eb-8eb3-1eb0733b3a6d.png">

^^^ Click Paid

then click "2"

<img width="246" alt="Screen Shot 2020-12-27 at 9 59 29 PM" src="https://user-images.githubusercontent.com/14945613/103186526-1c8fb480-48c1-11eb-9cfa-30bfee671775.png">

Notice this milestone is nowhere to be found: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f032863913cce2008c7e4dd

**Comment by aminlatifi** [comment]
Only milestones with Paid status are shown in Paid tab, and Paid milestones are capped milestones which has fully founded and paid after.

**Comment by aminlatifi** [comment]
I fooled the dapp to consider me having your wallet address. I could see https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f032863913cce2008c7e4dd

![image](https://user-images.githubusercontent.com/5684607/104716346-12810900-573d-11eb-9cf3-9e6b477a57e8.png)
