### ISSUE TITLE
Dani to get the power to appoint DAC and Campaign managers

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1618]

**Comment by Danibelle** [comment]
I'm available today to do this with @aminlatifi or @geleeroyale

**Comment by geleeroyale** [comment]
Amin showed me how to make changes to the whitelist. I'd say its no problem for @Danibelle to get 'the power's but you would need to be ready to access the backend via terminal and add directly to a file on the server.

It is probably easier for you to just PM me with addresses that should be added.

**Comment by Danibelle** [comment]
Amin is awesome and will make this a UI function!
