### ISSUE TITLE
New design of Dapp using a strong UI framework

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1619]
@peymannaderi3 Has awesome ideas about redesigning Giveth Dapp using a modern strong UI framework (Ant Design, Bulma, Material UI, etc.)

Peyman likes [Ant Design](https://ant.design/docs/spec/introduce) most

**Comment by markoprljic** [comment]
Ant is cool, it even has a Figma library (the extended version is paid).

@peymannaderi3 Can you describe your ideas on why and how you would use such a UI library and what benefits will this provide to the project?

**Comment by peymannaderi3** [comment]
Using such libraries would help us to develop the project faster and it improves ui consistency.
There are some complexity in the project that i think can be much simpler by rewriting the views from scratch.

**Comment by markoprljic** [comment]
Thanks! 
I believe we're currently using Bootstrap, right @aminlatifi?

@peymannaderi3 Can you elaborate on how a different framework would lead to faster development and improve UI consistency?

**Comment by aminlatifi** [comment]
> Thanks! 
> I believe we're currently using Bootstrap, right @aminlatifi?
> 
> @peymannaderi3 Can you elaborate on how a different framework would lead to faster development and improve UI consistency? 

Yes,

**Comment by peymannaderi3** [comment]
> Thanks!
> I believe we're currently using Bootstrap, right @aminlatifi?
> 
> @peymannaderi3 Can you elaborate on how a different framework would lead to faster development and improve UI consistency?

Well, I think current ui can be improved and make it simpler for users. Currently we're using Bootstrap; but as far as i know bootstrap style is pretty old even though it has changed over time. The other problem is with the way we are using Bootstrap in our project that we're importing the cdn  and  jquery instead of using React-Bootstrap library.

**Comment by markoprljic** [comment]
I'd like to evaluate the effort/impact/budget/timeline before jumping into this. 
@aminlatifi and @GriffGreen I'd like your opinion on this as well.
