### ISSUE TITLE
Wrong Value in Requested Crypto Column in Milestone List

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1626]
I as (Sunny) checked my milestone list. The requested crypto for [MILESTONE groceries in develop ;(](https://develop.giveth.io/campaigns/5ed2848c0486523330330eae/milestones/5f4407d6ce0f0025aa7e54ec) is wrong see below picture. 
![image](https://user-images.githubusercontent.com/65175075/103443855-29712700-4c78-11eb-835c-97f25269f0af.png)

**Comment by mohammadranjbarz** [comment]
@horus2021 

Your link is invalid https://develop.giveth.io/campaigns/5ed2848c0486523330330eae/milestones/5f4407d6ce0f0025aa7e54ec

I would appreciate if give the valid link for this milestone

**Comment by aminlatifi** [comment]
It's the link
https://giveth-dapp.netlify.app/campaigns/5ed2848c0486523330330eae/milestones/5f4407d6ce0f0025aa7e54ec

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @horus2021 
Could you provide more info for this issue?

**Comment by mohammadranjbarz** [comment]
@aminlatifi  I talked with @horus2021  and we realized that Hadi was wrong,  for uncapped milestones yes we just have the token symbol but for capped milestones we should add amount + symbol in the row, if am I right you can close this issue

**Comment by horus2021** [comment]
> 
> 
> @aminlatifi I talked with @horus2021 and we realized that Hadi was wrong, for uncapped milestones yes we just have the token symbol but for capped milestones we should add amount + symbol in the row, if am I right you can close this issue

Yes this is totally a misunderstanding by me.
