### ISSUE TITLE
Giveth Loads for other people... but not for me!!! Worked 10 hours ago?!?!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1635]
<img width="949" alt="Screen Shot 2021-01-04 at 9 12 38 AM" src="https://user-images.githubusercontent.com/14945613/103543900-8dc1ff80-4e9f-11eb-9639-564c4fda40eb.png">

I tried refreshing a lot.... not sure whats up..

**Comment by GriffGreen** [comment]
![Uploading Screen Shot 2021-01-04 at 9.20.58 AM.png…]()

**Comment by mohammadranjbarz** [comment]
@GriffGreen 

Is your metamask open and it's working?
I had a similar issue like this, The develop and beta was not  loaded in my system and agter investigating I saw that my metamask in close and the extension is not working ( after restart my system this my metaamask was closed and I faced this problem)
I think its worth to test it , my problem solved by opening the metamask

**Comment by mohammadranjbarz** [comment]
> @GriffGreen
> 
> Is your metamask open and it's working?
> I had a similar issue like this, The develop and beta was not loaded in my system and after investigating I saw that my metamask in close and the extension is not working ( after restart my system, my metaamask has been closed and I faced this problem)
> I think its worth to test it , my problem solved by opening the metamask
Sorry now I check that in screenshot your metamask is open,  I think we had different problem

**Comment by aminlatifi** [comment]
The way we connect to MetaMask and handling events is challenging and is not solid implementation. I suggest switching to onboardjs, it has better event handling, supporting large number of wallets and has required functionalities out of the box.
#1538

**Comment by aminlatifi** [comment]
> @GriffGreen
> 
> Is your metamask open and it's working?
> I had a similar issue like this, The develop and beta was not loaded in my system and after investigating I saw that my metamask in close and the extension is not working ( after restart my system, my metaamask has been closed and I faced this problem)
> I think its worth to test it , my problem solved by opening the metamask

Also, App is not loaded if MetaMask is connected to turned off network! like when you had connected it to localhost networks and have killed the ganache
