### ISSUE TITLE
When creating a new milestone... you have to go really fast or the page refreshes and you lose everything!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1636]
reported by 2 users

**Comment by peymannaderi3** [comment]
@GriffGreen What does it mean that you lose everything?
I just created a milestone and after creating you are redirected to the campaign page and the milestone will be in pending at first so the user would see the milestone right away.

**Comment by aminlatifi** [comment]
@peymannaderi3 @GriffGreen Probably it means user should fill the form fast, otherwise the page will refresh and filled data is lost.

**Comment by peymannaderi3** [comment]
@aminlatifi @GriffGreen I've tested the create new milestone page and could not reproduce the bug.
If you can please tell me how i can reproduce the bug.

**Comment by aminlatifi** [comment]
> @aminlatifi @GriffGreen I've tested the create new milestone page and could not reproduce the bug.
> If you can please tell me how i can reproduce the bug.

Test with beta/develop/localhost backend and  under unstable link condition (I mean feathers or web3 node are not reachable)

**Comment by GriffGreen** [comment]
Reported by several users... :-/
