### ISSUE TITLE
Specify the Roles of the Giveth Platform

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1638]
The overhaul was so amazing! Let's do it for the Roles! 

what can a Campaign Manager do?

What can a DAC Delegate do?

Reviewers?

**Comment by horus2021** [comment]
https://docs.google.com/document/d/1E6zBzVVpSW5_ISmSpdqFgoJCMIKFPztZMf_uhF2IKnY/edit#

**Comment by horus2021** [comment]
> https://docs.google.com/document/d/1E6zBzVVpSW5_ISmSpdqFgoJCMIKFPztZMf_uhF2IKnY/edit#
@GriffGreen I re-share it with all Giveth people. Please check it and let me know if you have problem.

**Comment by GriffGreen** [comment]
Hunt down Amin! ;-)

**Comment by aminlatifi** [comment]
#1846
