### ISSUE TITLE
Show Campaign Reviewer

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#164]
**Task**
Show who is a Campaign Reviewer in the Campaign details page - View Campaign component.

**Comment by GriffGreen** [comment]
.1 eth bounty by Gov campaign

**Comment by 0x6431346e** [comment]
I can take a crack at this if it's alright

**Comment by vojtechsimetka** [comment]
@0x6431346e go for it

**Comment by GriffGreen** [comment]
@0x6431346e Did you end up doing this one?

@vojtechsimetka Who do i owe the 0.1 ETH to?

**Comment by vojtechsimetka** [comment]
Nope @raresica did. You can see the two PR's above.

**Comment by raresica** [comment]
i will create the video tomorrow, i am out of the city, and i do not have my laptop with me. thank you
