### ISSUE TITLE
Error on token and symbol

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1640]
Issue type: **Error**
Sadly we were unable to load the Campaign in which this Milestone was created. Please try again.

**Name:**
Cannot read property 'symbol' of undefined

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"TypeError: Cannot read property 'symbol' of undefined\n    at t.value (https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:4209226)\n    at t.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:4208008)\n    at _ (https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:2459653)\n    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:2459441)\n    at Generator.e.<computed> [as next] (https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:2459832)\n    at r (https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:4202729)\n    at https://d33wubrfki0l68.cloudfront.net/js/86b81e274eb3154d15ca38e762a1400c63613eec/static/js/main.e3cd2084.js:1:4202823"
</details>

**Comment by mohammadranjbarz** [comment]
Getting this error 

When in user wants to creaate milestone for a campaign , but in login dialog user pressed on not now get this error

![image](https://user-images.githubusercontent.com/9850545/103636058-ae9d5a00-4f5e-11eb-9e39-0c924024762a.png)


![image](https://user-images.githubusercontent.com/9850545/103636067-b0ffb400-4f5e-11eb-844f-b6eeacf122fb.png)
