### ISSUE TITLE
 Whitelist permissions for giveeth for ZER8( the first crypto funded social engineering project for the youth of Romania)

### ISSUE THREAD

**Issue by Razga** [Giveth/giveth-dapp#1645]
**ZER8** is the name of my social engineering project based on providing clothing accompanied by _educational products_ (with a cool design for the younger generation) based on history, science and knowledge that me and my team(a psychologist and engineer) are deploying. 

This is my solution for a BiG  problem we have in _Romania_, a large part of the youth live below means and believe that education is only in order to get into university. The mentality of the previous generation(that lived under communism) does not neccesaraly prepare them for the modern world of today.

The mission is to make education, tech and history seem like something valuable and cool that is worth investing time in, not just means in order to get a job, but also in order to empower them to BECOME the creators of tommorow.

Altough Romania is part of the EU, the EU funds to not always reach those in need and  sometimes get siffoned along the way .

Oh, if you think this is something to ignore or not worth your time, check these news and studies:

https://business-review.eu/br-exclusive/romanias-shameful-statistics-1-in-4-people-lives-in-a-house-without-bath-shower-or-indoor-flushing-toilet-183532
https://www.romania-insider.com/romania-children-indoor-toilet

All the work we will do will be public and posted on Twitter, Instagram, Facebook and Linkedin.

Public Eth Address : 0xb62E762Af637b49Eb4870BCe8fE21bffF189e495

**Comment by Danibelle** [comment]
@geleeroyale  ..
Vojtech taught me how to add people to feathers but it has been a while since I did it on a different computer.

I know you said I can just send you the address in PM, I"ll do that now with this one and give you the link ;)

**Comment by Danibelle** [comment]
@Razga please test to see if you can now create a Campaign!

**Comment by Razga** [comment]
Got it.

**Comment by Razga** [comment]
@Danibelle It works now, thanks
