### ISSUE TITLE
Redesign edit campaign form

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1647]
On creating new campaign page if user switches to wrong network no tx is created and campaign is saved in db without tx info. It ends up the created campaign stay in pending state forever.

**Expected behavior**
A popup should warns user to switch to correct network and don't disappear till do it.

**Note:**
onboard.js support such functionality and if we decide to adapt it to Giveth 1 it's not necessary to implement ourself

**Comment by GriffGreen** [comment]
This is implemented for milestones... it just needs to be added for Campaigns AND DAC's

**Comment by aminlatifi** [comment]
We should used the components used here #1214

**Comment by GriffGreen** [comment]
Waiting for the update of Campaigns creation

**Comment by MoeNick** [comment]
#1967

**Comment by MoeNick** [comment]
It has been redesign with new components.  All forms should be tested. @mohammadranjbarz @MoeNick

**Comment by MoeNick** [comment]
![4df3f589-5312-4f28-9acf-df3e6d03954f](https://user-images.githubusercontent.com/80677512/113570352-63f8b000-9629-11eb-9ac8-347e5fcee8de.jpg)
Reviewer list is not valid.

**Comment by aminlatifi** [comment]
> ![4df3f589-5312-4f28-9acf-df3e6d03954f](https://user-images.githubusercontent.com/80677512/113570352-63f8b000-9629-11eb-9ac8-347e5fcee8de.jpg)
> Reviewer list is not valid.

Fixed

**Comment by MoeNick** [comment]
Tested and passed.
