### ISSUE TITLE
Same issue different error... can't get dapp to load

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1649]
Issue type: **Error**
Something went wrong with getting user profile. Please try again after refresh.

**Name:**
Timeout of 30000ms exceeded calling users::find

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"Error: Timeout of 30000ms exceeded calling users::find\n    at https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2242781"
</details>

**Comment by aminlatifi** [comment]
#1660
