### ISSUE TITLE
Another Error... can't load dapp

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1650]
Issue type: **Error**
Unable to load dacs, Campaigns or Milestones.

**Name:**
Timeout of 30000ms exceeded calling dacs::find

**LineNumber:**
undefined

**FileName:**
undefined
<details><summary>Stack</summary>

"Error: Timeout of 30000ms exceeded calling dacs::find\n    at https://d33wubrfki0l68.cloudfront.net/js/775b810a10a70f4cda19c9936a1da6445af15165/static/js/main.d267e863.js:1:2242781"
</details>

**Comment by aminlatifi** [comment]
#1660
