### ISSUE TITLE
Repeated DAC in the list

### ISSUE THREAD

**Issue by peymannaderi3** [Giveth/giveth-dapp#1651]
/campaigns/5fef135eec471b4967fc3b0c/milestones/new
In develop when i want to create a new milestone int the list of "DAC to donate to *"  there are two equal campaigns.

**Comment by peymannaderi3** [comment]
![Screen Shot 1399-10-19 at 1 28 55 PM](https://user-images.githubusercontent.com/25097709/104001836-7a6fa680-51b5-11eb-8e5c-f1af240e39df.png)

**Comment by aminlatifi** [comment]
It's on develop env, and delegate Id is 581
There is two entry with same delegetId

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I think it's because of bad behaviour of simulation and it fixed on simulation script, but its far from deploy (because of changing and refactoring simulation script)

**Comment by aminlatifi** [comment]
Please remove the duplicate dac entity in DB

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
@peymannaderi3 

The second DAC that was created in simulation by mistake is deleted now,

And the simulation problem has fixed already, So it would not happen again, I think we can close this issue
