### ISSUE TITLE
Whitelist Jake Cassani as Campaign Manager

### ISSUE THREAD

**Issue by freedumbs00** [Giveth/giveth-dapp#1652]
@GriffGreen     Necesito hacer campanas en Costa Rica por favor y gracias.

**Comment by Danibelle** [comment]
Reminder @freedumbs00 to select me as Campaign Reviewer!

**Comment by geleeroyale** [comment]
Your address has been added to the whitelist @freedumbs00 🎉

**Comment by freedumbs00** [comment]
@Danibelle  Will do!!!

**Comment by freedumbs00** [comment]
@Danibelle  Hey I need to use a different addy for the campaign.  0x41c7C469BDA5CE9dD6Bf69372875c21806ABE1B6

**Comment by aminlatifi** [comment]
Done

**Comment by aminlatifi** [comment]
@freedumbs00

**Comment by freedumbs00** [comment]
Thanks Amin!
