### ISSUE TITLE
Leaderboard should show donations with zero USD value

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1656]
Current implementation of leaderboard doesn't show donations of a user if all of his donations have zero value in USD (usdValue in db docs).
Since rate service can be down or irresponsible sometimes, this cause user doesn't see his donations.

**Comment by mohammadranjbarz** [comment]
It wasn't giveth-dapp issue , there was a condition in `/aggregateDonatiosService` webservice of feathers that it didnt return the donations with `totalAmount:0` in usdValue that I removed that condition.
@aminlatifi
