### ISSUE TITLE
Document simulations script

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1669]
Simulation script is not visible much from outside while it's doing crucial job in keeping feathers state synced.
Whole simulation script concept and idea behind needs to be documented and also the design should be too. 
It should explain the functionalities (what kind of patching it does)

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Could you give me access to push feature branch on this repo: https://github.com/Giveth/giveth-beta-docs
