### ISSUE TITLE
When I click "create my profile" on the "please register" pop up, i get 404

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#1670]
I tried to create a milestone in the Giveth 2 Campaign on beta.giveth.io. I recieved a pop up that said "please register" 
![image](https://user-images.githubusercontent.com/74267818/104379134-a610ca80-54ee-11eb-863f-c81bcd9959bf.png)

and when i clicked the "create my profile" option, i got a 404 error:
![image](https://user-images.githubusercontent.com/74267818/104379097-97c2ae80-54ee-11eb-97bb-88008734ef63.png)

**Comment by GriffGreen** [comment]
when going thru a milestone... you get the error message

**Comment by aminlatifi** [comment]
@WhyldWanderer Profile form has been refactored on some extend, the bug seems is fixed. Please test it.

**Comment by WhyldWanderer** [comment]
@aminlatifi I went through the process again...

I click create new milestone on the campaign page.. then it asks me to sign in.
![image](https://user-images.githubusercontent.com/74267818/105904449-c2c8fa00-5fe6-11eb-8169-87ae75075d4f.png)

after i click ok, the please register pop up comes up
![image](https://user-images.githubusercontent.com/74267818/105904472-ca889e80-5fe6-11eb-8347-1c7797af391f.png)

after i clicked create my profile it asked me to sign in again
![image](https://user-images.githubusercontent.com/74267818/105904525-d83e2400-5fe6-11eb-9a0b-331dd456f62c.png)

this time, my metamask opens and i sign the transaction..
![image](https://user-images.githubusercontent.com/74267818/105904558-e7bd6d00-5fe6-11eb-896c-b6204d991307.png)

Then for like 2 seconds i see the profile creation screen..
![image](https://user-images.githubusercontent.com/74267818/105904850-4b479a80-5fe7-11eb-9352-23af3b4b8361.png)

after about 2 seconds, the screen automatically goes to 404..
![image](https://user-images.githubusercontent.com/74267818/105904809-3965f780-5fe7-11eb-94e7-8bafedd1549c.png)

If i click the back button in my browser, it brings me back to profile creation page and i can successfully create my profile.
Hope this was helpful!

**Comment by aminlatifi** [comment]
@WhyldWanderer Please do your tests on develop.beta.giveth.io, we have changes not merged yet and may have fixed this issue

**Comment by GriffGreen** [comment]
Happening on Develop

**Comment by WhyldWanderer** [comment]
I have tested and am unable to recreate the error.
I think its fixed! Good job guys
