### ISSUE TITLE
Autogenerate token name

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#168]
As discussed in product_dev channel, now that we show token names & symbols: 
1. They should be immutable
2. Token names and symbols should be generated automatically. E. g. `tokenSymbol: GVT` (Giveth token) and  `tokenName: the name of the campaign / dac`
3. Still allow those who are interested to define the name and symbol for their token.

**Comment by perissology** [comment]
note, that for 3. this has to be done at creation time. After a dac/campaign is created, the token name/symbol is immutable

**Comment by GriffGreen** [comment]
Probably easy to leave the option there for the next few DACs.. We should remember that at least until we solve a way for this dapp to use some sort of stable coin, the majority of groups that will use this will be familiar with Ethereum and will think its fun to choose their token name and symbol.

**Comment by vsimetka** [comment]
Just adding as reference @kingflurkel response in Giveth slack:

> With every hashtag in swarm city, 2 rep tokens are deployed. The shortname is always SWR, the full name is Swarm City Seeker Reputation INSERT HASHTAG / Swarm City Provider Reputation INSERT HASHTAG
Having the same shortname makes it easy to query it on fi. ethplorer

**Comment by vojtechsimetka** [comment]
I'd suggest to follow Swarm City model and use:

Token Symbol: `GVT`
Token Name : `Giveth - <TITLE OF THE DAC/CAMPAIGN>`

The idea is that both of these values are shown to the user but not editable until they explicitly say so.

@GriffGreen Could you confirm the Token Symbol and Name are fine?

**Comment by vojtechsimetka** [comment]
We removed governance tokens. The decision has been made to simplify the DApp but also because since we will support token donations it would be very difficult to decide how much governance tokens should be emitted.
