### ISSUE TITLE
Making a new milestone and all info is lost because of a refresh :-(

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1680]
https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6/milestones/propose

This bug is real, try that campaign, just happened there for me

**Comment by aminlatifi** [comment]
#1636

**Comment by aminlatifi** [comment]
@peymannaderi3 As we discussed, on possible cause would be exception thrown by rate service.
If that wasn't the case, we should investigate other possiblities.

**Comment by GriffGreen** [comment]
Some development has been done.... really hard to replicate :-(
