### ISSUE TITLE
Use UserProvider in all components instead of passing userInfo as a property

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1681]
We have created a react provider for user info, but had passed it as property in many places. Those passed props should be removed and UserProvider should replace it.

**Comment by RamRamez** [comment]
In PR #2296 the below issues are done:
1. Remove unnecessary props: currentUser, displayForeignNetRequiredWarning, balance, isForeignNetwork, match and history props
2. Fix Community Button wrong url type

**Comment by aminlatifi** [comment]
Tested, it's ok
