### ISSUE TITLE
Test that delegation from a DAC with a comment shows the Comment

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1684]
When user delegate token to a project, one or multiple donations entities will be created. New feature will allow the user to put comment when doing delegate action and all donations created by that should have comment value.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Is this block yet?
Can I start before closing Giveth/giveth-dapp#1679

**Comment by mohammadranjbarz** [comment]
When I was testing I understood that in delegation we just have `Committed` donations ,    and the `Commited` donation has the comment so we don't need propagation  ( it's not like direct donations that have `Waiting` donation and after that `Commited`, ...)
So I think this taks ha nothing to do, 
@aminlatifi  What's your opinion?

**Comment by GriffGreen** [comment]
needs testing when a user delegates from a DAC directly to a milestone.

**Comment by GriffGreen** [comment]
Contact @mohammadranjbarz for questions

**Comment by laurenluz** [comment]
@mohammadranjbarz I test this on develop, right?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I test this on develop, right?

@laurenluz 
yes please
test both donate and delegate

**Comment by aminlatifi** [comment]
@laurenluz Any updates?

**Comment by laurenluz** [comment]
@aminlatifi so sorry - this fell to the wayside. I'll test or ask @WhyldWanderer to help this week

**Comment by WhyldWanderer** [comment]
Tested! 
Comments are working!
![image](https://user-images.githubusercontent.com/74267818/111254249-3c8a6680-85da-11eb-8386-ba3e298cb7f6.png)

**Comment by WhyldWanderer** [comment]
I tested this on develop and its working!
