### ISSUE TITLE
Glitch in Display of Large Numbers for Requested Value in Card View of Capped Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1686]
I intentionally put a large number as Requeste Value field of a Capped Milestone to check out UI behaviour. I see this in parent [campaign Fire Fire Fire](https://develop.giveth.io/campaigns/6005804661cc26692cadff71) 
![image](https://user-images.githubusercontent.com/65175075/104917843-32b50000-59a9-11eb-9830-fe2212e8119a.png)

**Comment by aminlatifi** [comment]
@horus2021 

![image](https://user-images.githubusercontent.com/5684607/105825113-783e8200-5fd4-11eb-9782-a755f4f4fc9d.png)

**Comment by horus2021** [comment]
Excellent Job. Thanks @peymannaderi3
