### ISSUE TITLE
Milestone "Paid" doesnt connect to mainnet payment... only rinkeby

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1689]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5ff3daeb2d93392e76e6b738

This milestone says Paid... BUT IT LIES!!! ;-) It was never paid... There probably could be a few issues out of this one... its a big fail of the system

see the https://bridge.beta.giveth.io/

<img width="1235" alt="Screen Shot 2021-01-19 at 2 45 00 PM" src="https://user-images.githubusercontent.com/14945613/105085162-aa615880-5a97-11eb-8565-69f505da2c2e.png">
<img width="738" alt="Screen Shot 2021-01-19 at 2 44 46 PM" src="https://user-images.githubusercontent.com/14945613/105085170-acc3b280-5a97-11eb-9aa5-e49028df5577.png">

**Comment by aminlatifi** [comment]
It has paid by this tx
https://etherscan.io/tx/0xa58a3f60cfb8b717482a01bc2a50ace9a2a237c8b1237bd3b9442f62aaae93a1

**Comment by aminlatifi** [comment]
I manually patched the db and could create this
![image](https://user-images.githubusercontent.com/5684607/105223010-7c037c00-5b70-11eb-93ed-4416f59ce0f2.png)


@GriffGreen @bowensanders Is it enough?

**Comment by aminlatifi** [comment]
We should rewrite bridge monitor, it's design doesn't save events and not allow make an event be replayed!

**Comment by aminlatifi** [comment]
@GriffGreen I guess this issue is over... we have fixed the issue by patching bridge monitor manually. We should rewrite most of it to make it more reliable

**Comment by GriffGreen** [comment]
<img width="252" alt="Screen Shot 2021-01-25 at 12 04 59 PM" src="https://user-images.githubusercontent.com/14945613/105738947-df5a2900-5f37-11eb-950c-ea637f332f6f.png">

This should say "Payment Requested" when sent to the Bridge


This should only say paid for capped milestones if the payment has been sent on mainnet

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Could you check and tell me if the exported csv is ok or need some changes:
https://docs.google.com/spreadsheets/d/1PYTEn7AiN_rg3Q3_BpqWDBH-FoWVBGVCefSGcgnAUOU/edit?usp=sharing

**Comment by aminlatifi** [comment]
> @aminlatifi
> Could you check and tell me if the exported csv is ok or need some changes:
> [common stack campaign donations.csv.zip](https://github.com/Giveth/giveth-dapp/files/6038386/common.stack.campaign.donations.csv.zip)
> 
> https://docs.google.com/spreadsheets/d/1PYTEn7AiN_rg3Q3_BpqWDBH-FoWVBGVCefSGcgnAUOU/edit?usp=sharing

Thanks @mohammadranjbarz, just fix time format and and remove the bridge status column. Just having time and transaction means it has been paid and status column is not necessary

**Comment by aminlatifi** [comment]
New entry `paymentTransactionHash` is added to bridge monitor api output, it's added just for payment after 2021 Jan 30
https://feathers.bridge.beta.giveth.io/payments?event.returnValues.reference=0xaf2b14cd98187352bc1dbf8e44c758ee552d0936dacb9d1aad28d197fe5e0566

**Comment by aminlatifi** [comment]
> New entry `paymentTransactionHash` is added to bridge monitor api output, it's added just for payments after 2021 Jan 30
> https://feathers.bridge.beta.giveth.io/payments?event.returnValues.reference=0xaf2b14cd98187352bc1dbf8e44c758ee552d0936dacb9d1aad28d197fe5e0566

Older transactions have it now too

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi
> > Could you check and tell me if the exported csv is ok or need some changes:
> > [common stack campaign donations.csv.zip](https://github.com/Giveth/giveth-dapp/files/6038386/common.stack.campaign.donations.csv.zip)
> > https://docs.google.com/spreadsheets/d/1PYTEn7AiN_rg3Q3_BpqWDBH-FoWVBGVCefSGcgnAUOU/edit?usp=sharing
> 
> Thanks @mohammadranjbarz, just fix time format and and remove the bridge status column. Just having time and transaction means it has been paid and status column is not necessary

Done,
You can check the new CSV here:

https://docs.google.com/spreadsheets/d/17b7tmKbZt9qn3WEQKVbjhNbk01THncqKF02PbPzpJP8/edit?usp=sharing

@aminlatifi  And now I use paymentTransactionHash that you added to bridge monitor response

**Comment by aminlatifi** [comment]
The backend part is implemented
