### ISSUE TITLE
External Notifications

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#170]
Adding email notifications to the DApp and hooking it to events like new donation, new delegation, milestone status change and others.

**Comment by satyavh** [comment]
This is actually an epic, not a story. It includes:

- design an email template
- code the email template and make it dynamic
- setup email API (I have good experience with Mailgun, it's free for our volume)
- setup DNS etc to make sure our emails get delivered
- implement some kind email job worker to tackle failed email deliveries
- handle unsubscribes

Future: 
- daily aggregation emails, example: we might not want to sent an email for each donation
- handle timezones

Now for the fun part, when are we going to send emails?

1. Based on stuff that happens in Feathers (boring...!)
2. Based on blockchain / contract events (way cool, this is the new reality!)

But can we do only #2 @perissology ?

**Comment by perissology** [comment]
ya, it'll mostly be for #2, except for marking a milestone complete as that is done off-chain & needs a notification.

there might be some other cases that need notifications, but aren't on-chain actions.

for anything that happens on-chain, we should only notify after the tx is confirmed / event fired

**Comment by satyavh** [comment]
Super awesome. I'm imagining Etherscan for marketing triggers here. I'm so going to build this :-D
