### ISSUE TITLE
Email Notification Overhaul

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1700]
This is an EPIC (Super Task) on Email Notification Overhaul. We need to revise everything related to notification email in Giveth  
This EPIC has 4 Phase

Phase 1) Requirement Specification. Finalizing the list of email. The [list of emails](https://docs.google.com/spreadsheets/d/1gqyb8_ATVbbu0Xi2DjINyXBMvpznlsKcUUrp_dutg1A/edit#gid=1084492120) determines who receives what email when. The list is Google sheet and any comment is welcomed.

Phase 2) Content Generation. Finalizing the **Subject**, **secretintro**, **title**,... of emails.

[Email Text](https://docs.google.com/document/d/1mtXaNscF0qottZyvAhLCM36yEXoJDXKrFTfjOH9rE0k/) can be found  in Google doc

@WhyldWanderer @laurenluz as content generator will prepare something like this for each email.

**subject:** Giveth - _campaign name_ has added a new milestone!
**secretintro**: Check out what _campaign name_  has in store!
**title**: _campaign name_ has expanded!
**text**: Hi _Email Recipient_ _campaign name_ added a new milestone _milestone name_ . Come see what awesome things they have planned!
**button link**: _milesone name_ (link to milestone page) 

![image](https://user-images.githubusercontent.com/65175075/107140808-ddca3100-6939-11eb-853e-ad74d178af97.png)

Phase 3) Development 
@mohammadranjbarz  and @aminlatifi  will develop in backend this emal.

Phase 4) Test

**Comment by horus2021** [comment]
This the master sheet of this  [EPC Giveth 1 Email Overhaul Requirement](https://docs.google.com/spreadsheets/d/1tDqhN41NR_4jvHGFgQOAXHD15PeeHXHICH3Osx64iI0/edit#gid=0)

**Comment by WhyldWanderer** [comment]
@laurenluz and I have been adding email content in this working google doc and will add the text into each issue as we finish it.
Once the text has been added to the corresponding issue we will add it to sprint backlog with the correct Milestone Label.
https://docs.google.com/document/d/1mtXaNscF0qottZyvAhLCM36yEXoJDXKrFTfjOH9rE0k/

**Comment by horus2021** [comment]
> 
> 
> @laurenluz and I have been adding email content in this working google doc and will add the text into each issue as we finish it.
> Once the text has been added to the corresponding issue we will add it to sprint backlog with the correct Milestone Label.
> https://docs.google.com/document/d/1mtXaNscF0qottZyvAhLCM36yEXoJDXKrFTfjOH9rE0k/

I like thed Idae, thanks!
