### ISSUE TITLE
Email to Parent Campaign Subscriber When Campaign Manager Accepts a Proposed Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1704]
Emails tells Campaign Subscriber there is an opportunity for giving lablab la..

**Comment by WhyldWanderer** [comment]
to parent campaign subscriber when campaign manager accepts a proposed milestone
subject: Giveth - 'campaign name' has added a new milestone!
secretintro: Check out what 'campaign name' has in store!
title: 'campaign name' has expanded!
text: 'campaign name' added a new milestone. Come see what awesome things they have planned!

Maybe have some sort of preview of the new milestone? And maybe that would link to the milestone page?

**Comment by horus2021** [comment]
@WhyldWanderer please check my revision.

**subject:** Giveth - _campaign name_ has added a new milestone!
**secretintro**: Check out what _campaign name_  has in store!
**title**: _campaign name_ has expanded!
**text**: Hi _Email Recipient_ _campaign name_ added a new milestone _milestone name_ . Come see what awesome things they have planned!
**button link**: _milesone name_ (link to milestone page) 

![image](https://user-images.githubusercontent.com/65175075/107140808-ddca3100-6939-11eb-853e-ad74d178af97.png)

**Comment by MoeNick** [comment]
@mohammadranjbarz it's in our currant sprint, pls go forward. 
I forgot to assign it to u.

**Comment by aminlatifi** [comment]
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
I subscribed https://develop.giveth.io/campaign/renjer-test-campaign
with this user : https://develop.giveth.io/profile/0x4aA4e5B70b5B6529290AA9d2e22599d6887C1216
and after campaign owner accept below milestone
 https://develop.giveth.io/milestone/test-email-to-campaign-subscriber
I got this email:

![Screen Shot 1400-02-27 at 15.40.54.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/ff7c59d0-1d1e-4c64-9ef4-5cc72b599a41)
