### ISSUE TITLE
Email to Parent DAC Subscriber When Campaign Manager Accepts a Proposed Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1705]
Emails tells DAC Subscriber there is an opportunity for giving lablab la..

**Comment by WhyldWanderer** [comment]
to parent dac subscriber when campaign manager accepts a proposed milestone

subject: Giveth - 'dac name' has added a new milestone!
secretintro: Check out what 'dac name' has been up to!
title: 'dac name' has expanded!
text: 'dac name' added a new milestone. Come see what awesome things they have planned!

Maybe have some sort of preview of the new milestone? And maybe that would link to the milestone page?

Is this the kind of feedback your looking for? Am I doing it right? haha

**Comment by mohammadranjbarz** [comment]
I'm in half way of implementing this, but I now I noticed it has a blocker #1722
and that task is not in this sprint, 
So I think it's better to start #1722 as well

**Comment by horus2021** [comment]
Hey @mohammadranjbarz according our weekly meeting subscriber emails are not priority.  see [list of emails](https://docs.google.com/spreadsheets/d/1gqyb8_ATVbbu0Xi2DjINyXBMvpznlsKcUUrp_dutg1A/edit#gid=1084492120). in #1700 emails that  in coloum N, O, and P are not priority. They have blocker, but the blockers are content of emails by @laurenluz and @WhyldWanderer

**Comment by WhyldWanderer** [comment]
Email received!
![image](https://user-images.githubusercontent.com/74267818/113523162-5973e300-9563-11eb-8c19-c1ef5a97ff14.png)
