### ISSUE TITLE
Milestone did not go through to the bridge

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#1718]
I claimed the funds from my milestone: https://beta.giveth.io/campaigns/5f504e7bfb3dbe37aee4e050/milestones/5ffe4e6c0563d75cf55d9fcc
Recipient Address: 0xed8DB37778804A913670d9367aAf4F043AAd938b

But when I check the bridge https://bridge.beta.giveth.io/
I do not see my milestone or address on the list.

When I created my milestone I chose to donate 3% to this DAC: https://beta.giveth.io/dacs/5fbbc85f188f980d941470e2
It appears they have received the donation however I never received the pan in my wallet.

Maybe my milestone is stuck somewhere?

**Comment by aminlatifi** [comment]
It was an inconsistency in bridge-monitor data which is fixed.
