### ISSUE TITLE
Implement a search bar for milestones within a campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1732]
So sick of having to click this so many times:
<img width="259" alt="Screen Shot 2021-02-06 at 4 12 16 PM" src="https://user-images.githubusercontent.com/14945613/107129795-65775780-68c8-11eb-91bd-999e81122593.png">

I am constantly searching for the old Milestones in the Commons Stack It0 Campaign... its pretty annoying... I would love a search bar... But where do we put it, and what should it look like  :-D?

@markoprljic ... This is a tester ;-)

**Comment by markoprljic** [comment]
Search bar on Campaign page to filter Milestones.

<img width="943" alt="Image 2021-02-09 at 2 40 30 pm" src="https://user-images.githubusercontent.com/5704285/107371646-cb402b00-6ae4-11eb-9f76-d6dd6d96e104.png">

**Comment by GriffGreen** [comment]
This issue is cool... it would take some research to understand the requirements to execute

Would need its own server?

**Comment by GriffGreen** [comment]
We could use Azure?
