### ISSUE TITLE
Email to Milestone Recipient When Giver Donates to Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1733]
subject
    secretIntro
    title
    text

**Comment by laurenluz** [comment]
subject: ‘Giveth - Your Milestone has received a donation!’,
secretIntro: ‘Your Milestone ${milestoneTitle} has received a donation of ${normalizedAmount} ${token.symbol}!’
title: ‘You are so awesome!’,
text: ‘Your Milestone ${milestoneTitle} has received a donation of ${normalizedAmount} ${token.symbol}! Check to see how close you are to reaching your goal.’
Cta: ‘Manage your account’
