### ISSUE TITLE
Email to Milestone Reviewer When Milestone Manager Proposes (Creates) a Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1736]

**Comment by laurenluz** [comment]
subject: ‘Giveth - Time to review!’
secretIntro: ‘Take action: A Milestone has been proposed for your review! 
title: ‘Take action: Milestone proposed’
text: ‘The milestone ${milestoneTitle} has been proposed for your review. If you think this is a great idea, please approve this Milestone within 3 days to add it to your Campaign. If not, then please reject it with a comment.'
Cta: ‘See the Milestone’
