### ISSUE TITLE
Email to Milestone Manager (Proposer) When Campaign Manager Edit Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1737]

**Comment by laurenluz** [comment]
subject: ‘Giveth - Your Milestone has been edited’
secretIntro: ‘Your milestone ${milestoneTitle} has been edited by the Campaign Manager.’
title: ‘Your Milestone has been edited’
text: ‘Your milestone ${milestoneTitle} has been edited by the Campaign Manager. Check to see what edits have been made.’
Cta: ‘See the Milestone’
