### ISSUE TITLE
Email to Campaign Manager When He/She Edit Proposed Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1738]
In fact, this is just a confirmation for his action. It proves that the edit has been registered in Giveth bookkeeping system.

**Comment by laurenluz** [comment]
subject: ‘Giveth - You Milestone edits have been submitted’
secretIntro: ‘You have edited the proposed Milestone ${milestoneTitle}’
title: ‘Your Milestone edits have been submitted’
text: ‘Your edits to the proposed Milestone ${milestoneTitle} in your Campaign ${CampaignTitle} have been submitted. Check to review your edits.’
Cta: ‘See the Milestone’
[MilestoneProposed]
