### ISSUE TITLE
Email to Milesotne Manager When He/She Edit his/her Proposed Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1739]
In fact, this is just a  simple confirmation.

**Comment by laurenluz** [comment]
subject: ‘Giveth - You Milestone edits have been submitted’
secretIntro: ‘You have edited the Milestone ${milestoneTitle}’
title: ‘Your Milestone edits have been submitted’
text: ‘Your edits to the Milestone ${milestoneTitle} have been submitted. Check to review your edits.’
Cta: ‘See the Milestone’
[MilestoneProposed]
