### ISSUE TITLE
Email to Campaign Manager When Milestone Reviewer Edits Proposed Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1740]

**Comment by laurenluz** [comment]
subject: ‘Giveth - A proposed Milestone in your Campaign has been edited’
secretIntro: ‘The proposed Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been edited.’
title: ‘A proposed Milestone has been edited’
text: ‘The proposed Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been edited by the Milestone Manager. Check to review your edits.’
Cta: ‘See the Milestone’
[MilestoneProposed]

**Comment by laurenluz** [comment]
@mohammadranjbarz - I just updated the text on this one a few minutes ago - sorry for the late change :(

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - I just updated the text on this one a few minutes ago - sorry for the late change :(

Thanks Lauren, no problem

**Comment by mohammadranjbarz** [comment]
I cant test it because the reviewer account dont see edit icon
#1903

**Comment by GriffGreen** [comment]
This is not something that ever happens.. I'm so sorry for not seeing this earlier :-/
