### ISSUE TITLE
Email to Milestone Givers When Milestone Manager Marks Milestone as Complete

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1743]

**Comment by WhyldWanderer** [comment]
This email seems redundant with #1750

**Comment by laurenluz** [comment]
Subject: Giveth - A Milestone you gave to is complete!
Secretintro: The Milestone ${milestoneTitle} that you gave to has been marked complete by the reviewer.
Title: You are so awesome!
Text: The Milestone ${milestoneTitle} in the Campaign ${campaignTitle} has been marked complete by the reviewer! Your contribution helped make it possible for this Milestone to reach its funding goal. The recipient can now transfer the funds out the Milestone and take action. Together, we are making the world a better place.
Cta: ‘Manage your donations’
[donation]

**Comment by laurenluz** [comment]
@mohammadranjbarz I had to update this one too

**Comment by horus2021** [comment]
@laurenluz I appreciate your nice text. I think button link should be linked to completed milestone not giver donation page.


Subject: Giveth - A Milestone you gave to is complete!
Secretintro: The Milestone ${milestoneTitle} that you gave to has been marked complete by the Milestone manager.
Title: You are so awesome!
Text: The Milestone ${milestoneTitle} in the Campaign ${campaignTitle} has been marked complete by the Milestone manager! Your contribution helped make it possible for this Milestone to reach its funding goal. The recipient can now transfer the funds out the Milestone and take action. Together, we are making the world a better place.
button link: milestone name (link to milestone page)

**Comment by mohammadranjbarz** [comment]
@laurenluz
@GriffGreen
@horus2021

I think Griff said we just need to email to givers when anything happens to money, so I think it's not necessary to send email for giver in this case

**Comment by laurenluz** [comment]
hmm yeah I'm also not sure... @Danibelle - can you confirm? if a milestone is market "complete" (and funds remain) are the funds released to the recipient?

**Comment by Danibelle** [comment]
If the Milestone requires being marked complete then it goes to the Reviewer for approval before funds can be released.. so the Giver would not be notified at this step.

The Reviewer would be notified that it's been marked complete and they need to review it and approve so the funds can be released.

Once Reviewer approves,  then the Donor should be notified that the Milestone they funded has been completed.

**Comment by laurenluz** [comment]
@Danibelle ok thank you!!
@mohammadranjbarz you're right - this email is unnecessary. Closing.
