### ISSUE TITLE
Email to Milestone Reviewer when he/she Approves Milestone Complete

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1749]

**Comment by WhyldWanderer** [comment]
This email seems redundant

**Comment by laurenluz** [comment]
Subject: Giveth - You approved the completion of a Milestone
Secretintro: You have marked the Milestone ${milestoneTitle} as complete. The recipient can now collect the payment.
Title: Milestone completed!
Text: You have marked the Milestone ${milestoneTitle} in the Campaign ${campaignTitle} as complete! The recipient can now transfer the funds out of this Milestone.
Cta: ‘See your Milestones’

**Comment by MoeNick** [comment]
Tested.
