### ISSUE TITLE
Change 72 hours to 3-5 days

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1751]
<img width="469" alt="Screen Shot 2021-02-07 at 12 23 35 PM" src="https://user-images.githubusercontent.com/14945613/107154628-42a27d00-6974-11eb-9d3a-c609b5d41422.png">

Change to:

Note: For security reasons and to save in fees, there is a delay of approximately 2-5 days before the crypto will appear in the recipient's wallet.

**Comment by RamRamez** [comment]
@GriffGreen @MoeNick 
In title it is said 3-5 days but in description it is said 2-5 days.
So how should we change it?

**Comment by aminlatifi** [comment]
> @GriffGreen @MoeNick
> In title it is said 3-5 days but in description it is said 2-5 days.
> So how should we change it?

Let's go with 2-5 days

**Comment by GriffGreen** [comment]
Sounds good! Thx Amin!

**Comment by mohammadranjbarz** [comment]
![Screen Shot 1400-02-26 at 16.12.35.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/31909a67-ec35-44cf-b045-17b55aece5d9)

@MoeNick 
It works,  as you see
