### ISSUE TITLE
Delegation button is inaccessible if the window size is too small

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1752]
<img width="1196" alt="Screen Shot 2021-02-07 at 4 55 12 PM" src="https://user-images.githubusercontent.com/14945613/107160636-bd30c400-6997-11eb-92c6-70c2717869bf.png">

I can't even scroll to it

**Comment by aminlatifi** [comment]
@MohammadPCh Thanks, can you do the same for donate modal?

**Comment by MohammadPCh** [comment]
@aminlatifi I impelemted it But i think it's better to design them with our new design system. i think our modals should have title and show full screen in mobile size.
