### ISSUE TITLE
Email to Campaign Manager when Milestone Reviewer Approves Milestone Complete

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1754]

**Comment by laurenluz** [comment]
subject: ‘Giveth - A Milestone in your Campaign is finished!
secretIntro: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the reviewer.’
title: ‘Milestone completed!
text: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the Milestone reviewer. The recipient can now transfer funds out of this Milestone.’
Cta: ‘See the Milestone’

**Comment by horus2021** [comment]
@laurenluz I appreciate your nice text. Just a bit update to make all things more clear for @mohammadranjbarz .


> subject: ‘Giveth - A Milestone in your Campaign is finished!
> secretIntro: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the Milestone reviewer.’
> title: ‘Milestone completed!
> text: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the Milestone reviewer. The recipient can now transfer funds out of this Milestone.’
**button link: milestone name (link to milestone page)**

**Comment by MoeNick** [comment]
@laurenluz appreciate if u can help

**Comment by MoeNick** [comment]
Tested and its done.
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/0dbdcbd2-1dbc-4577-8dab-cdffbf6140c9)
