### ISSUE TITLE
Email to Campaign Reviewer when Milestone Reviewer Approves Milestone Complete

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1755]

**Comment by laurenluz** [comment]
subject: ‘Giveth - A Milestone in your Campaign is finished!
secretIntro: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the reviewer.’
title: ‘Milestone completed!
text: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the Milestone reviewer. The recipient can now transfer funds out of this Milestone.’
Cta: ‘See the Milestone’

**Comment by horus2021** [comment]
It's a good idea to display profile name of Milestone Reviewer in email text.

subject: ‘Giveth - A Milestone in your Campaign is finished!
secretIntro: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the Milestone reviewer.’
title: ‘Milestone completed!
text: ‘The Milestone ${MilestoneTitle} in your Campaign ${CampaignTitle} has been marked complete by the Milestone reviewer ${profile name of Milestone reviewer} The recipient can now transfer funds out of this Milestone.’
button link: milestone name (link to milestone page)

**Comment by MoeNick** [comment]
@laurenluz @WhyldWanderer can u pls help us test this?

**Comment by MoeNick** [comment]
I tested with ranjbar and it was ok
