### ISSUE TITLE
Email to Parent DAC Community Manager when Milestone Reviewer Approves Milestone Complete

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1756]

**Comment by laurenluz** [comment]
subject: ‘Giveth - Milestone Completed!
secretIntro: ‘The Milestone ${MilestoneTitle} for the Campaign ${CampaignTitle} that you support has been marked complete by the Milestone reviewer.’
title: ‘Milestone completed!
text: ‘The Milestone ${MilestoneTitle} in Campaign ${CampaignTitle} that you support has been marked complete by the Milestone reviewer. The recipient can now transfer funds out of this Milestone.’
Cta: ‘See the Milestone’

**Comment by laurenluz** [comment]
@WhyldWanderer can you review this text to make sure it makes sense?

**Comment by horus2021** [comment]
@laurenluz text makes sense. Just mention the profile name of milestone reviewer everywhere as below.

subject: ‘Giveth - Milestone Completed!
secretIntro: ‘The Milestone ${MilestoneTitle} for the Campaign ${CampaignTitle} that you support has been marked complete by the Milestone reviewer ${profile name of Milestone reviewer}.’
title: ‘Milestone completed!
text: ‘The Milestone ${MilestoneTitle} in Campaign ${CampaignTitle} that you support has been marked complete by the Milestone reviewer ${profile name of Milestone reviewer}. The recipient can now transfer funds out of this Milestone.’
Cta: ‘See the Milestone’

**Comment by MoeNick** [comment]
@MoeNick and @mohammadranjbarz will go on testing
