### ISSUE TITLE
Email to Milestone Givers when Milestone Reviewer Rejects Milestone Complete

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1761]

**Comment by laurenluz** [comment]
The givers don't need to be informed about this, let's skip this email

**Comment by horus2021** [comment]
@horus2021  @laurenluz the givers may want to exit (disburse/refund) their money from rejected milestone. I think this is the right for givers to be informed about this important event and help transparency of Giveth. 
@GriffGreen what do you think?

> The givers don't need to be informed about this, let's skip this email

**Comment by laurenluz** [comment]
I think this is just the reviewer rejecting the "completion" not rejecting the milestone... so the funds from the giver are still there, they just haven't yet reached the funding goal. I asked @GriffGreen about this the other day and he said not to send an email here... but I can write something if we agree that it's necessary.
