### ISSUE TITLE
Listed twice in the leaderboard?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1781]
https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6

<img width="938" alt="Screen Shot 2021-02-09 at 1 09 35 PM" src="https://user-images.githubusercontent.com/14945613/107407798-65ff3080-6b0a-11eb-9a29-eb4379cb7d8a.png">

**Comment by aminlatifi** [comment]
Fixed
