### ISSUE TITLE
Oh No Popup - Why???

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#1785]
When collecting funds from a milestone, I got an inexplicable Oh no! popup even though it seemed that the withdrawal was initiated just fine.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6221d748-87dc-4958-ad5c-bfe0ac9a741f)

**Comment by aminlatifi** [comment]
@laurenluz thanks for reporting, next time please open browser console take a screenshot like below. It would be precious info for us.

![image](https://user-images.githubusercontent.com/5684607/107609514-5d1a7600-6c54-11eb-9657-f4d5f81339f6.png)

**Comment by laurenluz** [comment]
@aminlatifi ok right, makes so much sense. If I can recreate it I'll post the console screenshot here

**Comment by laurenluz** [comment]
It happened again trying to collect DAI. Got an "Oh No!" popup but everything went through fine

![image](https://user-images.githubusercontent.com/75490971/110728266-58f56000-81e2-11eb-8bd6-d32c42574c85.png)

**Comment by aminlatifi** [comment]
@laurenluz Thanks for reporting, unfortunately console doesn't have useful info. 
I pushed a patch to code, it doesn't solve the issue we can reopen this one

**Comment by laurenluz** [comment]
@aminlatifi 

This just happened to me again. I tried to collect from the milestone, and it worked fine, but I received an "Oh no!" popup:
related to #2001 

In the other issue, you said that it is because funds have been collected before from the milestone, but it should be possible for the user to collect multiple times from the payment milestone (i.e. for monthly payments).

I think we need to change the text of this popup so that is says instead something like "You have initiated the collection of funds from this milestone. Please allow up to 72 hours for the funds to be released to the recipient"

![image](https://user-images.githubusercontent.com/75490971/115155118-aebbf400-a03b-11eb-81e9-9da4649a57a5.png)

**Comment by aminlatifi** [comment]
@laurenluz I hope it solve the issue, you can test on develop now.

**Comment by MoeNick** [comment]
> @laurenluz I hope it solve the issue, you can test on develop now.

Can I test?

**Comment by MoeNick** [comment]
Seems it;s ok, I got this:

![image](https://user-images.githubusercontent.com/80677512/115661743-2b5c1480-a353-11eb-979e-e0332e289bf7.png)

**Comment by aminlatifi** [comment]
> Seems it;s ok, I got this:
> 
> ![image](https://user-images.githubusercontent.com/80677512/115661743-2b5c1480-a353-11eb-979e-e0332e289bf7.png)

Actually it's the expected behavior, for better interactivity should hide collect button after user first click. It needs some new design and implementation by me, @MohammadPCh  and @RamRamez
