### ISSUE TITLE
User sees /profile page without unlocking wallet (MetaMask)

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapp#1786]
The app does not seem to react when I click the send button

**Comment by aminlatifi** [comment]
@Santigs Would you please provide more information? Which send button?

**Comment by Santigs** [comment]
Sorry, I meant the Save button
![Screenshot 2021-02-10 at 21 38 32](https://user-images.githubusercontent.com/34634436/107612801-576a6380-6c47-11eb-9496-58242c2c092c.png)
The page does not seem to react. I provided info in all fields

**Comment by aminlatifi** [comment]
@Santigs It seems you haven't enabled Web3, basically you shouldn't see this page until you connect your MetaMask. Thanks for reporting this.

**Comment by aminlatifi** [comment]
@Santigs To make it go through you should unlock your metamask and then try again

**Comment by GriffGreen** [comment]
If the wallet is locked, and the user clicks the Save Profile button, they should be asked to log into metamask.

**Comment by aminlatifi** [comment]
I prefer something like this
https://github.com/MohammadPCh/giveth-dapp/blob/f_1730_create_new_UI/src/components/Web3ConnectWarning.jsx
@MohammadPCh I guess it's better to keep consistency, so fix this issue as part of above branch

**Comment by WhyldWanderer** [comment]
No matter how hard I try,  i am unable to even create a profile without enabling web3 so i assume the loophole has been closed. (Ive tried through creating a new campaign or milestone or donating)

I get this message
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/21bf814a-be67-4110-9263-1e3903fcef71)

When this message pops up, there is no [x] close window option so i must press the back button in my browser to remove the pop up.

**Comment by MoeNick** [comment]
@WhyldWanderer it's not have x button because you need to use metamask changing your account I assume. What do yo think?

**Comment by aminlatifi** [comment]
> No matter how hard I try, i am unable to even create a profile without enabling web3 so i assume the loophole has been closed. (Ive tried through creating a new campaign or milestone or donating)
> 
> I get this message
> ![image.png](https://camo.githubusercontent.com/3809456a801efec5f292e9960fd96b1de7835ddd6b69f24246a6e1d5a4893cab/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566666464653830373937363063343334363338316434352f32316266383134612d626536372d343131302d393236332d316533393033666365663731)
> 
> When this message pops up, there is no [x] close window option so i must press the back button in my browser to remove the pop up.

It's how it has been implemented. In case you visit a page with connected wallet and then you disconnect it, you should not be able to do anything till active it. In case you are directly directed to the view, back button doesn't have any meaning.

**Comment by WhyldWanderer** [comment]
When I try to connect directly in my metamask i get this message
![image](https://user-images.githubusercontent.com/74267818/115445139-b2ce4a00-a1d2-11eb-832a-fdbdcf3ad77d.png)

I guess its not a big inconvenience for a user to press the back button before pressing the "enable web3" button.

**Comment by aminlatifi** [comment]
@WhyldWanderer I imagine adding an `Enable Web3` button to the warning modal, what do you think?

**Comment by WhyldWanderer** [comment]
@aminlatifi I think that would be a sufficient solution... ;)
Or make it so the user is able to interact with the one in the upper right corner.

Sorry for my late response

**Comment by aminlatifi** [comment]
@WhyldWanderer Thanks Ashly for your precious feedback
