### ISSUE TITLE
The transaction pop up should stay twice as long.

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#179]
The transaction pop up that links to the etherscan tx goes away before i have time to comprehend what it says and click... I think it should be up for about 10 seconds... i know its a long time but I think its better to err on too long than too short.

**Comment by GriffGreen** [comment]
Also 
it is linking to: https://beta.giveth.io/campaigns/undefinedtx/0xf7c34b9dcb423a28dea78fd4e8328428770590fc09c2a635ffe218e126852ada

I know the WHG is hot to trot on an open source Etherscan.... but lets keep our scope small and just link to etherscan's centralized version

**Comment by vojtechsimetka** [comment]
Resolved in cc9ed6d1799d012d3dbccf5a2d77a4d1ff54f491
