### ISSUE TITLE
ChangeRecipient button is missing when the transaction is dropped

### ISSUE THREAD

**Issue by darcher-framework** [Giveth/giveth-dapp#1792]
## Description
After we send a transaction to change `recipient` of a `milestone`, the `Change Recipient` button is hidden. 
However, when I drop the transaction using MetaMask or other tools, the button does not come back.

## Reproduce Steps
1. submit a new transaction to change recipient of a milestone. (At this moment, the `Change Recipient` button is hidden)
2. Send another transaction with higher fee using MetaMask to drop the previous transaction. 
3. After the second transaction is confirmed, the `Change Recipient` button does not come back and I cannot change the recipient any more. 

## Expected Behaviour
`Change Recipient` button is expected to be shown when the previous transaction is dropped, since at this time the recipient is not changed and will not be changed.
This use case is useful since I may regret the previous recipient change and want to change to another recipient address.

**Comment by GriffGreen** [comment]
@darcher-framework OMG Thank you sooooooo much for the beautifully written issue! You are a hero!

 Can you give us a link to your milestone? :-D
 
 We will get this sorted ASAP!

**Comment by GriffGreen** [comment]
I am assuming feathers has recorded the false changed address as the new address so now the button doesnt show up... may need a hot fix for this edge case

**Comment by darcher-framework** [comment]
@GriffGreen thanks for your kindness. 
Actually we didn't run into this problem in production environment of Giveth.
We are building automated test framework for DApps like Giveth. 
This is a bug we found in Giveth during testing process.

**Comment by aminlatifi** [comment]
Maybe removing pendingRecipientAddress is better idea, having that makes backend complicated and needs handling such situation (canceling tx) which can happen.
