### ISSUE TITLE
Bad "Read More" Link in Edit DAC page

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1793]
In [Edit page of DAC philosophy](https://develop.giveth.io/dacs/5eca119399915a4eca2c71a3/edit), I see read more link. It sends me to the [wiki](https://wiki.giveth.io/documentation/glossary/) full of unrelated content for new user. :(( I think we need good help content and someone should check our all **help link**  and **read more** on all pages to be sure that they give new user useful and correct information.

**Comment by GriffGreen** [comment]
We need to remove this link.... @horus2021 can you add a Screenshot so its clear?
