### ISSUE TITLE
Weird Delegation Output... I assume the simulation script will clean this up...

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1798]
Why is it showing 900 worth of donations when the delegation at first?

<img width="960" alt="Screen Shot 2021-02-15 at 10 35 14 AM" src="https://user-images.githubusercontent.com/14945613/107966266-e363ee80-6fab-11eb-930c-8a510e0fb0f5.png">

And then a few minutes later this is what I see.

<img width="385" alt="Screen Shot 2021-02-15 at 10 41 48 AM" src="https://user-images.githubusercontent.com/14945613/107966905-c54abe00-6fac-11eb-9280-395e61ccef0a.png">

Thats all fucked up. :-D

But this now adds up to 450...
<img width="880" alt="Screen Shot 2021-02-15 at 10 41 20 AM" src="https://user-images.githubusercontent.com/14945613/107966915-c7148180-6fac-11eb-89ec-8092644844e7.png">

But why are the first 2 pledges broken up? I guess there was a refund or something?

**Comment by GriffGreen** [comment]
For this Milestone: https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6/milestones/60240e887922530e8cd058e5

**Comment by GriffGreen** [comment]
Processing 1 event multiple times

**Comment by GriffGreen** [comment]
Each picture is an issue...

**Comment by GriffGreen** [comment]
This probably got stuck processing an event multiple times...

**Comment by GriffGreen** [comment]
Simulation script fixed the issues connected to the last 2 issues

**Comment by mohammadranjbarz** [comment]
@aminlatifi How about closing this issue?
