### ISSUE TITLE
Glitch in Dapp

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1799]
I see first page of develop.giveth.io. but when I want to see DAC pages I see this on Feb 15 19:19. I guess it is related to metamsk glith. I see this error 

in Chrome with metamask 
but not in 
Firefox without metamask.
Chrome after metmask lock

![image](https://user-images.githubusercontent.com/65175075/107967486-67c16c00-6fc2-11eb-94f7-c0cc4f188b4b.png)

**Comment by aminlatifi** [comment]
Would be fixed by this
https://github.com/Giveth/giveth-dapp/commit/17bc007a6e29a34b0832364bbd2ed6bb67723d1c

**Comment by horus2021** [comment]
Thanks @aminlatifi
