### ISSUE TITLE
Weird 6 emails sent to me over a couple hours about 1 donation

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1801]
<img width="1381" alt="Screen Shot 2021-02-16 at 3 08 52 PM" src="https://user-images.githubusercontent.com/14945613/108116007-41bbca80-709b-11eb-8e19-c104c150782b.png">

There was 1 donation ^^^^

But it sent me 6 emails over the course of 2 hours, every one was the same.....

<img width="1069" alt="Screen Shot 2021-02-16 at 3 07 48 PM" src="https://user-images.githubusercontent.com/14945613/108116009-42ecf780-709b-11eb-8b91-c2480a039a11.png">

**Comment by aminlatifi** [comment]
@GriffGreen It's related to #1798 
We are processing one event multiple times

**Comment by aminlatifi** [comment]
@mohammadranjbarz Reprocessing the event doesn't just create duplicate conversation and donation (we have stopped it), it also cause sending multiple email!

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Reprocessing the event doesn't just create duplicate conversation and donation (we have stopped it), it also cause sending multiple email!

@aminlatifi 
You are right, sending multiple emails are issue here also
