### ISSUE TITLE
When delegating from the Commons Stack Association I keep getting this weird notification... but it's not true!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1803]
<img width="543" alt="Screen Shot 2021-02-16 at 8 13 52 PM" src="https://user-images.githubusercontent.com/14945613/108142336-df2bf400-70c5-11eb-86c0-5f7c645db098.png">

**Comment by aminlatifi** [comment]
The command is generally true, but not applicable for this milestone because it's capped and doesn't need to donate from more than 10 sources.

**Comment by GriffGreen** [comment]
the logic is complicated... but it should be aware that I am not donating more than the first 10 delegations amounts...

**Comment by aminlatifi** [comment]
@RamRamez On develop I see this while is incorrect
![image](https://user-images.githubusercontent.com/5684607/113487795-4b748280-94cf-11eb-8e07-df4d501c65f1.png)

**Comment by aminlatifi** [comment]
I will test it

**Comment by MoeNick** [comment]
@aminlatifi I couldn't reproduce it :(
