### ISSUE TITLE
Fix the Anonomous donors in the Commons Stack Association

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1805]
I think we fixed their profiles... but it still says anon in the leaderboard

https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6 

![Screen Shot 2021-02-18 at 8.06.47 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/10acd6da-d32b-42bd-946b-efafb9ef47be)

**Comment by aminlatifi** [comment]
@mohammadranjbarz please check all users have donated to this campaign

**Comment by mohammadranjbarz** [comment]
@aminlatifi @GriffGreen 

There were two or three users that was missing in adding names like 
https://beta.giveth.io/profile/0xF8D1d34956cEa24718cf8687588D6FeDbc6d9AA6
and there are added now,
but most of users in this leaderboard don't have any event s with name ( I actually checked their events in rinkbey as well but they dont have any name)

For example check this flow for one users: 
https://beta.giveth.io/profile/0x2Ce202Ad36aDb3B7515D2E6ec1395F55298DC230
https://feathers.beta.giveth.io/events/6008735196d5a337711164af
https://rinkeby.etherscan.io/tx/0x59a9fdf1cad05b7a840e11173472012cdb8364b50645196195d4a0c7163eee4f

@aminlatifi 
Do you think I did some checking wrong or I missed something?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I wrote a script to do this but after running that I saw the DV is good, it means that the users that don't have name, they didn't have name from begining

https://github.com/Giveth/giveth-1-simulation/blob/develop/src/scripts/updateUserInfoByEvents.ts
