### ISSUE TITLE
Fair Data Society DAC, Campaigns hidden?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1812]
Please unhide the FDS DAC and related Campaigns, Milestones..

**Comment by aminlatifi** [comment]
They are hidden at home page since they are not updated for 6 month, any way all projects (DACs, Campaigns and Milestones) are available on their dedicated routes ('/dacs', '/campaigns', '/milestones'). Is it enough @Danibelle , other wise we should implement pining project feature.

**Comment by GriffGreen** [comment]
I am going to donate to the DAC to bring it to the forefront of the DApp

**Comment by Danibelle** [comment]
Ok.. I will let them know this change. 

Their transparent history here on Giveth helps them with further donations and grants.

Will they have to donate to each Campaign regularly to keep it showing? Having to provide many direct links would be .. less awesome.
