### ISSUE TITLE
Horus cannot delegate from Philosophy Updated DAC to Test Milestone title change / 2 Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1813]
Funding of [Philosophy Updated](https://develop.giveth.io/dacs/5eca119399915a4eca2c71a3) DAC is 0.0000002 ETH. 

![image](https://user-images.githubusercontent.com/65175075/108723219-410eb280-7539-11eb-87a4-3ad5ab134c6f.png)

When Horus is going to donate to [Test Milestone title change / 2](https://develop.giveth.io/campaigns/600f54972e350e08a9122a59/milestones/602fd9d4a0620763dc25a498) he got this message
![image](https://user-images.githubusercontent.com/65175075/108723498-921ea680-7539-11eb-964f-061324b591b5.png)

**Comment by aminlatifi** [comment]
@horus2021 DAC ETH balance is zero
![image](https://user-images.githubusercontent.com/5684607/108731998-63f19480-7542-11eb-8dce-ef5536f5d7be.png)
