### ISSUE TITLE
No Connection between DAC and Campaign After Delegation to His Child Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1814]
Horus as DAC Manager of [Philosophy updated](https://develop.giveth.io/dacs/5eca119399915a4eca2c71a3) delegates money of DAC to [Test Milestone title change / 2
](https://develop.giveth.io/campaigns/600f54972e350e08a9122a59/milestones/602fd9d4a0620763dc25a498) 
![image](https://user-images.githubusercontent.com/65175075/108729600-f3497880-753f-11eb-80bb-a5ea34b54488.png)
I expect to see Test Milestone title change /2's campaign - [Account 2 Campaign!](https://develop.giveth.io/campaigns/600f54972e350e08a9122a59) - in campaign list of [Philosophy updated](https://develop.giveth.io/dacs/5eca119399915a4eca2c71a3) but I cannot see.
![image](https://user-images.githubusercontent.com/65175075/108729935-48858a00-7540-11eb-8c9a-2aaf89d052a8.png)

**Comment by GriffGreen** [comment]
Great find!

**Comment by aminlatifi** [comment]
@horus2021 It's implemented, please test it

**Comment by MoeNick** [comment]
I will take it.

**Comment by MoeNick** [comment]
Tested on develop, passed
