### ISSUE TITLE
Accessing protected URLs redirects user back to page outside of Giveth

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#182]
If you directly access protected link while already being on the page, it will just redirect you back.

**Replicate:**
- Go to website like swarm.city
- Paste in the browser prodected dapp URL e.g. https://alpha.giveth.io/delegations
- Enjoy the loop

**Correct Behaviour:**
If the history.back points outside of giveth platform, it should redirect to the base url instead.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8c8780c9e9e4c8da3543577aa8814b51de7bf90390fa64122a23abb232c73c67](https://etherscan.io/tx/0x8c8780c9e9e4c8da3543577aa8814b51de7bf90390fa64122a23abb232c73c67)

**Comment by RnbWd** [comment]
I have a fix for this issue

**Comment by rsercano** [comment]
It's merged but still seems open in open bounty.

**Comment by RnbWd** [comment]
hmm?

**Comment by vojtechsimetka** [comment]
@RnbWd can you try an make empty PR with link to the original one and mention "fix #182" in it? I'll merge and that should do the trick.

**Comment by vojtechsimetka** [comment]
@geleeroyale Can we pay this out somehow so that I can close?

**Comment by geleeroyale** [comment]
wow - hurray for github notifications - sorry - I just did not see this. @RnbWd - please follow these steps:

1 - register on openbounty.status.im to link your github account to a metamask account
2 - sumbit an empty PR with the following comment: fixes #[your issue number] (without the square brackets)
3 - Ping @geleeroyale on Riot, to accept the PR

I will then close this issue again
