### ISSUE TITLE
Revise UI of Funding Table

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1820]
I made a mistake #1813 . I take funding as balance ;(. I suggest to revise the UI to avoid these mistakes in the future. We need to highlight balance vs funding. Balance is more important than funding history. 
my suggestion 
1) move current balance value column
2) use bigger/bold font for balance in order to highlight it
3) Note typo on B
I am novice in UI. @markoprljic surely have better idea to highlight balance. See below for my suggestion

![UI revised balance and funding highlight  2222](https://user-images.githubusercontent.com/65175075/108807063-a786e580-75b8-11eb-8315-768c1fa2d7ac.png)

**Comment by markoprljic** [comment]
Can we use the same table style as for the donations/leaderboard but with the columns as you stated? @aminlatifi

**Comment by aminlatifi** [comment]
> Can we use the same table style as for the donations/leaderboard but with the columns as you stated? @aminlatifi

We can, is it nice to have the same style and colors on balance table? I prefer uniq style for this table because it contains more important numbers

**Comment by markoprljic** [comment]
I see the issue here being a position of the columns, no? Horus suggested to have Current balance and Current balance value next to each other. If that's the case then we could just switch that and keep the styling same? @horus2021

**Comment by horus2021** [comment]
@markoprljic keep current style, just move columns.

**Comment by markoprljic** [comment]
@aminlatifi There's not much for me to do in that case, it's just a matter of switching the columns as @horus2021 pointed out.
