### ISSUE TITLE
Works on Chrome but not brave for me similar past issue

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1821]
<img width="1281" alt="Screen Shot 2021-02-23 at 2 16 13 PM" src="https://user-images.githubusercontent.com/14945613/108895607-180f2000-7614-11eb-841a-86eed2df2ff8.png">

**Comment by aminlatifi** [comment]
Brave cannot establish wss connection, maybe upgrading feathers solve the issue

**Comment by aminlatifi** [comment]
Same #1725

**Comment by aminlatifi** [comment]
@mdehghani Is going to upgrade feathers dependency and other related one to version 4.x

**Comment by MoeNick** [comment]
@aminlatifi how can I test it?
