### ISSUE TITLE
Replace Milestone with Traces 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1832]
Lets move away from the Milestone terminology and move to calling them a "Project" and there are 4 types of projects: Milestones, Payments, Bounties and Expenses

**Comment by WhyldWanderer** [comment]
related issue: https://github.com/Giveth/giveth-planning/issues/127

**Comment by MoeNick** [comment]
- Comms Team make it more clear.  
- Backend, api and entities should changes
- Short update could be changing the names in Frontend.
- Variables in BE and FE

**Comment by aminlatifi** [comment]
Done
