### ISSUE TITLE
Put delete button for expense items

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1834]
![image](https://user-images.githubusercontent.com/5684607/109786284-40a1a600-7c22-11eb-9f5d-ec6b6fb1a656.png)

**Comment by aminlatifi** [comment]
@MohammadPCh Implement it as part of this PR https://github.com/Giveth/giveth-dapp/pull/1808

**Comment by MohammadPCh** [comment]
@aminlatifi  I implemented it. it's functionality is Ok. but i think our designer can recommend us a better UI.

**Comment by aminlatifi** [comment]
> @aminlatifi I implemented it. it's functionality is Ok. but i think our designer can recommend us a better UI.

Thanks @MohammadPCh, you are right. Nice design and I guess it's good enough for the first version
