### ISSUE TITLE
Not showing status updates when it's delegated from DAC

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1837]
https://beta.giveth.io/campaigns/5fbbce04188f980d941470eb/milestones/601abd93f9e6e877930e9694

![image](https://user-images.githubusercontent.com/9850545/109862373-9c494f00-7c75-11eb-8635-c6057562ca8f.png)

**Comment by aminlatifi** [comment]
It needs a fix in backend
