### ISSUE TITLE
'Create Community' or 'Start a Campaign' buttons should not be visible to non-whitelisted users.

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#184]
Users who are not part of the whitelist should not be able to get to the create DAC/Campaign pages. I propose that the buttons should be disabled/hidden or a pop-up with explanation should be shown.

Currently once non-whitelisted user click these buttons he/she gets stuck on loading page.
<img width="1127" alt="screen shot 2017-12-01 at 22 43 25" src="https://user-images.githubusercontent.com/7974813/33511453-1b21d724-d6e9-11e7-93d5-dd5050ebe947.png">

**Comment by satyavh** [comment]
Since when is this? I've been working on this, see
e9f78ea - Make isWhitelist middleware a bit more useful, add notifications to create buttons
in develop branch.

**Comment by vsimetka** [comment]
I completely agree. I think that for the time being we can just merge to master whenever something is fixed (not ideal but we are not live and we can always revert). But after we deploy I want to have proper gitflow setup with release branch. https://blog.axosoft.com/gitflow/

![gitflow-diagram](https://user-images.githubusercontent.com/7974813/33531393-7bd1e31c-d85a-11e7-86f3-de5a7ce18900.png)

For this one, I think you did not push that fix when I was writing the issue :)
