### ISSUE TITLE
Button Alignment at Campaign Page in Mobile View is not Perfect

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1845]
For example see [Promote Plato Philosophy](https://develop.giveth.io/campaign/promote-plato-philosophy) 

![image.png](https://images.zenhubusercontent.com/5eb95a92a4d6c08826d1d99c/ab1458aa-85eb-4bfc-9057-798cdaea1e1b)

**Comment by GriffGreen** [comment]
Try to stack the buttons if you can and add some padding

**Comment by MohammadPCh** [comment]
I'm working on it and this will fix in our new design.(#1730)
