### ISSUE TITLE
DAI balance not showing correctly when delegating funds

### ISSUE THREAD

**Issue by JulietEA** [Giveth/giveth-dapp#1848]
DAI balance not showing correctly when delegating funds:

<img width="561" alt="Screen Shot 2021-03-09 at 12 10 58 AM" src="https://user-images.githubusercontent.com/54636748/110426622-0c881400-806c-11eb-9de6-db7f50cd05e6.png">

**Comment by aminlatifi** [comment]
@JulietEA What's your address (public key)?

**Comment by GriffGreen** [comment]
The modal request should be smarter ... :-D
