### ISSUE TITLE
Adding Video to an MIlestone Update Failed

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1852]
I'm adding a video to a Milestone..  a little "Meme Jam" by Lauren Luz on the Costa Rica Crew Milestone to be specific :)

![image](https://user-images.githubusercontent.com/39466970/110564963-8cf95400-8102-11eb-827d-a44fc14c8e83.png)

I can click on any of the radio buttons then click CLOSE and the button just stays in the 'pressed' state. Until I click a different radio button then it switches back to normal. But I have to hit the Escape button to get out then I can continue editing.

**Comment by GriffGreen** [comment]
![Screen Shot 2021-03-29 at 10 26 18 AM](https://user-images.githubusercontent.com/14945613/112860204-e75b5400-90b3-11eb-87a1-c964f3b4a313.png)

**Comment by aminlatifi** [comment]
@MohammadPCh Attaching video using youtube link didn't work

**Comment by aminlatifi** [comment]
Youtube is supported as separate option in menu.
Thanks @MohammadPCh
