### ISSUE TITLE
Button Text of  Delete Milestone? Dialog Should be Revised

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1858]
When Milestone Proposer wants to delete an Proposed Milestone he sees the below. I think **Yes, Delete** makes more sense.

![cancel 2 delete](https://user-images.githubusercontent.com/65175075/110624665-c3db7280-81b3-11eb-8200-091146822bf5.png)

**Comment by KANE-99** [comment]
I would like to do it.
