### ISSUE TITLE
Wrong List of Donations for a Proposed Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1859]
Sunny created a  [Purchase The Symposium book](https://develop.giveth.io/milestone/purchase-the-symposium-book). The milestone was in proposed state. Sunny went to milestone page and  saw donation list had 50 entry!!!! The milestone  has been in proposed state with no donations. So list should be empty. It is too strange.

See below video as proof.

https://user-images.githubusercontent.com/65175075/110635928-e6c05380-81c0-11eb-869a-2741d5722c69.mp4

**Comment by aminlatifi** [comment]
It was reported and closed now
