### ISSUE TITLE
After update a Milestone (without any changes), Duplicate Milestone Error Message

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1860]
Sunny went to edit page of a proposed Milestone Purchase Symposium. He did not change anything. He clicked button and he got a error message **a milestone with dsfkltitle already exits...**!!!!

https://user-images.githubusercontent.com/65175075/110647098-c8605500-81cc-11eb-8ebe-c6954220a835.mp4

**Comment by horus2021** [comment]
Note: Wrok-around is modifying milestone title before!!!!

**Comment by mohammadranjbarz** [comment]
PS: This happens when user doesn't change the `title`, if title has been and it's not repetitive it wont happen
