### ISSUE TITLE
Showing donations table incorrectly when going to mlestones by slug link

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1861]
For example if you go to milestone page with below link you should see a lot of unrelated donations:

https://develop.giveth.io/milestone/simulation-test-4

But if you go with old links you see table correctly

https://develop.giveth.io/campaigns/5fc7e32f048ee557f352f670/milestones/600ebfd19ca6ac3d2a1a3cfa

**Comment by horus2021** [comment]
I encountered the same issue. I created new issues. I hope it helps you. 
#1869 
#1859

**Comment by aminlatifi** [comment]
Thanks @horus2021
