### ISSUE TITLE
Validating picture size and format, in uploading (Community/campaign/traces/editors-comments)

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1862]
Upload by feather. check all picture and video. 

I am uploading an incorrect image format (JFIF( into milestone picture. I got error message from IPFS. I think it  should be checked by Frontend in the first place.

https://user-images.githubusercontent.com/65175075/110655822-a36fe000-81d4-11eb-8cf5-4ac3ac273932.mp4

**Comment by MoeNick** [comment]
Please check it out, it is important more because if the security issues.
