### ISSUE TITLE
Pagination doesnt work in /my-milestones

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1863]
After clicking on `2` or `next` icons nothing happens

![Screen Shot 1399-12-20 at 20.11.55.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/c30d6358-daad-4325-a8b5-8076a119e6b3)

**Comment by aminlatifi** [comment]
@mohammadranjbarz Thanks
