### ISSUE TITLE
Donation List in Milestone Page is Totally Wrong.

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1869]
Orisis has donated 0.001 ETH to [Purchase The Symposium book1](https://develop.giveth.io/milestone/purchase-the-symposium-book1) and saw his donation in status update but not in Donation List! 
Related to #1859 
![image](https://user-images.githubusercontent.com/65175075/110742693-10728c80-824c-11eb-87e2-e2078267d9f2.png)

**Comment by horus2021** [comment]
After first donation by orisis Donation List is incorrect. After second donation by Nut it is corrected. I am just trying to write down the whole process to help @aminlatifi  find the root cause. I guess this issue is difficult to reproduce.  

![image](https://user-images.githubusercontent.com/65175075/110754109-ab736280-825c-11eb-870d-637c2d23160d.png)

**Comment by aminlatifi** [comment]
We had issue in showing milestone donations, it should be fixed now
