### ISSUE TITLE
Change Recipient not Displayed in Status Update of Milestone Page

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1871]
Sunny as recipient of [Purchase The Symposium book1](https://develop.giveth.io/milestone/purchase-the-symposium-book1) milestone changed recipient to Hathor. This happened, but this is not displayed in Status Update.

![image](https://user-images.githubusercontent.com/65175075/110750285-7fa1ae00-8257-11eb-8293-df6c6c277216.png)

**Comment by mohammadranjbarz** [comment]
![Screen Shot 1400-02-06 at 16.41.35.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/236eb142-a08c-43da-94b5-7a3fb7dd908c)

**Comment by mohammadranjbarz** [comment]
[Uploading... Screen Shot 1400-02-06 at 16.46.17.png]

**Comment by MoeNick** [comment]
tested.
