### ISSUE TITLE
Archive not Working for Milestone Owner

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1874]
Sunny (milestone owner of [Purchase The Symposium book1](https://develop.giveth.io/milestone/purchase-the-symposium-book1)) is going to archive his milestone and encounter the following error message. 

Side Note: Horus (owner of parent campaign) can archive.

https://user-images.githubusercontent.com/65175075/110778914-331a9a80-8278-11eb-86a7-6157cd6f8c30.mp4

**Comment by aminlatifi** [comment]
@horus2021 Archiving a milestone is just a DB (not network) change, it's strange. Before fixing this issue we should document archiving user story :)

**Comment by divine-comedian** [comment]
testing this out again, brave browser clean cache and cookies on `develop` 
no problems archiving a Trace while logged in.

![image](https://user-images.githubusercontent.com/67759413/122054192-73c50b00-cdb5-11eb-9edc-b8ad318600cf.png)
![image](https://user-images.githubusercontent.com/67759413/122054235-7aec1900-cdb5-11eb-9bc9-fdb022ab270d.png)
![image](https://user-images.githubusercontent.com/67759413/122054255-80496380-cdb5-11eb-899a-d90a861b98dd.png)
