### ISSUE TITLE
Archive Event Should Be Logged in Status Update

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1875]
Horus (Campaign Owner) archived [Purchase The Symposium book1](https://develop.giveth.io/milestone/purchase-the-symposium-book1) milestone. The event is not logged in status updated.

![Archived purchase symposium milestone for PoV sunny milestone owner](https://user-images.githubusercontent.com/65175075/110783225-67dd2080-827d-11eb-91d2-01eeb545f013.JPG)

**Comment by aminlatifi** [comment]
As #1874 we need to define and create user story

**Comment by MoeNick** [comment]
I archived this milestone as milestone creator:
https://develop.giveth.io/milestone/test-email-for-subscriber

wo refresh, it won't showed up
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/5318bd3b-236f-4e97-87bc-655e837fe829)

with refresh, the status wont show up in status update :(

**Comment by MoeNick** [comment]
I did it with this milestone:
https://develop.giveth.io/milestone/test-milestone-9

 and it has been updated. :)

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/08b6a102-b09c-4db8-9920-49c78d0ab6ca)

**Comment by MoeNick** [comment]
Test also failed on this milestone:
https://develop.giveth.io/milestone/test-delegation
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/24d3e180-e7d2-4803-8f70-cddb0edb51ce)

**Comment by mohammadranjbarz** [comment]
@MoeNick 
This issue is just about creating archived milestone, so refreshing status updates after this is not related to this issue, I think you can move this issue to done

**Comment by MoeNick** [comment]
@mohammadranjbarz problem existed on last test I made. even with refresh.

**Comment by mohammadranjbarz** [comment]
@MoeNick 
If you test and approve this on UAT we could close it

**Comment by MoeNick** [comment]
@mohammadranjbarz im on it

**Comment by MoeNick** [comment]
Seems ok to me.
