### ISSUE TITLE
Video Attaching not working in Reject Proposed Milestone Menu

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1878]
See below video

https://user-images.githubusercontent.com/65175075/110789370-09b43b80-8285-11eb-8fc7-8e89d0dd5439.mp4

**Comment by aminlatifi** [comment]
It's same as #1852

**Comment by MoeNick** [comment]
We have to replace our old quill editor component with new one.

**Comment by WhyldWanderer** [comment]
I was able to successfully attach a video in the reject proposed milestone menu!

![image](https://user-images.githubusercontent.com/74267818/114067801-7443a180-985a-11eb-82e7-26509e6a789c.png)
