### ISSUE TITLE
Video Attaching not working in Accept Proposed Milestone Menu

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1879]
Same as #1878

**Comment by MoeNick** [comment]
We have to replace our old quill editor component with new one.

**Comment by WhyldWanderer** [comment]
I was successful in attaching a video in the accept proposed milestone menu! yay

![image](https://user-images.githubusercontent.com/74267818/114067481-1747eb80-985a-11eb-9694-c8e44892f062.png)
