### ISSUE TITLE
Video Attaching not working in Cancel Milestone Menu

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1880]
Same as #1879 #1878

**Comment by MoeNick** [comment]
We have to replace our old quill editor component with new one.

**Comment by WhyldWanderer** [comment]
I was successful in attaching a video in the cancel milestone menu!!

However, when I try to attach a video in the edit milestone menu, I get this pop up to select the video source.
![image](https://user-images.githubusercontent.com/74267818/114065107-8a039780-9857-11eb-8c8d-d6495113ee2c.png)
however when I choose any option nothing happens... and the button just says close but i dont want to close.
If I press the close button nothing happens and I have to refresh the page to get the pop up to go away.

**Comment by MoeNick** [comment]
It's not working @aminlatifi ... shall we send it back to in progress?

**Comment by mohammadranjbarz** [comment]
https://develop.giveth.io/milestone/milestone-with-reviewer2

Canceled and video works

**Comment by aminlatifi** [comment]
@MoeNick I changed it to Cancel Milestone, for edit milestone we should create another issue

**Comment by MoeNick** [comment]
According to our DOD, the value to customer just delivered by editing, pls change the estimate and move it back to in-progress, you may create another issue and put the estimates there and relate it to another. 
Let's not broke the value of a story to multiple release. 
@aminlatifi
