### ISSUE TITLE
Cancelling Milestone Should be Logged in Status Update of Milestone Page

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1881]
Sunny (Milestone Owner) canceled [Crito 2nd chance12](https://develop.giveth.io/milestone/crito-2nd-chance12) but this event is not displayed in Status Update box.

![image](https://user-images.githubusercontent.com/65175075/110793562-01aaca80-828a-11eb-90cc-c806f49e4515.png)

**Comment by MoeNick** [comment]
#2013 Done
