### ISSUE TITLE
Misspelling InProgress instead of In Progress in Details Box of Milestone Page

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1882]
![InProgress --- In Progress](https://user-images.githubusercontent.com/65175075/110794346-e7252100-828a-11eb-9fcf-9ad484546fc8.JPG)

**Comment by 96RadhikaJadhav** [comment]
@horus2021 Can I work on the issue?

**Comment by aminlatifi** [comment]
> @horus2021 Can I work on the issue?

Hi @96RadhikaJadhav 

Thanks for your intention to contribute to our Dapp 🙏  , you can work on this issue 😃

**Comment by 96RadhikaJadhav** [comment]
@aminlatifi @horus2021 I have created PR #1906 . Could you please check and let me know if any changes required.

**Comment by aminlatifi** [comment]
Thanks @96RadhikaJadhav, you are very kind since decided to contribute to our DApp
