### ISSUE TITLE
Don't allow creating milestone with capped amount less than limt

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1885]

**Comment by laurenluz** [comment]
Suggestion to add text below the entry field for "Maximum amount in ${token.symbol}" that says _"Must be greater than ${value} ${token.symbol}"_ - values are fetched from the backend

This new text should be the same smaller and un-bolded font as "1 ETH = 1782.42 DAI"

Also, please check that ${entry.field.value} > ${value} (fetched from backend), and if it is not, the "Create Milestone" button should be light green and unclickable.

@mohammadranjbarz can you help to implement this? Let me know if it is unclear



![image](https://user-images.githubusercontent.com/75490971/111370735-35a53780-865e-11eb-8701-757ff6fcc4e6.png)

**Comment by mohammadranjbarz** [comment]
> Suggestion to add text below the entry field for "Maximum amount in ${token.symbol}" that says _"Must be greater than ${value} ${token.symbol}"_ - values are fetched from the backend
> 
> This new text should be the same smaller and un-bolded font as "1 ETH = 1782.42 DAI"
> 
> Also, please check that ${entry.field.value} > ${value} (fetched from backend), and if it is not, the "Create Milestone" button should be light green and unclickable.
> 
> @mohammadranjbarz can you help to implement this? Let me know if it is unclear
> 
> ![image](https://user-images.githubusercontent.com/75490971/111370735-35a53780-865e-11eb-8701-757ff6fcc4e6.png)

Thanks Lauren

**Comment by GriffGreen** [comment]
@mohammadranjbarz this should be added to the new milestone creation page

**Comment by MoeNick** [comment]
@MoeNick has to check it on develop.

**Comment by aminlatifi** [comment]
@MoeNick It should be up in develop in few minutes

**Comment by MoeNick** [comment]
ok

**Comment by MoeNick** [comment]
Tests passed.
