### ISSUE TITLE
Spelling Error: Withdrawal Popup

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#189]
On the popup that confirms that your withdrawl is processing, the word "you're" should be "your."

<img width="463" alt="screen shot 2017-12-04 at 3 28 31 pm" src="https://user-images.githubusercontent.com/27023908/33583724-85055d68-d910-11e7-8d10-ff2a262cff2d.png">

**Comment by bowensanders** [comment]
_Note: I can go in, find and fix these small spelling and gramatical errors if allowed, Griff suggested I ask here for permission. _

**Comment by vsimetka** [comment]
You can just clone the repo and make pull request. I am not handing out write access to the main repo yet but of course if you keep contributing you can get it :).

**Comment by bowensanders** [comment]
Copy that. PR #191 incoming.

During edit, found two more spelling errors in this file. as noted in PR:

**Comment by vojtechsimetka** [comment]
Fixed in 5211bb7787b5959ae446c426ac372629e68c4bda
