### ISSUE TITLE
Page scroll not functioning 

### ISSUE THREAD

**Issue by JulietEA** [Giveth/giveth-dapp#1891]
On the "My Milestones" page, the page numbers are not working at all. When I click either the forward/backward buttons or the numbers, nothing happens.

<img width="637" alt="Screen Shot 2021-03-12 at 10 31 00 AM" src="https://user-images.githubusercontent.com/54636748/110969517-631c7900-831e-11eb-8c1f-4ca0ca1a9f5d.png">

**Comment by aminlatifi** [comment]
@JulietEA Thanks for reporting, it's fixed now
