### ISSUE TITLE
Misleading Text Below Donations for a Paid Milestone without Any Donation

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1893]
Meno is archived milestone so it is paid and cannot accept any money. In the bottom page below donations you see. 

Donations
No donations have been made yet. Be the first to donate now!

This is completely misleading for novice user like me.

Please revise  it to something like this. 

**No donation has been made.**

![image](https://user-images.githubusercontent.com/65175075/111036671-9dc50500-8435-11eb-9b33-3ac7bf936a7c.png)

**Comment by horus2021** [comment]
related to #1896

It is a good idea if a milestone cannot accept money (e.g. Proposed, Paid, Cancelled..) we do not invite the user to donate.

**Comment by aminlatifi** [comment]
@horus2021 You are right

**Comment by aminlatifi** [comment]
@RamRamez Only `InProgress` milestones can accept donation
