### ISSUE TITLE
Cancel Button for a Cancelled Milestone!!!

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1895]
Below my milestone page of Horus , tab cancelled.  **MILESTONE This is to be cancelled** has been cancelled so button cancel is totally meaningless. 

![image](https://user-images.githubusercontent.com/65175075/111037399-02359380-8439-11eb-9f45-6c511dd632b9.png)

**Comment by divine-comedian** [comment]
No more cancel buttons it seems! 
testing brave browser on `develop`
as Trace Manager

![image](https://user-images.githubusercontent.com/67759413/122056093-45482f80-cdb7-11eb-9d00-793955bea9bb.png)
