### ISSUE TITLE
Change my role on GitHub to Owner please

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1897]
If not, someone who is will have to finish the process of getting Giveth listed on stakes.social

https://stakes.social/create

![image](https://user-images.githubusercontent.com/39466970/111055433-a6fca480-842a-11eb-9347-353fd2d430a5.png)

**Comment by Danibelle** [comment]
@geleeroyale or @aminlatifi maybe?

**Comment by aminlatifi** [comment]
@Danibelle I assign Maintain role to you on `giveth-dapp` repository, is it enought?

**Comment by aminlatifi** [comment]
> @Danibelle I assign Maintain role to you on `giveth-dapp` repository, is it enough?

Also made you owner of Giveth organization
