### ISSUE TITLE
Spelling Error: Donation Popup

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#190]
On the donation confimation popup, the second instance of "You're" should be "Your."
  
<img width="451" alt="screen shot 2017-12-04 at 3 36 38 pm" src="https://user-images.githubusercontent.com/27023908/33583808-0fa54726-d911-11e7-826b-70f0f07b7cd2.png">

**Comment by bowensanders** [comment]
_Note: I can go in, find and fix these small spelling and gramatical errors if allowed, Griff suggested I ask here for permission. _

**Comment by bowensanders** [comment]
All spelling/grammar errors in this file:

Fix in line 63: "Great to see that you want to donate!! However" to "It's great to see that you want to donate, however, 
Fix in line 118: "You're" to "Your"
Fix in line 142: "You're" to "Your"
Fix in line 254: "Pledge that you also need to pay for the transaction." to "Please remember that you must also pay the transaction fee."

**Comment by bowensanders** [comment]
Changed line 63 to be unicode compliant.

**Comment by vojtechsimetka** [comment]
Fixed in 0995851787cdb765d8c50b94921002387a997780
