### ISSUE TITLE
Why dont show edit button for reviewer 

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1903]
https://develop.giveth.io/milestone/email-when-reviewer-edits-milestone

![Screen Shot 1399-12-24 at 17.37.41.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/f51f4454-49b5-484f-8811-29aca364790d)
![Screen Shot 1399-12-24 at 17.38.03.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/26ec9084-5dad-4664-aff9-2ce4c55f353d)

**Comment by GriffGreen** [comment]
Reviewers can't edit milestones.
