### ISSUE TITLE
Hathor Cannot Propose a Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1907]
Hathor is going to propose a milestone to Horus, but he cannot. A yellow box with following content will pops up 

Something went wrong with the Milestone creation. Is your wallet unlocked? undefinedtx/undefined => { "stringValue": "\"{}\"", "kind": "ObjectId", "value": {}, "path": "_id", "reason": {}, "__error_callsites": [ {}, {}, {}, {}, {}, {} ] }

See below

https://user-images.githubusercontent.com/65175075/111078792-860c8000-850c-11eb-86bf-437602d14f93.mp4

**Comment by aminlatifi** [comment]
It's fixed
