### ISSUE TITLE
Can't start a campaign

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#1914]
Issue type: **Error**
Something went wrong.

**Name:**
not whitelisted

**LineNumber:**
undefined

**FileName:**
undefined
![creae campaine](https://user-images.githubusercontent.com/80677512/111154454-7cd0f100-85a8-11eb-85b8-df1c7a59c6c3.PNG)
![creae campaine](https://user-images.githubusercontent.com/80677512/111154517-8ce8d080-85a8-11eb-804a-c6e09d289fb3.PNG)

<details><summary>Stack</summary>

"Error: not whitelisted\n    at https://d33wubrfki0l68.cloudfront.net/js/e93869ef9baa22b3dc270852554289358db55c7a/static/js/main.d21848ef.js:1:4137981"
</details>

**Comment by aminlatifi** [comment]
@mohammadranjbarz Disabling whitelist doesn't work as expected. I will enable it

**Comment by aminlatifi** [comment]
@mohammadranjbarz Please test it yourself by disabling whitelist on develop

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Please test it yourself by disabling whitelist on develop

@aminlatifi  Sure I'll test it

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
It has problem, I made a new PR and I tested in on netlify, it was OK

#1923

**Comment by mohammadranjbarz** [comment]
@aminlatifi  It has problem, So I made a new PR , and it's ok, you can check on netlify before merge
#923
