### ISSUE TITLE
Mail user payment info when money is finally send to their wallet

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1916]

**Comment by mohammadranjbarz** [comment]
@horus2021  @WhyldWanderer @laurenluz 

Could you give me the email texts for this issue?

**Comment by laurenluz** [comment]
I can do this, but what is the "payment info"? is it the amount of funds (and currency) sent?

This email is sent after the funds are released from the bridge?

**Comment by laurenluz** [comment]
If the answer is "yes" - here's some text 😉 let me know if this needs revision

Subject: ‘Giveth - Your funds have been sent!’
secretIntro: ‘The funds from your Milestone ${MilestoneName} have been sent to your wallet.
Title: ‘Time to Celebrate!’
Text: The funds from your Milestone ${MilestoneName} of the amount ${amount} ${token.symbol} have been sent to your wallet. It’s time to take action to build a brighter future!
Cta: See your Milestones
Button link: Milestone name (link to milestone page)

**Comment by mohammadranjbarz** [comment]
> I can do this, but what is the "payment info"? is it the amount of funds (and currency) sent?
> 
> This email is sent after the funds are released from the bridge?

@laurenluz 
The Answer is yes for all of your questions :D

**Comment by mohammadranjbarz** [comment]
> If the answer is "yes" - here's some text 😉 let me know if this needs revision
> 
> Subject: ‘Giveth - Your funds have been sent!’
> secretIntro: ‘The funds from your Milestone ${MilestoneName} have been sent to your wallet.
> Title: ‘Time to Celebrate!’
> Text: The funds from your Milestone ${MilestoneName} of the amount ${amount} ${token.symbol} have been sent to your wallet. It’s time to take action to build a brighter future!
> Cta: See your Milestones
> Button link: Milestone name (link to milestone page)

Thanks a lot
Should I send it to just to milestone recipient or it's needed to send to milestone owner as well?

**Comment by MoeNick** [comment]
For testing, @aminlatifi @mohammadranjbarz do some db manipulation for testing.

**Comment by aminlatifi** [comment]
I am testing
