### ISSUE TITLE
Represent payment info in milestone conversation

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1918]

**Comment by aminlatifi** [comment]
Same on conversation
https://github.com/giveth/giveth-dapp/issues/1917#issuecomment-799533288

**Comment by mohammadranjbarz** [comment]
@laurenluz 
Could you give me a good text for putting in milestone status updates for this case?

**Comment by laurenluz** [comment]
@mohammadranjbarz happy to help but I'm not exactly what we're talking? can you send me a screen shot of the part that needs text? or give me a bit of context?

**Comment by mohammadranjbarz** [comment]
@laurenluz  After user collects and money real

![Screen Shot 1399-12-29 at 10.08.48.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/e8c1135b-0f68-4540-b381-34716e97e9bf)ly goes to recipient's wallet we should an item in milestone status updates

Now I added a text  `{amount} {token} went to recipient's wallet`
If it's not good enough I would appreciate if you give me some other texts.

**Comment by laurenluz** [comment]
That's good! but perhaps this is a bit more specific:

{amount} {token} has been sent to recipient's wallet

**Comment by mohammadranjbarz** [comment]
> That's good! but perhaps this is a bit more specific:
> 
> {amount} {token} has been sent to recipient's wallet

Thanks a lot

**Comment by aminlatifi** [comment]
Tested, works
