### ISSUE TITLE
Weird! I see milestones repeating in the Commons Stack Community campaign... and even see some that are part of other Campaigns!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1924]
Scroll thru the milestones here: https://beta.giveth.io/campaign/commons-stack-community-iteration-0
Notice that a lot of milestones repeat

And i can see lots of Milestones from other campaigns!
<img width="993" alt="Screen Shot 2021-03-16 at 6 29 01 AM" src="https://user-images.githubusercontent.com/14945613/111302126-4bf9c600-8653-11eb-8929-fd344a2b625b.png">

**Comment by aminlatifi** [comment]
Maybe after slug

**Comment by aminlatifi** [comment]
fixed
