### ISSUE TITLE
Add banner on front page explaining transaction limit

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#1930]
Spoke with @Danibelle about this. Considering issues #1885 #1886 #1887 we think it makes sense to give the user a heads-up about the limitation on transaction values... so they're not just finding out last-minute when they try to make, disburse, collect from, or mark complete a milestone.

Suggestion to add a banner to the front page that says:
"Giveth pays the gas fees so you don't have to! Because of this we are temporarily limiting transactions to those greater than ${value} ${token.symbol}"

@markoprljic - what do you think? can we add something like this?

**Comment by markoprljic** [comment]
UX approved. 😊

**Comment by laurenluz** [comment]
ballin'. @aminlatifi - can you help make this happen?

**Comment by aminlatifi** [comment]
@laurenluz It's not clear to me `add a banner to the front page`

**Comment by laurenluz** [comment]
hey @aminlatifi something simple like this "free delivery" banner at the top of this clothing page... any maybe with a little x in the corner so the user can hide the banner after reading.

@Danibelle - what do you think? is this what you had in mind?
@markoprljic is there a specific colour that you think we could use? maybe a simple design would be helpful.

![image](https://user-images.githubusercontent.com/75490971/111919172-35d27800-8a4e-11eb-9632-e0e284de627b.png)

**Comment by Danibelle** [comment]
Exactemente!

**Comment by GriffGreen** [comment]
Anyone who comes to Giveth Trace, they should know that there is a big change here.

**Comment by markoprljic** [comment]
Here's the banner, let me know what you think. @Danibelle @laurenluz @aminlatifi @GriffGreen 

![Image 2021-03-22 at 6 40 50 pm](https://user-images.githubusercontent.com/5704285/112033917-334f4b80-8b3e-11eb-8a78-9e41f88f94ee.jpg)

**Comment by laurenluz** [comment]
I think it's awesome 😍

**Comment by Danibelle** [comment]
Danibelle Approved!!
(Can I get a banner for that? 🤔😉🤣)

**Comment by markoprljic** [comment]
It's here for devs to grab and implement. https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=2072%3A827

**Comment by MoeNick** [comment]
@RamRamez the text is ok.. we got value form backend and we just put USD as TokenSymbol.

**Comment by MoeNick** [comment]
@laurenluz @markoprljic It has to be shown on every-page? How many times and when?
I suggest it just showed up once after each login. and it wont showed up after the user push I got it button.

**Comment by RamRamez** [comment]
> @laurenluz @markoprljic It has to be shown on every-page? How many times and when?
> I suggest it just showed up once after each login. and it wont showed up after the user push I got it button.

It's currently showing on each page until user click "Got it". After that, It will never be shown to that user again. Please check it in pull request #1966 if it's working fine.

**Comment by MoeNick** [comment]
Due to technical problems we have, we decided to show the banner below the page, until we change the menu-bar code at the top. @laurenluz @markoprljic We know it's not the exact requirement, but do accept it will deploy on beta? 
![image](https://user-images.githubusercontent.com/80677512/113485476-edda3900-94c2-11eb-9472-7486b9d44f61.png)

**Comment by markoprljic** [comment]
When do we expect to resolve top bar technical problem?

**Comment by MoeNick** [comment]
We have to plan for the next sprint, I don't have any estimation right know.

**Comment by MoeNick** [comment]
> When do we expect to resolve top bar technical problem?

We can close this till the end of Sp. 6# April 19th.

**Comment by MoeNick** [comment]
![b65888d4-4c99-4ba1-a2d6-42f4a91a257f](https://user-images.githubusercontent.com/80677512/113570635-fb5e0300-9629-11eb-8753-266d879482eb.jpg)
Banner load at the middle when list is empty, not top, nor bottom,

**Comment by RamRamez** [comment]
> ![b65888d4-4c99-4ba1-a2d6-42f4a91a257f](https://user-images.githubusercontent.com/80677512/113570635-fb5e0300-9629-11eb-8753-266d879482eb.jpg)
> Banner load at the middle when list is empty, not top, nor bottom,

@MoeNick It's done.

**Comment by RamRamez** [comment]
The new main menu with Ant design is now completed in PR #1978 and tx limit banner is moved to the top the page.
