### ISSUE TITLE
Display of "People" on the campaigns page actually displays # of donations

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#194]
Rather than give the correct number of "people" associated with a project, it seems that the number displayed as "people" is the number of donations to the project:

<img width="335" alt="screen shot 2017-12-04 at 7 05 42 pm" src="https://user-images.githubusercontent.com/27023908/33588299-04c85cb0-d927-11e7-9e3e-4008beec861c.png">
<img width="884" alt="screen shot 2017-12-04 at 7 06 27 pm" src="https://user-images.githubusercontent.com/27023908/33588304-07a6c6a6-d927-11e7-88a7-550c1f47eb81.png">

and then a couple minutes later:
<img width="439" alt="screen shot 2017-12-04 at 7 11 33 pm" src="https://user-images.githubusercontent.com/27023908/33588308-0e450e0a-d927-11e7-9ede-96f5a4a2262d.png">
<img width="787" alt="screen shot 2017-12-04 at 7 11 46 pm" src="https://user-images.githubusercontent.com/27023908/33588309-0ff981ea-d927-11e7-9b05-31cc923673f3.png">

**Suggestion:** Either change "people" to "donations" or change the code to display the number of people properly. Also possible is doing both, since it's a great undocumented feature! :)

**Comment by bowensanders** [comment]
I also wonder if the Donations / People issue is happening here too, on the milestones page for me:
<img width="1151" alt="screen shot 2017-12-05 at 9 21 10 pm" src="https://user-images.githubusercontent.com/27023908/33645952-4bf4856a-da02-11e7-93b1-7d98fcc311b1.png">

In a message to Vojtech I mentioned that the numbers for donations were incrementing strangely, as you can see it says 011, 01, 0 - which leads me to believe that there is a variable acting like a string and not an integer, making N + 1 to be "01" and then N + 1 would then become "011"....

**Comment by vojtechsimetka** [comment]
I believe it is because we are adding two BigNumbets together. The BigNumbers are passed as strings to avoid precision loss.

**Comment by bowensanders** [comment]
I think that the top and the bottom are seperate issues. Should I split the second part (0-01-011) out to a new issue?

**Comment by satyavh** [comment]
You are absolutely right, these counters are wrong. Good catch.

We want to focus on the amount of people supporting the project, not the amount of donations. But this needs to be changed in feathers. I created a story for it: https://github.com/Giveth/feathers-giveth/issues/66

**Comment by vojtechsimetka** [comment]
The counters has been fixed in the feathers rewrite.
