### ISSUE TITLE
A donation is slow to be added... i assume the simulation script will catch it

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1950]
https://beta.giveth.io/milestone/kris-february-milestone
<img width="968" alt="Screen Shot 2021-03-22 at 4 57 59 PM" src="https://user-images.githubusercontent.com/14945613/112063691-162c7400-8b62-11eb-8c9f-cb5f9893bd5b.png">

It's weird cause i used other campaigns to delegate funds and they all got accepted before this one...

**Comment by aminlatifi** [comment]
@GriffGreen This delegation is committed and ready to be used. The loading is due to not cleaning some field in backend, and is going to be fixed!
Just donations with status `Pending` are not ready

**Comment by aminlatifi** [comment]
Submitted https://github.com/Giveth/feathers-giveth/issues/432 in feathers
