### ISSUE TITLE
Use the Standard Fee from Gasnow.org for the bridge 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1959]
Check to make sure that we have a good way to replace transactions implemented as this is a very conservative approach.

**Comment by aminlatifi** [comment]
implemented and has been setup on beta bridge, we should wait for some payment and see whether it works

**Comment by MoeNick** [comment]
Seems I cant test, pls let me know then.

**Comment by MoeNick** [comment]
Amin said it's working fine, I cant do UAT testing on this issue.
