### ISSUE TITLE
Can't Delegate...?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1964]
<img width="851" alt="Screen Shot 2021-03-30 at 10 41 43 PM" src="https://user-images.githubusercontent.com/14945613/113087427-e1649080-91e3-11eb-8376-76f758b1d458.png">
From: https://beta.giveth.io/milestone/merlin-commons-stack-non-simulator-work

I get stuck here... the delegate pop up isnt happening

**Comment by MoeNick** [comment]
Related to #1969

**Comment by MoeNick** [comment]
Tested on chrome and brave.
