### ISSUE TITLE
Show clear info/message when user with address not found

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1968]
https://develop.giveth.io/profile/dskajdlaskj

now when we enter fake address the giveth-dapp dont tell that this user address is invalid and user not found![Screen Shot 1400-01-14 at 14.36.07.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/f97d2135-7537-4373-b470-477d11057ce8)

**Comment by MoeNick** [comment]
No results found
We couldn’t find any user for your search or it doesn’t exist.
Try adjusting your search.

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/a3f3a556-3e8d-4883-b07a-a0a95be81e0c)

**Comment by divine-comedian** [comment]
testing on `develop.giveth.io` 
brave browser - clean cache and cookies

tried typing in a fake user name into URL `https://develop.giveth.io/profile/dfoiangfar` 
this is what popped up - 

![image](https://user-images.githubusercontent.com/67759413/126487620-13f20c43-022e-45a5-a419-e065212266c5.png)


it's not clear from the issue description what the intended action should be. Is this how the issue should look to be considered resolved?  @RamRamez  @MoeNick

**Comment by RamRamez** [comment]
> testing on `develop.giveth.io`
> brave browser - clean cache and cookies
> 
> tried typing in a fake user name into URL `https://develop.giveth.io/profile/dfoiangfar`
> this is what popped up -
> 
> ![image](https://user-images.githubusercontent.com/67759413/126487620-13f20c43-022e-45a5-a419-e065212266c5.png)
> 
> it's not clear from the issue description what the intended action should be. Is this how the issue should look to be considered resolved? @RamRamez @MoeNick

The issue is about making a Not found page for user profile page. We didn't have it before and it used to be confusing whether the user had registered or not.

**Comment by MoeNick** [comment]
Yeah its correct right now. It showed anonymous user before now it get better. 
Thanks @divine-comedian
