### ISSUE TITLE
Delegate menu doesn't work when you directly go to milestone and select a DAC or Campaign from options list

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1969]
If I go to milestone directly when I click to `Delegate` button We get error because `selectedToken` is undefined, 
but if we go to milestone from campaign it works

**Comment by mohammadranjbarz** [comment]
[Uploading... Screen Shot 1400-01-14 at 17.30.20.png]

**Comment by GriffGreen** [comment]
Related to #1964

**Comment by aminlatifi** [comment]
@RamRamez Please consider this in refactoring DelegateMultipleButton component for #1848

**Comment by mohammadranjbarz** [comment]
@RamRamez  @MoeNick 
I couldn't reproduce this bug again

**Comment by MoeNick** [comment]
tested both on brave and chrome
