### ISSUE TITLE
I can't use the dapp on Chrome or brave... same error as usual

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1970]
<img width="1205" alt="Screen Shot 2021-04-03 at 8 41 11 PM" src="https://user-images.githubusercontent.com/14945613/113496221-b3d75a00-94f7-11eb-975d-2ecaf220ad60.png">

**Comment by mohammadranjbarz** [comment]
Feathers was down and I think it was Mongo connection error, restarting application resolved the issue in this case
