### ISSUE TITLE
Aggregate payout conversations

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1972]
When one payment is aggregate of multiple donations like this one

![image](https://user-images.githubusercontent.com/5684607/113509439-d2c30400-956a-11eb-9799-255590b09d45.png)

For each paid donation one conversation is created as below:

![image](https://user-images.githubusercontent.com/5684607/113509416-ae672780-956a-11eb-9c35-82daf79c1b40.png)

While both above refer to single transaction https://etherscan.io/tx/0x2cfeacdaf014ca4a914545ffd010c5da42106d20761198e42dd8db28d644a4ef
In which 785 DAI is spent to recipient.

The two above conversation should be only one with value of 785, technically whenever a conversation is going to be created, existence of similar one should be checked. In case exists the new value should be added to previous one and the result be saved.

**Comment by MoeNick** [comment]
@aminlatifi & @mohammadranjbarz Pls test seems I cant

**Comment by mohammadranjbarz** [comment]
I'll do that

**Comment by mohammadranjbarz** [comment]
I tested, it was ok

![Screen Shot 1400-01-24 at 08.34.11.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/e2b51d44-e0c8-41b7-9431-346afdee24cf)
