### ISSUE TITLE
when milestone is approved or rejected once, don't show the accept/reject buttons, only shows update pending/accepted/rejected status. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#1983]
As a Milestone Owner or co-owner, in confirming milestone, I don't want to see accept/reject buttons after I click on any of them. because I got confused and may do it again after a while, since Im waiting for my transaction to got confirmed on net.
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/43a683eb-fbb5-4876-8595-f6f6e3fe1ba9)

**Comment by RamRamez** [comment]
We've add subscription to the Trace view so this is already done.
