### ISSUE TITLE
Notif on required fileds in create/edit milestone. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#1988]
As a user, when I start a milestone, If any fields are required, the form wont show me the notification, or scroll to the exact required field. So I got confused.... Nothing happened after I push propose milestone button. 

Success Criteria:

1- A notif will be shown on the top right, letting me knw there was any verification problem at the forms
OR
2- Scroll me to required or not verified field, so I gonna see the red error msg

**Comment by MoeNick** [comment]
I assigned it to cherik, @aminlatifi would u pls follow it  up with cherik? tnx

**Comment by MoeNick** [comment]
it scrolled to bottom of the error msg so as a user I cant see the error msg. can we just send some notif on top right of the page? 
@MohammadPCh @RamRamez

**Comment by aminlatifi** [comment]
> it scrolled to bottom of the error msg so as a user I cant see the error msg. can we just send some notif on top right of the page?
> @MohammadPCh @RamRamez

@MoeNick it's ready to test
