### ISSUE TITLE
Getting error while start campaign locally

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1996]
[Uploading... Screen Shot 1400-01-18 at 20.51.22.png]

**Comment by mohammadranjbarz** [comment]
it was ok after change nothing, 
I don't close it maybe it happens again

**Comment by mohammadranjbarz** [comment]
@MoeNick 

I couldn't reproduce it again, I'm not sure if this issue really exists

**Comment by mohammadranjbarz** [comment]
@MoeNick 
@aminlatifi 
Should I work on #2132?
it blocks testing this issue

**Comment by aminlatifi** [comment]
@mohammadranjbarz It's assigned to @MohammadPCh

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
@MoeNick 
This error happened one time for me in local and never saw it again, in last month , and now it's ok.
I think  we have nothing to do with this issue
