### ISSUE TITLE
Edit milestones with new form.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#1998]
As a user who can create a milestone, and as a campaign owner who want to accept and reject the milestone, I may need to edit the forms and their goes to old ones and I realty got confused caus they dont have the new form templates (lik bounty, payment etc.) So I need to edit them in new forms. 

Campaign owner also have edit button  in acceptance module.

**Comment by aminlatifi** [comment]
It has been implemented.
