### ISSUE TITLE
When donating the amount field became empty after scroll down in dialog and I should enter amount again

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#1999]
![Screen Shot 1400-01-18 at 23.52.06.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/3536d5ef-b362-4510-8d9c-7a7a075b5d16)

**Comment by RamRamez** [comment]
@mohammadranjbarz If you hover your mouse on the amount input box and scroll with your mouse, the number and slider changes. When you scroll down from top to bottom, amount decreases the time cursor passes the amount field.
This not actually a bug, although the UX is not perfect. I think we should redesign the slider with Ant design.
