### ISSUE TITLE
fix access via non-root path

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#2]
if you try and load mvp.giveth.io/profile we currently get a 404

**Comment by perissology** [comment]
this appears to be a hosting issue as it works correctly on localhost

**Comment by vsimetka** [comment]
I am pretty sure you need to configure the server to consider HTML5 routes for a base document. There is a chapter in netlify rewrite rules :) https://www.netlify.com/docs/redirects/#history-pushstate-and-single-page-apps

**Comment by perissology** [comment]
fixed in d2459f8
