### ISSUE TITLE
OH NO! warning and error despite a successful withdraw

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2001]
https://beta.giveth.io/milestone/rpp63s-scholarship-for-swiss-foundation-dues-new

<img width="462" alt="Screen Shot 2021-04-08 at 6 26 18 AM" src="https://user-images.githubusercontent.com/14945613/114018878-086b3400-986e-11eb-989f-2a87b7a43075.png">

**Comment by aminlatifi** [comment]
He had collected once, that's the reason

![image](https://user-images.githubusercontent.com/5684607/114024432-4aee3a00-9889-11eb-991f-3d50cd92e457.png)

**Comment by MoeNick** [comment]
As a user I want to see my live statues of my milestone and prevet me to do the actions more than just I did, so I didn't get confused.

**Comment by aminlatifi** [comment]
Same as #1785

**Comment by aminlatifi** [comment]
It's an error from smart contract side, maybe he has pushed button twice
