### ISSUE TITLE
Follow-up on scholarship request

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapp#2005]
Hi. I just wanted to check in on the status of my scholarship application that I submitted a week ago. I thought I might to add that I am joining the CS community as the Onboarding coordinator for the TEC, which either may not have been evident in my scholarship application and/or my identity may not have been clear. Thank you!

**Comment by GriffGreen** [comment]
@danelsuga THANK YOU SOO MUCH FOR MAKING AN ISSUE!!

:-D That's awesome! We love issues!


Sorry for the delay... the request didn't follow our guidelines and it will be edited to fit them as listed here: https://medium.com/commonsstack/trusted-seed-swiss-membership-scholarship-application-f2d07bc2fc90

It has a reviewer (It shouldn't), it is not asking for an amount, it doesn't include any links and didnt have your name in the title... 

I have been passing the responsibility to approve these scholarship requests to @julietea, but as this one is a weird one it has been delayed..

Thank you Suga! You will get an email when it is filled.

**Comment by GriffGreen** [comment]
Wow! You are fast on the Github notifications! :-D!

**Comment by danelsuga** [comment]
I've got my finger on the pulse, as they say. :D
(Or, well anyway, I was waiting to see what the problem was. :P Thank you!!!)

**Comment by danelsuga** [comment]
Me again! I claimed my scholarship but still see nothing in my account. (It's been 3 days.) I'm tagging @JulietEA just in case.  Thanks for the help!

**Comment by danelsuga** [comment]
Got it! Thank you! 💘

**Comment by danelsuga** [comment]
Got it! Thank you! 💘
