### ISSUE TITLE
Scroll to required filed keeps the field behind the menu

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2008]
In milestone creation forms, if a required field is not filled and user press create/propose button browser view scrolls to required field. But after scroll to required field, the field is behind menu!
![image](https://user-images.githubusercontent.com/5684607/114295873-4611cc00-9abd-11eb-94bd-dc43824c0b26.png)

**Comment by aminlatifi** [comment]
#1988

**Comment by MohammadPCh** [comment]
oops! so we should handle it manually.  ‌I will work on it tomorrow.

**Comment by MoeNick** [comment]
Tested on chrome and brave.
