### ISSUE TITLE
I canceled a milestone, but the conversation doesn't show up!

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2013]
I canceled a milestone and put a video in comment

https://develop.giveth.io/milestone/2342342342

But conversation is not created and cancel button still exists.

**Comment by mohammadranjbarz** [comment]
![Screen Shot 1400-01-23 at 13 08 07](https://user-images.githubusercontent.com/9850545/114365967-3a430a00-9b90-11eb-9044-635bdd7af932.png)
I attached error image for archive

**Comment by aminlatifi** [comment]
@MoeNick It's ready to be tested

**Comment by mohammadranjbarz** [comment]
Tested works

https://develop.giveth.io/milestone/milestone-with-reviewer2
