### ISSUE TITLE
Video Attaching not working in Edit Milestone View

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2017]

**Comment by aminlatifi** [comment]
@MohammadPCh Edit milestone uses old component `QuillFormsy` for detail, please fix it's uploading issue like the new Editor component.

**Comment by MoeNick** [comment]
@WhyldWanderer can u proceed with your test again on edit milestone?

**Comment by MoeNick** [comment]
I successfully attached a youtube after editing, the removal of attached YouTube was really hard but it meets the MVP requirements.  
But when I use a link on venmo, the video couldn't play after submitting edit. see: https://develop.giveth.io/milestone/video-attaching-test

**Comment by WhyldWanderer** [comment]
I tested on Chrome browser...
YouTube: passed 
Link: passed except vimeo. However if i use the link option to link to a different site like dailymotion, it worked fine.
File: passed
