### ISSUE TITLE
Process `PaymentExecuted` transactions corresponding to payments and compute user share on spent gas

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2020]

**Comment by aminlatifi** [comment]
Transactions made by other than Griff and Bowen should be excluded, @GriffGreen do you agree?

**Comment by aminlatifi** [comment]
In case a transaction includes `n` payments, `1/n` of gas price is user share

**Comment by MoeNick** [comment]
@aminlatifi 
How can I test it?
