### ISSUE TITLE
Design UI menus and components which represent gas paid for each user

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2021]
We will want to tell the user that we are spending on gas for them We can aggregated the gas costs and display them for each of these categories:

- [x] recipient (To be displayed in the profile page?)
- [x]  campaign (To be displayed on the Campaign Page?)
- [x]  milestone (To be displayed on the Milestone page?)

The question is... how should we actually display them? @markoprljic :-D?

How audacious do we want to be for displaying them? should we do pop-ups?

**Comment by GriffGreen** [comment]
<img width="219" alt="Screen Shot 2021-04-12 at 8 22 02 AM" src="https://user-images.githubusercontent.com/14945613/114419365-a5ea9e80-9bb3-11eb-8a1b-22265ddfd028.png">

We could put it here too.. like recipients, if we have paid gas for them, we could list it here

**Comment by markoprljic** [comment]
I don't think this issue is clear to me. What is the problem we're solving? What are we trying to achieve by informing users about paid gas fees? 
Should this just be a static box on each of the listed pages that shows total gas paid for that project/user? Who benefits from reading this information? Is this publicly visible or just by the project owner?

I'd need more clarification obviously :)

**Comment by laurenluz** [comment]
Would love to be kept in the loop on this issue so I can tweet about it once we have it live!

**Comment by markoprljic** [comment]
Public info
We're paying their gas and no one knows, we wanna brag about it!
Example: "Hey Fairdata Society, we paid that much gas for you!"

For User in dropdown menu My Profile, show this info, or their profile page as well.
For Campaigns show the total sum of gas fees paid for this campaign.
For the Milestones as well. 

Ideally have a share button to share this info on Twitter or elsewhere. 

Have this info somewhere on those pages where people will be able to find it easy again. 

Keep Lauren in the loop when this is done so she can tweet about it.

**Comment by markoprljic** [comment]
In Profile dropdown (also proposing to combine Manage under user profile dropdown)
![Image 2021-04-25 at 6 27 32 pm](https://user-images.githubusercontent.com/5704285/116002365-b2321b00-a5f9-11eb-8d7e-8a339fe6f8b9.jpg)

On the Campaign page, under Funding (contextually fits there), also notice slightly improved UI for this table
![Image 2021-04-25 at 7 08 17 pm](https://user-images.githubusercontent.com/5704285/116002381-c544eb00-a5f9-11eb-887b-1ae6510a8a54.jpg)

On the Milestone page, under Details
![Image 2021-04-25 at 7 13 12 pm](https://user-images.githubusercontent.com/5704285/116002495-5025e580-a5fa-11eb-8b6f-e22e90971844.jpg)

**Comment by MoeNick** [comment]
@RamRamez pls take a look

**Comment by MoeNick** [comment]
@RamRamez are u ok with the design?

**Comment by RamRamez** [comment]
@MoeNick @markoprljic The gas icon is a little different from the banner gas limit notification (it has a leaf on it). Should we change the banner gas icon with the new icon or use different icons for these?
And please give me the link of this new gas icon.

**Comment by markoprljic** [comment]
@RamRamez Yes, tha gas icon is intentionally different, please use it there. No need to change the one in the banner.

Link to Figma https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4961%3A0
