### ISSUE TITLE
Delegation didnt work? or stuck?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2022]
https://beta.giveth.io/milestone/merlin-commons-stack-non-simulator-work

<img width="1023" alt="Screen Shot 2021-04-12 at 8 25 15 AM" src="https://user-images.githubusercontent.com/14945613/114419856-1691bb00-9bb4-11eb-86ea-8641f5908269.png">

**Comment by aminlatifi** [comment]
@mohammadranjbarz `commitTime` wasn't set for that donation! it was delegated from DAC and wasn't normalized ! Can you investigate it? does simulation script needs some change?

**Comment by aminlatifi** [comment]
@mohammadranjbarz Simulation says this donation is rejected, but shouldn't
{_id: ObjectId('6063f1116e095261b8174321')}

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Simulation says this donation is rejected, but shouldn't
> {_id: ObjectId('6063f1116e095261b8174321')}

Thanks Amin I'll check it

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
it seems you fixed the donation, am I right?

**Comment by aminlatifi** [comment]
Multiple issues are showed up in this case:
1. The delegated donation from dac didn't have `commitTime` entry, so feathers didn't normalize (and transfer to milestone) after three days
2. I filled `commitTime` manually on DB. But, the `performedByAddress` role of new donation created after pledgeNormalize action was feathers. That caused the conversation owner not be any user and that stopped UI from processing conversation (#2025, #2026)
3. After normalizing the donation by feathers, the parent donation (with `ToApprove` state) `amountRemaining` wasn't zero
4. Simulation script fixed the transfer and `amountRemaining`, but the parent donation status became `Rejected`

**Comment by mohammadranjbarz** [comment]
> Multiple issues are showed up in this case:
> 
> 1. The delegated donation from dac didn't have `commitTime` entry, so feathers didn't normalize (and transfer to milestone) after three days
> 2. I filled `commitTime` manually on DB. But, the `performedByAddress` role of new donation created after pledgeNormalize action was feathers. That caused the conversation owner not be any user and that stopped UI from processing conversation (#2025, #2026)
> 3. After normalizing the donation by feathers, the parent donation (with `ToApprove` state) `amountRemaining` wasn't zero
> 4. Simulation script fixed the transfer and `amountRemaining`, but the parent donation status became `Rejected`

It seems the donations had `commitTime` but, simulation has been changed that to `Rejected`

https://feathers.beta.giveth.io/donations/6063f1116e095261b8174321
(I think it's the original donation because it has comment)

**Comment by aminlatifi** [comment]
> > Multiple issues are showed up in this case:
> > 
> > 1. The delegated donation from dac didn't have `commitTime` entry, so feathers didn't normalize (and transfer to milestone) after three days
> > 2. I filled `commitTime` manually on DB. But, the `performedByAddress` role of new donation created after pledgeNormalize action was feathers. That caused the conversation owner not be any user and that stopped UI from processing conversation (#2025, #2026)
> > 3. After normalizing the donation by feathers, the parent donation (with `ToApprove` state) `amountRemaining` wasn't zero
> > 4. Simulation script fixed the transfer and `amountRemaining`, but the parent donation status became `Rejected`
> 
> It seems the donations had `commitTime` but, simulation has been changed that to `Rejected`
> 
> https://feathers.beta.giveth.io/donations/6063f1116e095261b8174321
> (I think it's the original donation because it has comment)

I filled commitTime entry myself manually, if you notice it has the same value of `createdAt`

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I just deleted your comment by mistake :(
Zenhub UX confuse me sometimes, your comment was this

**I filled commitTime entry myself manually, if you notice it has the same value of createdAt**

**Comment by mohammadranjbarz** [comment]
Simulation script fixed the transfer and amountRemaining, but the parent donation status became Rejected?
@aminlatifi 
**Answer**:

This is the first event:

```
    "transactionHash": "0x3279171755dc968ce987129397b8ad07f21c62114ff5b8402abed4a367008193",
    "transactionIndex": 22,
    "id": "log_cd01e675",
    "returnValues": {
      "0": "8913",
      "1": "9071",
      "2": "110000000000000000",
      "from": "8913",
      "to": "9071",
      "amount": "110000000000000000"
    },
    "event": "Transfer",
```
 the owner of `8913` and `9071` is :
```
  addr: '0xc9737bD3DCa2d644e15d5662163Df3b5D9ca6878',
  name: 'Giveth Bounty rescued funds',
```

The second event ( after normalizing https://rinkeby.etherscan.io/tx/0x2026e7970f47d6ebdb920d0b339d228e117d7550936cffac4a4352ad450eeb25):

```
    "transactionHash": "0x2026e7970f47d6ebdb920d0b339d228e117d7550936cffac4a4352ad450eeb25",
    "transactionIndex": 12,
    "id": "log_20bb696a",
    "returnValues": {
      "0": "9071",
      "1": "9169",
      "2": "110000000000000000",
      "from": "9071",
      "to": "9169",
      "amount": "110000000000000000"
    },
    "event": "Transfer",
```

The owner of `9169` is :
```
 addr: '0x55C0D3019521DBDfd4D6c66e3a65235d42BCB9ef',
  name: 'Merlin Commons Stack (non Simulator) Work',

```

So as we see after delegating money goes to `9071` and after finalizing money goes from `9071` to `9169` that is `Merlin Commons Stack (non Simulator) Work` so I think its reasonable that this https://feathers.beta.giveth.io/donations/6063f1116e095261b8174321

become rejected, and the new donation will create with `Committed` status to `Merlin Commons Stack (non Simulator) Work` milestone.

https://feathers.beta.giveth.io/donations?parentDonations=6063f1116e095261b8174321

PS: as you see in simulation script: https://github.com/Giveth/giveth-1-simulation/blob/6aae9affb32a43f9aa6449dda3e676958c2a6083/src/index.ts#L254-L262

this donation https://feathers.beta.giveth.io/donations/6063f1116e095261b8174321 has
`"intendedProjectId": 2532`, but toPledge's owner was `2515` so the donation became `Rejected`

**Comment by aminlatifi** [comment]
> Simulation script fixed the transfer and amountRemaining, but the parent donation status became Rejected?
> @aminlatifi
> **Answer**:
> 
> This is the first event:
> 
> ```
>     "transactionHash": "0x3279171755dc968ce987129397b8ad07f21c62114ff5b8402abed4a367008193",
>     "transactionIndex": 22,
>     "id": "log_cd01e675",
>     "returnValues": {
>       "0": "8913",
>       "1": "9071",
>       "2": "110000000000000000",
>       "from": "8913",
>       "to": "9071",
>       "amount": "110000000000000000"
>     },
>     "event": "Transfer",
> ```
> 
> the owner of `8913` and `9071` is :
> 
> ```
>   addr: '0xc9737bD3DCa2d644e15d5662163Df3b5D9ca6878',
>   name: 'Giveth Bounty rescued funds',
> ```
> 
> The second event ( after normalizing https://rinkeby.etherscan.io/tx/0x2026e7970f47d6ebdb920d0b339d228e117d7550936cffac4a4352ad450eeb25):
> 
> ```
>     "transactionHash": "0x2026e7970f47d6ebdb920d0b339d228e117d7550936cffac4a4352ad450eeb25",
>     "transactionIndex": 12,
>     "id": "log_20bb696a",
>     "returnValues": {
>       "0": "9071",
>       "1": "9169",
>       "2": "110000000000000000",
>       "from": "9071",
>       "to": "9169",
>       "amount": "110000000000000000"
>     },
>     "event": "Transfer",
> ```
> 
> The owner of `9169` is :
> 
> ```
>  addr: '0x55C0D3019521DBDfd4D6c66e3a65235d42BCB9ef',
>   name: 'Merlin Commons Stack (non Simulator) Work',
> ```
> 
> So as we see after delegating money goes to `9071` and after finalizing money goes from `9071` to `9169` that is `Merlin Commons Stack (non Simulator) Work` so I think its reasonable that this https://feathers.beta.giveth.io/donations/6063f1116e095261b8174321
> 
> become rejected, and the new donation will create with `Committed` status to `Merlin Commons Stack (non Simulator) Work` milestone.
> 
> https://feathers.beta.giveth.io/donations?parentDonations=6063f1116e095261b8174321
> 
> PS: as you see in simulation script: https://github.com/Giveth/giveth-1-simulation/blob/6aae9affb32a43f9aa6449dda3e676958c2a6083/src/index.ts#L254-L262
> 
> this donation https://feathers.beta.giveth.io/donations/6063f1116e095261b8174321 has
> `"intendedProjectId": 2532`, but toPledge's owner was `2515` so the donation became `Rejected`

The last line has a wrong statement, toPledge's owner is 2532

![image](https://user-images.githubusercontent.com/5684607/118484451-7a1b8500-b72c-11eb-8f50-b80c0a534268.png)

**Comment by laurenluz** [comment]
I think this is working correctly now on develop. I was able to delegate from a community to trace.

![image](https://user-images.githubusercontent.com/75490971/120937132-f0c2f700-c6c8-11eb-838e-d6340ee6299d.png)
