### ISSUE TITLE
Redesign the "Accept a proposal" and "Write a comment" modals

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2028]
<img width="993" alt="Screen Shot 2021-04-13 at 6 52 54 AM" src="https://user-images.githubusercontent.com/14945613/114592539-57a8ce80-9c8b-11eb-9750-64b421a1a94e.png">

<img width="989" alt="Screen Shot 2021-04-13 at 10 04 02 AM" src="https://user-images.githubusercontent.com/14945613/114592548-59729200-9c8b-11eb-97ef-b71a085bcd05.png">

**Comment by Danibelle** [comment]
Accept Proposed Milestone:
Your acceptance of this Milestone will be recorded as a publicly visible comment, and emailed to the Milestone Owner. Please add a personal comment, compliment or other custom message to accompany it!

**Comment by Danibelle** [comment]
Comment on Milestone:
Use this Comment section to provide a public record of questions and answers, updates, changes, compliments or concerns, and other information that helps donors and project participants understand the current status of the Milestone!

**Comment by laurenluz** [comment]
Love the suggested text Dani. Can we also make the headers "Accept Proposed Milestone" and "Comment on Milestone" bolded, and delete the text "Accompanying message" for both?

**Comment by MoeNick** [comment]
@RamRamez and @aminlatifi pls take a look, can we proceed?

**Comment by MoeNick** [comment]
@markoprljic would u pls tale a look at this?

**Comment by RamRamez** [comment]
Changing the text is a good idea. But I think we need more colors to make them more exciting

**Comment by markoprljic** [comment]
On it.

**Comment by markoprljic** [comment]
Write a Comment modal

![Image 2021-05-03 at 6 56 52 pm](https://user-images.githubusercontent.com/5704285/116907057-5a229680-ac41-11eb-8d13-11e4ee73733f.jpg)


Using lottie animation of the pencil https://lottiefiles.com/180-pencil-write

**Comment by MoeNick** [comment]
Thanks to @markoprljic 
@RamRamez @MohammadPCh pls take a look and approve

**Comment by markoprljic** [comment]
Accept proposed Milestone

![Image 2021-05-03 at 7 09 30 pm](https://user-images.githubusercontent.com/5704285/116908403-26487080-ac43-11eb-8d2a-94b537762052.jpg)


Lottie https://lottiefiles.com/32537-checkmark

**Comment by markoprljic** [comment]
@RamRamez @MohammadPCh Figma source https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4973%3A199

**Comment by RamRamez** [comment]
OK. Thanks @markoprljic for the design.

**Comment by aminlatifi** [comment]
@RamRamez When I click the submit, both buttons go to loading state
![image](https://user-images.githubusercontent.com/5684607/118453507-8bed3000-b70c-11eb-8ea4-d6ab7f0957d7.png)
