### ISSUE TITLE
Issues with opening Giveth Dapp

### ISSUE THREAD

**Issue by Vyvy-vi** [Giveth/giveth-dapp#2033]
## Issues:
- I can't log back in and the content on giveth isn't loading for me

## Screenshots:
![DACs not loading](https://user-images.githubusercontent.com/62864373/114740012-10900b80-9d67-11eb-9ae2-b9503f3c49d6.png)
![Screenshot 2021-04-14 at 9 04 13 PM](https://user-images.githubusercontent.com/62864373/114740364-682e7700-9d67-11eb-8a4f-8778d291e83a.png)

## The full story:
Some time ago(about a day ago), I made a Giveth profile and opened a milestone(on [Commons Stack’s Swiss Association’s Giveth Campaign.](https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6)). I got an acknowledgement mail, and everything was working great. But, right now I am facing some weird errors. While opening the site, sometimes it shows - `Unlock Metamask`, even tho my metamask is unlocked. Sometimes, it looks like it signed in, but then shows some errors like `Oops, something went wrong... The Giveth dapp could not load Campaigns for some reason. Please try refreshing the page...`.
I tried locking metamask, clearing cache, but still the same errors persist. 

## Context on what I was using:
- Brave Browser-v1.22.71
- Metamask(with Rinkeby chain selected)

## I also screwed up a few things:
- I think while I was making a milestone for the scholarship grant, I forgot to mention the amount and the cryptocurrency 😅 
- Maybe the picture wasn't fun enough?

**Comment by Vyvy-vi** [comment]
### Console logs-

![Screenshot 2021-04-14 at 9 25 21 PM](https://user-images.githubusercontent.com/62864373/114740962-f571cb80-9d67-11eb-840e-91ab257a829e.png)

![Screenshot 2021-04-14 at 9 26 26 PM](https://user-images.githubusercontent.com/62864373/114741134-19351180-9d68-11eb-8a8d-0eadb415cc4d.png)

**Comment by Vyvy-vi** [comment]
*UPDATES - 
Interestingly, I left for an hour and rebooted my laptop and there seem to be no issues logging in.
Could this be an issue on my end?

**Comment by mohammadranjbarz** [comment]
@Vyvy-vi 
Yes, I thinks it's about your end, because our monitoring says we had no down time in backend, so If your request failed with timeout it's maybe because your network connection or something like that

**Comment by mohammadranjbarz** [comment]
> ### Console logs-
> ![Screenshot 2021-04-14 at 9 25 21 PM](https://user-images.githubusercontent.com/62864373/114740962-f571cb80-9d67-11eb-840e-91ab257a829e.png)
> 
> ![Screenshot 2021-04-14 at 9 26 26 PM](https://user-images.githubusercontent.com/62864373/114741134-19351180-9d68-11eb-8a8d-0eadb415cc4d.png)

Thanks for sending your console logs

**Comment by aminlatifi** [comment]
@Vyvy-vi Thanks for reporting, other customers have reported the issue of connecting problem on Brave. Next time please try using chrome or other browser to see whether it's working, if yes please inform us.

**Comment by Vyvy-vi** [comment]
Thanks for the response. :+1:
I'll close the issue for now. If there's any future issues that are regarding the same reason, or some info on causes, I'll reopen it.
