### ISSUE TITLE
Can't access the dapp from brave again :-P

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2034]

**Comment by MoeNick** [comment]
I try to test all issues at brave too.

**Comment by aminlatifi** [comment]
@MoeNick This issue would be solved after upgrading feathers and its dependencies to version 4.
https://github.com/feathersjs/feathers/issues/2297#issuecomment-815904750

**Comment by aminlatifi** [comment]
I upgraded `@feathersjs/socketio` to `^3.2.9` and Griff issue is solved at least now. But upgrading whole feathers to version 4.x is still undergoing.
