### ISSUE TITLE
Can't delegate from milestone screen

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2035]
<img width="887" alt="Screen Shot 2021-04-14 at 9 27 48 AM" src="https://user-images.githubusercontent.com/14945613/114745752-475a2780-9d4f-11eb-94af-d2293ef04416.png">

**Comment by RamRamez** [comment]
@GriffGreen I checked delegation from Commons Stack Association on beta develop branch and it was ok for me. Please let me know if you face the problem again.
By the way, it takes sometime to fetch pledges from backend.
