### ISSUE TITLE
Options not showing up when delegating funds

### ISSUE THREAD

**Issue by JulietEA** [Giveth/giveth-dapp#2038]
When logged in and delegating funds to a milestone, the campaign is selected, but the additional options / next steps aren't showing up: 

<img width="736" alt="Screen Shot 2021-04-16 at 4 47 50 PM" src="https://user-images.githubusercontent.com/54636748/115087431-c6786880-9ed3-11eb-8159-59f12f7dcda7.png">

**Comment by aminlatifi** [comment]
It's the repeat of #1964
