### ISSUE TITLE
randomly selected reviewer needs to be checked

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#204]
It is possible for the randomly selected reviewer to be the campaign owner or for milestones the recipient.

We need to make sure the the reviewer is a different address:

- campaigns:
  - reviewer should not be the user deploying the campaign (campaignOwner)

- milestone:
  - reviewer should not be the recipient or the campaignReviewer

**Comment by vojtechsimetka** [comment]
Reviewers are now picked from a list that does not contain the Campaign Manager or Milestone Manager.
