### ISSUE TITLE
check login and network before loading my donations and refund button 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2040]
As a donator, when I want to refund any of my donations and I was logged out, nothing happens. Until I get logged in and click on refund button again. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/7c99300a-9cb2-4af1-a73f-82ef6fa41e21)

**Comment by aminlatifi** [comment]
Sign in action should add to refund button

**Comment by RamRamez** [comment]
@MoeNick It was ok for me. Refund asks for sign in and changing the user account refreshes the page.
If you could reproduce the problem again, please tell me.

**Comment by aminlatifi** [comment]
@MoeNick Please test it again

**Comment by MoeNick** [comment]
This is the scenario:
1- Change the account on metamask
2- Go to Me doantion
3- Before sign-in, click on refund, correctly it says you need to sign in, after signing in, nothing happens
4- you need to click on refund bottom again. 
(User expects, refund automatically begins after signing-in 
OR
a message come and say," signing was successful, now click on refund again. )

**Comment by RamRamez** [comment]
There are similar problems for Commit and Reject buttons on My donations page.
