### ISSUE TITLE
Use Ant Design component in edit DAC

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2046]
Me as a Dac owner want to edit my DAC page better.

**Comment by MoeNick** [comment]
@RamRamez the form won't scroll to the top of the field, which is required of missing validation. 
Scenario:
I make the title empty, try to submit the DAC , mothing happens or I didn't see any error.

**Comment by RamRamez** [comment]
> @RamRamez the form won't scroll to the top of the field, which is required of missing validation.
> Scenario:
> I make the title empty, try to submit the DAC , mothing happens or I didn't see any error.

It's fixed on PR #2073

**Comment by MoeNick** [comment]
Tested!
