### ISSUE TITLE
Balance is incorrect in donate modal

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2047]
When I directly open campaign page and immediately open donate modal balance is shown zero

![image](https://user-images.githubusercontent.com/5684607/115243787-882fb300-a138-11eb-8e56-31c328a35661.png)

**Comment by aminlatifi** [comment]
Seems to be fixed.

**Comment by MoeNick** [comment]
tested!

**Comment by aminlatifi** [comment]
It shows my balance zero still under slow network environment 

![image](https://user-images.githubusercontent.com/5684607/116972485-51c56c80-acd0-11eb-9bf8-ce4a592102cb.png)

![image](https://user-images.githubusercontent.com/5684607/116972527-61dd4c00-acd0-11eb-81ee-cb24ddb466ea.png)

**Comment by MoeNick** [comment]
How can u simulate slow connection environment 🧐

**Comment by aminlatifi** [comment]
> How can u simulate slow connection environment 🧐

Browser DevTools -> Network Tab -> No throttling has options

**Comment by MoeNick** [comment]
@aminlatifi can cherick take this task? we planned for it.

**Comment by aminlatifi** [comment]
> @aminlatifi can cherick take this task? we planned for it.

It was assigned to him, but he got busy
