### ISSUE TITLE
Design withdraw limit alerts/notifications

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2049]

**Comment by aminlatifi** [comment]
@mohammadranjbarz Would you feel this milestone with images of your ready cases of marking milestone complete, withdraw and proposing a milestone?

**Comment by mohammadranjbarz** [comment]
![Screen Shot 1400-01-30 at 20 08 08 (2)](https://user-images.githubusercontent.com/9850545/115264452-8fac8780-a14b-11eb-8579-4a0792a18c1a.png)
![Screen Shot 1400-01-30 at 20 08 30 (2)](https://user-images.githubusercontent.com/9850545/115264463-91764b00-a14b-11eb-85c8-d1844e0fad9c.png)
![Screen Shot 1400-01-30 at 20 14 05](https://user-images.githubusercontent.com/9850545/115264777-d8fcd700-a14b-11eb-96ce-8edd667c26a1.png)

**Comment by markoprljic** [comment]
Use this modal for all cases, update text accordingly. 
Use Lottie animation https://lottiefiles.com/5527-alert-notification-character
Figma file here https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4967%3A0

![Image 2021-04-25 at 7 25 09 pm](https://user-images.githubusercontent.com/5704285/116002891-03dba500-a5fc-11eb-9d2d-c667312d37ed.jpg)

**Comment by MoeNick** [comment]
@RamRamez pls approve and create implementation task if it's ok for you.

**Comment by RamRamez** [comment]
> @RamRamez pls approve and create implementation task if it's ok for you.

@MoeNick ok.
