### ISSUE TITLE
currentUser object is not reactive

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#205]
to reproduce:

1. sign-in as a new user
2. open react devtools & inspect the `currentUser` object.
3. there should not be a `myGiverId` property
4. make a donation
5. once the donation is mined the feathers contains a `giverId` for the user, but it is not reflected in the dapp

the `myGiverId` property is only present after a page refresh. This is problematic as it can lead to a single giver having multiple "giverId" in the lp contract

we need to make the `currentUser` object reactive.

**Comment by vojtechsimetka** [comment]
Could be solved with Context API after #150

**Comment by perissology** [comment]
this is fixed
