### ISSUE TITLE
Frontend implementation for search bar inside campaign. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2052]

**Comment by MoeNick** [comment]
@aminlatifi it shouldn't get tested on UAT before closing?

**Comment by MoeNick** [comment]
1- Won't search within characters on titles or body
2- Must show "no result " msg after search has no results
3- Must have search botton amd UX improvement, it's confusing to press magnifier icon while there is some other icons there.
4- It should be a "clear search" or reset button, especially after no result found and after each search done.

I think we'd better count on marko for this.

**Comment by MoeNick** [comment]
Dear @markoprljic would u pls take a look, it needs a better design on:
1- placement of the bar, watermark and search button instead of magnifier
2- Remove search filters button.
3- Design "no result found"

Appreciate it.

**Comment by markoprljic** [comment]
Can you please provide a screenshot of the Campaign page and where you want this search to be? 

What is a watermark? 
What search filters to remove? Where is that?

I'm lost.

**Comment by aminlatifi** [comment]
> Can you please provide a screenshot of the Campaign page and where you want this search to be?
> 
> What is a watermark?
> What search filters to remove? Where is that?
> 
> I'm lost.

@markoprljic The search bar is implemented in develop.giveth.io campaign pages

**Comment by markoprljic** [comment]
This one here?

![Image 2021-05-06 at 4 35 10 pm](https://user-images.githubusercontent.com/5704285/117316649-0e622e00-ae89-11eb-85ee-90bd5849f2af.jpg)

**Comment by MoeNick** [comment]
> This one here?
> 
> ![Image 2021-05-06 at 4 35 10 pm](https://user-images.githubusercontent.com/5704285/117316649-0e622e00-ae89-11eb-85ee-90bd5849f2af.jpg)

Yes Man...

**Comment by markoprljic** [comment]
This should be a live search, when user starts typing it automatically filters the results below.

In case no results matching the search then show this information below:

![Image 2021-05-06 at 5 12 59 pm](https://user-images.githubusercontent.com/5704285/117322510-5cc5fb80-ae8e-11eb-843f-fc64a63969d9.jpg)

Figma https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4984%3A14
Lottie https://lottiefiles.com/5451-search-file

**Comment by MoeNick** [comment]
> This should be a live search, when user starts typing it automatically filters the results below.
> 
> In case no results matching the search then show this information below:
> 
> ![Image 2021-05-06 at 5 12 59 pm](https://user-images.githubusercontent.com/5704285/117322510-5cc5fb80-ae8e-11eb-843f-fc64a63969d9.jpg)
> 
> Figma https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4984%3A14
> Lottie https://lottiefiles.com/5451-search-file
Thanks marko, clasp for quick respond: 
1- @aminlatifi  jaan, can we make it live or we have limitation on backend? 
2- Due to case of limitation, should we have a button to reset the search result @markoprljic ? clear the bar character by character is a little bit boring to me. Am I right?

**Comment by markoprljic** [comment]
Sorry forgot to include focus state on search input field.

![Image 2021-05-06 at 5 32 50 pm](https://user-images.githubusercontent.com/5704285/117325592-28077380-ae91-11eb-9e2e-d812319a8cb7.jpg)

**Comment by MoeNick** [comment]
> Sorry forgot to include focus state on search input field.
> 
> ![Image 2021-05-06 at 5 32 50 pm](https://user-images.githubusercontent.com/5704285/117325592-28077380-ae91-11eb-9e2e-d812319a8cb7.jpg)

Perfect

**Comment by aminlatifi** [comment]
> > This should be a live search, when user starts typing it automatically filters the results below.
> > In case no results matching the search then show this information below:
> > ![Image 2021-05-06 at 5 12 59 pm](https://user-images.githubusercontent.com/5704285/117322510-5cc5fb80-ae8e-11eb-843f-fc64a63969d9.jpg)
> > Figma https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4984%3A14
> > Lottie https://lottiefiles.com/5451-search-file
> > Thanks marko, clasp for quick respond:
> > 1- @aminlatifi  jaan, can we make it live or we have limitation on backend?
> > 2- Due to case of limitation, should we have a button to reset the search result @markoprljic ? clear the bar character by character is a little bit boring to me. Am I right?

Thanks @markoprljic 

@MoeNick No, backend doesn't need any new feature.

**Comment by MoeNick** [comment]
@aminlatifi shall we assign to frontend guys or you can go forward?

**Comment by aminlatifi** [comment]
@MoeNick I take over
