### ISSUE TITLE
Implement subscription for milestone on ViewMilestone to get updates on changes

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2058]
Me as campaign owner, expect the accept/reject buttons hide after I click on one of them and accept the transaction in meta mask, so it prevents me to double click on them again and again. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/27424d29-f35e-4efd-80e8-e90428a7b522) 

It won't change only I refresh the page.

(We may add "get update " button after clicking on any button )

**Comment by RamRamez** [comment]
@aminlatifi It seems all milestone alerts like Request mark complete, Propose milestone again, Archive milestone … have this problem. Maybe we can implement a subscription for milestone object on ViewMilestoneAlerts

**Comment by aminlatifi** [comment]
> @aminlatifi It seems all milestone alerts like Request mark complete, Propose milestone again, Archive milestone … have this problem. Maybe we can implement a subscription for milestone object on ViewMilestoneAlerts

Yes we should
