### ISSUE TITLE
I have DAI but it's says you can't donate because you don't have any. (My latest logged-in didnt have)

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2059]
This is my account
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/6a718e6f-e81d-4b49-bec6-281db8b8faa1)

This is the error I get
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/75058b20-8066-4ae4-b6d0-e7cfb52f7ee7)

After refreshing the page:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/8ad1aa85-7528-4933-9dca-916439b57b6f)

Note: My latest logged-in account  didnt have any  DAI, I change it, but the DAPP didnt get updates only I change my account)

**Comment by aminlatifi** [comment]
Same as #2047
