### ISSUE TITLE
The edit CAM / DAC / Milestone form, won't let me working with pictures.. etc

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2069]
Me as a user who wants to propose milestone or create campaign, need to resize pictures in forms, while on editing or creating. 
I don't have any tools to resize or change the location. 

Take a look at this: 
https://develop.giveth.io/dac/dac-owner-dac-test-1
- the picture length is enlarged to the size of video. 
- The height of youtube video is shorten! 
- the uploaded rabbit video, dont have any progress bar during upload and I didn't get how much time it takes and it didn't showed up in edit form as uploaded one.

**Comment by MoeNick** [comment]
@aminlatifi jan pls take a look. User even cant resize a picture in editor.

**Comment by aminlatifi** [comment]
> @aminlatifi jan pls take a look. User even cant resize a picture in editor.

I can resize and select section of an image in edit forms

**Comment by aminlatifi** [comment]
> @aminlatifi jan pls take a look. User even cant resize a picture in editor.

I could reproduce it here

https://develop.giveth.io/dac/new-dac-with-new-form

**Comment by aminlatifi** [comment]
> Me as a user who wants to propose milestone or create campaign, need to resize pictures in forms, while on editing or creating.
> I don't have any tools to resize or change the location.
> 
> Take a look at this:
> https://develop.giveth.io/dac/dac-owner-dac-test-1
> 
> * the picture length is enlarged to the size of video.
> * The height of youtube video is shorten!
> * the uploaded rabbit video, dont have any progress bar during upload and I didn't get how much time it takes and it didn't showed up in edit form as uploaded one.

Slug is changed and the mentioned dac url is not useful anymore unfortunately

**Comment by MoeNick** [comment]
it goes to old form while editing, and don't let me resize the pic etc... 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/0ad8d247-50e7-4e49-8a15-ca3af3c08f9e)
