### ISSUE TITLE
Wrong caption for Cancelled donations in /donations page

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2075]
according to this
https://github.com/Giveth/giveth-dapp/issues/2061#issuecomment-826927852

**Comment by mohammadranjbarz** [comment]
@MoeNick 
If you want to test it, create a milestone, donate to it, then after cancelling milestone, got to your donations page then you should see the donation status is cancelled and the caption is right ( it was unknown before merging this)

**Comment by MoeNick** [comment]
I have problems and I told @mohammadranjbarz in telegram chat.
