### ISSUE TITLE
Pending Transaction Design 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2080]
This screen remains active. after I unlock and donate. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/90805aef-eea6-4a7f-83f4-34974e9a9339)

**Comment by aminlatifi** [comment]
After donate dapp tries to update backend. Maybe there was some connectivity issue at the moment.

**Comment by MoeNick** [comment]
Need design for show pending trx

**Comment by markoprljic** [comment]
Here all three notifications for transactions.

![Image 2021-05-06 at 4 20 57 pm](https://user-images.githubusercontent.com/5704285/117314477-19b45a00-ae87-11eb-8454-f37a3263f453.jpg)

Source file in Figma here https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4973%3A199

**Comment by MoeNick** [comment]
@aminlatifi can i assign it to RamRamez?

**Comment by aminlatifi** [comment]
> @aminlatifi can i assign it to RamRamez?

Yeah

**Comment by MoeNick** [comment]
@RamRamez as an unplanned task you can take this in this sprint.

**Comment by RamRamez** [comment]
@markoprljic Do these notification icons have Lottie animations?

**Comment by markoprljic** [comment]
https://lottiefiles.com/30679-loading
