### ISSUE TITLE
Unsubscribe email sent from beta get 404 error. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2083]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/835bd664-72b3-4e19-9121-75644be4d63d)

**Comment by RamRamez** [comment]
It's done in Dapp-mailer [PR #21](https://github.com/Giveth/dapp-mailer/pull/21).

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/120937917-90828400-c6cd-11eb-8e1c-4aec6a6902c5.png)

unsubscribe link from email is working fine now
