### ISSUE TITLE
Slider bug while on my delegations as campaign owner

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2085]
Me as campaign owner, when log-in and see my delegations, after clicking on delegate button, it appears:

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4143e6d5-0fb9-4675-a983-d605c0d727d2)

sometimes it get like his|:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/dec92950-aece-44f5-9b06-17cd0f413672)

**Comment by aminlatifi** [comment]
@MoeNick Delegate modal is changed a lot, can you test this scenario again?
