### ISSUE TITLE
I keep clicking on mark complete but nothing happend ( console says jwt expired)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2088]
I think maybe we should force the user to login again when jwt expired ( after 1 day)

![Screen Shot 1400-02-09 at 08.50.23.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/fca305f7-2ec6-42f8-9c98-810113567150)

**Comment by aminlatifi** [comment]
#2109

**Comment by aminlatifi** [comment]
@MoeNick It should be fixed by #1639
