### ISSUE TITLE
How the milestone completed below limit donated amount? 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2089]
How did it become completed? while total amounts are under the limit? the money stuck in the milestone and it cannot be collected. 

https://develop.giveth.io/milestone/test-delegation
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e84ecf3b-40d7-458d-9e2e-8d6b69aa7cf7)

**Comment by MoeNick** [comment]
Please investigate with logs, then make it more clear and put estimation .
@aminlatifi

**Comment by aminlatifi** [comment]
@MoeNick It's archived. the status of archived milestones is shown as `Completed`

**Comment by aminlatifi** [comment]
Archive should be disabled for milestone with balance less than limit.

**Comment by MoeNick** [comment]
@aminlatifi I think we have a new design for "oh no" msg. 
How ever it works fine functionally.
