### ISSUE TITLE
GivethWallet will not unlock when switching wallets

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#21]
If I sign in with 1 wallet after a page reload, I can unlock it and successfully make transactions. However if I try and switch wallets, for some reason the GivethWallet instance will unlock successfully, but will not remember the state, thus I can't make a transaction.

My guess is this has to do with either the animationFrame hackery or the use of `WeakMap` in the GivethWallet itself

**Comment by satyavh** [comment]
I get this in Feathers:

```
info: error: authentication - Method: create: Challenge = jwHhrKyoFQx4xWlNDRIf
error:  NotAuthenticated: Challenge = jwHhrKyoFQx4xWlNDRIf
    at NotAuthenticated (/Users/satya/Development/feathers-giveth/node_modules/feathers-errors/lib/index.js:100:17)
    at /Users/satya/Development/feathers-giveth/node_modules/feathers-authentication/lib/hooks/authenticate.js:102:31
    at <anonymous>
info: after: authentication/challenges - Method: get
info: error: users - Method: get: No record found for id '0xd03ea8624C8C5987235048901fB614fDcA89b117'
error:  NotFound: No record found for id '0xd03ea8624C8C5987235048901fB614fDcA89b117'
    at NotFound (/Users/satya/Development/feathers-giveth/node_modules/feathers-errors/lib/index.js:121:17)
    at /Users/satya/Development/feathers-giveth/node_modules/feathers-nedb/lib/index.js:146:17
    at <anonymous>
```

And in the console
```
Error: Invalid JSON RPC response: {"id":9,"jsonrpc":"2.0"}
    at Object.InvalidResponse (http://localhost:3010/static/js/bundle.js:183563:16)
    at http://localhost:3010/static/js/bundle.js:193884:36
    at http://localhost:3010/static/js/bundle.js:169471:9
    at http://localhost:3010/static/js/bundle.js:10344:16
```

Is Feathers actually (re-)authenticated after changing wallet?

There are more things not going so smooth in the authentication and changing wallets. Can't really get my finger on it...feels like race conditions

**Comment by perissology** [comment]
this is still an issue.

read the op for how to reproduce

**Comment by perissology** [comment]
This is no longer an issue. I believe it was fixed in a web3 pr dealing w/ shared state.
