### ISSUE TITLE
Not to show disburse button in cancelled milestone. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2105]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/386167e5-cbc2-40a3-995a-3c4b73fba8b8)

**Comment by aminlatifi** [comment]
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
It's ok, 
I dont see the disburse/collect button

![Screen Shot 1400-02-27 at 15.23.59.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/1b9339cb-7db2-4792-87ca-c1105e24e69b)

![Screen Shot 1400-02-27 at 15.25.55.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/b00f9e3a-4ff5-4538-8962-3d696b3418e7)
