### ISSUE TITLE
Implement new designs: gas paid info and related alerts

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2108]
Related to : #2021 and ##2049

Alert:
https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4967%3A0
https://lottiefiles.com/5527-alert-notification-character

Public gas information: 
https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4961%3A0

**Comment by aminlatifi** [comment]
> Related to : #2021 and ##2049
> 
> Alert:
> https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4967%3A0
> https://lottiefiles.com/5527-alert-notification-character
> 
> Public gas information:
> https://www.figma.com/file/SuQbqtNjtRNrlYGAXijaMI/Giveth-TRACE?node-id=4961%3A0

So beautiful, thanks @markoprljic
