### ISSUE TITLE
Set up new better Server for Trace

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2110]
Before Server Upgrade:
- [x] Prepare Spec 
- [x] Set up accounts

After Server Upgrade:
- [x] Install Redis
- [x] Install NgineX and config
- [x] Review Ci/CD (netlify / githubAction)
- [x] Deploy

**Comment by geleeroyale** [comment]
I need more details to tackle this issue please :)

**Comment by MoeNick** [comment]
@aminlatifi @mohammadranjbarz can u please provide more information for Kay?

**Comment by mohammadranjbarz** [comment]
@geleeroyale 
Could you set DNS for new server, I'll send the IP and domain in discord DM for you

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Now the trace.giveth.io backend is on azure service,
if it has no problem you can put this to DONE

**Comment by MoeNick** [comment]
Wow... thank you guys 🤩
