### ISSUE TITLE
Lots of tests under DAC on the home page

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-dapp#2116]
https://develop.giveth.io/
Is this page live? Doesn't look professional with all the tests. Maybe we can shift them down or hide them from public view? I'm not sure if I'm seeing this right now because they were just pushed or if it's been there for a while.

**Comment by MoeNick** [comment]
> https://develop.giveth.io/
> Is this page live? Doesn't look professional with all the tests. Maybe we can shift them down or hide them from public view? I'm not sure if I'm seeing this right now because they were just pushed or if it's been there for a while.

Thanks for the feed back @ForestSoleil , where did you find the link or the address? It's our testing environment, should bot be find on Google etc.
