### ISSUE TITLE
I did a bunch of network and account switching and then got locked out of Giveth again

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2128]
![Screen Shot 2021-05-05 at 8 56 20 PM](https://user-images.githubusercontent.com/14945613/117239862-d8dd2680-ae2f-11eb-959c-e5f0e9a5ad06.png)

**Comment by aminlatifi** [comment]
@GriffGreen I tried to reproduce this by changing a lot to different networks and accounts, but couldn't see this issue. Are you sure the cause was that? sometimes connection issues happens and not related to user activity.
Would you please send us dev tools log (F12 -> console) next time?
