### ISSUE TITLE
Cant upload photo in new forms ( for example creating campaign)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2132]
After clicking on upload photo and selecting photo nothing happened, you can check this on develop

**Comment by mohammadranjbarz** [comment]
<img width="1440" alt="Screen Shot 1400-02-19 at 19 03 38" src="https://user-images.githubusercontent.com/9850545/117576386-0c070a80-b0fb-11eb-9d4d-19a78d63f63a.png">

**Comment by aminlatifi** [comment]
#2129

**Comment by MoeNick** [comment]
> @MoeNick Please test image uploading in all kind of projects,
> Also the issue mentioned below should works now
> [#2089 (comment)](https://github.com/Giveth/giveth-dapp/issues/2089#issuecomment-833491480)

Are sureabout the 2089 related to this?

**Comment by aminlatifi** [comment]
> > @MoeNick Please test image uploading in all kind of projects,
> > Also the issue mentioned below should works now
> > [#2089 (comment)](https://github.com/Giveth/giveth-dapp/issues/2089#issuecomment-833491480)
> 
> Are sureabout the 2089 related to this?

No it's now, but I pushed a code with this one :(

**Comment by mohammadranjbarz** [comment]
@MoeNick 
I've tested upload photo when creating `DAC`, `Campaign`, `Milestone`
So I think we can close this issue

https://develop.giveth.io/campaign/test-upload-photo
https://develop.giveth.io/milestone/test-upload-photo
https://develop.giveth.io/dac/test-upload-photo
