### ISSUE TITLE
replace Trace in backed with feathers

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2143]

**Comment by MoeNick** [comment]
- [ ] DB Renaming

- [ ] Service renaming

- [ ] Entity Renaming

- [ ] FE URLs and Queries

**Comment by mohammadranjbarz** [comment]
@MoeNick 

We merged giveth-dapp and feathers-giveth on develop,
now you can test the develop 

( create trace, create campaign, create community, change recipient, donate, delegate, collect, ...) should be tested, because changes are a lot and maybe we have some bugs

**Comment by MoeNick** [comment]
👌🙏
