### ISSUE TITLE
Show usdValue of donation amount in donate/delegate menu

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2152]
I think it's cool to show the usd value of the amount, it makes more sense for user to know how much he/she is donating

**Comment by MoeNick** [comment]
@markoprljic what do you think?
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c240da8f-b1b3-47e3-9dd0-dd14a652eda9)

**Comment by markoprljic** [comment]
Yes

**Comment by mohammadranjbarz** [comment]
@MoeNick 
I think maybe it's better to assign this issue to @RamRamez  or @MohammadPCh

**Comment by RamRamez** [comment]
These are done in PR #2447 (For UAT test):
1. Show usd Value of amount in donate, delegate and delegate multiple modal
2. Remove unused scss files
3. Make donate, delegate and delegate multiple modal responsive
