### ISSUE TITLE
"Change recipient" bug?

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapp#2156]
Hi! I tried to "change recipient" to collect for my Milestone, and something went wrong. I received an "Oh no!" message without any explanation. Can you please help? Thank you!

**Comment by MoeNick** [comment]
Amin jan pls take a look. @aminlatifi

**Comment by GriffGreen** [comment]
https://beta.giveth.io/milestone/katy-onboarding-coordinator-2

**Comment by danelsuga** [comment]
It's all good, I think! Thank you for the help and explanation, @GriffGreen!

**Comment by danelsuga** [comment]
Hi. I'm reopening this issue because the xDAI for the trace was never paid out after I changed recipients. Maybe I still need to wait? But this was a couple weeks ago already. Thanks for the help. @GriffGreen

**Comment by MoeNick** [comment]
@danelsuga in status update click on view transaction in last update, and you'll see how its gone to this wallet: 0x30f938fed5de6e06a9a7cd2ac3517131c317b1e7

**Comment by danelsuga** [comment]
Hi @MoeNick and thanks. I'm sorry, but I'm still confused. That's not my wallet. Does that mean I still wait until it goes through to mine? Thanks for the help.

**Comment by danelsuga** [comment]
Hi @MoeNick and thanks. Oh dear, I see it now. Thank you!
