### ISSUE TITLE
Edit Trace: pic size get back to their original size. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2167]
I resize a pic in body, when go back to edit mode, it get back to it\s original size. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/92a55f7a-d363-4274-9f0b-462424b2fd89)

**Comment by aminlatifi** [comment]
@MoeNick Please test all kind of traces

**Comment by MoeNick** [comment]
Passed on payments - Brave
Not Passed on expences. Brave & Chrome
