### ISSUE TITLE
wrong error - edit campaign on a wrong network

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2170]
Brave: Im on ropsten, trying to make edit milestone. instead of wrong network I get this: 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4094bf5b-7dc3-4356-be57-0a3956c078e3)

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/120935766-8a86a600-c6c1-11eb-8a00-329bea483948.png)

working fine now - testing on develop w brave
