### ISSUE TITLE
initial donation amount in slider differ from one token to another

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2172]
Video sent to Ramin can't uplad here.

**Comment by MoeNick** [comment]
Let's make all default amount to zero,

**Comment by divine-comedian** [comment]
I'm not sure how to test this! I need more clarification!

**Comment by mohammadranjbarz** [comment]
> I'm not sure how to test this! I need more clarification!

When you wanted to donate and dialogue was opening for `ETH` token the default amount was `1` but for other tokens it was zero, now we changed the default amount to  be zero for all tokens
