### ISSUE TITLE
Content for Tweet this in Gas payment info. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2185]
@laurenluz @WhyldWanderer 

Can you please help us on the content for tweet this option.
We gonna let the user know how much gas we paid for them. these are the designs:

![116002365-b2321b00-a5f9-11eb-8d7e-8a339fe6f8b9.jpg](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/7ef9d918-a345-4df6-9699-e589b02977e5)
![116002381-c544eb00-a5f9-11eb-887b-1ae6510a8a54.jpg](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e58e86d2-0058-41e5-8656-901e79debd96)
![116002495-5025e580-a5fa-11eb-8b6f-e22e90971844.jpg](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/52b52ca1-1d11-4505-8040-8e18609bd634)

and this is tweeter API: 
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

We may need: text, URL, hashtag.

**Comment by laurenluz** [comment]
How about:

Wow! To date, Giveth has covered <AmountofGasPaidforUser> USD in gas fees for me so I could withdraw donated funds via Giveth TRACE 👀 Try it out for yourself: https://beta.giveth.io/
#blockchain4good

@MoeNick - what do you think? too informal?

Could also try:

Giveth pays the gas fees for withdrawing funds via Giveth TRACE so the users don't have to. To date, Giveth has covered <AmountofGasPaidforUser> USD for me alone! Try it out for yourself: https://beta.giveth.io/
#blockchain4good

**Comment by RamRamez** [comment]
@laurenluz The "Tweet this" button is designed to be in trace and campaign pages, so "Giveth has covered x USD for me alone" is not gonna be an exact sentence.

**Comment by laurenluz** [comment]
What about simply...

Wow! To date, Giveth has covered USD in gas fees for me to cover transactions on Giveth TRACE 👀 Try it out for yourself: https://beta.giveth.io/
#blockchain4good
