### ISSUE TITLE
Can't see the DApp with Brave again

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2187]
![Screen Shot 2021-05-18 at 5 38 49 PM](https://user-images.githubusercontent.com/14945613/118740139-661a7500-b84b-11eb-9c11-5478b6bc5cf4.png)

**Comment by GriffGreen** [comment]
OMG!! ITS JUST NOT ME!! :-D

<img width="1050" alt="Screen Shot 2021-05-18 at 7 34 41 PM" src="https://user-images.githubusercontent.com/14945613/118748162-a71a8580-b85b-11eb-93fe-48b18fd04519.png">

This happened to Dan from the Commons Stack!

**Comment by MoeNick** [comment]
@aminlatifi would u pls tale a look?

**Comment by aminlatifi** [comment]
@GriffGreen Please send a screenshot from devtools console

**Comment by aminlatifi** [comment]
> @GriffGreen Can send here a screenshot from devtools console

What's your brave version?
