### ISSUE TITLE
Email get messy after I cancel the trace, 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2190]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/71dd0033-1ba4-46f9-88ff-96b3ce5bf3e2)

**Comment by MoeNick** [comment]
@MohammadPCh pls talk with amin about it

**Comment by mohammadranjbarz** [comment]
@MoeNick 

please test it, it's deployed now

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/120937379-5c599400-c6ca-11eb-96f8-ca146c077364.png)

it looks similar @mohammadranjbarz ... what was supposed to have changed? I think the wording is fine but the quotation marks " are awkward and I would suggest to remove them

**Comment by MoeNick** [comment]
> ![image](https://user-images.githubusercontent.com/75490971/120937379-5c599400-c6ca-11eb-96f8-ca146c077364.png)
> 
> it looks similar @mohammadranjbarz ... what was supposed to have changed? I think the wording is fine but the quotation marks " are awkward and I would suggest to remove them

Test scenario: Attach a big pic or video in comments whilst trying to cancel, reject or approve or make complete the: traces, delegations, campaigns.... and see what will happen to the email.
Besides, thanks for quotation problem you reported, shall we totally move it ? shouldn't it shows sense of quotation? @laurenluz

**Comment by laurenluz** [comment]
I understand - thanks for the test case scenario!

As for the quotation, it should have two quotation marks, i.e.

> " I don't like flowers "

or

Or if not, simply in bold and italics:

> _**I don't like flowers**_

I think either option is fine, whatever is easier to format... but as it is with just one ' " ', it doesn't make sense

**Comment by MoeNick** [comment]
@mohammadranjbarz or @MohammadPCh jan
would u please remove " (double quotation mark) ?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz or @MohammadPCh jan
> would u please remove " (double quotation mark) ?

Sure, I'll do it now
