### ISSUE TITLE
Change wording of 'Insufficient Balance' pop-up

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapp#2204]
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/b61f5dbb-4b24-4b9f-833f-340c5a267768)

Current text: "Be patient, you need at least 0.01 Rinkeby ETH in your wallet to take actions on the Giveth DApp, we are sending some to you now."

Suggested change: Be patient, you need at least 0.01 Rinkeby ETH in your wallet before you can interact with the Giveth DApp, We are sending some to you now!"

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/120937795-b196a500-c6cc-11eb-83b4-9e89d639b196.png)

the text has not yet been updated

**Comment by divine-comedian** [comment]
modal has been updated! 

![image](https://user-images.githubusercontent.com/67759413/121206405-6f916e80-c846-11eb-99d9-5811d1e30f53.png)
I'm sorry to be that guy though and say the proposed text has improper punctuation. 
updated:
"Be patient, you need at least 0.01 Rinkeby ETH in your wallet before you can interact with the Giveth DApp. We are sending some to you now!"

**Comment by mohammadranjbarz** [comment]
> modal has been updated!
> 
> ![image](https://user-images.githubusercontent.com/67759413/121206405-6f916e80-c846-11eb-99d9-5811d1e30f53.png)
> I'm sorry to be that guy though and say the proposed text has improper punctuation.
> updated:
> "Be patient, you need at least 0.01 Rinkeby ETH in your wallet before you can interact with the Giveth DApp. We are sending some to you now!"

Thanks dude, 
God bless your amazing eyes :))
