### ISSUE TITLE
can propose milestone, w/o being signed in

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#221]
to reproduce:

1. signin like normal
2. wait at least 24 hrs ( i think this is the jwt token expiration)
3. reload the page. ( you should see `sign in` in the top right)
4. navigate to a campaign & click `propose milestone`
5. the unlock wallet popup will appear where you can unlock your wallet and propose milestones

You should not be able to unlock your wallet w/o signing in.

**Comment by ascariandrea** [comment]
I'm gonna take care of this!

**Comment by ascariandrea** [comment]
Hi @perissology, I've tried what you described here, but I wasn't able to reproduce it.

The code seems correct: if the *jwt* token verification is successful it returns a valid user, while when no user is returned there's no *Propose milestone* button.
Are you sure it should be expired after 24 hours?

**Comment by ascariandrea** [comment]
Yep, but we're calling `feathersClient.passport.verifyJWT(token)` in `Application.jsx` which returns the payload. If the payload has no `userId` no user gets fetched. That's why I don't think it's a matter of token expiration.

**Comment by perissology** [comment]
but the payload should have a userId no?

Anyways, like I said this may have been fixed at some point. I'll try and take see if I can reproduce it soon.

Thanks for taking a look!
