### ISSUE TITLE
Tweet how much gas is paid.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2216]
#2185

**Comment by MoeNick** [comment]
https://github.com/Giveth/giveth-dapp/issues/2185

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/120937442-a6db1080-c6ca-11eb-9484-8eb1d287afbe.png)

Please update wording to...

"Giveth pays gas fees on Giveth TRACE so the users don't have to. To date, Giveth has covered 0 USD for my TRACE! See my Trace here: https://develop.giveth.io/trace/harvesting-hibiscus-flowers"

The current formatting/wording feels a little off.

**Comment by MoeNick** [comment]
@laurenluz  the problem is that trace is not always his/her trace :) So we decided to put "This Trace" or "This campaign" wording, and make it possible for everybody to tweet and say, hey look, Giveth paid n $ gas fee for this trace...
But... on the profile section, the wording is  "Gas paid for me" ... 
What do you think.

**Comment by laurenluz** [comment]
I get it. Would love to tweak the wording here a lil' bit...

"Giveth pays gas fees to collect or disperse funds donated on Giveth TRACE so the users don't have to! To date, Giveth has covered **$value** for **(this Trace)/(this Campaign)/(me)**. Check it out here: **link**"

**Comment by aminlatifi** [comment]
> I get it. Would love to tweak the wording here a lil' bit...
> 
> "Giveth pays gas fees to collect or disperse funds donated on Giveth TRACE so the users don't have to! To date, Giveth has covered **$value** for **(this Trace)/(this Campaign)/(me)**. Check it out here: **link**"

@laurenluz I guess you meant `collect or disburse` not `collect or disperse`

**Comment by laurenluz** [comment]
yes, sorry, "disburse"

**Comment by laurenluz** [comment]
I just saw this on twitter: I think there is an extra space on "so  the users..."
@mohammadranjbarz can you check?

![image](https://user-images.githubusercontent.com/75490971/121817604-a6e58e00-cc3f-11eb-9da5-678d1bec327c.png)

**Comment by RamRamez** [comment]
> I just saw this on twitter: I think there is an extra space on "so the users..."
> @mohammadranjbarz can you check?
> 
> ![image](https://user-images.githubusercontent.com/75490971/121817604-a6e58e00-cc3f-11eb-9da5-678d1bec327c.png)

Thanks @laurenluz it's fixed in PR #2277

**Comment by MoeNick** [comment]
Im just wondering why we show gas paid before the user collect the money?
