### ISSUE TITLE
make 'edit trace' and 'delete trace' buttons more noticeable

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2220]
as a user while viewing my trace I found it hard to find the buttons to edit and delete my trace, I found them eventually up in the top right corner but the text is too small and can be hard to see depending on the trace image. I suggest if we could increase the box-size, the text size/weight and add a background color to the button so it is more distinguishable on the page. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/e4004471-4656-44d6-a39f-ab529d0b9a0a)

**Comment by markoprljic** [comment]
For Trace Owner View, why not have it below the Trace title in header? They don't need the donate button, right?
Also, please note that the labels are now Edit and Delete.

![Image 2021-06-02 at 12 16 50 pm](https://user-images.githubusercontent.com/5704285/120463696-77f82e00-c39c-11eb-91e2-c7e1436df6e9.jpg)

**Comment by MoeNick** [comment]
@RamRamez is it ok for you? Dont u want t say any comments about the background stuff that was mentioned in the daily?

**Comment by RamRamez** [comment]
Thanks @markoprljic. Ghost button is a good idea.
I just want to add we have a gradient on background header to make text more clear on light background pictures.

**Comment by aminlatifi** [comment]
> Thanks @markoprljic. Ghost button is a good idea.
> I just want to add we have a gradient on background header to make text more clear on light background pictures.

@RamRamez We have dark gradient on projects header already.

**Comment by divine-comedian** [comment]
![image](https://user-images.githubusercontent.com/67759413/121239374-2a316900-c867-11eb-82b2-9960770d25dd.png)
much more noticeable! This looks great! I checked for all types of Traces and this looks to be fixed as proposed.
