### ISSUE TITLE
rich text editor doesn't display things properly

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2221]
While creating/editing my Trace on develop.giveth.io

the rich text editor is not displaying quotes at all once I save my description

- also it is impossible to make nested lists,
   - usually while making a list you can use the `tab` key to nest a bullet point like this
      - and so on...

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/7534a5a0-9fd4-4f35-b9e4-079326e6c826)

**Comment by laurenluz** [comment]
quotes and nested lists are still not working
![image](https://user-images.githubusercontent.com/75490971/120938093-739a8080-c6ce-11eb-8acb-09ec372715af.png)

**Comment by divine-comedian** [comment]
quotes and nested lists are working now! 

![image](https://user-images.githubusercontent.com/67759413/121205339-956a4380-c845-11eb-92b2-1762391d4ed7.png)
