### ISSUE TITLE
When trying to donate to Trace, get ask to switch from Rinkeby to Ropsten, then a new prompt to switch to Rinkeby

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#2222]
This has happened twice, testing on develop.giveth.io with Brave browser.

I'm initially on Rinkeby. Then I go to donate, and it asks me to switch to Ropsten. I switch to Ropsten then I suddenly get this popup asking me (incorrectly) to switch to Rinkeby

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/08f42ad4-0574-4c51-a3d2-cc6c6629547f)

**Comment by mohammadranjbarz** [comment]
@MoeNick 
I tried a lot, but I couldn't reproduce the bug, I also took screen recording

![ezgif com-gif-maker](https://user-images.githubusercontent.com/9850545/120590885-78ea9780-c450-11eb-9759-0d7a210bdaac.gif)

**Comment by laurenluz** [comment]
I can't seem to reproduce either anymore. I'll move to done, but keep an eye on it.
