### ISSUE TITLE
After donating to a trace, (while the donation is still pending) the delegation of 3% shows up as a donation to the trace, but a separate donation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#2223]
Is this working as functioned? I donated to a Trace (on develop with brave browser) and the owner enabled "delegate 3% to community"... but both parts of the donations show up as donations to the Trace, just split up.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fff2db06-f4c2-4ff5-99b8-3fd3f3433dc9)

**Comment by laurenluz** [comment]
UPDATE: after the donation transaction completed... only 1 part of the donation remained on the trace's page (as expect).

so my feedback is that perhaps we should have the pending transaction also not be displayed on the trace's page, but rather on the community's page, as expected

![image](https://user-images.githubusercontent.com/75490971/120239794-4e17fd80-c21c-11eb-9a70-230992f4c9cf.png)

**Comment by mohammadranjbarz** [comment]
@MoeNick 

For testing this, please create a trace and mark the checkbox to donate 3% to Community, then after donating to trace you will see one donation to trace (minus 3%)

**Comment by laurenluz** [comment]
it's working fine now on develop. Thanks Mohammad!

![image](https://user-images.githubusercontent.com/75490971/120846867-f46f4600-c52f-11eb-8631-e10e25885c57.png)
