### ISSUE TITLE
donation confirm graphic looks funny

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2225]
the check mark graphic seems to be overlapping the two lines, looks weird, is this intentional or a graphics error?
testing `develop.giveth`
brave browser, clean cache and cookies 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/a457a0cc-25c9-4144-be77-87fc1d186d4c)

**Comment by MoeNick** [comment]
Related #2226

**Comment by MoeNick** [comment]
We Fixed it.
