### ISSUE TITLE
TX Success modal changes.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2226]

**Comment by markoprljic** [comment]
![Image 2021-06-01 at 5 23 24 pm](https://user-images.githubusercontent.com/5704285/120353347-e6d47900-c301-11eb-9a42-b12c0072a805.jpg)

**Comment by RamRamez** [comment]
Thanks @markoprljic for the design. Is this also for tnx submitted modal?

**Comment by markoprljic** [comment]
No, only on success.

**Comment by RamRamez** [comment]
> No, only on success.

What about the delegation success modal? does it have it?

**Comment by markoprljic** [comment]
Idk. @MoeNick ?

**Comment by MoeNick** [comment]
> Idk. @MoeNick ?
Just donation modal is fine. @RamRamez thanks

**Comment by MoeNick** [comment]
Tested except not "logged in" state. 
@RamRamez  I don't have any idea how can I donate w/o being signed-in.

**Comment by MoeNick** [comment]
It works fine. thanks
