### ISSUE TITLE
"Join Our Community" leads to a 404

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#2227]
I clicked to join Mitch's community:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/50367c32-6666-46a6-96c6-4cedc2ea2f1f)

and it opened a new page that redirected me to a 404:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d9ec2762-afa6-4156-8d65-240acacdc697)

**Comment by divine-comedian** [comment]
+1  I encountered the same Issue!

**Comment by laurenluz** [comment]
tested- working fine now on develop.
