### ISSUE TITLE
Donation to community now showing up

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#2228]
I donated twice to Mitch's community, but even after the transactions went through in my wallet, they do not show up in the "funding section" of the community. In fact, there are none.

Worth noting, after my first donation it said "1 new" next to "Leaderboard" but after a page refresh, it disappeared.

Testing on develop with Brave browser

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2a366f38-046b-4da3-b2ba-dddfb69b47d5)

**Comment by aminlatifi** [comment]
@laurenluz On direct donate scenario, it takes few minutes to money be included in funding balance. It needs few steps to be completed:
1. 7 blocks be passed from the block donation is minted (Mainnet)
2. The bridge mint token in foreign network (Rinkeby)
3. 7 blocks be passed from bridge transaction
4. Feathers process the event

So, it's not possible to updated funding immediately.
@markoprljic Do you have any idea to convey that concept to user?

**Comment by markoprljic** [comment]
Show "1 New" immediately after user has donated. 
During the minting etc. show message: "Your donation is pending and will appear here after several confirmations." 
Bonus: add tooltip at the end of the message which shows pending confirmations needed.

**Comment by MoeNick** [comment]
> @laurenluz On direct donate scenario, it takes few minutes to money be included in funding balance. It needs few steps to be completed:
> 
> 1. 7 blocks be passed from the block donation is minted (Mainnet)
> 
> 2. The bridge mint token in foreign network (Rinkeby)
> 
> 3. 7 blocks be passed from bridge transaction
> 
> 4. Feathers process the event
> 
> 
> 
> So, it's not possible to updated funding immediately.
> 
> @markoprljic Do you have any idea to convey that concept to user?

Don't we have a rolling circle design in front of each donation before it got completed?

**Comment by aminlatifi** [comment]
> > @laurenluz On direct donate scenario, it takes few minutes to money be included in funding balance. It needs few steps to be completed:
> > 
> > 1. 7 blocks be passed from the block donation is minted (Mainnet)
> > 2. The bridge mint token in foreign network (Rinkeby)
> > 3. 7 blocks be passed from bridge transaction
> > 4. Feathers process the event
> > 
> > So, it's not possible to updated funding immediately.
> > @markoprljic Do you have any idea to convey that concept to user?
> 
> Don't we have a rolling circle design in front of each donation before it got completed?

We have it for Trace donation list, not Community and Campaign types

**Comment by MoeNick** [comment]
1. Fix Badge on Campaign and Community.
2. During the minting etc. show message: "Your donation is pending and will appear here after several confirmations."

**Comment by MoeNick** [comment]
@aminlatifi @RamRamez any updates?

**Comment by aminlatifi** [comment]
@RamRamez Aggregate service now includes pending donations too. Please make the front-end to be updated after donating.Also it would be cool if we change campaign fetch in ViewCampaign to subscribe mode (like trace) in order to update balance immediately after the pending donation is committed.
