### ISSUE TITLE
Donation Modal Redesign

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2233]
Related to #2181 and due to "tnx submitted" and  "tnx successful " we recently updated, seems we need a new design for donation modal. The current modal is too busy and have lots of contents, with so many actions, that makes it always have a scroll bar. We can make it more  compact. 

I think, we can see it as a  wizard: donation> submitted > successful. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/afe9ef7f-f2ee-45cd-bc50-301cfa857886)
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/f65f6650-12a6-4f4b-bbb1-9793b14b6946)

**Comment by markoprljic** [comment]
Here's the proposal for new Donation modal. Default height is 652px.

![Image 2021-06-08 at 1 04 44 pm](https://user-images.githubusercontent.com/5704285/121174644-6c07e280-c85a-11eb-981e-e937aa5722b7.jpg)

**Comment by MoeNick** [comment]
@markoprljic 

In our currant design we have: 1-  unlock & donate button, 2- infinite unlock and donate 3-Buy/Exchange
 ("Remove Access" appears when the access to a certain crypto is already granted)

the question is, what we should do about "unlocking process: in this design, ideas:

1- we will change the text to "Unlock and donate" - after clicking that button:  this modal disappear, pending transaction modal appears, and two transactions go automatically one after another. 

2- we will change the text to "Approve" - after clicking that button:  this modal disappear, pending transaction modal appear for unlocking ,  this modal shows up BUT the text ob button will change to "Donate" user click on donate,  this modal disappears and pending transaction modal appears .

3- We will have 3 button: Approve - Donate - Buy/Exchange , Donate is disabled in 1st step. after clicking on approve button:  this modal disappear, pending transaction modal appear for unlocking ,  this modal shows up BUT the "approve"  button  will show as "approved" and get disabled, and  "Donate" button is enabled, user clicks on donate,  this modal disappear and pending transaction modal appears .


Note:
1- in all above scenario we omit "infinity access" if the user has granted the access before we will change the text or disable Approve button.
2- We should think about removal access process in he profile or somewhere else.

**Comment by markoprljic** [comment]
Option 2 BUT without closing this modal, user stays on the same modal open and waits till the transaction has been confirmed. 
Include a loader in the button as well. When user clicks on Approve and confirms with MM then button label change to [loader] Pending

**Comment by MoeNick** [comment]
@RamRamez @MohammadPCh 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4a8800b0-f7ec-43b0-8002-
d36842f7ffa4)

**Comment by RamRamez** [comment]
RP #2404 
1. Donation Modal Redesign
2. Unlocking Process Modal
3. Fix not showing token balance on donate refresh
4. Optimizing DonateButtonModal.jsx
