### ISSUE TITLE
Fix email content - delegate from community to camp. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2237]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/6096daaf-d7da-4108-87bf-26fc039f6176)

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @MoeNick 

I think the email content is ok, 
The email says that The `Community` requested a delegation from the donation that you donated to `Community` and it's logically ok, but if it's not clear, I think @laurenluz  can help us to write clear message

**Comment by laurenluz** [comment]
ahh I noticed this too and made another issue without seeing this one

https://github.com/Giveth/giveth-dapp/issues/2246

I suggest we change it to:

"The Community [community name] has proposed a delegation of [donation amount] to the [campaign or trace] [campaign or trace name].

This is a proposed delegation of funds that your sent to the Community [Community name]. You have until [date] to approve...."
