### ISSUE TITLE
When accepting a Proposed Milestone, the list of other proposed milestones disappear

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#224]
These photos pretty much show what happens:
When Managing "My Milestones"
<img width="1234" alt="screen shot 2018-01-13 at 1 04 31 am" src="https://user-images.githubusercontent.com/14945613/34915014-b193547e-f950-11e7-82d6-12fa1a6a20c5.png">

And Accepting a proposed Milestone:
<img width="1264" alt="screen shot 2018-01-13 at 1 04 41 am" src="https://user-images.githubusercontent.com/14945613/34915015-b1cd878e-f950-11e7-93c3-18abe6f267b5.png">

All of the proposed milestones disappear:
<img width="1308" alt="screen shot 2018-01-13 at 1 04 51 am" src="https://user-images.githubusercontent.com/14945613/34915018-b2a55844-f950-11e7-990b-bb0f2f0cba34.png">

Then i have to hit back and then go forward and they will reappear, so i can click to accept the next proposed milestone.

**Comment by vojtechsimetka** [comment]
Fixed in ddb9ca89d552904c65db112237dc98d3d05a814c
