### ISSUE TITLE
Error on creating a Campaign

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2244]
Ramin has created this campaign https://develop.giveth.io/campaign/test-campaign-to-cancel-2 
But the event processing in feathers is not successful and corresponding event entity in db stays in `Processing` state.

{transactionHash:"0xc121e18c73fa1e8a5546f4cf111f8feed18d16408af817ecce519638b074ef85"}

Here are two questions:
1. Why processing the event is failed
2. Why the corresponding event entity status is not `Failed` as the event processing has thrown exception

**Comment by MoeNick** [comment]
@mohammadranjbarz appreciate if you set sprint label after you have just started working on this.

**Comment by mohammadranjbarz** [comment]
The error occured because using `Infura` service for getting events from blockchain, after changing that to `Giveth` node URL , the problem has been fixed
