### ISSUE TITLE
Incorrect wording for delegation from community to campaign (it calls the campaign a Trace)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#2245]
Testing on develop w brave. Wanted to "reject" a proposed delegation from my community to my campaign... the text popup says the campaign is a trace

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2485ce33-6c0d-4e69-8d84-ef270801a3f4)

**Comment by MoeNick** [comment]
Thanks @laurenluz 
@mohammadranjbarz would you pls take a look?

**Comment by mohammadranjbarz** [comment]
> Thanks @laurenluz
> @mohammadranjbarz would you pls take a look?

Sure @MoeNick
