### ISSUE TITLE
Email to Giver when a delegation is proposed - wording is strange

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapp#2246]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d7f90578-43b2-4b82-9acc-82bca554961c)

This is confusing wording... I suggest...

"The Community [community name] has proposed a delegation of [donation amount] to the [campaign or trace] [campaign or trace name].

This is a proposed delegation of funds that your sent to the Community [Community name]. You have until [date] to approve...."

**Comment by MoeNick** [comment]
@laurenluz it's related to: #2237
