### ISSUE TITLE
Donation API to GivBack Project to give-tokens manually

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2253]
API should have:

Result:
GiverAddress, GiverID,

**Comment by mohammadranjbarz** [comment]
@MoeNick As I and @GriffGreen Talked we conclude we need these in this story:

* Somewhere we need to have in the backend whether a project is verified or not
So ideally we would be able to pull the direct donations (not delegations or anything) for all projects
And then filter on if they are verified or not
* Projects will need to apply to be verified ( So there should be a boolean somewhere and Set the all to false for now)

And then you can send out the data that has
1. the address that donated, 
2. the currency,
3. the usd value of the currency in that moment, 
4. what they donated to (projectId), 
5.  whether that project is verified

**Comment by mohammadranjbarz** [comment]
@MoeNick 

Getting All projects donations:
https://feathers.develop.giveth.io/verifiedProjectsGiversReport?fromDate=2018/05/01-00:00:00&toDate=2021/06/14-00:00:00&allProjects=true

Getting verified projects donations:
https://feathers.develop.giveth.io/verifiedProjectsGiversReport?fromDate=2018/05/01-00:00:00&toDate=2021/06/14-00:00:00

**Comment by MoeNick** [comment]
Hi @mendesfabio 
We need your approve to make it done man.

**Comment by mendesfabio** [comment]
hey guys! the API is amazing, it has all the required information, as I previously aligned with @mohammadranjbarz. 

one question: do we only have one verified project on TRACE?

**Comment by mohammadranjbarz** [comment]
> hey guys! the API is amazing, it has all the required information, as I previously aligned with @mohammadranjbarz.
> 
> one question: do we only have one verified project on TRACE?

Hi Fabio, happy to hear that
yes I just made a campaign verified in server to test it
