### ISSUE TITLE
Infinite unlock tooltip not showing completely

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapp#2254]
![image.png](https://images.zenhubusercontent.com/6040fd6c6873c665b22c45b3/3c71e3c2-9ade-4439-bfc5-9479065078b4)

**Comment by MoeNick** [comment]
@RamRamez do we still have this tooltip in our new design?

**Comment by RamRamez** [comment]
> @RamRamez do we still have this tooltip in our new design?

No we don't have
