### ISSUE TITLE
'your delegations' menu options are missing and the text is mispelled.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2256]
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/1f29d7a1-6cb0-4a5b-85b7-6e6bb1afa7a0)

When I go to the my delegations page when in the DAC owner account I have the option to delegate funds that have been delegated to me. I have plenty of options of where to delegate my trace but there are no options in the campaigns menu for me to delegate... Also the text over the hover tooltip should read:

"Choose a Campaign or a Trace to delegate your funds to."

**Comment by MoeNick** [comment]
Tested. Good job guys.
