### ISSUE TITLE
Hide milestones for a couple months please

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2258]
https://beta.giveth.io/milestone/chuy-may-tec-comms 

This is one that slipped thru :-( but there were so many that i caught and asked people to remake milestones traces into payment traces. Chuy ended up not getting paid cause he thought he had to make a milestone.

People still say "make a milestone" and then they really need to make a payment trace... 

This has caused a lot of problems and no one uses this feature right now... can we please remove the milestone option for the next couple months to avoid this confusion

**Comment by MoeNick** [comment]
@aminlatifi jan

Will we take it I assign it to @mohammadranjbarz ?

**Comment by GriffGreen** [comment]
Wow!! Amazing work @mohammadranjbarz !
