### ISSUE TITLE
Weird display issue on DAC page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#226]
https://alpha.giveth.io/dacs/Tt2iCd06KpFRUaFr

picture will speak for itself

Google Chrome is up to date
Version 63.0.3239.132 (Official Build) (64-bit)
on a mac

<img width="1096" alt="screen shot 2018-01-15 at 1 19 50 pm" src="https://user-images.githubusercontent.com/14945613/34929668-d6c341da-f9f7-11e7-9526-66650c591cee.png">

**Comment by emazurek** [comment]
I can fix the bug, but besides that, this part of the UI seems awfully squeezed, especially when scaling the screen down. How would you suggest I proceed? (already read contributor wiki, and signed up as contributor)

![screen shot 2018-02-06 at 12 25 19 pm](https://user-images.githubusercontent.com/5423313/35873820-da38c856-0b38-11e8-9327-ccfb38aa6c05.png)

**Comment by vojtechsimetka** [comment]
Hi @emazurek,

Thank you for your help, we really appreciate it! If you need any help from my side please let me know.

> Shall I open an additional issue for this?

This is just one of the visual issues there are. Generally if it does not take a lot of your time, go for it. However, we are preparing a redesign of the DAC and Campaign page so be mindful that such issues will be solved there and it will be completely reworked (will be a bit more like Netflix for example).

**Comment by geleeroyale** [comment]
Has been addressed in:

https://github.com/Giveth/giveth-dapp/pull/278
