### ISSUE TITLE
Remove the Donate button from the Commons Stack Association

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2265]
https://beta.giveth.io/campaign/commons-stack-association

For various reasons...

@kristoferlund

**Comment by aminlatifi** [comment]
Implemented for this campaign https://develop.giveth.io/campaign/campaign-with-disabled-donation

**Comment by aminlatifi** [comment]
Implemented for this campaign https://develop.giveth.io/campaign/campaign-with-disabled-donation
