### ISSUE TITLE
Semantics: Giveth is in alpha, but all over the site it says beta

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#227]
Change all mentions of Beta to alpha:

https://github.com/Giveth/giveth-dapp/search?utf8=%E2%9C%93&q=beta&type=

the one that made me notice is the one on the milestone page: The Milestone Reviewer is automatically assigned while Giveth is in beta.

**Comment by Alonski** [comment]
Fixed this :smile:
