### ISSUE TITLE
update trace description text 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2273]
following discussion in Giveth TRACE dev channel we should update this text to describe traces a bit more and explain what each type of trace is for.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/7775aaee-f8d7-49a9-8810-87f8b6fe54fc)

**Comment by divine-comedian** [comment]
Suggest: 
## Traces
Represent requests for funding from a Campaign or its members. Traces are the foundation of the Giveth TRACE DApp. There are four different types of Traces that can exist: **Milestones**, **Bounties**, **Payments** and **Expenses**.

@markoprljic  @MoeNick

**Comment by MoeNick** [comment]
Thanks @divine-comedian . can u go forward about this and all wording issues you see with your PR?

**Comment by divine-comedian** [comment]
yes, just need validation for the text and I will include it in my PR

**Comment by markoprljic** [comment]
Cut the text to: Requests for funding from a Campaign or its members.

**Comment by divine-comedian** [comment]
we shouldn't mention there's different types of traces? It's not mentioned anywhere unless you're making a trace yourself.

**Comment by markoprljic** [comment]
Below title should just be short description, not a full explanation. This is enough.
