### ISSUE TITLE
 trace.giveth.io SSl problem 

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2281]
trace.giveth.io showing warning, but other sub domains seems ok

![Screen Shot 1400-03-24 at 22.02.20.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/429d29a1-25a2-4c4b-a8c6-9b15add8b216)![Screen Shot 1400-03-24 at 22.04.13.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/0909d28a-68ec-48d2-ae18-1c96eac94569)

**Comment by mohammadranjbarz** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=https://trace.giveth.io

[
<img width="1114" alt="Screen Shot 1400-03-24 at 22 08 53" src="https://user-images.githubusercontent.com/9850545/121934975-2917a480-cd5d-11eb-8c92-73c05843f2b1.png">
](url)

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/122006642-4fc0f400-cdcc-11eb-8567-83e41341df8f.png)
Fixed

**Comment by aminlatifi** [comment]
Thanks @mohammadranjbarz for reporting
