### ISSUE TITLE
formatting issue when editing

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#229]
when you edit a milestone/campaign etc, it screws up formatting: all line spaces disappear and everything is pasted together.

reproduce:

- edit any milestone
- you see spaces between paragraphs disappear

**Comment by GriffGreen** [comment]
this is related to https://github.com/Giveth/giveth-dapp/issues/238 and https://github.com/Giveth/giveth-dapp/issues/294

Bounty for 0.1 ETH from the Gov Campaign.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8d8becbb5f24e6b1b390a73fd6500beabcd9eea141bd3343da34a55667cfbd8a](https://etherscan.io/tx/0x8d8becbb5f24e6b1b390a73fd6500beabcd9eea141bd3343da34a55667cfbd8a)

**Comment by ovx** [comment]
Issue fixed in https://github.com/Giveth/feathers-giveth/pull/91 (its related to `sanitizeHtml` in the feathers server).

**Comment by vojtechsimetka** [comment]
Thanks @ovx !

This is our first openbounty so I will coordinate with @geleeroyale to figure out how we can award the bounty to you.
