### ISSUE TITLE
Co-owner of Campaign cannot delegate funds to Traces

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#2291]
Willy made me co-owner of the Giveth 2 Campaign so I can make the PAN delegations!
But the Campaign does not show up for me to delegate funds from within the Trace:
![image](https://user-images.githubusercontent.com/39466970/123105778-edc84600-d3ec-11eb-9a9a-51dac1663626.png)

Also from within the Campaign I have no ability to delegate from, only to:
![image](https://user-images.githubusercontent.com/39466970/123105952-12242280-d3ed-11eb-80e3-6324f9f84eb8.png)

**Comment by aminlatifi** [comment]
@Danibelle Coowner cannot delegate money, just owner can

**Comment by Danibelle** [comment]
OK  -- so proposal is for MoeNick to be the Giveth 2 Campaign Manager..
There are PAN payouts that need to get out quickly - maybe we make me the Manager first to get these outstanding payments done and document the process, then hand off to MoeNick for July payments.

**Comment by Danibelle** [comment]
Let's change the owner to me from Willy so I can make the payouts please :)

**Comment by aminlatifi** [comment]
> Let's change the owner to me from Willy so I can make the payouts please :)

Changing ownership of a campaign needs few transaction to be made by current owner. So @willyogo and I should have a hack session on this. I will ping Willy.

**Comment by Danibelle** [comment]
THank you Amin!  This is pretty high priority as we need to get the PAN Payouts made with time in the GitCoin Grant Round..

Here is the [spreadsheet of PAN distro](https://docs.google.com/spreadsheets/d/1v0PCi7A1Hb8zppz9Yu-Gx7AQTT6ycUsV1V5MGsdN70g/edit#gid=0) FYI.

**Comment by aminlatifi** [comment]
@Danibelle We made you owner of Giveth-2
Just confirm it's working by doing some delegation.

**Comment by Danibelle** [comment]
Spelling error on this window:
(Etherscan, not Etherescan)

![image](https://user-images.githubusercontent.com/39466970/123304399-c5674700-d4d3-11eb-95ec-48908d1ceb10.png)

**Comment by Danibelle** [comment]
All is Swell!!
