### ISSUE TITLE
Milestone instead of Trace shown in "trace status update" on live. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2293]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e12e60b0-4c06-4e7f-afae-a9d0c131277b)

**Comment by mohammadranjbarz** [comment]
![Screen Shot 1400-04-06 at 08.59.56.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/a154775b-b301-4f5c-846e-974557e25759)

https://trace.giveth.io/trace/mohammad-ranjbar-reward-nov-08-nov-21

@MoeNick 
it deployed on `UAT` and `Production`
