### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2299]
- [x] (Description)

- [x] Backend 

- [x] External endpoints
Crypto Compare
Coin gecko
Gasnow
Eth nodes
Infura
IPFS

- [ ] Discord notif.

**Comment by mohammadranjbarz** [comment]
@MoeNick I suggest create another issue for setup self hosted sentry and integration between sentry and discord, then we should ask for Kay's help
