### ISSUE TITLE
feather monitoring

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2301]

**Comment by mohammadranjbarz** [comment]
@MoeNick 
could you say what scenarios you want to test?
based on test scenario maybe it will need some impelmentaion

**Comment by MoeNick** [comment]
Thanks @mohammadranjbarz for the test:

Test Scenario:
1- MongoDB pass changed in config manually to occur a lost DB connection. 
2- Restart DB
3- We got an alert for a loss connection on Sentry. 

https://sentry.io/organizations/giveth-ds/issues/2506479187/events/ab55f4318e704cbeac010f2a09b341c4/?project=5853180

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/22e0d288-cc43-4ce7-bfab-7e0a4ed35a40)
