### ISSUE TITLE
Not able to submit scholarship milestone for Michel Bauwens

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#2312]
Here is the error message.  My wallet is connected to Rinkeby & unlocked, not sure what else the problem might be?

Something went wrong with the Trace creation. Is your wallet unlocked? https://rinkeby.etherscan.io/tx/undefined => { "hook": { "type": "before", "method": "create", "path": "traces", "params": { "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOiIweDc3ODU0OUViMjkyQUM5OEE5NmEwNUUxMjI5NjdmMjJlRkEwMDM3MDciLCJpYXQiOjE2MjQ4OTE2NzgsImV4cCI6MTYyNDk3ODA3OCwiYXVkIjoiaHR0cHM6Ly9mZWF0aGVycy5naXZldGguaW8iLCJpc3MiOiJmZWF0aGVycyIsInN1YiI6IjB4Nzc4NTQ5RWIyOTJBQzk4QTk2YTA1RTEyMjk2N2YyMmVGQTAwMzcwNyIsImp0aSI6IjkyZGI2ZTk1LTdhNTktNDUxOS05MDIwLTg0M2U2NmU4MDA2MCJ9.f5_sHYYM8aZ1VnnMHMOrmhXc1qsby_2YDmSNvNQE0qM", "user": { "address": "0x778549Eb292AC98A96a05E122967f22eFA003707", "createdAt": "2018-11-27T20:41:06.237Z", "updatedAt": "2021-02-21T16:59:00.869Z", "avatar": "/ipfs/QmawiW7BCj4sou4M9XQ2PsSoBb93dDrQeKaXDVcUi66es3", "email": "jeffemmett@gmail.com", "giverId": 2414, "linkedin": "", "name": "Jeff", "commitTime": 259200, "url": "/ipfs/QmfUatPjCF5ouRTpS6CFttxWR4osuZPiJXiEJ616uRvQaT", "isDelegator": false, "isProjectOwner": false, "isReviewer": true, "gasPaidUsdValue": 748.9200000000001 }, "info": { "userId": "0x778549Eb292AC98A96a05E122967f22eFA003707" }, "authentication": { "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJ1c2VySWQiOiIweDc3ODU0OUViMjkyQUM5OEE5NmEwNUUxMjI5NjdmMjJlRkEwMDM3MDciLCJpYXQiOjE2MjQ4OTE2NzgsImV4cCI6MTYyNDk3ODA3OCwiYXVkIjoiaHR0cHM6Ly9mZWF0aGVycy5naXZldGguaW8iLCJpc3MiOiJmZWF0aGVycyIsInN1YiI6IjB4Nzc4NTQ5RWIyOTJBQzk4QTk2YTA1RTEyMjk2N2YyMmVGQTAwMzcwNyIsImp0aSI6IjkyZGI2ZTk1LTdhNTktNDUxOS05MDIwLTg0M2U2NmU4MDA2MCJ9.f5_sHYYM8aZ1VnnMHMOrmhXc1qsby_2YDmSNvNQE0qM", "payload": { "userId": "0x778549Eb292AC98A96a05E122967f22eFA003707", "iat": 1624891678, "exp": 1624978078, "aud": "https://feathers.giveth.io", "iss": "feathers", "sub": "0x778549Eb292AC98A96a05E122967f22eFA003707", "jti": "92db6e95-7a59-4519-9020-843e66e80060" } } }, "data": { "title": "TS Scholarship: Michel Bauwens", "description": "Expense items describes what has been paid or should be paid", "image": "/img/expenseProject.png", "ownerAddress": "0x778549Eb292AC98A96a05E122967f22eFA003707", "reviewerAddress": "0x0000000000000000000000000000000000000000", "communityId": 0, "recipientAddress": "0x778549Eb292AC98A96a05E122967f22eFA003707", "campaignId": "5feb2ca1dae3134bd0166dd6", "status": "Proposed", "items": [ { "date": "2021-06-27T00:00:00.000Z", "description": "<p>I have sent 450 DAI to Michel Bauwens, and will be working with him this week to finalize his membership activation in the Trusted Seed.</p>", "image": "/ipfs/QmZtBntUduFm7XXSbG5CJByBP5qP9UnYAC9tv13315ckqu", "selectedFiatType": "DAI", "fiatAmount": "450", "wei": "450000000000000000000", "conversionRate": 1, "conversionRateTimestamp": "2021-06-27T00:00:00.000Z" } ], "date": "2021-06-27T00:00:00.000Z", "pluginAddress": "0x0000000000000000000000000000000000000000", "token": { "name": "DAI", "address": "0x6b175474e89094c44da98b954eedeac495271d0f", "foreignAddress": "0x05A075B296995AdCaEC7c1dE0E52271a4Cf6DEb8", "symbol": "DAI", "rateEqSymbol": "USD", "coingeckoId": "dai", "decimals": 3 }, "type": "BridgedMilestone", "formType": "expense", "maxAmount": "450000000000000000000", "fiatAmount": "0" } } }

**Comment by aminlatifi** [comment]
It happens on creating expense trace
Amount is 450 DAI and token is DAI
```
0|feathers | 2021-06-28 17:43: error: Hook error: while converting number to string, invalid number value 'NaN', should be a number matching (^-?[0-9.]+). Error: while converting number to string, invalid number value 'NaN', should be a number matching (^-?[0-9.]+).
0|feathers | 2021-06-28 17:43:     at numberToString (/home/deploy/feathers-giveth-beta/node_modules/ethjs-unit/lib/index.js:61:13)
0|feathers | 2021-06-28 17:43:     at Object.toWei (/home/deploy/feathers-giveth-beta/node_modules/ethjs-unit/lib/index.js:114:15)
0|feathers | 2021-06-28 17:43:     at Object.toWei (/home/deploy/feathers-giveth-beta/node_modules/web3/node_modules/web3-utils/lib/index.js:251:75)
0|feathers | 2021-06-28 17:43:     at calculateCorrectEther (/home/deploy/feathers-giveth-beta/src/services/traces/checkConversionRates.js:56:21)
0|feathers | 2021-06-28 17:43:     at app.service.find.then.conversionRate (/home/deploy/feathers-giveth-beta/src/services/traces/checkConversionRates.js:79:11)
0|feathers | 2021-06-28 17:43:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mohammadranjbarz** [comment]
@MoeNick 
@aminlatifi 

it's ok now, I've created this trace (with expense form) in develop

https://develop.giveth.io/trace/test-issue-2312-giveth-dapp

**Comment by aminlatifi** [comment]
I created on trace.giveth.io and it's OK. Thanks @Jeff-Emmett for reporting
