### ISSUE TITLE
Add Freshelle to the Registry that will allow her to be the Co-owner of many Campaigns

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2316]
Freshelle is going to help CS and Giveth do accounting and payment management on Giveth... so i would like to make her co-owner of these campaings

her address is 0x38f80f8f76B1C44B2beeFB63bb561F570fb6ddB6

<img width="864" alt="Screen Shot 2021-06-29 at 1 28 39 PM" src="https://user-images.githubusercontent.com/14945613/123790027-25982780-d8de-11eb-849d-f0123ac838e1.png">

**Comment by aminlatifi** [comment]
@GriffGreen Can you ask Freshelle to create an account first in Giveth Trace?
