### ISSUE TITLE
Use Ant components in ChangeOwnershipButton component 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2319]

**Comment by RamRamez** [comment]
Done in PR #2322 

1. Remove react-rangeslider component
2. Use ant components in change ownership
3. Add ability to remove Campaign co-owner

**Comment by MoeNick** [comment]
Any Ideas for default value of changing co-owner modal? 

Eider a campaign has a co-owner or not. so putting the owner address as a default value in dropdown list is a bad idea I think. 
What do you think? 
@RamRamez

**Comment by RamRamez** [comment]
> Any Ideas for default value of changing co-owner modal?
> 
> Eider a campaign has a co-owner or not. so putting the owner address as a default value in dropdown list is a bad idea I think.
> What do you think?
> @RamRamez

There was a problem before that the campaign owner could make himself co-owner, so in this PR I removed Campaign owner from co-owner selection list and this is not also a default selection. The default selection is the previous campaign co-owner so in your case, probably the campaign owner had been set as campaign co-owner in DB before.

**Comment by MoeNick** [comment]
So is it okay that I keep this issue here to see your recent changes and after move it to done? 
@RamRamez

**Comment by RamRamez** [comment]
> So is it okay that I keep this issue here to see your recent changes and after move it to done?
> @RamRamez

It seems when creating campaign, backend is setting the default co-owner address equal to the campaign owner.
@mohammadranjbarz Could you please check it?

**Comment by mohammadranjbarz** [comment]
> > So is it okay that I keep this issue here to see your recent changes and after move it to done?
> > @RamRamez
> 
> It seems when creating campaign, backend is setting the default co-owner address equal to the campaign owner.
> @mohammadranjbarz Could you please check it?

Yes you are right
by default the `coownerAddress` is the userAddress of who create the campaign

**Comment by MoeNick** [comment]
I created another issue and make it done.

**Comment by RamRamez** [comment]
> > > So is it okay that I keep this issue here to see your recent changes and after move it to done?
> > > @RamRamez
> > 
> > 
> > It seems when creating campaign, backend is setting the default co-owner address equal to the campaign owner.
> > @mohammadranjbarz Could you please check it?
> 
> Yes you are right
> by default the `coownerAddress` is the userAddress of who create the campaign

@MoeNick has created an issue for it #2339
