### ISSUE TITLE
Add faucet to Wallet interface

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#232]
https://faucet.rinkeby.io/ it might be nice if there was a link to this faucet in the wallet and maybe a pop up when the user first signs on?

**Comment by vojtechsimetka** [comment]
**Task:**
Add text/button to the Wallet view through which user can get Rinkeby ether.

**Comment by GriffGreen** [comment]
Do we have an address to fill with Rinkeby ETH? I guess that would just be part of the design

**Comment by perissology** [comment]
fixed in fac9ed86ed80b85cb88d2d6d2908f84989a3b821.

Wallets are auto-filled, however if they use the eth at a faster rate then we fill, a warning will appear on the wallet with a link to the faucet
