### ISSUE TITLE
Co-owners cannot edit traces

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapp#2320]
![image](https://user-images.githubusercontent.com/86718721/123946930-53f72f00-d9d2-11eb-825a-611848917f02.png)

I clicked the "edit" button and the screen flashes, and it won't let me edit traces.

**Comment by freshelle** [comment]
Hi Amin. I see that the issue is still open. I tried to edit a trace again today and I experienced the same issue. I'll keep posted for updates on this. Thank you so much!

**Comment by aminlatifi** [comment]
> Hi Amin. I see that the issue is still open. I tried to edit a trace again today and I experienced the same issue. I'll keep posted for updates on this. Thank you so much!

Hi @freshelle
We are working on it, it will be fixed on develop and then will be released to production env. We hope it happen soon this week

**Comment by MoeNick** [comment]
@RamRamez @aminlatifi 

**Tested, as co-owner I can:**
1- Edit, Accept, reject. from trace page and from dashboard. 
2- All Traces type: Expense, Bounty and Payment. 

Problems:
1. Wrong update msg on edit payment and expense: It says Bounty is get updated! 
2. If not signed in, needs double click on reject, edit and re-propose botton. 
3.  edit trace small badge over the trace card not showed on campaign page for owner and co-owner.

**Comment by RamRamez** [comment]
> @RamRamez @aminlatifi
> 
> **Tested on Brave, as co-owner I can:**
> 1- Edit, Accept, reject. from trace page and from dashboard.
> 2- All Traces type: Expense, Bounty and Payment.
> 
> Problems:
> 
> 1. Wrong update msg on edit payment and expense: It said Bounty is get updated!
> 2. If not signed in, needs double click on reject, edit and re-propose botton.
> 3. edit trace small badge over the trace card not showed on campaign page for owner and co-owner.

No. 3: Only proposed traces can be edited by campaign owner or campaign coowner and we do not show proposed traces on campaign page

**Comment by RamRamez** [comment]
> @RamRamez @aminlatifi
> 
> **Tested on Brave, as co-owner I can:**
> 1- Edit, Accept, reject. from trace page and from dashboard.
> 2- All Traces type: Expense, Bounty and Payment.
> 
> Problems:
> 
> 1. Wrong update msg on edit payment and expense: It said Bounty is get updated!
> 2. If not signed in, needs double click on reject, edit and re-propose botton.
> 3. edit trace small badge over the trace card not showed on campaign page for owner and co-owner.

No. 1 and 2 are fixed in PR #2345
