### ISSUE TITLE
Join links are all broken!! 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2324]
Join links on home page and campaign page are all broken... check it out!

**Comment by MoeNick** [comment]
@mohammadranjbarz would u pls take a look?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz would u pls take a look?

@MoeNick 
@GriffGreen 

What link should we set there, the Discord link?

**Comment by MoeNick** [comment]
Trace.giveth.io there are join us links at top. Even in campaigns an traces page.

**Comment by mohammadranjbarz** [comment]
@MoeNick  In my machine and [UAT](https://develop.giveth.io) it's ok, so I think after deploy to beta it will be fixed,
@RamRamez  what do you think?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
it has been fixed and merge on [Production](https://trace.giveth.io)
