### ISSUE TITLE
Etherescan typo :) 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#2327]
Typo on accepting 

![image](https://user-images.githubusercontent.com/6533925/124188150-289e3e00-dabf-11eb-8f98-0f4959cd2eff.png)

**Comment by mohammadranjbarz** [comment]
@MoeNick 
@aminlatifi  has fixed that in this [Commit](https://github.com/Giveth/giveth-dapp/commit/b3fd2d86b805f124ceca3b6895ec0335eb9777f8), it will be fixed after the next release (merging `develop` to `master`)
