### ISSUE TITLE
did this canceled trace refund to the campaign? 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2328]
https://trace.giveth.io/trace/hatch-animation-video

**Comment by mohammadranjbarz** [comment]
Yeah we have returned donations that come from this trace to [Commons Stack Association](https://feathers.beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6)

https://feathers.beta.giveth.io/donations/60dfb70d1e3e9e27f7f03e5e
https://feathers.beta.giveth.io/donations/60dfb70e1e3e9e27f7f03e65
https://feathers.beta.giveth.io/donations/60dfb70f1e3e9e27f7f03e6c

**Comment by aminlatifi** [comment]
> @GriffGreen
> Yeah we have returned donations that come from this trace to [Commons Stack Association](https://feathers.beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6)
> 
> https://feathers.beta.giveth.io/donations/60e0fd1e9d05be7e11d4541c
> https://feathers.beta.giveth.io/donations/60e0fd1f9d05be7e11d4541d
> https://feathers.beta.giveth.io/donations/60e0fd1f9d05be7e11d4541e

Thanks @mohammadranjbarz

**Comment by MoeNick** [comment]
May we close this @GriffGreen ? Is it clear?
