### ISSUE TITLE
add analytics page trackers on front-end for page loads

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2331]

**Comment by MoeNick** [comment]
Hey @divine-comedian , would u please check it to make sure we are done in front-end?

**Comment by divine-comedian** [comment]
looks to be received in segment... 

![image](https://user-images.githubusercontent.com/67759413/124600397-aa31fb00-de34-11eb-9b5b-2d914f5fea59.png)

and the info is being sent to amplitude... 
![image](https://user-images.githubusercontent.com/67759413/124600713-039a2a00-de35-11eb-9673-1e393b5c1b8b.png)

I would call this issue done! nice work @aminlatifi  on such quick implementation..
