### ISSUE TITLE
Has more than 20$ but get limit error while trying to collect

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2336]
On this trace: 
https://develop.giveth.io/trace/milescretest1

Seems It has balance:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/b11a82a7-6ece-41e4-b105-c02323457297)

But cant collect. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e9c7b4bd-5a26-4057-88ce-8e50932f67a9)

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Actually I didn't get this error while collecting money, 
Maybe we can check it with together (you share screen and show me what happens)

**Comment by MoeNick** [comment]
@mohammadranjbarz were u on brave?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz were u on brave?

You are right, I faced the error on brave

**Comment by mohammadranjbarz** [comment]
@MoeNick 
My mistake, some donations were not mined so I got the error, after mining of donations I collected on brave
https://develop.giveth.io/trace/test-collect-on-brave-2

<img width="1433" alt="Screen Shot 1400-04-20 at 10 57 44" src="https://user-images.githubusercontent.com/9850545/125184966-219dcb00-e237-11eb-84dd-96f40b7c0376.png">

**Comment by mohammadranjbarz** [comment]
@MoeNick 
I think we need to discuss about it, how should we handle there is a tiny amount in trace,
should we not show collect button in this case?
