### ISSUE TITLE
Users are having trouble seeing the Enable web3 button

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2341]
<img width="732" alt="Screen Shot 2021-07-06 at 6 25 38 PM" src="https://user-images.githubusercontent.com/14945613/124635412-aed3cf00-de87-11eb-9f1a-ee9774903817.png">

It would be cool if that error box had the "enable web3" button in it :-D

**Comment by aminlatifi** [comment]
#2131

**Comment by RamRamez** [comment]
PR #2407 
1. Enable Web3 button is added to the "Wallet is not connected" modal.
2. This modal has been added to other profile pages (my donations, my delegations, etc.).
