### ISSUE TITLE
Fix some issues

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapp#2344]
1. Fix AcceptRejectProposedTraceButtons.jsx ApproveRejectTraceCompletionButtons.jsx ArchiveTraceButton.jsx CancelCampaignButton.jsx CancelTraceButton.jsx ChangeTraceRecipientButton.jsx DeleteProposedTraceButton.jsx EditCampaignButton.jsx EditTraceButton.jsx ProfileUpdatePermission.jsx ReproposeRejectedTraceButton.jsx RequestMarkTraceCompleteButton.jsx TraceConversationComment.jsx WithdrawButton.jsx WithdrawTraceFundsButton.jsx ChangeOwnershipButton.jsx needs double click if not signed in
2. Fix wrong message on updating traces
3. Remove unused UserWallet.jsx
4. Remove isLoggedIn and actionWithLoggedIn and replace with authenticateUser
5. Fix showing wrong notif when clicking back on edit traces page
6. Show notification when user is not allowed to edit Campaign or Community
7. Add loader when loading traces on ViewCampaign.jsx

**Comment by MoeNick** [comment]
Goodjob @RamRamez thanks.
