### ISSUE TITLE
Implement Eth-fiat price conversion API for milestones

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#235]
Integrate ETH to fiat conversion for milestones.

The idea is that you enter the amount in fiat, or in eth, for a specific date. And then the Dapp fetches the respective conversion in fiat/eth for the date and does the calculation.

Now this can easily be gamed, so when the reviewer views the milestone, we will fetch the data again to make sure the entered data was correct.

But perhaps we should check the conversion in feathers....

**Comment by vojtechsimetka** [comment]
There is a lot of APIs that can get ether price. Almost every exchange has one below are some notable ones that I've tested. Most of them have official node package.
JSON APIs:
cryptocompare: https://www.cryptocompare.com/api/  - you can chose multiple exchanges or aggregated rate
bittrexapi: https://bittrex.com/home/ap
coinbase: https://developers.coinbase.com
coinmarketcap: https://coinmarketcap.com/api/
kraken: https://www.kraken.com/help/api
poloniex: https://poloniex.com/support/api/
...

CSV data:
Etherscan: https://etherscan.io/chart/etherprice
Etherchain: https://www.etherchain.org/charts/priceUSD

For currency exchange rate the only open api I found was http://fixer.io which takes data from European Central Bank. Of course there is a lot of other APIs but most of them are behind paywall.

I would suggest to use cryptocompare or coinbase as those were the most reliable in my experience (though google sheets may not be the best test). The rates should be cached in feathers and frontend should just fetch them from there (less API calls, slightly safer if the API's are down).

Just for the reference this is the sheet https://docs.google.com/spreadsheets/d/1S3LvfwrwShKA5_jcKzAMTcjySsxH6f7Mq8JazkgRhyU/edit?usp=sharing

**Comment by Alonski** [comment]
This could also be used to show fiat price at time of milestone confirmation sort of like what Etherscan does in regards to old transactions
