### ISSUE TITLE
Research and confirm the block size on rinkeby and see if we can fit more pledges into a transaction

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2354]
Rinkeby just hardforked to apply 1559... what does this mean... well i have ideas... but it would be good for someone to fully understand how big transactions can be in this new situation

**Comment by MoeNick** [comment]
@aminlatifi ay thoughts ?

**Comment by MoeNick** [comment]
Discussed on grooming, mohammad will test it.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
@MoeNick 
I donated to a trace with 20 different account and after collecting, it was ok, you can rinkbey transaction:

https://rinkeby.etherscan.io/tx/0xb3a2cfa39dce8ceb2bf816dee0474a89c6b5de43316275921e485c0ac06332df
https://develop.giveth.io/trace/test-docker

So I think we should change the limit from 10 to 20

**Comment by aminlatifi** [comment]
@mohammadranjbarz @MoeNick Delegating from 20 different pledges should be tested too
To test it,
1. Create a new campaign and donate via 20 different accounts to campaign, all in one token
2. Create a trace in the campaign and delegate all the money to that trace
3. Collect the money in the trace

**Comment by aminlatifi** [comment]
> @mohammadranjbarz @MoeNick Delegating from 20 different pledges should be tested too
> To test it,
> 
> 1. Create a new campaign and donate via 20 different accounts to campaign, all in one token
> 2. Create a trace in the campaign and delegate all the money to that trace
> 3. Collect the money in the trace

Please test here:
https://github.com/Giveth/giveth-dapp/pull/2413

**Comment by mohammadranjbarz** [comment]
It worked for this scenario:
1. Donate with 20 different accounts to a campaign
2. Create a trace in campaign
3. Delegate all amount of campaign to trace (from 20 pledges)
4. Collect trace money at once

https://develop.giveth.io/trace/test-blocksize-trace

https://rinkeby.etherscan.io/tx/0x2f67ac7b758c460e827711a3b8e62071fb6fdf3bfe6be3050d4eaf938306f48f

https://rinkeby.etherscan.io/tx/0xddbe82065259a1a3ad4b8b328643f46faaaad2d5e2cfcf580d1804c5c4860dea

**Comment by MoeNick** [comment]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/12c8cd36-d656-4d25-9c3d-e04447c870c5)
@GriffGreen @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> ![image.png](https://camo.githubusercontent.com/04acdc8de2eee4dce9c1604d4e3d8da658377c627abe11d3e91ac6b94e0e77a0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630346632343263323831396435646136343236616430332f31326338636433362d643635362d346432352d396333642d653034343437633837306335)
> @GriffGreen @mohammadranjbarz
> Just to make sure this issue is done.

@MoeNick The DOD has been changed, in the last sprint we tested for 20 pledges, but maybe we should do more research and tests, I suggest close this issue and create new one and I'll do it, or we can return this task to inProgress and make new estimation
