### ISSUE TITLE
Avoid user to input the same address while changing recipient. & fix trx hash

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapp#2355]
Me as management user, want the app won't let me to change the recipient if the address I entered is the same at it as was. 

![image](https://user-images.githubusercontent.com/73441857/125094580-a29a7c80-e0e8-11eb-8649-b640795e6fa2.png)

**Comment by MoeNick** [comment]
It works fine for me. 
Shall you please share screen to have a review? @RamRamez

**Comment by RamRamez** [comment]
> It works fine for me.
> Shall you please share screen to have a review? @RamRamez

Sure. Tested again and got failed tnx again.

**Comment by RamRamez** [comment]
As we tested, if the new recipient address be the same as the old recipient address, the user will get failed tnx error.
Otherwise, the tnx will be successful and recipient will be changed but the tnx hash is always undefined.
