### ISSUE TITLE
Accidentally made a second grant ops campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2359]
I tried to edit this old campaign... 

https://trace.giveth.io/campaign/grantops

and when i did... it made a new one...

https://trace.giveth.io/campaign/grantops-2

I would like to cancel the new one

And add this text to the top of the  old campaign:

This Giveth Campaign has been in active for over 2 years, but in that time the value of the ether in the Campaign has skyrocketed. It wouldn't be prudent for Giveth to just leave these funds here with no team members here to support the original efforts of the Campaign.

We will instead use these funds to pay some of our monthly salaried employees, until this campaign runs out of funds.

**Comment by aminlatifi** [comment]
Campaign is an old one holding feathers uploaded image in its image field. That caused issue in editing.
@GriffGreen Now it should be fixed and you can edit you campaign. Please cancel the new one.
