### ISSUE TITLE
Campaign Cancel button wont go after cancellation, it needs refresh. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2365]
As a campaign manager, After I canceled a campaign,  I don't want to see the cancel button still be there and clickable, because it I might think smth is not okay and tray to click that button again

**Comment by divine-comedian** [comment]
I just cancelled my campaign and the `cancel` button instantly dissapears after I send the transaction on rinkeby - looks to be fixed! 

![image](https://user-images.githubusercontent.com/67759413/126520290-b400ceea-d7ae-4060-8fdb-bd01cfc48a61.png)
