### ISSUE TITLE
community to campaign deleation email link

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2377]

**Comment by mohammadranjbarz** [comment]
@MoeNick plz provide email text for this issue

**Comment by divine-comedian** [comment]
there's no context to this issue so I am not able to test it!

**Comment by MoeNick** [comment]
when community owner, delegate funds to a campaign, donor receives an emails. The link to  my donations got 404 error. It should be fixed right now. 
@divine-comedian

**Comment by divine-comedian** [comment]
testing this on `develop.giveth.io` I delegated a donation from a community to a campaign - I receive this email in my inbox - 
![image](https://user-images.githubusercontent.com/67759413/126518633-0783c1d6-d43f-492a-879b-8f474a2fd6ce.png)

I click the `my donations` link and it takes me to a 404! 

![image](https://user-images.githubusercontent.com/67759413/126518790-306f016b-38d4-4c9f-963d-bb1293e97ac3.png)

another issue encountered during this process is also the email sent to the recipient campaign owner there is an email link to see delegations - this also goes to the wrong slug and gives a 404 error. 

The obvious problem causing both of these errors is that the slug is incorrect - they should link to this address instead - `https://develop.giveth.io/my-delegations` with a similar format for any 'my donations' link.
![image](https://user-images.githubusercontent.com/67759413/126519582-a1a7693a-8226-48c1-8d57-e5d2122c7b53.png)

**Comment by MoeNick** [comment]
Thanks @divine-comedian

**Comment by MoeNick** [comment]
Tested. The link was OK.
