### ISSUE TITLE
Rejected Delegations send new donation email to community owner

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2378]

**Comment by mohammadranjbarz** [comment]
@MoeNick plz provide email text for this issue

**Comment by MoeNick** [comment]
Hey @laurenluz 
Can help us on this issue? We need a text of email whenever the donor, rejects the delegation of his donation, from a community  to a campaign.  The emails should be sent to community manager, inform him that the delegation he has made was rejected and will get back to Community balance. 
Thanks.

**Comment by laurenluz** [comment]
Subject: ‘Giveth - Rejected Delegation"
SecretIntro: ‘A Giver to your Community {communityname} has rejected your delegation to the {trace/campaign} {tracename/campaignname}'
Title ‘Delegation Rejected :-('
Text: ‘Unfortunately, your proposed delegation of ${normalizedamount} ${tokensymbol} from your Community {communityname} to the {trace/campaign} {tracename/campaignname} has been rejected by the Giver. The donation will be returned to the Community.
Cta: ‘Manage your Community’

@WhyldWanderer can you do a quick QA?

**Comment by WhyldWanderer** [comment]
Looks good to me!

**Comment by MoeNick** [comment]
Thank u all @mohammadranjbarz @laurenluz @WhyldWanderer

**Comment by MoeNick** [comment]
Tested.
