### ISSUE TITLE
Images not saving in new milestones 

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#238]
![screen shot 2018-01-29 at 3 02 23 pm](https://user-images.githubusercontent.com/35914957/35499550-77203d0a-0505-11e8-87a1-2fcadf0509eb.png)

![screen shot 2018-01-29 at 3 03 30 pm](https://user-images.githubusercontent.com/35914957/35499577-9db72ece-0505-11e8-80dc-ed7da19a240f.png)

I used the photo attachment icon to add the screenshot and saved the milestone; but when I review the milestone the image is gone. 

Milestone: https://alpha.giveth.io/campaigns/Wze7njNMv5Z68M2X/milestones/ilErxdwiFYRWz2ki

**Comment by twmilli** [comment]
I'll take care of this 👍

**Comment by vojtechsimetka** [comment]
Still needs a fix in feathers. Should be closed once https://github.com/Giveth/feathers-giveth/pull/81 is merged.

**Comment by twmilli** [comment]
Looks like the feathers PR got merged so we can probably close this 😀

**Comment by vojtechsimetka** [comment]
Yep, thank you. I also tested it and worked for me.
