### ISSUE TITLE
Can not set recipient for Bounty

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2394]
After creating Bounty, I want to set recipient bu I got error

Logs in UAT
![Screen Shot 1400-04-24 at 18.15.56.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/c250ed0b-9235-4eb8-b477-0531a5d3f8d8)

Logs in localhost
![Screen Shot 1400-04-24 at 18.16.48.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/64492fa6-43a8-4e6d-ad04-d9484be0c23c)

**Comment by divine-comedian** [comment]
testing on `develop.giveth.io` 

changing recipient of an approved trace 
![image](https://user-images.githubusercontent.com/67759413/126494626-6162f138-c666-47e1-8bff-775e62aab6d3.png)

I successfully propose a recipient 
![image](https://user-images.githubusercontent.com/67759413/126494928-f3186cdb-9f9a-4c0a-9d10-74e27cd3c79f.png)
 
 
 error looks to be fixed!
