### ISSUE TITLE
can't change sign in option after rejecting Torus

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapp#2405]
testing on `develop.give.io` - brave browser clean cache and cookies. 
I clicked `sign in` on the homepage and chose Torus, the sign-in button changes to `Enable Web3` I being the Torus wallet sign-in but change my mind and reject the pop-up, from here there is no option to go back to the original sign-in to choose metamask (or another option). even on page refresh it takes me directly back to the `Enable Web3` with Torus wallet. 

As a user I should be able to change my mind and have an easy way to sign in **and** sign-out  with Torus or Metamask without having to delete my cookies and start over.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/aa63e7e5-e1fa-44cd-b954-17d1ddd8d040)

**Comment by MoeNick** [comment]
My UX Suggestion to change wallet and continuing connecting other wallets:

![Slide1.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/364d445c-1607-4985-99f7-7285c68ce61c)
![Slide2.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/adcd0117-496c-4f3e-a3ad-2b492bb49535)![Slide3.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/1ad1890d-7241-43e6-ba0e-1f41cddfe194)
![Slide4.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/da080d56-e568-4026-8d9d-92864cf89487)
![Slide5.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/fea3590d-213c-4589-a968-319a9a7c2c99)
![Slide6.JPG](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/b1e2827b-6b36-4888-a684-8442ede19029)

**Comment by MoeNick** [comment]
@markoprljic 
Appreciate if you can take a look at my UX suggestion, any thoughts to make it better? 
And do u have some room for design wallet label on the top?

**Comment by markoprljic** [comment]
This is a standard Web3 pattern that we should be using @MoeNick Please continue.

**Comment by MoeNick** [comment]
I think it works creepy @divine-comedian , would you pls go with it again? 
I made it done but want to make sure before closing,

**Comment by divine-comedian** [comment]
yes I see now that once I connect with Torus I can switch wallets by clicking on my address which will bring up onboardJS.. as well when I reject the pop-up to log in with Torus the button `Switch Wallet` remains allowing me to choose another sign-in option! This looks to be resolved!

![image](https://user-images.githubusercontent.com/67759413/130685144-15972142-525e-4033-a5d0-c2d04ecaed30.png)
