### ISSUE TITLE
Enabling web3 button won't do anything in Brave

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapp#2415]

**Comment by MoeNick** [comment]
Im on Brave. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/85e61e46-504f-49d2-9431-8b51f9e61aed)

**Comment by RamRamez** [comment]
It was ok for me.
If the MetaMask modal is already open, clicking on the Enable Web3 wouldn't do anything, because it's waiting for the user action.
![image](https://user-images.githubusercontent.com/73441857/126913292-a2b39230-d4a9-44d1-abf4-de2da018e345.png)
