### ISSUE TITLE
Change text of Change co-owner button to Set co-owner when campaign doesn't have co-owner

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapp#2422]
related to #2339

![Screen Shot 1400-05-04 at 16.08.51.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/b4f17565-3675-4c14-9cda-9697554614b3)

**Comment by MoeNick** [comment]
In the case I remove the co-owner the button text still be change co-owner: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/920f2223-837e-4b72-8190-426d663922f0)

**Comment by mohammadranjbarz** [comment]
@MoeNick  Please test it again
