### ISSUE TITLE
Can't edit milestones

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#247]
I can't seem to edit any of my milestones right now
I get the ominous blinking green dot in the center of the page and it never opens the milestone

Ive tried on chrome and brave and get the same
I can view my milestones

**Comment by vojtechsimetka** [comment]
Can you share a link which milestone you are trying to edit?

**Comment by ljg583** [comment]
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/Wxcd4QbgZrEowpqo

I have tried with 3 or 4 but this is one of them :) Thanks

**Comment by vojtechsimetka** [comment]
Solved for new milestones
