### ISSUE TITLE
Can't edit or delete milestone expenses, invoices or items once they've been added

### ISSUE THREAD

**Issue by c1e0** [Giveth/giveth-dapp#249]
Here's a super quick video showing the issue: https://www.dropbox.com/s/cu7ihildfdefdmy/edit%20items%20expenses.mp4?dl=0

**Comment by vojtechsimetka** [comment]
That is actually correct. The total milestone amount is stored on the blockchain and you should not be able to modify it. The only option is to cancel and propose new milestone. That being said, we should make it clearer for the end user.

**Comment by c1e0** [comment]
Totally makes sense. I was thinking that because it was before the milestone had been submitted that I'd be able to change it. Thanks for the quick reply!
