### ISSUE TITLE
If a campaign delegates to a dac, the `my-donations` page for original owner is not clear that they have committed the funds to the campaign

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#25]
To reproduce...

1. donate to a campaign
2. campaign delegates to a dac
3. view my-donations from the donor's profile

The status of the donation is "waiting for further delegation" and the donated to is the "dac". This is misleading as this "donation" from the user's perspective looks the exact same as if they donated to the dac (and still have control), however since they donated to a campaign first, they don't control the funds.

Either don't allow campaigns to delegate to a dac, or find a way to display this better

**Comment by satyavh** [comment]
Please check this issue: https://github.com/Giveth/feathers-giveth/issues/30

There are more cases than written down in this issue, but including the `proposedProject` would solve all of them I think.
