### ISSUE TITLE
Still can't propose milestones but heres what I got

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#251]
There does seem to be much less red in the console tab in dev tools  :)

![screen shot 2018-03-15 at 4 51 34 pm](https://user-images.githubusercontent.com/35914957/37474731-560acfd8-2871-11e8-8789-e0801fb45eb9.png)
![screen shot 2018-03-15 at 4 51 17 pm](https://user-images.githubusercontent.com/35914957/37474735-57cc6322-2871-11e8-960d-dc5fb0058a76.png)

**Comment by satyavh** [comment]
Can you write down the exact steps that you took? So the order you put data in the input fields, and what amounts?

**Comment by satyavh** [comment]
And is this on release.giveth.io?

**Comment by ljg583** [comment]
No, that was on alpha dapp.  I proposed one on release.giveth and it worked fine so I tried alpha

**Comment by ljg583** [comment]
I typically just go down from top to bottom but I can try again and document exactly if you need

**Comment by vojtechsimetka** [comment]
Should be fixed now, I've just very quickly deployed the release to alpha. Try now @ljg583
