### ISSUE TITLE
Can't edit completed milestone & need to clarify it or transparency

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#252]
https://alpha.giveth.io/campaigns/Wze7njNMv5Z68M2X/milestones/Wwt0ZUIvdRUn26fK is the link to his milestone

Upon checking with kkx, the address that was submitted is no longer under their control. So via email they requested that we send to this address: 0x4a42ceaad068a8c926e19231d149ed3c1238e51f

This happened in this tx: https://etherscan.io/tx/0xd7034491f4e41b7ab61721b2c4d93ad71f7caeb3cacbeb73a310222449fb780e

Notice that 1.800117316 ETH was sent to 0x4a42ceaad068a8c926e19231d149ed3c1238e51f that is what paid out this milestone 😃

I am unable to open this milestone to edit 

Is there anyway to change this address in the bank end?

![screen shot 2018-03-16 at 11 06 14 am](https://user-images.githubusercontent.com/35914957/37515182-4c2db8e2-290a-11e8-8f5a-b6f4854bfc03.png)

**Comment by vojtechsimetka** [comment]
The recipient address can not be changed. It is because the recipient's, milestone manager's, reviewer's addresses and the total amount in ETH are stored directly in the contract on the blockchain. There is no way for any of us to change any of these. However, I will keep this issue up as you should be able to edit the milestone (just not those addresses).

**Comment by satyavh** [comment]
You should not right? This is a completed milestones. We don't allow editing those because then you can mess up the accounting. After the milestone is created, you should only be able to cancel it and create a new one.

**Comment by GriffGreen** [comment]
I agree, we should not let the end user be able to edit the approved description.... however, there are 2 issues within this issue.

1. We need to bring transparency to our own actions. We did not send to this address, our review process failed but the triple check saved us from throwing away 1.8 ETH, Cleo made us check in with him to verify his address and he had lost the keys, so he gave us a new address to send to.

I think we NEED to manually override this description this time for this milestone so that Giveth can maintain transparency for 10 years down the line :-D

2. I am excited to allow for that "Conversation" feature where people can add notes to the milestones. So that yes, the approved description should not be editable, but the milestone itself has some data field that can always be added to, so that people can add like a success video or a thank you note. :-D

**Comment by satyavh** [comment]
I really can't imagine a feature that gives someone superpower to manually override a single milestone in a decentralised system. Immutability is what defines blockchain. 
And even if possible, where do we (and who's we here?) draw the line?

**Comment by GriffGreen** [comment]
Yeah... there is where we are and where we want to be... I'm not looking for a new feature to be built, I'm curious if there is a way to add to our centralized UI a clarification about what REALLY happened to that 1.8 ETH... cause right now we are lying.

**Comment by GriffGreen** [comment]
and btw... immutability is not in any way part of a blockchain....

**Comment by GriffGreen** [comment]
but on that suggested feature... (point #2) i thought you and vojtech came up with the idea... the ability  for people to have a conversation in a milestone, and I agree we can and SHOULD freeze the conversation after the milestone is approved.

**Comment by GriffGreen** [comment]
So is it possible to Edit the text of KKX's milestone so we can maintain our transparency?

**Comment by satyavh** [comment]
Well, you could try to convince @perissology to edit the milestone data in the backend. 
I can't (and won't) make a button in the dapp to do so, that would enable everyone to edit completed milestones instantly.

**Comment by GriffGreen** [comment]
I would love a button that would allow people to add notes, NOT edit :-D

**Comment by GriffGreen** [comment]
Also for transparency we need to upload the pics again (or something) for the 2 milestones in this issue: 
https://github.com/Giveth/giveth-dapp/issues/260

**Comment by perissology** [comment]
I would propose that we wait until we migrate to the new lp contract to take care of these issues.

All milestones will have to be re-created, so we can make the edits then.

**Comment by GriffGreen** [comment]
ANOTHER ONE TO FIX!
https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/YXgSgjCHyEE2gZgi 
This milestone was apporved but is not going to be paid out, it's approval should be changed to `CANCELED`

**Comment by lorelei1** [comment]
NEEDS A FIX :)
https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/KTIOWKE2UaYZVyD8
This milestone needs to have a note added to it of Satya's agreement to donate back the eth that was over compensated now that eth has gone up.

**Comment by lorelei1** [comment]
We need to make a note on these three milestones (in issue #353) saying that they weren't actually paid to the recipient address listed (Griff's) and were indeed paid to who the points were awarded to. https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/D8lvi7jf2RD04onu
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/hN3m6N8S505dCGwU
and
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/VvpdpidCezmpoZVW

**Comment by lorelei1** [comment]
aaand these two: https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/j8CsAITBGgBVZFwH
https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/W5IeiYPH2BsjzM13
says in the milestone that they were sent to a certain multisend address, but as y'all know we had to send them somewhere different. so need to make a note of that during migration! i like this idea of a notes field on the milestones :)

**Comment by vojtechsimetka** [comment]
> We need to make a note on these three milestones (in issue #353) saying that they weren't actually paid to the recipient address listed (Griff's) and were indeed paid to who the points were awarded to. https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/D8lvi7jf2RD04onu
> https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/hN3m6N8S505dCGwU
> and
> https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/VvpdpidCezmpoZVW

@lorelei1 can you give me the multisend transaction for this and the correct addresses to which it was sent? I am working on the migration right now.
