### ISSUE TITLE
Can't accept milestones that I am the campaign manager for

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#253]
My old Griff's Boss account (0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1) is the account manager for the ScalingNOW campaign

My new Griff's Boss* account (0x51e37e3716c0ED418a90e519CeEE395d8f6deCB9) proposed milestones to this campaign

I have tried to accept the milestones so it can be reviewed and have received the following response:
![screen shot 2018-03-16 at 12 14 57 pm](https://user-images.githubusercontent.com/35914957/37518270-c88b198e-2914-11e8-9538-aecf5a7a5a66.png)
![screen shot 2018-03-16 at 12 19 46 pm](https://user-images.githubusercontent.com/35914957/37518277-cc277024-2914-11e8-8dd0-33fcf980445a.png)
![screen shot 2018-03-16 at 12 24 44 pm](https://user-images.githubusercontent.com/35914957/37518373-1ee718c8-2915-11e8-91a6-5ca8dcf503b2.png)

Yes, my wallet was unlocked and has sufficient balance.  Please let me know what I can do to make these go through

Thank you!!!!! :-D

**Comment by vojtechsimetka** [comment]
Please just try and refresh. It looks like you were disconnected (yeah we should write proper warnings...)

**Comment by vojtechsimetka** [comment]
@ljg583 does it work now?
