### ISSUE TITLE
Add sorting and filtering to My Milestones page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#254]
It would be nice if i could filter and sort the "My Milestones" page, right now i have all these canceled milestonse i dont care about, that i have to scroll thru....

If its hard to allow the user to filter/sort, can we change the default sort to be based on action (which is easier?... Let's just take the path of least resistance).

The user would like to see the actionable items at the top! 

If I'm the reviewer and the milestone "Needs Review" then boom! its at the top.
If I'm the Campaign Manager and the milestone is "Proposed" then its at the top.

:-D

**Comment by satyavh** [comment]
This is weird, the sorting is already like this. Milestones that need action should be on top. 
Rejected milestones at the bottom, etc.

But the sorting probably got messed up due to paging. Because we sort client side, but we need to change that to server side.

And I agree with filtering...

**Comment by vojtechsimetka** [comment]
My Milestones page is now tabbed, sorting works, search and filtering is missing but not an issue for now.
