### ISSUE TITLE
Canceled Milestones are the first Milestones shown in the ScalingNow! Campaign

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#255]
I was going to link the ScalingNow! Campaign in our DApp in an email to everyone... but the first 8 milestones were all canceled and it just looks bad :-( 

Can we display the canceled milestones at the end? I would suggest we prioritize active milestones, then completed, then canceled?

**Comment by vojtechsimetka** [comment]
Potentially fixed for now. The milestones are sorted by the creation date in descending order. Please confirm we can close @GriffGreen 

Proof: https://alpha.giveth.io/campaigns/ap6KXg8iJwwUAxBY
