### ISSUE TITLE
IPFS Integration

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#258]
1. Set up the IPFS consortium node(s) that we can run with Swarm City. 
2. Modify the DApp to store profile data in there rather than on chain/just feathers.
3. Create components for uploading, replacing and viewing pictures, videos and other files uploaded to IPFS. Bonus points for integrating the uploads to wall of fame.

**Comment by GriffGreen** [comment]
also remember to merge the whitelist bug fix ;-D

**Comment by vojtechsimetka** [comment]
Merged in by RJ.
