### ISSUE TITLE
Can't pay people :-(

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2581]
Trace on brave shows me this:
<img width="1335" alt="Screen Shot 2022-03-03 at 8 01 28 PM" src="https://user-images.githubusercontent.com/14945613/156684814-053380a6-e53f-4243-8c29-034074a83fdf.png">

Classic "Griff being blocked on brave from using Trace" issue... @aminlatifi you know what I'm talking about :-D

Then on Chrome i get this error: 

![Uploading Screen Shot 2022-03-03 at 9.08.42 PM.png…]()

Help!

**Comment by aminlatifi** [comment]
@GriffGreen Your second image is not uploaded correctly. Besides, it's working for me now! do you still have issue?

**Comment by GriffGreen** [comment]
it is working now... accept the donation i made while it wasn't working didnt show up:
https://etherscan.io/tx/0x11ebd8848000c8411a3549eb45a819b4e3fe65622b9d9980d884e8e3c9ffd6a3

And also https://bridge.beta.giveth.io/ doesnt work!

**Comment by GriffGreen** [comment]
It's not in the Iteration 0 Campaign, https://trace.giveth.io/campaign/commons-stack-community-iteration-0

<img width="1224" alt="Screen Shot 2022-03-08 at 7 10 02 PM" src="https://user-images.githubusercontent.com/14945613/157352783-d14d9a70-3c81-4527-9a55-87738b3746a9.png">

It looks like it is in a weird limbo when i check: https://trace.giveth.io/my-donations :-/ Should I refund? or can i some how move it to the iteration 0 campaign
<img width="1128" alt="Screen Shot 2022-03-08 at 7 12 46 PM" src="https://user-images.githubusercontent.com/14945613/157353047-bf1e3133-83e8-4459-a582-475717dba2e4.png">

**Comment by GriffGreen** [comment]
Ok I could delegate it!

Weird even tho the bridge has 1402 as the receiver ID it ended up in my delegation window

**Comment by GriffGreen** [comment]
<img width="983" alt="Screen Shot 2022-03-08 at 7 15 41 PM" src="https://user-images.githubusercontent.com/14945613/157353473-3258b5e8-a382-46a9-b4af-f5ee67993990.png">
