### ISSUE TITLE
Cannot connect with Giveth Trace

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapp#2597]
I already connected my wallet with Rinkeby network. Griff is experiencing the same issue.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/86718721/163900548-c60bcf24-0d8f-4e5d-b416-2aeadb1e8a73.png">

**Comment by aminlatifi** [comment]
Trace backend (feathers) was down for any reason, I restarted and it's working now.
Do you have the issue now?

**Comment by freshelle** [comment]
All good now. Thank you so much Amin!!
