### ISSUE TITLE
Some receipts won't pop up when they are clicked

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#260]
**Second pic in this one doesn't pop up:** 

https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/6JuNhD47V8VhuIhZ
<img width="865" alt="screen shot 2018-03-27 at 10 02 30 pm" src="https://user-images.githubusercontent.com/14945613/37992195-4a7fe39e-320b-11e8-927c-a3b0fea13f9b.png">

**Error message for this one:**

<img width="685" alt="screen shot 2018-03-27 at 10 13 27 pm" src="https://user-images.githubusercontent.com/14945613/37992504-366459d4-320c-11e8-89f9-960518dbb31e.png">

**Text of Error message:**

Not allowed to navigate top frame to data URL: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlMAAANJCAYAAAAoe7mhAAABGWlDQ1BJQ0MgUHJvZmlsZQAAKJFjYGBSSCwoyGESYGDIzSspCnJ3UoiIjFJgf8TAxCDFIMDAy6CcmFxc4BgQ4MMABDAaFXy7xsAIoi/rgszClMcLuFJSi5OB9B8gzk4uKCphYGDMALKVy0sKQOweIFskKRvMXgBiFwEdCGRvAbHTIewTYDUQ9h2wmpAgZyD7A5DNlwRmM4Hs4kuHsAVAbKi9ICDomJKflKoA8r2GoaWlhSaJfiAISlIrSkC0c35BZVFmekaJgiMwpFIVPPOS9XQUjAwMLRgYQOEOUf05EByejGJnEGIIgBCbI8HA4L+UgYHlD0LMpJeBYYEOAwP/VISYmiEDg4A+A8O+OcmlRWVQYxiZjBkYCPEBG51KV2OIoHcAAAAJcEhZcwAACxMAAAsTAQCanBgAAEAASURBVHgB7J0PXJRVvv8/7...AJkAAJJAjQmUqw4BkJkAAJkAAJkAAJrJkAnak1I2MBEiABEiABEiABEkgQoDOVYMEzEiABEiABEiABElgzATpTa0bGAiRAAiRAAiRAAiSQIEBnKsGCZyRAAiRAAiRAAiSwZgJ0ptaMjAVIgARIgARIgARIIEGAzlSCBc9IgARIgARIgARIYM0E6EytGRkLkAAJkAAJkAAJkECCAJ2pBAuekQAJkAAJkAAJkMCaCdCZWjMyFiABEiABEiABEiCBBAE6UwkWPCMBEiABEiABEiCBNROgM7VmZCxAAiRAAiRAAiRAAgkCdKYSLHhGAiRAAiRAAiRAAmsmQGdqzchYgARIgARIgARIgAQSBOhMJVjwjARIgARIgARIgATWTIDO1JqRsQAJkAAJkAAJkAAJJAjQmUqw4BkJkAAJkAAJkAAJrJkAnak1I2MBEiABEiABEiABEkgQoDOVYMEzEiABEiABEiABElgzgf8f+1zfJ80Lh3kAAAAASUVORK5CYII=

**Second and 3rd pic don't pop up for this one:**  

https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/za8GqVrUfRKwvQ1p
<img width="853" alt="screen shot 2018-03-27 at 10 05 01 pm" src="https://user-images.githubusercontent.com/14945613/37992220-5c9dd31a-320b-11e8-8f72-56991b34e593.png">

**Error message for these two:**

<img width="665" alt="screen shot 2018-03-27 at 10 10 33 pm" src="https://user-images.githubusercontent.com/14945613/37992342-b928809e-320b-11e8-8c17-6f3c2a2b7d4c.png">

**Text of Error messages:**

Not allowed to navigate top frame to data URL: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlgAAAIrCAYAAAAz0OezAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKvmlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjarZZnVFPZHsX/9970QkuIgJTQmyCdANJrKIJ0sBESSiDEGBJUbIgMjmBFRIoVHIooOBZAxoJYsDAoNuwDMiioz8GCDZX3gUd489b78tZ6/7Xuur+11zn77HPvlw1Au8+TSESoCkCWWCaNDPRhxycksonPAAEtUAUrMOHxsyXeERGhAABT77/Px3uAAADctuJJJCL430ZVkJLNB0AiACBZkM3PAkBOACBn+RKpDACTAYDhMplEBoCVAwBTGp+QCIAdBgBm2iR3AAAzeZLvAABTGh3pC4ANA5BoPJ40DYD6AQDYOfw0GQCNCQA2YoFQDEDzAwAPfjpPAEArAIBZWVlLBAC0owBglvxvPml/80xWePJ4aQqevAsAA...M1OMzZ/hhlFfU01layMHaBqXiSlZvLcRg6YZ80YSGEEFceGcESS8bI5bCcYeobq3GpPvKZDE6ng5GLnfQNTOHEIJ/XMLU8Wt4AK8dCyqKxtpyRwU7Od/QwEzepKC5idGiScEkxpVH5L22EEEJceeTnv1i6NO8to3VNGJcNQKG6phqnB0rWbCKWPUUs52TN+hX4VTu65QJXhIblKiXRCOtXJ+kbHqaxdTNbK8s5faydKRuUVQOybJYQQogrjKzkLp7jv3MldyGEeCmTldylL3yWuLQCIYQQQogXmAQsIYQQQggJWEIIIYQQErCEEEIIISRgCSGEEEIICVhCCCGEEBKwhBBCCCEkYAkhhBBCCAlYQgghhBASsIQQQgghJGAJIYQQQggJWEIIIYQQErDEy4mu5UgkkuR1QwpDCCHEy5YDiAPBxT+FePGkp/nZPd+jZ8Yg4PWxfts1XLdprZSLEEKIl5MgEP9/AwCfHx0fGK/oEQAAAABJRU5ErkJggg==
za8GqVrUfRKwvQ1p:1 Not allowed to navigate top frame to data URL: data:;base64,/9j/4QwKRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAgAAAAcgEyAAIAAAAUAAAAkodpAAQAAAABAAAAqAAAANQACvyAAAAnEAAK/IAAACcQQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKQAyMDE4OjAzOjA2IDE0OjAwOjU4AAAAAAOgAQADAAAAAf//AACgAgAEAAAAAQAABKagAwAEAAAAAQAAAscAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAAK0AAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDA...FX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX3/mzwBmxV9/5s8AZsVff+bPAGbFX/9k=

**Comment by vojtechsimetka** [comment]
This is fixed for new uploads, however leaving open so that we migrate existing data.

**Comment by GriffGreen** [comment]
:-D Thx V! :-D

**Comment by vojtechsimetka** [comment]
Just so you know, this is how a plaintext png image looks like (in base64 characters). If you save the text in text file and add .png suffix it will show you the image :).

**Comment by perissology** [comment]
or use firefox ;)

**Comment by vojtechsimetka** [comment]
Fixed somewhen by someone. It just works now :).
