### ISSUE TITLE
Too many decimals in the Converted amounts

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#261]
Is it possible to avoid 18 decimals of accuracy when using exchange rates? This level of accuracy ends up causing a lot of issues in spreadsheets and in all the other tools that just aren't expecting that many digits... 

I don't really know how this works on the backend, but my personal suggestion is that we maintain 10 sig figs on big numbers, and always less than 10 decimals on ETH, but more than 6 :-D

For example: 100.1234567 should work. If we round off on the 7th decimal ETH would need to become worth $1,000,000 for us to round someone off a penny. 

We can go up to 10 decimals if sig figs is limited, which should be enough :-D

GoogleSheets "sheets" out at 15 sig figs

**Comment by vojtechsimetka** [comment]
Not an issue

**Comment by GriffGreen** [comment]
Definitely an issue, this makes the DApp not look pretty, if its not prioritized its fine... but it should stay open so contributors can fix it

**Comment by GriffGreen** [comment]
We don't need 18 decimals of accuracy, 8 is good enough for bitcoin, its good enough for our DApp too. Too many decimals cause issues when working with other programs, if someone wants to audit a charity, they shouldn't have to build their own software custom software to work with 256 bit numbers.

This level of accuracy litterally doesnt make sense... if you look at any lazy smart contract audit, they will always complain about this level of accuracy causing issues and having rounding errors.

Not to mention... it just looks ugly and is bad UX/UI

**Comment by vojtechsimetka** [comment]
This will require changes in frontend and feathers. It will also prevent users to edit all the already created/proposed milestones.
