### ISSUE TITLE
Fix overflow in my-milestones and my-campaigns

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapp#265]
A very small issue but bugging me since the start.

`overflow: scroll` should be set to `overflow: hidden` on the views for:

1 - my-milestones
2 - my-campaigns

I could **not observe the same bug  on my-communities**

Screenshot **FIXED (left)** and **BUG (right)**
![dapp-overflow](https://user-images.githubusercontent.com/317685/38139106-4fa2c36c-342e-11e8-8993-681c6103e1a5.png)

**Comment by vojtechsimetka** [comment]
Go ahead and make a PR :). Mind you this needs to be tested because if you resize the screen it may hide some columns (e. g. Actions)

**Comment by vojtechsimetka** [comment]
Solved in https://github.com/Giveth/giveth-dapp/pull/268
