### ISSUE TITLE
When performing an action in "My Milestones" the page all the milestones disappear

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#269]
![Screen Shot 2018-03-31 at 10.14.38 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/70e7d10b-fa49-4303-9481-5c4712ef97d3)

this would be horrible in a demo

**Comment by vojtechsimetka** [comment]
Yeah this is actually quite big issue. The feathers subscribe is buggy and we may need to upgrade to feathers 3. I was hoping it can wait a bit until other issues are resolved.

**Comment by GriffGreen** [comment]
there is no ghetto fix for this? Or at least some mitigation? Maybe we can force navigate to the milestone or somewhere else.... Maybe we can have a pop up that explains the action that was just made and when you click out of it there is a refresh... something like that?

**Comment by perissology** [comment]
should be fixed in develop
