### ISSUE TITLE
handle refund flow

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#27]
using the vault, there is a time delay before the user can actually take the money out of the vault. So when a user takes back control of a donation, it is still locked in the vault for a few days. Then they need to withdraw to their wallet.

we need to incorporate this into the donations page.

**Comment by perissology** [comment]
this actually isn't the case for refunds. Refunds now work in the dapp

**Comment by vsimetka** [comment]
Works in develop as of 2017-11-21.
