### ISSUE TITLE
Campaign Reviewers are not listed anywhere

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#270]
Low Priority
they need to be listed and there needs to be a way for people to change them... I need to change a couple of mine ;-)

**Comment by vojtechsimetka** [comment]
This will require a number of transactions from the UI. Let's wait to see how the contracts change.

**Comment by vojtechsimetka** [comment]
- [x]  Listing campaign reviewer in campaign has been resolved in #338
- [ ] Add way to change the campaign reviewer.

@perissology @satyavh Who can change campaign reviewer right now in the contracts? Does it have to be the current campaign reviewer who asks to be changed and the new campaign reviewer needs to confirm the nomination?

**Comment by GriffGreen** [comment]
Thats exactly right @vojtechsimetka 

It has to be the current campaign reviewer who asks to be changed and the new campaign reviewer needs to confirm the nomination.

https://github.com/Giveth/lpp-campaign/blob/aragon/contracts/LPPCampaign.sol#L131

**Comment by vojtechsimetka** [comment]
I've created new issue for the change reviewer buttons #489
