### ISSUE TITLE
The DApp is way too gung ho on decimals

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#271]
We don't need 18 decimals of accuracy, 8 is good enough for bitcoin, its good enough for our DApp too. Too many decimals cause issues when working with other programs.

**Comment by vojtechsimetka** [comment]
Not an issue

**Comment by GriffGreen** [comment]
Definitely an issue ;-) If its not on the priority list thats fine, but it should stay open.

**Comment by GriffGreen** [comment]
Closing this one because my description is better in a previous one.
