### ISSUE TITLE
Ξ0 of Ξ0.861066861841822017 raised is very depressing and confusing we cannot raise money yet with this version

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#274]
Talking about money being raised will make sense while when we can donate to milestones. Right now its just sad, it makes it look like no milestones are ever funded.

I think having it display just: "amount requested" instead would be good (and get rid of Ξ and all the decimals).

**Comment by vojtechsimetka** [comment]
Fixed by @satyavh in fb7c5843074bd102f49adba97f08b84c0e28d037
