### ISSUE TITLE
Ctrl-F Ξ and Delete it! Put ETH after each number instead

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#275]
Ξ is weird... i don't see anyone really use it, I would just use ETH but I am open to hear other thoughts on that.

**Comment by Alonski** [comment]
An update to Blockfolio actually added this feature in the past few days. To show balance in ETH and it is using this symbol. However it might make sense to show ETH. Lots of sites show USD instead of $

**Comment by geleeroyale** [comment]
Ok maybe I should scroll down more before starting to fix issues. I saw that @deamme referenced this issue already in a PR. 
- changed all instances of Ξ to ETH and rearranging the order (first number then ETH)

If you go for @deamme 's  commit, don't hesitate to delete the branch

**Comment by vojtechsimetka** [comment]
Fixed in #281
