### ISSUE TITLE
Canceled DACs and Campaigns should fall off the face of the DApp

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#276]
I'm not sure if this has happened yet with Taylors Test DAC but make sure that thing is not visible from the interface! 

Delete or hide test and canceled DACs and campaigns from the main interface.

**Comment by vojtechsimetka** [comment]
Not an issue, canceled Campaigns are hidden but yallor can not cancel his because he lost the key password. As for DACs, yes that needs to be reanabled.

**Comment by GriffGreen** [comment]
looks like we have an opportunity to test out our censorship strategy

**Comment by vojtechsimetka** [comment]
Yeah there is already issue #266

**Comment by krrisis** [comment]
Uhm could we plz do this with Milestones too? (not in that other issue that just got closed), very messy here: https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ

**Comment by vojtechsimetka** [comment]
Fixed in develop.
