### ISSUE TITLE
ETH missing from the list of currencies

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#279]
One of the most common currencies for us to use is ether! And it's exchange rate is really easy! :-D Sometimes when we are doing an old milestone, the displayed fiat amount it doesnt match the agreed upon ETH. This is a pretty big problem that could be easily over come if ETH was an option.
 
<img width="326" alt="screen shot 2018-04-05 at 5 01 37 am" src="https://user-images.githubusercontent.com/14945613/38345359-f4803b8a-388e-11e8-9984-3c9a67b5e88c.png">

**Comment by GriffGreen** [comment]
Yep! Mostly a cosmetic issue.

**Comment by GriffGreen** [comment]
0.1 ETH Bounty

**Comment by GriffGreen** [comment]
bonus for adding bitcoin to the list... :-D

**Comment by satyavh** [comment]
Adding BTC (or any other currency) is actually really complicated and needs a lot of changes....
