### ISSUE TITLE
The DApp connection does not inform user when the feathers connection is lost

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#280]
So i try hard not to log out via the back button or refresh cause i have a really long password :-P

But i do get logged out when i leave the tab open for a while, even though the button in the corner gives me the option to lock the wallet. 

i would expect that to still say "Lock Wallet" when it idles out while i'm still on the same page, but when I navigate to another page, i would expect it to say "Unlock Wallet" because of the navigation... that it would check to see if the wallet is locked or not.

**Comment by vojtechsimetka** [comment]
Known issue, linked to #298

**Comment by deamme** [comment]
Should be fixed in https://github.com/Giveth/giveth-dapp/pull/310
