### ISSUE TITLE
Cannot edit milestone without changing fiat calculator values

### ISSUE THREAD

**Issue by mex20** [Giveth/giveth-dapp#282]
**Issue:** When editing a milestone that the proposer created in the DApp and clicking the save button, the DApp will indefinitely hang with the save button displaying "saving". The user is able to navigate to other areas of the DApp in this state. 

**Steps to reproduce:**
1. Create a milestone and complete all of the fields, while adding a date and amount of fiat currency to be converted to ETH.  (In the discovery of this issue, I used 2000 EUR on 31/03/2018)

2. Propose milestone

3. While milestone is awaiting acceptance or denial by the campaign manager, click the edit button on the milestone.

4. Change the body of the milestone, but do not change the values in the fiat converter.

5. Click save

6. DApp indefinitely hangs on "saving" the edits.

**Notes on the bug:**
When the proposer tries to edit a milestone without changing the fiat conversion values and the DApp hangs, the DApp will  the console will show some errors about the conversion rate not being correct. This issue still occurs after the campaign manager approves a milestone, and after the proposer marks the milestone "completed" after the campaign manager has accepted the proposed milestone.

**Workaround:**
When this error occurs, the proposer can work around the issue by changing both the day for the fiat conversion, and the currency for fiat conversion. After changing the values in the fiat converter, the proposer is able to successfully save the edit of the milestone. The only caveat is that once the proposer marks the milestone "complete" after the campaign manager accepts the proposed milestone, the proposer is not able to change the any values in the fiat converter which breaks this workaround.

**Browser log:**
[alpha.giveth.io-1523014420956.log](https://github.com/Giveth/giveth-dapp/files/1884034/alpha.giveth.io-1523014420956.log)

**Comment by GriffGreen** [comment]
I wonder if we removed the precision if that would also fix this issue...

**Comment by ljg583** [comment]
I also experienced this issue with this milestone: [](https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/ZHjpvm44tYxGZfkw)

![screen shot 2018-04-07 at 4 07 40 pm](https://user-images.githubusercontent.com/35914957/38455837-d562e2f2-3a7d-11e8-9d84-d6c4f413b4e3.png)

- I copied the ETH amount from the original proposed milestone

- Changed the currency to EUR

- Changed it back to USD 

- Pasted the original ETH amount into the ETH amount field

And then it would save

**Comment by vojtechsimetka** [comment]
Can you verify this fixed the issue? @GriffGreen @mex20 @ljg583 @eduadiez  https://5acc69f502ed832f55d4c242--giveth-dapp-alpha.netlify.com

**Comment by vojtechsimetka** [comment]
Fixed in 340ca1eb1b0cfae334026954c73576651104c19e, verified by @eduadiez
