### ISSUE TITLE
Create extra tab in 'my milestones' 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#283]
Currently 3 tabs, all rejected Milestones are stored under active.
Would make more sense to create a 4th one 'rejected' OR put both canceled & rejected under same tab and label as 'inactive'.

![image](https://user-images.githubusercontent.com/6533925/38446301-87d3c0b4-39f7-11e8-8016-753cae4b29a5.png)

**Comment by vojtechsimetka** [comment]
Yep thx for creating the issue, i’ve almost finished it. Nevertheless in the nextrelease you will be able to delete rejected milestones or repropose them.

**Comment by GriffGreen** [comment]
ooooo thats a cool feature!
