### ISSUE TITLE
image adaptation milestones

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#285]
FOR DEMO 

set image restrictions or recommended size for milestone images so they don't show just a fraction of it 
would also make images obligatory OR add giveth logo as placeholder if no image - looks like crap without any

-> there is some code you can steal from the swarm city dapp for automatic image resizing, plz contact faffy dee or kingflurkel

**Comment by perissology** [comment]
I like the default image. Maybe just set to the campaign img?
