### ISSUE TITLE
Support nested bullet points in DAC, Campaign and Milestone description

### ISSUE THREAD

**Issue by dapplion** [Giveth/giveth-dapp#294]
Although the milestone text editor provides the functionality of indenting bullet point list to multiple levels deep, they are rendered as if they were not indented. Although bullet point lists with multiple levels deep may not be supported at the moment, the UI can confuse the user into thinking they are and mistake the current behaviour as a bug.

**Comment by vojtechsimetka** [comment]
Fixed by @satyavh in f18dc7cc2b77db40b50bb9890901b7c45222c344
