### ISSUE TITLE
Nodejs: possible memory leak detected

### ISSUE THREAD

**Issue by mex20** [Giveth/giveth-dapp#297]
When using the DApp, the following warning is logged:

```
events.js:138 (node) warning: possible EventEmitter memory leak detected. 31 listeners added. Use emitter.setMaxListeners() to increase limit.
a.addListener @ events.js:138
```
When compiling the DApp, the following warning is logged:

```
(node:8744) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x05893e15100ef166b1d55cd87ce15ec5508e5f923576c3d97bd2b8961076b0f4](https://etherscan.io/tx/0x05893e15100ef166b1d55cd87ce15ec5508e5f923576c3d97bd2b8961076b0f4)

**Comment by debragail** [comment]
@mex20 what's the bounty price for this?

**Comment by vojtechsimetka** [comment]
@debragail we are assigning it now. Should be in before next thursday.

**Comment by stefek99** [comment]
I was running `truffle`

`CTRL + c` to kill it

Got the error that you describe.

Might be `truffle` related, not Giveth Dapp related?

```
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBalance
eth_getBlockByNumber
net_version
^C^C^C^C^C^C^L^C^C^C^C^C(node:9035) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
^C^C^C^C^C^C^C^C^C^C^Cnet_version
eth_getBalance
```

**Comment by vojtechsimetka** [comment]
Thanks @stefek99. We also think this is in one of the libraries we depend on (definitely not truffle). Nontheless, it should be fixed :).

**Comment by perissology** [comment]
I'm 99.99% sure this is in the web3.js lib.

**Comment by debragail** [comment]
is this happening in all versions or is this with the latest build?  Tempted to climb through the branches to find the last stable build.

**Comment by perissology** [comment]
see #356 for more context

**Comment by debragail** [comment]
Was this closed by ovx?

**Comment by vojtechsimetka** [comment]
@debragail no

**Comment by bookmoons** [comment]
I've been trying to reproduce this without success. Is it possible `web3` has updated?

The described mechanism leads me to believe this test script should cause the warning. It runs 100 contract creations. But it gives me no warning.

```javascript
const Web3 = require('web3')
const { MiniMeToken } = require('minimetoken')

const nodeAddress = 'http://localhost:8545'
const provider = new Web3.providers.HttpProvider(nodeAddress)
const web3 = new Web3(provider)

const address = '0xA7f08778123787f2b9EdFe83843d4C02E9d8B97f'
const tokens = []
for (let i = 0; i < 100; i++) {
  const token = new MiniMeToken(web3, address)
  tokens.push(token)
}
```

**Comment by bookmoons** [comment]
I've been trying to reproduce this without success. Is it possible web3 has updated?

The described mechanism leads me to believe this test script should cause the warning. It runs 100 contract creations. But it gives me no warning.

```javascript
const Web3 = require('web3')
const { MiniMeToken } = require('minimetoken')

const nodeAddress = 'http://localhost:8545'
const provider = new Web3.providers.HttpProvider(nodeAddress)
const web3 = new Web3(provider)

const address = '0xA7f08778123787f2b9EdFe83843d4C02E9d8B97f'
const contracts = []
for (let i = 0; i < 100; i++) {
  const contract = new MiniMeToken(web3, address)
  contracts.push(contract)
}
```

**Comment by bookmoons** [comment]
I'm also not seeing a warning in log output, but there a lot of messages and I'm not really sure where it's supposed to show up.

**Comment by vojtechsimetka** [comment]
Thank you @bookmoons , it does seem that the error is no longer present. Let me thoroughly verify again and I'll come back.

**Comment by mroberts10** [comment]
Hey Vojtech, has this issue been sorted? Was there some sort of web3 update?

**Comment by mroberts10** [comment]
Kay can you remove the funds

**Comment by geleeroyale** [comment]
Someone has to claim them - do it @mroberts10 =)

Please follow this procedure:

1 - register on openbounty.status.im to link your github account to a metamask account
2 - sumbit an empty PR with the following comment: fixes #[your issue number] (without the square brackets)
3 - Ping @geleeroyale, to accept the PR

**Comment by debragail** [comment]
I believe this is a known issue with node that I ran into with @status-open-bounty last year.

**Comment by arbreton** [comment]
@geleeroyale Can this be closed?

**Comment by geleeroyale** [comment]
We should keep it open as a reminder (or make a category with stale status bounties) ... the bounty never was claimed, so there are still 1.9ETH sitting in the bounty contract

**Comment by debragail** [comment]
what's the status?

**Comment by aminlatifi** [comment]
@geleeroyale I couldn't find this issue in giveth gitcoin active issues! Is it over? Can we close this issue?

**Comment by geleeroyale** [comment]
This issue is ancient. There are almost 2 Eth, sitting in a smart contract at Status. You can close it if you want @aminlatifi - I don't think these bounties will ever be paid out. We asked for that, but seems like the Status tram straight up abandoned it without ever releasing the funds that were on there :-(

**Comment by corpetty** [comment]
Who is the repo owner for this bounty? I have the admin account that can release the funds (it took some digging) but it is a multisignature wallet. The other signer is the owner of this repo.

**Comment by corpetty** [comment]
The address in question that I'm looking to track down is this one: https://etherscan.io/address/0x701d0ECB3BA780De7b2b36789aEC4493A426010a.

You can find me at security@status.im, `security` on status, or `petty#7979` on discord. I am currently in contact with @aminlatifi on Discord so you can go through him if need be. 

I will also monitor this thread.

**Comment by corpetty** [comment]
Funds have been drained and @geleeroyale has control of them. This can be closed, and we sincerely apologize for the wait and inconvenience of this.

**Comment by aminlatifi** [comment]
Thanks @corpetty
