### ISSUE TITLE
Double Email Notifications

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#305]
I love the email notifications, they are one of the most important parts of the DApp and are working really well! 

I couldn't find any documentation on when what emails are sent out to double check this. 

I am starting to get double email notifications for some milestones... maybe because i am the Campaign manager and the reviewer?

These 2 emails were sent 8 seconds apart, and are slightly different... maybe a filter for this circumstance can be put in place?

<img width="492" alt="screen shot 2018-04-15 at 3 09 34 pm" src="https://user-images.githubusercontent.com/14945613/38778796-1f32feb6-40bf-11e8-8453-a2c82eda115c.png">

<img width="340" alt="screen shot 2018-04-15 at 3 09 26 pm" src="https://user-images.githubusercontent.com/14945613/38778797-1f5e3c16-40bf-11e8-8efb-aefa0c7238c3.png">

<img width="494" alt="screen shot 2018-04-15 at 3 09 50 pm" src="https://user-images.githubusercontent.com/14945613/38778795-1f0a123a-40bf-11e8-8a5b-4463f1f07a5e.png">

**Comment by vojtechsimetka** [comment]
@satyavh can you comment? Is this a bug?

**Comment by perissology** [comment]
yes, this is a bug w/ how the notification code in feathers. Already an issue. Email is re-sent everytime a milestone is edited

**Comment by vojtechsimetka** [comment]
This was fixed by @perissology during rewrite.
