### ISSUE TITLE
Double Dating on Milestones - Awkward!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#314]
When we have specified dates listed in the milestone like so: 
https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/Lzyi7LXmEMEhXeBD

<img width="899" alt="screen shot 2018-04-20 at 12 21 01 pm" src="https://user-images.githubusercontent.com/38163206/39046324-0cae33e8-4496-11e8-8bec-b2c6e6b07a28.png">

There is no need for this date down below!
<img width="906" alt="screen shot 2018-04-20 at 12 21 12 pm" src="https://user-images.githubusercontent.com/38163206/39046330-107d33fc-4496-11e8-9507-f463dc999a94.png">  

The part in red "This date defines the eth-fiat conversion rate" - that is a LIE when there's multiple conversions. Can we omit this second date field when the dates are itemized above? @vojtechsimetka @satyavh

**Comment by vojtechsimetka** [comment]
That date is the date of the creation of that milestone. I guess the description is wrong but this will change soon with implementation of bridge.

**Comment by lorelei1** [comment]
I get that. here's another milestone with the same issue: https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/iuPIbf9RVSJWuJZv

**Comment by lorelei1** [comment]
Ok this is a slightly different issue but still about the Milestone date field: Quazia's milestone that states he's being rewarded €600, but the milestone date field below says the conversion happens april 16th giving him only €253. 
<img width="723" alt="screen shot 2018-04-21 at 6 38 43 pm" src="https://user-images.githubusercontent.com/38163206/39086615-860162b6-4594-11e8-99f1-30e490696fa0.png">

<img width="798" alt="screen shot 2018-04-21 at 6 38 14 pm" src="https://user-images.githubusercontent.com/38163206/39086605-655222ee-4594-11e8-8be8-3908e679a37b.png">

This needs to get fixed in the migration! Not sure what the fix for this is, but we need the milestones to make more sense at a glance, especially when it comes to payment details.

**Comment by vojtechsimetka** [comment]
Thank you, yeah we should look at it during migration.

**Comment by lorelei1** [comment]
sounds good thank you!

**Comment by lorelei1** [comment]
keeping track here of other milestones with the same fix! https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/kOtI8FCcnjPKsmCw

https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/2cS3TaQDBWXtB6ev

**Comment by vojtechsimetka** [comment]
Partially fixed in a790dff1e9f45ed16b98b6ced1553b66221af49b
