### ISSUE TITLE
Milestone needs a conversion date!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#316]
No exact date of exchange on Kris's milestone here. Quick fix! Need it for transparency. 
<img width="727" alt="screen shot 2018-04-21 at 7 21 23 pm" src="https://user-images.githubusercontent.com/38163206/39087015-2e072be4-459a-11e8-9732-865eee42f7e0.png">

https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/K8KPIXYi5B2N1h6x

Of course it lists above in the milestone title what week it was, but we need the exact date of conversion! 
@krrisis @vojtechsimetka , can we make this happen?

**Comment by vojtechsimetka** [comment]
not a DApp issue, that is something @krrisis should provide.

**Comment by krrisis** [comment]
It's always the Friday.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vojtechsimetka** [comment]
So @lorelei1 if the description will be modified to say the date of exchange which is Friday 9th of February, would that be a solution for you?

**Comment by lorelei1** [comment]
@vojtechsimetka absolutely! 
yes, @krrisis i know that it has been on fridays, but it looks cleaner and more trustworthy for anyone else looking in at our processes if everything is transparent and specific! especially if not everybody is using fridays.

**Comment by vojtechsimetka** [comment]
So the task at hand is: During the migration, modify the description to say the date of exchange is Friday 9th with a rate of 675.40€.

**Comment by lorelei1** [comment]
yeah that's great, thanks!

**Comment by vojtechsimetka** [comment]
Partially fixed in a790dff1e9f45ed16b98b6ced1553b66221af49b

**Comment by vojtechsimetka** [comment]
Fixed in b910a3f8887a71ab0e7f1d44af0bcbfb13e75182
