### ISSUE TITLE
Campaigns show up strangely on bigger screens

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#326]
On a 17" screen the Campaigns are sticking to each other, other times of the day I saw them all outlined to the left for some reason. See screenshot below. 

![image](https://user-images.githubusercontent.com/6533925/39329277-1b38993c-499e-11e8-9f1d-f9c9b7518eb4.png)

**Comment by vojtechsimetka** [comment]
Does this also happen in the develop.giveth.io?

**Comment by krrisis** [comment]
Nope! So I guess that means it is fixed in the next release and that you can close this one :)

**Comment by vojtechsimetka** [comment]
Reopen if the issue appears again.
