### ISSUE TITLE
Make expense visuals clickable

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#328]
When you upload items to a Milestone (mostly expenses), you cannot click the visual. 
Mostly the details of the expense are .. in the visual. 
So when creating Milestones you always need two screens open all the time. 
Solution: when clicking the visual open in pop-up with an 'X' at top right hand side to close. 

![image](https://user-images.githubusercontent.com/6533925/39329556-f79bdccc-499e-11e8-98bd-4b64c01953db.png)

**Comment by krrisis** [comment]
Same thing with visuals in the text, you cannot click to enlarge this, so you cannot verify if the proof is correct. 
example of such a Milestone here https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5ba5e19c910d22748d87a82c

**Comment by horus2021** [comment]
I dealt with dapp to see how can I improve it.

**Comment by horus2021** [comment]
In redesign, "Add an item .." has been removed from milestone UI, so this issue is outdated.
