### ISSUE TITLE
Back button uses calls on browser back function

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#329]
non-urgent issue but can be annoying during demos: 

When you link to a Milestone or a Campaign from somewhere (like here below) the 'back' arrow does not function, as it seems call on the back function of the browser. When you click the below link it opens in a new tab, so when you hit 'back' nothing happens, instead of going to the campaign to which this milestone is linked. 
eg: click here on the back arrow, nothing happens: https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/Oo3yG9msdYA78X78

**Comment by RnbWd** [comment]
I can work on this

**Comment by RnbWd** [comment]
I have a fix to this issue with the back button that goes to a lower route based on the URL. This can be implemented as the default behavior for the back button, but when adding new Routes, the functionality of the back button will have to be considered to prevent users from being stuck at a dead urls. The only dead url I could find was: `/campaigns/:id/milestones`, so I added a redirect Route for it to go to `/campaigns/:id/milestones`

**Comment by vojtechsimetka** [comment]
This was fixed in the #403
