### ISSUE TITLE
'Create' date missing for older Milestones under 'my Milestones'

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#330]
See screenshot, older Milestones are missing the date. 

![image](https://user-images.githubusercontent.com/6533925/39329967-4b310e1a-49a0-11e8-9df8-ac46e60a37d0.png)

**Comment by vojtechsimetka** [comment]
If this truly is an issue we could add the date retrospectively in the migration (reconstruct it from the transaction). What do you say @perissology ?

**Comment by vojtechsimetka** [comment]
Fixed in ff11e4508222de587c47cff2ed94fc30b4ed2ce6
