### ISSUE TITLE
All giveth DApp mail keeps ending up in spam

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#331]
Whatever I change, this keeps happening as the current set-up is a hard **no** for outlook.com (and I guess most mail servers).
Current set-up: 'no-reply=giveth.io@mg.giveth.io' pretends to be 'no-reply@giveth.io'

Solution: 
- send mails from no-reply@giveth.io directly 
- if rrreally not possible for some reason, at least simplify this address: 'no-reply=giveth.io@mg.giveth.io', might help too, but I know it's the 'on behalf' that is causing the issue.

![image](https://user-images.githubusercontent.com/6533925/39330398-cc9aa85c-49a1-11e8-9e96-967abee68571.png)

**Comment by vojtechsimetka** [comment]
@krrisis this is resolved, right?

**Comment by krrisis** [comment]
sorry for late reply, just changed back to hotmail to test it, will report back when I get a new notification. On gmail it works (again) in any case.

**Comment by vojtechsimetka** [comment]
This works for me on my test hotmail account, closing
