### ISSUE TITLE
Add 'edit' button to Milestones in various places

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#334]
Crucial (and very annoying) one!

Current behavior: 
- only possible to edit a Milestone by going to a Campaign, look at the Milestone overview and hit the pencil on the Milestone

Desired: 
- add an edit button IN the Milestone -- most people are asked to edit their Milestones by reviewers who send them links 
- add an edit button next to Milestones in 'My Milestones' --- this is the other logical place where you go to edit your Milestones

**Comment by vojtechsimetka** [comment]
This is done in develop #322 by @twmilli fixing #241
