### ISSUE TITLE
Issue with fiat amount in this Milestone

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#336]
Shows up as 'undefined undefined'

https://alpha.giveth.io/campaigns/OcKJryNwjeidMXi9/milestones/iMrCZbvlmFvjAgKA

**Comment by ascariandrea** [comment]
I can work on this!

**Comment by vojtechsimetka** [comment]
There are values missing in the items array for this milestone:

- selectedFiatType
- fiatAmount
- conversionRate
- etherAmount

**Comment by ascariandrea** [comment]
The object creation should be prevented when no such data are available on item creation

**Comment by vojtechsimetka** [comment]
Should be handled in ff11e4508222de587c47cff2ed94fc30b4ed2ce6
