### ISSUE TITLE
Donate Popup improvements

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#339]
The current donate button is hacked together so we can start testing the bridge. We need to add the following actions to the button:

- [x] - explanation text that this is going through a bridge, so there will be a minor delay.
- [x] - if the user has a `giverId`, we direct the user to call `donate` on the givethBridge otherwise we call `donateAndCreateGiver` on the givethBridge contract.
- [ ] - allow donations of any token in `config.tokenAddresses` that is in the user's wallet. This is a tx on the foreign chain and only involves calling `liquidPledging.donate` method.
- [x] - allow proxy donations. They can enter an address to donate on behalf of. We should lookup the address in feathers. If found & the user has a `giverId`, we direct the user to call `donate` on the givethBridge otherwise we call `donateAndCreateGiver` on the givethBridge contract.

**Comment by vojtechsimetka** [comment]
Closing as point 3 is part of #484
