### ISSUE TITLE
Photos not saving while editing a proposed milestone

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#344]
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/ZHjpvm44tYxGZfkw

This milestone has been accepted by campaign manager and proposer and is waiting for review
I attempted to add a photo
The photo seemed to be uploaded, and the milestone updated
When I reopen the milestone the photo is not there
There are no visible errors in the developer tools

While editing the milestone, the photo uploads:
![screen shot 2018-05-05 at 11 10 09 am](https://user-images.githubusercontent.com/35914957/39661216-9c719fa8-5056-11e8-9919-5c913607c16a.png)

The milestone is saved and updated:
![screen shot 2018-05-05 at 11 11 06 am](https://user-images.githubusercontent.com/35914957/39661211-9771d2b6-5056-11e8-9dcc-8356470e7bbd.png)
When updating the milestone, no errors are reported:
![screen shot 2018-05-05 at 11 16 37 am](https://user-images.githubusercontent.com/35914957/39661202-85e9eb00-5056-11e8-91b3-6b39a823d06e.png)
When I reopen, there is NO PHOTO!!! :( 👎 
![screen shot 2018-05-05 at 11 11 28 am](https://user-images.githubusercontent.com/35914957/39661207-93f80c4a-5056-11e8-9fcc-e152f2bc5c6d.png)

I have signed out and back in to my account and attempted this 5 or 6 times

**Comment by perissology** [comment]
this is fixed
