### ISSUE TITLE
Review email does not link correctly 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#345]
Mail links to https://dappmailer.giveth.io/my-milestones and gives an error 

![image](https://user-images.githubusercontent.com/6533925/39732561-2ae4c210-523c-11e8-8014-c6a78c8f28d7.png)

**Comment by vojtechsimetka** [comment]
Can you copy the link here?

**Comment by krrisis** [comment]
link is in description above, links to https://dappmailer.giveth.io/my-milestones

**Comment by satyavh** [comment]
Was this on alpha?

**Comment by krrisis** [comment]
yup

**Comment by krrisis** [comment]
this is fixed I see. thx!
