### ISSUE TITLE
Milestone view is showing "1 eth = undefined"

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#348]
Check it out: https://alpha.giveth.io/campaigns/fzOahNwFVyY7qLTI/milestones/2gKpRTLvXeRZDDne

<img width="828" alt="screen shot 2018-05-08 at 8 17 44 pm" src="https://user-images.githubusercontent.com/14945613/39794006-efae01d6-52fc-11e8-85ea-b3422b74626f.png">

**Comment by vojtechsimetka** [comment]
Known issue for some of the old milestones, this PR likely fixes it https://github.com/Giveth/giveth-dapp/pull/340 I'll check ASAP

**Comment by lorelei1** [comment]
not sure if this is part of the same bug, but i noticed also on this one i was unable to click to expand the attached proof

**Comment by vojtechsimetka** [comment]
Should be handled in ff11e4508222de587c47cff2ed94fc30b4ed2ce6
