### ISSUE TITLE
Community or Campaign creation problem - hang in pending state.

### ISSUE THREAD

**Issue by assiomatica** [Giveth/giveth-dapp#351]
I have cloned giveth and feathers-giveth , installed and run in local as in README instructions but when I try to create a community after I confirm the transaction the app hangs on Saving ...

from the testrpc console Seems the transaction is performed but don't get confirmed.

Some idea?

Thanks

Antonio

**Comment by vojtechsimetka** [comment]
Interesting, any more information? Just tried locally and it works with the latest develop.

**On feathers have you done:** 
window 1:
```
yarn deploy-local
yarn ganache-cli 
```
window 2:
```
yarn start
```

**Comment by assiomatica** [comment]
Hi
thanks for message

PodioBoxMacBookPro:feathers-giveth ninnicasula$ yarn deploy-local

yarn run v1.6.0

error Command "deploy-local" not found.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this
command.

at the beginning of package.json:

{
  "name": "feathers-giveth",
  "description": "Real-time json cache for blockchain data.",
  "version": "*0.0.0*",

Seems I have cloned the wrong version.
I will retry with the develop branch

Antonio

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/

**Comment by assiomatica** [comment]
I have cloned the develop branch

followed your commands but now:

[image: image.png]
hanged on

Best
Antonio

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/

**Comment by assiomatica** [comment]
![download 4](https://user-images.githubusercontent.com/2242177/40130937-be3ec0f8-5938-11e8-8af1-e7aad5cb5883.jpeg)

**Comment by assiomatica** [comment]
I am able now to create a campaign after a delete and re-clone all,
but now when I try a donation nothing happen and this message appear on browser console (giveth-dapp):

TypeError: wallet.signTransaction(...).then is not a function

**Comment by vojtechsimetka** [comment]
Yeah you can't donate in the local environment. We are in process of creating a local version of the bridge. For now you can connect to the develop environment by setting environment variable REACT_APP_ENVIRONMENT=develop or changing that in the dapp/src/configuration.

**Comment by perissology** [comment]
that error is super weird. @satyavh was getting the same thing saying that signTransaction is not a promise. Maybe when signTransaction is called and the account doesn't have a provider, then it doesn't return a promise. If so, we should fix this in web3. I'll take a look

**Comment by assiomatica** [comment]
Hi I have solved changing the function in this way:

signTransaction(txData) {
    if (!this.unlocked) return Promise.reject(new Error('Locked Wallet'));

    if (!txData.gasPrice || (!txData.nonce && txData.nonce < 0) ||
!txData.chainId)
      return Promise.reject(new Error('gasPrice, nonce, and chainId are
required'));

    const accounts = mapGet.call(mapAccounts, this);

    return Promise.resolve(accounts.wallet[0].signTransaction(txData));
  }

this works

Antonio Casula

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/

**Comment by vojtechsimetka** [comment]
@assiomatica wrote:
> signTransaction(txData) {
>  if (!this.unlocked) return Promise.reject(new Error('Locked Wallet'));
> 
>     if (!txData.gasPrice || (!txData.nonce && txData.nonce < 0) ||
> !txData.chainId)
>       return Promise.reject(new Error('gasPrice, nonce, and chainId are
> required'));
> 
>     const accounts = mapGet.call(mapAccounts, this);
> 
>     return Promise.resolve(accounts.wallet[0].signTransaction(txData));
>   }
> 
Not sure what I am looking at but if it solves some error in the DApp please make a PR.

> BTW, I should like to define a new environment different from develop.
> may I modify the deploy.js script to work in a private blockchain or on a
> different instance on  rinkeby or ropsten?
> and change the configuration file accordingly?

Even better you can just inject your own through `.env` or `.env.local` file as described in https://github.com/Giveth/giveth-dapp#configuration . This way your configuration will be outside of files tracked by git.
