### ISSUE TITLE
Editing Proposed Milestone as Campaign Manager modifies the Recipient address

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#353]
## Description of the Issue:
If Campaign Manager edit's milestone that is being proposed, the "Recipient address is different from my address" is always toggled off overwriting the original milestone recipient's address with the Campaign Manager's address. However, if manually toggled off the correct address appears.

## Expected Behavior:
The "Recipient address is different from my address" should be toggled on/off correctly if the address of the person who edits the milestone is different/same than the recipient address.

## To replicate:
1. Create campaign with account A
2. Propose milestone with account B in the campaign
3. With account A edit the milestone as it is being proposed

## Demonstration of the error:
Proposed Milestone:
<img width="895" alt="screen shot 2018-05-20 at 11 03 10" src="https://user-images.githubusercontent.com/7974813/40277446-5e7ad50a-5c1f-11e8-8d09-861ba7df02a1.png">

What Campaign Manager see when they edit Proposed Milestone.
<img width="773" alt="2" src="https://user-images.githubusercontent.com/7974813/40277470-a8675530-5c1f-11e8-8401-bd20ec419ae4.png">

If they click on "Recipient address is different from my address" the correct recipient address appears.
<img width="769" alt="screen shot 2018-05-20 at 11 04 00" src="https://user-images.githubusercontent.com/7974813/40277476-cf7ad2fa-5c1f-11e8-82e4-b0ded7aeb59c.png">

## Original issue text:
Hi guys, this week we had 3 milestones that got paid out to the wrong address. https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/D8lvi7jf2RD04onu
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/hN3m6N8S505dCGwU
and
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/VvpdpidCezmpoZVW   <--that's mine! I want my points dangit! 
All of these despite clearly being for Davy, Yalda, and I, were sent to Griff's address, and I think this happened when he approved them as a campaign manager.

**Comment by perissology** [comment]
hmm, considering that the rest of the proposed milestones went through just fine (mine included), I'm not sure it happened when approving them.

Are you sure that they were entered with the correct recipient to begin with? This sounds more like a human error to me.

**Comment by GriffGreen** [comment]
yes it was my error, but we should probably change the default. I didn't notice the default was that when the campaign manager edits a milestone the "Recipient address is different from my address" button is selected to "X"

It needs to be checked yes every time for every edit, so that it goes to the originally selected address
<img width="992" alt="screen shot 2018-05-18 at 7 24 47 pm" src="https://user-images.githubusercontent.com/14945613/40263036-a8074c92-5ad2-11e8-8d1e-175ed01ca87b.png">

**Comment by perissology** [comment]
ah, that makes sense. 

Ya, that "Recipient address is different from my address" should always be enabled if the campaign manager is editing a proposed milestone

**Comment by vojtechsimetka** [comment]
I'm actually not sure this is causing issues, I've been testing it but could not replicate.
