### ISSUE TITLE
The Milestones with videos have a weird scrolling requirement

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#354]
We have to scroll to view the videos in a milestone: 
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/RnIhy9VCYNCC1nam 

I am aware that this is an ever evolving process... in fact, i hope that we will have the wall of fame integrated straight into the DApp some time soon, but currently, its a bit embarrassing to show external people video milestones (which are nearly half of the milestones we have!) 

To raise the quality of the dapp the Gov campaign is throwing some ETH to make this issue happen!

For this bounty to be complete, the videos from the wall of fame need to be nicely embedded, no need for scrolling and the features that are there now are not lost, autoplay still happens, etc

**Comment by vojtechsimetka** [comment]
I don't think this is a problem, it's rather expected behaviur. It depends what do you put in as a link for the video. If you put in the video page, the whole page will be in that link. If you put in directly the link to the video on firebase then you only see the video. Here is a link to a milestone demonstrating both:

https://develop.giveth.io/campaigns/8zjKq5LPO2gnrYT4/milestones/O1LqGUOHyi2LO4lh

All you need to do is use the firebase link instead.
**URL to video page:** https://fame.giveth.io/view/-LAF7ZDmK7dAMf5zsRkv
**URL to video directly:** https://firebasestorage.googleapis.com/v0/b/givethvideowalloffame.appspot.com/o/GVWOF_v2%2F16_4_2018%2FJoshua%20geeks%20on%20audio%20for%20the%20Giveth%20mini-documentary?alt=media&token=349b31f9-3442-4262-a20e-a528210598fb

**Comment by GriffGreen** [comment]
hmmmm well then thats an easy fix. @geleeroyale is there an easy way to cancel the bounty?
