### ISSUE TITLE
cannot create campaign without donating?

### ISSUE THREAD

**Issue by parkwil89** [Giveth/giveth-dapp#358]
In trying to follow the instructions but have not made it past step 2 successfully yet. I am attempting to complete a campaign but to create a campaign it says I have to donate? So to receive a payment I have to first give ETH? this is on the develop.giveth.io website

Then further down I see I have to fund my campaign? I don't understand how this plays into me trying to get paid for a bounty.

**Comment by perissology** [comment]
what instructions? You shouldn't need to do this for a bounty, what bounty & who asked you to create a milestone?

**Comment by parkwil89** [comment]
https://www.loomio.org/p/ewJSymUx/dogfooding-making-2-milestones-for-the-price-of-one

Those are the instructions passed to me when I asked how to collect on a bounty. Griff proposed a bounty for me for work on the nest grant submission. 

Sorry for any confusion I'm causing!

**Comment by perissology** [comment]
ah, got it...

does it say you have to donate? or that you need eth in your wallet? My guess is, it's the later.

you'll need to get eth from both of the following places.

http://faucet.ropsten.be:3001/
https://faucet.rinkeby.io/

**Comment by parkwil89** [comment]
Success! thank you
