### ISSUE TITLE
error message when donating to milestone on giveth.develop.io

### ISSUE THREAD

**Issue by parkwil89** [Giveth/giveth-dapp#361]
When I try to donate to my milestone as per the instructions on loomio, I get an error message and don't seem to have any success donating. Same for when I try to donate to the campaign.

There was no point where I was asked to approve the milestone as per step 4 in the directions below. Maybe that has something to do with it?

https://www.loomio.org/p/ewJSymUx/dogfooding-making-2-milestones-for-the-price-of-one

**Comment by vojtechsimetka** [comment]
@parkwil89 I think it is because your wallet does not have enough ropsten ETH in it. What does the error say? Does it give you an option to report the error?

**Comment by vojtechsimetka** [comment]
@perissology The same error occured for @ljg583 . Here is the report:

**Description of the Error:**
Something went wrong with your donation.

**Transaction link:**      https://ropsten.etherscan.io/tx/0xf45e7d588505273793447edb9dc830f62ae5862ab6bb26875665a50ad9fb9302 => Error: Transaction ran out of gas. Please provide more gas:
{
  "blockHash": "0x447637410050b5c897be96b4d0ec105beb0ea2524dc781d175c0ebdbfd4ae86a",
  "blockNumber": 3318605,
  "contractAddress": null,
  "cumulativeGasUsed": 67920,
  "from": "0x51e37e3716c0ed418a90e519ceee395d8f6decb9",
  "gasUsed": 22710,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x8588ee5e97e06ba863fdb2ebc5b523246d459638",
  "transactionHash": "0xf45e7d588505273793447edb9dc830f62ae5862ab6bb26875665a50ad9fb9302",
  "transactionIndex": 2,
  "events": {}
}
     
I attempted to donate to my campaign, which is how I assume I will fund my milestone.  I tried this 3 times with signing in and out in between.  This is the fail from Etherscan: https://ropsten.etherscan.io/tx/0x7395989590c44ebe2b2f61fc37f8c16802a76759f96b1bc98719dc9dde540d5a

**Comment by perissology** [comment]
This was a bug in the donate button. You can see in the above tx that `idGiver` was 0, which will throw.

Fixed in bc6046da6388a8018167badf7d5d2a1350ff70cd
