### ISSUE TITLE
Cannot withdraw from milestone

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#362]
on `develop.giveth.io`

tx fails with error:
`Error: gas required exceeds allowance or always failing transaction`

reproduce:
create and fund a milestone
bring to completion until you see the `$withdraw` button
try to withdraw, it will throw

My wallet balance at time of filing issue:
Rinkeby ETH balance: 18.7109567364 ETH
Ropsten ETH balance: 0.688664504 ETH

**Comment by perissology** [comment]
fixed in b5fe51f9e42fd24239716b650512b72aeb54da10.

note: you may still get an error in the ui, but check etherscan as the tx should be sent correctly and the ui will update shortly despite an error being shown
