### ISSUE TITLE
Saving Bar of Death 

### ISSUE THREAD

**Issue by YalorMewn** [Giveth/giveth-dapp#363]
Develop.Giveth.Io

Saving my Milestone I got the spinning button of death. Saving button just loads forEVER. 

Here's the console info. 

<img width="554" alt="screen shot 2018-05-28 at 4 12 31 pm" src="https://user-images.githubusercontent.com/34845103/40618554-2293406c-6292-11e8-83d8-fc51ff9aad99.png">

**Comment by perissology** [comment]
note to self: maybe the web3-provider-engine NonceTracker isn't working properly. If we see more nonce errors we'll have to remove it.

**Comment by vojtechsimetka** [comment]
This did not happen since reported. Closing for lack of evidence that this is actually a bug.
