### ISSUE TITLE
Unclear error when trying to donate more ETH than the address has

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#366]
**Description:**
If user tries to donate more than they have in their bridged address the donation fails saying Something went wrong with your donation.

**The corresponding error when reporting:** 

>       Description of the Error:
>       Something went wrong with your donation.
> 
>       Transaction link:
>       https://ropsten.etherscan.io/tx/undefined => Error: Unknown address - unable to sign transaction for this address: "0x53516256736bebf6b5acd3aba9994a064247cf9d"

   

**Correct behaviour:**
The donation popup should show how much ETH user has on foreign network and should only allow that much + the tx fee.

**Comment by perissology** [comment]
also ran into this error trying to withdraw from the wallet view. Something to do with either the incorrect web3 instance, or the account not being added to the instance

**Comment by vojtechsimetka** [comment]
This is solved for donations, have not seen the error in a while. Closing
