### ISSUE TITLE
List of supported exchange rates should be retrieved from feathers service

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#368]
Rather than having the list of supported exchange rates hardcoded in [`/src/components/RateConvertor.jsx`](https://github.com/Giveth/giveth-dapp/blob/develop/src/components/RateConvertor.jsx) and [`src/components/views/EditMilestone.jsx`](https://github.com/Giveth/giveth-dapp/blob/develop/src/components/views/EditMilestone.jsx) it should come from feathers.

**Comment by wildaces215** [comment]
Is this open?

**Comment by vojtechsimetka** [comment]
Yes

**Comment by wildaces215** [comment]
Ok I would like to take it! Should the data come from an api?

**Comment by wildaces215** [comment]
That way more currencies can be supported

**Comment by vojtechsimetka** [comment]
For the time being I think this list needs to be exposed in feathers and read in UI.
https://github.com/Giveth/feathers-giveth/blob/abdf973189977ab57dbd0568c4410ca2d7a1fbed/src/services/ethconversion/getEthConversionService.js#L4

Satya will rewrite that part soon because it can not fetch historical prices in the current implementation.

**Comment by wildaces215** [comment]
Ok sounds good!

**Comment by perissology** [comment]
looks like this is done
