### ISSUE TITLE
Some wall of fame videos download automatically when embedded

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#372]
**Description:**
We allow users to add video into a dedicated video component in the DAC, Campaing and Milestone description. However, some of these links instead of displaying the video, download the video. This is likely issue with wall of fame, but we should handle these cases as well.

**Example:**
In chrome this milestone will automatically start downloading a video.
https://develop.giveth.io/campaigns/3kgmzoEAZgRt9irx/milestones/GupMCvKDqpl6bt92

Also described in:
https://github.com/Giveth/feathers-giveth/issues/96

**Comment by ljg583** [comment]
This issue is still on-going

Using Chrome, these two videos (links below) automatically start downloading when I attempt to embed the video in a milestone using the Firebase link

[https://fame.giveth.io/view/-LFKGZ8fvPmPagPvcaNe](url)
[https://fame.giveth.io/view/-LFM41v2vg31jmqRkm5W](url)

**Comment by ljg583** [comment]
This video auto-downloads any way I try to embed it in a milestone
Using the Firebase, Share link, etc. they all download

[(https://fame.giveth.io/view/-LGUmUp_RbZkd32HtgAD)]
