### ISSUE TITLE
Created 1 milestone but it ends up showing up 4 times in my milestones page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#373]
<img width="1113" alt="screen shot 2018-06-05 at 7 07 12 pm" src="https://user-images.githubusercontent.com/14945613/40991398-fb31f640-68f3-11e8-97ff-b901c430c8db.png">

**Comment by vojtechsimetka** [comment]
There was a problem with the develop environment and it was sporadically running multiple times. This should be fixed.
