### ISSUE TITLE
Withdraw does not work on overfunded milestone

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#374]
**Description:**
I can't withdraw (collect) from [this milestone](https://develop.giveth.io/campaigns/3kgmzoEAZgRt9irx/milestones/tHcQ84wUFXYutayJ). Due to UI error, the milestone has been overfunded, which may be the reason for failing. Here is console log:
<img width="958" alt="screen shot 2018-06-05 at 22 44 46" src="https://user-images.githubusercontent.com/7974813/41001953-adb7ce02-6912-11e8-9d68-a74d1ce6fb7e.png">

**Comment by vojtechsimetka** [comment]
It does work on another milestone thought so maybe not a concern. https://develop.giveth.io/campaigns/3kgmzoEAZgRt9irx/milestones/UcMRpFmRMufzeYkv

**Comment by perissology** [comment]
at a quick glance, this looks like a bug in feathers possibly. Looks like kay's donation was recorded 2x, but I'm guessing it only happened 1x

**Comment by vojtechsimetka** [comment]
Yeah the duplication of delegation actually happens quite often. I'll create issue for that.

**Comment by perissology** [comment]
should be fixed in develop
