### ISSUE TITLE
After withdrawing from wallet, wallet balance is not automatically updated

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#380]
**Reproduce:**
- withdraw 0.1 ETH from wallet
- wallet balance stays the same, giving the impression nothing is happening
- check transaction to succeed

result: 
Wallet balance only updates after page refresh, this is very confusing for user.

**Expected behavior:**
- withdraw 0.1 ETH from wallet
- wallet balance should drop 0.1 ETH instantly, also after page refresh
- if the tx fails, wallet balance should go back 0.1 ETH

**Comment by vojtechsimetka** [comment]
The Giveth Wallet balance is now irrelevant and not used anymore.
