### ISSUE TITLE
What testing framework/suite should be used for testing?

### ISSUE THREAD

**Issue by wildaces215** [Giveth/giveth-dapp#381]
One thing I've noticed is that there is no testing tools to be used for the project, or at least that I don't know about. What framework should be used then?

**Comment by vojtechsimetka** [comment]
We are using Jest which is default for create-react-app. You can see how it is (rather stupidly) used in models, though we will shortly push to do more automated testing.

**Comment by vojtechsimetka** [comment]
Of course. All you need to do is run `npm run test` or `yarn test`.
