### ISSUE TITLE
Proposing milestones is not possible right now on alpha.giveth.io for anyone

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#385]
When trying to propose a milestone I get these errors:
<img width="836" alt="screen shot 2018-06-16 at 7 32 48 pm" src="https://user-images.githubusercontent.com/14945613/41504181-578b7596-719c-11e8-81a3-a5d159a83ff4.png">
<img width="538" alt="screen shot 2018-06-16 at 7 35 30 pm" src="https://user-images.githubusercontent.com/14945613/41504190-8405f20e-719c-11e8-9613-d4a151ff8cb7.png">

Deam and Lorelei also had errors... here are Deam's:

![image](https://user-images.githubusercontent.com/14945613/41504259-410cf360-719e-11e8-9fbc-d4d676c52046.png)

**Comment by vojtechsimetka** [comment]
I'm on it

**Comment by vojtechsimetka** [comment]
Fixed. For the record, the reason why this happened is because the `data/ethconversion.db` contained record without any rates for yesterday's timestamp.

**Comment by GriffGreen** [comment]
Thx V!! ;-)
