### ISSUE TITLE
"Minimum value must be at least 1" when you select ETH as the currency for a milestone

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#388]
In both alpha and develop! 
<img width="795" alt="screen shot 2018-06-17 at 3 26 56 pm" src="https://user-images.githubusercontent.com/38163206/41512701-e805a582-7242-11e8-8e92-c12a1976739a.png">

We need to be able to have less than 1 eth and still choose 1ETH=1ETH as the conversion because otherwise it puts fiat amounts onto reward daos and bounties and just looks incorrect/awkward.

**Comment by lorelei1** [comment]
also, what's up with this? 
<img width="774" alt="screen shot 2018-06-17 at 3 32 36 pm" src="https://user-images.githubusercontent.com/38163206/41512772-07cbb996-7244-11e8-84c6-ce52285c4ae2.png">

When we know that this is true: 
<img width="641" alt="screen shot 2018-06-17 at 3 30 18 pm" src="https://user-images.githubusercontent.com/38163206/41512744-988ecd0c-7243-11e8-831a-e67b8f159f21.png">

I see that that's fixed in develop but are we compensating for it somehow for alpha milestones? I know it's minuscule, a rounding issue i'm sure, but it adds up.

**Comment by lorelei1** [comment]
Ok. Who will take care of checking those retrospectively? Since I'm a milestone checker already I could help with that, I'd also be happy to propose a group decision to forgive the discrepancies...it'll be over 200 milestones and if we can show that the exchange rate was only off by a margin of a couple euro per eth, i bet a loomio would find our community willing to just forget it in the interest of saving time. ;-)

**Comment by vojtechsimetka** [comment]
We will write script to check it. Thats why I have not made attempt to alter the past rates yet.

**Comment by lorelei1** [comment]
word. thanks!
what about the 1 eth minimum tho?

**Comment by vojtechsimetka** [comment]
thats fixed. minimum is anything above 0 now.

**Comment by lorelei1** [comment]
sweet! thank youuu
