### ISSUE TITLE
Incorrect exchange rate in Alpha 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#390]
All amounts in the alpha are slightly off from the develop exchange rate. According to vojtech it is the alpha exchange rate that is off. So this means many previous Milestones will need to be compensated?

two exact Milestones to show this difference: 
https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/9Cjl6QuskgQeYUaC 
https://develop.giveth.io/campaigns/5b27bf48cd46d41e274b53ef/milestones/5b27c133cd46d41e274b53f4

**Comment by perissology** [comment]
@vojtechsimetka this has been fixed right?

**Comment by vojtechsimetka** [comment]
Yes but the reimbursement has not been made.

**Comment by vojtechsimetka** [comment]
Rates are resolved (the cryptocompare sometimes gets updated after midnight, but the changes are not dramatic). This document monitors that the rates are within error margin https://docs.google.com/spreadsheets/d/1SzAF39l2NkyICv1Xbdo6muw2dIT_4SA-CyDx2H4S47s/edit?usp=sharing . Initial rate recalculation has been created but needs more feedback from Griff and Lindsay.

**Comment by krrisis** [comment]
what about the reimbursements?

**Comment by krrisis** [comment]
I think this one still needs to be figured out, right? It's an annoying one but maybe this is another one to put on gitcoin --> someone should calculate how much the eth was off and how much should be reimbursed to the different people

**Comment by vojtechsimetka** [comment]
@krrisis here it is. There may be some small errors but this was shared before. I am not going to do anything about this anymore mostly because the difference is for the most affected less than 30 USD https://docs.google.com/spreadsheets/d/11fdhiv0_KhjsEujwzntvXecVr9i_Sj3EVMBQXrJUQ78/edit?usp=sharing
