### ISSUE TITLE
Pending and Failed Milestones

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#391]
![screen shot 2018-06-18 at 1 20 19 pm](https://user-images.githubusercontent.com/35914957/41560327-9c6a1a2c-72fb-11e8-895d-b87ddb9fcda3.png)

Multiple milestones are getting stuck after the proposer selects "Mark Complete"with a spinning circle and "Pending" or "Failed" status

No contract registered for these transactions
There is no sign of these transactions on the rinkeby etherscan for this wallet

**Comment by vojtechsimetka** [comment]
Can you send ID's of those milestones?

**Comment by ljg583** [comment]
There aren't and transaction IDs but here are links to the milestones

RewardDAO #16 Apr16-May15: Ronald: (Pending) https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/J3RQukbKC508bZSB
RewardDAO #16 Apr16-May15: Raresica: (Failed)
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/lloOxKfbO1CMvCwG
RewardDAO #16 Apr16-May15: Abram Symons: (Pending)
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/9ioctPTBs0OzBtuC

**Comment by vojtechsimetka** [comment]
And you said you just marked them as complete?

@perissology  Here are the TX hashes and data from feathers. To me this almost looks like there was chain reordering?

On feathers
https://feathers.alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/J3RQukbKC508bZSB
Latest tx:
https://rinkeby.etherscan.io/tx/0xc0f9ea417c39cdc73b378d447a6ed17c55b07a5f74f79cb9a4a66dc571c57a6d

On feathers
https://feathers.alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/lloOxKfbO1CMvCwG
Latest tx:
https://rinkeby.etherscan.io/tx/0x4b7a9844944f0a4b0da433515a94f279b8aeca349e11ea7d2d57fbc416aaeaa5

On feathers
https://feathers.alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/9ioctPTBs0OzBtuC
Latest tx:
https://rinkeby.etherscan.io/tx/0xffbbb8d8df6e7eb0640a50edecd0c2b2fafa153bc87d59c60c3aeac98e0b1684

**Comment by ljg583** [comment]
Yes, they were marked complete after the campaign manager accepted and before going to review

**Comment by perissology** [comment]
hmm, are you sure that you marked them complete? That should not have been possible as they have never been created.

I don't see any evidence of a re-org in the logs...

> RewardDAO #16 Apr16-May15: Ronald: (Pending) https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/J3RQukbKC508bZSB

>RewardDAO #16 Apr16-May15: Abram Symons: (Pending)
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/9ioctPTBs0OzBtuC

I can't find any tx for either of the above milestones. Neither of them have a `projectId` assigned, which tells me they were never created.

A couple of things could have happened, but it's hard to say.

1. the tx was sent w/ low gasPrice & happened to be overwritten elsewhere
2. there was a bug in the nonce cache (web3-provider-engine) and it set the nonce too high, and the tx will be broadcasted when appropriate (the nonce is correct)

> RewardDAO #16 Apr16-May15: Raresica: (Failed)
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/lloOxKfbO1CMvCwG

You can see that the [tx](https://rinkeby.etherscan.io/tx/0x4b7a9844944f0a4b0da433515a94f279b8aeca349e11ea7d2d57fbc416aaeaa5) creating this milestone failed, thus the failed state.

This did bring up a couple of edge cases we need to handle however.
1. When the status is 'pending', but we haven't seen a tx in x # of hrs, we need to revert to the previous state so the user can try again (possible there is still a pending tx, but the gasPrice is too low)
2. When a tx has failed, we need to inform the user, hopefully giving them a hint why it failed, and revert to the previous state

I've set the txs states back to 'proposed'.

**Comment by ljg583** [comment]
This milestone is stuck pending for review

https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b4c3bf0b89c2175b538dea4

![screen shot 2018-07-16 at 2 11 29 pm](https://user-images.githubusercontent.com/35914957/42757987-39b4c252-8902-11e8-8ee2-4ab741ec1b8c.png)

**Comment by perissology** [comment]
this will be fixed in 1-2 days when we roll out a new release
