### ISSUE TITLE
Some issues with text out of fields (develop.giveth)

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#392]
On a 13" screen text on develop run out of the blocks, see screenshot below.

![image](https://user-images.githubusercontent.com/6533925/41564709-feb12970-7353-11e8-9602-8c33b8f17f27.png)

**Comment by perissology** [comment]
I don't think we need to show both the address and username here. We should show only the username & default to the address if no username has been set

**Comment by anshumanv** [comment]
@vojtechsimetka can I work on this?

Agreed with @perissology that showing just the username makes sense to me too.

**Comment by perissology** [comment]
I fixed this yesterday
