### ISSUE TITLE
Extra spacing / paragraphs in text after saving 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#394]
This is different from the issue of spaces coming when editing, these extra paragraphs now appear after saving.

Text when creating: 

![image](https://user-images.githubusercontent.com/6533925/41565327-9f161e28-7356-11e8-96d4-686fea3687f7.png)

Text after saving: 

![image](https://user-images.githubusercontent.com/6533925/41565409-fc8229b2-7356-11e8-8398-0be771dfd4ad.png)

**Comment by perissology** [comment]
This is a problem when you use wsiwyg editors. They convert text to html as best and it can't always be exactly the same. Closing as this won't be fixed.
