### ISSUE TITLE
Not possible to update image in a Milestone you edit 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#396]
Reproduce:

See example in Milestone https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/BuxdhbJiEhwGOulL

Selected a new image, see below

![image](https://user-images.githubusercontent.com/6533925/41565914-377adad0-7359-11e8-9677-3835612ada02.png)

After saving, still shows wrong image: 

![image](https://user-images.githubusercontent.com/6533925/41565947-6ae0cd30-7359-11e8-8682-17fd584cd42e.png)

**Comment by satyavh** [comment]
It depends, what state is your milestone in (proposed, inProgress, completed...)?

**Comment by vojtechsimetka** [comment]
It actually does not work in any state even on develop. Somewhere that functionality got broken.
