### ISSUE TITLE
2 Milestones stuck on 'paying' (develop.giveth)

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#397]
these are stuck, also don't show any status

https://develop.giveth.io/campaigns/5b27bf48cd46d41e274b53ef/milestones/5b2824bdcd46d41e274b5467
https://develop.giveth.io/campaigns/5b27bf48cd46d41e274b53ef/milestones/5b27e36acd46d41e274b5423

![image](https://user-images.githubusercontent.com/6533925/41566187-b68882d6-735a-11e8-90d9-f37bb5caeab6.png)

![image](https://user-images.githubusercontent.com/6533925/41566195-c47213f8-735a-11e8-9251-b4a09a2ab008.png)

**Comment by perissology** [comment]
ah, I see what happened. The tx events got processed out of order. The `prevStatus` is `Paid` and the status is `Paying`. That should be reversed.

I'll implement a fix

**Comment by perissology** [comment]
This should be fixed in feathers [be51db6](https://github.com/Giveth/feathers-giveth/commit/be51db63ed9f64884fb01b8d9d9dda04bce69aeb)

**Comment by vojtechsimetka** [comment]
Just did a bunch of milestones, seems good.
