### ISSUE TITLE
Create warning message when leaving Community/Milestone/Campaign you edit 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#400]
Happens often that (apparently?) I click back and lose my entire Milestone. 
Can we have a pop-up with a warning message that confirms moving away from page?

**Comment by perissology** [comment]
even better is to just cache the current values in local storage when editing, so we can re-fill when we return to the page. Like github does if you navigate to a different page when editing/creating an issue, etc.

I guess we would need a cancel button to clear the cached data

**Comment by vojtechsimetka** [comment]
It is on my plan when rewriting the milestones to model, this should be provider and consumer.

**Comment by satyavh** [comment]
I've been trying to tackle this today. React Router has a built-in Prompt function that should conditionally trigger a prompt upon route change. 

Unfortunately, the thing doesn't work with `history.back` 👎 

Upon pressing back, it will change the browser route url, but it does prevent React from rendering the new route. Then it will show a prompt, but if you press cancel, it will restore the browser url and as such rerender the current route. 

What it should obviously do is prevent changing the url.

**Comment by vojtechsimetka** [comment]
@satyavh does this solve the history back issue? I was about to merge it. https://github.com/Giveth/giveth-dapp/pull/337

Also can you disable the erase on escape press?

**Comment by satyavh** [comment]
Fixed in develop branch

**Comment by vojtechsimetka** [comment]
There is a bug. When creating new DAC/Campaign or Milestone, hitting the save button gives the popup.
