### ISSUE TITLE
Incorrect Milestone conversion rate in edit view

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#401]
Milestone gives wrong date when editing - it always shows the current date (well, date of yesterday), which is highly confusing (made me reassign this Milestone - and now logically cancel - as date was actually correct in the first place).

Screenshots as example from [this milestone](https://alpha.giveth.io/campaigns/R1WkS0obautijkvJ/milestones/BuxdhbJiEhwGOulL) but actually is the case with all Milestones. Milestone conversion date says 29/04

When editing it is 18/06 (see screenshot).

![image](https://user-images.githubusercontent.com/6533925/41606916-14f49f32-73e5-11e8-9dc5-7ad0e468cc2d.png)

**Comment by vojtechsimetka** [comment]
Actually no, it seems like apart from visual issue it does not cause any other problems. I prefer not touching this part before the next release is rolled out.
