### ISSUE TITLE
Milestone Descriptions Reject Inline Images

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#402]
see: https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/u2bYcmF3SIgSdXiI

When writing the description for my weekly milestone, I attempted to inline an image, which during the editing phase was visible, but upon saving disappeared. I tried both dragging the image on and using the insert image button.

I assume that this problem will persist through any of the items (community or campaign descriptions) that use this same edit window.

**Comment by satyavh** [comment]
I fixed this in develop, will be released soon
