### ISSUE TITLE
CORS setup on develop

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#404]
Allow netlify.com in CORS for develop and release environments. This way we can test PRs directly from github.

**Replicate:**
- Go to https://deploy-preview-403--giveth-dapp.netlify.com/
- Try creating new DAC
- It will get stuck on saving and display following error in console
<img width="833" alt="screen shot 2018-06-21 at 03 11 45" src="https://user-images.githubusercontent.com/7974813/41694658-a0190b62-750b-11e8-8651-c138237b330b.png">

**Comment by perissology** [comment]
fixed
