### ISSUE TITLE
unlock wallet popup is hidden when trying to donate w/ locked wallet

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#406]
The unlock wallet popup appears behind the donate popup now.

**Comment by vs77bb** [comment]
Hi @vojtechsimetka is this one worth a Gitcoin bounty? @anshumanv is willing to take it up and we can fund it, if so 🙂

**Comment by vojtechsimetka** [comment]
hey @vs77bb Thank you for the offer it is very kind! This issue was rather simple fix we needed to hotfix. I will create a bunch of new issues soon that should be well defined so those should be great candidates :) . In any case we will start using Gitcoin ourselves soon.

**Comment by anshumanv** [comment]
Hey @vojtechsimetka didn't know the issue is this quick, nice fix though. :)

Will look up more issues that need fix.
