### ISSUE TITLE
When signing up for a new account, the page stays on sign up

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#408]
the expected behavior is that it would give me a chance to back up the wallet, then add my name and whatever other deets in the profile page but instead i'm just logged in (as you can see in the corner but its not really obvious) and it stays on the same page, so i have to manually back up my wallet.

<img width="1183" alt="screen shot 2018-06-30 at 10 10 30 am" src="https://user-images.githubusercontent.com/14945613/42127479-58d442a4-7c4e-11e8-94d5-f70de5ed4a6b.png">

**Comment by GriffGreen** [comment]
Also it didnt auto send me Rinkeby, even after 10 minutes

**Comment by perissology** [comment]
okay, it has lots of eth now, should start auto sending.
