### ISSUE TITLE
Join Giveth buttons send users to slack

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#412]
You can see where the button directs you in the bottom left of the pic... it should go to giveth.io/join or even http://riot.im/app/#/room/#giveth-general:matrix.org (my preference is the latter)

<img width="950" alt="screen shot 2018-06-30 at 11 26 50 am" src="https://user-images.githubusercontent.com/14945613/42128086-9d708788-7c58-11e8-8262-8f4381fd1e33.png">

**Comment by vojtechsimetka** [comment]
Yes only whitelisted addresses can see those buttons (because only they can perform the actions)

**Comment by GriffGreen** [comment]
thx V i edited in the comment to remove my sillyness
