### ISSUE TITLE
GasPrice Oraclet too limiting, needs flexibility

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#417]
It would be really nice in times like these, if we had an "advanced" button that would allow people who understand gas price the ability to just put their own gas price in the field.

Right now its autogenerating 1.1 Gwei... i'm not taking the bait and just waiting for it to recalculate and charge me more... refresh, refresh, refresh

<img width="665" alt="screen shot 2018-07-02 at 4 46 49 pm" src="https://user-images.githubusercontent.com/14945613/42191543-433b5c36-7e18-11e8-8d54-2e6c02bfe942.png">

**Comment by GriffGreen** [comment]
and the oracle is working right, the ethgasstation safe low is 1 Gwei... its just actually not really safe enough to try.
<img width="733" alt="screen shot 2018-07-02 at 4 54 41 pm" src="https://user-images.githubusercontent.com/14945613/42191664-d26f469c-7e18-11e8-8553-384f73279c0d.png">

**Comment by vojtechsimetka** [comment]
This is fixed since you can now only donate with metamask (where the gas price is editable)
