### ISSUE TITLE
Editing a milestone doesnt navigate to the page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#418]
Granted, i have crappy internet... maybe with stronger wifi it would work, but when i try to navigate to  the edit page for this milestone, it just shows me the green dot and reloads the my-milestone page.
<img width="1285" alt="screen shot 2018-07-02 at 5 56 08 pm" src="https://user-images.githubusercontent.com/14945613/42193077-7ceb0ed2-7e21-11e8-8755-ef3641d7f7d5.png">

**Comment by vojtechsimetka** [comment]
Yeah your browser has 5 seconds to load the page otherwise it fails. We should in general fix the socket connection and offer rest as backup.

**Comment by GriffGreen** [comment]
thx
