### ISSUE TITLE
 Site not loading on first try 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#420]
95% of the time the 'homepage' of the DApp does not load on the first try, just a blank page, works on refresh. 
Always have had this issue with alpha, beta does the exact same think.

reproduce: type beta.giveth.io

Linked to my extensions? Console: 

Error in event handler for (unknown): TypeError: Cannot read property 'length' of undefined
    at doBlacklistCheck (chrome-extension://pdknmigbbbhmllnmgdfalmedcmcefdfn/js/DomainBlacklist.js:54:34)
    at chrome-extension://pdknmigbbbhmllnmgdfalmedcmcefdfn/js/DomainBlacklist.js:23:24

**Comment by vojtechsimetka** [comment]
Yeah this looks like an extension issue. Although I definitely had the same issue before. Should be fixed in develop now, anyone feel free to reopen if the issue appears again..
