### ISSUE TITLE
View not fixed on DAC overview

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#421]
view [here](https://beta.giveth.io/dacs/5b37da13a239ac21b383d4da) is still not ok (13" screen), it's correct on the campaign subpage, not on communities

![image](https://user-images.githubusercontent.com/6533925/42211818-c31dfc28-7eb4-11e8-894d-807fc62be3fa.png)

**Comment by vojtechsimetka** [comment]
Fixed in #459
