### ISSUE TITLE
style issue when creating Campaign/DAC

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#422]
You can now edit Campaigns and it does not delete spacing between paragraphs but... now it does the opposite when creating a new Campaign, example Campaign [here](https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328) 

There is now double the spacing between paragraphs, visable in other Campaigns too.

**Comment by mroberts10** [comment]
Assign to Nepali.
