### ISSUE TITLE
Donation splitting when a milestone reaches it's funding goal

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#424]
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b3ab3d5df629170d472b3dc

I thought these milestones were capped?

Also it says i can still delegate the 1.2 ETH which was sent to the Milestone... I'm not sure if this is a UI bug or what is going on.

i haven't tried to double delegate... yet... see the screen shot, its the last one. 

<img width="1321" alt="screen shot 2018-07-07 at 3 13 20 pm" src="https://user-images.githubusercontent.com/14945613/42411207-520b76cc-81f8-11e8-8117-35f80a82aaf6.png">

**Comment by vojtechsimetka** [comment]
Yeah the UI gets updated very slowly. You can not double spent. You "can over delegate" in UI (it will bug it out) but the contract will reject the over delegation. We left the over delegation/donation in on purpose but kinda forgot about it for the release. Will be fixed in the next one :).

**Comment by bowensanders** [comment]
On my milestone I'm experiencing a number of issues:
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b3ab3d5df629170d472b3dc

I had in error marked it complete before it had enough donations. Griff later rejected it, and then donated to it. 

I saw today that the donations were in, and marked it complete:
https://rinkeby.etherscan.io/tx/0x45af2f43e0ade56b9e529e69da499106b365b0ced6dd6c29bb974b781dac2c0a

However, it is not showing as marked complete to (at least me) and it will not allow me to do so (it gives the "oh no" wallet error).  

Griff asked me to add this info to the issue.

**Comment by bowensanders** [comment]
Also two secondary notes: 
• The milestone isn't showing in the Giveth Governance campaign
• When I marked the milestone complete (the tx in the above comment) The URL that is provided in the green window (marked complete - view transaction) provides the correct TX ID but it points to plain etherscan.io instead of rinkeby.etherscan.io.

**Comment by perissology** [comment]
did you have a different recipient address then your rinkeby address?

There is a bug in the ui when creating milestones, where upon creation of a proposed milestone, the campaignOwner is set as the milestoneManager. Only the milestoneManager & recipeint can mark a milestone complete, so I'm guessing this is your issue. We will have a fix today, but griff may have to mark this milestone complete.

**Comment by perissology** [comment]
your milestone should be correct now

**Comment by bowensanders** [comment]
It sure looked correct, but I get the "Oh No! is your wallet unlocked" upon trying to [$collect]...

I checked, reloaded, unlocked again (a few times) and even doublechecked metamask to make sure I was using the right wallet. I *seem* to be doing it right, but I think this milestone may be cursed! ;)

**Comment by perissology** [comment]
closing as I'm pretty sure this has all been fixed. the milestone is paid.
