### ISSUE TITLE
Tx link goes to mainnet etherscan instead of rinkeby

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#425]
The flag link (which IMO goes away too quickly and is there another way to get to this tx from the app?) is linking to the wrong network.
https://etherscan.io/tx/0x19d13c40a111e27b78feb187d0a697e5279b7b80c0c9fd48424303cd549974d5

should be 

https://rinkeby.etherscan.io/tx/0x19d13c40a111e27b78feb187d0a697e5279b7b80c0c9fd48424303cd549974d5

This was on https://beta.giveth.io/donations

<img width="1295" alt="screen shot 2018-07-07 at 3 53 15 pm" src="https://user-images.githubusercontent.com/14945613/42411581-b7d8d41c-81fe-11e8-958a-73b6d8d549be.png">

**Comment by perissology** [comment]
fixed
