### ISSUE TITLE
Trying to delegate with wallet locked no error message

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#426]
<img width="965" alt="screen shot 2018-07-08 at 11 48 03 am" src="https://user-images.githubusercontent.com/14945613/42418634-e607aad8-82a4-11e8-8b96-db9a63f97b3a.png">

Just sits there delegating... obv i need to unlock my wallet... i forgot, but i prob needed a prompt before this point

**Comment by GriffGreen** [comment]
oh! funny, when i closed the box in the screen shot, the password input was right behind it

**Comment by vojtechsimetka** [comment]
Yeah the popups are in wrong order :( .

**Comment by GriffGreen** [comment]
and let me just say, the next delegations were so fucking smooth :-D love the flow, so fast so easy :-D no waiting... way better then any dapp i've ever used

**Comment by GriffGreen** [comment]
well except for: 

<img width="989" alt="screen shot 2018-07-08 at 11 55 51 am" src="https://user-images.githubusercontent.com/14945613/42418700-108250be-82a6-11e8-8bbf-c75a1e1bf285.png">
<img width="1017" alt="screen shot 2018-07-08 at 11 56 05 am" src="https://user-images.githubusercontent.com/14945613/42418701-10bc89a0-82a6-11e8-9382-95e73c103b02.png">

**Comment by vojtechsimetka** [comment]
Fixed in af4b9b49f9478513d120a9079d3cc82996a8e8d0
