### ISSUE TITLE
prevent donation to canceled milestones

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#43]
we shouldn't be able to donate to canceled milestones in the dapp.

LiquidPledging will not throw when donating to a canceled milestone, so we need to prevent this in the dapp. With liquidPledging, if a donation is made to a canceled milestone, the tx successfully completes, but the funds end up in a note that the owner controls.

**Comment by perissology** [comment]
also need to distinguish between different milestone states in `ViewCampaign`. 

only milestones w/ `status === 'InProgress'` && `totalDonated < maxAmount` can receive donations.

**Comment by satyavh** [comment]
I guess that also counts for delegations to milestones
