### ISSUE TITLE
Lots of people are completing milestones before they receive any donations

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#431]
major issue

https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b48c9e3b89c2175b538de77

https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b3fe7f73539167798ff4645

both these and many more have been marked complete and then the reviewer accepted... but now these guys dont get paid? What is the fix and the preventive medicine?

**Comment by vojtechsimetka** [comment]
1. I have disabled for now the Mark as complete button if the donation amount is 0.
2. I will make an on-boarding call with each campaign manager whos responsibility it will be to make sure that all people within the campaign know what they are doing.
