### ISSUE TITLE
Need's reviewing but no button to review?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#432]
https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b4e1583b89c2175b538df0d

https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b4e13f6b89c2175b538df0c

Couple o milestones that got an issue :-D

<img width="1110" alt="screen shot 2018-07-18 at 5 59 00 pm" src="https://user-images.githubusercontent.com/14945613/42893341-60b2aeec-8ab4-11e8-9121-bc1b44e562be.png">

They are somewhere in a limbo the needs reviewing thing is spinning, but no buttons for reviewing it.

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b4c3bf0b89c2175b538dea4

**Comment by vojtechsimetka** [comment]
Yeah those are just stuck on pending. I fixed them manually, but hopefully tomorrow we can deploy the new release and this will be fixed.

**Comment by GriffGreen** [comment]
:-D

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b4e13f6b89c2175b538df0c
https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5b4e1583b89c2175b538df0d
2 more! :-D

**Comment by vojtechsimetka** [comment]
Done.

**Comment by vojtechsimetka** [comment]
Should be fixed with yesterday's release. Reopen if not.
