### ISSUE TITLE
Make it easy to fund campaigns with Milestones (Feature request)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#433]
I'm filling out this Stable.fund grant and it would be sooooo nice to be able to have a milestone for funding integrating the DAI feature and then have that feed into the DApp Campaign directly.

Currently: 

I can make a milestone for integrating DAI. It will end up with ETH on mainnet sent to an address. If it's supposed to support a campaign in general... well then it has to be put back in the system.

Desired:

I make a milestone that sends money directly to a campaign upon completion

**Comment by GriffGreen** [comment]
We are making Milestones in DAppNode that will send 15-50 ETH to the campaign... but to do it, we made a dappnode address (which deployed the campaign) and then that address will receive the ETH and then it has to be re-donated to the DAppNode campaign or milestones, and that takes an extra couple txs on mainnet...

Gotta get it so mainnet ETH is not touched in situations like this and liquid pledging is handling it.

I think this is a VERY common pattern.

**Comment by vojtechsimetka** [comment]
Not saying whether we shoul or should not do it but what will a difference between DAC and Campaign then be? I feel OK with shared milestones between campaigns but sending money from campaign to campaign sounds to me like DAC duplication. Mind you I do understand the usecase.

**Comment by GriffGreen** [comment]
I'm sorry, i'm not communicating clearly... i mean a milestone within a campaign that can send money back up to the "general funds" for THAT campaign. 

To say it slightly different... this would be a milestone that can be funded directly and when this milestone is accomplished, the funds go straight to the campaign that the milestone was proposed in.

In a lot of grants, funding to the campaigns comes at the completion of a milestone: "Get this done and we will give you 10 ETH" right now that ETH has to leave the campaign and then be donated back.... when really it should just go directly to the Campaign to be delegated to future milestones (as in paying salaries)

For example.

For the DApp Campaign, we could propose a milestone for integrating DAI, MakerDAO could fund that milestone... but who is the recipient? Right now it has to be a trusted person or a multisig that receives those funds with the intention to just donate them back to the DApp Campaign....

It would be nice if we could skip the mainnet completely and keep everything on the DApp :-D

**Comment by YalorMewn** [comment]
We now have our first Milestone for adding a DApp to DAppNode. Welcome Mysterium !!! https://beta.giveth.io/campaigns/5b44b198647f33526e67c262

**Comment by GriffGreen** [comment]
This feature would make a feature request funding method (as mentioned in https://github.com/Giveth/giveth-dapp/issues/446 ) trustless... That's basically what I'm asking for here

**Comment by perissology** [comment]
related #517

**Comment by GriffGreen** [comment]
This is solved in #517
