### ISSUE TITLE
redirect alpha.giveth.io 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#434]
as mentioned in the unicorns channel - can you please redirect all alpha.giveth.io/** pages to beta.giveth.io ? There are links to alpha in many Milestones. thx!

**Comment by vojtechsimetka** [comment]
The problem is that even if we redirect the links to milestones and campaigns will be broken. Hence we decided not to redirect so that rather than showing incorrect link we show broken one. Does that make sense to you?

**Comment by krrisis** [comment]
the proposal I'd make is to redirect all links (so, all the specific milestones that are on subpages - alpha.giveth.io/** ) to the homepage of beta.giveth.io (so not to the new url of the specific milestone on beta) -- as far as I know no link will give an error at all?

**Comment by vojtechsimetka** [comment]
@perissology I've tried to add alpha.giveth.io as alias on netlify after which I would make the necessary rewrite rules. However, it seems the domain has since been removed from netlify, can you add following record?

```
alpha CNAME giveth-dapp-beta.netlify.com
```

**Comment by perissology** [comment]
that doesnt seem to work
