### ISSUE TITLE
Campaigns no longer show up under DAC

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#435]
only donations visible under DAC
now impossible to see which Campaigns are funded by a DAC - takes away a lot of the transparency.

**Comment by vojtechsimetka** [comment]
This will be added back but in a different form. The DACs and Campaigns will be linked through donations.

**Comment by krrisis** [comment]
currently Campaigns still not showing up under DACs, even after donations - reduced transparency at the moment..

**Comment by vojtechsimetka** [comment]
It's fixed in develop.
