### ISSUE TITLE
Created Campaigns hang in Release and Beta

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#436]
Trying to create a few campaigns... but first one died on me:
<img width="833" alt="screen shot 2018-07-20 at 1 23 09 pm" src="https://user-images.githubusercontent.com/14945613/43000372-74fd5b7c-8c21-11e8-94ae-8228a3fd0a86.png">

https://rinkeby.etherscan.io/tx/0xa01b9a0736a2fd9d045fd4a5c0e4b71c704cb6b89f28efc73af76967bb5b013a

Tx went thru, but the UI is showing pending forever...

**Comment by vojtechsimetka** [comment]
Fixed, all that needed to be done was restarting the beta feathers. If this ever happens again please put another comment here. @perissology said he is aware and will fix this.

**Comment by perissology** [comment]
bug has been fixed

**Comment by lorelei1** [comment]
This is happening to me now!
<img width="1230" alt="screen shot 2018-12-07 at 5 45 46 pm" src="https://user-images.githubusercontent.com/38163206/49640379-6c845000-fa48-11e8-82f1-b4723d3034d1.png">
I created this DAC like 2 days ago and it still looks like this...
