### ISSUE TITLE
Double donation? I only sent it once!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#439]
https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5

<img width="796" alt="screen shot 2018-07-22 at 8 11 33 pm" src="https://user-images.githubusercontent.com/14945613/43048670-c0552a52-8deb-11e8-8edb-3866761fbb1e.png">

**Comment by GriffGreen** [comment]
Also... I sent it from my Metamask address... 0x83939.....80 it might be jarring to see that it came from a different address... we might need an info box during the donation that explains that?

**Comment by perissology** [comment]
the duplicate is taken care of. Not sure of the cause, but I added some more logging so if/when it happens again, we can better determine the cause.

I agree on the donation address point.

**Comment by vojtechsimetka** [comment]
The infobox is already there, have not seen duplicate donations lately.
