### ISSUE TITLE
When a Campaign Manager edits a milestone it shows the number of wei???

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#444]
I just walked some people thru making milestones for the signaling website and they selected ETH as the base currency, then i went to edit it and i saw that 2.5 ETH was converted to 25000000000000000000 ETH

![screen shot 2018-07-24 at 5 15 33 pm](https://user-images.githubusercontent.com/14945613/43148303-50278fc4-8f65-11e8-8af6-30e25e07c29a.png)

**Comment by GriffGreen** [comment]
oops already mentioned in https://github.com/Giveth/giveth-dapp/issues/442

**Comment by vojtechsimetka** [comment]
Yeah closing as a duplicate. It is actually "fine" in sense that it will not let you save and break the system, but definitely something we are focusing to solve ASAP.
