### ISSUE TITLE
Milestone will not disburse

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#445]
I have a milestone ready for disbursement, but clicking disburse gives the "oh no" dialog:

<img width="1251" alt="screen shot 2018-07-24 at 9 30 42 am" src="https://user-images.githubusercontent.com/27023908/43154259-97cd5f4e-8f28-11e8-8e0f-9702b2bcfd9c.png">

The milestone can be seen here:
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b47d5588f99d75a704edd60

**Comment by vojtechsimetka** [comment]
Sorry RJ I tried to fix it, could not :(

**Comment by perissology** [comment]
this is fixed
