### ISSUE TITLE
DAC's don't show their campaigns... could be better for users!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#448]
It's awkward that when i click on a DAC, for example, https://beta.giveth.io/dacs/5b37da13a239ac21b383d4da, I can't see that DAC's campaigns. I have to scroll up and click on the campaigns tab, which then, for a user, cuts any connection to their parent DACs. As DACs are umbrellas under which all their campaigns exist, the click-flow on the DApp should reflect that. Conversely, when navigating to a campaign, nowhere does it say what DAC that campaign is attached to. Neither from the all campaigns page nor when you click on a specific campaign.

**Comment by vojtechsimetka** [comment]
Alright alright, I will do this. Just so you know there is absolutely no link between DAC and Campaign. One can exist without the other. The only link is made through delegations. DAC is not an umbrella and one Campaign can be linked to 0 or 1000 DACs.
