### ISSUE TITLE
Hide mail address from public view

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#452]
currently your mail address to which notifications are being sent is publicly viewable by anyone, which is ofc not ideal for privacy, spam etc. Could this be hidden by default? people can indicate maybe with a checkmark if they want to show this on their profile, but should be off by default.

**Comment by vojtechsimetka** [comment]
Well we can hide in in the UI but all those email addresses are exposed and will be. Especially once we store them on IPFS. I believe hiding them in UI will just make it even less transparent.

**Comment by krrisis** [comment]
how can we solve this? this is one of the things you could add to a list (a version) of things that need to be fixed before we onboard external projects. logically I don't want my mail address on the blockchain and most people don't want this, major privacy issues. Mail is in any case outdated.. maybe the twitter api, sending you a DM if you authorize?

**Comment by vojtechsimetka** [comment]
Right, well email should be optional. But in principle we can not store anything off chain/IPFS/Swarm otherwise it would not be decentralized. So would making emails optional solve this struggle?
