### ISSUE TITLE
Milestone showing wrong amount paid?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#453]
<img width="429" alt="screen shot 2018-08-10 at 5 03 34 pm" src="https://user-images.githubusercontent.com/14945613/43985832-7073bf84-9cbf-11e8-9b06-18a28b5b61c7.png">

https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b4c949fb89c2175b538dec7

I hope I get the left overs as a delegation ;-D

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b566a7e2c76b41c27b9b52b
this one too

**Comment by vojtechsimetka** [comment]
Yeah there is some problem in the counters. RJ is looking into that but I am also working on something that might solve it.

**Comment by perissology** [comment]
@GriffGreen did you make this donation outside of the ui?

There was a donation from a dac directly to a milestone which isn't supported in the ui

**Comment by perissology** [comment]
fixed in feathers-giveth f628e4c.

production will be updated on next release
