### ISSUE TITLE
No create new campaign button

### ISSUE THREAD

**Issue by Ins0mniaIco** [Giveth/giveth-dapp#458]
I am not sure what I am doing wrong, but there is no buttons for creating a new campaign or community, even if I try to add the trailing URL /campaigns/new it reverts back to the homepage. 

<img width="1397" alt="screen shot 2018-08-22 at 11 24 31" src="https://user-images.githubusercontent.com/40732463/44455343-1ce75900-a5fe-11e8-91ac-8a007f9e50bf.png">

**Comment by vojtechsimetka** [comment]
Yes that is correct, we are still in rather experimental closed beta stage. Creation of the DACs and Campaigns is whitelisted for the time being and we are slowly onboarding external projects in waves. If you are interested in creating your project on the platform please contact @danibelle:matrix.org on Riot.
