### ISSUE TITLE
my-milestones shouldn't be able to mark complete if there are 0 donations?

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#46]
If there are no donations to a milestone, we should not allow the owner to `markComplete`, only to `cancel`.

If we allow them to mark complete and it is approved by the reviewer, then the milestone will have a `requestWithdraw` button, but there will never be anything to withdraw.

So I guess we have 2 options.

1. allow owner to `markComplete` but do not show the `requestWithdraw` btn if there are 0 donations.
2. don't allow owner to `markComplete` if there are no donations

Maybe the 1st option is better so the campaign can show they are getting stuff done

**Comment by perissology** [comment]
I hide the request withdrawal button if there are not donations

**Comment by vsimetka** [comment]
Option 1 is implemented.
