### ISSUE TITLE
EADDRINUSE error when deploying Smart Contracts on Feathers-giveth

### ISSUE THREAD

**Issue by arquimed** [Giveth/giveth-dapp#461]
I there everyone!

I am trying to install de Giveth DAPP locally, following the walkthrough video (https://www.youtube.com/watch?v=r06804yGen4&index=3&list=PL4Artm1rmCWEvm8WgcFpwZ2UMYT_BOF92)

After starting a local blockchain using yarn ganache-cli, I try to deploy the smart contracts but get the folling error:

 node scripts/deploy.js 
{ Error: listen EADDRINUSE 127.0.0.1:8545
    at Server.setupListenHandle [as _listen2] (net.js:1334:14)
    at listenInCluster (net.js:1382:12)
    at doListen (net.js:1508:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8545 }

I am running Node v10.9.0, Yarn 1.5.1, Npm 6.2.0.

Any help will be more than welcome!

**Comment by arquimed** [comment]
As it seemed a problem caused by having an instance of Ganache-cli already running, I stopped the Ganache-Cli instance and runned again scripts/deploy.js. 

It actually deployed the Smart Contracts and returned the addresses, to my surprise, as the local testnet should not be working! It seems as if deploy script starts its own blockchain.

Here's the result:
$ node scripts/deploy.js 
Foreign Network:  eth_accounts
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x479306c6ffbe8366a803272f822d16ec30d6986369c6c5538e58c29915e83e76
Foreign Network:    Contract created: 0xe78a0f7e598cc8b0bb87894b0f60dd2a88d6a8ab
Foreign Network:    Gas usage: 1447997
Foreign Network:    Block Number: 1
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:06 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x7e0ba8a75ae124d895943954dcf90fb6e7245d4a7483a62fbfd26b313aa055a8
Foreign Network:    Contract created: 0x5b1869d9a4c187f2eaa108f3062412ecf0526b24
Foreign Network:    Gas usage: 5649553
Foreign Network:    Block Number: 2
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:06 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_accounts
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x62d998024a744cb03fe6465ccfb2007c587dfb3007eefd363f9fca249647a2bc
Foreign Network:    Contract created: 0xcfeb869f69431e42cdb54a4f4f105c19c080a601
Foreign Network:    Gas usage: 6634719
Foreign Network:    Block Number: 3
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:07 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x9d07719edbd7237beebb0c82f69efc42fdd974eef5d7c059a50c3179156d2cc1
Foreign Network:    Contract created: 0x254dffcd3277c0b1660f6d42efbb754edababc2b
Foreign Network:    Gas usage: 68589
Foreign Network:    Block Number: 4
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:07 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0xa72bad98f83079238ce5798f886b1474c164dda32e5130cb5334ad4ddc761f4d
Foreign Network:    Gas usage: 2426442
Foreign Network:    Block Number: 5
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:07 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_accounts
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x211555eea09a454060a14a97223f387047a35b07c4a4ec5e058195b60db37597
Foreign Network:    Gas usage: 83497
Foreign Network:    Block Number: 6
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:07 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x356af3a90658ee3fd0ba0278e1ea8e28d89bf5ca6f7237cc840431b29702c939
Foreign Network:    Gas usage: 83561
Foreign Network:    Block Number: 7
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:07 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x27ab6a920275ccaa9db9a7427b06b5377861d4ddda81096e44c833fa36d44a77
Foreign Network:    Gas usage: 83497
Foreign Network:    Block Number: 8
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x59df527d8a9f83a9b726e2a5ee08a49dcca48e372b039e56b7843dbb4a3b8ba6
Foreign Network:    Gas usage: 70633
Foreign Network:    Block Number: 9
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x6ab91ec609f50bfd652e54030c7879fdd56eaf095143b14eda54c241abe71ac8
Foreign Network:    Contract created: 0x0290fb167208af455bb137780163b7b7a9a10c16
Foreign Network:    Gas usage: 2066512
Foreign Network:    Block Number: 10
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x8a6ab888013ee3faa543e5d304c0920b609ef9cf8bdfe3fb1fe2250e2041767e
Foreign Network:    Contract created: 0x9b1f7f645351af3631a656421ed2e40f2802e6c0
Foreign Network:    Gas usage: 2503096
Foreign Network:    Block Number: 11
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x6b1e796c02e91970bb94ab64c42aa82065078a342d9609b000ad1f94b409c250
Foreign Network:    Gas usage: 58165
Foreign Network:    Block Number: 12
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x661ebe0884d36bc7998224a469d731465a258a158fe7c928b6c4bc11d393c949
Foreign Network:    Gas usage: 58165
Foreign Network:    Block Number: 13
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x0013c47381286b3a3630128b03939df4d3ae661fd4be1801edbd3bcbc9d69228
Foreign Network:    Contract created: 0xa57b8a5584442b467b4689f1144d269d096a3daf
Foreign Network:    Gas usage: 1762514
Foreign Network:    Block Number: 14
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0xa63ac0ee45027f091737d8fd080fed993332fa9a1cff39351f3d46c062faca4a
Foreign Network:    Gas usage: 68378
Foreign Network:    Block Number: 15
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0xb1af2d9d05ab55185859cedbaaa4061a1c2abe8575316e8e62245c229e5f596d
Foreign Network:    Contract created: 0x630589690929e9cdefdef0734717a9ef3ec7fcfe
Foreign Network:    Gas usage: 2427768
Foreign Network:    Block Number: 16
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x16fab5e35b5c13602df1c32d779b8aa0d3e7f84ffed5501d64969db4167ee196
Foreign Network:    Gas usage: 58165
Foreign Network:    Block Number: 17
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0xaf0b84cecf6fc57d871650e5231e15cb6186e506e404406b2046bfbc30627588
Foreign Network:    Gas usage: 58165
Foreign Network:    Block Number: 18
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_accounts
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0xf6e076367bb05307be1d90b4e8cb2ce57d3e584dd3002fa1e72b47891618f293
Foreign Network:    Contract created: 0xa94b7f0465e98609391c623d0560c5720a3f2d33
Foreign Network:    Gas usage: 2272227
Foreign Network:    Block Number: 19
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x72d309a46a68d5c580402eb2ad58e1732f2ad87dc6d5ada0d8743ecf4fa3d717
Foreign Network:    Gas usage: 68378
Foreign Network:    Block Number: 20
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0xaa9f729b55c68f5787bce6adc6a6165b88497ece109029df2274c392de9be61b
Foreign Network:    Contract created: 0x8fed3f9126e7051dea6c530920cb0bae5ffa17a8
Foreign Network:    Gas usage: 3181230
Foreign Network:    Block Number: 21
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_getCode
Foreign Network:  eth_accounts
Foreign Network:  eth_call
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x2c0157f96ee7010b785321be9f823b14b7414f68ce8c82fc1ea02d9f79f69027
Foreign Network:    Gas usage: 68378
Foreign Network:    Block Number: 22
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Home Network:  eth_estimateGas
Home Network:  eth_gasPrice
Home Network:  eth_sendTransaction
Home Network:  
Home Network:    Transaction: 0x06619a5300d42f02df06403340aee1e156ab7e6cdb95984d1f7179b3bd17a679
Home Network:    Contract created: 0x8fed3f9126e7051dea6c530920cb0bae5ffa17a8
Home Network:    Gas usage: 2135052
Home Network:    Block Number: 1
Home Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Home Network:  
Home Network:  eth_getTransactionReceipt
Home Network:  eth_getCode
Home Network:  eth_accounts
Home Network:  eth_estimateGas
Home Network:  eth_gasPrice
Home Network:  eth_sendTransaction
Home Network:  
Home Network:    Transaction: 0x8ca5f6e6978088d2d276a2306c3fbe5ed8705f76459829abcb08597b8ebe80aa
Home Network:    Gas usage: 45658
Home Network:    Block Number: 2
Home Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Home Network:  
Home Network:  eth_getTransactionReceipt
Foreign Network:  eth_estimateGas
Foreign Network:  eth_gasPrice
Foreign Network:  eth_sendTransaction
Foreign Network:  
Foreign Network:    Transaction: 0x9b6c1c03bd6fc0cbe44e299d859adfa2f3cedb3e3dd7a3da095fd4ff9e2630f2
Foreign Network:    Gas usage: 1492296
Foreign Network:    Block Number: 23
Foreign Network:    Block Time: Sat Sep 01 2018 20:06:08 GMT+0200 (Central European Summer Time)
Foreign Network:  
Foreign Network:  eth_getTransactionReceipt
Foreign Network:  eth_call


 { vault: '0x6098441760E4614AAc6e6bb3Ec7A254C2a600b5d',
  liquidPledging: '0xBeFdf675cb73813952C5A9E4B84ea8B866DBA592',
  lppCampaignFactory: '0x9b1f7F645351AF3631a656421eD2e40f2802E6c0',
  lppCappedMilestoneFactory: '0x630589690929E9cdEFDeF0734717a9eF3Ec7Fcfe',
  givethBridge: '0x8fed3F9126e7051DeA6c530920cb0BAE5ffa17a8',
  foreignGivethBridge: '0x8fed3F9126e7051DeA6c530920cb0BAE5ffa17a8',
  homeEthToken: '0x5a42ca500aB159c51312B764bb25C135026e7a31' }

**Comment by perissology** [comment]
yes, the deploy scripts start their own instance.

The [readme](https://github.com/giveth/feathers-giveth#run-server) has the latest instructions.
