### ISSUE TITLE
When delegating multiple times with one delegate, the delegate button is not able to be pressed

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#465]
<img width="1024" alt="screen shot 2018-09-16 at 3 20 05 pm" src="https://user-images.githubusercontent.com/14945613/45601589-40ff4580-b9c4-11e8-9139-dc9ee7242ce9.png">
^^^ pic of what i see after the first delegation... even after waiting for the first delegation to clear. the only way to delegate multiple times is to refresh

**Comment by perissology** [comment]
pretty sure this has been fixed
