### ISSUE TITLE
when delegating and selecting the campaign/milestone to donate to, the amount is reset to the the total amount able to be donated

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#466]
<img width="1011" alt="screen shot 2018-09-16 at 3 25 50 pm" src="https://user-images.githubusercontent.com/14945613/45601631-11047200-b9c5-11e8-8d80-b3667be87207.png">
^^^ I type in gov to find the gov campaign

<img width="1032" alt="screen shot 2018-09-16 at 3 25 59 pm" src="https://user-images.githubusercontent.com/14945613/45601634-224d7e80-b9c5-11e8-99ec-162dd10673e1.png">
^^^^ The amount i put in is overwritten

**Comment by markoprljic** [comment]
Things I'd suggest here (on Donation popup):

1. remove slider
2. add link below the input field "Available funds: [amount]. **Select all**" (selecting all will auto populate the input field with all available funds)
3. Show predefined ETH (or DAI or other depending on selected) amounts to select (1, 2, 5, 10) or enter custom amount
