### ISSUE TITLE
Delegated milestone doubled up

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#467]
a new delegation popped up... its a double of a real one 
<img width="1242" alt="screen shot 2018-09-16 at 3 29 28 pm" src="https://user-images.githubusercontent.com/14945613/45601846-39da3680-b9c8-11e8-8560-d8927f31802b.png">
that 72.1 ETH one is fake!

**Comment by GriffGreen** [comment]
This is still an issue... cause old donations are still showing up as doubled... I am confident the smart contract accounting is right... but i dont know if my accounting is right... Also... I wonder how this is even being handled! 
<img width="1292" alt="screen shot 2018-10-20 at 3 24 26 pm" src="https://user-images.githubusercontent.com/14945613/47256249-f8ccba80-d47c-11e8-9d7b-32977028d8af.png">

Both of the donations above are doubled... i started delegating out of all four of them for fun.... we will see how it goes.... I expect the donations from one will work but the other wont (despite making a transaction and looking like it works)... I have been experiencing this weird thing where it seems like i have to donate to milestones multiple times, like the first time i donate it just pretended like i didnt... I am going to try and document:
Here are two donations i made out of the top DAC Delegations (not sure which is which): 
https://rinkeby.etherscan.io/tx/0x816957dceb2a8cd510d72ece04c1c69bf1fd38eef4f665308e10a1af1dcfe12c
https://rinkeby.etherscan.io/tx/0x3da12485a73d24ca4449945c3fdc1fa97b0b39a00a4141824d519518af0b42f9
Here are two donations i did out of Rafa's donations:
The top one (Which I don't think works cause i have used it to donate to this milestone multiple times, it acts like it works but then the milestone never gets the money): https://rinkeby.etherscan.io/tx/0x2749d92b1d55cf6ecab9ca65c3b22cef68301e641a4804d347e7c21f959ce429
The bottom one (Which I think will work): https://rinkeby.etherscan.io/tx/0x8764eeaa754019db8a7ec7dd684989c2991411d6a84d7280ec9da1ba5366a1e9

:-D this is a fun one :-D

**Comment by GriffGreen** [comment]
Follow up... my theory was correct, the top rafa donation didnt work... so now i tried to make the donation with the bottom one :-D I bet it will work! Screen shot of the balances post donations :-D
<img width="1326" alt="screen shot 2018-10-20 at 6 31 36 pm" src="https://user-images.githubusercontent.com/14945613/47258121-eeb7b580-d496-11e8-8e18-78e4d31cbcbc.png">
https://rinkeby.etherscan.io/tx/0xa92fa0e0cba1de5f974bf17ce903174fcc760586199f89293409b1130470272d

**Comment by perissology** [comment]
I'm been looking into this right now. They actually both should work b/c they point to the same `pledgeId` in lp. However they will each start failing once the pledge has been used up in lp.

I think I know why they were doubled up, but waiting to a response from @vojtechsimetka  on riot

**Comment by perissology** [comment]
I see why it appears it didn't work.

https://rinkeby.etherscan.io/tx/0x2749d92b1d55cf6ecab9ca65c3b22cef68301e641a4804d347e7c21f959ce429 was donated to https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5bb26b0bae4f6e3373e4fae0

The 2nd one was donated to a milestone that was already funded. Look at the [event logs](https://rinkeby.etherscan.io/tx/0x8764eeaa754019db8a7ec7dd684989c2991411d6a84d7280ec9da1ba5366a1e9#eventlog) you see 2 logs where topics 1 & 2 are the inverse of each other & data is the same in both events.

That is saying first transferred from pledge `0x2b1` to `0x318` & then transferred from `0x318` to `0x2b1`

**Comment by GriffGreen** [comment]
so then this is an error: https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b98826990b3c1478f06b462 
it says it needs funding... should i assume it actually is funded?

**Comment by perissology** [comment]
The original issue should be addressed in https://github.com/Giveth/feathers-giveth/pull/101, but we'll need to re-sync feathers.

Looking into the latest comment

**Comment by perissology** [comment]
leaving this here for later investigation:

[This](https://feathers.beta.giveth.io/donations?ownerId=203&txHash=0x391c72be8000d7384c046c4d6f5cd4fa87b638e691fd828ad161410d4803bbd3) donations show `amountRemaining = 0` in feathers

but the tx was clearly successful and not returned https://rinkeby.etherscan.io/tx/0x391c72be8000d7384c046c4d6f5cd4fa87b638e691fd828ad161410d4803bbd3#eventlog

Why does feathers show `amountRemaining = 0`?

**Comment by perissology** [comment]
fixed
