### ISSUE TITLE
Milestone says it has twice the Max ETH it can have

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#468]
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b62fa776d8ed147a62a6a0e

Should i accept this?

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5b97e3fe90b3c1478f06b45e
this one too

**Comment by bowensanders** [comment]
The one of those is my milestone - and it's showing as double in 'my milestones'
<img width="1311" alt="screen shot 2018-09-17 at 10 35 29 am" src="https://user-images.githubusercontent.com/27023908/45639715-8de72880-ba65-11e8-9d57-1b0c4efd8634.png">

**Comment by vojtechsimetka** [comment]
@perissology this one is very interesting
Milestone: https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b62fa776d8ed147a62a6a0e

Feathers:
https://feathers.beta.giveth.io/milestones/5b62fa776d8ed147a62a6a0e

Donations:
https://feathers.beta.giveth.io/donations?ownerId=169
Interestingly enough it actually seems like two independent donations with two TX hashes
https://rinkeby.etherscan.io/tx/0x71ea6b452b50a3bcf694c7862acc7b71686719ea481b3dc1739a7c929c3c0da0
https://rinkeby.etherscan.io/tx/0x01207781237f06c9814c91172ca704cff872b8ccb4c059f5cceadf4bd9289e56



@GriffGreen 
I fixed these and you can go ahead with them:
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b86e7ab3f1b956d7ccce470
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5b97e3fe90b3c1478f06b45e

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5b71f94da5f82545c38d2cdf
This one is fairly important, i would loe to get him paid

**Comment by vojtechsimetka** [comment]
@GriffGreen yeah it is always safe to do if it lets you (the smart contract will not allow you to deposit/retrieve more money than the limit). Re-processing fixed all of these. Not sure why this keeps happening.
