### ISSUE TITLE
2 milestones stuck in pending limbo

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#469]
I accepted these milestones and they disappeared from my milestones page... then i couldnt delegate to them... it was hard to find them again but I found a webpage that shows the milestones!

<img width="810" alt="screen shot 2018-09-17 at 12 02 38 am" src="https://user-images.githubusercontent.com/14945613/45609574-69f7f880-ba0d-11e8-8599-bd7405b13446.png">

i want to pay them out. :-D

**Comment by vojtechsimetka** [comment]
Oh @perissology  will have to fix those :(. For some reason feathers did not register the create event so they are still in a Proposed state and the plugin address was not saved :(.

**Comment by vojtechsimetka** [comment]
These are the milestones:
**Epoch 32** https://feathers.beta.giveth.io/milestones/5b72c2e7a5f82545c38d2d05
**Epoch 31** https://feathers.beta.giveth.io/milestones/5b72c17aa5f82545c38d2d04

**Comment by vojtechsimetka** [comment]
Oh actually I just reprocessed all the events after 2018-08-20 and it got fixed.
