### ISSUE TITLE
When donating to a milestone, the default suggested amount is blank

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#470]
<img width="1050" alt="screen shot 2018-09-17 at 10 49 37 am" src="https://user-images.githubusercontent.com/14945613/45640462-99d3ea00-ba67-11e8-8c6d-4b73a8fe007c.png">

This is a different screen then when delegating from the my delegations screen... in that screen the entire requested amount is shown and you can use a slider to choose the amount... that screen works really well and makes it easy to donate as much as possible, it either caps out on the total you have to delegate, or the size of the milestone, whichever is less (the actual max) i would love to see this in the donation screen too!

<img width="986" alt="screen shot 2018-09-17 at 11 11 31 am" src="https://user-images.githubusercontent.com/14945613/45641627-d3f2bb00-ba6a-11e8-95d5-f33f6aba6937.png">

**Comment by anshumanv** [comment]
Hey @vojtechsimetka @GriffGreen can I work on this?

**Comment by vojtechsimetka** [comment]
Hey, sure!

**Comment by vojtechsimetka** [comment]
This should work similar to delegate button.

**Comment by anshumanv** [comment]
Ah missed this :sweat_smile: 

On it along with #474

**Comment by anshumanv** [comment]
@vojtechsimetka can this be closed too or do we need some more changes here? :smile:
