### ISSUE TITLE
Can't view Donations at the bottom of some milestones

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#472]
<img width="984" alt="screen shot 2018-09-17 at 3 29 31 pm" src="https://user-images.githubusercontent.com/14945613/45654025-d6ffa280-ba8e-11e8-8c2f-9410b333d33f.png">

i get the dancing green dot at the bottom of: 
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b72c17aa5f82545c38d2d04 

https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b98826990b3c1478f06b462

https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5b86e7ab3f1b956d7ccce470

https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5b5ed9ce4745ce2cd04ac159

ok wait.. now i'm having trouble finding milestones where the donations are showing :-(

**Comment by GriffGreen** [comment]
Do you have an estimate on when this will be fixed in the deployed version? I am trying to do some accounting with DAppNode and i need to confirm that I didn't donate directly to any milestones. I think it can wait, no need to rush it in, but if you have a time line that would help me out.

**Comment by GriffGreen** [comment]
Reopening it cause i'm an attention whore

**Comment by vojtechsimetka** [comment]
Closing again as I pushed it to beta :) https://beta.giveth.io/campaigns/5b44b198647f33526e67c262
