### ISSUE TITLE
Home page goes to Communities but for the UI as it is, Campaigns are the main attractions 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#476]
Can we point the home page to "Campaigns"?

**Comment by vojtechsimetka** [comment]
I actually had this in one of my branches before my computer crashed. There should be one page called explore where both Campaigns and Communities are.

**Comment by GriffGreen** [comment]
@vojtechsimetka WOW 😻 that is a gorgeous plan!
I love the "recently visited" section especially... i think that will help A LOT.

But that will take a big effort... for the time being while we are showing people the DApp, can we have a simple redirect making the home page campaigns, and DAC's can have it's own page like campaigns do now?

**Comment by vojtechsimetka** [comment]
Yeah I will fix this for the next release before devcon. It is part of simplifying some components.
