### ISSUE TITLE
Canceled & rejected Milestones are not showing up 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#481]
Just asked someone to cancel my Milestone I know for sure I have had some in the past, 
These tabs are empty however - can we bring these back? I need the info that's there :) 

![image](https://user-images.githubusercontent.com/6533925/45971475-64b43280-c039-11e8-8e3b-4abf9f23993b.png)

**Comment by vojtechsimetka** [comment]
All non-paid milestones before 1st of July have not been migrated. So if it is before that then no. Otherwise this tab works, I have 2 canceled milestones there.

**Comment by krrisis** [comment]
Aaaand.. I found it. Person who was going to cancel didn't cancel and missed it, my mistake, apologies!
