### ISSUE TITLE
Token Integration

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#484]
The aim is to allow ERC20 tokens like DAI to be used in the DApp in addition to ether. The Liquid Pledging smart contracts support ERC20 tokens, the feathers has some support but the UI support is missing. 

In the current design the smart contract plugins are written to accept any whitelisted token donation for DACs and Campaigns. At the creation of milestone users have to choose which token or ether will the milestone accept. The steps are:

Receiving donations:
- [x] Allow donating and displaying tokens to DACs and Campaigns in the UI and feathers
- [x] Rewrite the feathers conversion service and corresponding UI components to allow conversion between selected fiat currencies and whitelisted tokens and ether/bitcoin

Payouts
- [x] Modify the milestone creating allowing users to select which token or ether will the milestone accept
- [x] Modify delegation workflow to allow token delegation
- [x] Thoroughly test the DApp and the bridge

**Time estimate:**
160-200 man hours

**Comment by perissology** [comment]
done
