### ISSUE TITLE
Donations aren't showing up under "Amount Donated"

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#492]
i started delegating to a bunch of campaigns but its not showing up...

Under https://beta.giveth.io/donations it shows i donated to this milestone:
<img width="1174" alt="screen shot 2018-10-10 at 12 21 49 am" src="https://user-images.githubusercontent.com/14945613/46702316-e784e200-cc22-11e8-932c-fd80f3af63b2.png">

but when you check out the milestone in the campaign's page or in the milestone's page the Amount Donated is still 0
<img width="651" alt="screen shot 2018-10-10 at 12 21 26 am" src="https://user-images.githubusercontent.com/14945613/46702358-126f3600-cc23-11e8-98f3-5293d7e11a59.png">

**Comment by cryptomental** [comment]
Hi. I was just about to open a similar ticket. I started working today on https://github.com/Giveth/giveth-dapp/issues/67 and spent way too much time on this already, stuck with this issue as well ;)

I would be grateful if somebody set up the most recent develop branch of feathers and dapp and confirmed that. Perhaps @vojtechsimetka ?

I will  also open a separate ticket for broken my-milestones view.

**Comment by vojtechsimetka** [comment]
There is just some undefined value passed to the Donation model which throws error that is uncaught. Just check the model which of the attributes is incorrect and loosen it if needed.

For the develop environment please try develop.giveth.io (thanks @perissology for fixing it!)

**Comment by cryptomental** [comment]
The reason for '0' amount was likely due to donations for the milestones were actually targeted to the campaign. With the simple fix donate milestone button is now unlocked so that donations to milestones within campaigns work as expected.

**Comment by GriffGreen** [comment]
this small fix fixes the flashing green dot under "Donations" for every single milestone @vojtechsimetka ? If so... can i beg for a hot fix... I am trying to do some accounting with DAppNode and i need to confirm that I didnt donate directly to any milestones.

**Comment by GriffGreen** [comment]
Oh never mind... its a different issue probably... i'm looking for this one:
<img width="852" alt="screen shot 2018-10-17 at 12 07 49 am" src="https://user-images.githubusercontent.com/14945613/47050483-d1d26800-d1a0-11e8-9e49-674ab93e5715.png">

**Comment by cryptomental** [comment]
Hi, exactly this green dot on milestone view will be fixed with
https://github.com/Giveth/giveth-dapp/commit/68fa1d2bc3d6fd98a009311afd78f80b6ce8f770
commit.
I had to implement the same fix when I was working on #67
