### ISSUE TITLE
Broken milestones view and milestone view donated amount 0 after donating to milestones

### ISSUE THREAD

**Issue by cryptomental** [Giveth/giveth-dapp#493]
While trying to set up  https://github.com/Giveth/giveth-dapp/issues/67 I encountered an issue where the milestones view is broken after donating to milestones. There is a hotfix branch with the fix which seems to solve it, but on the milestone view total donated amount is 0.

This issue seems to be related to https://github.com/Giveth/giveth-dapp/issues/492

I am pasting a few screenshots I did on my way for reference.

![screenshot from 2018-10-09 22 45 34](https://user-images.githubusercontent.com/20819151/46703030-b659e100-cc25-11e8-9947-0a95fd2f8ab4.png)
![screenshot from 2018-10-09 22 46 51](https://user-images.githubusercontent.com/20819151/46703031-b659e100-cc25-11e8-9884-d9f2bd54b388.png)
![screenshot from 2018-10-09 22 47 00](https://user-images.githubusercontent.com/20819151/46703032-b6f27780-cc25-11e8-9e44-c6734e1c5a97.png)
![screenshot from 2018-10-09 22 47 11](https://user-images.githubusercontent.com/20819151/46703033-b6f27780-cc25-11e8-85ce-9fe390842f94.png)
![screenshot from 2018-10-09 22 48 47](https://user-images.githubusercontent.com/20819151/46703034-b78b0e00-cc25-11e8-8d58-b92efdf1eeae.png)
![screenshot from 2018-10-09 22 49 00](https://user-images.githubusercontent.com/20819151/46703035-b78b0e00-cc25-11e8-9a00-d5e9f595d075.png)
![screenshot from 2018-10-09 22 49 19](https://user-images.githubusercontent.com/20819151/46703036-b78b0e00-cc25-11e8-9e3f-7709bdfe3ca2.png)
![screenshot from 2018-10-09 22 55 23](https://user-images.githubusercontent.com/20819151/46703037-b823a480-cc25-11e8-9372-e0d5802381f0.png)
![screenshot from 2018-10-09 22 55 37](https://user-images.githubusercontent.com/20819151/46703039-b823a480-cc25-11e8-9794-ea96f67bbd92.png)
![screenshot from 2018-10-09 22 55 47](https://user-images.githubusercontent.com/20819151/46703040-b823a480-cc25-11e8-8983-662f8716faec.png)
![screenshot from 2018-10-10 00 21 28](https://user-images.githubusercontent.com/20819151/46703041-b8bc3b00-cc25-11e8-98a3-122392d61faf.png)
![screenshot from 2018-10-10 00 32 07](https://user-images.githubusercontent.com/20819151/46703042-b8bc3b00-cc25-11e8-8a1d-321733d5e440.png)

**Comment by vojtechsimetka** [comment]
There is a hotfix I am waiting for @YalorMewn to confirm it works `hotfix/mymilestonesUndefined`. I'll just merge it then. @cryptomental please pull develop and confirm it is fixed.

**Comment by YalorMewn** [comment]
Hot Fix confirmed 👍

**Comment by cryptomental** [comment]
Can be closed now. Thank you!
