### ISSUE TITLE
Can't add a milestone to campaign

### ISSUE THREAD

**Issue by JeremiGendron** [Giveth/giveth-dapp#496]
Asks at the bottom, which is broken:
Maximum amount in Fiat && Maximum amount in Ether

However, if one of those values isnt rounded, it doesn't allow the creation and also doesn't show any visible error.

Would like to fix, need to get familiar with codebase first. Initially came for #475

**Comment by JeremiGendron** [comment]
Here's a screenshot: [imgur](https://i.imgur.com/aCUZUUQ)

**Comment by vojtechsimetka** [comment]
I guess chrome is again enforcing numbers to follow step attribute. I'll make a fix https://www.isotoma.com/blog/2012/03/02/html5-input-typenumber-and-decimalsfloats-in-chrome/
