### ISSUE TITLE
Not letting me commit donation to milestones

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#504]
Had a couple successes and then this message started coming up repeatedly when trying to commit a donation
<img width="1218" alt="screen shot 2018-10-13 at 4 06 25 pm" src="https://user-images.githubusercontent.com/38163206/46906352-6ec3a580-cf02-11e8-9376-8d70f78bce24.png">
wallet's definitely unlocked ;)

**Comment by GriffGreen** [comment]
yeah and we pushed commit a couple times and it looked like it worked... but then we refreshed the page and it didnt work!

**Comment by GriffGreen** [comment]
![screen shot 2018-10-13 at 9 15 36 pm](https://user-images.githubusercontent.com/14945613/46909088-44d3a880-cf2d-11e8-84e6-e35c301c8063.png)
Thats what dev tools looked like... its still not working
