### ISSUE TITLE
When donating to a partly funded Milestone the amount is no longer automatically calculated 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#509]
Example: the below Milestone [here](https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5bbb4d4a089683199bce5592) is already funded for 0.5 of the amount but when delegating funds it still shows 0.7

![image](https://user-images.githubusercontent.com/6533925/46974623-d9244380-d0c4-11e8-8cf6-7eb45b116474.png)

FYI I think vojtech is on this but posting here on request of @FrederikBolding

**Comment by krrisis** [comment]
Still not working unfortunately @vojtechsimetka - no stress, but @FrederikBolding wants that Milestone completed, so will just fill in the approximate amount now so that this Milestone can be completed, hope you can still reproduce afterwards.

![image](https://user-images.githubusercontent.com/6533925/48001470-f4ed9900-e108-11e8-83b2-41ea8a4392dc.png)

**Comment by FrederikBolding** [comment]
As discussed with @vojtechsimetka in DMs - It seems that the issue is caused because the "data" is bugged, would require reprocessing to fix. It doesn't seem to be happening when running locally and creating new milestones.

**Comment by vojtechsimetka** [comment]
Also we will remove the max amount limitation for milestones very soon, probably not worth spending time on fixing it now.

**Comment by FrederikBolding** [comment]
@vojtechsimetka If that is the case, then sure, it shouldn't be a priority at all 😄

**Comment by GriffGreen** [comment]
There has been a lot of push back from Michael and others about getting rid of the max funding feature... After some consideration, it seems to make sense that choosing a "max funding" for a milestone should still be there by default... unlimited funding can be there for the campaigns. 

If we want to, we could make the default for extra funds that go to a milestone above the max funding that they go into the campaign... that would make a lot of sense... The worry is that the people that make sexy milestones, like feeding orphans, would get over funded and the less sexy but necessary milestones, like cleaning the toilets and managing the accounting for the orphanage, wouldn't get any funding.
