### ISSUE TITLE
The Auto estimator for funding milestones isnt auto calculating the max available

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#519]
<img width="999" alt="screen shot 2018-11-08 at 11 13 10 pm" src="https://user-images.githubusercontent.com/14945613/48230709-410c3800-e3ac-11e8-9217-ff691027cca6.png">

Trying to get rid of some of these small BM donations to get to the tennegraph and aragon dac donations i need to delegate, but i'm scared to over donate to some of the milestones... not sure why the slider is not auto filling the right number like it used to...

<img width="1157" alt="screen shot 2018-11-08 at 11 25 16 pm" src="https://user-images.githubusercontent.com/14945613/48231197-9f85e600-e3ad-11e8-8630-c6bb198e3b79.png">
<img width="1160" alt="screen shot 2018-11-08 at 11 25 03 pm" src="https://user-images.githubusercontent.com/14945613/48231199-9f85e600-e3ad-11e8-92cf-34114ce0c73b.png">

**Comment by GriffGreen** [comment]
its a problem in release too
<img width="992" alt="screen shot 2018-11-09 at 10 06 19 am" src="https://user-images.githubusercontent.com/14945613/48253271-2c10c280-e407-11e8-8566-d032d43a689f.png">
<img width="562" alt="screen shot 2018-11-09 at 10 05 57 am" src="https://user-images.githubusercontent.com/14945613/48253272-2c10c280-e407-11e8-8ed3-c7f356a3552e.png">

**Comment by anshumanv** [comment]
I think it was decided to prefill the max donation amount, what would be the ideal amount @GriffGreen @vojtechsimetka ?

**Comment by perissology** [comment]
I don't think this is an issue any longer
