### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#520]
<img width="1276" alt="screen shot 2018-11-08 at 11 28 45 pm" src="https://user-images.githubusercontent.com/14945613/48231365-1de28800-e3ae-11e8-8a4c-0fb9b1518c13.png">

**Comment by anshumanv** [comment]
Ideally, all cards should be of the same size, have any ideas about this @vojtechsimetka ?

**Comment by ewingrj** [comment]
this is fixed
