### ISSUE TITLE
Authorized payment missing from bridge?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#529]
Hey, do you guys know the status of this milestone? It says completed, but it's not in the list on the bridge. https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5bd6aacf90748f ?

**Comment by perissology** [comment]
I think that the link got cut off? I can't access the milestone

**Comment by jvluso** [comment]
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5bd6aacf90748f6a14206928

**Comment by perissology** [comment]
doesn't look like it's been disbursed, only marked complete.

`0x901CE5e910061c5c56F6E4F85B027eb30bCa9b40` or `0x1424F8b752788841eFAE5965f76Ed168DDa6c822` needs to disburse the payment from the 'My Milestones' page

**Comment by vojtechsimetka** [comment]
Not an issue, it was not disbursed and here is the bridge TX - https://etherscan.io/tx/0x15816da6b8ccb54fd0ff49f79393b557712e18d22c45b8046a47ba8dbbb9e8dd
