### ISSUE TITLE
Slack symbol for Join our community button

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#53]
The join our community button displays slack symbol even though the community does not necessarily need to be on slack.

![screen shot 2017-10-11 at 13 39 48](https://user-images.githubusercontent.com/7974813/31438759-c8cf8a7a-ae89-11e7-891a-015656135d97.png)

**Comment by satyavh** [comment]
It dynamically changes the icon based on the community url that you put for the DAC. Communities supported:

slack, reddit, linkedin, facebook, github, twitter

And otherwise it wont show an icon
