### ISSUE TITLE
Token Bug fixes before release

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#530]
- [x] milestone amount donated shows 0 even after a token donation.
- [x] My donations has no indication of the donation type, just the amount
- [x] my delegations always says eth
- [x] my communities doesn't show the counters
- [x] I think feathers donation counters in general is not working

**Comment by satyavh** [comment]
If this is on develop, they are all resolved. The db wasn't migrated yet and Ropsten ETH wasn't correctly whitelisted.

What is a problem is donations 'multiplying'

**Comment by vojtechsimetka** [comment]
@satyavh it still does not work well for me locally.

**Reproduce:**
1. Clear `data` and local mongo DB, redeploy everything with `node scripts/deploy.js`
2. Sign in with first testrpc key
3. Create DAC
4. Donate to it 1 ETH and 20 ANT tokens

later on

5. Create Campaign
6. Try Delegating to the Campaign

**Problems:**
- [ ] There is this error in feathers once there is enough confirmations - probably the reason for many of the problems mentioned below.
```
info: Handling Event:  {
  "_id": "5bf2cdf1d5a11861663c2329",
  "topics": [],
  "status": "Waiting",
  "logIndex": 3,
  "transactionIndex": 0,
  "transactionHash": "0x38436750fd83b4fc2ca6a21ac3dcd309093afd13c5bdd60f84ed23ca52e9cd4e",
  "blockHash": "0x742709746a096d0c861362d283645b3d690f619d2cc0cc09be77a3b0ceab1872",
  "blockNumber": 192,
  "address": "0xBeFdf675cb73813952C5A9E4B84ea8B866DBA592",
  "type": "mined",
  "id": "log_d38dc953",
  "returnValues": {
    "0": "3",
    "1": "4",
    "2": "20000000000000000000",
    "from": "3",
    "to": "4",
    "amount": "20000000000000000000"
  },
  "event": "Transfer",
  "signature": "0xaf6151f5085accf2d57e1e7bf7601d3b3982e0de7e9a90f032f8554de9c104f6",
  "raw": {
    "data": "0x000000000000000000000000000000000000000000000001158e460913d00000",
    "topics": [
      "0xaf6151f5085accf2d57e1e7bf7601d3b3982e0de7e9a90f032f8554de9c104f6",
      "0x0000000000000000000000000000000000000000000000000000000000000003",
      "0x0000000000000000000000000000000000000000000000000000000000000004"
    ]
  },
  "confirmations": 0,
  "createdAt": "2018-11-19T14:51:29.951Z",
  "updatedAt": "2018-11-19T14:51:29.951Z"
} 

```

- [ ] The My Donation page does not show in which currency the donations are (once they have all the confirmations).
<img width="1920" alt="screen shot 2018-11-19 at 15 51 54" src="https://user-images.githubusercontent.com/7974813/48714742-a31e3600-ec13-11e8-9303-fed29b53d391.png">

- [ ] My Delegations show ETH as the currency for everything
<img width="1587" alt="screen shot 2018-11-19 at 15 57 07" src="https://user-images.githubusercontent.com/7974813/48714827-d8c31f00-ec13-11e8-986d-f6b41726b00c.png">

- [ ] The delegate button in the Campaign says there are no funds to be delegated even though there are.
<img width="1362" alt="screen shot 2018-11-19 at 15 59 56" src="https://user-images.githubusercontent.com/7974813/48715203-c3022980-ec14-11e8-8a48-91de14aed037.png">

- [ ] The delegate button in My Delegations shows ETH even for the token donation
<img width="1330" alt="screen shot 2018-11-19 at 15 59 16" src="https://user-images.githubusercontent.com/7974813/48715236-d7debd00-ec14-11e8-8e95-366eac2cce7c.png">
