### ISSUE TITLE
Campaign becomes undefined when editing a milestone

### ISSUE THREAD

**Issue by 0x6431346e** [Giveth/giveth-dapp#533]
The url looks like this `https://beta.giveth.io/campaigns/{id}/milestones/{id}`, but when I press edit milestone it becomes `https://beta.giveth.io/campaigns/undefined/milestones/{id}`

**Comment by vojtechsimetka** [comment]
@satyavh will fix this with his rewrite of Milestones :)

**Comment by perissology** [comment]
fixed in bd2151d
