### ISSUE TITLE
Mails notifications from the DApp no longer arriving at all (on hotmail) 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#534]
... not even in spam, although I now see that I have 5 or 6 Milestones to review

**Comment by vojtechsimetka** [comment]
@krrisis is this still the case? I've received 2 today

**Comment by krrisis** [comment]
well no new requests today but for the ones I had I never got any mail - can check back in here to confirm when I get new requests

**Comment by krrisis** [comment]
nope, new milestones, no mail notification

**Comment by vojtechsimetka** [comment]
yeah.... you were unlucky I actually switched off the notifications as I needed to reprocess the whole DB. It is up now....

**Comment by vojtechsimetka** [comment]
Worked for me, closing

<img width="607" alt="screen shot 2018-11-29 at 21 34 48" src="https://user-images.githubusercontent.com/7974813/49250360-ec923080-f41e-11e8-886e-21a36807d424.png">

**Comment by krrisis** [comment]
Has not worked since I first mentioned it. Don't want to again give in another of my personal mails so reopening this - it is already bad enough that my main mail address is stored on the blockchain (hope we can figure out a better notification system soon vojtech or @mroberts10 )

**Comment by perissology** [comment]
not an issue for me. Maybe you clicked unsubscribe at some point? We have no way to manage that in the dapp yet

**Comment by krrisis** [comment]
Is it no issue for you on hotmail or on another service? Nope, didn't hit unsubscribe. Mails simply not arriving.

**Comment by vojtechsimetka** [comment]
Nope I am also getting spammed, so are 2 other people who reached out to me about that.

**Comment by krrisis** [comment]
You mean that you do receive them on hotmail? And yeah, I know that helps, tried it before, but as said that is another of my mail addresses that will be written permanently & publicly on the blockchain. 
If it works for other people on hotmail (if that's what you're saying) you can close and I'll create a temp fwd address.

**Comment by vojtechsimetka** [comment]
None of them uses hotmail, nor do I sorry. I may test it later but to fix this could be a challenge.

**Comment by ewingrj** [comment]
okay, I've changed mail providers. Other than that, there's nothing I can do. Hopefully it works for you now.

**Comment by krrisis** [comment]
It did not but now I created a mail forwarder address, so now I finally get them. thx!
