### ISSUE TITLE
'enable web3' button does not function when not logged into metamask

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#539]
When not logged in in metamask and you click enable web3 nothing happens when you click the button. 
Metamask logs out automatically by default, so if there's nothing here, we prob need this.
solution could be:

- action: click button 
- if not logged in: pop-up on site: please log in to metamask to continue 

Console log below, just in case this use case already exists (but don't think the issue is in there.) 

![image](https://user-images.githubusercontent.com/6533925/49182185-d66e6c80-f359-11e8-8427-c6f8e67ff035.png)

**Comment by krrisis** [comment]
Ok could not reproduce now after logging out, but had the same thing yesterday, so keeping this open for now. 
Now I do see the log in to metamask message + pop-up from metamask (yay!) 

Other Q: 
1) will we get this request to connect our account every time after logging in? (see screenshot below) Why is this needed as I already authorized this? 
2) for people who just want to browse this pop up might be annoying? I very often go to milestones without needing to be logged in (just check milestones etc) -- maybe better that the pop up comes only when hitting 'log in'? 

![image](https://user-images.githubusercontent.com/6533925/49182565-eb97cb00-f35a-11e8-9aef-ce734eea78f5.png)

**Comment by vojtechsimetka** [comment]
Yes you will receive this every time, this is the new metamask thing we have no control over. The only thing we could do (though would huge changes across the DApp) is to ask for it when you first time sign TX. Just like we do right now with sign in.

**Comment by perissology** [comment]
metamask should actually cache your approval. maybe they broke that or you are using an old version, so you should only see that 1 time.

however, we have no ability to see you addresses until you "approve" the dapp. If we don't see you address, then we don't know who you are.

The other option would be to make users explicitly click a button like "connect metamask" to sign in. I'm not sure if that is much better. Maybe try an make sure your metamask is up to date b/c I don't see that window everytime.

Actually, have you enabled "privacy mode" in metamask? I think it is opt in currently.

**Comment by perissology** [comment]
I'm also curious about the log out thing. metamask does not log me out automatically unless the browser is closed.

How long do you have to wait for the auto logout to happen?

**Comment by krrisis** [comment]
yeah log out doesn't seem to have happened recently (was prob in the previous version).  

'metamask should actually cache your approval. maybe they broke that or you are using an old version, so you should only see that 1 time.' --> I have the latest version. It does ask for approval again every time though. 

I think you could steal quite some things from the gitcoin userflow by the way. So when I'm still on mainnet on the dapp I, as a user might forget I still have to switch from mainnet to rinkeby (after clicking the connect buttons) and don't know why my account doesn't show up. On gitcoin it gives you a double warning that I'm on the wrong network: 
![image](https://user-images.githubusercontent.com/6533925/49381845-29a73d00-f715-11e8-8eea-e76a559e6c65.png)

Other warning is that my metamask is set to the wrong address, also a very important one ofc, as people will often have to switch:

![image](https://user-images.githubusercontent.com/6533925/49381971-7a1e9a80-f715-11e8-826c-32f94ef5b518.png)

hope this is useful!
