### ISSUE TITLE
my delegation and my dontation pages won't load

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#540]
Below is the error i get for delegations
<img width="584" alt="screen shot 2018-11-29 at 2 03 30 am" src="https://user-images.githubusercontent.com/14945613/49192603-fd3d9a80-f37b-11e8-9541-fc1c5b9d0d50.png">
<img width="1167" alt="screen shot 2018-11-29 at 2 12 30 am" src="https://user-images.githubusercontent.com/14945613/49192678-5e656e00-f37c-11e8-89c9-501268cf1636.png">

Below is the error i get for donations:
<img width="839" alt="screen shot 2018-11-29 at 2 04 23 am" src="https://user-images.githubusercontent.com/14945613/49192602-fca50400-f37b-11e8-911f-d2ed9a24a0af.png">
<img width="1149" alt="screen shot 2018-11-29 at 2 12 59 am" src="https://user-images.githubusercontent.com/14945613/49192670-573e6000-f37c-11e8-90da-698f06e1ccc6.png">

**Comment by vojtechsimetka** [comment]
Fixed in https://github.com/Giveth/feathers-giveth/commit/5efdf8836ac6dddc92bc771a413cb3c8a1f7015d
