### ISSUE TITLE
delegating not working

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#546]
Heard people say this does not work, but don't see an issue, maybe it's a different one, so here we go.
When I want to fund a Milestone, I cannot select the Milestone, see below. I'm logged in on rinkeby with the right account.

![delegate](https://user-images.githubusercontent.com/6533925/49383970-46923f00-f71a-11e8-9775-7703f3802fc0.gif)

**Comment by satyavh** [comment]
What browser is that?

**Comment by krrisis** [comment]
Chrome, latest version

**Comment by krrisis** [comment]
still not working :/

**Comment by krrisis** [comment]
This one is working now indeed. Thx @perissology
