### ISSUE TITLE
GivETH currency in dapp is confusing (required fix for DAI reward)

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#548]
We (@bowensanders @danibelle @GriffGreen & me) just noticed a new currency (?) in the dapp. This GivEth token has a different value depending on the moment of the month? Also a bit confusing knowing that we used that token earlier for other purposes. Maybe best to disable for now? 

![image](https://user-images.githubusercontent.com/6533925/49469672-6e5fd080-f808-11e8-8a99-abc790206ca6.png)

**Comment by satyavh** [comment]
Fixed
