### ISSUE TITLE
Can't see the balances for any campaigns (required fix for DAI reward)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#549]
:-( We don't know how much ETH is in RewardDAO, we need a way to display the balances for tokens and ETH for everyone to see.

**Comment by GriffGreen** [comment]
Shutting down the browser fixed it...

**Comment by GriffGreen** [comment]
I got screen shots man, in the last version there were balances:
<img width="257" alt="screen shot 2018-11-04 at 12 59 02 am" src="https://user-images.githubusercontent.com/14945613/49891722-81e1eb80-fe47-11e8-93bf-60b9ac58b5f0.png">
this feature was removed in the latest upgrade, I assume because including it would be difficult in token integration. It is necessary.

**Comment by satyavh** [comment]
You're right, I'm wrong! I will get those balances back

**Comment by satyavh** [comment]
It's on beta
