### ISSUE TITLE
The ability to edit amounts and recipients in milestones after proposed has been disabled?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#550]
<img width="924" alt="screen shot 2018-12-05 at 3 35 27 am" src="https://user-images.githubusercontent.com/14945613/49486463-d9c49500-f83e-11e8-8946-4d2009248129.png">
You used to be able to edit amount and recipient.... but now you can't?

**Comment by lorelei1** [comment]
Is this desired editing taking place after proposing and before campaign manager accepting? 

Honestly if it's after anyone else has reviewed it (campaign mgr or reviewer) I think editing these fields should NOT be allowed. Its too easy to slip under someone's nose the change of a SIGNIFICANT detail. There's a reason the amount and recipient are the most sensitive details of a milestone.
