### ISSUE TITLE
Can't delegate to new milestones from the DAC (required fix for DAI reward)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#552]
<img width="993" alt="screen shot 2018-12-05 at 7 17 57 pm" src="https://user-images.githubusercontent.com/14945613/49534793-c78c3a80-f8c2-11e8-8cbd-f2be03f8c825.png">
It only allows DAC's right now to donate to Campaigns... how do DACs donate to milestones?

**Comment by vojtechsimetka** [comment]
The problem is that there is a limit to how many Campaigns and Milestones are visible in that screen with Campaigns being the first ones so it does not show any Milestone for you

**Comment by satyavh** [comment]
This should be fixed, please check

**Comment by GriffGreen** [comment]
yeah its fixed
