### ISSUE TITLE
The text in DAI milestones around DAI is weird

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#554]
<img width="895" alt="screen shot 2018-12-06 at 1 30 00 am" src="https://user-images.githubusercontent.com/14945613/49553146-9299db00-f8f6-11e8-95d7-d5d184ad15ac.png">

It currently says:
ETH 15
1 Maker DAI = 1 ETH

This should say: 
15 DAI
1 DAI = 1 DAI

(You can leave out Maker)

**Comment by satyavh** [comment]
This won't be fixed retrospectively, only for new actions within the system

**Comment by GriffGreen** [comment]
this has my 👍
