### ISSUE TITLE
Changing accounts does not refresh token balance

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#555]
<img width="1231" alt="screen shot 2018-12-06 at 1 36 11 am" src="https://user-images.githubusercontent.com/14945613/49553335-91b57900-f8f7-11e8-9dc2-25dfc9371eee.png">

**Comment by GriffGreen** [comment]
Oh I figured it out... i had to refresh the page... but basically my old account's balance lingered... 
1. was on rinkeby with Key1
2. Switched to mainnet 
3. Switched accounts
balance showed 0....
Refreshed to fix it

**Comment by vojtechsimetka** [comment]
So the issue is that changing accounts within network does not refresh the balances.

**Comment by gil-air-may** [comment]
Interesting... I tried to test this locally, but I was not able to reproduce the behavior.

For reference:

![issue#555](https://user-images.githubusercontent.com/34509679/55744728-f864b380-5a0b-11e9-8e8f-869628e6cec7.gif)

**Comment by jurek1oo** [comment]
Hi there,
I had a look at changing accounts on local network, when trying to donate to a milestone. I can not reproduce error, as the value of the available funds on the accounts change on the page. According to the actual value of the account in the Metamask. Has that issue been resolved?

**Comment by jurek1oo** [comment]
pics of two different accounts: 
![image](https://user-images.githubusercontent.com/3112638/64904594-61a4cd00-d6f6-11e9-9d8e-6dce67a74ff3.png)
![donateMile-Doe3-$100-2019-09-14 13-39-00](https://user-images.githubusercontent.com/3112638/64904598-7da86e80-d6f6-11e9-8b40-5098ca3f1c03.png)
