### ISSUE TITLE
Can't navigate to the second page in the Donation Page (required fix for DAI reward)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#557]
The pagination doesn't work... or at least, i can't get to the second page of donations right now
<img width="1248" alt="screen shot 2018-12-07 at 2 14 12 pm" src="https://user-images.githubusercontent.com/14945613/49649768-68493a00-fa2a-11e8-8b8f-e71782636fa9.png">

**Comment by satyavh** [comment]
This is not caused by the token integration, as such not part of the Dai reward.
I will have a look and fix it though.

**Comment by satyavh** [comment]
Are you still experiencing this issue, because I cannot replicate it.
If yes, please click on REPORT and check if it shows any error

**Comment by GriffGreen** [comment]
clicked report
It was fixed for a day.... but its broken again
<img width="1012" alt="screen shot 2018-12-15 at 7 51 08 am" src="https://user-images.githubusercontent.com/14945613/50040149-55dc8b00-003e-11e9-8664-d30c30090c5f.png">

**Comment by GriffGreen** [comment]
> This is not caused by the token integration, as such not part of the Dai reward.
> I will have a look and fix it though.

The thing is... the is a bug that had been fixed but now is reintroduced from the last upgrade that greatly affects the use of the dapp (I can't commit donations early after delegating) The DAI integration can't be considered complete until the new bugs introduced are fixed.
