### ISSUE TITLE
When proposing a milestone, DAI is not in the list of currencies and 1 DAI != 1 USD right now?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#562]
<img width="906" alt="screen shot 2018-12-10 at 1 55 09 am" src="https://user-images.githubusercontent.com/14945613/49705506-e9692280-fc1e-11e8-9442-6c513c6307f1.png">

1 DAI = 1.01 USD ? 

Milestones need to be able to be made in DAI directly.

**Comment by satyavh** [comment]
This is correct. Dai is not 1 USD
https://coinmarketcap.com/currencies/dai/

**Comment by satyavh** [comment]
FYI; I understand what you want, and you could make this a feature requests.
But this is not an issue caused by token integration.

**Comment by GriffGreen** [comment]
That doesn't make any sense... this is totally within the scope. The token isnt integrated if it cannot be selected as a currency for payment. Thats a core part of integration. being able to denominate milestones in DAI is part of the token integration

**Comment by satyavh** [comment]
It's now in on beta, please check
