### ISSUE TITLE
When creating a new milestone, but rejecting the transaction, the whole milestone is stuck

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#563]
It would be nice if you could reject the transaction and then the button came back and you could change what you wanted to change (the reason you rejected the transaction) and then submit the transaction:
<img width="1221" alt="screen shot 2018-12-10 at 2 14 43 am" src="https://user-images.githubusercontent.com/14945613/49705801-672e2d80-fc21-11e8-8473-27f4c5fb981c.png">

The big problem is you lose your work... :-( and have to copy paste everything to a new milestone... 

when this happens to you the first time... you get really turned off making milestones... 

the 10th time... you make an issue, then open up another window, copy paste everything and continue on with a new milestone and a new day :-D

**Comment by GriffGreen** [comment]
this is a soft ball

**Comment by vojtechsimetka** [comment]
It is very likely there is `this.setState({isLoading: false})` missing when the tx is rejected.

**Comment by ElMejorge** [comment]
This got solved sometime before me but the issue was not closed.
