### ISSUE TITLE
"Attached Proof" button is a weirdly named, and there's no way to remove them once added

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#564]
Attach Proof should be renamed its sort of weird and doesn't capture the entire set of use cases, which is very well lined out on the "Add multiple expenses, invoices or items" switch.

- [ ] I would suggest "Add Line Item" as a new name for that button.

- [ ] Also, it would be nice if we could remove a line item once added, if there was a mistake in it... instead, if we dont like the name we gave a line item... we have to recreate a whole milestone!
<img width="968" alt="screen shot 2018-12-10 at 2 50 30 am" src="https://user-images.githubusercontent.com/14945613/49706606-26d1ae00-fc27-11e8-8ee5-faf5aa5fc4f4.png">

**Comment by vojtechsimetka** [comment]
You can remove them, just scroll right.

**Comment by GriffGreen** [comment]
Ok... so thats a bug as well... Actions need to be visible

**Comment by GriffGreen** [comment]
Looks great!!!
