### ISSUE TITLE
Whitelist Datafund

### ISSUE THREAD

**Issue by mmohorko** [Giveth/giveth-dapp#567]
Please whitelist Datafund so we can take our campaigns live on beta. 

0x58E017795699cEB023dDa1a370F789C49ee6aDE2 

You can find our campaigns in the testing environment here: 

https://release.giveth.io/campaigns/5be5617ba42e9c652fdbf81e 
https://release.giveth.io/campaigns/5bec221ea42e9c652fdbf830

The addresses have been added to the beta users whitelist form (https://docs.google.com/spreadsheets/d/1GxsWyMt-O2ZCmeho5Ui814WzSgebQTJF_XxiI94UwN8/edit#gid=0) 

Please add us to https://beta.giveth.io/ 

Thank you.

**Comment by Danibelle** [comment]
Confirming DataFund is ready to go on Beta!

**Comment by mmohorko** [comment]
@satyavh - Can you please change the whitelisted address to this one:

0x258FbdBC8500B459a45Bf0932093C888A6676acB 

I am sorry for the inconvenience. 

Thank you.

**Comment by perissology** [comment]
done via riot
