### ISSUE TITLE
Duplicate donation appears in DAC

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#569]
There's definitely only one Griff donation here but the UI on this page shows 2.

<img width="1170" alt="screen shot 2018-12-11 at 2 44 00 pm" src="https://user-images.githubusercontent.com/38163206/49785674-e6bc1980-fd53-11e8-9cf0-e8d0a430f6e9.png">

Elsewhere, in "My Delegations", it appears correct.
<img width="1062" alt="screen shot 2018-12-11 at 2 50 23 pm" src="https://user-images.githubusercontent.com/38163206/49785836-634ef800-fd54-11e8-9e25-62d5c67d9bda.png">

**Comment by perissology** [comment]
is this still an issue? I'm pretty sure it's been fixed

**Comment by lorelei1** [comment]
yep i don't see any issue anymore
