### ISSUE TITLE
Unable to edit milestones

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#571]
When I select the edit pencil at left from My Milestones I receive this error:

![image](https://user-images.githubusercontent.com/39466970/49814417-946cff80-fd37-11e8-9c3d-67e2f69c74a3.png)

Same thing if I go into the milestone and choose the edit pencil from top left.  After closing the error window the dapp stays stuck in the pulsing green dot.

**Comment by lorelei1** [comment]
Similar to my issue #576 but I went at it from the milestone itself and it gave a slightly different error msg.

**Comment by GriffGreen** [comment]
See #566 as well, the work around is to add `/edit` to the milestone's address

**Comment by Danibelle** [comment]
The workaround Griff suggested continually crashed the Dapp previously.

Today I received a different error on attempt to edit..  it's not clear to me WHERE I need to have the ETH from this message, Rinkeby?

![image](https://user-images.githubusercontent.com/39466970/50044734-16219d80-0056-11e9-943f-78a9b0bc5bb3.png)

**Comment by Danibelle** [comment]
Still happening..  when I type /edit at the end of the milestone it just hangs:
![image](https://user-images.githubusercontent.com/39466970/50044774-ba0b4900-0056-11e9-8f50-0e160b33391c.png)

**Comment by Danibelle** [comment]
And clicking the edit button from anywhere changes the URL to undefined:

![image](https://user-images.githubusercontent.com/39466970/50044787-e8892400-0056-11e9-905f-ef555f4729d2.png)

**Comment by satyavh** [comment]
This is fixed, please check
