### ISSUE TITLE
RewardDAO Campaign Ownership Change

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#572]
Dani is taking responsibility for the RewardDAO campaign going forward:

https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424

We need the project owner changed from Lindsay (Griff's Boss) to Danibelle please.

**Comment by Danibelle** [comment]
I'm told RJ @perissology is the only one that can make this change?

**Comment by GriffGreen** [comment]
Linds is the only one who can make that change... RJ is the only one who knows how to do it... i know we did it for another campaign... I just can't remember how

**Comment by perissology** [comment]
done
