### ISSUE TITLE
Donation visible in Delegation page, when it shouldnt be

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#575]
<img width="1010" alt="screen shot 2018-12-12 at 9 36 06 am" src="https://user-images.githubusercontent.com/14945613/49857111-fa1dc200-fdf1-11e8-9185-4cadd60312aa.png">

I am not the delegate of the unicorn dac... so i shouldn't see this donation

**Comment by perissology** [comment]
is this still a problem? What is the exact amount that is showing in the donation?

**Comment by perissology** [comment]
any donation to a dac is appearing in the my-delegations page

**Comment by GriffGreen** [comment]
looks good to me :-D
