### ISSUE TITLE
Can't edit a milestone I just made

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#576]
When I click the edit button i get this message: 
<img width="1171" alt="screen shot 2018-12-12 at 7 30 04 pm" src="https://user-images.githubusercontent.com/38163206/49869928-81942100-fe44-11e8-96cf-ecb07c3df038.png">

**Comment by satyavh** [comment]
From where did you click the edit button?

**Comment by satyavh** [comment]
#566 is fixed, so please check if this issue is still the case
