### ISSUE TITLE
Display popup when any metamask tx is executed

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#578]
I do see the notification in the metamask extension but no pop-up or question from the interface to go sign them.

**Comment by satyavh** [comment]
Are you stating a fact of observation or requesting a feature?

**Comment by krrisis** [comment]
Both I guess?

**Comment by perissology** [comment]
There are some weird quirks w/ metamask. Ideally we would show a msg informing the user they need to sign the metamask tx. We do this for logging in. We need to do this everywhere b/c we have 0 control on if the popup will appear

**Comment by ewingrj** [comment]
We already do this when we ask a user to signin, but we should do it for all actions

**Comment by krrisis** [comment]
seems to be ok and outdated - closing this
