### ISSUE TITLE
Can not start campaign with locked wallet

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#58]
The Start Campaign button does not work if the wallet is locked but you can still create a DAC. Except for some graphical glitches, clicking the button does nothing.

**Comment by satyavh** [comment]
Can you make a reproduction scenario?
Start campaign is related to campaigns, but you are talking about DACs...

And how did you get to the edit page if your wallet is locked?

**Comment by vsimetka** [comment]
Here. Just lock your wallet and try.

https://www.dropbox.com/s/iqocn1x0xiwq8lr/can%27t%20create%20campaign.mov?dl=0

**Comment by satyavh** [comment]
Huh that's so weird. I really can't reproduce this locally but I see it on MVP.
@perissology do you have any idea?
