### ISSUE TITLE
When donating DAI, the max amount of the milestone is not auto calculated 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#581]
Also related to #509 but unlike #509, this deals with new money coming into the system and is much more critical.

The slide bar shouldn't let me over donate to the milestone... this could be a potential security hole and cause a lot of drama around missing donations.... as in, lets say i donate too much... what happens? Am i over approved? Do i send money in and it ends up as a pledge somewhere? This is a critical fix as it could lead to major issues.

Milestone:
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c114ac34a43c73a7ca14108

<img width="1109" alt="screen shot 2018-12-17 at 4 06 18 am" src="https://user-images.githubusercontent.com/14945613/50064564-20f14500-01b2-11e9-8434-b6680e6e36f8.png">

**Comment by satyavh** [comment]
Actually, the milestone contract returns any excessive funds. 
But yes, the input/slider should 'enforce' it.

**Comment by GriffGreen** [comment]
returns it how? Thats easy to do when its ETH... but with a token, its a lot easier to cause UX issues... if it works at all. And how does the UI react?

**Comment by satyavh** [comment]
LP cancels the exceeding amount of the pledge and returns those funds. The bridge should pick it up. Not sure if and how the UI reacts. 

https://github.com/Giveth/lpp-capped-milestone/blob/master/contracts/LPPCappedMilestone.sol#L330-L340

I don't know if it has been tested at all.

**Comment by satyavh** [comment]
I have fixed this, please check. 
(I also might have fixed your delegation issue, but maybe not)

**Comment by GriffGreen** [comment]
see #587 The bridge doesnt pick up DAI refunds :-(
