### ISSUE TITLE
Milestone erroring out

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#582]
I know this milestone was viewable recently, like yesterday....
<img width="900" alt="screen shot 2018-12-18 at 10 57 56 pm" src="https://user-images.githubusercontent.com/38163206/50166375-86137a80-0319-11e9-8619-944b595bc87b.png">

buuut when I click on it it brings me here: 

<img width="855" alt="screen shot 2018-12-18 at 10 57 07 pm" src="https://user-images.githubusercontent.com/38163206/50166400-90357900-0319-11e9-8c5c-44629690e978.png">

:( 

I believe Matt Carano's other milestone just beneath it is erroring out in the same way.

**Comment by satyavh** [comment]
Sorry about that. There are some edge cases in the beta database that apparently are not handled well. Should be fixed now.
