### ISSUE TITLE
Donated a bunch of DAI to some milestones and they went into limbo

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#584]
I tried to donate DAI in these transactions:

This one I donated in a standard way: 
https://etherscan.io/tx/0x1e229a2244aabdaacb8ba16de1d27ca581922841f93518c435e3a51d1f934778

This one I donated in my other accounts name:
https://etherscan.io/tx/0x4b1dd4b21ba19f21f349fa0a53d3009a0fbe7f9ae57487be3de4af5a442ce32f

The donations ended up in limbo with a status of "unknown"

<img width="1208" alt="screen shot 2018-12-19 at 1 48 47 pm" src="https://user-images.githubusercontent.com/14945613/50221757-7d14be80-0396-11e9-9383-ca19834613cb.png">

<img width="1143" alt="screen shot 2018-12-19 at 1 46 21 pm" src="https://user-images.githubusercontent.com/14945613/50221759-7dad5500-0396-11e9-874d-8c1a3fc615ea.png">

The Milestones I was donating to were: https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c10f3aa4a43c73a7ca140c7
and
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c10f32f4a43c73a7ca140c5

**Comment by vojtechsimetka** [comment]
Yeah it seems like this just failed and the money got to your giver account instead of the milestone. Sometimes it happens with ether donations as well :(

**Comment by GriffGreen** [comment]
first time i noticed this happening... I will try again and see if we can get it to work

**Comment by GriffGreen** [comment]
Looks like the refunding doesn't work :-( but i should be able to delegate them... 

I am surprised at the failure rate of donating to milestones:

Tried $1 here:
https://etherscan.io/tx/0x907e66386d1e9232f46d9a496ceb130ae9426f2b4b43a477d6cfb2ca5348f3f4

no dice, ended up in ~/my-delegations

then I delegate it to https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c114ac34a43c73a7ca14108, and a transaction happens: https://rinkeby.etherscan.io/tx/0xe6699b2a6529f09f7b6e7dbec036418effec1adede9d3b044ba36c772105ed5a

And the value disappears on the delegation page (the spinning one at the bottom)... 
<img width="1094" alt="screen shot 2018-12-23 at 11 54 49 am" src="https://user-images.githubusercontent.com/14945613/50382908-ab9ddc80-06a9-11e9-923a-a151b3396f4b.png">


but i get an error, when i hit "Report" it says:


      Description of the Error:
      Unable to update the donation in feathers

      Error name:
      donations validation failed: ownerType: Path `ownerType` is required.
      
      Error lineNumber:
      undefined
      
      Error fileName:
      undefined
      
      Error stack:
      BadRequest: donations validation failed: ownerType: Path `ownerType` is required.
    at new s (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:74773)
    at convert (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:76865)
    at r.<anonymous> (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1695529)
    at r.onack (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1762313)
    at r.onpacket (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1761719)
    at r.<anonymous> (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1763770)
    at r.emit (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1716076)
    at r.ondecoded (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1722132)
    at o.<anonymous> (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1763770)
    at o.r.emit (https://beta.giveth.io/static/js/main.4d93ab0b.js:1:1716076)
   


There are other donations that are sitting in my delegation list... it seems like, more often then not, when i donate to a milestone, it fails and instead of the donation going to the milestone the donation goes to the delegation page, and when I try to then delegate those donations, they fail too and the money disappears from the dapp completely...

I am missing a delegation of 2627.97 DAI from the DApp Completely... its just gone...

**Comment by perissology** [comment]
should be fixed
