### ISSUE TITLE
No easy Automated Accounting

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#585]
We need an easy way to pop out the data in each campaign... 

Right now it is almost impossible to actually be transparent with the DApp... cause all the numbers are hidden... It would be so nice to be able to easily pop out a google spreadsheet that shows every milestone and every donation, with as much data as possible.

**Comment by FrederikBolding** [comment]
Shouldn't be that difficult to make some sort of "Export to Excel" button?

**Comment by GriffGreen** [comment]
Exactly... Aragon beat us to it... 
<img width="1204" alt="Screen Shot 2019-04-26 at 12 22 15 AM" src="https://user-images.githubusercontent.com/14945613/56772234-a1a3fb80-67b9-11e9-96b4-06cd5143dc2d.png">

**Comment by GriffGreen** [comment]
Defining the data is the hard part.... maybe there is a user who would want to help us figure it out?

**Comment by FrederikBolding** [comment]
Yeah, I agree. When we know which data to export, the rest is probably quite simple.

**Comment by GriffGreen** [comment]
only for campaign's 
We need to be able to produce a report that show's every financial transaction that happens inside a campaign and every milestone within that campaign

**Comment by arbreton** [comment]
Report regeneration for campaigns, donate directly to a milestone needs to be tracked on the campaign, shows every transaction that happened inside the campaign (collect (disburse), donate, delegate, cancelation of milestones)

**Comment by GriffGreen** [comment]
I finally finished working on the CSV!

https://docs.google.com/spreadsheets/d/1QECQfXulcLXg-fGQzl2UjtrHNHOK36V1m-w0guzgMy8/edit?usp=sharing

See the different tabs

The dream is that this CSV would record a log of every action that happened in the Campaign... Every milestone donation, every edit of text of a milestone description, every change of owner...

Ok but thats the dream.

To start let's just keep the scope at money that is coming in and out of the Campaign (not including milestones) 

:-D

**Comment by aminlatifi** [comment]
CSV demo is available on develop.giveth.io right now.

**Comment by GriffGreen** [comment]
https://docs.google.com/spreadsheets/d/1QECQfXulcLXg-fGQzl2UjtrHNHOK36V1m-w0guzgMy8/edit?usp=sharing

**Comment by GriffGreen** [comment]
one small change...

Direct Donation should change to:
Campaign Donation
Milestone Donation

**Comment by GriffGreen** [comment]
#1255
