### ISSUE TITLE
Campaign pages are not displayed in browsers without metamask support

### ISSUE THREAD

**Issue by igorline** [Giveth/giveth-dapp#586]
I tried to load today the webpage of campaign on the beta portal from brave browser on my mobile and it failed due to some error.
Later on I tried loading webpage from qutebrowser on my laptop and got this error.

![image](https://user-images.githubusercontent.com/1465430/50301807-96963300-0488-11e9-9672-bbec8b546a09.png)

I expect if the page needs to fetch some web3 data more specific error should be showed, like "Your browser does not have Metamask plugin installed"

**Comment by perissology** [comment]
what specific campaign?

**Comment by igorline** [comment]
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c18f6616c76245cd3f97b5b

**Comment by igorline** [comment]
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c18f6616c76245cd3f97b5b

**Comment by igorline** [comment]
Was it fixed? Still can reproduce

**Comment by kelsien** [comment]
This is also an issue in Brave browser, which has native Metamask support.

You can an error code when you click in to a campaign
