### ISSUE TITLE
Refunding DAI doesn't work?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#587]
Tried to get a refund due to #584 and the withdrawal isnt making it to the bridge :-( 

I made a bunch of other actions and they have made it to the bridge... https://bridge.beta.giveth.io/

here is the tx:
https://rinkeby.etherscan.io/tx/0xede7610d9d1e03cbf11823191c8d98333062ff35e7ab09308559d2f5aef93d50

I hope we can get this $2500 out of limbo

**Comment by perissology** [comment]
refunding ETH or DAI only end up in your wallet (https://blockscout.com/eth/rinkeby/address/0x839395e20bbb182fa440d08f850e6c7a8f6f0780/tokens). You'll need to manually call withdraw on the bridge.

ping me if you need help

closing in favor of #591

**Comment by GriffGreen** [comment]
oh shit funny! well that sounds like fun... I should be able to figure it out.
