### ISSUE TITLE
Trying to donate with locked wallet cancels the donation prompt

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#59]
If the wallet is locked and user tries to donate, he/she is asked for password to unlock the wallet. Once entered, the donation prompt disappears and user need to click on the donate button again.

**Comment by satyavh** [comment]
Yes I'm aware of that. The way the wallet is implemented needs to be radically changed in order to change this

**Comment by vojtechsimetka** [comment]
Anyone taking this should wait for #324 to be merged.

**Comment by perissology** [comment]
fixed in aa2d66d282803b5e9de4d8bce01a61da8bfcf2d5
