### ISSUE TITLE
My Delegations page is empty

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#590]
And it shouldn't be! 
<img width="1251" alt="screen shot 2018-12-25 at 2 30 01 pm" src="https://user-images.githubusercontent.com/38163206/50416604-20ad1580-0854-11e9-9b42-8723801eeb2b.png">

I have 6 delegations I should be working with here... you can still see they exist in the DAC page.
<img width="925" alt="screen shot 2018-12-25 at 2 49 14 pm" src="https://user-images.githubusercontent.com/38163206/50416634-476b4c00-0854-11e9-9b44-c44a4c00c027.png">

**Comment by vojtechsimetka** [comment]
Please check but it should be fine now. I was just trying to fix some of the issues

**Comment by lorelei1** [comment]
Sweet, they are back. Thank you!
