### ISSUE TITLE
Can't propose milestone

### ISSUE THREAD

**Issue by helmot** [Giveth/giveth-dapp#593]
ERROR:
      project reviewer address 0x29684371d4dFb108B66B24922679442d3218F560 is not in the whitelist

Campaign:
https://beta.giveth.io/campaigns/5b94a71490b3c1478f06b42b

**Comment by perissology** [comment]
can you try now. I just deployed a fix I made earlier today. I think it should be fixed

**Comment by markhainesii** [comment]
@perissology I'm finding this same error starting a new campaign on feathers-giveth locally.
