### ISSUE TITLE
weird dapp rendering 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#595]
<img width="1375" alt="screen shot 2018-12-27 at 11 22 08 am" src="https://user-images.githubusercontent.com/14945613/50476870-35131e80-09ca-11e9-98cd-6eade157d9c3.png">

Chrome, Macbook

And a great milestone for it to happen on :-D

**Comment by perissology** [comment]
fixed in 282e2e7e9bf7ed7e5ee5f340fe0d0a2636707398
