### ISSUE TITLE
Campaign/Dac donations list sorting & paginated

### ISSUE THREAD

**Issue by ewingrj** [Giveth/giveth-dapp#597]
should be sorted by amount (leaderboard).

also needs to be paginated so all donations can be seen

**Comment by perissology** [comment]
okay @GriffGreen , this isn't so straight forward...

donations can be in multiple tokens. How do we determine the value so we can sort w/ highest value first? Do we make the conversion at the time of the donation?

**Comment by perissology** [comment]
okay, we calculate the usdValue at the time of donation/delegation now. The sorting is live on develop.

still need to do the pagination part

**Comment by perissology** [comment]
donations view should be migrated to behave more like the milestones w/ a "load more" btn & a badge showing new donations since page load

**Comment by GriffGreen** [comment]
Huge fix! Thank you!
