### ISSUE TITLE
Error received on Donating to Milestone

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#599]
Donated to Jeff's milestone for my flight to Prague and received this error:

![image](https://user-images.githubusercontent.com/39466970/50520671-95b85f00-0a8f-11e9-9ac6-a89b47ca5421.png)

I did not get a link to monitor the transaction.

**Comment by perissology** [comment]
This is most likely (but hard to know w/o seeing the error report) the same issue as #577 and is now fixed

**Comment by Danibelle** [comment]
Not sure how to test this since there's already a donation of the full amount, so I can't resubmit the donation.  

I am noticing that it has the funny currency naming of GivETH where it shows CZK conversion rate: 
![image](https://user-images.githubusercontent.com/39466970/50783398-b85d2b80-1278-11e9-8bf4-7cddc9a3b873.png)

**Comment by Danibelle** [comment]
ah ha.  that's my donation. so it went through and didn't know it was me.
