### ISSUE TITLE
Email Notifications for DAI Milestones still use the ETH symbol

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#602]
<img width="538" alt="screen shot 2018-12-30 at 9 09 56 am" src="https://user-images.githubusercontent.com/14945613/50545682-8a913a80-0c19-11e9-9ae8-c96c4edfd952.png">

It says ETH but the milestone is actually: https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c24ac05bf3e293e567c358b

This is really 2 issues wrapped in one... No one uses the 3 line symbol when they talk about ETH... so we should make the ETH symbol just `ETH`

Also we need to make sure the notifications can be aware of the currency that the milestone is in, it looks like this is just hard coded :-P

**Comment by perissology** [comment]
fixed in https://github.com/Giveth/feathers-giveth/commit/8dee504aaa2787427a468dd4374ce38c853c2a55

**Comment by GriffGreen** [comment]
<img width="507" alt="screen shot 2019-01-07 at 3 42 07 am" src="https://user-images.githubusercontent.com/14945613/50746238-5a0b5b00-122e-11e9-8d94-8b5594fac13a.png">
yeah baby!
