### ISSUE TITLE
Donated DAI to the Gov Campaign and got a weird error

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#605]
<img width="1321" alt="screen shot 2019-01-02 at 4 30 28 pm" src="https://user-images.githubusercontent.com/14945613/50598774-10c4af80-0eac-11e9-89b1-01a977923ba0.png">

https://etherscan.io/tx/0x7830ef55a8ed977650ed4ae2f9f26acf2d740dd28c9194e14bfca38633da0765 is the donation

**Comment by perissology** [comment]
Should be fixed in release branch
