### ISSUE TITLE
Make sure that each error message is descriptive and communicates the real issue to the user

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#607]
<img width="1304" alt="screen shot 2019-01-03 at 8 53 52 pm" src="https://user-images.githubusercontent.com/14945613/50658661-5c558700-0f9a-11e9-842f-d2d5aaae8823.png">

When i went to report it, it said: 
      Description of the Error:
      Thare was a problem with the delegation transaction.

      Transaction link:
      https://rinkeby.etherscan.io/tx/undefined
   
Here is the transaction
https://rinkeby.etherscan.io/tx/0xcd63104dfb0beae568769b9b13236d4fbeb37522321632540d6c6645acd3b1fb

but i have no idea if it worked or not because of #574

**Comment by GriffGreen** [comment]
<img width="1118" alt="screen shot 2019-01-03 at 10 41 23 pm" src="https://user-images.githubusercontent.com/14945613/50663113-e1479d00-0fa8-11e9-917b-caac331b3d34.png">
Actually it is still showing up in my donations page

**Comment by perissology** [comment]
The cause of this is most likely poor error handling in the dapp. We need to catch these, especially when they involve a tx

**Comment by GriffGreen** [comment]
So this issue is more about improving the error handling

**Comment by GriffGreen** [comment]
any time there is a call to feathers, the error needs to be wrapped... or something... eliminating the need for signing in will help maybe... i dont know ... just quick notes

**Comment by mroberts10** [comment]
Colleagues in Ukraine looking into this issue

**Comment by arbreton** [comment]
This is greatly improved now with this commit https://github.com/Giveth/giveth-dapp/commit/c5c791e7e7c26f3802fc04a233c85b72d2718c70, but this should be an ongoing revision and text making for specific scenarios

**Comment by arbreton** [comment]
@aminlatifi is improving false positives on errors, completing the last parts of this bug series

**Comment by arbreton** [comment]
#1153 has taken care of

**Comment by GriffGreen** [comment]
Whenever an error happens a pop up is shown... but we don't always show a meaningful message...

**Comment by aminlatifi** [comment]
It happens due to errors thrown by `mTransfer` call to smart contract. Something like this line
https://github.com/Giveth/giveth-dapp/blob/4816a4592180c1f3aeab1909b5e5c4d109508df7/src/services/DonationService.jsx#L196

This should not cause error popup, if e is not defined some warning toast is enough
