### ISSUE TITLE
Change the sign in process to let DAOs use the DApp

### ISSUE THREAD

**Issue by jvluso** [Giveth/giveth-dapp#611]
I'd like to be able to interact with Giveth using a DAO. Supporting pre-signed messages to log in will allow a dao capable of signing those to log in and participate. I'll be working on this and using this issue to update my progress.

**Comment by GriffGreen** [comment]
https://eips.ethereum.org/EIPS/eip-712

**Comment by GriffGreen** [comment]
opening a chat in keybase

**Comment by GriffGreen** [comment]
error handling is probably a better solution... will request more information from Jeremy

**Comment by GriffGreen** [comment]
will be fixed with #607

**Comment by GriffGreen** [comment]
Almost done, should be fixed by #658
