### ISSUE TITLE
New User: Vocdoni add to Whitelist

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#612]
New campaign forthcoming for Vocdoni requested by Matthew Carano of Swarm City for user @d3n on Riot, see request in new room Vocdoni Grant Support https://riot.im/app/#/room/!pWSwVBpSipekDjxDfV:matrix.org.

Please add the following address to 'Project Owner' whitelist:
0x47fCD86C2a8A02af00CADF8660Ca1896AA4FE238

**Comment by perissology** [comment]
done
