### ISSUE TITLE
Donation lists don't include info about the delegate only the donor

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#613]
When money comes in to a campaign or a milestone... it is often delegated.... but the display we have now is just showing the donor...

<img width="956" alt="screen shot 2019-01-11 at 10 29 56 pm" src="https://user-images.githubusercontent.com/14945613/51060590-84736480-15f0-11e9-8b7a-58e6374989c3.png">

It would be nice if the donation would show where the money came from, i would imagine a column labeled: `Origin` (or `From` or `Source` or  man i dont know `delegating organization` damn naming is hard) that would have these items in it:

Direct donation
Governance Campaign
Unicorn DAC

So that way someone could see who actually decided to send money there and the donor that originally gave the money... I think we can change the `Name` column to `Giver` and but this clumn between the `giver` and `address` column

Bonus
If we ever want to be really cool and show more providence, we could add `via` here to add more detail... like if the Giveth DAC delegated to the Comms campaign which sent funds to a milestone, in the `Origin` column it could say:
Communication Campaign via Giveth DAC

And bonus future proofing/paranoia... we might want to think about what will happen in the next upgrade when milestones can send donations to Campaigns ... for example:

Maker DAO puts a bounty with the dapp on token integration, that donation then gets paid out just to the DApp Campaign, then the DApp Campaign pays RJ for solving an issue, will the database in the background understand what to display in RJ's Milestone. 

I would expect it would say the donor was MakerDAO and the `Origin` is the DApp Campaign... but maybe that could get screwed up... 

Even worse what if makerDAO's donation originated from the Giveth DAC...? or what if RJ's milestone then sent the makerdaos donation to the Unicorn DAC and then that went to a different milestone which was sending to the gov campaign etc etc...

**Comment by GriffGreen** [comment]
RJ said it was listed in feathers somehwhere

**Comment by ElMejorge** [comment]
@ewingrj Do you know if this value is being returned from the Feathers Server?

**Comment by ewingrj** [comment]
each donation has a `giverAddress` field which was the original giver.

There is also the `parentDonations` field which you can use to build the donation path. You would need to write some code in feathers to handle this

**Comment by aminlatifi** [comment]
What I have implemented till now. I like to know other guys' idea.
![image](https://user-images.githubusercontent.com/5684607/65143677-d5aee000-da2a-11e9-94de-3254a0447b65.png)

**Comment by aminlatifi** [comment]
I have implemented this till now. 
![image](https://user-images.githubusercontent.com/5684607/65173149-7caf6e00-da63-11e9-847a-b408c6e78005.png)

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/65173559-4b836d80-da64-11e9-9365-df188744798e.png)

**Comment by arbreton** [comment]
Looks amazing amin!!, excited to see this one implemented! 👍 !

**Comment by aminlatifi** [comment]
@GriffGreen has a great idea of showing each parent donation share of donation amount. Like this: `09/15/2019 0.001 ETH donated to Campaign 10 (.0005 ETH delegated to this milestone)` 
Currently we cannot deduce this information with simple trace of data. So we need another collection in mongo to keep track of share. This collection can contain a good snapshot of donation events. @arbreton  once shared this idea with me too.

**Comment by aminlatifi** [comment]
I decided to close this issue because feature is implemented. I create another issue to address donation share in history.

**Comment by GriffGreen** [comment]
thx amin!
