### ISSUE TITLE
Link from Notification email does not open the Dapp

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#616]
When I receive an email notification and click the link to take action, it recognizes my user account and goes to the correct page, but does not actually open it - I get a blank page.  The green dot never shows up and refreshing does not load it either.

![image](https://user-images.githubusercontent.com/39466970/51063902-0e103b80-15cb-11e9-8de1-3c0e9cf64e98.png)

**Comment by GriffGreen** [comment]
https://beta.giveth.io/my-delegations its not the email link.... that page isnt loading correctly

Also we should add a second issue to make notifications have smarter links

**Comment by perissology** [comment]
fixed in https://github.com/Giveth/feathers-giveth/commit/d1bc8f3bf2e7dfb051e09f803d2e6fb5138b4ade

**Comment by GriffGreen** [comment]
trust
