### ISSUE TITLE
Release 2019-01-11 bugs

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#618]
This is to transparently collect all the bugs in the next 2019-01-11 release. Please follow the [release precedure](https://docs.google.com/forms/d/e/1FAIpQLSeY-9mwXUpdkiHorjDfqay0Z4aYSjn0BnvaZZ00OJ8-1EqqfQ/viewform?usp=sf_link), all tests are to be made on [release.giveth.io](release.giveth.io).

## Testing guidelines
To test the tokens you will need to request MiniME token from @vojtechsimetka (@vojtech:matrix.org) and add the token to your MetaMask account manually:
**Token Address**: `0xE690E380740a682E2b8CEAEa33584Ea2cb59849E`

### New features
- **Milestone actions** - You can now do all the operation for a given milestone directly in the milestone itself. Gone are the times when you needed to go to manag -> my milestones!!!!

### Test especially
- Delegations
- Milestone flow (especially tokenized milestones and proposing milestones)
- Wallet actions
- Getting paid :)

**Comment by geleeroyale** [comment]
I think the 'Cancel' function should be only available at milestone overview - at least in my experience it is a rarely used (and quite dangerous) function.

**Comment by geleeroyale** [comment]
**BUG** - this milestone shows `collect`, but does not follow through (I get empty tx and nothing happens, except OH-OH error)

https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c24ac05bf3e293e567c358b
