### ISSUE TITLE
Email Notification of Donation does not match Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#619]
Magenta received an email that says Bloom Network received a donation as shown below.  The donation does not appear in the [Campaign](https://beta.giveth.io/campaigns/5bd31756e411be3e787d0f68).

![image](https://user-images.githubusercontent.com/39466970/51064462-c50db680-15cd-11e9-8156-0de9f06209cc.png)

**Comment by perissology** [comment]
that donation was for 0.0000000044. We only show 2 decimals, so it shows up as 0

**Comment by perissology** [comment]
donations are now sorted by value, so maybe you missed it at the bottom
