### ISSUE TITLE
Make it more clear when form fields are valid or invalid

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#62]
Currently, it is not obvious whether the input fields are valid or not. There is some text below them at all times and it does not change colour or anything. Also the save button is always active.

**Comment by satyavh** [comment]
`Also the save button is always active.`
@vsimetka Please turn that into a separate story with a reproduction scenario as the save button is disabled by default unless required form fields are filled out. It is also not clear which form(s) you are referring too.

**Comment by vsimetka** [comment]
Works in develop as of 2017-11-21.
