### ISSUE TITLE
Funds didn't come fully

### ISSUE THREAD

**Issue by MaxSemenchuk** [Giveth/giveth-dapp#622]
On this payout https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c07d0768b83251b841a6a6d

Requested: 35 ETH

Incomes:
* 6.5 ETH https://etherscan.io/tx/0xa74070f53bdbc072706d1e24673adfcf91c3ccea063aff7fb36b9b0603d4bce7
* 14.1 ETH to https://etherscan.io/address/0xe69394fcf8260f3e3702166a470d89f3db3d1d9a#internaltx 

Missing 10 ETH, can you help to figure this out?

**Comment by perissology** [comment]
You're actually missing 20.839693 from that milestone (notice the donation does not say paid).

The 6.5 ETH looks like a manual transfer from griff and is not related to the dapp.

When you paid out that milestone, there was a bug #561. The recipient should see a disburse button on that milestone when he visits beta.giveth.io/my-milestones. If that button is clicked, the rest of the funds should be withdrawn.

Let me know if that button is not available.

Sorry about the inconvenience.

**Comment by MaxSemenchuk** [comment]
Hi @perissology thank for the support.

I saw 20.8 wasn't paid, but wasn't sure what is meant by committed. Should we ask them to click something?

here's what I see beta.giveth.io/my-milestones, should it be like that?
![screenshot-github com-2019 01 15-17-05-35](https://user-images.githubusercontent.com/11428528/51189027-ce599480-18e7-11e9-947a-9a5f192fbe31.png)

**Comment by perissology** [comment]
Yes, ask him to go to my-milestones page and click "collect" button next to that milestone

**Comment by mroberts10** [comment]
Are we able to close this issue?

**Comment by MaxSemenchuk** [comment]
It seems that funds should come tomorrow, please let me check and i'll close or provide comments
