### ISSUE TITLE
Bug - i'm prompted to delegate a delegation that has just been made to a milestone

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#624]
After I made these delegations this week, the "My Delegations" page on the DApp as well as emails prompted me to delegate "a new donation":
<img width="870" alt="screen shot 2019-01-15 at 8 52 35 pm" src="https://user-images.githubusercontent.com/38163206/51242072-acc4df80-19b1-11e9-94da-7a53322a0d7e.png">
And it even carries me as far as this pop up when I click delegate: 
<img width="991" alt="screen shot 2019-01-15 at 8 53 04 pm" src="https://user-images.githubusercontent.com/38163206/51242107-c0704600-19b1-11e9-8182-fa8f8bfad709.png">

Haven't actually gone thru with it to see if it does anything 😅
And I was sent emails asking me to delegate a bunch of these:
<img width="793" alt="screen shot 2019-01-16 at 2 14 03 pm" src="https://user-images.githubusercontent.com/38163206/51242158-e1d13200-19b1-11e9-81ae-5c0c903f9810.png">

It's as if it thinks the Milestone is the Unicorn DAC itself

**Comment by perissology** [comment]
Is this still an issue? I can't seem to reproduce

**Comment by perissology** [comment]
no longer an issue according to loie
