### ISSUE TITLE
RewardDAO campaign delegations failing

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#627]
Some worked!  Some didn't :(

Frederiks showed the delegation, he confirmed.. then, it disappeared.  I just redelegated to the milestone and received a 'success' message, but it's hanging:  
https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5c3403f146d9c67925653d14

**Comment by Danibelle** [comment]
This one is hung up as well:  https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5c34229746d9c67925653d4b

![image](https://user-images.githubusercontent.com/39466970/51338698-8908a480-1a58-11e9-949c-2e870ff6ac92.png)

**Comment by FrederikBolding** [comment]
Happened to this one as well: https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c35204746d9c67925654088

**Comment by perissology** [comment]
okay, these should be sorted out now. There were some node issues today :(
