### ISSUE TITLE
Can't do any actions in the dapp?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#628]
<img width="946" alt="screen shot 2019-01-17 at 9 27 30 pm" src="https://user-images.githubusercontent.com/14945613/51346833-de67a480-1a9e-11e9-8890-9dc4d9ee852e.png">

Getting the spinning sign of death on all actions...

**Comment by perissology** [comment]
should be fixed now. There were some node issues today :(
