### ISSUE TITLE
Delegations that failed still appear to count on Milestone

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#629]
Maybe this isn't a big deal and I'll learn how to trace transactions through this issue, but I had several delegations fail on the RewardDAO campaign while the node was on it's way down 1/16-17th ish.

Now these milestones say they had 2 and 3 donations made:
![image](https://user-images.githubusercontent.com/39466970/51393410-a34c8c00-1b05-11e9-954b-9a9578560080.png)

But only 1 shows up in the Milestone record itself:
![image](https://user-images.githubusercontent.com/39466970/51393461-c1b28780-1b05-11e9-91ef-9d9db22c924f.png)

And I don't actually know how to check and see whether the funds were only taken out once. :\

**Comment by perissology** [comment]
this should be fixed
