### ISSUE TITLE
Autofilling milestones

### ISSUE THREAD

**Issue by FrederikBolding** [Giveth/giveth-dapp#631]
It would be great to be able to embed milestone information in the URL, meaning that a certain link would autofill certain fields when creating a milestone.

I talked to @Danibelle about using this for RewardDAO, but it could probably be useful for other things as well.

**Comment by FrederikBolding** [comment]
I might have time to look at this - I'll get back to this thread when I've looked at it a bit.

**Comment by vojtechsimetka** [comment]
Talked to @FrederikBolding about this.

Basically all that needs to be done is in the src/components/views/editmilestone . You would get the parameters from URL and if this is new milestone set it to the Model in loadMilestone function. Parameters that make sense from the top of my head are title, recipient, reviewer, description, date, amount, token, fiatAmount & fiatType or amount in crypto.

**Comment by FrederikBolding** [comment]
I've started work on it here: https://github.com/FrederikBolding/giveth-dapp/tree/autofilling-milestones
