### ISSUE TITLE
Can't Access my-milestones :-( big number error

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#633]
<img width="1190" alt="screen shot 2019-01-19 at 6 48 25 am" src="https://user-images.githubusercontent.com/14945613/51422836-5379cd80-1bb6-11e9-989c-2ca1e4255725.png">

**Comment by GriffGreen** [comment]
this is with account 0x567355f84d44a982629D8675AB4aadBB92dbfD54 but it works with my other account

**Comment by perissology** [comment]
fixed in 7598b3f5955105a43364dc02b9d771a088294c01
