### ISSUE TITLE
Delegations and Financial overview don't match up

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#634]
Auditing the Aragon DAC's R&D campaign and I dont know which view is correct either one of these delegations is not real 
<img width="1129" alt="screen shot 2019-01-19 at 7 19 48 am" src="https://user-images.githubusercontent.com/14945613/51423125-f7657800-1bba-11e9-8ecb-02ebc9fc6313.png">

Or this overview at the bottom of the R&D Campaign is missing something 
<img width="1107" alt="screen shot 2019-01-19 at 7 20 50 am" src="https://user-images.githubusercontent.com/14945613/51423135-2845ad00-1bbb-11e9-801a-5e7b5c3817b6.png">

I assume the problem is the 1094.85 delegation as that is the difference between the two numbers

**Comment by GriffGreen** [comment]
Yeah some how that 1093.85 pledge isnt being counted in the overview... i donated 1 DAI and the overview didnt change

**Comment by perissology** [comment]
I'm pretty sure this would have been fixed in https://github.com/Giveth/feathers-giveth/commit/db6e5eb2337561d36cc89c6a8c2b8496d7be48cb

**Comment by GriffGreen** [comment]
not sure how to check, but i'll give you the benefit of the doubt
