### ISSUE TITLE
Typos & capitalization

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#635]
When editing a Milestone you get the below. 
Space is missing between the words plus Milestone should be capitalized 

![image](https://user-images.githubusercontent.com/6533925/51425196-22f75b00-1bd9-11e9-873f-6954a097a903.png)

All the below is about capitalization of the word 'Milestone'. Communities/DACs, Campaigns and Milestones are our key building blocks of the DApp, and to make clear to people when we use them in this context we always capitalize them. This has been decided at some point (before my time) so this is how we talk about it on the wiki & in medium posts - we should be consistent about it in the DApp as well.

When hitting submit or propose a new Milestone, the capital in the title is also missing: 

![image](https://user-images.githubusercontent.com/6533925/51425238-96996800-1bd9-11e9-891f-98d0b48a33cf.png)

Under 'My Milestones', same things, should be capitalized: 

![image](https://user-images.githubusercontent.com/6533925/51425308-8cc43480-1bda-11e9-8375-0babf6808d7b.png)

When approving a Milestone x3: 

![image](https://user-images.githubusercontent.com/6533925/51675559-4d2f8b00-1fd4-11e9-8969-306a4a5c0570.png)

When deleting a Milestone: 
![image](https://user-images.githubusercontent.com/6533925/51675892-4f461980-1fd5-11e9-8753-9d860610d186.png)

in each Milestone detail: 

![image](https://user-images.githubusercontent.com/6533925/51676095-e612d600-1fd5-11e9-87ad-fe616cbda3d5.png)

Text above completed Milestone: 
![image](https://user-images.githubusercontent.com/6533925/51676229-502b7b00-1fd6-11e9-89e0-867f29294af6.png)

**Comment by bowensanders** [comment]
I might be able to tackle most of these myself if we have a comprehensive list of where they occur
