### ISSUE TITLE
Milestone from June just popped up here? 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#636]
Seems to be paid before, what is this? 

![image](https://user-images.githubusercontent.com/6533925/51425405-19bbbd80-1bdc-11e9-9b65-ca7b1bdcd6bc.png)

In the Milestone I see this description? Which I did not put there. 
If other people can just create Milestones in my name and from my account, is this - apart from being incorrect - not also quite a vulnerability?

![image](https://user-images.githubusercontent.com/6533925/51425412-2c35f700-1bdc-11e9-88ab-676b3e55ea16.png)

**Comment by vojtechsimetka** [comment]
Can we get the link to the milestone? There must have been an error where the cache service did not manage to match this with an existing milestone.

**Comment by vojtechsimetka** [comment]
@krrisis @perissology This could have been erased from the DB on accident. Maybe we can ask reviewer to cancel it and that would solve it?

**Comment by krrisis** [comment]
Can cancel it myself as well I see? If that doesn't work I can ask kay who's the reviewer, whatever you guys want, just wanted to flag this mysterious reappearance :)

**Comment by vojtechsimetka** [comment]
Oh right I forgot RJ added that functionality. I'm not sure if he had to modify the smart contracts for that. @perissology can @krrisis cancel it himself?

**Comment by krrisis** [comment]
reopening (sorry M :) ) until I know what I should do with this one.

**Comment by ewingrj** [comment]
not that hard, just cancel.

duplicate of #646
