### ISSUE TITLE
Viewing milestone causes error

### ISSUE THREAD

**Issue by cjyabraham** [Giveth/giveth-dapp#638]
When I try to go to [my milestone](https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c401c01d84361151fdd631a) I get [an error](https://pastebin.com/rf8Eqyyy).

**Comment by lorelei1** [comment]
Yup, also experiencing a lot of milestones buggin out. Can't find the pattern yet. 
https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5c3426c146d9c67925653d4f
https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5c42c38854c4dd181cdb2903
https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5c4835658a6a785b61462b1f
and
https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5c4835478a6a785b61462b1c
so far.

**Comment by perissology** [comment]
fixed in 2c2fe6fbe5a844f98795e37298b413b7d31e041d

**Comment by GriffGreen** [comment]
Nice! Can this be a hot fix?

**Comment by vojtechsimetka** [comment]
@GriffGreen already is. RJ already did all the work.
