### ISSUE TITLE
Accepted milestones appear twice in My Milestones

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#639]
![screen shot 2019-01-23 at 4 39 45 pm](https://user-images.githubusercontent.com/38163206/51597332-8eb92b00-1f2d-11e9-9b48-3c4caedce570.png)
![screen shot 2019-01-23 at 4 51 24 pm](https://user-images.githubusercontent.com/38163206/51597986-266b4900-1f2f-11e9-8634-932eb63d558f.png)

After I accepted Dani and Kris's milestones, they appear anew in "My Milestones" marked as being created on the date that I accepted them. I also still have the button to accept or reject them below. This happened when I accepted Dani's from the My Milestones page and accepted Kris's from within the Milestone. Result was the same! And they error out when I click on them at the top there. 
![screen shot 2019-01-23 at 4 43 23 pm](https://user-images.githubusercontent.com/38163206/51597523-04bd9200-1f2e-11e9-9d7a-89aef96c3a7d.png)
I also still have the buttons for accept and reject within the milestone after confirming the tx to accept it. 
![screen shot 2019-01-23 at 4 53 41 pm](https://user-images.githubusercontent.com/38163206/51598179-88c44980-1f2f-11e9-85c8-36845e5c4d4f.png)

**Comment by perissology** [comment]
fixed in 55f3f2c9c7e04325b20d13f40164f4e72d37869b
