### ISSUE TITLE
A milestone has an unknown milestone manager??? 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#641]
https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c401c01d84361151fdd631a
It says chris proposed it, but when you click his name, it says he is unknown.

<img width="831" alt="screen shot 2019-01-23 at 5 20 16 pm" src="https://user-images.githubusercontent.com/14945613/51620710-3c7b0880-1f33-11e9-8694-674950e99001.png">

**Comment by perissology** [comment]
fixed in 794b7218de27446a7080ffaa26922b3cba527398
