### ISSUE TITLE
Rejected Milestone has a cancel button? 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#643]
See below, a Milestone for which I am the reviewer (not Manager) and that I rejected, after rejection it has a cancel button? 
Milestone; https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5c34113746d9c67925653d2e 

![image](https://user-images.githubusercontent.com/6533925/51676332-97b20700-1fd6-11e9-9290-0aed01899edd.png)

**Comment by perissology** [comment]
the manager & reviewer can cancel a milestone. When it's rejected, it is still active
