### ISSUE TITLE
Weird milestones in a couple campaigns

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#646]
<img width="936" alt="screen shot 2019-01-26 at 10 28 01 am" src="https://user-images.githubusercontent.com/14945613/51785460-58abbf00-2158-11e9-9621-ede001f6a8d2.png">
<img width="969" alt="screen shot 2019-01-26 at 10 27 29 am" src="https://user-images.githubusercontent.com/14945613/51785461-58abbf00-2158-11e9-8863-6ffc579d22ac.png">
This is in the Comms campaign and in Social coding... not sure if this is a bug or what happened... but i doubt these were really added outside the UI...

Quaiza has milestones like this in the Dev campaign as well... but i dont know if they were added inside the UI or not.

**Comment by vojtechsimetka** [comment]
This is interesting. Linked to https://github.com/Giveth/giveth-dapp/issues/636 . We should check if those are duplicates or if they started to pop up now @ewingrj

**Comment by ewingrj** [comment]
Yes, same a #636. I fixed a bug in feathers where the events for these milestones were not processing.  I'm not sure why these milestones were created, but they definitely exist on the blockchain as separate contracts/milestones.

I suspect a UI bug caused the campaign owner to accept a proposed milestone multiple times.

These milestones will need to be canceled.

There are 8 in total:

https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c3f7a934af9e97812c97496
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c3f7e094af9e97812c97f2a
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c3f7ebb4af9e97812c981c0
https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c3f80904af9e97812c987e1
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f83b84af9e97812c9911b
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f81764af9e97812c98a4c
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f83bd4af9e97812c9911e
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f842d4af9e97812c9929c

**Comment by lorelei1** [comment]
it's happening to me too! 
<img width="1130" alt="screen shot 2019-02-04 at 12 45 10 pm" src="https://user-images.githubusercontent.com/38163206/52206633-192d5300-287b-11e9-990e-7fa6265583ff.png">

JSYK when I was creating this milestone it was quite buggy too, idk if related but I made this issue about it: https://github.com/Giveth/giveth-dapp/issues/660

**Comment by GriffGreen** [comment]
@bowensanders and many other campaign managers need to close these issues

https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c3f7a934af9e97812c97496
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c3f7e094af9e97812c97f2a
https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c3f7ebb4af9e97812c981c0
https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c3f80904af9e97812c987e1
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f83b84af9e97812c9911b
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f81764af9e97812c98a4c
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f83bd4af9e97812c9911e
https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f842d4af9e97812c9929c

Click each link and see who needs to close it

**Comment by bowensanders** [comment]
I was unable to cancel the two milestones for Social Coding - but i did mark them complete with 0 donations stating that they were faulty / dead. The cancel button greyed out and I couldn't select it.



I cannot do anything about Quazia's aragon milestones.



Please let me know if I need to do anything further!



-b


---- On Mon, 10 Jun 2019 10:28:26 -0700 Griff Green <mailto:notifications@github.com> wrote ----



https://github.com/bowensanders and many other campaign managers need to close these issues

https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c3f7a934af9e97812c97496
 https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c3f7e094af9e97812c97f2a
 https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c3f7ebb4af9e97812c981c0
 https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c3f80904af9e97812c987e1
 https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f83b84af9e97812c9911b
 https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f81764af9e97812c98a4c
 https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f83bd4af9e97812c9911e
 https://beta.giveth.io/campaigns/5b6cb8da11875f2dc87ff150/milestones/5c3f842d4af9e97812c9929c
Click each link and see who needs to close it

**Comment by arbreton** [comment]
All milestones closed
