### ISSUE TITLE
Updating proposed milestone fails

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#650]
When updating milestone that is proposed, the action fails with incorrect exchange rate.

<img width="722" alt="screen shot 2019-01-27 at 16 43 36" src="https://user-images.githubusercontent.com/7974813/51805973-cf2ce780-2252-11e9-919f-30e9853ad9d2.png">

**Comment by vojtechsimetka** [comment]
The milestone must still be in proposed state. Once approved, editing works.

**Comment by ewingrj** [comment]
I couldn't reproduce. Was this on develop? I did fix some other propose/reject milestone bugs in 844011927eeb1aa3e6ae5b4231f6f664cdf9eb3c

**Comment by vojtechsimetka** [comment]
No this was on beta. And it was a milestone with expenses so I think that is causing the issue.

**Comment by ewingrj** [comment]
I'm not able to reproduce this in develop env

**Comment by vojtechsimetka** [comment]
Works in develop

https://develop.giveth.io/campaigns/5c545bd1ae70d16188cd042b/milestones/5c545ceaae70d16188cd0432
