### ISSUE TITLE
My delegations error - amount appears the same after delegating part of it away

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#653]
Before I started the delegations this week, i noticed kris's DAI delegation was STILL spinning from last week! 

<img width="821" alt="screen shot 2019-01-30 at 6 21 07 am" src="https://user-images.githubusercontent.com/38163206/51961528-52ba2480-245d-11e9-8fae-05a741b1cc3e.png">

Then I delegated 150 to his own milestone, the spinner remained but the number changed to 450, and then it went right back to 600 and the spinner stopped. 

<img width="852" alt="screen shot 2019-01-30 at 6 25 11 am" src="https://user-images.githubusercontent.com/38163206/51961571-78472e00-245d-11e9-96b6-b1abf29b4150.png">

I continued to delegate from this donation of his and at the end after i had delegated the whole 600 away, it still never accounted for the 150. 
<img width="929" alt="screen shot 2019-01-30 at 7 06 47 am" src="https://user-images.githubusercontent.com/38163206/51961626-a298eb80-245d-11e9-91d4-e369c6aaeeeb.png">

Even tho in the milestone it appears: 

<img width="725" alt="screen shot 2019-01-30 at 7 07 53 am" src="https://user-images.githubusercontent.com/38163206/51961671-d116c680-245d-11e9-91a0-a9f9bc595e21.png">

Another example: I delegated this whole donation down to the last cent of a DAI (huh, is there a name for small denominations like cents in any crypto?):

<img width="922" alt="screen shot 2019-01-30 at 6 36 27 am" src="https://user-images.githubusercontent.com/38163206/51961865-7b8ee980-245e-11e9-8eaa-2f44029c9747.png">

<img width="642" alt="screen shot 2019-01-30 at 6 36 39 am" src="https://user-images.githubusercontent.com/38163206/51961870-847fbb00-245e-11e9-876f-ae3a42e3482e.png">

And afterward, it looks the same in My Delegations! 

<img width="922" alt="screen shot 2019-01-30 at 6 36 27 am" src="https://user-images.githubusercontent.com/38163206/51961888-8fd2e680-245e-11e9-8c3a-18d5c36d3da8.png">

**Comment by lorelei1** [comment]
ok, by the time i finished making this issue the lanski one was sorted. but the kris one is still inaccurate.

**Comment by mroberts10** [comment]
Colleagues in Ukraine taking a look at this one.

**Comment by GriffGreen** [comment]
It might just be a lag of a few hours...

**Comment by GriffGreen** [comment]
It might not be an issue any more
