### ISSUE TITLE
Actions in Milestone don't require authentication

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#658]
It is possible to take Milestone actions even when the user is not signed in. This throws error in UI saying there was an error and the TX did not go through. This is however not the case, the TX is made correctly but feathers is not updated correctly. Once mined and confirmed the UI is upgraded correctly.

<img width="1400" alt="screen shot 2019-02-04 at 06 41 02" src="https://user-images.githubusercontent.com/7974813/52193594-d900ad00-2847-11e9-80db-bdc114cda3fd.png"> 

Can be quickly fixed by https://github.com/Giveth-One/giveth-dapp/issues/16 , though better solution would be to prompt sign in once the action is clicked

**Feathers:**
```
2019-02-04 06:34: info: error: milestones - Method: patch - Error
2019-02-04 06:34: error: Error {"type":"FeathersError","name":"NotAuthenticated","code":401,"className":"not-authenticated","errors":{},"timestamp":"2019-02-04T06:34:51.746Z"}
2019-02-04 06:34: info: newEvent called {
  "address": "0xF3e2bc6B7684Af91E1B96a76da2Df682E860Ad28",
  "blockNumber": 3808876,
  "transactionHash": "0x91568ac46f28beaa9b4ed2c227b2ee5aec20c99a5ae52f8ac69a9787b45df1cd",
  "transactionIndex": 14,
  "blockHash": "0xdbd4b67dc9feb8bd06e14320e6717dac6bc36ad50c59584c5ec96884c16896c6",
  "logIndex": 13,
  "removed": false,
  "id": "log_bdb837eb",
  "returnValues": {
    "0": "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "1": "932",
    "liquidPledging": "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "idProject": "932"
  },
  "event": "MilestoneCompleteRequestApproved",
  "signature": "0x75718956abfdac55bf1a7d4da565a985ea3a3e27d0fde1f05f1f86501890a75d",
  "raw": {
    "data": "0x",
    "topics": [
      "0x75718956abfdac55bf1a7d4da565a985ea3a3e27d0fde1f05f1f86501890a75d",
      "0x0000000000000000000000008eb047585abed935a73ba4b9525213f126a0c979",
      "0x00000000000000000000000000000000000000000000000000000000000003a4"
    ]
  }
} 
```

**Comment by GriffGreen** [comment]
grey out the buttons when they wont work.....

**Comment by GriffGreen** [comment]
its already implemented in my my_milestones

**Comment by GriffGreen** [comment]
Ask RJ about this... because there is a desire for DAOs to use frame and not have to sign in... to be able to skip sign in process and still push buttons ;-)

**Comment by GriffGreen** [comment]
relies on 731 to be finished

**Comment by GriffGreen** [comment]
relates to #731

**Comment by mroberts10** [comment]
Related to #731 needs a button like not now.
