### ISSUE TITLE
Creating/editing milestone does not show to which campaign.

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#66]
When creating or editing milestone, you don't know in which campaign it is being created.

**Comment by satyavh** [comment]
The only way to create / edit a milestone is within a campaign, and it says "Edit milestone" or "Add milestone". Imo should be quite straightforward.

But I will add the campaign name to the edit milestone form to make it more clear

**Comment by vsimetka** [comment]
Works in develop as of 2017-11-21.
