### ISSUE TITLE
Max amount when creating milestone is buggy

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#660]
Pretty sure this issue has been rehashed several times before.... but I can't find it now and also the scenario is a little different: 
I selected DAI in *all the places* BEFORE I ever put a number in... and it's still calculating the "Max Amount in DAI" as if it's ETH.  
<img width="918" alt="screen shot 2019-02-04 at 11 54 48 am" src="https://user-images.githubusercontent.com/38163206/52204868-aa99c680-2875-11e9-9783-586bd21ffc93.png">

Other times I had this problem when I put in the amount before changing the currency out of ETH, so I think it got confused because of the wrong order, but not this time.

**Comment by lorelei1** [comment]
Oh! I figured out how to fix it! 
NOT! Lol. 
<img width="830" alt="screen shot 2019-02-04 at 12 13 11 pm" src="https://user-images.githubusercontent.com/38163206/52205165-783c9900-2876-11e9-8304-1cda8679f8a5.png">

1 DAI=1 ETH uhhhhhh

**Comment by vojtechsimetka** [comment]
Yeah this is a bug and rather dangerous one. Also encountered this issues with exchange rates and there is a fix RJ is going to merge from the Giveth.One repo - https://github.com/Giveth-One/giveth-dapp/commit/8e31c0e218f19da86c9a0bb45452cb6265e5f2db#diff-2fd7757f4dffb4f8bf4c2298f93e5048R15.

**Comment by ewingrj** [comment]
should be fixed in 141699d74c84d877a92c3399b940feb65a60e356

**Comment by lorelei1** [comment]
Well I'm happy to find the issue #646 part of my problem is fixed... but I've still got this DAI conversion bug going on in this milestone. 
<img width="915" alt="screen shot 2019-02-13 at 2 08 37 pm" src="https://user-images.githubusercontent.com/38163206/52744307-918dc580-2f99-11e9-8021-17d463238b48.png">

**Comment by lorelei1** [comment]
@ewingrj idk if the fix you are talking about is just in the new release, or is in beta... can you help me understand if I just need to remake this milestone all together? I'll probs do that if I don't hear back from you, it's not a big deal to do.

**Comment by lorelei1** [comment]
ack! which one do I donate to? I'm guessing this double is related to the same bug because I had to create this milestone in eth because DAI conversion was broken in the way described above. And now that @krrisis decided to fund this milestone thru the Unicorn DAC, I need to know where to delegate the donation!  
<img width="965" alt="screen shot 2019-02-13 at 4 08 12 pm" src="https://user-images.githubusercontent.com/38163206/52750676-2a2c4180-2faa-11e9-9cf4-72d1b9f67bd7.png">

**Comment by ewingrj** [comment]
> @ewingrj idk if the fix you are talking about is just in the new release, or is in beta... if it's a fix from here on out, or if it's a fix that corrects the currently buggy milestones. can you help me understand if I just need to remake this milestone all together? I'll probs do that if I don't hear back from you, it's not a big deal to do.

You're going to have to cancel & re-create that milestone. The ui is displaying what the contract shows

**Comment by ewingrj** [comment]
regarding the duplicate milestones...

It looks like it was created 2x. Here are the corresponding txs. Notice the data is exactly the same.

https://rinkeby.etherscan.io/tx/0x45d9f470dce277b131821a3f7dac6eeeae5ca9cb62905f74b056725b0ae4a617
https://rinkeby.etherscan.io/tx/0xdba949aea81662e57f72ba803d0e0c9ef3c34cedb5a02fc37d879380e034dfc4

and milestones:
https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c5d97bf9f1aab32c2690b80
https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c5dfaad9f1aab32c2690bbf

I would cancel the one that say missing description.

Now why did that happen???

It looks like they were deployed by @krrisis. So @krrisis do you remember if there was anything strange in the ui that happened when you accepted this milestone from loei? Any error messages, etc?

**Comment by krrisis** [comment]
Nope, nothing strange that I recall.. I did notice it afterward that there were two and that it looked the same as what I had in #636

**Comment by mroberts10** [comment]
@lorelei1 can you cancel the milestone. The bug has been fixed but previous milestone have to be cancelled.

**Comment by lorelei1** [comment]
Ok I canceled the ETH one (i already remade a dai one a bit ago) but FYI it seems to have fixed itself when RJ did the fix... it was actually raising the correct amount of ETH after all that.

**Comment by lorelei1** [comment]
and yeah as far as closing this issue... i myself don't make that many milestones so I don't have the greatest perspective on if the bug is happening still. but everybody seems to be asking me a lot about this one haha. so my two cents is i don't have proof that it's not fixed... so close it? 😝
