### ISSUE TITLE
Milestone completion email says "Ether", regardless of whether Ether or Dai is involved

### ISSUE THREAD

**Issue by gentlemandonadams** [Giveth/giveth-dapp#662]
A milestone I was involved in was recently confirmed as complete.  The milestone was denominated in Dai, but when I received the email confirming that the milestone had been completed, the text of the email invited me to collect my "Ether".  Not sure if we want to go with a token-neutral wording or specify which type of token the recipient will be collecting, but either way we can't be calling Dai "Ether".

**Comment by bowensanders** [comment]
The idea I discussed with RJ at ETHDenver about this was to have it say "ETH" or "DAI" - or in a circumstance that it is mixed-token, just leave off the moniker so it just says "Time to collect.

**Comment by bowensanders** [comment]
Problems can be addressed here: https://github.com/Giveth/feathers-giveth/blob/develop/src/utils/dappMailer.js

**Comment by bowensanders** [comment]
Could we consider changing "Ether" to "Funds" in order to simplify the fix and make the changes that would show ETH / DAI / Other as a feature request?

**Comment by gentlemandonadams** [comment]
I like "funds"!  Just my 2 wei

**Comment by GriffGreen** [comment]
@Danibelle what happens when its multiple tokens? :-D
