### ISSUE TITLE
Went to make a small text edit of a milestone and i get an error

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#663]
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c41ef8754c4dd181cdb2893/edit

Either i don't have the permissions to edit this.. (I'm the campaign manager and reviewer is there a conflict there?)

Or there is a more general bug... I'm using the brave browser. 

<img width="1191" alt="screen shot 2019-02-07 at 11 35 57 am" src="https://user-images.githubusercontent.com/14945613/52405904-bdf29f00-2acc-11e9-9cb2-8ebcfd9d8adc.png">

**Comment by ewingrj** [comment]
duplicate of #665. Should be fixed now
