### ISSUE TITLE
Conflicting Milestone Approval msgs

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#668]
First when I clicked approve milestone (signed the metamask tx too) the DApp gave me this message: 
<img width="854" alt="screen shot 2019-02-11 at 11 01 59 am" src="https://user-images.githubusercontent.com/38163206/52583412-bdb81380-2dec-11e9-8da5-d1d5e3566c27.png">

And then before I had time to fully try again, it gave me a green "Milestone Approved" banner.

**Comment by mroberts10** [comment]
Great opportunity to improve our error handling... Would be a solid way to learn how the dapp works for a new dev

**Comment by GriffGreen** [comment]
Will be solved by #607

**Comment by GriffGreen** [comment]
very weird bug... we need more details is it still an issue? probably but i don't think we can do it.

**Comment by arbreton** [comment]
this is going to be fixed on #607 which includes a more complete refactor
