### ISSUE TITLE
Campaign has milestones in DAI and ETH; Donate button only gives ETH option

### ISSUE THREAD

**Issue by gentlemandonadams** [Giveth/giveth-dapp#669]
I clicked the Donate button for the GRACEaid campaign (https://beta.giveth.io/campaigns/5c4794dd8a6a785b61462b0f)

Although this campaign has Milestones associated with it that are denominated in both ETH and DAI, the donate button took me to a page where I was given the option to donate in ETH but no DAI option.  Seems I should be given a choice between the two rather than just ETH.

**Comment by krrisis** [comment]
hey adam, are you connected to mainnet when you do this? then you should see this option!

**Comment by gentlemandonadams** [comment]
You're right, I see that now
