### ISSUE TITLE
Is there now a second Metamask tx to delegate to milestones?

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#670]
Some very fishy things are happening when delegating to Milestones. I get prompted *twice* to sign a metamask transaction. 
The first time it happened I was surprised by a second metamask tx after I had already completed the process: 
<img width="814" alt="screen shot 2019-02-11 at 8 23 22 pm" src="https://user-images.githubusercontent.com/38163206/52611386-955b0400-2e42-11e9-9473-1a8c249c05e0.png">

And then the following, on a whole different milestone:
Here's a shot of after I signed the transaction once, it appears to have gone thru because the DApp gave me this nice pop up window indicating success, and yet here another unsigned metamask tx has showed up...
<img width="765" alt="screen shot 2019-02-11 at 8 52 08 pm" src="https://user-images.githubusercontent.com/38163206/52611289-136adb00-2e42-11e9-9511-7e5ecb328aef.png">
Here you can see again, the success with now the green banner, aaand a new tx waiting to be signed.
<img width="1440" alt="screen shot 2019-02-11 at 8 52 12 pm" src="https://user-images.githubusercontent.com/38163206/52611410-b7ed1d00-2e42-11e9-886b-d6e5cd16f9a2.png">

I rejected it, and then saw this:
<img width="914" alt="screen shot 2019-02-11 at 9 02 54 pm" src="https://user-images.githubusercontent.com/38163206/52611439-d3582800-2e42-11e9-9e7c-7d061569efa8.png">

But when i see the "My Delegations" page, the correct amount has been taken out of Kris's total,
<img width="889" alt="screen shot 2019-02-11 at 9 34 31 pm" src="https://user-images.githubusercontent.com/38163206/52611946-01d70280-2e45-11e9-8886-52d9f2669ead.png">
 and the milestone itself has the "Proposed Delegation" listed in it's donations. 
<img width="789" alt="screen shot 2019-02-11 at 9 36 13 pm" src="https://user-images.githubusercontent.com/38163206/52611991-27fca280-2e45-11e9-82b1-74439cef4c9c.png">

**Comment by ewingrj** [comment]
I couldn't reproduce this locally

**Comment by GriffGreen** [comment]
Wait for it to happen again....

**Comment by lorelei1** [comment]
yeah i haven't experienced this again after that day that I made the issue.
