### ISSUE TITLE
Release 2019-02-12 bugs

### ISSUE THREAD

**Issue by ewingrj** [Giveth/giveth-dapp#671]
This is to transparently collect all the bugs in the next 2019-02-12 release. Please test the various milestone flows & configurations. All tests are to be made on [release.giveth.io](release.giveth.io).

## Testing guidelines
To test the tokens you will need to request MiniME token from @vojtechsimetka (@vojtech:matrix.org) and add the token to your MetaMask account manually:
**Token Address**: `0xE690E380740a682E2b8CEAEa33584Ea2cb59849E`

### New features
- **New Milestone Options** - Milestone are now much more configurable.

    - Optional Reviewer (for regular rewards)
    - Can set recipient after the milestone has been deployed
    - Optional funding cap
    - Can still receive funding after a milestone is completed
    - Accept multiple tokens

**Comment by GriffGreen** [comment]
<img width="114" alt="screen shot 2019-02-12 at 10 51 38 pm" src="https://user-images.githubusercontent.com/14945613/52670432-cdcd1180-2f18-11e9-83e5-9d49b696b306.png">
Is that true... can we send ANY token? or is it only ETH and DAI and any whitelisted token

**Comment by GriffGreen** [comment]
Small cosmetic thing
<img width="323" alt="screen shot 2019-02-12 at 10 58 47 pm" src="https://user-images.githubusercontent.com/14945613/52671284-f229ed80-2f1a-11e9-9471-70ef79ca72f2.png">
unless 2 tokens have been sent to the milestone... it should say Balance... I would say... just make it say Balance and let the grammar be wrong if there 2 balances there as that is the more unlikely use case

**Comment by ewingrj** [comment]
> Is that true... can we send ANY token? or is it only ETH and DAI and any whitelisted token

yes and no. The UI only supports the whitelisted tokens, as well as the bridge. But there are no token restrictions in the lp or milestone contracts

**Comment by Danibelle** [comment]
feedback from Joshua in this [issue #693](https://github.com/Giveth/giveth-dapp/issues/693) he created.
