### ISSUE TITLE
Bug with Committing delegations

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#672]
I already committed this delegation yesterday (with full success messages from the DApp), and then went back to my milestones page to find that it wants to be committed again... 
<img width="1014" alt="screen shot 2019-02-12 at 4 09 20 pm" src="https://user-images.githubusercontent.com/38163206/52674509-0cdf7080-2ee1-11e9-90b1-6122cebf12a1.png">

**Comment by ewingrj** [comment]
I couldn't reproduce this, and unfortunately it's probably too late for me to look at this specific case (lmk if this is still an issue).
