### ISSUE TITLE
Etherscan Links should always open in a new tab

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#673]
<img width="924" alt="screen shot 2019-02-13 at 2 27 29 pm" src="https://user-images.githubusercontent.com/14945613/52714996-9d7a8700-2f9b-11e9-904f-1fa4469c9961.png">

Clicked the address in D's profile and the etherscan opened inthe same tab taking me off the site... all etherscan links should go to a new tab

**Comment by lorelei1** [comment]
griff means they should open in a new tab, not a new window. change title bro! @GriffGreen

**Comment by GriffGreen** [comment]
Thank you @lorelei1 

Also... I have been noticing this is an issue everywhere in the dapp

might be a good gitcoin issue
