### ISSUE TITLE
this donation has been pending for a month

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#675]
I don't know why this is happening... I don't think @krrisis ever even got prompted to commit this donation after i delegated it for him...
<img width="841" alt="screen shot 2019-02-15 at 12 01 03 pm" src="https://user-images.githubusercontent.com/38163206/52878278-7944b480-3119-11e9-8efd-3b4265567ec3.png">

**Comment by lorelei1** [comment]
the spinner's still spinning

**Comment by lorelei1** [comment]
this one too https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5c45c89c54c4dd181cdb2a6b

**Comment by Danibelle** [comment]
Here's how it looks in My Donations - errors when I attempt to commit:
![image](https://user-images.githubusercontent.com/39466970/53101066-0c556400-34f7-11e9-8846-9ab5c762212f.png)

**Comment by krrisis** [comment]
Could we possibly prioritize this issue @ewingrj @mroberts10 ? 
I urgently need some funds to be able to pay my bills and the Unicorn DAC is already a delay in itself, the fact that funds have been 'hanging' for a weeks makes it more difficult/stressful. Thanks so much for your help. 

Milestones that currently have funds stuck that I have and for which Loie & Dani cannot commit: 

https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c5df8de9f1aab32c2690ba5
https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c5df9709f1aab32c2690baa
https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5c42fbdf54c4dd181cdb2931

**Comment by ewingrj** [comment]
this is fixed now. @Danibelle do you still have the above issue?

**Comment by krrisis** [comment]
Indeed fixed, thx RJ!
