### ISSUE TITLE
Unable to change my name in Profile

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#677]
When changing my name, or URL, the save profile button remains greyed out and clicking does not work.

<img width="228" alt="screen shot 2019-02-16 at 4 16 52 pm" src="https://user-images.githubusercontent.com/27023908/52906314-6a87fb80-3206-11e9-9b05-6f8b2e4ebeeb.png">

**Comment by GriffGreen** [comment]
this is a one off and we can leave this for if it becomes an issue for someone else
