### ISSUE TITLE
Right click Milestones to open in new tab 

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#679]
Unicorn DAC has me scanning the campaigns for milestones that meet funding prioritization criteria, and having to 'go back' to the full list every time I select one to review is a real pain as the lists get longer.

From the main page it would be AWESOME to right click on a DAC, Campaign, or Milestone and open several in new tabs.

**Comment by gil-air-may** [comment]
Hello
New contributor here 😃 Can I work on this one ?
