### ISSUE TITLE
Eth Amount in this Milestone does not match Exchange Rate

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#680]
https://giveth.github.io/xchange-rates/?v=873.78640777&t=1546279200&l=ETH&r=USD

 873 ETH is 900 USD?  Something does not look right on  [this milestone:](https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c114ac34a43c73a7ca14108)

**Comment by vojtechsimetka** [comment]
@GriffGreen cancel

**Comment by GriffGreen** [comment]
it was canceled...?

**Comment by vojtechsimetka** [comment]
No you should cancel it and recreate

**Comment by GriffGreen** [comment]
it looks like it was canceled on my side:
<img width="601" alt="screen shot 2019-02-22 at 4 52 09 pm" src="https://user-images.githubusercontent.com/14945613/53253748-3e66f180-36c2-11e9-998b-3edffe3f4aea.png">

**Comment by vojtechsimetka** [comment]
You are right
