### ISSUE TITLE
Milestone Canceled, Now What?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#681]
Andreas has canceled this [milestone] as the creator: (https://beta.giveth.io/campaigns/5bd7ad6cdb72b92a41002fc5/milestones/5bd8f88ddb72b92a41002ffe)

Dani has canceled the [campaign](https://beta.giveth.io/campaigns/5bd7ad6cdb72b92a41002fc5)

Dani had previously donated an ETH to the milestone directly, which shows in My Donations:
![image](https://user-images.githubusercontent.com/39466970/52960278-0f691c80-335e-11e9-9b34-9bd9b1cead10.png)

It appears to be stuck?  How do I get this Eth back so I can donate it to the new milestone that Andreas has re-created under the new, cleaner campaign structure for GRACEaid?

**Comment by Danibelle** [comment]
Cancelled all Andreas' previous campaigns (they've been recreated as milestones under a single GRACEaid Campaign now.  Here's how they still show up in My Campaigns (I am the Reviewer):
![image](https://user-images.githubusercontent.com/39466970/53304170-68462280-3840-11e9-8985-b27c32488d90.png)

I'd like to be walked through and learn how to check up on these donations and escort them through the process to appropriate resolution please :grin:

**Comment by ewingrj** [comment]
this donation should show up as refundable now. I think it will also show up on the delegations page as well
