### ISSUE TITLE
Milestone page doesn't alert user to switch metamask settings from mainnet to rinkeby

### ISSUE THREAD

**Issue by gentlemandonadams** [Giveth/giveth-dapp#683]
With metamask set to mainnet instead of rinkeby, I attempted to mark a Milestone complete from the Milestone page itself (https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c12c07538756672b224ebd9).  

When I tried to click the "mark complete" button, nothing happened (i.e. I wasn't prompted to change my settings in metamask to point to the rinkeby network.)

I experienced a similar lack of response a week or two ago when trying to disburse the funds from a completed milestone.  

This does not seem to be an issue on the My Milestones page, where the message does display; it's  only an issue on pages for individual Milestones.

**Comment by GriffGreen** [comment]
@gentlemandonadams !!! Thank you for making this issue!!! What browser are you using? We can't recreate this issue.

**Comment by gentlemandonadams** [comment]
Chrome on Mac (OS Mojave)
