### ISSUE TITLE
The "Collect" button does not work. 

### ISSUE THREAD

**Issue by mmohorko** [Giveth/giveth-dapp#685]
The button doesn't work and we can't collect the money from the closed milestone. Please help. Tnx.

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5c34c70746d9c6792565407e/milestones/5c34c99946d9c67925654081

**Comment by mroberts10** [comment]
@ewingrj can you take a look at this?

**Comment by mroberts10** [comment]
@mmohorko are you on mainnet or rinkeby?

**Comment by GriffGreen** [comment]
The same account is able to collect and disburse

**Comment by mmohorko** [comment]
I tried Rinkeby and the button worked now. We can close this issue.  Thank you for your help.
