### ISSUE TITLE
Weird donation hanging... accounting off in milestone?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#687]
<img width="880" alt="screen shot 2019-02-24 at 9 40 21 pm" src="https://user-images.githubusercontent.com/14945613/53305052-dc062080-387c-11e9-8959-fbf84e0db93a.png">
Not sure about the accounting for this milestone... something happened where both kay and I sent money to this milestone? But his is hanging? Maybe extra money went into the milestone?

https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c3729e846d9c679256544dd

**Comment by geleeroyale** [comment]
What happened was that Griff and I were donating at the same time (within seconds of each other) to this milestone. It might pay off to watch what happens down the line. My last action was to request a refund.

**Comment by ewingrj** [comment]
it looks like this got sorted out. the milestone looks correct now.

@geleeroyale fyi, when you request a refund, the tokens end up in your wallet on rinkeby and the ui doesn't support that right now. #591. You'll need to manually call lp or bridge contract to donate/withdraw
