### ISSUE TITLE
Vojtech's Handover

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#688]
I would like to slowly handover my responsibilities on the DApp to the remaining Giveth community. @GriffGreen suggested I create issue about it. Here is a list of things I have access to that I no longer wish to maintain and the latest I am willing to continue with the role:

- [x] Giveth DApp Overflow multisig (end of Feb) 0x16fda2fcc887dd7ac65c46be144473067cff8654
- [x] Giveth DApp EscapeHatch caller multisig (end of Feb) 0x1e9f6746147e937e8e1c29180e15af0bd5fd64bb
- [x] Giveth Multisig (end of Feb) 0x8f951903c9360345b4e1b536c7f5ae8f88a64e79
- [x] Giveth Rinkeby multisig (end of Feb) 0x20fc2ec2518dec7041b4c3e82663d6071bae953f
- [ ] Credit card on mLab (end of Feb)
- [x] Netlify team (10th of May)
- [x] Feathers access to beta & release + develop servers (10th of May)
- [ ] Github organisation administration (10th of May)
- [ ] mLab team administration (10th of May)

Please let me know how to best proceed.

**Comment by geleeroyale** [comment]
Thank you @vojtechsimetka for initiating this. I wanted to talk about permissions a while ago with you and never got around to do it, so I am very excited that you handle the handoff in this professional manner.

There is some stuff you can take off the list immediately, as I have the same permissions and can handle it for you - that is the general administration of  Netlify, Github, DNS, cloud VPS - for the VPS deployments themselves, we need to talk in detail how each is set up and make new admin accounts, I hope we can spend some time at your convenience on the operational handoff.

**Comment by vojtechsimetka** [comment]
Thanks @geleeroyale . I am happy to stay on the Netlify, Github and Feathers until May should there be any urgent issues. But I do not want to be on the multisigs as that brings much greater liability for me.

**Comment by GriffGreen** [comment]
i think i found another multisig on rinkeby... 0xc3b2128ca330871037d35fdc5f7b05e195aac5ce i can't really see who is on it

**Comment by arbreton** [comment]
is this still a wip? @geleeroyale, @bowensanders?, can we close this one?,

**Comment by vojtechsimetka** [comment]
It can be closed. I am still paying the DB and will do this month but I will ask @GriffGreen or someone else to take over.

**Comment by arbreton** [comment]
Thank you @vojtechsimetka, will move this issue to the closed section
