### ISSUE TITLE
Error on disbursing Milestone 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#694]
Getting the feared 'oh no' error, our BSOD on disbursing [this Milestone](https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c5df9709f1aab32c2690baa)

This is the one to which @Danibelle could not commit which @ewingrj fixed and now suddenly her committed amount in there is double, which has pushed my Milestone 350 DAI over the amount. Pretty sure this is the thing causing the error bcs the release that allows this is not live yet? How can this be fixed? Is this just the front end showing an error? 

edit: screenshot of the amount that got committed once but shows up double
![image](https://user-images.githubusercontent.com/6533925/53606408-0d535900-3bbb-11e9-83f1-7c11eb4644b2.png)

(Thx for hopefully urgent help bcs this is the Milestone to pay my aforementioned bills/taxes that are causing me stress)

**Comment by ewingrj** [comment]
should be resolved

**Comment by krrisis** [comment]
thx for the quick solution RJ

**Comment by lorelei1** [comment]
I think this bug has reinstated

**Comment by lorelei1** [comment]
This milestone https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5cd696e4362bdb014ef149d7
and this milestone
https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5cbf9e54cf48770f67ee85d6
are behaving exactly as kris described above! We can't disburse.

**Comment by GriffGreen** [comment]
also similar but different than #751

**Comment by arbreton** [comment]
@ewingrj Could you tell us what happened with this bug last time?

**Comment by ElMejorge** [comment]
@lorelei1 So as far as I could gather, the second donation for 177 DAI is a bug with MongoDB that created two records for one donation. I deleted one of them in this milestone https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5cd696e4362bdb014ef149d7 to see if this enables you to disburse the milestone. Could you try it again? If it works I'll do the same for the other ones, if it's something else then I'll reinsert the donation record into the DB

**Comment by ewingrj** [comment]
@ElMejorge has the quick fix.

But a true fix would be to determine why a duplicate pledge was created. I looked into it a bit, and I think is has to do with some donations being created with `amount === 0` in feathers. They are never "mined" and then the event is re-emitted in feathers `failedTxMonitor`.

I suspect that [this check](https://github.com/Giveth/giveth-dapp/blob/develop/src/services/DonationService.jsx#L145) needs to be outside of the if statement, so it is always run, not just for split delegations. But that would need to be tested.

Another check that could be added is in [pledges.js createDonation](https://github.com/Giveth/feathers-giveth/blob/develop/src/blockchain/pledges.js#L328) you could check that a donation hasn't been created yet. We only search for un-mined donations currently and update that if found or create a new one. If you threw an error if the donation was already created, that may prevent the duplicate donations from ever happening. But you would need to make sure that "spent" donations were reverted as well

**Comment by arbreton** [comment]
@ewingrj It makes sense the mentioned above i'll try to move the check outside the if statement, additionally i'll try to make a check implementation if the TxHash and the amount is already in the milestone prevent it from duplicating the donation.

@lorelei1 We applied a quick fix to https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5cbf9e54cf48770f67ee85d6 disbursing should be working now, can you confirm if it's working? thank you in advance
