### ISSUE TITLE
Can't Create Profile On Forked Repo

### ISSUE THREAD

**Issue by webjunkie01** [Giveth/giveth-dapp#699]
Hi guys,

I'm using metamask with an account connected to RinkedBy Test to sign in. But when I try to create my profile it says there's have been a problem creating the profile.

![image](https://user-images.githubusercontent.com/193131/53686979-8e663980-3cfc-11e9-8d3b-437e48d8b21f.png)

Here's my .env

  PORT=3010
  NODE_PATH=src/
  REACT_APP_FEATHERJS_CONNECTION_URL=wss://feathers.develop.giveth.io
  REACT_APP_ETH_NODE_CONNECTION_URL=wss://rinkeby.giveth.io/ws
  REACT_APP_ENVIRONMENT='develop'

**Comment by GriffGreen** [comment]
@webjunkie01 can you come to our chat and tell us whats up... we dont really understand this issue.

**Comment by mroberts10** [comment]
Can you join our riot chat. We would love to discuss this more there with you.
