### ISSUE TITLE
Lionsmane issue: Requesting funds in DAI results in no response upon clicking "Propose Milestone"

### ISSUE THREAD

**Issue by JoshuaDuChene** [Giveth/giveth-dapp#701]
I just proposed a milestone on the new Lionsmane update: https://beta.giveth.io/campaigns/5bc0a9a5089683199bce566a/milestones/5c7e0d0d32b73a520a0cb632

When I selected to receive funds in DAI and clicked the "Propose Milestone" button, nothing happened whatsoever, as though I hadn't clicked anything. I tried reloading the page, logging out and back into Metamask, and restarting the browser with the same results each time. After all that, I tried requesting the funds in ETH, and it worked the first time I clicked "Propose Milestone."

I'm not sure what the error is from, but if it's legitimately not a payout option at the moment, the DAI option should be greyed out or removed from the drop-down box where you select the funding type (or whatever solution prevents users from selecting it and/or explains why only ETH is available as a payout option at that time).

**Comment by ewingrj** [comment]
hmm, what browser?

I'm not able to reproduce this. [Here](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c7da6cf32b73a520a0cb61a) is a proposed milestone in DAI.

I was also able to propose a milestone with a cap w/o issue.

Did the popup asking if you wanted to propose appear? Did the button say "saving..."?

If you can reproduce this, can you open the devtools console & post the info. right click on page & select "inspect" in chrome. Then goto the "console" tab

**Comment by JoshuaDuChene** [comment]
Hi RJ!

I just tried to repro using the exact same parameters, same computer,
browser, wallet, body text & images, reviewer, amount, etc. as before, and
now it's working fine with DAI and ETH both.

But yeah, I was in Chrome on Windows, all synced up with Metamask and
signed into my Giveth account. I tried all sorts of refreshes, logging out
and back in, restarting the browser, basically all the first tier tech
support stuff. No matter what I tried, the result of clicking on the green
"Propose Milestone" button at the bottom was absolutely nothing. No pop up,
no indication anything had been clicked. Literally as though the green
button wasn't even there and I was just clicking on white space. Zero
response whatsoever. Now, however, it gives me the expected pop-up box
saying "Propose Milestone? etc..." whether I choose ETH or DAI.

Thanks for the quick response on this - hopefully it was just some one-time
fluke. If I end up reproing the issue, I'll try opening the devtools
console as you suggested and I'll grab that info for the Github issue.

Cheers!
Joshua

-
Joshua Du Chene, Ed.M.

*Creative Audio Design, Production, & Consulting*
*DisinterMedia <http://disinter-media.com/> *

*Vocal Chameleon & Audio Specialist*
Decentralize All The Things! Podcast Network <https://dattpodcast.com/>
Where the Water Tastes Like Wine <http://waterwinemusic.com/>
A Porcupine's Narrative <http://aporcupinesnarrative.com/>
Joshua Du Chene Audio <http://joshuaduchene.audio/>
Mötæ Music <http://motaemusic.com/>
Giveth.io <http://giveth.io/>

*Social*
YouTube <https://www.youtube.com/joshuaducheneaudio>
LinkedIn <https://www.linkedin.com/in/joshuaduchene/>
T <https://twitter.com/JoshuaDuChene>witter
<https://twitter.com/JoshuaDuChene>
Facebook <https://www.facebook.com/JoshuaDuChene>
Instagram <https://www.instagram.com/joshua.duchene/>
<http://www.seattleurbanwineries.com>
