### ISSUE TITLE
Campaign Manager Editing of Proposed Milestone doesn't work

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#703]
I have the option to edit a proposed milestone when reviewing:
![image](https://user-images.githubusercontent.com/39466970/53817302-22b9e180-3f33-11e9-8009-7c75a2adf119.png)

Made a minor change to include proposer's name in Milestone Title, then when I click the Update Milestone button, nothing happens.
![image](https://user-images.githubusercontent.com/39466970/53817380-4e3ccc00-3f33-11e9-8cd0-19344855983d.png)

**Comment by Joshfairhead** [comment]
I can confirm the same issue occurs on the proposers side also.

**Comment by ewingrj** [comment]
It should be fixed in a few mins after the deploy finishes
