### ISSUE TITLE
Lionsmane: Video upload of a .mov 18mb in size hangs indefinitely

### ISSUE THREAD

**Issue by Joshfairhead** [Giveth/giveth-dapp#704]
Upload just hangs forever I think (I did not test it that long, just a couple of mins) but in the same time I uploaded to youtube so canceled the file and used the link for my video instead.

**Comment by mroberts10** [comment]
@Joshfairhead Can you try this again to see if this is reoccurring or a one-off?

**Comment by Joshfairhead** [comment]
The same file fails to upload, or preview.
I'm guessing its to do with the video codec. .mov is a container for other
formats, so perhaps the Dapp either doesnt like the containerised format or
h.264
Trying with a different .mp4 I get the same behaviour. Its also h.264
encoded but this time not containerised.
ᐧ

**Comment by GriffGreen** [comment]
error message would be nice.... 
#607 might consider this

**Comment by Joshfairhead** [comment]
So I tried uploading a .mov for April RewardDAO today. This is the screen shot after several hours of "uploading" in the background. It would be cool to have a progress bar so that we can see if the file makes it to the Dapp, or to somewhat more usefully deduce where faults lie... if the file is not valid, if its hitting the servers, if its just a failure to start the upload etc. - the three " ... " are pretty non indicative.

![Screenshot 2019-05-03 at 19 34 46](https://user-images.githubusercontent.com/34649155/57158151-8f8a1480-6dda-11e9-9e0f-21742b0c06e6.png)

**Comment by Joshfairhead** [comment]
Also I converted the video to .mp4 with same results over 10min. 

.h264 as a non recognised codec perhaps?

**Comment by arbreton** [comment]
This isn't working with any video now

**Comment by Joshfairhead** [comment]
Uh oh spaghetti codes!

**Comment by arbreton** [comment]
After investigating this issue it seems to be that it works now only on beta.giveth.io, the other environments return an error on IPFS 405 'Method not allowed' due to the lack of CORS configurations.

Video uploading only works with videos under 15MB otherwise IPFS returns 413 ' Payload Too Large', Already modified the code so when the call fails shows an error popup.

**Comment by arbreton** [comment]
@Danibelle, @lorelei1, @mroberts10, @GriffGreen, Milestone editing, the display of images, videos, and the uploads should be working fine now, 

I have managed to increase the max file size limit to 100MB
