### ISSUE TITLE
Changing tokens does funky stuff with exchange rates

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#706]
1. If during the process of creating milestone with items user switches the base token, exchange rates don't recalculate for the items.
2. If the token is changed to "Accept donations in all tokens" the output looks

Demonstration of 1: In the screenshot below it was changed from DAI to ETH
<img width="967" alt="screen shot 2019-03-05 at 21 24 32" src="https://user-images.githubusercontent.com/7974813/53837907-1154f180-3f94-11e9-9de8-69ceffb26f3f.png">

Demonstration of 2: Changed from DAI to All tokens (shows incorrect exchange rate and also the column is funky)
<img width="1028" alt="screen shot 2019-03-05 at 21 24 10" src="https://user-images.githubusercontent.com/7974813/53838073-83c5d180-3f94-11e9-968a-090034df7709.png">

**Comment by ewingrj** [comment]
I've addressed the 2nd point.

The first point existed before the latest release (probably since initial token implementation) and still needs to be addressed

**Comment by ewingrj** [comment]
thanks for the bug reports ;)
