### ISSUE TITLE
Can't view my delegations

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#709]
Darn :/ 
<img width="837" alt="screen shot 2019-03-07 at 5 11 47 pm" src="https://user-images.githubusercontent.com/38163206/53971216-bdb1e780-40fc-11e9-9fed-35bec7563fde.png">

Despite saying that, it does load my DACs, campaigns, and milestones. It's only delegations that has a problem.

**Comment by lorelei1** [comment]
maybe same thing going on as in #590 ?

**Comment by ewingrj** [comment]
okay, should be resolve ned
