### ISSUE TITLE
Request feature: provide image specs when proposing new campaign

### ISSUE THREAD

**Issue by kelsien** [Giveth/giveth-dapp#712]
Would be great to know and make dapp look better to know what size the image should be

**Comment by lorelei1** [comment]
Nice good point. I've gotten used to looking for images I know are a good size, and i've forgotten how adappted i am to this DApp! It should be clearer for first timers.

**Comment by vojtechsimetka** [comment]
Aspect ratio of 16:9

**Comment by GriffGreen** [comment]
So we just need that text explicit in the milestone.... but isnt ther actually 2 different aspect ratios to worry about... the header of the milestone AND the tile view?
