### ISSUE TITLE
Metamask transactions currently get stuck in the DApp

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#713]
at least when I want to commit donations. 
the metamask 'wheel' keeps on turning: 

![image](https://user-images.githubusercontent.com/6533925/54092049-c9fda500-4387-11e9-87e7-fd41920f3dec.png)

Only way to unblock it, is to switch from mainnet to rinkeby again, then I get the below message: 

![image](https://user-images.githubusercontent.com/6533925/54092066-faddda00-4387-11e9-8733-a90fdc37cb31.png)

**Comment by GriffGreen** [comment]
@krrisis did it actually work when you switched the network, or can you not commit the delegation at all?

**Comment by krrisis** [comment]
sorry hould have closed this before - it worked again the next day. Switching networks etc did not help, it just unblocked metamask being stuck. Don't know if it was a metamask or a temporary network issue but committing worked next day, so will close for now.
