### ISSUE TITLE
DApp gives wrong creator name

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#714]
[This Milestone](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c7eccfc27ae4211c836be03)  says it has been created by Vojtech at the top, but it actually has only been accepted by Vojtech, pretty sure it is owned and has been created by @Danibelle , so it shows this wrongly at the top. 
Linked to the fact that this is a Milestone that has no reviewer? 

![image](https://user-images.githubusercontent.com/6533925/54092174-4644b800-4389-11e9-8286-9bb423be390e.png)

**Comment by ewingrj** [comment]
#705
