### ISSUE TITLE
When editing a milestone the Dapp crashes

### ISSUE THREAD

**Issue by Joshfairhead** [Giveth/giveth-dapp#715]
As per Michaels response to issue #704 I went to edit my milestone. However the Dapp crashes on clicking the edit button. Error is thrown, email report offered (I hit submit), then the screen goes to the green loading dot on blank background and hangs.

**Comment by mroberts10** [comment]
@Joshfairhead can you try to cancel that milestone and re-try it again?

**Comment by Joshfairhead** [comment]
I'm sorry, its now gone (disbursed RewardDAO). I can try on a new milestone
if preferable?


---
Mobile: +44 (0) 7412090234
Calendar of my non-liquid commitments
<https://calendar.google.com/calendar/embed?src=joshafairhead%40gmail.com&ctz=Europe%2FLondon>
Calendar of my liquid arrangements
<https://calendar.google.com/calendar/embed?src=mef94j8i5evn7f89p76bsql89s%40group.calendar.google.com&ctz=Europe%2FLondon>
Loomio <https://www.loomio.org/g/Yx3rGU5I/techtonic>

ᐧ

**Comment by krrisis** [comment]
Just had the same. Editing Milestone throws the following error:

![image](https://user-images.githubusercontent.com/6533925/54480240-5267c400-4826-11e9-8a92-e5d9a7d9b5f5.png)

error happened in [this Milestone](https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c8d46c1c7ed727e1add1ad1)

**Comment by krrisis** [comment]
@mroberts10 I see you added the tag 'backlog' but also have this on a New Milestone which I wanted to complete today. Again the message '(intermediate value).update is not a function'.
This is this [new Milestone](https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c8d265bc7ed727e1add1a7a)

**Comment by krrisis** [comment]
Referring to issue #737 - @ElMejorge is this something you could help with? thx!

**Comment by krrisis** [comment]
Further updating (as still open) - I see that with older Milestones, like [this one](https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5c5e01319f1aab32c2690bcc) this issue does not exist - these ones I can just edit, both title & text.
