### ISSUE TITLE
Milestone hanging at "Needs Review" status

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#716]
[Loie's RewardDAO Milestone](https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5c82c77e4f696063caa2bdef) appears to be stuck: 

![image](https://user-images.githubusercontent.com/39466970/54210483-f6174400-44b5-11e9-8e6f-f874bb531400.png)

**Comment by GriffGreen** [comment]
able to repeat.. How did you replicate it @ElMejorge ??? Its a feathers issue... @ewingrj can you assist George??

**Comment by ewingrj** [comment]
fixed in giveth/feathers-giveth@8f988d57a80238d04f9e6744eee5a7e2dbe6e0ed
