### ISSUE TITLE
amount donated has larger amount than it should

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#717]
<img width="916" alt="Screen Shot 2019-03-13 at 2 46 11 AM" src="https://user-images.githubusercontent.com/14945613/54247732-55b73300-453a-11e9-8cec-a77341d72c44.png">

https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c4cdde898ca9c454f897a67

**Comment by ElMejorge** [comment]
The reason for this is a discrepancy between the amount shown in the donations table (Which is called amount in the code) and the amount that is summed to get the donation total (Which is called remainingAmount in the code), looking at the console these two values are different on the first donation: 558.9 vs 587.5399. The reason for this discrepancy I don't yet know, I'm still looking into it and after that I'll check if it would happen on other donations.

![image](https://user-images.githubusercontent.com/17806802/54710543-28075680-4b05-11e9-90ca-95ba67962cc9.png)

**Comment by GriffGreen** [comment]
another example https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c3c9ede46d9c67925654794

**Comment by GriffGreen** [comment]
solution almost ready to merge
