### ISSUE TITLE
[Milestone Upgrades] Paid and funded milestone shows "0 donated"

### ISSUE THREAD

**Issue by Pol-Lanski** [Giveth/giveth-dapp#719]
As per image below:
<img width="1128" alt="Capture d’écran 2019-03-13 à 20 50 56" src="https://user-images.githubusercontent.com/19168735/54284534-b85c0d80-45d2-11e9-986e-e4e9f91b7f6a.png">

**Comment by mroberts10** [comment]
@Pol-Lanski have you had any similar issues since posting this bug?

**Comment by krrisis** [comment]
Just wanted to create this one too but good to see that it already exists. This is still the case, all paid Milestones say that 0 has been donated to them. 

![image](https://user-images.githubusercontent.com/6533925/55685398-fa6c3b00-5955-11e9-950d-a2075f1205be.png)

**Comment by arbreton** [comment]
It's showing now the correct amount or the link the milestone
