### ISSUE TITLE
Whitelist Jorge for Castro Limon Campaign on Beta

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#720]
Jorge needs to get the Fundación Castro Limón campaign created today. He has completed the Beta Users Form, response can be seen [here](https://docs.google.com/spreadsheets/d/1n-J7u41W_HP3Uqg4foGLGX4a0C-Yz1HuhIlhLsId5lM/edit?usp=forms_web_b#gid=391373504).

This means we need him Whitelisted as a Project Owner, the Eth address provided is:  0x06aDCE1Ea3b2d7B839349f1381e1965AE08D44DC

Jorge Montiel | @molloy:matrix.org

This is also a good opportunity to hand off responsibility for updating the Whitelist to Jorge with Michael as a backup as well and take this off Vojtech's list of things he still does for the Giveth DApp.  It would be helpful to include at least one of them in the completion of this issue toward that end!

**Comment by vojtechsimetka** [comment]
@Danibelle as I understand this is time sensitive I have already added Jorge Montiel to the whitelist. However, Jorge has all the instructions and I asked him to try it.
