### ISSUE TITLE
Some formatting does not work in Milestone status updates and pictures are distorted

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#722]
In [this milestone](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c4cdde898ca9c454f897a67), I have put quote (the middle paragraph) but the status update does not show it. Also the picture is rather distorted.

<img width="632" alt="Screen Shot 2019-03-16 at 20 48 39" src="https://user-images.githubusercontent.com/7974813/54480788-16842d00-482d-11e9-89cd-efd1b688172a.png">

**Comment by GriffGreen** [comment]
would make for a good gitcoin issue

**Comment by aminlatifi** [comment]
The problem is that our editor (quill) doesn't add appropriate styles to image tags...
I fixed this manually for this milestone...
To solve it permanently we should spend time to configure quill if possible or use another editor which doesn't have quill problems

**Comment by arbreton** [comment]
Could not replicate have you seen this one @aminlatifi ?
