### ISSUE TITLE
Either Scroll or Character Limit Needed... UX request

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#723]
When adding expenses/receipts to a milestone, there appears to be no limit to the description, so I type out a wordy one :) It said "This is a regular self delegation milestone, i'm just testing the expenses function" or something like that. And then when the milestone is published, it cuts off halfway and there's no way to see the full description... either need to impose a character limit on that field or make scroll function available when the milestone is published cuz otherwise we just get this dot dot dot awkwardness. 

<img width="890" alt="Screen Shot 2019-03-19 at 1 36 35 AM" src="https://user-images.githubusercontent.com/38163206/54568318-c8675900-49e7-11e9-927e-32fd1d9699be.png">

**Comment by GriffGreen** [comment]
35 dai bounty... to post this :-D

**Comment by gil-air-may** [comment]
Another option is to have a button inside the description cell that displays a pop-up modal with the full description. What do you think?
