### ISSUE TITLE
Pagination for My Delegations!

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#725]
2 Things, Would be great to have:
- all delegations shown on "my delegations," including committed ones (right now it appears to be only proposed ones
- pagination to see all these historical delegations

@ElMejorge Thank you for working on this stuff!!!

**Comment by GriffGreen** [comment]
I thought we already had this....

**Comment by GriffGreen** [comment]
check to see if its actually an issue

**Comment by arbreton** [comment]
It's going to be fixed on performance improvements on loading and data handling tasks
