### ISSUE TITLE
False Alarm Error Message Pops Up! 

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#728]
I think this has happened to me before... but I don't remember the issue. The DApp tells me first that the delegation failed, but at the same time Metamask is prompting me for a successful transaction 

<img width="1243" alt="Screen Shot 2019-03-22 at 11 20 17 PM" src="https://user-images.githubusercontent.com/38163206/54853756-64030d00-4cf9-11e9-9ed0-5359e44d1592.png">

and then it confirms success after I sign the metamask tx... 

<img width="1230" alt="Screen Shot 2019-03-22 at 11 20 28 PM" src="https://user-images.githubusercontent.com/38163206/54853781-79783700-4cf9-11e9-9817-8ea9eb453a12.png">

Perhaps related to issue #577

**Comment by GriffGreen** [comment]
#607 should solve this

**Comment by GriffGreen** [comment]
this is in the delegations page

**Comment by GriffGreen** [comment]
I think we should check if Lorelei is still running into this

**Comment by arbreton** [comment]
It's getting solved on #607 with a more complete implementation
