### ISSUE TITLE
Get rid of the waiting for donations in tokens

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#730]
It would be pretty easy to reduce the pain of donating tokens by allowing the user to submit both txs at once. 

I would suggest we just have a session where we revise the donation design, allowing the user to 

1. unlock (better term than approve) just the amount that they need for this donation (default)

2. Flip a switch that says something along the lines of "unlock 10x the amount of this donation, this is a risk but because i trust the Giveth team and Giveth smart contracts i would rather enjoy a better UX dont want to have to pay extra gas everytime i want to donate"  this will multiply the donation by 100 and approve their account for that amount.... it is important that if there is an approval for an amount larger than the

3. GET RID OF WAITING! Allow the user to click a pay button to make the payment tx right away so they can get on with their day.

**Comment by GriffGreen** [comment]
follows #735

**Comment by GriffGreen** [comment]
We need to hot wire metamask to auto estimate gas for the second tx and have it pop up right away

**Comment by GriffGreen** [comment]
set the gas limit to 400,000 for the second gaslimit

**Comment by aminlatifi** [comment]
https://docs.metamask.io/guide/sending-transactions.html#example

**Comment by GriffGreen** [comment]
tackling this this week

**Comment by arbreton** [comment]
some updates, the transactions are working OK now, seem to be a problem with token amount specifics that need some more investigation, will reach out tomorrow morning

**Comment by GriffGreen** [comment]
3% milestone is worth testing

**Comment by aminlatifi** [comment]
Any updates?

**Comment by arbreton** [comment]
Still looking at this one for some reason 2nd tx is failing even when gas is very high and tokens are approved could be a bug

**Comment by aminlatifi** [comment]
Make gas limit 200K

**Comment by aminlatifi** [comment]
@GriffGreen I tried to do the donate tx immediately after approve allowance, but triggering the tx cause this exception from MetaMask and no popup is shown
```
https://home.etherscan.io/tx/undefined => Error: Internal JSON-RPC error.
{
  "message": "VM Exception while processing transaction: revert",
  "code": -32000,
  "data": {
    "stack": "c: VM Exception while processing transaction: revert\
    at Function.c.fromResults (/Users/amin/Work/giveth/feathers-giveth/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:194812)\
    at e.exports (/Users/amin/Work/giveth/feathers-giveth/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2095043)",
    "name": "c"
  }
}
```

**Comment by aminlatifi** [comment]
@GriffGreen For unlock 10x I need some UI/UX design, after that the implementation would be easy.

**Comment by aminlatifi** [comment]
When two transactions are needed to set allowance before an ERC20 token donation, I made the 2nd tx popup immediately after first one is confirmed.
It's not possible to do the same for donation tx, because it will throw execution reverted error and MetaMask doesn't show anything.
