### ISSUE TITLE
Allow users to not sign into the DApp so that Aragon DAOs can access the DApp with Frame

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#731]
This is an alternative option to #611 which @ewingrj has convinced me is a better solution... there will need to be an extra button that allows the user to not sign in here: 

<img width="766" alt="Screen Shot 2019-03-24 at 12 24 18 PM" src="https://user-images.githubusercontent.com/14945613/54878727-f823c000-4e30-11e9-824c-913193b702c9.png">

Maybe @ewingrj can further specify? also will there be an issue with feathers like #658 and #620

**Comment by GriffGreen** [comment]
@arbreton lets have a deep dive convo on this topic!

**Comment by arbreton** [comment]
@GriffGreen totally, i'm right now adding a button and i will be testing how feathers behaves with those changes, if there is additional info we can definitely jump on a call
