### ISSUE TITLE
[Milestone Upgrades] Milestone created but then unable to be viewed... but able to be edited!?!?!?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#732]
There are a few bugs here... I will video the issues 

1. is the fact that i cancel the tx and then the milestone is inaccessible... :-( here are the broken milestone links: 

https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c976f17150a830a701e15d8
^^^First one that was made, i canceled it.

https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c977700150a830a701e15de
^^^The one i made in the video that i havent canceled yet... but will by the end of the week

2. Also i think its a bug that the picture viewer only pops up after that user makes a second action (or input)... it should pop up right away.

https://youtu.be/-01T9SGg4uQ

**Comment by GriffGreen** [comment]
Ok this is a bug for RJ... because it is actually because of the specific path i chose.



To reproduce:
1. Be the Campaign manager
2. 

<img width="677" alt="Screen Shot 2019-03-24 at 3 56 02 PM" src="https://user-images.githubusercontent.com/14945613/54881183-9d4c9180-4e4d-11e9-9001-5283637e7210.png">

**Comment by GriffGreen** [comment]
the edit webpage works... but can't submit edits....
<img width="1200" alt="Screen Shot 2019-03-24 at 4 57 51 PM" src="https://user-images.githubusercontent.com/14945613/54882010-1fd94f00-4e56-11e9-804f-b63c8104c87d.png">

**Comment by GriffGreen** [comment]
Bug seems present in other campaigns too: https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5c97b42e150a830a701e15ff

**Comment by GriffGreen** [comment]
but it works in develop!?!?!? https://develop.giveth.io/campaigns/5c979871b670ef31461c180f/milestones/5c979967b670ef31461c1812

**Comment by GriffGreen** [comment]
but not in Decentral: 
and it gave some other weird error... it created 2 proposed milestones and an auto accepted one as expected (link to that one below) https://beta.giveth.io/campaigns/5b3d94ba329bc64ae74d1421/milestones/5c97b42e150a830a701e15ff

**Comment by GriffGreen** [comment]
It works if i add a recipient :-D

https://beta.giveth.io/campaigns/5b51bdbdf8ba4732631989f5/milestones/5c97f058150a830a701e160b

**Comment by ewingrj** [comment]
okay, I fixed the display bug.

can you check if the edit bug is still an issue?
