### ISSUE TITLE
Chrome is rejecting the DApp

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#734]
I can't get a single DApp page to load while in google chrome (which is where my address I use to interact with the DApp is stored). I need to get on to be able to delegate for the Unicorn DAC and make time sensitive milestones! 
Please halp!! 
Have already cleared cache and cookies further back than when it quit working, no luck.

**Comment by krrisis** [comment]
What is the message you are getting exactly Loie? Then it's easier for them to help out, possibly a screenshot? DApp works perfectly on my side right now.

**Comment by GriffGreen** [comment]
@lorelei1 solved this... can you post the solution?

**Comment by bowensanders** [comment]
The solution that I gave to Loie:

Check your DNS settings and make sure that you have Google's DNS servers set up (especially if you are in an internet-censored area, or you have any issues reaching sites you think you should be able to)

Google's DNS Servers are: 8.8.8.8 & 8.8.4.4
On OSX it can be found in System Preferences > Network > WiFi Settings > DNS

**Comment by krrisis** [comment]
Or you can use the chrome/brave extension 'Windscribe', a free VPN with almost unrestricted data, and avoids you to have to go via google.

**Comment by bowensanders** [comment]
This is just google's DNS servers though. They've always been censorship-free AFAIK - which you can see even painted on walls in warzones and protest areas - i've seen it on twitter during demonstrations and internet lockdowns... I'm sure there are other censorship resistant DNS solutions, but I know that this one works and you don't have to VPN to use it (but you can if you want)

**Comment by lorelei1** [comment]
@bowensanders can you help me to remember exactly what we did to correct this? cuz your solution worked for me... it would be nice to document it here maybe even with screen shots for good resources in the future!
