### ISSUE TITLE
Error on Milestone editing

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#737]
![image.png](https://images.zenhubusercontent.com/5b588051b2890d2788b3d5de/13b6d919-3192-4d96-b105-6355506551ca)

Editing this [Milestone](https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5c9cd92c150a830a701e16f6/) to add more notes and links.. I've tried a few ways and keep getting this error.

Yesterday it actually duplicated the Milestone then had no text at all in the duplicate, I've cancelled but it should still be there if helpful.

**Comment by Danibelle** [comment]
This issue is preventing Milestones that have been rejected because they need edits to be revised and completed - which means it's affecting our ability to pay out in a timely manner..  [Lanski's Milestone in the RewardDAO Campaign](https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5ca59eacdd7b2c0bf14ed74f) is one example, and I believe Kris is impacted as well.

Please prioritize this one! :)

**Comment by krrisis** [comment]
Yup indeed, thx Dani. Kept updating my findings in issue #715

**Comment by krrisis** [comment]
Hey @mroberts10 or @ElMejorge , so this was changed to in progress 15 days ago, do you think this will get fixed? If not I can see if I can cancel this Milestone and ask the Unicorn DAC to re-fund a new Milestone. An said, I cannot complete this Milestone (and pay myself) if I cannot edit in a description of the tasks I did that week. Thanks for an update!

**Comment by krrisis** [comment]
Update, I cannot ask people to re-fund this Milestone, because I see it's not only this one. 

Same issue with these Milestones, cannot edit, so cannot pay myself for all these outstanding - funded - Milestones. 

https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c8d46c1c7ed727e1add1ad1
https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5c9ea4bfdd7b2c0bf14ed206
https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5caa114f8269486f489a63c4

**Comment by krrisis** [comment]
Update - also newly created Milestones (today) are impossible to edit, one example: https://beta.giveth.io/campaigns/5b3789513a65c31e4e4e8328/milestones/5ccb2b43cf48770f67ee8704

**Comment by arbreton** [comment]
@krrisis do you know if there's any common thread between these milestones? Since it doesn't seem to happen to every milestone

**Comment by krrisis** [comment]
I have no idea - it could be linked to specific moments when they are created? I know it's an issue we've had before and @perissology knew what was up then, it could be the same thing. It's in any case a crucial one, I think I now have about 1,5 months of pay locked in uneditable Milestones that I cannot complete.

**Comment by krrisis** [comment]
pinging @ewingrj bcs I'm about to max out all my credit cards and this is not OK.

**Comment by krrisis** [comment]
ok thx a gazillion @ewingrj . This is FIXED. Before closing prob best that you check what got changed here @arbreton - or maybe RJ can clarify, so you guys know what to do if this happens again (we've had this a few times). thx!!

**Comment by mroberts10** [comment]
The error in milestone editing appears to have returned or is intermittent.  @ElMejorge  can you edit your own milestone? https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5cd9538f362bdb014ef14d16

**Comment by arbreton** [comment]
@ewingrj Could you explain exactly what's happening in these milestones? How did you fix the issue?

**Comment by ewingrj** [comment]
idk, I never looked into this.

There was another issue where the ui was calling an undefined value & throwing an error that I fixed. Not sure if this is the same thing or not. It looks like it is failing when they try to save, instead of when the milestone loads (like the other issue I fixed)
