### ISSUE TITLE
[Milestone Upgrades] Need a way for No-Cap Milestones to be marked complete and paid

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#741]
With the new Milestone functionality to disable the 'cap', there are some strange things happening with 'completing' the Milestones.

In particular, the RewardDAO Campaign now allows Milestones to be created before the value of points dished is known.  Once the month ends, funds are delegated and collected, the Milestones remain with "In Progress" status - there is no way to fully complete and change status to Paid.

![image](https://user-images.githubusercontent.com/39466970/55655506-0ae7ae80-57ba-11e9-9cba-a5c807019067.png)

Request #1: In the 'My Milestones' view, the only option currently is to Change Recipient.  Add a button to 'Mark Complete' that changes status to Paid, and moves Milestone to the Paid tab (out of Active).  See the Milestone in image below [Dapp Whitelist and Beta User Support](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c7eccfc27ae4211c836be03)

![image](https://user-images.githubusercontent.com/39466970/55655747-9b25f380-57ba-11e9-9815-529b8963ceca.png)

Request #2: When viewing the Milestone, add the Mark Complete button with same functionality at top too:
![image](https://user-images.githubusercontent.com/39466970/55655819-cc062880-57ba-11e9-965f-0afdf2dced23.png)

**Comment by GriffGreen** [comment]
ok so in summary we want a milestone marked complete button for milestones with no cap so that the Campaign can close that request... and it doesnt show in progress forever

In a dream world, we would have that button pop up after the first time the milestone is paid out, and the milestone manager, **Campaign Manager**, and Recipient would all have the ability to push it.

If marked complete, and the milestone still has money to collect, it should have a "Completed" status

If marked complete, and the milestone has no money to collect, it should have a "Paid" status

**Comment by ewingrj** [comment]
Hmm, so this isn't really possible w/o modifying the contracts & redeploying the milestone contracts. This is also not in the original spec laid out for the contract changes, so to me this is more of a feature request for the next set of contract changes/deployment.

The only possibility w/o modifying the contracts is to restrict this action to the milestone manager only. Then we can just store this in the ipfs data.

**Comment by ewingrj** [comment]
Also, this would only be applicable if a milestone does not have a reviewer. Otherwise it would allow bypassing the review process.

**Comment by GriffGreen** [comment]
Is it possible for this specific milestone type (no cap & no reviewer) to not transfer the Milestone manager to the person proposing the milestone and instead leave the campaign manager as the the milestone manager... this might give the desired functionality... 

Then at least they could control what is seen in their campaign as options to donate to.

Its definitely a big bug tho if a milestone can't be turned off some how... 

And ideally it wouldn't need to be canceled but it could be completed/paid 

If we have to fake it some how that's ok for this version.... as long as these milestones have a way of being closed and still showing up as successful milestones from the past.

Maybe if a milestone of this type has been paid out the cancel button is reused as a mark complete button?

**Comment by ewingrj** [comment]
Okay, this this now live. Campaign Manager & Milestone owner can archive an uncapped milestone.

FYI, archiving a milestone as the campaign manager is not reactive and the milestone will only change status after the tx is mined.

**Comment by Danibelle** [comment]
Gorgeous Solution!

Completed Milestones can now be archived:
![image](https://user-images.githubusercontent.com/39466970/57335135-55c15280-70e7-11e9-9336-07eae9b9e2b8.png)
