### ISSUE TITLE
[Milestone Upgrade] Need to be able to continue raising funds after withdraw

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#746]
https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5ca47926dd7b2c0bf14ed5d1

This milestone was paid out but it needs to be able continue to accept donations to reach the cap... right now i can't donate to it.

**Comment by ewingrj** [comment]
Giveth/feathers-giveth@5684a194957b5f85f3f687f9b392f3ae2fcb1e42

**Comment by ewingrj** [comment]
this is now live

**Comment by GriffGreen** [comment]
hmmmm so for the old milestone... https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5ca47926dd7b2c0bf14ed5d1 i guess i cancel it?

Nm I'll just make a note in it and leave it be.

**Comment by GriffGreen** [comment]
damn! I can't edit it....!

**Comment by ewingrj** [comment]
regarding editing... does it fail when you try and save or before?

**Comment by arbreton** [comment]
Milestone now are only are set to paid status when fullyDunded
