### ISSUE TITLE
3 metamask txs to donate?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#748]
I am trying to fund the DApp Campaign and I had a weird Approve 0 tx precede the normal 2 txs.... https://etherscan.io/tx/0xb71806dc2ce7b28bff6a2c992179bc0d837c659890a6d5d7a7d460f2d7a3a1e9

<img width="1238" alt="Screen Shot 2019-04-15 at 6 17 50 PM" src="https://user-images.githubusercontent.com/14945613/56150409-23707980-5faf-11e9-8929-3fa3c77ed410.png">
<img width="1234" alt="Screen Shot 2019-04-15 at 6 22 14 PM" src="https://user-images.githubusercontent.com/14945613/56150408-23707980-5faf-11e9-9bbc-19d6660019c9.png">
<img width="1265" alt="Screen Shot 2019-04-15 at 6 23 56 PM" src="https://user-images.githubusercontent.com/14945613/56150407-23707980-5faf-11e9-8eb4-e388c223856c.png">

**Comment by ewingrj** [comment]
not a bug. You already have an approval, but it's not enough. You can't just up an approval (contract restriction b/c there is a race condition here that opens up a vulnerability). You need to first set to 0, then up it, then donate

**Comment by arbreton** [comment]
Can this be closed or is there something that can be done related to this behavior?

**Comment by Danibelle** [comment]
This is in the SmartContract and designed to prevent frontrunning attacks.  Annoying but necessary.

**Comment by GriffGreen** [comment]
This is because of the race condition for approvals... a well known issue with the ERC20 standard
