### ISSUE TITLE
Bridge Monitor is Broken

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#749]
<img width="1420" alt="Screen Shot 2019-04-16 at 10 35 41 AM" src="https://user-images.githubusercontent.com/27023908/56231472-6aa04e00-6033-11e9-90c7-47f3679a91b2.png">
The bridge monitor dashboard is unable to pull data from the bridge monitor.

According to @vojtechsimetka : 
<img width="486" alt="Screen Shot 2019-04-16 at 10 37 36 AM" src="https://user-images.githubusercontent.com/27023908/56231585-ae935300-6033-11e9-9d89-4617d1c98126.png">

**Comment by ElMejorge** [comment]
@bowensanders The feathers server for the bridge service was down for some reason in the server. Fixed this by restarting it and it seems to be pulling data now. Please double check the data to see if it's all right or something else needs to be done

**Comment by bowensanders** [comment]
I just checked it again, the problem where it is showing old data is still an issue, even though the server restarted. It's saying the newest tx is 498 when it is actually 529 (checked the contract manually via etherscan)

So the original problem still exists, even though the feathers service is working, it doesn't have current data.
