### ISSUE TITLE
Minimal donation value

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#75]
Decrease and fix the minimal donation value. Currently it is set to 0.1 ETH (around 30 USD) but the minimal real value is 0.100001 . I propose the minimal value should be at most 10x current recommended gas price.

**Comment by caseyhelbling** [comment]
Definitely agree with this. I also think we should not include the gas in the minimum calculation. For lay user that is very confusing. Here is a gif of my use of it... UX is a bit wonky... 

![donate-now-bug](https://user-images.githubusercontent.com/12005/33235004-b66b4e66-d1f5-11e7-8284-1ef766be36ef.gif)
