### ISSUE TITLE
Upload image doesn't work sometimes in Milestone body

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#750]
Sometimes I have to redo the image upload 2, 3, 4 times... now it's just not doing it for me at all :( 
This is when I click on the image upload button in the action menu above the milestone text field. 
Other images in this same milestone uploaded fine, it seems to be kinda random when this happens.

**Comment by lorelei1** [comment]
Aww, and then it's very unmotivating to create attractive milestones when the images get squished and warped.

**Comment by GriffGreen** [comment]
what are the images?
can you add them here?

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5cbb3774cf48770f67ee82d9
