### ISSUE TITLE
Line item receipts bug when changing the currency raised

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#752]
When I put in an itemized receipt, and then change the currency i'm raising, the conversion lags behind and gives incorrect numbers. I took a screen recording cuz it's easier to explain that way! 
https://youtu.be/OEecvSccBys

**Comment by GriffGreen** [comment]
related to #706

**Comment by Danibelle** [comment]
related to 706, plus a new one today 837

**Comment by GriffGreen** [comment]
#752

**Comment by GriffGreen** [comment]
#837

**Comment by GriffGreen** [comment]
apparently this is a common issue!
