### ISSUE TITLE
Release.giveth.io is down

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#755]
We have some new users ready to practice making Campaigns and Milestones - however the sandbox appears to be closed for cleaning:

![image](https://user-images.githubusercontent.com/39466970/57230164-5372d180-6fdd-11e9-9ca9-2daca570a922.png)

@ElMejorge was having a look at it late last week.

**Comment by arbreton** [comment]
Same issue happening with develop.giveth.io

**Comment by arbreton** [comment]
Release should be working fine now, develop.giveth.io is still down ATM, working on it
