### ISSUE TITLE
RewardDAO Spreadsheet Isn't Populating, Again...

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#756]
Throughout the month (and especially right now) I need to use this [spreadsheet ](https://docs.google.com/spreadsheets/d/1KQEjMKXx9tKHiDqn6tj5iRIwdSwqa6_HrM5N-AXBBSs/edit?usp=sharing)to approve and process Milestones for the [RewardDAO ](https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424)Campaign.

It often gets locked up - it's designed to go check - somewhere - and retrieve or update data, on a high frequency throughout every day.  I do not know how it works and would like to so I can kick it back up when it goes down.  Here is the [Drive Folder](https://drive.google.com/drive/folders/0B2gzflwFITCBdmYyb1BJcVp5bjg) where the Template and Monthly versions are stored.

Time sensitive, gotta get the March closed out and bring on the April.. calendar doesn't wait - could use some help on this one sooner than later, thank you!

**Comment by GriffGreen** [comment]
fixed by replacing the formulas with manual entries
