### ISSUE TITLE
EtherBank Campaign Request

### ISSUE THREAD

**Issue by alirezapaslar** [Giveth/giveth-dapp#758]
Kindly accept my humble request to create a campaign for EtherBank on beta.giveth.io

EtherBank used to have milestones on Social Coding campaign. Here is a [link](https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c43158054c4dd181cdb2939). Here's [another](https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd/milestones/5c18f6616c76245cd3f97b5b).
There are other milestones as well. You'll find them in Social Coding [campaign](https://beta.giveth.io/campaigns/5b3b3a34329bc64ae74d13cd).

Oh, and here's an [article](https://medium.com/@paslar) comparing EtherBank to MakerDAO regarding their fees and complexity.

This is your friend [Paslar](https://twitter.com/alirezapaslar) speaking. You can find my address [here](https://docs.google.com/spreadsheets/d/1n-J7u41W_HP3Uqg4foGLGX4a0C-Yz1HuhIlhLsId5lM/edit?usp=sharing). I'll be the campaign manager for EtherBank.

**Comment by Danibelle** [comment]
I will get you Whitelisted today @alirezapaslar , thank you!

**Comment by Danibelle** [comment]
OK - it appears I have completed this successfully - I reloaded beta.giveth.io and it didn't crash, AND, I checked feathers.beta.giveth/whitelist and see you there:

![image](https://user-images.githubusercontent.com/39466970/57306146-ee37e280-70a7-11e9-9f56-8f1189fdd9cb.png)

@alirezapaslar , please go to the Dapp and see if the "Start a Campaign" button appears at top for you now (and works)!

**Comment by alirezapaslar** [comment]
It appears!
Let's check if it works!

**Comment by alirezapaslar** [comment]
It does!
