### ISSUE TITLE
typo before metamask/matamask login ;-) 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#759]
Typo here as flagged by @Pol-Lanski - didn't see this before either, maybe recent? 

![image](https://user-images.githubusercontent.com/6533925/57622380-c22bce00-758d-11e9-9304-f32ce7e955b2.png)

**Comment by GriffGreen** [comment]
figured i'd make a PR to see how long it takes to be merged.... https://github.com/Giveth/giveth-dapp/pull/763/commits/c190bc6fbd02b185a34710af24d031f12d167ec7
