### ISSUE TITLE
Notifications don't stay long enough

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#76]
Currently the notifications live only 1 second. Since the system will not have that many notifications, I propose to increase this time to at least 5 seconds.

<img width="416" alt="screen shot 2017-10-17 at 22 02 04" src="https://user-images.githubusercontent.com/7974813/31686588-d676b4a8-b386-11e7-84bf-73aebd0271e3.png">

**Comment by satyavh** [comment]
Actually they live for 3000ms, I increased it to 5000
