### ISSUE TITLE
Cannot access the dApp when having multiple wallets (Chrome extensions) installed 

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapp#761]
Giveth dApp does not recognize the Dapper Wallet Chrome extension.

I had Dapper wallet Chrome extensions installed which seemed to be automatically set up as a default wallet upon installation if such settings even exist. 
https://www.meetdapper.com

When trying to access the beta.giveth.io I'm being informed that Metamask should be installed (popup with download links for Metamask) although I already have it installed and to my knowledge using it as the main getaway for dApps.

Solution: I had to disable Dapper extension and reload the Giveth dApp.

Is there a workaround to this? Can we support multiple chrome extensions for wallets?

**Comment by GriffGreen** [comment]
Improve the error message

**Comment by GriffGreen** [comment]
also... are we only allowing users to use metamask?

**Comment by GriffGreen** [comment]
@markoprljic does the giveth dapp not work with Dapper?

**Comment by GriffGreen** [comment]
We could add wallet connect and let our users use other wallets.. wait for a user to demand it
