### ISSUE TITLE
Weird milestone behaviour after hitting "disburse"

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapp#762]
One of my milestones was ready for payout (it got overdfunded actually). The whole flow worked great until I hit "disburse" - then the milestone changed in overview to **0 DAI donated** (see screenshot)
![image](https://user-images.githubusercontent.com/317685/57708137-2079af00-7669-11e9-9091-062bb1b31286.png)

The bridge monitor shows it as normal, so I guess it will be paid out as requested. Lanski donated last, so I guess he might be due for a refund (the overfunded amount)?

I will update this issue should something change in the DApp as this milestone payout progresses.

This is the direct link to the milestone:
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5cab4fc28269486f489a640b

**Comment by GriffGreen** [comment]
I think this is a bug from the milestone upgrades?

**Comment by ewingrj** [comment]
I don't think this was from the milestone upgrades, but should be resolved now:

40cc37e and giveth/feathers-giveth@d23c669

**Comment by geleeroyale** [comment]
Looks like expected now! Thanks!

**Comment by geleeroyale** [comment]
Unfortunately there is one minor issue left. The milestone payment worked flawlessly, but the UI did not move the milestone to "Paid" - it stays in the overview with his max amount donated and a status of "completed".

![image](https://user-images.githubusercontent.com/317685/58023906-45f73480-7b11-11e9-861a-cdf45c3d06da.png)

**Comment by ewingrj** [comment]
this is for the original milestone or a new one? If the orig, then it's because of the previous bug, but shouldn't happen for new milestones. I can manually fix the original

**Comment by mroberts10** [comment]
needs to manually updated for the old milestone.
