### ISSUE TITLE
Milestone edit error and DAI entry error

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#764]
For some reason when I entered my milestone (https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5cd54e19362bdb014ef14917), the amount of DAI I entered did not register.  As far as I am aware, I filled out the form appropriately.

Now, when I am trying to edit my milestone, it is throwing the following error:
There has been an error in the DApp.
Details - Error message:
Cannot read property 'toFixed' of undefined

Perhaps you can see it here: https://beta.giveth.io/campaigns/5c9e0a5add7b2c0bf14ed18d/milestones/5cd54e19362bdb014ef14917/edit/proposed

Please advise  =)

**Comment by ewingrj** [comment]
not sure about the dai part, but you should be able to edit now

**Comment by Jeff-Emmett** [comment]
Thanks!  Got that sorted.
