### ISSUE TITLE
Fixing Travis Integration so contributors stop wasting their time 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#766]
https://github.com/Giveth/giveth-dapp/pull/757#issuecomment-489735406
This is an issue... we have travis doing checks but the checks fail... we need to better maintain this. We are wasting every contributors time when this check fails :-(

**Comment by nadirlaskar** [comment]
It seems there is some problem with eslint check in the  build [process](https://travis-ci.org/Giveth/giveth-dapp/builds/528971192?utm_source=github_status&utm_medium=notification)

```
20.92s$ npm run eslint
> giveth-dapp@0.1.0 eslint /home/travis/build/Giveth/giveth-dapp
> eslint 'src/**/*.js*'
/home/travis/build/Giveth/giveth-dapp/src/components/ArchiveMilestoneButton.jsx
  87:9  warning  Unexpected console statement  no-console
/home/travis/build/Giveth/giveth-dapp/src/components/BackupWalletButton.jsx
  20:15  error  Replace `⏎······Array.isArray(wallet.keystores)·&&⏎·····` with `·Array.isArray(wallet.keystores)·&&`  prettier/prettier
  23:7   error  Delete `··`                                                                                           prettier/prettier
  24:1   error  Replace `··········` with `········`                                                                  prettier/prettier
  25:9   error  Delete `··`                                                                                           prettier/prettier
  26:1   error  Replace `··········` with `········`  
```

Some components are having inconsistent spaces i believe, which is failing the eslint check

**Comment by GriffGreen** [comment]
@nadirlaskar how much would you charge us to fix this?

**Comment by nadirlaskar** [comment]
> @nadirlaskar how much would you charge us to fix this?

There are 45 files having lint issue in the repo right now, some files are fixable with eslint --fix, others require manual changes.

Some files are using label without `htmlFor` attribute, fix requires updating the property where possible or replace with `<span className="label"></span>`

Also some update is required in `eslint` & `eslint:fix` script in `package.json`

All changes are possible to be completed in 2 hrs,
I can start working on a pull request with the described fixes for 60 DAI

**Comment by nadirlaskar** [comment]
> @nadirlaskar how much would you charge us to fix this?

I have opened a pull request with a fix, check it out @GriffGreen

**Comment by GriffGreen** [comment]
NICE! Whats your address? we are making a milestone for you in the dapp ;-D

**Comment by nadirlaskar** [comment]
> NICE! Whats your Ethereum address? we are making a milestone for you in the dapp ;-D George or Andre will review :-D
This will be my meta mask address `0x039dACca4a447E140d8B29F0652cd844Ea827D1a`

**Comment by nadirlaskar** [comment]
> NICE! Whats your Ethereum address? we are making a milestone for you in the dapp ;-D George or Andre will review :-D

@GriffGreen  Yay! Thanks :)
@ElMejorge  I am available for any clarifications on pull request.

**Comment by nadirlaskar** [comment]
@GriffGreen Is this issue closed ?

> NICE! Whats your Ethereum address? we are making a milestone for you in the dapp ;-D George or Andre will review :-D

**Comment by nadirlaskar** [comment]
> NICE! Whats your Ethereum address? we are making a milestone for you in the dapp ;-D George or Andre will review :-D
@GriffGreen 
The issue looks closed, when can I expect the bounty?

**Comment by GriffGreen** [comment]
:-D! Sorry for the delay! I'll get @mroberts10 to make this happen asap

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ce2d8182bb8c0257c7b83c5

**Comment by nadirlaskar** [comment]
> :-D! Sorry for the delay! I'll get @mroberts10 to make this happen asap

Thanks, that will be great! :-)

**Comment by nadirlaskar** [comment]
> https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ce2d8182bb8c0257c7b83c5

I see there is no recipient for the milestone, 
[this](https://github.com/Giveth/giveth-dapp/issues/766#issuecomment-494065941) is my eth address.

**Comment by GriffGreen** [comment]
Sorry about that delay! its up now tho! https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ce2d8182bb8c0257c7b83c5

**Comment by GriffGreen** [comment]
I sent a little extra eth to you to make up for the delay (That DAI could have been on Compound making interest!)
https://etherscan.io/tx/0xec91ea58a4151575c99009989b5c44b6a1015c41c0d9af76a75eacba294ec5b6

**Comment by nadirlaskar** [comment]
> Sorry about that delay @nadirlaskar ! its up now tho! https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ce2d8182bb8c0257c7b83c5

@GriffGreen looks like the [amount](https://rinkeby.etherscan.io/tx/0xbab7d8199056b73249bccbf3e25129ed4dc303b6629c5bcc76c1ee78cf0a995b) is sent to Rinkeby Test Network, Isn't it suppose to be sent to main-net.
