### ISSUE TITLE
Everytime i paste when making a campaign i get scorlled to the top of the window

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#769]
i hit ctrl-v and then i scroll out of view from where i was pasting... its pretty lame!

**Comment by mroberts10** [comment]
Colleagues in Nepal to look at this issue

**Comment by arbreton** [comment]
Have been trying to replicate this error, just some probing questions needed @lorelei1, 
is this happening on Google Chrome / Windows combo?
is this on the create campaign screen pasting on the description field (anywhere maybe?) ?

Already tried creating a campaign on mac os and pasting but doesn't seem to be happening anymore

**Comment by mroberts10** [comment]
need a lot of text to reproduce the bug

**Comment by arbreton** [comment]
Assigned to Amin

**Comment by aminlatifi** [comment]
The issue relates to [a bug](https://github.com/quilljs/quill/issues/2027) issued in react-quill project.
Nevertheless, there is [a fix](https://github.com/quilljs/quill/issues/2027#issuecomment-486513119) for this but it flickers on paste.

**Comment by 1002237913** [comment]
This is also a good solution
```javascript
   function findEditorScrollContainer(quill) {
      let el = quill.root;
      while (el) {
        if (el.scrollTop > 0) {
          break;
        }
        el = el.parentElement;
      }
      return el;
    }

     quill.on('editor-change', (type, delta, oldDelta, source) => {
          quill.scrollingContainer = findEditorScrollContainer(); // Solve the problem of scrolling to the top when pasting
         // your others code
       
     });
```
