### ISSUE TITLE
Name does not get saved when updating the user profile for the first time

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#77]
The first time user saves their profile, the Name does not get saved. However, profile picture, email and linkedin do.

<img width="741" alt="screen shot 2017-10-17 at 22 07 03" src="https://user-images.githubusercontent.com/7974813/31686860-d133c9b2-b387-11e7-9d73-bd60561be9f5.png">

On second try, the profile gets saved correctly.

**Comment by perissology** [comment]
This is most likely a feathers issue https://github.com/Giveth/feathers-giveth/issues/40

**Comment by satyavh** [comment]
Currently any change on the profile is not saved at all times.

**Comment by perissology** [comment]
@satyavh what do you mean? updates should be saved in feathers

**Comment by satyavh** [comment]
It doesn't for the profile, reproduce:

1. edit profile
2. save
3. reload page
