### ISSUE TITLE
links should preview the dapp

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#771]
When u paste a link to a milestone or campaign, it doesn't give you any visual preview of that page in the DApp! 
<img width="691" alt="Screen Shot 2019-05-18 at 4 04 12 PM" src="https://user-images.githubusercontent.com/38163206/57970839-cdfd0300-7986-11e9-8f80-209c9c64eeee.png">

**Comment by GriffGreen** [comment]
yeah we need a thumbnail for DACs, campaigns and milestones... i think this could be a github bounty

**Comment by GriffGreen** [comment]
or a great issue for a new dev :-D

**Comment by GriffGreen** [comment]
This takes lots of extra work... :( sadly being decentralized with IPFS and adding a preview for twitter is not easy... we might have to add some centralizing features to make that work

**Comment by GriffGreen** [comment]
prerender.io this would be a centralized solution... it will charge us, it hasn't been tested yet, but it could work and its only like $5 a month... 

Webcrawlers don't render javascript, they just grab the metadata from clients that are running on the serverside... we run on the clientside so they can't do that....

**Comment by mroberts10** [comment]
Andre to create test template of prerender.io for a test on the DAPP repo.

**Comment by arbreton** [comment]
Working for campaigns, to be worked DACs and milestones

**Comment by arbreton** [comment]
Campaigns have been working, still to be worked for the pending items

**Comment by papermache** [comment]
@arbreton Any updates?

**Comment by GriffGreen** [comment]
@arbreton might have finished this...

**Comment by papermache** [comment]
@arbreton

**Comment by arbreton** [comment]
Missing previews for DACs and milestones still

**Comment by GriffGreen** [comment]
Would be amazing if we could get the links to show up on twitter... i would say thats the real end goal here :-D

https://beta.giveth.io/campaigns/5f504e7bfb3dbe37aee4e050

**Comment by aminlatifi** [comment]
@arbreton Develop branch has changed extensively, don't forget to merge it to your branch you are working on

**Comment by GriffGreen** [comment]
There is a prerender.io option and a few other centralized solutions.. We will probably need to deploy a server that hosts pictures just for this... or change the routing to feathers....

We can add a share button... there are a few options... every project, milestone and other options should

**Comment by geleeroyale** [comment]
These are different issues! The preview on twitter can be accomplished by adding twitter compatible metadata in the page template header.

The preview for the DApp would need a different service/library but I see that was (at least partly) realized by Andre.

**Comment by mdehghani** [comment]
It's easy! I have used it in some other websites in a while.
To solve the problem we should:

1. Deploy prerender.io service on our servers (https://github.com/prerender/prerender)
2. Create an express server to play a proxy role and add a middleware to dispatch the requests from bots (e.g. twitter, whatsapp, facebook, ...) to our service (based on its User-Agent header)

I did these works and pushed it to a branch named f_771_link_preview branch. Please take a look at it and let me know if it is suitable for this situation.

To run the servers, use the following command instead of `npm start`:
`npm run start-with-prerender`

Then you can use the new version on port 8080 (instead of 3010)

@aminlatifi

**Comment by aminlatifi** [comment]
@mdehghani I tested your pull request but I didn't get expected result. I suggest connecting your local dapp to beta backend and testing it yourself.

**Comment by GriffGreen** [comment]
Push forward with Kay :-D Let's do it!
