### ISSUE TITLE
We need to add a page that says "oops page not found" - Milestone is infinitely loading

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#775]
https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5cd9c5a3e4ee5d18e7bad87d
This milestone of @Danibelle 's has been stuck in perma load not showing anything every time i've tried to open it in the past 24 hours so i can't delegate to it.

**Comment by arbreton** [comment]
Looks like a bugged milestone, an alternative was used to solve this problem?

**Comment by GriffGreen** [comment]
We need to implement a page that shows that this milestone doesn't exist
