### ISSUE TITLE
Donations are taking forever to become completed?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#777]
related to #772 

Its been happening in https://beta.giveth.io/campaigns/5cdf39aee4ee5d18e7bada0c a lot... 

<img width="1202" alt="Screen Shot 2019-05-22 at 1 00 33 PM" src="https://user-images.githubusercontent.com/14945613/58169720-be84ff00-7c91-11e9-987b-b4f831df9be1.png">

I tested it in a different older campaign with ETH and it is also happening under that scenario: https://beta.giveth.io/campaigns/5b94a71490b3c1478f06b42b
<img width="1079" alt="Screen Shot 2019-05-22 at 1 02 46 PM" src="https://user-images.githubusercontent.com/14945613/58169802-f0966100-7c91-11e9-9433-29fa7e550f87.png">

You can see that the transactions for DAI confirmed on the bridge just fine, but the ETH one has an issue: https://bridge.beta.giveth.io/

So I imagine this is something systemic... but there are some weird things going on for ETH vs DAI

**Comment by GriffGreen** [comment]
actually the ETH one eventually confirmed

**Comment by arbreton** [comment]
I have checked this situation with @ElMejorge the transaction was already mined and commited but just didn't updated in the MongoDB, we added the txHash, and changed the status to "Commited" and the mined variable to true as a temporal solution, i will investigate further why it wasn't updated correctly 

Here it should be corrected:
https://beta.giveth.io/campaigns/5cdf39aee4ee5d18e7bada0c

**Comment by arbreton** [comment]
It seems to be that there was a problem authenticating the user and even though we wasn't signed in, the Dapp let the user donate, so when the transaction came through feathers it failed fetching the profile which is the exact same thing that happens sometimes on localhost, I will keep diving into what is causing the authentication problems

> feathers-beta-out.log:2019-05-22 03:05: info: **error: authentication** - Method: create - Chall
enge = P5RpPia1EfCKVmmDORGO
feathers-beta-out.log:2019-05-22 03:06: info: **error: authentication** - Method: create - Challenge = ZSb9MVygy0GX652Ud7h7
feathers-beta-out.log:2019-05-22 03:06: info: users - **No record found for id '0xed08785867B434473f175aEE5018a8747d240EA0'**
feathers-beta-out.log:2019-05-22 03:09: error: **error in the processing looop Error:  is not
a valid ipfs path**
feathers-beta-out.log:2019-05-22 03:09:     at **Function.app.ipfsFetcher.path [as ipfsFetcher]** (/home/deploy/feathers-giveth-beta/src/utils/ipfsFetcher.js:16:35)
feathers-beta-out.log:2019-05-22 03:09:     at **fetchProfile** (/home/deploy/feathers-giveth-beta/src/blockchain/givers.js:9:41)
feathers-beta-out.log:2019-05-22 03:09:     at **addGiver** (/home/deploy/feathers-giveth-beta/src/blockchain/givers.js:49:27)

@ElMejorge , @ewingrj has anyone seen this problem before?, thank you in advance

**Comment by arbreton** [comment]
Gets solved with  #607
