### ISSUE TITLE
Mobile accessible pages (Campaigns, Milestones and general information pages)

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapp#793]
Giveth dApp should be accessible on mobile or any other device. 

**Problem**
A lot of times Campaigns and  Milestones are shared on social media to collect donations but that information cannot be seen if coming from a mobile device.

Basic information about:

- Communities
- Campaigns
- Milestones
- Other informative pages 

should be accessible by default on any device.

Only in case of interacting with the dApp that requires Metamask user should be prompted to continue on Desktop site or use Web3 enabled mobile browsers/apps (Status or other) if possible.

**Comment by arbreton** [comment]
Hello @markoprljic,

Could it be related to https://github.com/Giveth/giveth-dapp/issues/771 ?

**Comment by mroberts10** [comment]
Need to setup an external server. What we can do is setup a separate link.

**Comment by mroberts10** [comment]
@markoprljic are you still experiencing this issue?

**Comment by GriffGreen** [comment]
probably should be closed

**Comment by markoprljic** [comment]
> Hello @markoprljic,
> 
> Could it be related to #771 ?

Yes and no. We want to make all campaign and milestones pages mobile accessible, meaning user can open the page without being blocked by metamask.
It is more related to this issue https://github.com/Giveth/giveth-dapp/issues/620

**Comment by markoprljic** [comment]
> probably should be closed

Nope, I don't think it should. Unless of course, it's not feasible to do at this point. I believe that devs should estimate the effort and we can then decide whether it goes in this dapp version or wait fo 2.0.

**Comment by arbreton** [comment]
Hello @markoprljic 

I think the dapp is already fully accessible to campaigns, dacs and milestones on mobile without metamask are you still experiencing this on your phone?

**Comment by markoprljic** [comment]
> Hello @markoprljic
> 
> I think the dapp is already fully accessible to campaigns, dacs and milestones on mobile without metamask are you still experiencing this on your phone?

Ahhh, it works now. 
I couldn't access the pages when following a link from Twitter. I guess this issue can be closed now.

**Comment by arbreton** [comment]
This got fixed at #802
