### ISSUE TITLE
Conflicting messages on Milestone Create & Edit

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#795]
I got this error message both when I created the Milestone and when I edited it: 

![image](https://user-images.githubusercontent.com/39466970/58790072-3cf86f80-85b5-11e9-8e63-a65703a1b3a3.png)

The videos appear in the Milestone while I'm in edit version, but then when I view it, they are not there.

@arbreton this is like the one we looked at yesterday, where the video does not show/play unless you go into the 'EDIT' zone.

**Comment by arbreton** [comment]
This should be solved now tweaking internal configurations on the ipfs server
