### ISSUE TITLE
Uploading a video file to Milestone Fails

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#796]
Creating a Milestone with a video uploaded from file is not working - if this would work, all the other issues with linking an external video will no longer be an issue!

![image](https://user-images.githubusercontent.com/39466970/58792328-96629d80-85b9-11e9-9457-c9d5208be7a8.png)

![image](https://user-images.githubusercontent.com/39466970/58792279-77fca200-85b9-11e9-9c7f-d41662661e63.png)

**Comment by arbreton** [comment]
related to IPFS issues
