### ISSUE TITLE
Security alert from github

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#811]
what is this?
<img width="660" alt="Screen Shot 2019-06-06 at 11 33 02 AM" src="https://user-images.githubusercontent.com/38163206/59022898-ef972f00-884e-11e9-88e0-fd2de0263c92.png">

**Comment by arbreton** [comment]
Confirming, this is actually not a bug, It's an old dependency on another repository not being used that is now vulnerable, not related to the Dapp.

**Comment by arbreton** [comment]
@ewingrj , would you have permission to this repo?
