### ISSUE TITLE
Reward travis issue #766 get this guys address and put it in the dapp

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#814]
This is the milestone!
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ce2d8182bb8c0257c7b83c5

**Comment by arbreton** [comment]
@GriffGreen, this pull request is already into the dapp, does that solves this issue?

**Comment by arbreton** [comment]
https://github.com/Giveth/giveth-dapp/issues/773

0x039dACca4a447E140d8B29F0652cd844Ea827D1a
