### ISSUE TITLE
User flow for uncapped milestones

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#815]
So @Danibelle  and I are discovering some derps in the user experience of being a maker of an uncapped milestone. 
Dani had to mark [this milestone](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5cdca616e4ee5d18e7bad98b) complete in order to withdraw any money from it. Before, we were exploring this with her [first uncapped milestone](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5c7eccfc27ae4211c836be03): she was able to withdraw funds out of the milestone, and let more funds be donated, and then withdraw again. Great feature! I imagine capless milestones will often be used for work done over a longer period of time being valued/paid intermittently and the maker will withdraw several times throughout. 
So we were expecting this again, and now Dani marked this milestone complete to withdraw one week's pay from it and suddenly I am left unable to delegate further so she can get the second week's pay. The milestone has no donate/delegate button on it and it doesn't come up in options from my delegations page. 
Our questions: 
If this completion is accepted, will she be able to keep receiving funds for it after that? 
If the milestone completion is rejected - will it become delegatable again after that? 
Is there any way for Dani to withdraw multiple different times like described in the experience of her first milestone?

**Comment by lorelei1** [comment]
@markoprljic

**Comment by GriffGreen** [comment]
These are different types of milestones

One has a reviewer and the other doesnt...

1. If this completion is accepted, will she be able to keep receiving funds for it after that?

I doubt it. it will be marked complete.

2. If the milestone completion is rejected - will it become delegatable again after that?

Hell yeah ;-)

Is there any way for Dani to withdraw multiple different times like described in the experience of her first milestone?

She would need to not have a reviewer...

After thinking about the milestones and such... i made a small spreadsheet

it would be great to make different types of "Things" (formerly known as Milestones) and then we can really trim down the options... I see 4 options that if the user makes that one choice, they wont have to choose many other options...

**Bounties:**

Milestone reviewer = yes 
Money goes to...  blank
Funds raised in multiple currencies
No Cap 
Multiple expenses.... no


**Milestone:**

Milestone reviewer = yes 
Money goes to...  Campaign
Funds raised in multiple currencies
No Cap 
Multiple expenses.... no


**Payment:**

Milestone reviewer = No 
Money goes to...  specified address
Funds raised in one currency 
Cap 
Multiple expenses.... no


**Expense:**

Milestone reviewer = No 
Money goes to...  specified address
Funds raised in one currency 
Cap 
Multiple expenses.... yes

I used this spreadsheet for dreaming on this: https://docs.google.com/spreadsheets/d/1BTG_BluAahVGog_R-Ubt2a93POiA84RHU3NqiXaUog0/edit?usp=sharing

**Comment by Danibelle** [comment]
This will be great in the onboarding document. This can be assigned to me.

**Comment by markoprljic** [comment]
I just accidentally found this issue, because I'm not getting notifications when someone mentions me, this is weird and a constant problem I'm having. Off topic: How can I fix this and get notified?

For this issue... I need to wrap my head around it but at a glance reading Griff's suggestion to categorize "Things" looks like a good approach. On the other hand, introducing more options means more complexity meaning we need to clearly educate user what each of the "Thing" does and how it works, that should be very simple and clear. I imagine each of the category to be accompanied by use case scenarios (just a few words or examples) to better illustrate the purpose so that user can relate to one of the options easily and make the most appropriate choice.

After that ... we need to figure out how this will affect the interactions and how we'll structure the UI.

**Comment by Danibelle** [comment]
per chat with @markoprljic we're gonna work on 'decomplexifying' the Milestone Creation process.

Err, make a simple document with a graphic decision flow for creating a Milestone based on type.

And templates.  That automate the process for frequent use cases.

**Comment by papermache** [comment]
@markoprljic @Danibelle has any progress been made here? Moving to Icebox.

**Comment by markoprljic** [comment]
@papermache I believe this issue is related to (and solved) https://github.com/Giveth/giveth-dapp/issues/1214 for which we have approved designs https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth-Design?node-id=2072%3A841&viewport=210%2C424%2C0.08207457512617111&scaling=min-zoom
