### ISSUE TITLE
'ADD' Milestone not working 

### ISSUE THREAD

**Issue by mroberts10** [Giveth/giveth-dapp#818]
'ADD' Milestone not working, but I think its only for campaign managers.  When I use the same account go to something I'm not a campaign manager it will say 'PROPOSE' milestone and it works fine.
<img width="549" alt="Screen Shot 2019-06-10 at 1 53 47 AM" src="https://user-images.githubusercontent.com/4000911/59175206-a67efd80-8b22-11e9-9112-a41595ac0051.png">
<img width="708" alt="Screen Shot 2019-06-10 at 1 53 53 AM" src="https://user-images.githubusercontent.com/4000911/59175207-aa128480-8b22-11e9-8d27-35150d8281f4.png">

**Comment by GriffGreen** [comment]
some thing specific to dapp campaign

**Comment by arbreton** [comment]
This was discussed that the campaign owner was changed manually, this could have something to do with this problem, pending to check DB record integrity.
