### ISSUE TITLE
Stuck milestones

### ISSUE THREAD

**Issue by Joshfairhead** [Giveth/giveth-dapp#819]
So I hit disperse on these a little while back (at least a week) and when checking in on progress I found this screen which seems to be a failure of some sort:
![Screenshot 2019-06-06 at 16.58.05.png](https://images.zenhubusercontent.com/5c362fe2b7d8a251f243bee6/890a3b3f-e6d1-4218-ba9d-b72e6a56ae49)

After some investigation a note is that it's potentially due to the first milestone which has received mixed currency donations.  After that its singular currency donations but they are also stuck. [https://app.zenhub.com/files/98920496/79a0cea9-ad8f-447d-90d9-1d39dd853167/download](https://app.zenhub.com/files/98920496/79a0cea9-ad8f-447d-90d9-1d39dd853167/download)

Milestone one (mixed currency): https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5cd059162f70601995ce89c9

Reward DAO milestone March: https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5cc5ef48cf48770f67ee86b4

Reward DAO milestone April: https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5ccc9addcf48770f67ee8727

**Comment by arbreton** [comment]
Reviewing the donations on this milestones they successfully made it to the bridge but they don't appear on the bridge according to @bowensanders, what would be the next steps on this? @ewingrj , @mroberts10

**Comment by bowensanders** [comment]
<img width="501" alt="Screen Shot 2019-06-14 at 3 27 36 PM" src="https://user-images.githubusercontent.com/27023908/59542108-2d343180-8eb9-11e9-93fe-44b9b806a272.png">

Is it possibly related to the fact that in this example there is no recipient address??

**Comment by bowensanders** [comment]
That was from THIS milestone: https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5cc5ef48cf48770f67ee86b4

**Comment by Joshfairhead** [comment]
Damn, quite possibly some idiocy my end there (tho I feel like I filled
that in) but the problem remains due to an AWOL edit button... (i.e. non
existent)!

**Comment by bowensanders** [comment]
I believe that it is missing because you are not the reviewer and or the milestone has been accepted as complete


---- On Fri, 14 Jun 2019 16:49:56 -0700 notifications@github.com wrote ----


Damn, quite possibly some idiocy my end there (tho I feel like I filled
that in) but the problem remains due to an AWOL edit button... (i.e. non
existent)!

**Comment by arbreton** [comment]
I think i can apply a quick fix temporarily for the funds to go through, also when the funds are still not paid the milestone should not go to completed, i will need to check on that seems to be a UI problem

**Comment by arbreton** [comment]
I will just need your wallet address @Joshfairhead thank you!

**Comment by arbreton** [comment]
@Joshfairhead, Everything should be ok now Josh, please set recipient address before marking complete everything should be good to go.

I'm also uploading a fix which would prevent users to mark complete without setting a recipient address first.

**Comment by Joshfairhead** [comment]
Cheers Andre, unfortunately its still not working for me!

The UI has reverted to normal, however clicking edit throws the error
screen which stops me from editing the recipient address.

This is the address I'd use FYI :)
0xf89AD13EfF9d9d1cd5768dFf658C68A8108D38C5

Cheers!
ᐧ

**Comment by Joshfairhead** [comment]
However I did find the big green "set recipient" button which allowed me to
input the address.

Clicking "Mark complete" however throws an error now instead. It pops up
the window asking for a note, I add the note but then it fails. I have
tried this from "My Milestones" and from the milestone directly in several
ways.
ᐧ

**Comment by arbreton** [comment]
@Joshfairhead you should be able to collect now on your milestones tab, please confirm thank you! have a nice weekend

**Comment by Joshfairhead** [comment]
---
Mobile: +44 (0) 7412090234
JoshAFairhead.com <http://www.JoshAFairhead.com>
Ask the Loomio!?
<https://www.loomio.org/join/group/2dzzxELw5H6STeR55EMp2F79/>

ᐧ

**Comment by Joshfairhead** [comment]
Nice,

So looking at https://bridge.beta.giveth.io/ it seems that we are golden.
Thanks Andre, you da man!
ᐧ

**Comment by GriffGreen** [comment]
Adding fix to make it so you can't mark it complete
