### ISSUE TITLE
DAC Delegations should only list Campaigns and Milestones

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#82]
For the MVP we agreed that delegations from DAC can only go to Campaigns or Milestones. 
<img width="844" alt="screen shot 2017-10-18 at 17 30 45" src="https://user-images.githubusercontent.com/7974813/31727534-19186240-b42a-11e7-87f2-8b66a81d72bd.png">

I propose that the milestones are grouped within the campaigns and can be expanded on click.

**Comment by satyavh** [comment]
And as the screenshot shows, it only list campaigns and milestones :-)

Your requesting an UX pattern change based on....? (not to mention a hard one).

**Comment by vsimetka** [comment]
Sorry wrong screenshot. Tried now with donation do DAC.

<img width="969" alt="screen shot 2017-10-22 at 21 27 25" src="https://user-images.githubusercontent.com/7974813/31865480-d6587f32-b76f-11e7-8c82-4f47cdca244a.png">

I believe @Boban and @YoungYeezy were real users who pointed this one out.

**Comment by satyavh** [comment]
Ok will change
