### ISSUE TITLE
'Saved milestone' gets in the way of making diff milestones in diff campaigns

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#822]
User confusion! I think there's been issues abt this before, but...
There should be a tab for "Milestone Drafts" or something in My Milestones where you can access several different drafts at any time. I might be drafting a milestone for Comms and then need to draft one for a charity project completely unrelated.

Problem: Right now, I can only really "save" one milestone at a time: if I'm working on a "Mothers for the Future" milestone in the SWEAT campaign, when I go to make a new self delegation milestone in the Unicorn campaign, all the info from my Mothers for the Future milestone comes up autofilling the new milestone page. This is SUPER awkward and confusing:

Am I making my milestone in the wrong campaign? If I make the unicorn milestone will I lose all my work on the Mothers for the Future milestone? Do I have to choose one milestone to keep in draft form at a time?
All these questions run thru the user's head.

**Comment by arbreton** [comment]
Solution needs to be ability to create multiple drafts that would be based by campaign

**Comment by ElMejorge** [comment]
Issue related to #782

**Comment by arbreton** [comment]
Being improved partially on #853
