### ISSUE TITLE
error when donating to the dapp 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#823]
Following the steps to donate to the art car as described by @Danibelle / @GriffGreen , I got the below error after the first transaction in [this Milestone](https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7) 
 
I still had to do the second transaction and luckily this did pop up in my metamask (not as a pop-up but I saw the '1' and signed this one too. 

![image](https://user-images.githubusercontent.com/6533925/59206623-a07e3080-8ba5-11e9-86d3-8738656216b1.png)

After confirming that transaction I got the confirmation (top right) that my transaction went through, this is however not ideal. Most people will click away if they see the error and not sign that second transaction. 

![image](https://user-images.githubusercontent.com/6533925/59206578-85132580-8ba5-11e9-8ff0-505d6738dc4f.png)

**Comment by arbreton** [comment]
Hello @krrisis is this the first time this has happened to you,
I sense that this might be an uncommon bug hard to catch since doesn't seem to replicate easily, i will get more in depth in the donation process to follow the path in where this problem can be caused, if anyone can reproduce this error, please comment below

**Comment by GriffGreen** [comment]
I also couldn't replicate it....

**Comment by arbreton** [comment]
After some investigation seems to be that the cause could have been an intermittent connection to the web3 api, this was during the airdrop day, i will a apply preventive fixes in case this happens again

**Comment by krrisis** [comment]
Great! Yeah it might have been linked to that. Can't replicate it myself in the sense that I normally don't donate to giveth except for this one time :) So I think you can close this one. thx!
