### ISSUE TITLE
"Milestone Proposed" Email to Campaign Manager 

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#824]
Here's what it says:
![image](https://user-images.githubusercontent.com/39466970/59215271-72d1c100-8b7e-11e9-9dca-eadf00becdd8.png)

Not only does the variable for what's being requested need to be corrected so it displays the selected data, but we can do better with our words too..  Suggestion below!

Instead of:
A milestone Adding account to whishlist for NaN ANY_TOKEN has been proposed for your campaign to the campaign RewardDAO . If you think this is a great idea, then please approve this milestone within 3 days to add it to your campaign. If not, then please reject it.

More like:
The Milestone "Adding account to whishlist" for "value" has been proposed to the "RewardDAO" Campaign. If you think this is a great idea, then please approve this Milestone within 3 days to add it to your Campaign. If not, then please reject it with comment.

**Comment by mroberts10** [comment]
Assign to Nepalis

**Comment by horus2021** [comment]
I update the text based on @Danibelle suggestion.
@aminlatifi see the following pull req.
https://github.com/Giveth/feathers-giveth/pull/207
