### ISSUE TITLE
Milestones don't load in campaign pages

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#825]
This problem has been going on for a long time. When you load a campaign's page, it shows no milestones. It takes several refreshes often to get any to appear.

**Comment by GriffGreen** [comment]
its just really slow usually right? I guess we just need to paginate the Milestones

**Comment by mroberts10** [comment]
There is no pagination, so is the campaign has lots of milestone then it can take a long time.

**Comment by GriffGreen** [comment]
medium difficulty task....

**Comment by arbreton** [comment]
medium low priority less than making transfering campaign ownership

**Comment by aminlatifi** [comment]
In campaign page, milestone grid component replaced by native html-css alternative. I also changed milestone and donation fetch batch size to moderate sizes (They where 50 for both, I changed to milestone:12 and donations:5). 
I feel these numbers are good enough and user can load more if needed.
