### ISSUE TITLE
"Delegated Donation" Take Action Email needs grammatical correction

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#826]
**Please change** "You're donation" to "Your donation"
![image](https://user-images.githubusercontent.com/39466970/59216081-7bc39200-8b80-11e9-9f74-b2a9f734f0d4.png)

Also in the text below the image, where it says:
The dac Unicorn DAC has proposed a delegation of
250 DAI
from your donation to dac Unicorn DAC.

Please put the letters DAC in ALL CAPS (every time, every where ;) )

**side note** we should NOT include the letters DAC in the name of our DAC's going forward.  @lorelei1  - I think this is another nod toward changing the name of Unicorn DAC.

**Comment by mroberts10** [comment]
Nepalis
