### ISSUE TITLE
Donation made to Campaign not showing up 

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#827]
I made a donation of 50 dai to this campaign:
https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7

and it's not showing in the campaign from either the donator (0xB83b50335cF37DfbDf0f8Ca0E8717a536cc4b8ff) or the giver I donated under (0xac446dD360716ACef4E930612dCb1f652A98d750) as i made the donation in the address of the Security Guard: 

the relevant etherscan links are here, and it shows up as a donation on the bridge:
https://etherscan.io/tx/0xa047383bf5613ec1d7aab50f87d0510b075b178e01f499842bf8c9cd28405073

https://etherscan.io/tx/0x46e25ec9afa02f67ec145ca27bc0b86472ccc08c82518a3ec1b5bac33523fad2

The donated 50 DAI has been removed from my account as seen in the above etherscan links.

**Comment by GriffGreen** [comment]
may have been related to ethereum congestion... but there was also an issue with anon users donating
