### ISSUE TITLE
"Time to Review" Campaign Owner Email text edits

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#828]
Please capitalize the words Milestone, Campaign, and Milestone Owner everywhere they appear.
![image](https://user-images.githubusercontent.com/39466970/59216675-b24ddc80-8b81-11e9-8657-3140bdaf42e0.png)

**Comment by mroberts10** [comment]
nepalis

**Comment by horus2021** [comment]
Hey @aminlatifi  see my fix at
https://github.com/Giveth/feathers-giveth/pull/210

**Comment by horus2021** [comment]
Hey @aminlatifi I have fixed this in below
https://github.com/Giveth/feathers-giveth/pull/211
