### ISSUE TITLE
Status Messaging repeats for next actor with previous comment

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#834]
When I leave a comment as Campaign Manager to accept the proposed Milestone, the comment is then repeated as if it's from the Milestone Creator.. you can see here I provided detailed comment upon accepting the Milestone..  for some reason it shows my same comment under Josh's name for  Request Review:
![image](https://user-images.githubusercontent.com/39466970/59550887-18b37000-8f71-11e9-8c0f-5260b3e5ab61.png)

Then it does the same thing, where I commented to accept Milestone Completion, I just got an alert that Josh rejected the completion and it shows my same comment under his name:

![image](https://user-images.githubusercontent.com/39466970/59550845-65e31200-8f70-11e9-8901-8003d08b0224.png)

**Comment by GriffGreen** [comment]
could be a special case... ? Was @arbreton doing something that would make this happen?

**Comment by GriffGreen** [comment]
strange behavior... very likely to not be an issue
