### ISSUE TITLE
mark complete not triggering any real transaction

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#835]
made a screenshare
https://youtu.be/Vq4FRAjRK-8

**Comment by mroberts10** [comment]
likely a cache issue - something is stuck - could be hard to replicate.  - Griff reset metamask - gets rids of all the transactions but speeds up metamask (signed into different account and signed back)

**Comment by GriffGreen** [comment]
might be an issue from reseting metamask @lorelei1 can you try again?

**Comment by papermache** [comment]
@lorelei1 can you try again and give us an update? Maybe the metamask bug has been updated?
