### ISSUE TITLE
Adding a photo of a receipt ruins the scroll function

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#836]
I uploaded a pic of a receipt on a milestone and as soon as the picture is there, I can no longer see all the fields of the receipt/item box to be filled in. I wanted to fill in the name of this receipt after uploading the pic (cuz i don't know what to name it until i see the receipt) but now I can't see the name field, i can't scroll up to it, and i seemingly can't scroll at all. it's cutting off a bit of the bottom too. 
made a screenshare
https://youtu.be/FoBsHAekAT0

**Comment by GriffGreen** [comment]
Scroll issue... weird bug

**Comment by mroberts10** [comment]
Could assign to nepalis
