### ISSUE TITLE
Allow delegating money from Donate button in Campaigns and Milestones

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#84]
If you are a delegate and you have money to delegate, clicking on the Donate button (or GivETH) should offer you the option to delegate the DAC money.

**Comment by satyavh** [comment]
In DataRoutes we reactively keep dacs, campaigns and milestones in state.
We just need to clone & transform those and pass as props to the subroutes there, to be able to use them in the DelegateButton

**Comment by satyavh** [comment]
However, it is not needed at this stage :-)

**Comment by perissology** [comment]
This should also be available to givers that have un-delegated pledges.

**Comment by vojtechsimetka** [comment]
Fixed in 58831be7eeaca698233ed5afbf8f4764fdec86e4
