### ISSUE TITLE
Difficult to find ReceiverIDs in the DApp

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#841]
If you want to donate via the smart contracts it is difficult to do without the receiverID... I usually back it out by donating via the UI and then checking the data on the transaction, it would be great if the ID was just listed somewhere hidden on the page... maybe in the bottom corner or something... :-D

**Comment by arbreton** [comment]
@GriffGreen I gathered the data around this, should be an easy modification i have this as a result, just wanted to check if the margins, font size and colors are ok, i see this more like an easter rather an important display i think it looks good it's small on the bottom right corner, it will be available in all milestones, campaigns and DAC accross de Dapp

<img width="966" alt="Screen Shot 2019-06-18 at 5 30 18 PM" src="https://user-images.githubusercontent.com/12836187/59728549-6806d400-91ef-11e9-854f-22977a254826.png">
