### ISSUE TITLE
Create an option to donate to Giveth when they donate to a cause

### ISSUE THREAD

**Issue by mroberts10** [Giveth/giveth-dapp#845]
We talked about this at the retreat.  It would be great to allow people to make a small percentage of their donation to Giveth.

**Comment by GriffGreen** [comment]
Yeah!

**Comment by GriffGreen** [comment]
the pop up page saying thank you for donating could come up with a donate button for the Giveth DAC :-D and a nice message that says "Please donate to Giveth!"

**Comment by GriffGreen** [comment]
After every donation, we should have a pop up that looks like this:

<img width="542" alt="Screen Shot 2020-06-17 at 5 53 49 PM" src="https://user-images.githubusercontent.com/14945613/84920512-8d107a00-b0c3-11ea-88a7-dfa05e76d38d.png">

That says 

Thank you! 

Would you like to support Giveth as well?

[Donate] <---- button that makes a donation to the Giveth DAC

**Comment by GriffGreen** [comment]
<img width="556" alt="Screen Shot 2020-07-01 at 4 55 01 PM" src="https://user-images.githubusercontent.com/14945613/86258956-b5b46b80-bbbb-11ea-8768-8c2de9caf82c.png">

Change the button names!
Cancel -> No Thanks
OK -> Support Giveth
