### ISSUE TITLE
Add button "Create new Campaign"

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapp#849]
When you go to Campaigns and have an empty state page, add button to Create new campaign.
![Image 2019-06-21 at 1.35.23 PM.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/736f7dda-fd20-46a9-9895-98c3f0277623)

Additionally, when there are campaigns listed but the same button TOP RIGHT above the campaigns list.

**Comment by Danibelle** [comment]
You must be whitelisted for these buttons to appear for you in Beta.
