### ISSUE TITLE
In Campaign detail, list all the DACs which relate with it

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#85]
Right now we are showing what Campaigns are linked to a DAC in the DAC.

<img width="906" alt="screen shot 2017-10-18 at 17 45 36" src="https://user-images.githubusercontent.com/7974813/31728283-2e7549b2-b42c-11e7-8e8e-cab25ed15452.png">

However, there is no such link from the Campaign.

**Comment by ojones** [comment]
@vsimetka So there would be a DACs list and Milestone list. Sounds crowded.
