### ISSUE TITLE
Add a button to "Create your Community"

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapp#850]
Communities empty state page, add button to Create your Community. 

![Image 2019-06-21 at 1.39.40 PM.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/faa94f87-ee6e-4d63-8b9b-ed74434cb0f3)

**Comment by Danibelle** [comment]
This is necessary functionality in Beta.  You must be Whitelisted in order to create Communities and Campaigns.
