### ISSUE TITLE
Milestone does not disburse

### ISSUE THREAD

**Issue by MorganGR** [Giveth/giveth-dapp#856]
The below milestone is producing the following error.
![ClickDisburseMessage](https://user-images.githubusercontent.com/34093087/60102605-ee726700-9755-11e9-99bf-3fcdd4300596.PNG)
![ClickYesWithdrawalMessage](https://user-images.githubusercontent.com/34093087/60102606-ef0afd80-9755-11e9-85ff-3db7b38d5a1f.PNG)

Milestone:
https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5ca542f7dd7b2c0bf14ed740

**Comment by arbreton** [comment]
Hello @MorganGR, for some reason someone archived the milestone, it should be working fine now, can you try to disburse again? keep me posted!

**Comment by arbreton** [comment]
(Archiving should not prevent users from collecting money)

**Comment by mroberts10** [comment]
The milestone has been moved out of the archive so, so MorganGR can be paid, however, the larger issue that milestones with fund in it that have not be paid, you should be still be able to archive the milestones however, the individual should still be able to be paid.
