### ISSUE TITLE
Allow DACs to add related Campaigns

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#86]
Right now, linking DAC and Campaign is only possible from the Campaign side. It makes even more sense to link the Campaigns from DAC as that can provide Givers with and idea to which projects would their money go.

**Comment by ojones** [comment]
I see the tension, but don't think adding direct coupling from DAC is the solution. We should be able to see the Campaigns a DAC supports without the DAC owner needing to edit data.

**Comment by vojtechsimetka** [comment]
This has changed. Campaigns and DACs are now linked through money flow
