### ISSUE TITLE
"Reject" should be "Reject Completion"

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#860]
<img width="911" alt="Screen Shot 2019-06-26 at 10 12 05 AM" src="https://user-images.githubusercontent.com/38163206/60200419-ecaeaf00-97fa-11e9-9ab0-3d785edbe0d7.png">
It's too vague when i go to the milestone and it gives me the option to reject it - that makes me think i would be denying this person's work on the milestone overall, when in actuality the action of rejecting the milestone means the funding isn't complete yet.

**Comment by arbreton** [comment]
Assigned to Amin
