### ISSUE TITLE
Reject Completion won't work

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#861]
<img width="841" alt="Screen Shot 2019-06-26 at 10 14 24 AM" src="https://user-images.githubusercontent.com/38163206/60200792-aad23880-97fb-11e9-89ec-8c70eff380e6.png">
Tried again and again, refreshed, tried again, still this.

**Comment by lorelei1** [comment]
weeeeird - @Danibelle says it worked anyways despite always showing this message!

**Comment by arbreton** [comment]
This is very weird @lorelei1, ill see if i can check into this onebefore we prioritize on monday, seems to be a problem with cache, try deleting the cache of the browser see if it helps

Couldn't replicate it yet, seems ok now

**Comment by GriffGreen** [comment]
had trouble replicating...
