### ISSUE TITLE
Delegating from within a Milestone froze and didnt work

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#864]
<img width="1197" alt="Screen Shot 2019-07-02 at 5 20 11 PM" src="https://user-images.githubusercontent.com/14945613/60524902-b89d2780-9ced-11e9-9d75-61132006e41f.png">

It weird, i didnt get an error notification either... it just froze.

I was trying to delegate from the Commons Stack Prelaunch Campaign to Jeff's milestone https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d153261994eac53adc8f446

**Comment by GriffGreen** [comment]
still running into this
<img width="1275" alt="Screen Shot 2019-07-10 at 7 55 48 PM" src="https://user-images.githubusercontent.com/14945613/60992475-dfdaa100-a34c-11e9-91bd-8e0d40ae0d9d.png">

**Comment by arbreton** [comment]
This should be a good hotfix!, im checking on it right now

**Comment by arbreton** [comment]
Should be working now @GriffGreen, keep me posted

**Comment by GriffGreen** [comment]
<img width="1216" alt="Screen Shot 2019-07-15 at 7 53 23 PM" src="https://user-images.githubusercontent.com/14945613/61237243-58b96e80-a73a-11e9-95b1-cf320cd49bf4.png">
<img width="1260" alt="Screen Shot 2019-07-15 at 7 48 48 PM" src="https://user-images.githubusercontent.com/14945613/61237244-58b96e80-a73a-11e9-94e4-78c08af56286.png">
<img width="1245" alt="Screen Shot 2019-07-15 at 7 48 19 PM" src="https://user-images.githubusercontent.com/14945613/61237246-58b96e80-a73a-11e9-8813-4bafc8011e12.png">

The bug is still happening

**Comment by GriffGreen** [comment]
it worked one time tho... then it wouldnt even work for 10 dai

**Comment by arbreton** [comment]
This is very strange, line 280 at DelegateMultipleButton.jsx is not synced with the newest codebase @GriffGreen, what happens is since the Dapp is running on clientside, most likely you still have an older version of the dapp on your browser stored.

Please clean cache and close your browser to totally refresh the codebase it should be working perfectly now 👍

**Comment by arbreton** [comment]
Hold on you are right, newest code is not released on netlify, checking on that right now

**Comment by arbreton** [comment]
I found the problem!, cache got stuck on netlify,  the hot-fix got stuck on deployment 3 days ago! </3, newest version of the dapp is LIVE now! 

https://beta.giveth.io/,

Keep me posted @GriffGreen
