### ISSUE TITLE
Uncapped milestones no longer say "This milestone is collecting funds in ETH"

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#866]
On regular, capped milestones its really easy to see if a milestone is raising in DAI or ETH. Now, when i try to delegate to [Marko's redesign milestone](https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5cf1791f8182665680873f7d), it takes some detective work to find out its only accepting ETH. I had to go thru the process of delegating and not being able to pull up the milestone when typing it in, then testing with someone else's eth donation. 
There should be some sort of indicator if a milestone is limiting which currencies it accepts, even if the amount raised is not limited.

**Comment by arbreton** [comment]
I agree there should be an indicator on uncapped milestones for this to keep consistency!, how the indicator from capped milestones look like @lorelei1?, thank you!

**Comment by mroberts10** [comment]
Need some indicator that says something 'like only raising ETH'

**Comment by mroberts10** [comment]
So add some text into the detail section that says what types of currency are accepted for donations.

**Comment by GriffGreen** [comment]
<img width="492" alt="Screen Shot 2019-07-08 at 7 37 55 PM" src="https://user-images.githubusercontent.com/14945613/60830634-ec79c080-a1b7-11e9-8366-dab2099889af.png">

**Comment by GriffGreen** [comment]
I think the easiest way to do this is to just modify the "Amount Donated" text.

The amount of crypto that has been donated to this Milestone
This milestone accepts [only DAI, only ETH, DAI or ETH].

We should also have some sort of code that stops us from having to deal with changing this when we add more currencies.

**Comment by GriffGreen** [comment]
analyzing this i also noticed that we could place this info in the cards in the front
<img width="768" alt="Screen Shot 2019-07-08 at 8 09 21 PM" src="https://user-images.githubusercontent.com/14945613/60833667-0c60b280-a1bf-11e9-8d0c-aee5e05d6751.png">

If there is no cap, the card could say in the middle "Accepting DAI" "Accepting ETH" or "Accepting ETH & DAI"

**Comment by GriffGreen** [comment]
Ok!!! I found what Lorelei was talking about! THIS IS WHAT WILL SOLVE THE ISSUE.

<img width="1204" alt="Screen Shot 2019-07-08 at 9 03 35 PM" src="https://user-images.githubusercontent.com/14945613/60835632-edb0ea80-a1c3-11e9-8ce5-7940ef5c1244.png">

She wants us to have, a line at the top where it says 

"Amount requested: 4.38165366 ETH" for capped milestones... 

she wants uncapped milestones to say: 

"This milestone accepts [only DAI, only ETH, DAI or ETH]."

This will solve this issue, the other pieces above are bonus points @aminlatifi  ;-D
