### ISSUE TITLE
DACs should agree to be related with a Campaign

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#87]
Relating DAC and Campaign is up to the Fundraiser of the Campaign and the DAC has no say in the process. There needs to be some approval process from the DAC. (and from Campaign if the DAC can link itself with Campaign)

**Comment by ojones** [comment]
Yeah this direct coupling should be removed from Campaigns as well. These relations should not be explicitly included as part of the Campaign entity. Rather relations should be shown from histories of transfers.
