### ISSUE TITLE
We have a limitation on the DApp of using metamask for all things rinkeby

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#870]
I thought about "Connect Wallet" or "Enable Wallet" but open to suggestions!

**Comment by krrisis** [comment]
Both sound fine to me!

**Comment by markoprljic** [comment]
"Sign in" and popup to select wallet + information to change to Rinkeby network.

**Comment by GriffGreen** [comment]
now says "please unlock metamask"
