### ISSUE TITLE
There should be a status update once a payment happens

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#874]
<img width="663" alt="Screen Shot 2019-07-06 at 12 19 01 AM" src="https://user-images.githubusercontent.com/14945613/60747372-03849c80-9f85-11e9-9229-e48a5753ad5d.png">
I withdrew some funds and I would expect some way to express this on the screen... i status entry might be a good way to do it...?

**Comment by arbreton** [comment]
This milestone seems to have an odd problem, the status updates i'm pretty sure they should show up, must be something to do with data corruption but we need to identify what exactly happened, i can check on this with the milestone id, thank you!

**Comment by mroberts10** [comment]
Recipient actions don't show up such as paid outs. This should be added to the status updates.

**Comment by arbreton** [comment]
*also archived status changes

**Comment by aminlatifi** [comment]
Working on it.

**Comment by aminlatifi** [comment]
Functionality like this is implemented 
![Screenshot from 2019-09-04 17-48-18](https://user-images.githubusercontent.com/5684607/64347547-5e7c5380-d009-11e9-8954-7438740e8deb.png)
