### ISSUE TITLE
Accepting a proposed milestone sometimes creates a duplicate 

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#877]
Has happened once at #876, might investigation of the needed steps to replicate, probably something related with the process on updating the status of milestones on feathers

**Comment by mroberts10** [comment]
Might be related to internet connectivity.

**Comment by arbreton** [comment]
Happened to @bowensanders aswell today

**Comment by arbreton** [comment]
Need atomic transactions, need a prevention system for duplicates on low connectivity

**Comment by arbreton** [comment]
WIP on #1029
