### ISSUE TITLE
Starting a Campaign from DAC

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#88]
If DACs are raising money from problems and Campaigns are solving them, there should be an option to start a Campaign directly from DAC detail page.

**Comment by ojones** [comment]
While it would be kinda cool, this doesn't sound like a great idea. DACs and Campaigns should not be explicitly coupled.

**Comment by vojtechsimetka** [comment]
There is no direct coupling between DACs and Campaigns this does not make sense.
