### ISSUE TITLE
Pasting and scrolling on quill improvements

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#881]
A fix to #769 has been made but still we should be able to track cursor position as suggested on the thread to keep the user focused on what he is writing at all times and prevent him from scrolling wherever he is pasting

The quill box on edit milestone / campaign or DAC doesn't limits it's size and grows infinitely, that could be limited and it could help to this scenario

**Comment by GriffGreen** [comment]
Nice!

**Comment by GriffGreen** [comment]
If you don't figure out this issue quickly... please don't let it distract you... it hasnt been reported as an issue for over a year.
