### ISSUE TITLE
When a milestone is archived the status update doesnt show anything

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#883]
In general, we could be more verbose/prolific about status updates in general, but this is just one that we missed updating... related to 

https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5ca542f7dd7b2c0bf14ed740

and #856

**Comment by arbreton** [comment]
Could this be related to what you have worked on @aminlatifi?, is it fixed?

**Comment by aminlatifi** [comment]
> Could this be related to what you have worked on @aminlatifi?, is it fixed?

@arbreton I have not worked on Status Update. I am working on #874 now, it's related to Status Update. After I will come to this one.
