### ISSUE TITLE
Delegation hangs when using button in Milestone Header

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#890]
This might be related to [Issue 674](https://github.com/Giveth/giveth-dapp/issues/674) ..

Delegating from RewardDAO, it hangs when I use the Delegate button in Milestone Header for this [Milestone of Frederik's](https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5d279eeb67f1fe662d8ceeb2).  I hit close, refreshed my connections and tried again, same hanging.

Went to My Delegations and chose this same Milestone, and the delegation went through successfully.

**Comment by arbreton** [comment]
Hello @Danibelle, could it be related to #864?, uploading a hot fix now to beta, it corrects this problems
