### ISSUE TITLE
Milestone shows Paid but no donation or delegation?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#898]
See this Milestone: https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424/milestones/5d09e5beaad0322f5aeea0e1

Super weird?
![image](https://user-images.githubusercontent.com/39466970/61235087-415a9100-a6fa-11e9-87d5-817019de6cba.png)

**Comment by arbreton** [comment]
Was this milestone already received by @aminlatifi @Danibelle?, it seems to be that the archive feature is not working correctly, it is marked as archived, but no donations or anything

**Comment by aminlatifi** [comment]
> Was this milestone already received by @aminlatifi @Danibelle?, it seems to be that the archive feature is not working correctly, it is marked as archived, but no donations or anything

No, it isn't. Actually, I have paid for June last time instead of May. I will be paid for May this month :-). @Danibelle know more details.

**Comment by arbreton** [comment]
So this milestone should be active/still ongoing right @aminlatifi, @Danibelle?

**Comment by arbreton** [comment]
This milestone needs to be inprogress still

**Comment by arbreton** [comment]
switch june and may amounts

**Comment by arbreton** [comment]
@aminlatifi, @Danibelle, the milestone is in progress and is uncapped
