### ISSUE TITLE
Error on Committing from My Donations

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#899]
Proposed Donations are just spinning  -- Commit and Reject buttons show up but error on choosing to Commit:

![image](https://user-images.githubusercontent.com/39466970/61249532-1896c380-a71b-11e9-82a0-cb0c44ef503e.png)

**Comment by arbreton** [comment]
Is this still happening @Danibelle ?

**Comment by arbreton** [comment]
Just checking is it still happening?
