### ISSUE TITLE
rinkeby.giveth.io server down

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#904]
rinkeby.giveth.io server was down, websocket interaction and donating not working properly,

**Comment by arbreton** [comment]
Due to disk space limitation, service got shutdown, restarted service, server is back up

**Comment by GriffGreen** [comment]
Still not working, :-(

**Comment by arbreton** [comment]
Seems to be an intermittent issue, we will review this situation on a meeting with @geleeroyale, @ElMejorge, and @bowensanders to status alerts software and to investigate further

**Comment by arbreton** [comment]
@23/07/19 11AM PST

**Comment by GriffGreen** [comment]
https://beta.giveth.io/profile still not sending Rinkeby ETH :-(

**Comment by arbreton** [comment]
@GriffGreen i tested it just now! it's working, it takes some time tho! 

What i did is i created a new metamask account, got into profile, sign the transaction, 0.1 eth came after 1 minute

Affected accounts that didn't received 0.1 eth sadly they remain affected

**Comment by GriffGreen** [comment]
ok cool... so really new accounts, accounts that have never been seen work... old accounts that have been seen before but sent their ETH away don't... this is an acceptable issue ;-D
