### ISSUE TITLE
Make the default donation DAI for all campaigns

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#906]
<img width="1069" alt="Screen Shot 2019-07-22 at 7 55 56 PM" src="https://user-images.githubusercontent.com/14945613/61653519-cb869480-acba-11e9-9c27-603c2d0778de.png">

**Comment by GriffGreen** [comment]
I think making DAI the default all the way thru makes sense.... DAI is used 90% of the time

**Comment by jamespfarrell** [comment]
@arbreton - this seems to have been opened a while ago, and remember from the last call you are working on a couple of bigger issues. Would you like me to take this off your hands?

**Comment by arbreton** [comment]
@jamespfarrell, exactly as you said currently focused on another issue, feel free to do that, would be amazing!

**Comment by jamespfarrell** [comment]
@arbreton I don't seem to be able to assign this issue to myself.

**Comment by GriffGreen** [comment]
This is sooooo exciting @jamespfarrell !!! :-D

**Comment by aminlatifi** [comment]
This issue should be closed?

**Comment by arbreton** [comment]
To be discussed
