### ISSUE TITLE
Donation Stuck on DECENTRAL Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#912]
https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33

![image](https://user-images.githubusercontent.com/39466970/61911205-5c987e00-aefc-11e9-8149-a7409eabb136.png)

[Etherscan Tx Hash](https://etherscan.io/tx/0x15aa5e37043e3d0cdc95f1edb120add7afa24eb455b7ed10684056dc6860e4a3) shows Fail

Kevin Chu - There is one completed 800DAI Transaction from him already in the Campaign, these two have the same timestamp..

**Comment by arbreton** [comment]
I investigated this one Dani, There seemed to have a transaction failure but actually this one succeeded, it seems that in the end 2 transactions were made, the other conflicted with the database causing an infinite loop, but the funds were received ok

https://etherscan.io/tx/0x4fc0b183162666aa1f223a1afb1ff46df526b7955c115642f5d796fd8349d859

we need to try to find a way to reproduce so we can investigate further and it doesn't happen again

**Comment by arbreton** [comment]
Did he made 2 donations of 800? or just 1?

**Comment by Danibelle** [comment]
it does look like 2!  I've emailed a request for details..

**Comment by Danibelle** [comment]
He made two, because the first one errored and he couldn't cancel it.  So just made a second one which was successful.

**Comment by arbreton** [comment]
Need atomic transaction system

**Comment by arbreton** [comment]
WIP at #1029
