### ISSUE TITLE
Cannot Donate to campaign?!? Allowance needs to be set to 0 before donating

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#913]
Trying to send 1000 dai to 
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e
<img width="571" alt="Screen Shot 2019-07-26 at 9 20 00 PM" src="https://user-images.githubusercontent.com/14945613/61976175-5634ff80-afeb-11e9-9059-0827103655c5.png">
<img width="1146" alt="Screen Shot 2019-07-26 at 9 19 39 PM" src="https://user-images.githubusercontent.com/14945613/61976177-5634ff80-afeb-11e9-86f6-8074936bb371.png">

**Comment by arbreton** [comment]
There seems to be a bigger problem with the allowance that needs to be investigated !

**Comment by GriffGreen** [comment]
yep not as big of an issue as i thought

**Comment by arbreton** [comment]
Allowance set for DAI TBW

**Comment by arbreton** [comment]
Has this happened again @aminlatifi ?

**Comment by aminlatifi** [comment]
It has been fixed by new implementation
