### ISSUE TITLE
Remove functionality for a Campaign Manager to Transfer Ownership

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#916]
As time passes there are leadership shifts that have to happen! 

Campaigns should be able to change who holds the keys... this should also happen with DAC's as well

**Comment by arbreton** [comment]
To be worked, contract direct interaction instead of manual

**Comment by papermache** [comment]
@arbreton any updates?

**Comment by arbreton** [comment]
hide the campaign owner field so it doesn't get confused
