### ISSUE TITLE
Milestones not showing correctly in DECENTRAL Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#917]
we have a [Milestone](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d3646511038ff0d20b0b5c5) (No Reviewer), it appears in My Milestones for me as Campaign Owner, and for the Milestone Proposer/Recipient - but it is not showing in the Campaign itself.  It appears to have been marked complete before the delegation transactions completed - sooo, the delegations didn't go through but I can't do anything with it.

![image](https://user-images.githubusercontent.com/39466970/62072261-ebaadc00-b203-11e9-9cf3-a0854004690e.png)

![image](https://user-images.githubusercontent.com/39466970/62072317-04b38d00-b204-11e9-8f99-aac600491750.png)

![image](https://user-images.githubusercontent.com/39466970/62072427-3fb5c080-b204-11e9-8ab8-08354d29c2e8.png)

![image](https://user-images.githubusercontent.com/39466970/62072447-4a705580-b204-11e9-91f5-a4476fc9343e.png)

There's a 'Load More' button which is new!  And when I press it, instead of showing the BM Ticket Reimbursement Milestone I was expecting..  now, Kay's Milestone appears twice?
But I only see it one in My Milestones.

**Comment by arbreton** [comment]
Fixed now! https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33, just needs some donations before accepting completion again it should be good to go
