### ISSUE TITLE
To be tested: the co ownership doesnt always work on the front end ?

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#919]
I think the duties of a campaign owner should be able to be split between two addresses that can sign in. Because of the constant nature of needing to stay engaged (for milestone approvals, allocating funds, etc) things are always missed for days when it's just one person, but if it could be covered by shifts I think it would benefit many people's use cases for campaigns.

**Comment by arbreton** [comment]
I totally agree!, would be great to have some help on those tasks!

**Comment by GriffGreen** [comment]
:-D THIS IS AWESOME!

**Comment by arbreton** [comment]
To be worked, UI for co-owners display on the campaign

**Comment by papermache** [comment]
Can @arbreton finish this issue?

**Comment by arbreton** [comment]
hide the owner part pending
