### ISSUE TITLE
The detail of cancelled milestones is stuck on loading

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#92]
The detail page for a canceled milestone never loads.
<img width="764" alt="screen shot 2017-10-18 at 18 29 34" src="https://user-images.githubusercontent.com/7974813/31730469-51636d36-b432-11e7-9cdb-c7c72e97ee16.png">
<img width="875" alt="screen shot 2017-10-18 at 18 29 38" src="https://user-images.githubusercontent.com/7974813/31730472-53884f50-b432-11e7-9e7b-2ac940df1765.png">

**Comment by caseyhelbling** [comment]
I'm guessing this issue is fixed with 

https://github.com/Giveth/giveth-dapp/commit/4807ad9bdf01f7c896ee8ef691b4c89866967d96

**Comment by vsimetka** [comment]
Indeed
