### ISSUE TITLE
Milestone Stuck on Needs Review - no reviewer?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#920]
Delegated funds yesterday to this [Milestone](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d3f3e8a9182643880364635)., Kirch marked complete and it's just spinning in "Needs Review" status?

![image](https://user-images.githubusercontent.com/39466970/62133482-78a57200-b2a4-11e9-8141-5daeb449e7d6.png)

**Comment by arbreton** [comment]
It should be working now!, there was a critical error on feathers, related to #922 , #923
