### ISSUE TITLE
Paying multiple line items in DAI gives error that ETH amount is incorrect

### ISSUE THREAD

**Issue by Jeff-Emmett** [Giveth/giveth-dapp#921]
Issue type: **Error**
Something went wrong with the Milestone creation. Is your wallet unlocked?

**TransactionLink:**
undefinedtx/undefined => {
  "name": "Forbidden",
  "message": "Total amount in ether is incorrect",
  "code": 403,
  "className": "forbidden",
  "errors": {}
}

**Comment by arbreton** [comment]
Hello @Jeff-Emmett, would you have the milestone link? thank you!

**Comment by Jeff-Emmett** [comment]
Unfortunately I do not, I am waiting on the milestone to be accepted by
Griff before I can access the link - it is at the moment invisible to me.
Will keep trying!

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d40ac85efd9e46550e5ad42


I rejected this... cause there was this error

**Comment by arbreton** [comment]
Coming from a draft seem to doesn't update the token on items

**Comment by aminlatifi** [comment]
In dapp code items amounts are converted from wei to eth, fixed to 18 digit fraction one by one, then are summed up to obtain and store maxAmount. When it wants to send maxAmount to feather, dapp converts it to wei.
I guess these conversions and limited precision of fraction amounts is a candidate of cause.
I asked @arbreton to give me database record.

**Comment by arbreton** [comment]
Milestone debug info here

[milestoneraw.log](https://github.com/Giveth/giveth-dapp/files/3687988/milestoneraw.log)

**Comment by aminlatifi** [comment]
After trying various scenarios still unsuccessful in recreating the error. @Jeff-Emmett Would you please describe more your scenario? When was the error happened? e.g. Creating Milestone, Donating or withdrawing? any more information would be helpful.
