### ISSUE TITLE
Error Canceling Milestone

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#926]
Issue type: **Error**
Something went wrong with the transaction.

**TransactionLink:**
https://rinkeby.etherscan.io/tx/undefined => {}

From 'My Milestones' I hit the Cancel button on[ this duplicate Milestone](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d3646511038ff0d20b0b5c5) (the correct one has been funded and disbursed, yay!). (I'm the Campaign Manager - NOT the Milestone creator).

![image](https://user-images.githubusercontent.com/39466970/62419203-adf8e980-b62f-11e9-8d94-006fe287cdd6.png)

Tried again from the Milestone header..  Error again.

**Comment by arbreton** [comment]
@Danibelle did the milestone got canceled?
