### ISSUE TITLE
Proposed milestone links are hidden from user

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#932]
In #921 Jeff had trouble finding the link to his milestone that he just proposed... that should be front and center for the proposer... maybe there should be a pop up telling him the link and explaining that the milestone needs to be approved by the campaign manager

**Comment by aminlatifi** [comment]
Toast shows link to proposed milestone now.
<img width="1267" alt="Screen Shot 2019-10-15 at 18 20 55" src="https://user-images.githubusercontent.com/5684607/66844108-9d8fb400-ef7a-11e9-8445-e76820f7ede7.png">

**Comment by arbreton** [comment]
Thats so awesome @aminlatifi !, a great way to fix this issue
