### ISSUE TITLE
Zooming in on the picture breaks

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#933]
jeff showed us during the dapp if you zoom in on the picture it breaks our proposed milestone

**Comment by aminlatifi** [comment]
@Jeff-Emmett Can you tell here more about details? How does it happen?
On which OS, Browser and how do you zoom? 
I cannot reproduce it on my own. I used chrome and firefox on Mac. Zooming by trackpad gesture or control+scroll does not reproduce problem!
