### ISSUE TITLE
Disable 3% to Campaign keeps reverting to Enabled on Milestone Proposal

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#935]
I disabled the 3% then entered the amount in DAI - when Milestone is proposed it reverts back and takes the 3% anyways!

![image](https://user-images.githubusercontent.com/39466970/62562144-7065ad80-b835-11e9-87e0-f63d238ade8e.png)

![image](https://user-images.githubusercontent.com/39466970/62562162-7a87ac00-b835-11e9-944b-be282d3f5a5c.png)

![image](https://user-images.githubusercontent.com/39466970/62562224-98eda780-b835-11e9-8258-9764d196e84d.png)

![image](https://user-images.githubusercontent.com/39466970/62562283-a86cf080-b835-11e9-9b94-b405661141b6.png)

Milestone: https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d49b6cc045b566d7b2bfd65

**Comment by arbreton** [comment]
It is now fixed on beta!

**Comment by arbreton** [comment]
Rinkeby server might be down due to an update it should come back on asap, we are working on it
