### ISSUE TITLE
DAPP - Change of Campaign Ownership isn't working

### ISSUE THREAD

**Issue by mroberts10** [Giveth/giveth-dapp#937]
I tried to change the campaign owner from myself to Andre and Dani, but when I select Andre in the drop down it immediately crashes.  Before I select Andre it appears to be working fine.

<img width="1254" alt="Screen Shot 2019-08-07 at 9 08 36 PM" src="https://user-images.githubusercontent.com/4000911/62667878-b61a9700-b957-11e9-9de3-aab8c7374bb0.png">

![Screen Shot 2019-08-07 at 8.57.11 PM.png](https://images.zenhubusercontent.com/5bec4b6a2b1a577465f948ed/1d9763f8-b634-4b51-8738-18440bbf3274)

**Comment by mroberts10** [comment]
I tried clearing the cache and restarting the browser and still no luck.

**Comment by arbreton** [comment]
Let me take a look at this situation Michael! , i will get back asap

**Comment by arbreton** [comment]
It should be fixed Michael!, now on beta
