### ISSUE TITLE
Eternally Pending Transactions on the Art Car Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#938]
Four Donations at the bottom of this [Campaign](https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7):

![image](https://user-images.githubusercontent.com/39466970/62674035-79e63700-b955-11e9-89a1-fd83b9731e4d.png)

**Comment by arbreton** [comment]
It is fixed !
