### ISSUE TITLE
DAC, Campaign and Milestone title and description is limited to 10 characters

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#94]
- [ ] The Title of DAC/Campaign and Milestone should not be limited to 10 characters (to allow generic names like Health, Education, Children...)
- [ ] The description limit could remain but it needs to be clearly market as mandatory field.

**Comment by ojones** [comment]
This requires 2 changes:
1) change field validation character limit to 3 for both title and description.
2) display obvious indicator such as "*" to indicate the description is required.

**Comment by satyavh** [comment]
.2 The best UI pattern is to mark fields as optional, not required. See Nielson studies.

**Comment by vsimetka** [comment]
Currently set to 3.
