### ISSUE TITLE
Cannot cancel a Milestone

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#942]
[This milestone](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5d3646511038ff0d20b0b5c5) needs to be cancelled - I've tried from various points but it just wont go away!

![image](https://user-images.githubusercontent.com/39466970/62817685-b057b980-baef-11e9-9dd7-4d9859b1af34.png)

**Comment by arbreton** [comment]
Hello @Danibelle,
If you try Ctrl + Shift + J on your browser do you see any errors?,

keep me posted thank you!

**Comment by arbreton** [comment]
@Danibelle, please try to Reject the completion and then try to cancel see if that helps with the Smart contract, keep me posted

**Comment by arbreton** [comment]
It should be canceled now @Danibelle !
