### ISSUE TITLE
scope creep - donating to a dac

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#944]
Why are we adding new functionalities to the dapp when there are so many things to be solved? 
Do we not risk to cause to create errors during a stage that we decided to call the maintenance mode of the dapp? 
If this is really necessary to have at this point - plz fix the typo 'proyects' -> 'projects'

![image](https://user-images.githubusercontent.com/6533925/62876277-e336c300-bd24-11e9-9a38-5e54a5a9d72b.png)

**Comment by krrisis** [comment]
Would be good to not have this on by default or making it possible to change this when editing your Milestone (which is what I meant with scope creep, making this editable is more work for you). Ofc I succeeded in missing to disable this when creating my own Milestone, so will now cancel my Milestone and hope funds will flow back to my Campaign. 

![image](https://user-images.githubusercontent.com/6533925/62884236-51d04c80-bd36-11e9-897e-6d05f8204541.png)

**Comment by arbreton** [comment]
@krrisis!, we will hotfix the typo, 

The edit milestone it's a known issue, it's actually disabled!, but in the edit page will always show on

If you don't see this while viewing your milestone:
<img width="1439" alt="Screen Shot 2019-08-12 at 10 42 57 AM" src="https://user-images.githubusercontent.com/12836187/62885583-14e06780-bcee-11e9-8d7c-c265bd7fd816.png">

You don't have to worry, you are not delegating funds to any campaign
