### ISSUE TITLE
Incorrect "amount donated" listed on milestone

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#946]
i could see how this might say 600 (amt paid), or 900 (total donated), or 300 (amt committed not yet paid out)... but there's really no way it makes sense that it's 750. 
<img width="875" alt="Screen Shot 2019-08-12 at 10 54 58 PM" src="https://user-images.githubusercontent.com/38163206/62918475-91a62c80-bd54-11e9-82ef-fabda3adfc63.png"> 
https://beta.giveth.io/campaigns/5b37e5caa239ac21b383d4dd/milestones/5d3640d51038ff0d20b0b5c3

**Comment by arbreton** [comment]
This is a very strange case!, after analyzing what seem to happened is the following:

-450 donated
-150 donated
-rinkeby went down
-150 (on the dapp) was donate but failed!, but the counter on the database increased!
-150 donated (outside the dapp) success but not logged on the database at that time
-rinkeby went backup

I applied a fix for this specific case, also we are working in a long term solution atm so all this scenarios doesn't happen when some external resource fails (i.e rinkeby faucet)

**Comment by arbreton** [comment]
Stability of Rinkeby faucet prioritization and to be worked data sync refactor
