### ISSUE TITLE
slider max broken

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#948]
i slide the slider all the way to the max available of that donation to delegate it away and then some rounding shit must happen because i'm left with .0035 DAI when THE WHOLE POINT WAS TO EMPTY THAT DONATION TO ZERO 

<img width="945" alt="Screen Shot 2019-08-13 at 1 22 01 AM" src="https://user-images.githubusercontent.com/38163206/62926171-ccb25b00-bd68-11e9-8959-9cabb66ad80c.png">

**Comment by aminlatifi** [comment]
Maybe this issue be solved after https://github.com/Giveth/giveth-dapp/pull/1012 be merged.

**Comment by aminlatifi** [comment]
@lorelei1 Is problem still exists?

**Comment by arbreton** [comment]
Testing on new release

**Comment by aminlatifi** [comment]
@arbreton can we close this issue?

**Comment by GriffGreen** [comment]
The slider is still weird :-( there are issues with the conversions :-( 

It would be nice to limit the precision at the conversion

**Comment by GriffGreen** [comment]
Delegation refactor will help
