### ISSUE TITLE
Error on completing a Milestone 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#951]
When I hit the 'complete' Milestone on [this one](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d51833d7d4ad11d4adb5f7c) I got the metamask transaction but at the same time immediately an error message. 

So I first signed the transaction (bcs I know that when that one goes through most of the times we're good anyways). 
After signing and clicking away the error the 'complete' button was still there. 

The recording below shows that the error keeps on popping up every time I hit the 'complete' button, refreshing the page or going into the Milestone doesn't do anything. After I stopped the recording it changed to 'needs review'. So in the backend all is fine but the frontend is lagging here. Hope this explanation and vid helps.

![euro](https://user-images.githubusercontent.com/6533925/62951558-771e9280-bdea-11e9-83b4-1e5dbf306f06.gif)

**Comment by arbreton** [comment]
Definitely something happening there!, we would do some in depth testing on this scenarios maybe replicating the common stack and burning man campaigns on develop.giveth.io to be working with lots of data see what happens

Loved the GIF animation @krrisis!, it's so useful ! +1
It's just so clean in the same thread
Will investigate asap

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/68541535-e5f19480-03b5-11ea-8c59-fd53d10323cf.png)
As you seen error returned from smart contract is empty! so, there would be a problem either in the smart contract, or web3. We will be lucky if the work we done on upgrading web3 driver from beta version solve this issue.
