### ISSUE TITLE
dani's delegation is un-delegateable

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#952]
Tried it several times - yesterday and today! I always get this message after putting in the amount, milestone name, and clicking delegate. 
<img width="819" alt="Screen Shot 2019-08-13 at 12 45 11 PM" src="https://user-images.githubusercontent.com/38163206/62972196-58a79f80-bdc8-11e9-8aaa-372aba455306.png"> 
It's the delegation of 470.283456055238132458 to the Unicorn DAC in Dani's name.

**Comment by arbreton** [comment]
Is this still happening @lorelei1? I don’t think there could be an easy fix for this one, if you press Command + Option + J you see an error?

**Comment by lorelei1** [comment]
still behaves the same for me

**Comment by lorelei1** [comment]
<img width="1365" alt="Screen Shot 2019-09-09 at 10 56 29 AM" src="https://user-images.githubusercontent.com/38163206/64554565-87923200-d2f0-11e9-9e7c-498d4a7756c0.png">

**Comment by GriffGreen** [comment]
there seems to be a process that moves the pledges in the database but its no syncing with the smart contracts properly so when there is low connectivity, it will deplete the pledge on the smart contract ... 

We need to actually look at the pledge... the pledge is probably wrong...

**Comment by GriffGreen** [comment]
@lorelei1 can you check this again?

**Comment by lorelei1** [comment]
Works now! When I came to it just now it was split into 150, 150, and 170 (if i remember right it was a single 470 dai delegation before). And I was able to successfully delegate all 3.
