### ISSUE TITLE
3% to a DAC needs some language clean up

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#953]
"DAC to delegate *" should be "DAC to donate to" 

<img width="465" alt="Screen Shot 2019-08-13 at 12 55 44 PM" src="https://user-images.githubusercontent.com/38163206/62972818-c0121f00-bdc9-11e9-8065-db755903e478.png">

**Comment by lorelei1** [comment]
also, this is SO CUTE, but should probably change *projects
<img width="522" alt="Screen Shot 2019-08-13 at 12 58 26 PM" src="https://user-images.githubusercontent.com/38163206/62973026-2434e300-bdca-11e9-8189-d9783cb2b2db.png">

**Comment by arbreton** [comment]
Completely agree! definitely the idea was to test and review this implementation, those changes will improve readability for sure

Definitely fixing the typo, thank your that @lorelei1! will hotfix asap
