### ISSUE TITLE
can't commit donation

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#957]
<img width="1002" alt="Screen Shot 2019-08-15 at 11 34 34 AM" src="https://user-images.githubusercontent.com/38163206/63117478-c4b50f80-bf50-11e9-8d58-d802f1e1ab05.png">

**Comment by lorelei1** [comment]
ooh weird... the plot thickens. Now 2 donations are marked as committed even though I KNOW they aren't - each of my tries were met with error code and no metamask prompt, and griff hasn't even been on the dapp in the past 10 minutes since i made the delegation in his name... 
<img width="638" alt="Screen Shot 2019-08-15 at 11 38 01 AM" src="https://user-images.githubusercontent.com/38163206/63117809-60468000-bf51-11e9-9c76-0566f7c9cf4a.png">

**Comment by arbreton** [comment]
@lorelei1 are all the delegetions OK now?
