### ISSUE TITLE
No search or filtering option for DACs and Campaigns

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#96]
There is no option to search or filter through the list of DACs and Campaigns.

**Comment by satyavh** [comment]
Because there are no DACs and Campaigns yet to search for :-)

**Comment by vsimetka** [comment]
There are no real ones, but there is currently 17 DACs and 22 Campaigns on Ropsten. Yes sure right now may not be an issue to search those but it has been a request from one of the external testers (sorry at this point I don't remember who).

**Comment by satyavh** [comment]
It is on our roadmap (there's even a commented search bar in the Dapp). Will move to icebox

**Comment by aminlatifi** [comment]
We have just a few number of DACs. Campaigns' number is more, but still can surf without searching. Maybe we need to create a search capability for milestones in future.
