### ISSUE TITLE
Range Slider does not work well for small values

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#960]
Max donation is 0.0001 ETH. In this case range slider is somehow useless and misleading.
![image](https://user-images.githubusercontent.com/5684607/63334226-3675ca80-c350-11e9-9ec5-35cbcd5e75f3.png)

or this:

![image](https://user-images.githubusercontent.com/5684607/63334198-1f36dd00-c350-11e9-8b09-133b3761d323.png)

**Comment by aminlatifi** [comment]
I changed range component value from eth to wei and it's ok now. 
More validation and coordination with number input is required.

**Comment by GriffGreen** [comment]
:-D thx Amin!

**Comment by aminlatifi** [comment]
> I changed range component to wei (it was eth) and it's ok now.
> More validation and coordination with number input is required.

This approach makes some problem when using tokens! I went another way. 
But it would be better if it can be handled by wei or other number which represent finest fraction of a token.
