### ISSUE TITLE
Check #956 implementation colors

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#965]
#956 implementation has darker colors, we could check to leave them white to keep consistency

**Comment by aminlatifi** [comment]
The preview of current state can be seen in this milestone Donations section.

**Comment by aminlatifi** [comment]
Double clicking on collapse icon makes some inconsistency in UI. Maybe changing Icon by css (not react state) would be a solution. It's better if this this bug be fixed when working on this issue and not create another one.
