### ISSUE TITLE
Error on Propose Milestone

### ISSUE THREAD

**Issue by JulietEA** [Giveth/giveth-dapp#968]
When I click the "propose milestone" button on a campaign I receive an error message:
![Screen Shot 2019-08-27 at 3 27 13 PM](https://user-images.githubusercontent.com/54636748/63873475-4b241500-c985-11e9-958d-cf3e1a172119.png)

**Comment by arbreton** [comment]
Investigating more in depth this situation

**Comment by arbreton** [comment]
Confirmed now fully working on beta.giveth.io
