### ISSUE TITLE
Retry on Cancelling Stuck Milestone (Issue 942)

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#976]
This is for: https://github.com/Giveth/giveth-dapp/issues/942

Issue type: **Error**
Something went wrong with the transaction.

**TransactionLink:**
https://rinkeby.etherscan.io/tx/undefined => {
  "code": -32000,
  "message": "gas required exceeds allowance (7000000) or always failing transaction"
}

**Comment by arbreton** [comment]
Solved @ #942
