### ISSUE TITLE
Amin's milestone has a donation in limbo

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#977]
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5d1af6c4bd45530e23ad8546

**Comment by arbreton** [comment]
It seems to be that the homeTx didn't went through and failed, that could have cause this behavior, it should not be showing pending th, i will take a look further into this
https://etherscan.io/tx/0x28c8698412f1d39b5b5d796ed3a0a2816e4d9cec6cb2fd2ff921c1af8eb827f6

**Comment by arbreton** [comment]
Delegated funds from DAPP campaign to fund milestone
