### ISSUE TITLE
Canceling the discofish milestone 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#978]
There is a lot of crossing our fingers that this will work... i took some screen shots to record the data... putting it here just in case there is a problem...

<img width="839" alt="Screen Shot 2019-09-09 at 10 40 49 AM" src="https://user-images.githubusercontent.com/14945613/64554898-1d2dc180-d2f1-11e9-914c-44dc8108343d.png">
<img width="882" alt="Screen Shot 2019-09-09 at 10 40 35 AM" src="https://user-images.githubusercontent.com/14945613/64554900-1dc65800-d2f1-11e9-9aad-e0060ec17cbf.png">

**Comment by arbreton** [comment]
Looks like it's all good! https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7, there are funds on that campaign that were used for that purpose i think

**Comment by arbreton** [comment]
@GriffGreen

**Comment by GriffGreen** [comment]
https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7/milestones/5d1ba874bd45530e23ad86ed

^^^ This milestone took money out of the campaign and its not registered correctly in the campaign cause now the milestone is canceled

**Comment by GriffGreen** [comment]
https://beta.giveth.io/delegations is correct... but the Campaign is not

**Comment by GriffGreen** [comment]
https://github.com/Giveth/feathers-giveth/issues/146#issuecomment-587423687 worth checking

**Comment by aminlatifi** [comment]
> [Giveth/feathers-giveth#146 (comment)](https://github.com/Giveth/feathers-giveth/issues/146#issuecomment-587423687) worth checking

There are 502.34 no paid SAI token are stuck in milestone!

**Comment by aminlatifi** [comment]
Milestone
    "pluginAddress" : "0xf37e78484A7b640F2556b12e96dD423260e0257c",

**Comment by GriffGreen** [comment]
Some real weird stuff is happening in this campaign see the campaign balance at the bottom... the balance is higher than the total donations... thats an issue with something... especially since some money got paid out!
<img width="543" alt="Screen Shot 2020-02-24 at 5 14 44 PM" src="https://user-images.githubusercontent.com/14945613/75205958-14f40200-572a-11ea-994b-fae60b77ef14.png">

**Comment by GriffGreen** [comment]
ok so i was paid out 1050 here: https://etherscan.io/tx/0x27038c27c6770c79d36852de951f188fc6356174d2c179132aaca1ed32b9b502
But the milestone shows i was paid out 1564.16? 
<img width="955" alt="Screen Shot 2020-02-25 at 11 09 49 AM" src="https://user-images.githubusercontent.com/14945613/75279448-7c5c9100-57c0-11ea-888e-d63279c9715f.png">

**Comment by aminlatifi** [comment]
> ok so i was paid out 1050 here: https://etherscan.io/tx/0x27038c27c6770c79d36852de951f188fc6356174d2c179132aaca1ed32b9b502
> But the milestone shows i was paid out 1564.16?
> <img alt="Screen Shot 2020-02-25 at 11 09 49 AM" width="955" src="https://user-images.githubusercontent.com/14945613/75279448-7c5c9100-57c0-11ea-888e-d63279c9715f.png">

There is another collect action happened. Corresponding transaction in rinkeby is:
https://rinkeby.etherscan.io/tx/0x31008943b5575c004d8e095aa3e509026c62514970c62c87d5f42101b1d69105

**Comment by GriffGreen** [comment]
> 
the corresponding tx on mainnet will be made by this address at the same time an it will give the info you need to match it up
https://etherscan.io/address/0xa27243046e16ee596d19ff3091719160527e469a

**Comment by aminlatifi** [comment]
> > 
> 
> the corresponding tx on mainnet will be made by this address at the same time an it will give the info you need to match it up
> https://etherscan.io/address/0xa27243046e16ee596d19ff3091719160527e469a

Unfortunately I couldn't find the corresponding tx on mainnet! 
I chased for a transaction which its amount matches 464.16 or one of the tiny donations which makes up that amount (e.g.  64.16)!

**Comment by aminlatifi** [comment]
> > > 
> > 
> > 
> > the corresponding tx on mainnet will be made by this address at the same time an it will give the info you need to match it up
> > https://etherscan.io/address/0xa27243046e16ee596d19ff3091719160527e469a
> 
> Unfortunately I couldn't find the corresponding tx on mainnet!
> I chased for a transaction which its amount matches 464.16 or one of the tiny donations which makes up that amount (e.g. 64.16)!

@GriffGreen Even automatic code we use to find the home tx hash doesn't find anything!

**Comment by GriffGreen** [comment]
Tried to cancel this milestone: https://rinkeby.etherscan.io/address/0xf37e78484a7b640f2556b12e96dd423260e0257c#readProxyContract

it ended up not moving the pledges tho :-(

**Comment by GriffGreen** [comment]
there was a burn event on rinkeby but no pay event on mainnet... investigate

**Comment by horus2021** [comment]
It seems that this issue is basically the same as #1323, so we should close this one. We have this in our issue list as a closed issue in the future.
