### ISSUE TITLE
Back Button from Profile View (anyones) goes to 'Edit My Profile'

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#979]
When I click on any users link to view their profile from anywhere
![image](https://user-images.githubusercontent.com/39466970/64561970-b4e6dc00-d300-11e9-8f52-a7e717363bf9.png)
Then hit back
![image](https://user-images.githubusercontent.com/39466970/64561997-ca5c0600-d300-11e9-9fd8-dd0ff7815ea1.png)
I end up here 
![image](https://user-images.githubusercontent.com/39466970/64562053-f37c9680-d300-11e9-9d2f-4a0917589fe2.png)

Instead of back where I was before.

**Comment by arbreton** [comment]
Would definitely look into this one @Danibelle!
