### ISSUE TITLE
Milestone is Paid - Why Can't I Archive it?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#980]
How do I make this Milestone go to Paid/Completed and out of my Active view?  I would expect an Archive button on this one: https://beta.giveth.io/campaigns/5d1cfe6bbd45530e23ad87d0/milestones/5d5184157d4ad11d4adb5f81

![image](https://user-images.githubusercontent.com/39466970/64576299-cd6ceb80-d32c-11e9-87da-250df340d13d.png)

**Comment by aminlatifi** [comment]
Archive functionality has been just for uncapped milestones till now. Probably archiving should be implemented for capped one too.
Related to: https://github.com/Giveth/giveth-dapp/issues/961

**Comment by aminlatifi** [comment]
@Danibelle @GriffGreen do you have any idea how should it be. I mean archive functionality for capped milestones. Here are some points:
* Should user be able to donate to an archived capped milestone?
* Can user cancel archived capped milestone?

**Comment by GriffGreen** [comment]
Dani's goal here is to clear her own my milestones page..

Should user be able to donate to an archived capped milestone?

1. Not thru the UI, the  milestone should be marked "completed" and all the buttons should go away.

Can user cancel archived capped milestone?

2. The Milestone Manager and Campaign Manager should be able to archive a capped milestone... but man the list of buttons is getting LONG!

**Comment by aminlatifi** [comment]
> How do I make this Milestone go to Paid/Completed and out of my Active view? I would expect an Archive button on this one: https://beta.giveth.io/campaigns/5d1cfe6bbd45530e23ad87d0/milestones/5d5184157d4ad11d4adb5f81
> 
> ![image](https://user-images.githubusercontent.com/39466970/64576299-cd6ceb80-d32c-11e9-87da-250df340d13d.png)

@Danibelle the problem is the milestone is not fully funded and some fraction is remained. By recent fixes to donation slice you would donate remained.
