### ISSUE TITLE
Delegating from a specific contribution - amounts don't match

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#981]
This is me testing some fringe scenarios..

I delegated the full amount available using the slider from Samir's donation to the DECENTRAL Campaign, and the Milestone accepted only the exact amount requested, but the donated amount shows that full amount.. I expect that the difference should be returned and shown as available to be delegated?

![image](https://user-images.githubusercontent.com/39466970/64579883-4ffba800-d339-11e9-8837-2fc69ac858de.png)

the difference did return to my delegations at bottom in Samir's name.. 
![image](https://user-images.githubusercontent.com/39466970/64579946-7a4d6580-d339-11e9-9243-b7a0ec9d234d.png)

**Comment by arbreton** [comment]
It seems that it let you delegate more than it should have allowed @Danibelle ?

**Comment by arbreton** [comment]
could be related to #1002

**Comment by arbreton** [comment]
Testing on new release

**Comment by aminlatifi** [comment]
@Danibelle is it fixed?
