### ISSUE TITLE
Did Images Stop Working for Milestone Headers?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#982]
I selected a picture but it never popped up for me to crop/select area..

![image](https://user-images.githubusercontent.com/39466970/64583082-99052980-d344-11e9-8f8d-a54de6700fc2.png)

Now that I look at the DECENTRAL Campaign, none of the recent Milestones have a custom image - how boring! They all have the Giveth G.

![image](https://user-images.githubusercontent.com/39466970/64583192-f8633980-d344-11e9-965d-726fcd501306.png)

**Comment by arbreton** [comment]
Thank you for identifying this Dani!, we refactored the whole class on milestones and indeed pictures were not working properly, i released a hotfix on beta, it should working now !
