### ISSUE TITLE
Disburse/Collect status update shows just one of payments

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#985]
When milestone payment consists of donation of multiple giver or tokens, multiple PAID donation is created behind the scene. So, one status update should be added per PAID donation.
Currently is not as expected and just the first status update (conversation technically) is accepted by feather.

![image](https://user-images.githubusercontent.com/5684607/64764571-92023500-d557-11e9-9816-e9cc374446d3.png)

![image](https://user-images.githubusercontent.com/5684607/64764589-9c243380-d557-11e9-9437-2b3d6f359a82.png)

**Comment by arbreton** [comment]
A new feature needs to be implemented for this to be fixed @aminlatifi ?

**Comment by aminlatifi** [comment]
No it doesn't need any feature I believe. Logically this should work.

**Comment by aminlatifi** [comment]
We need to debug and search around. Maybe a technical issue causes this and not our code.
