### ISSUE TITLE
Not found page capability for DACs and campaign

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#986]
URLs `/dacs/<id>` and `/campaign/<id>` does not support not found. Entering random id for these two shows inappropriate pages.
![image](https://user-images.githubusercontent.com/5684607/64845865-7878f000-d620-11e9-9c93-c4ffe2ff842a.png)

![image](https://user-images.githubusercontent.com/5684607/64845881-829aee80-d620-11e9-93a2-a8e77f454174.png)

**Comment by arbreton** [comment]
Great observation @aminlatifi!, would be awesome to add a proper 404 landing page
