### ISSUE TITLE
No addresses that start with a letter can be co-owners of a campaign?!?!?!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#990]
Loie's name isnt there, and no one who's address startes with 0xa 0xb 0xc 0xd 0xe 0xf are listed either... 
<img width="823" alt="Screen Shot 2019-09-19 at 11 53 24 AM" src="https://user-images.githubusercontent.com/14945613/65272655-52e25f80-dad4-11e9-9baf-8ae274254749.png">

**Comment by arbreton** [comment]
This is very strange!, found the root cause seems to be on the users query from all across the app there is a default limit to 25 and now we have over 25 campaignOwners on the whitelist, i just updated it to 100, all names should show up now, pushing commit now
