### ISSUE TITLE
toggle buttons on milestones are very slow

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#991]
The "Give 3 percent to a DAC" toggle and the "Disable Reviewer" toggle both take a looooong time to register that you have clicked them... we're talking over a minute

**Comment by arbreton** [comment]
This is a known issue @lorelei1!, actually they seem to stop responding due to conflicting cache, try deleting your browser cookies and they should be working properly again, investigating the root cause

**Comment by lorelei1** [comment]
it fixed it temporarily... but it got slow again pretty soon! after one or 2 more milestones
