### ISSUE TITLE
Donations on campaigns should be grouped by donator!

### ISSUE THREAD

**Issue by arbreton** [Giveth/giveth-dapp#994]
Right now names repeat multiple times making it spammy and difficult to find transparency, i think with @aminlatifi solution for the donations trace and the plus sign, we can show all the users donations on that campaign and make it more cleaner 
<img width="1066" alt="Screen Shot 2019-09-08 at 1 59 25 AM" src="https://user-images.githubusercontent.com/12836187/65341724-45f76600-dbd1-11e9-86fc-3d29748c3824.png">

**Comment by markoprljic** [comment]
Is this related to this? https://github.com/Giveth/giveth-dapp/issues/1339

**Comment by aminlatifi** [comment]
> Is this related to this? #1339

Yes it's has been implemented there.
