### ISSUE TITLE
Old bug! Still goin

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#995]
If you don't click which currency you're raising funds in before inputting the amount - the conversion gets stuck and you end up with something nonsensical like this: 
<img width="820" alt="Screen Shot 2019-09-20 at 4 06 43 PM" src="https://user-images.githubusercontent.com/38163206/65363449-ded1b580-dbc0-11e9-9d94-f3708e18d78f.png">
Raising 3500 DAI, aka 16 DAI ... 🤦‍♀️

**Comment by arbreton** [comment]
I see the problem now @lorelei1 !, will fix it, what seem to be happening is compatibility when correctly selecting the currency to update all the fields, since we refactored completely this class very recently this situations might be arising and we need to correct them asap
